### PR TITLE
Filter item relations

### PR DESCRIPTION
**Pull request by bernatvadell**
Implements feature #5185 

This is a proposal, I would need someone from the team to validate it and tell me if the chosen path is correct. 

I have created a new property called "filter" in the "useItems" hook, at first it reused "filters" but the structure of the object itself limited the filtering possibilities. 

Related #6760

### CODE REVIEW

**Comment by bernatvadell** [comment]
Scenario:

We have the following collections:
- Category: List of categories
- Subcategory: List of subcategories related to Category
- Product: Composed of a Title field, and two many to one relationships: Category and Subcategory

The objective is that through the interface, the elements shown in Subcategory are filtered by the selected category. 

How to filter subcategories:
1. Go to product data model
2. Select subcategory field to edit
3. Go to tab "Interface"
4. Select Many to One interface
5. You will see that there is a new field "filter" 
6. Write this:
```
{
    "category": "$VALUE(category)"
}
```
image

If you now access the Products maintenance, you will see that the "Subcategory" elements are filtered by the selected Category element. 

A video how to work:
https://user-images.githubusercontent.com/17298604/126874990-eba68841-75bd-4e2c-b40d-fa6207869397.mp4

Current limitations:
- When you change an element, it is not cleaned automatically, in this case, subcategory. 
- Only implemented in m2o

**Comment by rijkvanzanten** [comment]
> I have created a new property called "filter" in the "useItems" hook, at first it reused "filters" but the structure of the object itself limited the filtering possibilities.

Instead of adding a secondary filter object in here, we should update the app filters structure to match the API filter rule syntax. Having that as the main standard for working with filters is way cleaner 👍🏻

**Comment by bernatvadell** [comment]
> > I have created a new property called "filter" in the "useItems" hook, at first it reused "filters" but the structure of the object itself limited the filtering possibilities.
> 
> Instead of adding a secondary filter object in here, we should update the app filters structure to match the API filter rule syntax. Having that as the main standard for working with filters is way cleaner 👍🏻

Done!

Now filter config on the same example is:

```json
[
    {
        "field": "category",
        "operator": "eq",
        "value": "$VALUE(category)"
    }
]
```

**Comment by bernatvadell** [comment]
I have had a problem with the fork and it has been reset, I have had to recreate the PRs.

Follow #7080

**Pull request closed without merging**
