### PR TITLE
Require value for  dropdown choices

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

Makes the `value` of dropdown choices required
Applied to the following interfaces:
- select-dropdown
- select-multiple-dropdown
- select-multiple-checkbox
- select-radio
- displays/labels
- operations/request
- interfaces/select-color
- modules/settings/routes/translation-strings/translation-strings-drawer

image

Note: I have made the text/label required too. leaving that empty wont break the app as such but you can question the logic of having empty labels to choose from which use different values.

Fixes ENG-89

## Type of Change

- [ ] Bugfix
- [X] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by licitdev — APPROVED** [review]
LGTM. 👍

**Comment by Nitwel** [comment]
Found a few more spots where we might want to add this:

displays/formatted-value
displays/labels
interfaces/select-color
modules/settings/routes/translation-strings/translation-strings-drawer
operations/request
panels/metric

Other than that, looking good. 👍

**Comment by br41nslug** [comment]
I have implemented most of the ones Nitwel mentioned except `displays/formatted-value` and `panels/metric` because it didnt instantly make sense to me in these situations.

**Review by azrikahar — COMMENTED** [review]
I've just recalled that we should probably add this for Field Name Translations and Collection Name Translations to prevent unintentional empty records there 👍

However for Collection Name Translations, maybe "singular" and "plural" doesn't need to be required 🤔

- Field: https://github.com/directus/directus/blob/0154878f2746809896738a1cfb73edcaa3dceace/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-field.vue#L34-L64

- Collection: 
https://github.com/directus/directus/blob/0154878f2746809896738a1cfb73edcaa3dceace/api/src/database/system-data/fields/collections.yaml#L60-L99

**Review by Nitwel — APPROVED** [review]

**Review by azrikahar — APPROVED** [review]

**Pull request merged**
