### PR TITLE
Fix flows editing existing operations

### LINKED ISSUE #13702: Data Flows: cannot edit an operation
### Describe the Bug

Hi,

first of all - long awaited feature with DataFlows - awesome!

But, once the flow is created, and an operation is added, it looks like, we cannot edit the operation, but we can replace it entirely i.e. Log in to console cannot be updated, after clicking Edit icon, the dialog with list of operations appears.

### To Reproduce

1. Create a flow
2. Add a operation - `Log in to console` and save it
3. Try to edit `Log in to console` operation - the list of operations appears, not the operation itself

### Errors Shown

None

### What version of Directus are you using?

9.12.0

### What version of Node.js are you using?

Docker

### What database are you using?

Docker

### What browser are you using?

Safari

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by rijkvanzanten**
## Description

Resolves a bug that would prevent operations from being edited.

Fixes #13702

## Type of Change

- [x] Bugfix
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included[^1]
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

[^1]: N/A. Don't have app component tests yet

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Still not quite happy

**Comment by rijkvanzanten** [comment]
Happy now

**Comment by rijkvanzanten** [comment]
Still not happy enough

**Comment by rijkvanzanten** [comment]
It's happy on my end now, just waiting for @licitdev to confirm

**Review by licitdev — APPROVED** [review]
Works great!!

**Comment by vanling** [comment]
Awesome :D just recreated docker file and editting works <3  thanks guys

**Pull request merged**
