### PR TITLE
Allow to pass custom URL for user invitation

### PR DESCRIPTION
**Pull request by andriusign**
Allow to pass custom URL for invitation to enable verification of user's email on custom Frond-End page (other than Directus Admin page).

### CODE REVIEW

**Review by rijkvanzanten — COMMENTED** [review]
Can you also update the docs to match this? 🙂

**Comment by andriusign** [comment]
Yes, of course, suggestions appreciated.

**Comment by rijkvanzanten** [comment]
We just have to update https://github.com/directus/directus/blob/main/docs/reference/api/rest/users.md#invite-a-new-user to show the new `invite_url` request attribute. You mirror the `reset_url` one 👍🏻  https://github.com/directus/directus/blob/main/docs/reference/api/rest/authentication.md#request-password-reset

**Comment by andriusign** [comment]
Updated.

**Review by rijkvanzanten — APPROVED** [review]
LGTM!

**Comment by andriusign** [comment]
Not sure if my fix helped. I am still getting error.
Using latest RC version (36).

Screenshot from 2021-02-12 16-21-36

**Comment by rijkvanzanten** [comment]
You're correct.. We forgot to allow `invite_url` in here:

https://github.com/directus/directus/pull/3972/files#diff-0176428ef7a174e439af8b342a7791b2efb2fb843cb94b5010caf31e7e24577eR205

**Comment by andriusign** [comment]
Not sure where specifically it has be enabled, but if you point me, I can gladly do the fix.

**Comment by rijkvanzanten** [comment]
This object:

https://github.com/andriusign/directus/blob/6583ea7c6807aaf6c8e8501c28769deefb433b4f/api/src/controllers/users.ts#L203-L206

controls the validation. We should add a `invite_url` key in there that is a `Joi.string().uri()` (not required)

**Comment by andriusign** [comment]
Thanks. https://github.com/directus/directus/pull/4028

**Pull request merged**
