### PR TITLE
Allow selection of image transformation in the WYSIWYG interface

### LINKED ISSUE #11901: Embeded WYSIWYG images not showing but show in direct browser call
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Image's are not showing inside the editor, but can be accessed using the same embedded code externally via browser with static image token appended.

### To Reproduce

Upload an image into the wysiwyg editor

### Errors Shown

_No response_

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

14.19.0

### What database are you using?

MYSQL

### What browser are you using?

Safari

### What operating system are you using?

Linux 5.4.0-84-generic

### How are you deploying Directus?

VPS

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Fixes #11901

### Allow all transformations

https://user-images.githubusercontent.com/26413686/172598622-07097adb-c423-41fc-8888-7a5ffd8bc258.mov

### Limit transformations to presets below

https://user-images.githubusercontent.com/26413686/172598728-80ad86a8-6567-4b3e-9616-c21012d8ff77.mov

### Disable transformations

https://user-images.githubusercontent.com/26413686/172598795-d9488fcd-f82c-470c-a212-1d2fe20793fe.mov

## Type of Change

- [x] Bugfix
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
When using "all", instead of showing/hiding width/height fields, could we keep them on the form and instead disable them? Ideally with showing the actual width/height of the selected preset. That's a little less jarring than having the form jump around 🙂

**Comment by licitdev** [comment]
@rijkvanzanten Agreed and updated! The input shouldn't jump in position after interaction. Thanks!

https://user-images.githubusercontent.com/26413686/172648228-686aff9f-ecf5-4ea8-9a21-38facbcfefac.mov

**Comment by rijkvanzanten** [comment]
One more thing in there @licitdev, could we pull in the actual configuration for the preset and preview the width/height of the preview in those disabled inputs? 🙂

**Comment by licitdev** [comment]
@rijkvanzanten That a good idea!

https://user-images.githubusercontent.com/26413686/172665511-9dc15b0b-0e46-4dac-a7ba-46d299f0dc48.mov

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
