### PR TITLE
Patch Tuesday 🐸 

### PR DESCRIPTION
**Pull request by rijkvanzanten**
# Updates

## `monorepo-root`

```
@types/jest                         29.2.3  →    29.2.4
@types/lodash                     4.14.189  →  4.14.191
@types/uuid                          8.3.4  →     9.0.0
@typescript-eslint/eslint-plugin    5.43.0  →    5.47.0
@typescript-eslint/parser           5.43.0  →    5.47.0
axios                                1.1.3  →     1.2.1
eslint                              8.27.0  →    8.30.0
eslint-plugin-jest                 ^27.1.5  →    27.1.7
eslint-plugin-vue                    9.7.0  →     9.8.0
lint-staged                         13.0.3  →    13.1.0
listr2                               4.0.5  →     5.0.6
prettier                             2.7.1  →     2.8.1
supertest                            6.3.1  →     6.3.3
typescript                           4.9.3  →     4.9.4
```

#### :x: Can't be updated at this time

- `globby ^11.0.4 → 13.1.3` ESM only

---

## `directus`

```
@aws-sdk/client-ses      3.211.0  →   3.235.0
@keyv/redis                2.5.3  →     2.5.4
@ngneat/falso              6.3.0  →     6.3.2
@types/async              3.2.15  →    3.2.16
@types/cors               2.8.12  →    2.8.13
@types/deep-diff           1.0.1  →     1.0.2
@types/express           4.17.14  →   4.17.15
@types/lodash           4.14.189  →  4.14.191
@types/marked              4.0.7  →     4.0.8
@types/node              18.11.9  →  18.11.17
@types/nodemailer          6.4.6  →     6.4.7
@types/object-hash         2.2.1  →     3.0.2
@types/sanitize-html       2.6.2  →     2.8.0
@types/uuid                8.3.4  →     9.0.0
@vitest/coverage-c8       0.25.2  →    0.26.2
axios                      1.1.3  →     1.2.1
exif-reader                1.0.3  →     1.1.0
fs-extra                  10.1.0  →    11.1.0
helmet                     6.0.0  →     6.0.1
jsonwebtoken               8.5.1  →     9.0.0
knex-mock-client           1.8.4  →    1.11.0
liquidjs                  9.42.1  →    10.3.3
marked                     4.2.2  →     4.2.4
openapi3-ts                3.1.1  →     3.1.2
openid-client              5.3.0  →     5.3.1
pino                       8.7.0  →     8.8.0
pino-http                  8.2.1  →     8.3.0
rollup                     3.3.0  →     3.7.5
sanitize-html              2.7.3  →     2.8.1
sharp                     0.31.2  →    0.31.3
sqlite3                    5.1.2  →     5.1.4
stream-json                1.7.4  →     1.7.5
tedious                   15.1.1  →    15.1.2
typescript                 4.9.3  →     4.9.4
vitest                    0.25.2  →    0.26.2
vm2                       3.9.11  →    3.9.13
```

#### :x: Can't be updated at this time

- `@directus/format-title ^9.15.0 → 10.0.0` ESM only
- `camelcase ^6.2.0 → 7.0.0` ESM only
- `chalk ^4.1.1 → 5.1.2` ESM only
- `execa ^5.1.1 → 6.1.0` ESM only
- `globby ^11.0.4 → 13.1.2` ESM only
- `inquirer ^8.2.4 → 9.1.4` ESM only
- `@types/inquirer 8.2.1 → 9.0.2` Needs inquirer@9
- `nanoid ^3.1.23 → 4.0.0` ESM only
- `ora ^5.4.0 → 6.1.2` ESM only
- `strip-bom-stream ^4.0.0 → 5.0.0` ESM only

---

## `@directus/app`

```
@babel/core                     7.20.2  →    7.20.5
@fullcalendar/core              5.11.3  →     6.0.1
@fullcalendar/daygrid           5.11.3  →     6.0.1
@fullcalendar/interaction       5.11.3  →     6.0.1
@fullcalendar/list              5.11.3  →     6.0.1
@fullcalendar/timegrid          5.11.3  →     6.0.1
@storybook/addon-actions        6.5.13  →    6.5.15
@storybook/addon-backgrounds    6.5.13  →    6.5.15
@storybook/addon-docs           6.5.13  →    6.5.15
@storybook/addon-essentials     6.5.13  →    6.5.15
@storybook/addon-links          6.5.13  →    6.5.15
@storybook/addon-measure        6.5.13  →    6.5.15
@storybook/addon-outline        6.5.13  →    6.5.15
@storybook/builder-vite          0.2.5  →     0.2.6
@storybook/client-api           6.5.13  →    6.5.15
@storybook/client-logger        6.5.13  →    6.5.15
@storybook/vue3                 6.5.13  →    6.5.15
@tinymce/tinymce-vue             4.0.5  →     5.0.0
@types/lodash                 4.14.189  →  4.14.191
@types/marked                    4.0.7  →     4.0.8
@vitejs/plugin-vue               3.2.0  →     4.0.0
@vue/test-utils                  2.2.3  →     2.2.6
axios                            1.1.3  →     1.2.1
codemirror                      5.64.0  →     6.0.1
cropperjs                       1.5.12  →    1.5.13
happy-dom                        7.7.0  →     8.1.1
highlight.js                    11.6.0  →    11.7.0
mapbox-gl                       1.13.2  →    2.11.1
maplibre-gl                     1.15.3  →     2.4.0
markdown-it-anchor               8.6.5  →     8.6.6
marked                           4.2.2  →     4.2.4
pinia                           2.0.23  →    2.0.28
sass                            1.56.1  →    1.57.1
tinymce                         5.10.2  →     6.3.1
typescript                       4.9.3  →     4.9.4
vite                             3.2.4  →     4.0.3
vitest                          0.25.2  →    0.26.2
```

#### :x: Can't be updated at this time

- `codemirror 5.64.0 → 6.0.1` Looks like codemirror 6 is a total rewrite and restructure of codemirror, meaning that the
  migration path is effectively the same as replacing codemirror completely. This should be done as a separate effort.
- `tinymce 5.10.2 → 6.2.0` Similar to codemirror, this is a bigger rewrite that affects our use of tinymce. We should do
  this in a separate sprint
- `@tinymce/tinymce-vue 4.0.5 → 5.0.0` Wraps tinymce 5, so see above
- `mapbox-gl 1.13.2 → 2.11.0` https://github.com/directus/directus/issues/16185
- `maplibre-gl 1.15.3 → 2.4.0` https://github.com/directus/directus/issues/16185

---

#### :x: Can't be updated at this time

- `inquirer ^8.1.2 → ^9.1.4` ESM only

---

## `extensions-sdk`

```
@rollup/plugin-commonjs   23.0.2  →   24.0.0
@rollup/plugin-json        5.0.1  →    6.0.0
@rollup/plugin-replace     5.0.1  →    5.0.2
@rollup/plugin-terser      0.1.0  →    0.2.1
@vitest/coverage-c8       0.25.2  →   0.26.2
concurrently               7.5.0  →    7.6.0
esbuild                  0.15.14  →  0.16.10
fs-extra                  10.1.0  →   11.1.0
rollup                     3.3.0  →    3.7.5
typescript                 4.9.3  →    4.9.4
vitest                    0.25.2  →   0.26.2
```

#### :x: Can't be updated at this time

- `chalk ^4.1.1 → 5.1.2` ESM only
- `execa ^5.1.1 → 6.1.0` ESM only
- `ora ^5.4.0 → 6.1.2` ESM only
- `inquirer ^8.1.2 → ^9.1.4` ESM only
- `@types/inquirer 8.2.1 → 9.0.3` Matches inquirer 9

---

## `@directus/schema`

```
typescript  4.8.4  →  4.9.4
```

---

## `@directus/shared`

```
@types/express    4.17.14  →   4.17.15
@types/lodash    4.14.189  →  4.14.191
@vue/test-utils     2.2.3  →     2.2.6
axios               1.1.3  →     1.2.1
concurrently        7.5.0  →     7.6.0
fs-extra           10.1.0  →    11.1.0
pino                8.7.0  →     8.8.0
typescript          4.9.3  →     4.9.4
vitest             0.25.2  →    0.26.2
```

---

## `@directus/storage`

```
@vitest/coverage-c8  0.25.3  →  0.26.2
typescript            4.9.3  →   4.9.4
vitest               0.25.3  →  0.26.2
```

---

## `@directus/storage-driver-azure`

```
@ngneat/falso         6.3.0  →   6.3.2
@vitest/coverage-c8  0.25.3  →  0.26.2
typescript            4.9.3  →   4.9.4
vitest               0.25.3  →  0.26.2
```

---

## `@directus/storage-driver-cloudinary`

```
@ngneat/falso         6.3.0  →   6.3.2
@vitest/coverage-c8  0.25.3  →  0.26.2
typescript            4.9.3  →   4.9.4
vitest               0.25.3  →  0.26.2
```

---

## `@directus/storage-driver-gcs`

```
@google-cloud/storage   6.7.0  →   6.8.0
@ngneat/falso           6.3.0  →   6.3.2
@vitest/coverage-c8    0.25.3  →  0.26.2
typescript              4.9.3  →   4.9.4
vitest                 0.25.3  →  0.26.2
```

---

## `@directus/storage-driver-local`

```
@ngneat/falso         6.3.0  →   6.3.2
@vitest/coverage-c8  0.25.3  →  0.26.2
typescript            4.9.3  →   4.9.4
vitest               0.25.3  →  0.26.2
```

---

## `@directus/storage-driver-s3`

```
@aws-sdk/client-s3    3.224.0  →  3.235.0
@aws-sdk/lib-storage  3.234.0  →  3.235.0
@ngneat/falso           6.3.0  →    6.3.2
@vitest/coverage-c8    0.25.3  →   0.26.2
typescript              4.9.3  →    4.9.4
vitest                 0.25.3  →   0.26.2
```

---

## `@directus/utils`

```
@ngneat/falso         6.3.0  →   6.3.2
@vitest/coverage-c8  0.25.3  →  0.26.2
typescript            4.9.3  →   4.9.4
vitest               0.25.3  →  0.26.2
```

### CODE REVIEW

**Comment by abdonrd** [comment]
Please, take this:
- https://github.com/directus/directus/pull/16796

**Review by azrikahar — APPROVED** [review]
LGTM! Not seeing any issues with the major bumps, as it looks like we're not really utilizing any of their features with breaking changes in our codebase. 👍

Added the following changes during the review:

- Removed `@types/pino` from api and shared

    `pino` was upgraded from v6 to v8 in #16052, but `pino` v7 onwards started to ship it's own types, so `@types/pino` has been deprecated (and wasn't really used anymore).
    
    - Ref to v7 release note: https://github.com/pinojs/pino/releases/tag/v7.0.0
    - Deprecation notice in `@types/pino` package page: https://www.npmjs.com/package/@types/pino

- Drive by removed `declare module 'grant'` definition in `api/src/types/shims.d.ts`

    `grant` package was removed in #8660, so there is no need for this declaration anymore.

**Comment by paescuj** [comment]
@azrikahar Good catch! 👍 Now that you are already in the "clean-up mode", would you mind merging in #16576? 😄

**Comment by azrikahar** [comment]
> @azrikahar Good catch! 👍 Now that you are already in the "clean-up mode", would you mind merging in (or taking over) #16576? 😄 (Additionally removes `@types/pino-http` & `pino-http`-shim)

@paescuj Great call! Looks like there's a lot of overlap indeed, and I've merged it into this PR. 🙌

Turns out `@types/pino-http` was moved (and updated) into `pino-http` via pinojs/pino-http#178, but `@types/pino-http` doesn't have the same deprecation notice (presumably since it's still technically valid for older versions) so I thought it's still updated. 😄

**Comment by paescuj** [comment]
> @paescuj Great call! Looks like there's a lot of overlap indeed, and I've merged it into this PR. 🙌

Thanks, much appreciated ❤️ 

> Turns out `@types/pino-http` was moved (and updated) into `pino-http` via [pinojs/pino-http#178](https://github.com/pinojs/pino-http/pull/178), but `@types/pino-http` doesn't have the same deprecation notice (presumably since it's still technically valid for older versions) so I thought it's still updated. 😄

Yup, this one is not that obvious... 😃

**Pull request merged**
