### PR TITLE
The Great TypeScript Modernization Program Season 3 Episode 6: The Big One

### LINKED ISSUE #15190: Build API to ESM instead of CJS
The API is currently building to CJS, which has a couple of downsides:

1. More and more packages are becoming ESM only, which in turn means we either have to start replacing them with internal code (like https://github.com/directus/directus/pull/14840), or have to stick behind on a previous version that's CJS compatible (with all security implications that comes with that). 
2. The app (through vite) is already building to ESM, which means we're in a split-codebase (App in ESM, API in CJS), which in turn means that the tooling is also split (vitest app, jest api for example). This is starting to become more of a maintenance problem, as it also means we have to keep the CJS vs ESM discussion in mind in things like the shared libraries.

Before, we weren't able to move to ESM as TypeScript's support wasn't quite there yet. However, since TS 4.7, it _should_ now have decent support to transpile to ESM instead of CJS, which in theory should mean we should be able to flip the switch.

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Attempt 4 at upgrading the codebase to adhere to the same TS Config rules and ESM goodness. This is the _big one_. The last change in the API to get it up to speed with the newer packages it switching the module system to ESM..

Big shoutout to the whole team for preparing and helping out on this, and apologies for the inevitable merge conflicts

Fixes https://github.com/directus/directus/issues/15190

- [x] Revert changes to `.github/workflows/blackbox-main.yml`

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Opening this up for initial review while I keep updating some of the last tweaks and test fixes 👍🏻

**Review by licitdev — APPROVED** [review]
gif

**Review by br41nslug — APPROVED** [review]
https://user-images.githubusercontent.com/9389634/229868821-669e5e7a-cf99-4a6d-8d8e-8e2d151f0d61.mp4

**Review by paescuj — APPROVED** [review]
giphy

**Pull request merged**
