### PR TITLE
Fix rehydrating cache after flow save

### PR DESCRIPTION
**Pull request by Nitwel**
@paescuj made a last minute change to that PR thinking there was some leftover code that I missed but we need to rehydrate the flows store after saving a flow in order to refect the changes made on said flow into the cache.

Fixes #17785

### CODE REVIEW

**Comment by paescuj** [comment]
Sorry, should have described my customization more precisely...
The problem when calling `rehydrate` is that changes in the front-end are reset after saving:

https://user-images.githubusercontent.com/5363448/225866914-f5b56602-df29-4ca8-9f82-17b225161a7f.mp4

I'm honestly not quite sure why this is the case (the store update itself works).
But I thought that we don't even need to update the flow store after changes within the flow, because the flows are freshly fetched every time anyway now.

**Comment by Nitwel** [comment]
Good catch, I forgot that we also need to refetch the local flow data. Updated it now.

**Comment by paescuj** [comment]
> Good catch, I forgot that we also need to refetch the local flow data. Updated it now.

Ah yeah, right 👍

**Review by paescuj — APPROVED** [review]

**Review by licitdev — APPROVED** [review]
Fixes the "missing" changes upon save. 👍

**Pull request merged**
