### PR TITLE
Implement OIDC provider in order to integrate directus admin users with other services!

### PR DESCRIPTION
**Pull request by caffeaun**
# TODO

- [ ] Add `node-oidc-provider` and implemented the example with directus authentication service.

- [ ] Integrate directus session with OIDC provider.

- [ ] Reuse Login UI and Implement Consent Prompt follow directus theme.

### CODE REVIEW

**Comment by aidenfoxx** [comment]
You should investigate integrating this as an auth-package, the PR for which is here: https://github.com/directus/directus/pull/6942

It allows integration with alternative login providers via a common interface: https://github.com/directus/directus/pull/6942/files#diff-3e323571c96a81e686a1de01e67effe78b45a1e76486568d0e186ab7eda888e2

**Comment by rijkvanzanten** [comment]
@aidenfoxx Problem: this doesn't fit in the interface, as it relies on a custom endpoint flow (similar to oAuth)

@aunsuwijak why was this closed? Is this a draft, or not supposed to be merged through?

**Comment by aunsuwijak** [comment]
@rijkvanzanten I submit the PR to the `main` branch by mistake, so I closed this one until I make sure my idea is validated. Thanks.

**Comment by rijkvanzanten** [comment]
Ohhh hold up a second @aidenfoxx this is turning Directus into the OIDC _provider_, not a _user_ 😄 It wouldn't go through the new auth modular setup, as it's not a way to login, but a way to let other services login _using_ directus as the OIDC provider

**Comment by aidenfoxx** [comment]
That's a use case I didn't even consider. 😅

**Pull request closed without merging**
