### PR TITLE
Remove stray console log

### PR DESCRIPTION
**Pull request by aidenfoxx**

### CODE REVIEW

**Comment by paescuj** [comment]
We could add a rule to eslint to prevent this in the future. E.g. something like this:
```js
rules: {
    // allow console and debugger only in development
    'no-console': process.env.NODE_ENV === 'production' ? 2 : 0,
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
  },
```

**Review by nickrum — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
@paescuj That should already be enabled 🤔 

https://github.com/directus/directus/blob/706f4af68b51b1f27e2b1f0889558f84968f7536/.eslintrc.js#L2-L5

I'll try reversing the logic to be "when not development" instead of "production", maybe the env flag in GH Actions CI is not production

**Comment by paescuj** [comment]
> @paescuj That should already be enabled 🤔

Ah, forgot about that... 😄

> I'll try reversing the logic to be "when not development" instead of "production", maybe the env flag in GH Actions CI is not production

Great, this makes more sense!

**Comment by paescuj** [comment]
@rijkvanzanten Aaand its already working 😄 (https://github.com/directus/directus/runs/2822866865)

**Pull request merged**
