### PR TITLE
Fixes _offset=0 in deep filters

### LINKED ISSUE #18370: `Deep` query with `_offset: 0` causes INTERNAL_SERVER_ERROR
### Describe the Bug

When using the API to fetch one-to-many nested records, I want to get the data per page. 
However, I got
```
{
	"errors": [
		{
			"message": "undefined is not iterable (cannot read property Symbol(Symbol.iterator))",
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR"
			}
		}
	]
}
```
My query body as below, `sub_products` is the one-to-many alias field.
```
{
	"query": {
		"fields": [
			"name",
			"sub_products.name"
		],
		"filter": {
			"name": {
				"_eq": "AHB-001"
			}
		},
		"deep": {
			"sub_products": {
				"_limit": 15,
				"_offset": 0
			}
		}
	}
}
```
The server error log shows:
```
[22:11:31.024] ERROR: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    err: {
      "type": "TypeError",
      "message": "undefined is not iterable (cannot read property Symbol(Symbol.iterator))",
      "stack":
          TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
              at parse (file:///home/homerh/directus15/api/src/utils/sanitize-query.ts:184:38)
              at parse (file:///home/homerh/directus15/api/src/utils/sanitize-query.ts:187:5)
              at sanitizeDeep (file:///home/homerh/directus15/api/src/utils/sanitize-query.ts:169:2)
              at sanitizeQuery (file:///home/homerh/directus15/api/src/utils/sanitize-query.ts:61:16)
              at file:///home/homerh/directus15/api/src/middleware/validate-batch.ts:26:25
              at file:///home/homerh/directus15/api/src/utils/async-handler.ts:4:18
              at Layer.handle [as handle_request] (/home/homerh/directus15/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
              at next (/home/homerh/directus15/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
              at file:///home/homerh/directus15/api/src/middleware/collection-exists.ts:29:9
              at file:///home/homerh/directus15/api/src/utils/async-handler.ts:4:18
    }
[22:11:31] SEARCH /items/app02_category 500 9ms
```

The workaround is 
* never use `_offset: 0`, because `_offset: <not 0>` is working.
* or, use `_page: 1` instead.

### To Reproduce

* Install latest version of Directus. 
* Create 2 collections A and B, A references B with a one-to-many field.
* Populate A and B with some data.
* Query B's records from A with 
```
                "deep": {
			"B_records": {
				"_offset": 0
			}
		}
```

### Directus Version

v10.0.0 (3ff71cc)

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by br41nslug**
The cause here was an incorrect truthyness check. This condition was working for both top-level `offset` and `deep._offset` using the query bracket format because those values get stringified resulting in `if ('0') { /* is true */ }` but when using JSON notation these values get properly parsed as numbers thus failing the check.
```js
if (rawQuery['offset']) {
	query.offset = sanitizeOffset(rawQuery['offset']);
}
```

I've updated the existing tests to catch this issue.

Fixes #18370

### CODE REVIEW

**Review by paescuj — APPROVED** [review]
LGTM!

**Review by licitdev — COMMENTED** [review]
Should this same fix be applied to `rawQuery['page']` as well? 
It also accepts an integer which could be `0`.

**Comment by paescuj** [comment]
> Should this same fix be applied to `rawQuery['page']` as well? It also accepts an integer which could be `0`.

But `page=0` isn't a thing, is it? 🤔

**Comment by licitdev** [comment]
Oh yes... 🙈 `page` is 1-indexed and does nothing when it's `0`. Thanks for clarifying!

https://github.com/directus/directus/blob/bf10c943c811867d516e51f017ab275efb8b5a10/api/src/utils/apply-query.ts#L49-L51

**Review by licitdev — APPROVED** [review]

**Pull request merged**
