### PR TITLE
Add support for grouping and aggregation (sum/avg/min/max/count)

### LINKED ISSUE #5551: GraphQL filtering problem
1. Create Article with 2 translations: 

Снимок экрана 2021-05-08 в 17 11 43

2. Filter articles with GraphQL:

```gql
fragment Article on article {
  id
  ...
  translations(filter: { languages_code: { code: { _eq: $lang } } }) {  # Getting filtered translations
    slug
    content # Filter added to filter large content for specified lang only
    ...
  }
  all_translations: translations { # Getting all translations without filter
    slug
    languages_code {
      code
      name
    }
  }
}

query getArticle($slug: String, $lang: String = "ru") {
  article(filter: { translations: { slug: { _eq: $slug } } }) { # This filter does not affect the problem
    ...Article
  }
}
```

3. Problem: `all_translations` contains filtered items (but it should not have `translations` filter):
Снимок экрана 2021-05-08 в 17 19 43

PS: Without a filter at translations:

Снимок экрана 2021-05-08 в 17 15 57

---

### Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: Linux 5.4.0-66-generic
Node: 10.19.0

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Adds two new query params: `group` and `aggregate`. Allows for grouping output and retrieving aggregate information, like sum/avg/min/max/count.

Example:

Get average sale price per category and total revenue over 2020:

```json
{
  "filter": {
    "_and": [
      { "date": { "_gte": "2020-01-01T00:00:00Z" }},
      { "date": { "_lte": "2021-12-31T23:59:59Z" }}
    ]
  },
  "group": "category",
  "aggregate": {
    "avg": "amount",
    "sum": "amount"
  }
}
```

---

Left to do:

- [x] Add `any` type
- [x] Add `alias` functionality (fixes https://github.com/directus/directus/issues/5551)
- [x] Add `*_func` support for datetime
- [x] GraphQL aggregation query
- [x]  change groupBy to input type that has the fields as an enum
- [ ] ~~Deprecate `meta` in favor of `aggregate[count]`~~
- [ ] Add `*_func` support for input filters
- [x] Docs, docs, docs
- [ ] Update SDK / CLI types / methods

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/directus/discussions/2989

**Comment by rijkvanzanten** [comment]
@TheAzack9 @iksent @WoLfulus Any thoughts around the ideal structure for aggregate functionality in GraphQL? We obv can't change the output type based on arguments used, so I was thinking we could add something like:

```GraphQL
query {
  <collection>_aggregate {
    avg {
      <field>
    }
    sum {
      <field>
    }
    # etc
  }
}
```

however, that doesn't really work with `group` (`GROUP BY`) 🤔 

Should we do something similar with a `_group` sub-type? 

```graphql
query {
  <collection>_grouped(field: String!) {
     fieldValue # < this is ugly
     avg {
      <field>
    }
    sum {
      <field>
    }
    # etc
  }
}
```

**Comment by tarwin** [comment]
Not sure how this handles `count` when not aggregating? Is there an example you could post?

For example, getting a `total_count` and `filtered_count` when doing a simple query on a collection, limited by `limit` or `filter`, but with total count in collection, and total returned from query. I guess total returned from query could be simply looking at the array length, so it is less needed than the `total_count`.

Without this I'm not sure how paging can be done ie nav between pages for a blog or any other list of items.

**Comment by ziguilp** [comment]
Nice!!!  
Will support for VIEW and MATERIALIZED VIEW ?

**Comment by rijkvanzanten** [comment]
@ziguilp No, that's a separate feature 👍🏻

**Comment by ziguilp** [comment]
> @ziguilp No, that's a separate feature 👍🏻

Got

**Comment by iksent** [comment]
Really waiting for this feature  🙏

**Comment by rijkvanzanten** [comment]
> Really waiting for this feature  🙏

Almost there! Any thoughts on the graphql structure for getting aggregates?

**Comment by supermx1** [comment]
Very needed feature. You guys are great!!!!. I upvote this

**Comment by tspvivek** [comment]
@rijkvanzanten 
Great, This is what i needed for report generations. Will group field will be single or multiple?

**Comment by rijkvanzanten** [comment]
@tspvivek What do you mean by "Will group field will be single or multiple?" ?

**Comment by tspvivek** [comment]
Yes, Thats what i mean.  :)

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/directus/pull/8009

**Pull request closed without merging**
