### PR TITLE
Show unique related value

### PR DESCRIPTION
**Pull request by pierre-H**
See https://github.com/directus/directus/discussions/5957

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@pierre-H Should we make that number 1 configurable? I could also imagine it would be very useful to render the first 3 inline, and then start using the popover, or even do something like: `Item A, Item B, and 5 others` where the "and 5 others" bit is the popover 🤔

**Comment by pierre-H** [comment]
@rijkvanzanten : good idea !

Should it be a parameter in the collection, the field or globally ?
I admit that I don't have the necessary knowledge of the Directus code to add such a configuration 😃

**Comment by rijkvanzanten** [comment]
It would be another option to the Display, which can be added in this array:

https://github.com/directus/directus/blob/60c18d612549ecba423a111631cdea250f709ec3/app/src/displays/related-values/index.ts#L38-L44

That will make it show up in the display configuration, and will allow you to read the value through a prop of the field name, just like this `template` usage:

https://github.com/directus/directus/blob/60c18d612549ecba423a111631cdea250f709ec3/app/src/displays/related-values/related-values.vue#L60-L63

🙂

**Comment by azrikahar** [comment]
> Should we make that number 1 configurable? I could also imagine it would be very useful to render the first 3 inline, and then start using the popover, or even do something like: `Item A, Item B, and 5 others` where the "and 5 others" bit is the popover 🤔

I think unfortunately this notice is a bit late, but perhaps #9597 was addressing the same interaction if I'm not mistaken?

**Comment by pierre-H** [comment]
@azrikahar : you're right !
Closing in favor of https://github.com/directus/directus/pull/9597.

**Pull request closed without merging**
