### PR TITLE
Make headline visible if title is short

### LINKED ISSUE #4101: Headline not visible if title is short
image

### PR DESCRIPTION
**Pull request by YannickMol**
Fixes #4101

### CODE REVIEW

**Comment by YannickMol** [comment]
As I had to remove the `position:absolute` to get this working, the vertical alignment of the title is no longer consistent on pages with and without headline, see below screenshots. Is this acceptable?

image

image

**Comment by rijkvanzanten** [comment]
No, we'll have to keep that as is... Otherwise it'll look pretty funky on the scrolled state.

**Comment by rijkvanzanten** [comment]
Be careful with this one 😁 There's a lot of sneaky things going on between responsive, scroll-state, and the title slot being filled with a render-template on certain item detail pages

**Comment by YannickMol** [comment]
What do you think of this? 
image

**Comment by rijkvanzanten** [comment]
> What do you think of this?

love it

**Review by rijkvanzanten — APPROVED** [review]
LGTM

**Pull request merged**
