### PR TITLE
[WIP] Strict types

### PR DESCRIPTION
**Pull request by laszlokorte**
This is still work in progress.

For now I converted all `==` and `!=` comparisons to `===` and `!==` and I added a `castType` function to `UIManager` that is used in the `settings.get` method.

Currently the usage of strict comparison introduced some bugs. I plan to add some type conversions to the various backbone models like `UIModel` and `Entries` model. For example to convert the `this.get('read')` in `MessageModel.getUnreadCount` to a number.

While going through the the files I noticed that often default values of the UI options are both encoded in the `serialize` method (https://github.com/directus/directus/blob/development/app/core-ui/datetime.js#L95) as well as in the `variables` objects (https://github.com/directus/directus/blob/development/app/core-ui/datetime.js#L114).

I think this could be unified by moving all default values to the variables object and get rid of all the `has()` tests in the serialize method.

### CODE REVIEW

**Comment by WellingGuzman** [comment]
This is awesome, Thanks @laszlokorte can't wait to see this done.

**Comment by benhaynes** [comment]
Whoa – this is amazing @laszlokorte, thank you so much for this PR!

Will this help with [our other ticket](https://github.com/directus/directus/issues/395) regarding stricter typing?

I really like the idea of of moving (core) UI default values to a variable object... would help clean that up a lot. @WellingGuzman what do you think?

**Comment by laszlokorte** [comment]
I just noticed that the API delivers some data as strings even though it's obviously typed as integers. For example the permission table columns (`allow_`*) and the messages (eg the `read` value).

I think such values should be encoded as the correct datatype on the server. But I am really not comfortable with the Zend framework so I could need some help there. I saw that the `AclAwareTableGateway` has an `parseRecordValuesByMysqlType` method that takes care of it but the `DirectusMessagesTableGateway` does not make use of it.

**Comment by WellingGuzman** [comment]
> I really like the idea of of moving (core) UI default values to a variable object... would help clean that up a lot. @WellingGuzman what do you think?

I like the idea, this will a good implementation, and we will always be sure that its default value will be the fallback at the end.

> I think such values should be encoded as the correct datatype on the server. But I am really not comfortable with the Zend framework so I could need some help there.

@laszlokorte I can help you with any question you may have.

> I saw that the AclAwareTableGateway has an parseRecordValuesByMysqlType method that takes care of it but the DirectusMessagesTableGateway does not make use of it.

True, We've plan on moving `parseRecordValuesByMysqlType` to the schema-specific class, so it can be accessible anywhere.

**Comment by benhaynes** [comment]
Question: With the UI defaults moved to the variable object, doesn't that mean that the UI doesn't have defaults until the user saves the UI Options? For example:

I create a new column/UI (WYSIWYG) and **do not view or save the UI options** because I'm fine with the defaults. Now when I see that UI on an edit page it won't have the default values (eg: height = 500px) because no options are saved in the DB. 

Isn't that correct?

**Comment by laszlokorte** [comment]
@benhaynes the `settings.get` method that is used to access the options is overridden to use the default value if not other value is provided:
https://github.com/directus/directus/blob/master/app/core/UIManager.js#L310-L324

**Comment by benhaynes** [comment]
Ahh, thanks for enlightening me... this is so much simpler! Really awesome @laszlokorte – thanks again!

**Comment by laszlokorte** [comment]
I am currently looking for number values that are (imo falsely) provided as strings by the API.

So far:

/api/1/tables/[table]/preferences:
- id
- user

/api/1/messages/rows:
- rows.from
- rows.read
- rows.recipients (imo should be array instead of csv string)

/api/1/tables/[table]:
- count

/api/1/groups/[id]:
- id
- restrict_to_ip_whitelist
- show_activity 
- show_messages
- show_users
- show_files

/api/1/privileges/[id]:
- id
- group_id
- nav_listed
- status_id
- allow_view
- allow_edit
-  allow_delte
- allow_alter

/api/1/privileges/[group-id]/[table-name]:
- id
- group_id
- nav_listed
- status_id
- allow_view
- allow_add
- allow_edit
- allow_delete
- allow_alter

**Comment by WellingGuzman** [comment]
> These need to be fixed for the strict equality checks to work. I think converting those values on the client side is not a good solution. The server should already provide them in the right way.

@laszlokorte True, that's our main subject to solve regards the strict mode on mysql as well, everything should be handle by the server and the server should provide the right type.

The client should trust that the value are in its expected type, before being skeptical and cast it.

**Comment by laszlokorte** [comment]
I currently do not have time to work on the server side part of this.
But as soon as the API returns correctly typed values (especially for messages read count and privileges) this could be merged.

**Comment by benhaynes** [comment]
@WellingGuzman is this something you can do? Are you thinking 6.3 or 6.4?

**Comment by WellingGuzman** [comment]
it sounds right @laszlokorte.

@benhaynes I'm thinking 6.3.x. this is part of strict mode issue #395.

**Comment by benhaynes** [comment]
OK, great!

**Comment by WellingGuzman** [comment]
I squash and merged this already here (https://github.com/directus/directus/commit/0dcef772b9528d272f09788c60341c3beb509366), but I don't know if it possible to mark this PR as merged.

**Comment by laszlokorte** [comment]
I just force pushed your squashed commit to my strict-types branch in order to mark this PR as merged.

**Comment by WellingGuzman** [comment]
Still shows that you closed it. It will have been better to be mark  as merged. seems like we rejected it. 😞

**Comment by laszlokorte** [comment]
For me it looks like this:

bildschirmfoto 2016-08-22 um 22 06 49

**Comment by WellingGuzman** [comment]
For me it looks like this: 
screen shot 2016-08-22 at 4 06 34 pm

**Comment by laszlokorte** [comment]
doesn't matter
had contributed 😄

**Comment by WellingGuzman** [comment]
haha, If you're cool, we're cool. 😃

**Comment by laszlokorte** [comment]
I am not sure if it's related to my changes but I just noticed two issues:

1. The privileges settings (/settings/permissions/1) do not show the correct privileges 
2. In the table settings the "Required" checkbox for columns that are NOT NULL in the DB is no longer force checked/disabled (UI: TextField, VARCHAR). Not sure if this is the supposed behavior.

**Comment by WellingGuzman** [comment]
Thanks for reporting this:

> The privileges settings (/settings/permissions/1) do not show the correct privileges

I  checked and the API is returning string instead of numbers.

> In the table settings the "Required" checkbox for columns that are NOT NULL in the DB is no longer force checked/disabled (UI: TextField, VARCHAR). Not sure if this is the supposed behavior.

Probably still related, I'm going to look at this one.

**Comment by benhaynes** [comment]
Thanks @laszlokorte – we're rolling out `6.3` and any testing is more than appreciated!

**Comment by WellingGuzman** [comment]
@laszlokorte the permissions should be fix now.

> In the table settings the "Required" checkbox for columns that are NOT NULL in the DB is no longer force checked/disabled (UI: TextField, VARCHAR). Not sure if this is the supposed behavior.

I checked and yes, that's the expected behavior.

**Comment by laszlokorte** [comment]
Currently I am on the dev branch. Should I switch to master to get the latest fixes?

**Comment by laszlokorte** [comment]
@WellingGuzman for Textarea/TEXT the required checkbox *is* force checked if the column is NOT NULL in the database. And for some other UI/Datatypes as well. For me that looks inconsistent and should be unified.

**Comment by benhaynes** [comment]
Ahh, that's not how it should be. If a TEXT column is NOT NULL, then you should still be able to choose if it's required or not. If not, then it would save an empty string: `""`

The same applies to other datatypes.

**Comment by WellingGuzman** [comment]
> Currently I am on the dev branch. Should I switch to master to get the latest fixes?

No, we fixes on development too. I just pushed those commits.

> @WellingGuzman for Textarea/TEXT the required checkbox is force checked if the column is NOT NULL in the database. And for some other UI/Datatypes as well. For me that looks inconsistent and should be unified.

I'm going through all the UIs to check this out.

**Pull request closed without merging**
