### PR TITLE
Move module setup to Project Settings

### PR DESCRIPTION
**Pull request by rijkvanzanten**
And add a custom interface to setup the module bar in a _way_ nicer way.

https://user-images.githubusercontent.com/9141017/133163942-7f0c023a-775b-4fe5-95fc-1ad44c138c86.mov

- Move module bar setup to project settings
- Add system modules interface to dnd configure module bar
- Cleanup order
- Crucially important typo
- Add ability to add custom links

### CODE REVIEW

**Comment by danieljwestman** [comment]
Skipping the ability to customize the module nav for roles?

**Comment by benhaynes** [comment]
For the short-term, yes. Module/Collection Overrides are the only fields on Roles that can not be merged... meaning we can't work towards _multiple roles per user_. It also makes it difficult to set up a consistent nav for your whole project. 

We're making this a global configuration, and will likely add a (mergeable) deny-list for modules at the Role level soon.

**Comment by danieljwestman** [comment]
Okay, I agree. 

> work towards multiple roles per user
👍🏻

> will likely add a (mergeable) deny-list for modules at the Role level soon
👍🏻

Hope to see the deny-list soon. Need the ability to have different navs for different roles over here.

**Comment by Pachat** [comment]
@benhaynes 
> we can't work towards multiple roles per user. It also makes it difficult to set up a consistent nav for your whole project.

I agree with that. 
Keeping with mono role, why not place the modules that are for now in the unique row of the collection `directus_settings` in a M2O collection?
Something like `directus_modules`. 
That way, we could benefit of all allow accesses and filters permissions we already have on collections.

**Pull request merged**
