### PR TITLE
feat(openid): retrieve role id from claims

### PR DESCRIPTION
**Pull request by ziouf**
## Scope

What's changed:

- In openid sso driver, extract user role id from claim returned by oidc provider.
- if not found, fallback to default role id.

## Potential Risks / Drawbacks

none

## Review Notes / Questions

none

---

Fixes #20631

### CODE REVIEW

**Comment by paescuj** [comment]
@aidenfoxx May I ask you about your opinion on that? 😇

**Comment by aidenfoxx** [comment]
> @aidenfoxx May I ask you about your opinion on that? 😇

It depends how you want to handle non-standard claims. There are hooks the enable doing this outside of the auth drivers (´auth.create` and `auth.update`). But if this is something you want, it should probably also be added to the OAuth2 flow for consistency.

**Comment by ziouf** [comment]
> > @aidenfoxx May I ask you about your opinion on that? 😇
> 
> It depends how you want to handle non-standard claims. There are hooks the enable doing this outside of the auth drivers (´auth.create`and`auth.update`). But if this is something you want, it should probably also be added to the OAuth2 flow for consistency.

Hello, I pushed a commit for the same feature in oauth2

**Comment by aidenfoxx** [comment]
So as mentioned you can use hooks to achieve this with the existing Directus functionality e.g:
```javascript
export default ({ filter }) => {
    filter('auth.create', (userPayload, { providerPayload }) => {
        return { ...userPayload, role: providerPayload.userInfo['directus_role_id'] };
    });
};
```

**Comment by ziouf** [comment]
> So as mentioned you can use hooks to achieve this with the existing Directus functionality e.g:
> 
> ```js
> export default ({ filter }) => {
>     filter('auth.create', (userPayload, { providerPayload }) => {
>         return { ...userPayload, role: providerPayload.userInfo['directus_role_id'] };
>     });
> };
> ```

Is it related to this documentation ? 
https://docs.directus.io/guides/extensions/hooks-validate-number-twilio.html#add-hook-to-directus

**Comment by aidenfoxx** [comment]
Yes, exactly. 😄

**Comment by ziouf** [comment]
I'm going to try this on testing environment ! 
Thank you

**Comment by ziouf** [comment]
Despite my poor coding skills, it works like a charm with hook system
Thank you, I close the PR. It's not needed anymore

**Pull request closed without merging**
