### PR TITLE
Add dark mode to docs

### PR DESCRIPTION
**Pull request by u12206050**
Screenshot 2021-11-26 at 20 48 03
Screenshot 2021-11-26 at 20 47 54

### CODE REVIEW

**Comment by benhaynes** [comment]
I love it!! Would it be possible to shift that toggle into the header so there's no overlap with the navigation?

Also, we might want to do another pass on the darker notice colors. Did you pull these from the Directus color vars in `_dark.scss`?

**Comment by paescuj** [comment]
Nice 👍 Instead of the toggle button (or in addition to) you could also rely on the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media feature.

**Comment by u12206050** [comment]
Agree on both accounts, actually forgot about the `_dark.css` will update them and add checking of `prefers-color-schema`

**Comment by u12206050** [comment]
Screenshot 2021-11-27 at 10 26 12

Now respects `prefers-color-scheme`
and looks way better with official dark theme from directus. :)

**Comment by benhaynes** [comment]
Much better, thank you, @u12206050!!! ❤️

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Instead of having a toggle on the page with a class on the html element (with global styles), lets just rely on the `@media (prefers-color-scheme: dark) {})` query in CSS directly

**Comment by u12206050** [comment]
> Instead of having a toggle on the page with a class on the html element (with global styles), lets just rely on the `@media (prefers-color-scheme: dark) {})` query in CSS directly

Ok done.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
