### PR TITLE
Default to current user language in field translation language selector

### LINKED ISSUE #20257: Preselect user's current language when creating new translations instead of en-US.
### Describe the Improvement

When you create a lot of translations for the primary language of your app in directus, it is really annoying, when the lanuage is always preselected with en-US as value. You always have to switch the language to the desired target language first. 

This is an unnecessary step that could be saved every time and would speed up the whole thing extremely.
By changing to the current user language, everything can be translated in one go. If you want to add another language as a translation, you only need to change the user language and it is preset again for the translations.

Please set the current language as default for translation language selector.

### PR DESCRIPTION
**Pull request by FloMaetschke**
## Scope

What's changed:

- The language selector when creating translation defaults to the current user language.

## Potential Risks / Drawbacks

nope

## Review Notes / Questions

- I ran the tests, and they failed before my change the file and after. Because of this consitency i guess its not messing up the tests.

---

Fixes #20257

### CODE REVIEW

**Review by paescuj — CHANGES_REQUESTED** [review]
I'd prefer to have this handled in the `system-language` interface itself.

**Comment by FloMaetschke** [comment]
At the moment, the default value is specified from outside the `system-language` interface. The interface is dumb. Thats why i made the change outside. 
Moving the decision into the `system-language` interface  would require to default the value to null from outside ... -Thats the only chance to decide, if no selected value is active - and to load current user language from within the interface if its null. I don't see a benefit here, only more code/complexity.

**Comment by paescuj** [comment]
> The interface is dumb.

Well, then let's change that 😄 

> Moving the decision into the `system-language` interface would require to default the value to null from outside ... -Thats the only chance to decide, if no selected value is active - and to load current user language from within the interface if its null. I don't see a benefit here, only more code/complexity.

I don't see an issue with this. If no value is passed, we default to the user language. The main reason I'd like to move that into the interface itself is that the interface is also used in other places, and we could thus benefit from this improvement everywhere.

**Comment by paescuj** [comment]
Hey @FloMaetschke, thanks for the pull request! I went through it and can confirm the approach is the best for now 👍 Thanks for your patience! Since you're branch is read-only, I've merged the commits via #21065, but I'll make sure you'll be credited in the release notes 🥇

**Pull request closed without merging**
