### PR TITLE
Fix ESM transpiling in `@directus/shared`

### PR DESCRIPTION
**Pull request by paescuj**
## Description

See https://github.com/directus/directus/pull/16787#issuecomment-1346840461.
As mentioned in the comment, this might not be the prettiest solution but the simplest I could come up on the fast.
While it seems to work, it comes with two small cons:
* Declaration maps aren't emitted anymore.
* Requires another tool (`nodemon`) to watch and rebuild in dev mode (due to unusual `unbuild` usage).

Additionally, I've tried to get rid of the "entrypoint declaration files" (`./composables.d.ts`, ...) by referencing types directly via:
```diff
	"exports": {
		"./composables": {
+ 			"types": "./dist/composables/index.d.ts",
			"import": "./dist/composables/index.mjs",
			"require": "./dist/composables/index.js"
		},
```
But this would mean that all packages depending on `@directus/shared` (e.g. `@directus/extensions-sdk`) would need to have `moduleResolution` set to `node16` which could be a breaking change for others.

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by paescuj** [comment]
(feels like a one-time issue with deps in the blackbox test run - would be great if someone can restart this test 😃)

**Comment by rijkvanzanten** [comment]
> But this would mean that all packages depending on @directus/shared (e.g. @directus/extensions-sdk) would need to have moduleResolution set to node16 which could be a breaking change for others.

This is actually a big deal yeah.. I ran into the same issue before in the `tsup` approach 😭 

Honestly I'm kinda thinking the `@directus/utils` approach is the least bad at the moment. Shared is getting pretty big regardless, so moving to a split approach where we have `@directus/exceptions` / `@directus/utils` / `@directus/types` isn't a bad thing either  🙂

**Comment by paescuj** [comment]
> Honestly I'm kinda thinking the `@directus/utils` approach is the least bad at the moment. Shared is getting pretty big regardless, so moving to a split approach where we have `@directus/exceptions` / `@directus/utils` / `@directus/types` isn't a bad thing either 🙂

Yup, this is probably true 🙂 I'm just a bit worried about "maintainability" when splitting out into multiple packages, seeing that some of the components are actually tightly coupled (what spoke for the unified `@directus/shared` package so far)...

**Comment by paescuj** [comment]
Closing for now as there seems to be some conflicts with the deps anyway.

**Comment by rijkvanzanten** [comment]
> Yup, this is probably true 🙂 I'm just a bit worried about "maintainability" when splitting out into multiple packages, seeing that some of the components are actually tightly coupled (what spoke for the unified @directus/shared package so far)...

For sure! The goal is to subset `@directus/shared` completely in favor of the new packages once everything is fully switched to ESM 🙂

**Comment by paescuj** [comment]
> For sure! The goal is to subset @directus/shared completely in favor of the new packages once everything is fully switched to ESM 🙂

I'm not quite sure I understand it correctly. Does that mean you are leaving it as it is for now? 🙂

**Comment by rijkvanzanten** [comment]
> > For sure! The goal is to subset @directus/shared completely in favor of the new packages once everything is fully switched to ESM 🙂
> 
> 
> 
> I'm not quite sure I understand it correctly. Does that mean you are leaving it as it is for now? 🙂

We're leaving shared as is, and then create new packages for the shared parts, like /utils, /types, etc. Those new parts can be done in ESM.

**Pull request closed without merging**
