### PR TITLE
swagger doc. interface

### PR DESCRIPTION
**Pull request by sacconazzo**
## Description

Fixes #

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [x] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by sacconazzo** [comment]
enabled api-docs interface on OAS definitions provided in `/server/specs/oas`.

API documentation provided at `/server/swagger`

**Comment by azrikahar** [comment]
Hi, thanks for your first PR here! ~~Would you mind updating the description to elaborating more on the motivations and/or any prior discussions that may be the catalyst/spark for this PR?~~ seems like you added a follow up comment 🙂

This does seem like a great addition, but I'm wonderingly would this be a better candidate for an extension rather than core, similar to the approach shared over here: https://github.com/directus/directus/discussions/7084#discussioncomment-1091115 or https://github.com/directus/directus/discussions/7084#discussioncomment-1455412. 🤔

That being said, we are actively looking to improve DX in general and this PR definitely can be a substantial leap in the right direction, so I'll defer to the team for their thoughts on this.

**Comment by sacconazzo** [comment]
> Hi, thanks for your first PR here! ~Would you mind updating the description to elaborating more on the motivations and/or any prior discussions that may be the catalyst/spark for this PR?~ seems like you added a follow up comment 🙂
> 
> This does seem like a great addition, but I'm wonderingly would this be a better candidate for an extension rather than core, similar to the approach shared over here: [#7084 (comment)](https://github.com/directus/directus/discussions/7084#discussioncomment-1091115) or [#7084 (reply in thread)](https://github.com/directus/directus/discussions/7084#discussioncomment-1455412). 🤔
> 
> That being said, we are actively looking to improve DX in general and this PR definitely can be a substantial leap in the right direction, so I'll defer to the team for their thoughts on this.

Hello. Thanks for considering.
Yes, it is a feature that could be quickly inserted into extensions, in fact in some projects I am using it like this. However considering that oas file is auto-generated and by modifying the standard directus permissions it is possible to show or not the desired endpoints without having to intervene on the code, I thought that even as a feature it could be useful.

**Comment by sacconazzo** [comment]
> Hi, thanks for your first PR here! ~Would you mind updating the description to elaborating more on the motivations and/or any prior discussions that may be the catalyst/spark for this PR?~ seems like you added a follow up comment 🙂
> 
> This does seem like a great addition, but I'm wonderingly would this be a better candidate for an extension rather than core, similar to the approach shared over here: [#7084 (comment)](https://github.com/directus/directus/discussions/7084#discussioncomment-1091115) or [#7084 (reply in thread)](https://github.com/directus/directus/discussions/7084#discussioncomment-1455412). 🤔
> 
> That being said, we are actively looking to improve DX in general and this PR definitely can be a substantial leap in the right direction, so I'll defer to the team for their thoughts on this.

Hi @azrikahar, I tried to create an external extension for this, I noticed that the script `directus-extension build`, including swagger-ui-express as a dependency, doesn't work properly. It works only as a local extension.

Could you suggest if there is a way to include dependency in the external-extension without recompiling them? Or another way to troubleshoot build problems.

**Comment by azrikahar** [comment]
> Hi @azrikahar, I tried to create an external extension for this, I noticed that the script `directus-extension build`, including swagger-ui-express as a dependency, doesn't work properly. It works only as a local extension.
> 
> Could you suggest if there is a way to include dependency in the external-extension without recompiling them? Or another way to troubleshoot build problems.

When you were including `swagger-ui-express` in the extension, were you using import or require?

`require` will not be compiled, but it does require the dependency to be installed beforehand (whereas import does get compiled and do not need to be installed as it's bundled in the built file) 👍

**Comment by sacconazzo** [comment]
> > Hi @azrikahar, I tried to create an external extension for this, I noticed that the script `directus-extension build`, including swagger-ui-express as a dependency, doesn't work properly. It works only as a local extension.
> > Could you suggest if there is a way to include dependency in the external-extension without recompiling them? Or another way to troubleshoot build problems.
> 
> When you were including `swagger-ui-express` in the extension, were you using import or require?
> 
> `require` will not be compiled, but it does require the dependency to be installed beforehand (whereas import does get compiled and do not need to be installed as it's bundled in the built file) 👍

Thanks for the precious tip! now it works 🥳

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
