### PR TITLE
Adds support for Supabase Storage

### PR DESCRIPTION
**Pull request by smuriu**
## Description

Adds support for Supabase Storage as a storage adapter. Based on #14742, not all `Storage` class methods are implemented.

Fixes #9057

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [X] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [X] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [X] Documentation was added/updated. PR: https://github.com/directus/docs/pull/237

### CODE REVIEW

**Comment by smuriu** [comment]
This pull request competes with #15631

Just noticed File Storage 2.0 in #16825

Would be happy to adapt this PR to File Storage 2.0 if/when necessary

**Comment by pixelkoduje** [comment]
When can we expect supabase storage to be implemented in directus?

**Comment by pixelkoduje** [comment]
@smuriu 
https://github.com/smuriu/directus

How to swap the current directus, with your package? Can you make it available as an npm package? So that supabase support can be added, while it is not officially implemented.
image

**Comment by rijkvanzanten** [comment]
Heya! Thank you for your contribution. Unfortunately, we can't accept PRs for improvements/features that don't have a prior accepted Discussion and associated Issue (as per the [Contributing Guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests)). This is to ensure that PRs that are opened will actually get the chance to be reviewed, merged, and maintained by the core maintainers. Thank you for your understanding!

**Comment by KULTI1995** [comment]
Dude, you don't even know how many people are using supabase right now. And you give up a little and don't implement it? no kidding..

**Comment by rijkvanzanten** [comment]
@KULTI1995 That's not even close to what's happening here.. I'd love to support Supabase Storage natively as a storage adapter, but it's untenable for us to review/maintain large new feature implementation PRs without going through the proper steps as per the [Contributing Guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests). This PR is actually a great example of where things can go sideways very fast when skipping over the process. While this PR was in flight, the storage abstraction setup was overhauled completely in #16825, making this PR stale and outdated before it was even ready for review. If the process had been followed as per the guidelines, that change would've been planned accordingly, and both would've been able to be progressed simultaneously. The fact that this particular PR was closed doesn't mean that we don't want to / won't ever support supabase storage 👍🏻

**Comment by MentalGear** [comment]
Supabase has now released v.3 of their Storage, using open source protocol TUS, which might make the integration easier.

[Supabase Storage v3 released](https://supabase.com/blog/storage-v3-resumable-uploads)

> "TUS is an open protocol for resumable file uploads. By leveraging an open protocol, developers can use existing libraries with Supabase Storage."

**Pull request closed without merging**
