### PR TITLE
Add JSON/CSV Import

### LINKED ISSUE #2927: Add import/export endpoints
The export endpoint allows you to export the output of multiple endpoints at the same time. This effectively allows you to export schema and data of the installation. Subsequently, the import endpoint should be able to intake this data and process it through the regular services, as if they were separate requests.

This allows you to move schema and/or data from/to different Directus installation, like staging to production

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Closes https://github.com/directus/directus/issues/2927

### CODE REVIEW

**Comment by tylerforesthauser** [comment]
I just wanted to point out that the added docs include an example just for the above Manual Sorting section...

**Comment by rijkvanzanten** [comment]
My b! (Note to self: no docs writing past 8pm)

**Comment by rijkvanzanten** [comment]
@tylerforesthauser 55efb688ed7e5c2eabcd13fde0de652fe27c494e Better 👍🏻

**Comment by co2nunes** [comment]
I have the schema in my localhost and dev, staging and production servers, but I must find out how to move the Collection's data ( including the files). Where are the documentation for this? Thanks for input

**Pull request merged**
