### PR TITLE
Update filename_disk extension when mimetype changes on overwrite

### LINKED ISSUE #23045: When uploading a replacement file with a different extension, filename_disk extension is not updated.
### Describe the Bug

When using the replace file option for image, replacing the file with a different extension type, `filename_disk` extension is not updated.

Note: The `type` and `filename_download` are updated properly.

Initial Upload
initial
Replaced Upload
replaced

### To Reproduce

1. Upload a file with any extension (i.e .png)
2. Replace file with a new file and extension type (i.e .jpg)
3. `filename_disk` is not updated to reflect the new file extension type.

### Directus Version

v10.13.1

### Hosting Strategy

Directus Cloud

### Database

_No response_

### PR DESCRIPTION
**Pull request by that1matt**
## Scope

What's changed:

- When a file is replaced, the extension is updated to reflect current mimetype

## Potential Risks / Drawbacks

- There is probably some, but I am not sure.

## Review Notes / Questions

- Verify this is the correct solution

---

Fixes #23045

### CODE REVIEW

**Comment by that1matt** [comment]
A potential issue I have found, is that when uploading a new file, if you supply the `filename_disk` the file extension doesn't get added. I can address the issue within the PR, or open another issue to handle that.

```
// If the filename_disk doesn't include an extension, append it
if (!path.extname(payload.filename_disk!)) {
     payload.filename_disk = payload.filename_disk + (fileExtension || '');
}
```

**Comment by rijkvanzanten** [comment]
Interesting follow up 🤔 I'm actually wondering what I'd expect to happen in that case. If I upload a file explicitly without an extension, or maybe even with a different extension, do I expect it to be "corrected" automatically or should it just leave my provided value as-is?

**Comment by that1matt** [comment]
@rijkvanzanten my two cents, if you supply a `filename_disk` with an extension, nothing happens, if you supply a `filename_disk` without an extension, try and add the extension from the mime type, otherwise do not include it.

This would provide a more consistent behavior where the `filename_disk` tries to always have an extension. Instead of having an extension and not having an extension depending on the path you take to upload an image.

**Comment by jaads** [comment]
>  I can address the issue within the PR, or open another issue to handle that.

@that1matt  This since is another issue, and may requieres some more discussion, please open a separate issue/PR 🙏

**Review by jaads — APPROVED** [review]
works as expected, fix is nicely integrated 👍

**Pull request merged**
