### PR TITLE
prevent user from changing their own status or role

### LINKED ISSUE #15761: A user should not be allowed to deselect its role
### Describe the Bug

Users can deselect their role.

As we cannot act on this Directus field,, by default, the `Deselect X` should not show on the role field of the user's form.

### To Reproduce

1. On the current user form, deselect the role
2. Save

### Errors Shown

You are not allowed to access this App (of course, no more role to allow access).

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL 14.2

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by freekrai**
## Description

Currently it's possible for a user to change their own status or role in the admin, this probably isn't a great idea as if you are an admin user and change your role, or even deselect your role then suddenly you lock yourself out.

This PR disables those two fields if you are editing your own records.

Fixes #15761

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
We should (also) add this check api side

**Comment by freekrai** [comment]
> We should (also) add this check api side

Nice catch, will add the check there too

**Comment by u12206050** [comment]
Nooo! :) Please don't merge this PR. It will break my Role Switcher Module. I have 3 products in production using Directus with a setup where some users have multiple roles, and they are able to switch between those roles based on validation rules.

I would rather opt for a hard coded validation rule that the role field is always required.

I am impartial to the status field.

**Comment by azrikahar** [comment]
Just a heads up based on the latest commit https://github.com/directus/directus/pull/15795/commits/9b4d680c94a2654014913c86715cc0a04b63a014, I believe the check should be made in Users service rather than the controller (as there are also cases such as custom extensions using UsersService or when Update Data flow operation officially supports system collections with UsersService) 👍

There's also an existing/similar "last admin" check in UsersService as well:

https://github.com/directus/directus/blob/6e730956afbba37832b49587cc06049d99b68937/api/src/services/users.ts#L126-L141

(so it can probably be updated or another similar function for "own status")

**Comment by freekrai** [comment]
Yeah can look at that further, I know a user can remove their role even if last admin so can look at moving this particular check to user service instead,

**Comment by u12206050** [comment]
Hmm, interesting, I'll need to then create another user with admin role, just in order for me (as an admin) to be able to switch to other roles while testing them.

This is purely an admin issue right? Normal users can just be restricted by using permissions.

Am starting to wonder if I should create a PR for multiple role support as I am using it in every Directus project now days. @rijkvanzanten the base setup is explained here: https://github.com/u12206050/directus-extension-role-chooser

**Comment by abdonrd** [comment]
> Am starting to wonder if I should create a PR for multiple role support as I am using it in every Directus project now days. @rijkvanzanten the base setup is explained here: https://github.com/u12206050/directus-extension-role-chooser

A built-in multi-role support should be really really great!

**Comment by freekrai** [comment]
Ok, so API wise the error works fine from existing userService checks, `You can't remove the last admin user from the role.` so will remove my API checks, this PR will still keep preventing a user from changing their own role in the user form.

**Comment by u12206050** [comment]
> Ok, so API wise the error works fine from existing userService checks, `You can't remove the last admin user from the role.` so will remove my API checks, this PR will still keep preventing a user from changing their own role in the user form.

Isn't it enough with just limiting it via permissions? I almost switch my roles on a daily basis, basically every time another user with a problem in their role is having an issue.

I might be mistaken, but this might just fall into the 20% of users needing this? The other 80% might be enough with just warning them when the select another role.

**Comment by freekrai** [comment]
Currently the biggest issue is if you are the last admin user changing your role, and we have checks in place for that already so closing this PR as it is and will revisit if we need to add additional checks elsewhere.

**Pull request closed without merging**
