### PR TITLE
Remove dots when disabled

### LINKED ISSUE #4038: Remove dots when disabled
dots

### PR DESCRIPTION
**Pull request by YannickMol**
Fixes #4038

### CODE REVIEW

**Comment by YannickMol** [comment]
@rijkvanzanten, this should work, but please go ahead and check 😅

**Comment by rijkvanzanten** [comment]
This won't work!

By de-rendering the whole `v-menu` component, we'll also hide the "activator" inside the menu (eg the button you click on to activate the menu). This'll cause the wanted behavior on the save-options dropdown, but cause problems for most other uses of v-menu, like the dropdown interfaces

**Comment by YannickMol** [comment]
Do you have an example of where I can test this? The dropdown interfaces I tried still seem to work.

**Comment by rijkvanzanten** [comment]
> Do you have an example of where I can test this? The dropdown interfaces I tried still seem to work.

Is your dropdown interface set to readonly? That should add the `disabled` to v-menu and make it disappear (if my calculations are correct 🤓 )

**Comment by YannickMol** [comment]
You were absolutely right, I have given it another try 🙄

**Comment by rijkvanzanten** [comment]
That's more like it! 😄 

One quick addition: could you do the same thing for the users/files module? I believe they have a similar save-options structure 🤔

**Comment by YannickMol** [comment]
Will do, should the `:disabled` tag also be deleted? I believe it won't be necessary if the element is not rendered.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
