### PR TITLE
fix: reset login error message on successful credentials

### PR DESCRIPTION
**Pull request by bwp91**
## Scope

What's changed:

- Hide the invalid credentials error message on the login form when a correct username/password combination is entered.

To reproduce, 2fa needs to be enabled - using the initial admin account is okay.

1. Attempt to login with the admin username but an incorrect password - the invalid credentials message appears
2. Next, login with the correct credentials so that the field for the 2fa code appears
3. At this point, the invalid credentials error is still visible (and in my opinion it should have been hidden when the 2fa input box appears)

## Review Notes / Questions

---

Fixes #\<num\>

### CODE REVIEW

**Review by licitdev — COMMENTED** [review]
How about clearing the error only when the OTP is required?

https://github.com/directus/directus/blob/b64bd4173c4fb455233d2d72878ee81d74688727/app/src/routes/login/components/login-form/login-form.vue#L91-L93

**Comment by bwp91** [comment]
> How about clearing the error only when the OTP is required?
> 
> https://github.com/directus/directus/blob/b64bd4173c4fb455233d2d72878ee81d74688727/app/src/routes/login/components/login-form/login-form.vue#L91-L93

thanks, a nicer solution actually!

**Comment by bwp91** [comment]
@licitdev all done!

**Review by AlexGaillard — APPROVED** [review]
This LGTM 👍 

Thanks @bwp91! A nice little UX improvement.

Congrats on your first contribution to Directus 🐰🎉

**Pull request merged**
