### PR TITLE
File Preview fixes

### LINKED ISSUE #14546: Hidden audio player and styling inconsistency
### Missing audio player

image

### Image

Padding around image, but large vertical resolution negates it
imageimage

Seems to work as intended for smaller resolution images
imageimageimage

### Video
Typical video resolution
image

Videos with smaller widths are not center aligned and video playback controls may be hidden
imageimageimage

Can see the required height of the player controls here
image

### To Reproduce

Test with [assets.zip](https://github.com/directus/directus/files/9156915/assets.zip)
 

### Errors Shown

_No response_

### What version of Directus are you using?

main branch https://github.com/directus/directus/commit/53168f75ad1530d0fcec174be54f90768a1ccc5f

### What version of Node.js are you using?

v16

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Fixes #14546

- [x] Missing audio player

   image
   
- [ ] Paddings around large vertical images (Pending discussion)

- [x] Video player centering/height

   |Before|After|
   |---|---|
   |chrome_HS74nfBSnj|chrome_BfFUyF1leY|
   
## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by azrikahar** [comment]
### Video controls hidden for smaller width

For this point, I'm not sure should we do anything? 🤔 Upon closer inspection, although controls like `Play`, `Audio` and `Fullscreen` can visually disappear when there's not enough screen real estate, they are actually tucked inside the context menu as shown here:

https://user-images.githubusercontent.com/42867097/180420525-06042c29-1604-4d41-8b37-278f8cd287be.mp4

That said, not sure can this differ (if any) in Safari or other browsers. 

### Large vertical resolution does not have padding

Currently there's a detection of the image height:

https://github.com/directus/directus/blob/3d03291c310c6d30a6cde1323f5298379a48fec3/app/src/views/private/components/file-preview/file-preview.vue#L58

which adds the `.small` class that adds the padding for small images:

https://github.com/directus/directus/blob/3d03291c310c6d30a6cde1323f5298379a48fec3/app/src/views/private/components/file-preview/file-preview.vue#L99-L104

Do we want to add such universal image padding for large images? It does "resolve" situations such as large vertical images, but for images that were previously filling up the whole preview, it now also has the padding applied. Here's a comparison:

|Before|After|
|---|---|
|chrome_TSbste2g9d|chrome_f70Z9sgb7Z|
|chrome_HEBfX8omRb|chrome_At231Fq6Sw|

**Comment by licitdev** [comment]
> Video controls hidden for smaller width

Should the video player have a full width, with letterboxing, for consistency between different video widths and with `v-image`?

Also, should there be a min height for the video player? 

I recall setting a min height before (same as the one used for image before) so the player controls will always be visible and easily accessible. There might be videos with a height smaller than the height of player controls.

But those styling was for `video.js` which has been removed. 🤔

**Comment by rijkvanzanten** [comment]
Yeah lets do the same gray letterboxing for non-"standard" aspect ratio videos

**Comment by azrikahar** [comment]
> Yeah lets do the same gray letterboxing for non-"standard" aspect ratio videos

Added:

https://user-images.githubusercontent.com/42867097/180750132-0b5dec01-fad0-4eea-acc2-8c780ad08f17.mp4

But I haven't added any padding yet since I'm not sure which strategy (the current "only have padding when small" or "always have padding") we'd like to use, similar to the [image padding discussed in the comment above](https://github.com/directus/directus/pull/14570#issuecomment-1192435466). However if we'd want to follow the same strategy of only padding to small videos, it'll likely require #6865 to work.

> Also, should there be a min height for the video player?

I've also added min height and min width to it, which does work. Let me know if it should be higher.

I'm also not sure if this value is too arbitrary to assume it'll work on all browsers' video player (or they are actually the same?). But I do think we can move with this until a potential custom video player can be added in the future.

|Before|After|
|---|---|
| <video src="https://user-images.githubusercontent.com/42867097/180749478-b5a0e38b-6cf3-4fa9-8f04-ca0090664340.mp4" /> | <video src="https://user-images.githubusercontent.com/42867097/180749368-8ed5c4fa-ebee-44c5-8228-b690c231556d.mp4" /> |

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
