### PR TITLE
Add v-date-picker base component & use it in datetime interface

### PR DESCRIPTION
**Pull request by azrikahar**
- adds <v-date-picker> component using Flatpickr
- changed current DateTime interface to wrap the new component
- adds the Set to Now button from existing interface to the new one

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
What's left to do on this @azrikahar? 🙂

**Comment by azrikahar** [comment]
locales support are not fully added yet (at least the ones available from flatpickr), and there is the thought of using the existing date-fns locale instead since I believe that's also being set in the translations via Crowdin right? So technically currently we may "drop" those date locales momentarily, but we can also opt add it in the next cycle if that's okay.

**Comment by azrikahar** [comment]
@rijkvanzanten scratch that. Added all the remaining locales from Flatpickr now, while we can circle back if the output from previous date-fns locale is preferred.

Also added Set to Now button:

xUySORHdiU

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Lets see if we can render the date picker component inside a regular v-menu, instead of relying on flatpickr to do its own positioning. Right now, it doesn't follow scroll and doesn't use our regular styling for the popover bounding box.

The `v-date-picker` component should only be the date-picker itself (the little calendar with the days). That way, we can have the datetime interface be:

```
v-menu
  template #activator
    input
  
  v-date-picker
```

That also allows us to use the same calendar component in other places outside of the input+menu combination 🙂

**Comment by azrikahar** [comment]
- Used v-menu to wrap it as mentioned. Definitely much better 👍
- Ended up removing flatpickr locales in favor of previous date-fns locales as well
- had to add a new prop to v-menu `maxHeightNone` so that the calendar won't become scrollable (we had to scroll down to change time or click set to now if we don't set this). If there's a better naming or overall different preferred approach, do let me know.

**Comment by rijkvanzanten** [comment]
@azrikahar @benhaynes lets clean up the styling a bit before merging this through. It's a bit too rough around the edges for my taste

https://user-images.githubusercontent.com/9141017/146453453-340dfa5d-97fc-4353-a4c2-d2fc48ffaef9.mp4

Most notably:

- The non standard fonts / dropdown icon in the "December 2021" header
- The hover / selection colors
- Input hover style of the time input

Can we make the hour / second input any smaller? They're spaced very far apart right now because we're rendering in that wider size 🤔 

How much flexibility in styling do we have @azrikahar? Are we limited by flatpickr in how much we can tweak these things?

**Comment by azrikahar** [comment]
Minor update:

https://user-images.githubusercontent.com/42867097/146519773-21eec8f8-134d-4efc-a1dd-31c3f6641b78.mp4

## Included in above update

> The non standard fonts / dropdown icon in the "December 2021" header

I believe they are the same font, but Flatpickr is currently scaling the font-size using the value `135%`. Changed it to `16px` in the update, not sure if that's better.

> The hover / selection colors

Wasn't really sure which color to use here. The updated one does use the lighter color, but I  think the updated one doesn't have enough contrast for dark theme:

C64e9jPvcQ

## Not included in above update

> Can we make the hour / second input any smaller? They're spaced very far apart right now because we're rendering in that wider size 🤔

It should be possible. Is there a recommended way of shrinking them? center aligning them with some form of max width?

> How much flexibility in styling do we have? Are we limited by flatpickr in how much we can tweak these things?

The previous and next month arrows on the top left & top right corner are technically the only ones that flatpickr allows us to provide our own svg html to replace them. 

The month picker uses the default select input, so the arrow will be the system default. We may be able to modify it by using material chevron down icon as a background image if we need to.

As for the up/down arrows for year input and time inputs, they are spans using border tricks to create triangles. Either we'll have to use `::before` to add svg as background image (also not ideal), or maybe sort of "hack" it by replacing the DOM element all together? It does feel somewhat limited around these parts.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
