### PR TITLE
Use lodash.assign in use-preset.ts

### PR DESCRIPTION
**Pull request by oreilles**
Just some light refactoring to improve readability.

### CODE REVIEW

**Review by azrikahar — APPROVED** [review]
LGTM!

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
.

**Review by rijkvanzanten — APPROVED** [review]

**Comment by Oreilles** [comment]
I had forgotten that PR but looking back at it, I think `merge` actually was correct and `assign` wrong.

For example, 

```ts
updatePreset({ layout_query: { [localPreset.value.layout]: query } });
```
will resolve to this with `assign`:
```ts
localPreset.value = {
	...localPreset.value,
	layout_query: {
		[localPreset.value.layout]: val,
	},
};
```
When the current behavior is:
```ts
localPreset.value = {
	...localPreset.value,
	layout_query: {
		...localPreset.value.layout_query,
		[localPreset.value.layout]: val,
	},
};
```
Which would have been obtained with `merge`. Same goes for `layout_options` - and other computed ref just adds single scalar values `bookmark`, `search` etc with which `merge` wouldn't interfere.

**Comment by rijkvanzanten** [comment]
@Oreilles True! However, when we were to use merge, you will most likely run into issues with filter or other deeply nested objects, for example:

```js
const filter = { _or: [{}] };

updatePreset({ filter });
```

if you already had a filter set to `{ _and: [{}] }`, you'd end up with

```js
{
  _and: [{}],
  _or: [{}]
}
```

instead of 

```js
{ _or: [{}] }
```

**Comment by rijkvanzanten** [comment]
I think assign is correct for `layout` / `filter` / `refresh_interval` / `search` / `bookmark`. 

`layout_options` and `layout_query` should use assign, but on a level "deeper" to get the current behavior you listed above

**Comment by Oreilles** [comment]
That's right, hadn't seen the `filter` case. I'll submit a PR soon replacing the other ones with `merge` and handle the special `filter` case with `assign`.

**Comment by rijkvanzanten** [comment]
@Oreilles Lets do it the opposite way. I think most of these are best suited with `assign` _except_ for `layout_query` and `layout_options`. Even for those, we wouldn't want to use merge, as the options object is an unknown nested JSON blob that we don't want to just deep-merge into.

**Comment by rijkvanzanten** [comment]
Maybe we could add a `updateScopedPreset` that'll do a nested assign, something like:

```js
const key = 'layout_query';

assign(
  {},
  localPreset.value,
  { 
    [key]: assign(
      {},
      localPreset.value[key],
      { [layout]: preset }
    )
  }
);
```

? That should do the trick I think

**Pull request merged**
