### PR TITLE
Map interface

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
Adding map interface using leaflet library, with tiles from OpenStreetMap, CARTO and Stamen.

Interface config
Screenshot 2020-11-24 at 21 07 19

UI with center mode
Screenshot 2020-11-24 at 21 09 47

UI with pin mode
Screenshot 2020-11-24 at 21 10 39

https://github.com/directus/directus/discussions/3133

### CODE REVIEW

**Comment by benhaynes** [comment]
This looks amazing!! Thank you @dimitrov-adrian !

**Comment by jroxendal** [comment]
Well done, @dimitrov-adrian! I few comments:

The typescript typechecker is complaining at quite a few places, did you try opening the code with vscode? That should help you fix some issues. A few that I noticed:

1. it appears that leaflet has not been installed using npm install leaflet, because there is no entry in the package-lock.json file. when I clone your pr and run npm install, leaflet isn't added. 
2. You're writing a feedback variable to the window object, this seems unnecessary, unless I'm missing something.
3. You've written custom code to handle geolocation, but there's a leaflet `map.locate()` to handle that, see https://leafletjs.com/reference-1.7.1.html#map-locate. Normally it wouldn't matter but the type checker seems to think that `success.accuracy` is an error, if you port your code to map.locate() that error should go away. 
4. all instances of event.target should probably be cast to Element, or some derivative. `event.target.classList` fails check but `(event.target as Element).classList` doesn't.
5. some of your code can be simplified using https://v3.vuejs.org/guide/events.html#key-modifiers, see your `addressToCodeKeyHandler` method. Adding a v-model to the <input> should remove the need to check the value property on the mouseevent.target, which squashes further type checker errors.

I'd love to see this PR get accepted! Good work so far.

**Comment by jroxendal** [comment]
Here's a locate function for leaflet from another project i'm working on:

```
    locate() {
      let html = '<div class="pulsating-circle"></div>'

      let marker
      map
        .locate({ enableHighAccuracy: true })
        .on("locationfound", event => {
          if (!marker) {
            marker = L.marker(event.latlng, {
              icon: L.divIcon({ html, className: "bg-transparent border-0" })
            }).addTo(map)
          } else {
            marker.setLatLng(event.latlng)
          }
          map.flyTo(event.latlng, 12)
        })
        .on("locationerror", event => {
          if (marker) map.removeLayer(marker)
          marker = null
        })
    }
```

and the location marker scss:
```
.bg-transparent {
  background-color: transparent;
}
.border-0 {
  border-width: 0;
}
.pulsating-circle {
  cursor: grab;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translateX(-50%) translateY(-50%);
  width: 30px;
  height: 30px;

  &:before {
    content: "";
    position: relative;
    display: block;
    width: 300%;
    height: 300%;
    box-sizing: border-box;
    margin-left: -100%;
    margin-top: -100%;
    border-radius: 45px;
    background-color: #01a4e9;
    animation: pulse-ring 1.25s cubic-bezier(0.215, 0.61, 0.355, 1) infinite;
  }

  &:after {
    content: "";
    position: absolute;
    left: 0;
    top: 0;
    display: block;
    width: 100%;
    height: 100%;
    background-color: white;
    border-radius: 15px;
    box-shadow: 0 0 8px rgba(0, 0, 0, 0.3);
    animation: pulse-dot 1.25s cubic-bezier(0.455, 0.03, 0.515, 0.955) -0.4s infinite;
  }
}
```

**Comment by benhaynes** [comment]
Thanks @jroxendal — this is really helpful!!

**Comment by jroxendal** [comment]
I've read through the latest commits and, for what it's worth, they look good to me! Due to other issues I've failed to try any real workflows with this interface, so someone else should absolutely have a closer look.

**Review by pes2020kk — DISMISSED** [review]

**Comment by Oreilles** [comment]
Thanks for this work, the interface looks great, but the output format doesn't fit any geographic type standard which make it a no-go for usage with proper geospatial database.
I think we should be able to select the output format in a list depending on the column type, as well as the coordinates SRID, with 4326 ( WGS84) as a default.
My suggestion is:
- json: GeoJSON/custom object as `{ [lat]: ..., [lng]: ... }`.
- string: WKT/WKB/EWKT/EWKB/TWKB
- maybe csv as lat,lng or lng,lat ?

[proj4js](https://github.com/proj4js/proj4js) can be use to reproject coordinates and [wkx](https://github.com/cschwarz/wkx) to serialize to the different output formats.

**Comment by jroxendal** [comment]
Much as I sympathise with the desire to conform to various geospatial standards, I think this PR should be accepted as is. It's currently at feature parity with the map interface in Directus 8, which means it's good enough. Conforming to [insert favorit geospatial standard here] should only require a very thin plugin, which I'm sure would make a great example for the docs too!

**Comment by benhaynes** [comment]
Now that we officially support Postgres (which has a native geospatial datatype), I think we want to (first) conform to their [SQL spec](https://www.postgresql.org/docs/9.4/datatype-geometric.html)... which seems to be:

```
( x , y )
  x , y
```

This is a _super_ basic format (which I like) and is therefore a good starting point. It also satisfies the last option @Oreilles mentioned. 🙂

**Comment by Oreilles** [comment]
> Much as I sympathise with the desire to conform to various geospatial standards, I think this PR should be accepted as is. It's currently at feature parity with the map interface in Directus 8, which means it's good enough. Conforming to [insert favorit geospatial standard here] should only require a very thin plugin, which I'm sure would make a great example for the docs too!

By going for `{lon: x, lat: y}` you basically are creating a new geographic encoding format, which I think is unnecessary considering:
 1. There is no standard for it, which means it is neither interoperable nor compatible with everything else
 2. There already are many well known and working encoding format already

If supporting several output formats is out of the scope of this interface at the moment, I think we should at least stick to an already existing format.

Going for the simplest solution we can find like @benhaynes suggests is a good idea, but we should also consider iteroperability: geometry types will need to be visualized in map layouts and there is no out of the box support in any map library for postgresql geometric data types. Which means one would have to write a parser in order to convert them to a library supported standard, which means more work and computational overhead.

If we want to with one geographic type I think it should be GeoJSON. It is easy to read, fast to parse and serialize, it has semi-builtin support thanks to directus JSON field, and it is supported by every spatial processing and visualization library.

**Comment by joelarula** [comment]
Does this pull request create also standard field type for geographical point, so user can create collections with map coordinates?

**Comment by jroxendal** [comment]
> Does this pull request create also standard field type for geographical point, so user can create collections with map coordinates?

That's what we're trying to do, yeah, the last question is about how to save the geo points in the databases. 

> So { "type":"Point", coordinates: [x, y] } ; or maybe just [x, y] if size is a concern.

I'm fine with this, the more verbose version supports complex geometric shapes in the same column, if we want that for the future. 

@dimitrov-adrian, are you willing to make the necessary changes?

**Comment by dimitrov-adrian** [comment]
@jroxendal I am planing to make changes in next few days.

I like the idea of having GeoJson as a more standard format. Also thinking in supporting in CSV field type and using the (x,y) format in that case (storing only the point).

So basically if using on JSON field type then will output as GeoJson, and if used in CSV field type, then will output as x,y

@benhaynes what do you think?

**Comment by benhaynes** [comment]
I like that! Seems like a smart approach. @rijkvanzanten do you agree with this?

**Comment by rijkvanzanten** [comment]
Sounds good to me 👍🏻

**Comment by Nitwel** [comment]
This is looking good to me. @rijkvanzanten you can do a final review or merge it directly. 👍

**Comment by darioguarascio** [comment]
@rijkvanzanten do you think you can spare some time to review and merge this? it would be extremely useful. Map interface was present in directus v8 and it was a significant loss when migrating to v9

**Comment by Oreilles** [comment]
@darioguarascio  This is an old one, the PR for all the map features (interface, layout and data types) is this one https://github.com/directus/directus/pull/5684

I'm pulling  from the main branch on a regular basis as I personally use this branch. There might still be some bugs so feel free to try and report them to me.

**Comment by darioguarascio** [comment]
@Oreilles thanks. maybe it would be good to close this one then

**Comment by rijkvanzanten** [comment]
This was integrated in https://github.com/directus/directus/pull/5684

**Pull request closed without merging**
