### PR TITLE
Patch Tuesday 🐸

### PR DESCRIPTION
**Pull request by paescuj**
## `root`

- Bump pnpm to 9.0.6
- Update GitHub action

```diff
devDependencies:
- @typescript-eslint/eslint-plugin 7.1.1
+ @typescript-eslint/eslint-plugin 7.7.1
- @typescript-eslint/parser 7.1.1
+ @typescript-eslint/parser 7.7.1
- eslint-plugin-vue 9.23.0
+ eslint-plugin-vue 9.24.1
```

## `@directus/api`

```diff
dependencies:
- @aws-sdk/client-ses 3.552.0
+ @aws-sdk/client-ses 3.564.0
- encodeurl 1.0.2
+ encodeurl 2.0.0
- graphql-ws 5.15.0
+ graphql-ws 5.16.0
- inquirer 9.2.16
+ inquirer 9.2.20
- ioredis 5.3.2
+ ioredis 5.4.1
- joi 17.12.2
+ joi 17.13.0
- liquidjs 10.10.1
+ liquidjs 10.12.0
- marked 12.0.1
+ marked 12.0.2
- minimatch 9.0.3
+ minimatch 9.0.4
- openapi3-ts 4.2.2
+ openapi3-ts 4.3.1
- pino 8.19.0
+ pino 9.0.0
- pino-pretty 10.3.1
+ pino-pretty 11.0.0
- qs 6.12.0
+ qs 6.12.1
- rate-limiter-flexible 5.0.0
+ rate-limiter-flexible 5.0.3
- rollup 4.12.0
+ rollup 4.17.1
- sharp 0.33.2
+ sharp 0.33.3
- tar 6.2.0
+ tar 7.0.1
- tsx 4.7.1
+ tsx 4.7.3
- ws 8.16.0
+ ws 8.17.0
- zod 3.22.4
+ zod 3.23.4
- zod-validation-error 3.0.3
+ zod-validation-error 3.2.0

optionalDependencies:
- pg 8.11.4
+ pg 8.11.5
- tedious 17.0.0
+ tedious 18.2.0

devDependencies:
- @types/express-serve-static-core 4.17.43
+ @types/express-serve-static-core 4.19.0
- @types/node 18.19.26
+ @types/node 18.19.31
- @types/node-schedule 2.1.6
+ @types/node-schedule 2.1.7
- @types/qs 6.9.14
+ @types/qs 6.9.15
- @types/tar 6.1.11
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/app`

```diff
devDependencies:
- @editorjs/paragraph 2.11.3
+ @editorjs/paragraph 2.11.4
- @fortawesome/fontawesome-svg-core 6.5.1
+ @fortawesome/fontawesome-svg-core 6.5.2
- @fortawesome/free-brands-svg-icons 6.5.1
+ @fortawesome/free-brands-svg-icons 6.5.2
- @histoire/plugin-vue 0.17.14
+ @histoire/plugin-vue 0.17.17
- @types/lodash 4.14.202
+ @types/lodash 4.17.0
- @unhead/addons 1.8.10
+ @unhead/addons 1.9.7
- @unhead/vue 1.8.10
+ @unhead/vue 1.9.7
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- @vue/test-utils 2.4.4
+ @vue/test-utils 2.4.5
- @types/diff 5.0.9
+ @types/diff 5.2.0
- apexcharts 3.47.0
+ apexcharts 3.49.0
- cropperjs 1.6.1
+ cropperjs 1.6.2
- dompurify 3.0.11
+ dompurify 3.1.1
- editorjs-toggle-block 0.3.15
+ editorjs-toggle-block 0.3.16
- happy-dom 13.10.1
+ happy-dom 14.7.1
- histoire 0.17.14
+ histoire 0.17.17
- marked 12.0.1
+ marked 12.0.2
- mime 4.0.1
+ mime 4.0.3
- ofetch 1.3.3
+ ofetch 1.3.4
- typescript 5.3.3
+ typescript 5.4.5
- tinymce 7.0.0
+ tinymce 7.0.1
- vite 5.1.4
+ vite 5.2.10
- vitest 1.3.1
+ vitest 1.5.2
- vue 3.4.24
+ vue 3.4.26
- vue-i18n 9.10.2
+ vue-i18n 9.13.1
- vue-router 4.3.0
+ vue-router 4.3.2
- vue-tsc 2.0.7
+ vue-tsc 2.0.14
```

## `@directus/sdk`

```diff
devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/components`

```diff
devDependencies:
- @histoire/plugin-vue 0.17.14
+ @histoire/plugin-vue 0.17.17
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- histoire 0.17.14
+ histoire 0.17.17
- rollup-plugin-node-externals 7.1.1
+ rollup-plugin-node-externals 7.1.2
- typescript 5.3.3
+ typescript 5.4.5
- vite 5.1.4
+ vite 5.2.10
- vitest 1.3.1
+ vitest 1.5.2
- vite-plugin-dts 3.8.1
+ vite-plugin-dts 3.9.0
- vue 3.4.24
+ vue 3.4.26
- vue-i18n 9.10.2
+ vue-i18n 9.13.1
- vue-router 4.3.0
+ vue-router 4.3.2
```

## `@directus/composables`

```diff
devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- @vue/test-utils 2.4.4
+ @vue/test-utils 2.4.5
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
- vue 3.4.24
+ vue 3.4.26
```

## `@directus/constants`

```diff
devDependencies:
- typescript 5.3.3
+ typescript 5.4.5
```

## `create-directus-extension`

```diff
dependencies:
- inquirer 9.2.16
+ inquirer 9.2.20
```

## `@directus/env`

```diff
devDependencies:
- @types/node 18.19.26
+ @types/node 18.19.31
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/errors`

```diff
devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/extensions`

```diff
dependencies:
- zod 3.22.4
+ zod 3.23.4

devDependencies:
- @types/node 18.19.26
+ @types/node 18.19.31
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- pino 8.19.0
+ pino 9.0.0
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
- vue 3.4.24
+ vue 3.4.26
- vue-router 4.3.0
+ vue-router 4.3.2
```

## `@directus/extensions-sdk`

```diff
dependencies:
- inquirer 9.2.16
+ inquirer 9.2.20
- vue 3.4.24
+ vue 3.4.26

devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/extensions-registry`

```diff
dependencies:
- ky 1.2.3
+ ky 1.2.4
- zod 3.22.4
+ zod 3.23.4

devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/format-title`

```diff
devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/memory`

```diff
dependencies:
- ioredis 5.3.2
+ ioredis 5.4.1
- lru-cache 10.2.0
+ lru-cache 10.2.2
- rate-limiter-flexible 5.0.0
+ rate-limiter-flexible 5.0.3

devDependencies:
- @types/node 18.19.26
+ @types/node 18.19.31
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/pressure`

```diff
devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/random`

```diff
devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- @types/node 18.19.26
+ @types/node 18.19.31
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/release-notes-generator`

```diff
dependencies:
- @pnpm/workspace.pkgs-graph 2.0.15
+ @pnpm/workspace.pkgs-graph 3.0.0

devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- @types/node 18.19.26
+ @types/node 18.19.31
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/schema`

```diff
devDependencies:
- npm-watch 0.11.0
+ npm-watch 0.12.0
- typescript 5.3.3
+ typescript 5.4.5
```

## `@directus/storage`

```diff
devDependencies:
- @types/node 18.19.26
+ @types/node 18.19.31
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/storage-driver-azure`

```diff
devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/storage-driver-cloudinary`

```diff
dependencies:
- undici 6.10.2
+ undici 6.14.1

devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/storage-driver-gcs`

```diff
dependencies:
- @google-cloud/storage 7.10.0
+ @google-cloud/storage 7.10.2

devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/storage-driver-local`

```diff
devDependencies:
- @types/node 18.19.26
+ @types/node 18.19.31
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/storage-driver-s3`

```diff
dependencies:
- @aws-sdk/client-s3 3.536.0
+ @aws-sdk/client-s3 3.564.0
- @aws-sdk/lib-storage 3.525.1
+ @aws-sdk/lib-storage 3.564.0
- @smithy/node-http-handler 2.4.1
+ @smithy/node-http-handler 2.5.0

devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/storage-driver-supabase`

```diff
dependencies:
- undici 6.10.2
+ undici 6.14.1

devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/stores`

```diff
devDependencies:
- typescript 5.3.3
+ typescript 5.4.5
- vue 3.4.24
+ vue 3.4.26
```

## `@directus/system-data`

```diff
devDependencies:
- esbuild 0.20.1
+ esbuild 0.20.2
- typescript 5.3.3
+ typescript 5.4.5
```

## `@directus/themes`

```diff
dependencies:
- @sinclair/typebox 0.32.20
+ @sinclair/typebox 0.32.27

devDependencies:
- @unhead/vue 1.8.10
+ @unhead/vue 1.9.7
- typescript 5.3.3
+ typescript 5.4.5
- rollup-plugin-node-externals 7.1.1
+ rollup-plugin-node-externals 7.1.2
- vite 5.1.4
+ vite 5.2.10
- vite-plugin-dts 3.8.1
+ vite-plugin-dts 3.9.0
- vue 3.4.24
+ vue 3.4.26
```

## `@directus/types`

```diff
devDependencies:
- typescript 5.3.3
+ typescript 5.4.5
- vue 3.4.24
+ vue 3.4.26
```

## `@directus/update-check`

```diff
dependencies:
- axios-cache-interceptor 1.5.1
+ axios-cache-interceptor 1.5.2

devDependencies:
- @types/node 18.19.26
+ @types/node 18.19.31
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `@directus/utils`

```diff
dependencies:
- joi 17.12.2
+ joi 17.13.0

devDependencies:
- @types/node 18.19.26
+ @types/node 18.19.31
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
- vue 3.4.24
+ vue 3.4.26
```

## `@directus/validation`

```diff
dependencies:
- joi 17.12.2
+ joi 17.13.0

devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
```

## `tests/blackbox`

```diff
devDependencies:
- @vitest/coverage-v8 1.4.0
+ @vitest/coverage-v8 1.5.2
- graphql-ws 5.15.0
+ graphql-ws 5.16.0
- listr2 8.0.2
+ listr2 8.2.1
- typescript 5.3.3
+ typescript 5.4.5
- vitest 1.3.1
+ vitest 1.5.2
- supertest 6.3.4
+ supertest 7.0.0
- ws 8.16.0
+ ws 8.17.0
```

## `docs`

```diff
devDependencies:
- typedoc-vitepress-theme 1.0.0-next.9
+ typedoc-vitepress-theme 1.0.0-next.10
- typedoc 0.25.12
+ typedoc 0.25.13
- @pnpm/find-workspace-dir 6.0.3
+ @pnpm/find-workspace-dir 7.0.0
- marked 12.0.1
+ marked 12.0.2
- typescript 5.3.3
+ typescript 5.4.5
- vue 3.4.24
+ vue 3.4.26
```

### CODE REVIEW

**Review by hanneskuettner — COMMENTED** [review]
One thing I found, that I can not make any comments on:

- `ws 8.17.0` makes the following breaking change https://github.com/websockets/ws/releases/tag/8.17.0


One nitpick in your description:

`@types/tar` was dropped instead of upgraded, since `tar` comes with types now

**Comment by paescuj** [comment]
> One thing I found, that I can not make any comments on:
> 
>     * `ws 8.17.0` makes the following breaking change https://github.com/websockets/ws/releases/tag/8.17.0

I don't think we rely on specific ordering of these events which could potentially be affected by this change.
 
> One nitpick in your description:
> 
> `@types/tar` was dropped instead of upgraded, since `tar` comes with types now

Thanks, had the "dropping" listed under `dependencies` instead of `devDependencies` 😅 Updated now 👍

**Comment by br41nslug** [comment]
After looking into the `ws` upgrade I can confirm we are not relying on that specific flag so should be unaffected

**Review by hanneskuettner — APPROVED** [review]
App runs, API runs, looked through all changelogs, saw no other breaking changes.

LGTM 🎸

**Pull request merged**
