### PR TITLE
Allow to catch errors that can happen when login with auth provider

### PR DESCRIPTION
**Pull request by gkielwasser**
Login might fail before any login hooks are triggered.

It allows to handle exception that might be thrown by `getUserId` when email is not unique.

Refer to discussion https://github.com/directus/directus/discussions/10948

### CODE REVIEW

**Comment by aidenfoxx** [comment]
Personally I'd just move the `emitStatus` helper function up and call that with 'error'. But I guess it's up to @rijkvanzanten if he wants this on a separate hook call.

**Comment by gkielwasser** [comment]
Here are some additional informations, 

To be able to react to this exception we would need to use either `filter('auth.login')` or `filter('request.error')`. Otherwise application cannot "transform" the error. I'm not sure which one is most appropriated but if I'm not wrong `request.error` is meant to expose error information.

My concrete usecase is I want to expose some sensitive information like what should be the proper provider to use if the email is already taken. As it is very opinionated I think it should be handle case by case. So instead of returning the original error thrown by the login, I return a custom method `getSuggestedAuthFlow(email)` . In order to do that I need to intercept and transform the error before it is actually returned to the client.

**Comment by gkielwasser** [comment]
@ri

> Here are some additional informations,
> 
> To be able to react to this exception we would need to use either `filter('auth.login')` or `filter('request.error')`. Otherwise application cannot "transform" the error. I'm not sure which one is most appropriated but if I'm not wrong `request.error` is meant to expose error information.
> 
> My concrete usecase is I want to expose some sensitive information like what should be the proper provider to use if the email is already taken. As it is very opinionated I think it should be handle case by case. So instead of returning the original error thrown by the login, I return a custom method `getSuggestedAuthFlow(email)` . In order to do that I need to intercept and transform the error before it is actually returned to the client.

What do you think about this PR @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
> Personally I'd just move the emitStatus helper function up and call that with 'fail'. But I guess it's up to @rijkvanzanten if he wants this on a separate hook call.

I agree with this. Lets rely on the existing `emitStatus` with the information 👍🏻

**Pull request closed without merging**
