### PR TITLE
Fix `MariaDB` erroring on column info introspection

### LINKED ISSUE #23486: MariaDB errors on introspection
### Describe the Bug

While testing something for MariaDB, I noticed that it throws an error after logging in (or more specifically: when introspecting the database). In the logs in basically says

```
You have an error in your SQL syntax;
```
In the UI you see this after logging in.

Screenshot 2024-08-26 at 10 40 14

It seems something is wrong with the last join of the `columnInfo` introspection query.

### To Reproduce

- Setup a MariaDB (Docker image `mariadb:11.4`) 
- Bootstap the database with the Directus tables 
- Start the server and the editor
- Log in. You will see the unexpected error

### Directus Version

main

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MariaDB

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- `MySQL` no longer utilizes a lateral join for column index introspection as it is not supported by `MariaDB`.

## Potential Risks / Drawbacks

- None, although as a left join the changes can result in duplicated results this should not be an issue as the MySQL inspector/dialect de-duplicates columns via post-processing https://github.com/directus/directus/blob/0737935cba1dbd5d09997a831818a0cd57990989/packages/schema/src/dialects/mysql.ts#L314

## Review Notes / Questions

- Alternative solutions for this query are welcome.
- As the index support feature has not yet been released this PR does not require a changeset.

---

Fixes #23486

### CODE REVIEW

**Comment by hanneskuettner** [comment]
Can the index of doubly indexed columns still be removed? What is the removal logic here? Does it take the index name into account or always go for the default name?

**Comment by ComfortablyCoding** [comment]
> Can the index of doubly indexed columns still be removed? What is the removal logic here? Does it take the index name into account or always go for the default name?

Yes, it can be removed. It does not take into account the index name, it always uses the default generated name by knex. This is inline with how unique works as well.

**Comment by hanneskuettner** [comment]
> For multiple indexed columns it will always remove the index that matches the knex default name first.

> It does not take into account the index name and uses the knex default every time, this is inline with how unique works as well.

Won't it be always stuck on indexed then, because the introspection query find the next index for that column? And not work for users that have custom names for their indices?

**Comment by ComfortablyCoding** [comment]
> > For multiple indexed columns it will always remove the index that matches the knex default name first.
> 
> > It does not take into account the index name and uses the knex default every time, this is inline with how unique works as well.
> 
> Won't it be always stuck on indexed then, because the introspection query find the next index for that column? And not work for users that have custom names for their indices?

Yes, that is correct. This is the case for a single index as well that is not inline with knex's naming scheme, it will error if the user attempts to remove it via the app/api. This is not specific to this PR, it was the same functionality in the original index PR as well. This works the same for unique as well.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
