### PR TITLE
Full page layout property, header bar collapsed state store

### PR DESCRIPTION
**Pull request by oreilles**
Solution to https://github.com/directus/directus/discussions/3631

Header bar collapsed state in now stored in the appStore.
Layout can now be defined with a `fullPage: boolean` attribute, which would cause the class `full-page` to be added to the `private-view` container when that layout is shown.
To do that cleanly, `getLayouts` is now called in the `collection` component rather than in `sidebar-detail`.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
> Layout can now be defined with a fullPage: boolean attribute, which would cause the class full-page to be added to the private-view container when that layout is shown.

This makes total sense to me, but why do we need:

> Header bar collapsed state in now stored in the appStore.

? I'm a little worried about that state accidentally persisting between navigations / updates on the page 🤔

**Comment by Oreilles** [comment]
I left it in case it would be a information needed for some features, like for the sidebar (different behaviour on layout change ?) but it's not required for the fullPage attribute to work so it may go away!

Considering the current implementation, I just set the header's top and margin bottom to 0 if the layout is a full page, but there is no animation or anything. It turns out that animations on margin are really slow and it looked terrible. I left it that way so that the PR stays cleen. In order to have a good looking transition, we would need to do it otherwise. There would be several solutions but I couldn't find one without drawbacks.

**Comment by rijkvanzanten** [comment]
@Oreilles We already have a collapsed state (with animation) on scroll regularly, can we reuse that class instead of setting a different style?

**Comment by Oreilles** [comment]
Then it we would easier to have it as a store, as we would otherwise need to pass the fullPage prop all the way down to the header.
Also, I think I initially tried but there was an issue with the fact that the header is `sticky` positioned. So it has a bottom margin when at the top position, but that margin *disappear* when the page is scrolled below. If we reuse the 'collapsed' class for the full page layouts then the margin stays. For it to look as expected, the collapsed state need to have a `margin-bottom` to 0, but then it screws the page position when that state transition as the user scrolls down the page.

**Comment by rijkvanzanten** [comment]
> Then it we would easier to have it as a store, as we would otherwise need to pass the fullPage prop all the way down to the header. 😁

As long as we're absolutely sure there's no possibility that the header ends up in the wrong state between navigations/updates, I'm ok with it ^^

> A solution to that would be to just take the header out of the flow, make it absolutely positioned to top, apply the margin to the layout container <main>, and apply the header a transform when it has the class collapsed. It would also allow butter smooth transition.

Not as easy as it sounds ^^ I spent weeks on layouting the different parts to make sure everything works within the scrolling contexts 😁

**Comment by Oreilles** [comment]
Ultimately I think that header should always be in the collapsed format, only the shadow should change. 😇

**Comment by rijkvanzanten** [comment]
haha, that's an easy solution to a hard problem. We actually tried that, but it's way too cramped to open with. Having it bigger without a shadow opens up the page a bit and makes it feel more relaxed. Only collapsing it on scroll changes the user's focus to the page content, and removes some clutter from the headline, decreasing the presence of the header 🙂

**Comment by Oreilles** [comment]
You're right. 😉 Although it's totally different, I like the way Notion solves this:
Capture d’écran 2021-01-11 à 17 45 28
Capture d’écran 2021-01-11 à 17 45 48
Capture d’écran 2021-01-11 à 17 46 29

**Comment by benhaynes** [comment]
Interesting approach. Would really push down content on a a lot of page though — eg: table listing. I'm down to look into ways to optimize/improve this, but for now, let's move forward with our current shrink+shadow way. 👍

**Comment by Oreilles** [comment]
I turned this in every way and just can't see a way to have a smooth transition while keeping the current behaviour.

**Comment by Oreilles** [comment]
Here's what the transition looks like, it's kind of meh but it's that or no transition, not sure what's best! If we choose another implementation it will probably require changes in the current behaviour.

https://user-images.githubusercontent.com/33065839/104237102-d9ece100-5457-11eb-929a-5cb87a29981f.mp4

**Comment by benhaynes** [comment]
I actually think that works pretty well! The fact that there's no spacing between the search and item count is driving me nuts... but that's a separate issue. 😉

**Comment by rijkvanzanten** [comment]
If mapbox is that heavy, we might want to delay loading it for like 500ms to open up the main thread a bit for the navigation and all other stuff

**Comment by Oreilles** [comment]
> The fact that there's no spacing between the search and item count is driving me nuts

Oh, I didn't even notice that..! Yes I didn't included the css for that part of the layout, I'll fix it right away.

> If mapbox is that heavy, we might want to delay loading it for like 500ms to open up the main thread a bit for the navigation and all other stuff

I added a small delay to the transition in this commit but that's actually a much better option, I'll try that.

**Comment by benhaynes** [comment]
Oh, haha, I wasn't commenting on _your_ implementation of that padding... I actually thought that was off in all of Directus. Glad it's fixed though! 😄

**Comment by Oreilles** [comment]
Not sure what would the best way to delay the map loading though. Mapbox and the actual map are loaded within a nested component of the layout.

**Comment by Oreilles** [comment]
Closing as it has been implemented in the map-layout branch.

**Pull request closed without merging**
