### PR TITLE
Add CSV/JSON Import capability via App

### PR DESCRIPTION
**Pull request by azrikahar**
Implements #7246
Resolves directus/organization#22

## Context

Currently we can use [`/utils/import/:collection`](https://docs.directus.io/reference/system/utilities/#import-data-from-file) endpoint to import records to a collection. This PR adds the same functionality via the App UI.

## Changes

- App
  - [x] Import Data sidebar for collections
  - [x] Change Export Data's button to "Start Export" for consistency
- Api
  - [x] add `application/vnd.ms-excel` to allowed MIME types as CSV since that is the mime type sent on a Windows machine with Microsoft Excel installed. [Reference](https://christianwood.net/posts/csv-file-upload-validation/)
- Docs
  - [x] Add Importing Items section to https://docs.directus.io/app/content-collections/
  - [x] Update Exporting Items section

## Result

https://user-images.githubusercontent.com/42867097/149526801-622750de-a960-4bbe-9a14-5b6611892247.mp4

### CODE REVIEW

**Comment by LasseRosenow** [comment]
I am wondering, what to do if imported CSV file format is not completely compatible with the collection format.

What about adding options based on what the CSV contains to select which columns should be mapped to which properties of the collection?

**Comment by rijkvanzanten** [comment]
> Just curious, but would it be possible to somehow programmatically check if a file has already been imported? If we think it has, we could offer a modal confirming that the user wants to import.

Not necessarily, unless we add a list somewhere of files we've imported before (so we can compare hashes) 🤔 

> What about adding options based on what the CSV contains to select which columns should be mapped to which properties of the collection?

I'd love to have that, and certainly think we should look into adding that. That being said, lets do that in another cycle to not get too bogged down in this particular PR (which is already a great improvement in and of itself :) )

**Comment by benhaynes** [comment]
I agree, stick to MVP. Maybe new tickets once this is done if we think they're worth it.

**Comment by leonardomdr** [comment]
Not sure if this is implemented here, but would be good to have a action trigger when the import has been done.

**Comment by azrikahar** [comment]
> Not sure if this is implemented here, but would be good to have a action trigger when the import has been done.

It's not included here since this PR just aims to make the existing `/utils/import/:collection` endpoint usable via the App, but it does sound like a great addition once the import logic itself undergoes some potential changes (still in discussion). 👍

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
