### PR TITLE
Set calendar height to 100%

### LINKED ISSUE #9166: Calendar Layout Height
Currently, the calendar layout is set to 800px tall, this needs to be dynamic based on the page. You have to scroll-y on smaller screens, and have lots of blank space on larger screens. We should use the height param to get this dynamic... with some proper min-height (to start scrolling):

https://fullcalendar.io/docs/height

### PR DESCRIPTION
**Pull request by oreilles**
Fix https://github.com/directus/directus/issues/9166
The `smallHeader` attribute has been set to true, so the layout no longer scrolls.
We could use the `clamp()` css function if we want to also set min/max height instead of having it always be `100%`.

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
@Oreilles Is there a way we can make this work without relying on smallHeader? 

The spacing is a little out of wack otherwise:

Current:


CleanShot 2021-11-01 at 11 23 03@2x

Intended:

CleanShot 2021-11-01 at 11 22 13@2x

**Comment by Oreilles** [comment]
Unset `smallHeader` and adjusted the layout height. Still no scroll, but now the header has its full height.

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Thank you! 💙🤍❤️

**Comment by benhaynes** [comment]
@Oreilles — is it possible to have a min-height... or a breakpoint when the viewport height gets too small? It'd be nice to have this calendar scroll-y when we get below something like 700px tall. Thoughts?

**Comment by Oreilles** [comment]
Totally possible, the `height` prop should accept any css value like `max(100%, 700px)` or `clamp(700px, 100%, 1200px)` if you also want an upper bound.

**Comment by benhaynes** [comment]
I think the physical size limitations of screens can be out upper bound, but good to know! Thanks, @Oreilles!! Good to wrap up all these Layouts!

**Pull request merged**
