### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by DanielBiegler**
Copyright year was out of date :smile: :+1:

### CODE REVIEW

**Comment by ComfortablyCoding** [comment]
Dankeschoen ❗

**Comment by ComfortablyCoding** [comment]
Should the license years be updated as well?

**Comment by paescuj** [comment]
> Should the license years be updated as well?
> 
> https://github.com/directus/directus/blob/7f14e387edebbe1a7174705ea16950376a6a6d84/sdk/license#L3
> 
> https://github.com/directus/directus/blob/7f14e387edebbe1a7174705ea16950376a6a6d84/license#L4

Yeah, recently stumbled upon this and was wondering the same.
There are different views on this when asking the Internet, but on sites like https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated the general opinion seems to be that we don't have to.

**Review by ComfortablyCoding — CHANGES_REQUESTED** [review]
Per Rijk, we should update the years of the license(s) as well.

**Review by licitdev — APPROVED** [review]
```ts
new Date().getFullYear(); // 2024
```

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀

**Pull request merged**
