### PR TITLE
Fix updates on unsigned integer fields for MySQL

### LINKED ISSUE #7808: "Allow null value"can't be changed on relation fields
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Changing "allow null value" on m2o fields causes a Mysql error

### To Reproduce

Create collection A
Create collection B
Create field relation in B as many to one relation with A : 
- "Allow null value" : true 
- Relation Triggers : Nullify the relation fields
Update value of "Relation Triggers" of field relation to "Prevent the deletion" (Sometimes Directus throw a Db error)
Update value "Allow null value" of field relation to false 
Directus throw a Db error

### What version of Directus are you using?

rc91

### What version of Node.js are you using?

16

### What database are you using?

Mysql 8.0.23

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Fixes #7808

### Problem

This issue has been reported numerous times and has been MySQL specific. Thanks to #14105, it brought to the attention that whenever we're updating a M2O that references a relational table that has auto-increment ID, it attempts to alter it as `int` instead of `int unsigned`.

This is because Knex mysql dialect specifically creates unsigned int for `increments()`: https://github.com/knex/knex/blob/d371c0424a92bda9fde35839a020fe9eec416a60/lib/dialects/mysql/schema/mysql-columncompiler.js#L166-L175

which is happening here:

https://github.com/directus/directus/blob/a7d96713724747b0dad08d6279406db5591200db/api/src/services/fields.ts#L557

However whenever we're updating/altering the column, only the field type which is `integer` is used here:

(such that it becomes `table.integer(field.field)`)

https://github.com/directus/directus/blob/a7d96713724747b0dad08d6279406db5591200db/api/src/services/fields.ts#L575

hence it attempts to alter it as from `int unsigned` to `int`.

### Solution

Made sure to chain `unsigned()` based on the relevant data types, as described in Knex docs: http://knexjs.org/guide/schema-builder.html#unsigned. Did a more verbose check rather than if the field contains `unsigned` just as a stricter measure, but we can loosen it if that's too verbose.

The test is also slightly specific for this scenario (PATCH request to change M2O to non-nullable), aside from the general CRUD actions. Hopefully that's okay, as all the fields and field types permutations can become quite hefty, and I assume we can offload this to the blackbox testing 😅

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by azrikahar** [comment]
Although this solution seems to work, but it consistently fails on the _first_ attempt after the field is newly created, and always succeeds on future attempts onwards:

https://user-images.githubusercontent.com/42867097/175950346-8f436e53-2d26-4a25-992c-b99a499eac35.mp4

Not sure if this is schema cache related or the solution is too crude. Will need to resolve this to get this out of draft. 🤔

**Comment by azrikahar** [comment]
Seems like it is actually not cache related, but something to do with side effects to the constraint. 🤔

When it is `SET NULL`, we'll receive this error _only during the first time_. As it turns out even when it errors, the constraint will be changed from `SET NULL` to `RESTRICT`. This makes any future changes work without any issue anymore:

https://user-images.githubusercontent.com/42867097/179740574-26346096-f82c-420a-9539-e0ab133f50a8.mp4

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Comment by g-30** [comment]
@rijkvanzanten  this is still relevant. Changing any property of a field that is associated with a foreign key results in this error for me:
```
ERROR: alter table `payments` modify `course_id` int - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'course_id': used in a foreign key constraint 'payments_course_id_foreign'
```
also related to #10932, #9897 and perhaps #14105.

**Comment by iksent** [comment]
Same for me. This happens while `npx directus schema apply --yes ./snapshot.yaml`

```
[11:48:53.390] ERROR: Failed to update field "article_translations.article_id"
[11:48:53.391] ERROR: alter table `article_translations` modify `article_id` int - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'article_id': used in a foreign key constraint 'article_translations_article_id_foreign'
    err: {
      "type": "Error",
      "message": "alter table `article_translations` modify `article_id` int - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'article_id': used in a foreign key constraint 'article_translations_article_id_foreign'",
      "stack":
          Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'article_id': used in a foreign key constraint 'article_translations_article_id_foreign'
              at Sequence._packetToError (/<path>/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
              at Query.ErrorPacket (/<path>/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
              at Protocol._parsePacket (/<path>/node_modules/mysql/lib/protocol/Protocol.js:291:23)
              at Parser._parsePacket (/<path>/node_modules/mysql/lib/protocol/Parser.js:433:10)
              at Parser.write (/<path>/node_modules/mysql/lib/protocol/Parser.js:43:10)
              at Protocol.write (/<path>/node_modules/mysql/lib/protocol/Protocol.js:38:16)
              at Socket.<anonymous> (/<path>/node_modules/mysql/lib/Connection.js:88:28)
              at Socket.<anonymous> (/<path>/node_modules/mysql/lib/Connection.js:526:10)
              at Socket.emit (node:events:513:28)
              at addChunk (node:internal/streams/readable:324:12)
              --------------------
              at Protocol._enqueue (/<path>/node_modules/mysql/lib/protocol/Protocol.js:144:48)
              at Connection.query (/<path>/node_modules/mysql/lib/Connection.js:198:25)
              at /<path>/node_modules/knex/lib/dialects/mysql/index.js:132:18
              at new Promise (<anonymous>)
              at Client_MySQL._query (/<path>/node_modules/knex/lib/dialects/mysql/index.js:126:12)
              at executeQuery (/<path>/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
              at Client_MySQL.query (/<path>/node_modules/knex/lib/client.js:146:12)
              at /<path>/node_modules/knex/lib/execution/transaction.js:363:24
              at new Promise (<anonymous>)
              at trxClient.query (/<path>/node_modules/knex/lib/execution/transaction.js:358:12)
      "code": "ER_FK_COLUMN_CANNOT_CHANGE",
      "errno": 1832,
      "sqlMessage": "Cannot change column 'article_id': used in a foreign key constraint 'article_translations_article_id_foreign'",
      "sqlState": "HY000",
      "index": 0,
      "sql": "alter table `article_translations` modify `article_id` int"
    }
```

**Pull request closed without merging**
