### PR TITLE
Extension Management

### LINKED ISSUE #17694: env EXTENSIONS_AUTO_RELOAD not working with bundle extensions
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

The env setting EXTENSIONS_AUTO_RELOAD is working fine with any other extension except bundle extensions.

### To Reproduce

Create a bundle extension and set `EXTENSIONS_AUTO_RELOAD=true` in your directus env settings. 

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by Nitwel**
## Description

Adds in the ability to manage extensions from the admin panel. Right now it's only possible to enable or disable extensions. The preview for extensions look like this at the moment:

Bildschirmfoto am 2023-01-11 um 12 54 04

closes #17694

## Featues
- New table `directus_extensions` with `name: string`, `enabled: boolean` and `options: JSON`
- Endpoints to configure extensions including:
  - Editing the enabled status
  - Configuring options for extensions (Right now only implemented for future use)
  - Getting Information about currently installed extensions (e.g. name, description and so on)
- App interface to view and enable / disable extensions.

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [x] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@Nitwel Moving this to draft, seeing all the linter warnings / commented out codeblocks etc. Lmk when this is ready for review!@

**Comment by danieljwestman** [comment]
Any progress? 😊

**Comment by ConnorSimply** [comment]
@Nitwel I installed 2 interfaces to test this, one via `index.js` file directly in the extensions folder and one via npm. Neither showed up in the extensions list to enable/disable. I must be missing something, any guidance?

**Comment by Nitwel** [comment]
Did you get some sort of error in the console @ConnorSimply?
When you are able to see the installed extensions in Directus, you should also be able to see them there.

**Comment by ConnorSimply** [comment]
@Nitwel There were no errors when I tested this. However, did notice some things.I had to rebuild dev to get the package installed via pnpm to show up, thats ok. I installed two packages one via pnpm and one with an index file in the extensions folder. The installed via pnpm showed up in the list, the index file one did not.

The interface I installed via pnpm and is in the list was a display. Enabling and disabling the extension did nothing, and when the extension was disabled it still used the display extension.

Is it supposed to enable/disable only certain types of extensions or should it work on all of them?

**Comment by rijkvanzanten** [comment]
@Nitwel Mind resolving the merge conflicts and providing a description of what this PR adds and how it works exactly? 🙂 the UI screenshot itself is obvious, but I'm very curious to learn more about new endpoints, database tables, etc

**Comment by Nitwel** [comment]
Updated the PR description with more info.

**Comment by danieljwestman** [comment]
Hey @Nitwel ! Anything stopping this great PR? Hope to get this going asap 🙏🏼

**Comment by danieljwestman** [comment]
Feels like this PR is forgotten 😢

**Comment by Nitwel** [comment]
Not really, there are just way bigger things cooking in the background that will outdo this quite a lot.

**Comment by danieljwestman** [comment]
Okay, Marketplace... 
https://directus.market/

**Comment by paescuj** [comment]
Closing in favor of  #19506 and #19507 🎉

**Pull request closed without merging**
