### PR TITLE
Extension Improvements

### PR DESCRIPTION
**Pull request by Nitwel**
## Description

This PR introduces the following new features:
- top level extensions support in local `/extensions` folder
- extension-sdk link command to create symlinks
- scripts to package.json of extensions so you don't have to remember `link` or `add` commands.

Also removes the pack type extension as it currently had no use and might not make sense to have as an separate extension type.

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [x] New Feature
- [x] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [x] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by piotr-cz** [comment]
Does it add similar functionality as [npm workspaces](https://docs.npmjs.com/cli/v7/configuring-npm/package-json?v=true#workspaces)?

**Review by br41nslug — APPROVED** [review]
Works very well in my tests and will help a ton in bundle extension development with docker

**Comment by abdonrd** [comment]
I see this in the release: https://github.com/directus/directus/releases/tag/v9.22.2

There are docs about it?

**Comment by paescuj** [comment]
As far as I know, this has not made it into the documentation yet. Would you mind opening an issue over there? 😃 https://github.com/directus/docs/issues

**Comment by abdonrd** [comment]
Would it be possible to have a brief explanation here while the documentation is not updated? Thanks! 🙏

**Comment by piotr-cz** [comment]
Looking at at the [source code](https://github.com/directus/directus/pull/16822/files#diff-efe34680db009abf06c09f80a2ec31f66a73cc70dddaec34a17dfc1990568935), there has been new command added `directus-extension link` with such description:
*Creates a symlink to the extension in the Directus extensions folder*

**Comment by Nitwel** [comment]
Basically, what this added is that you now can put your extensions into the extensions folder without worrying if you have put it in the right subfolder. That would something like:
```
/extensions
  /interfaces
  /displays
  /my-extension
    /dist
      index.js
    package.json
    README.md
  /operations
  ...and so on
```

And the other thing is that you now have a link command that creates a symlink to the desired /directus/extensions folder. Basically just a alias for crating a symlink on any platform.

**Comment by abdonrd** [comment]
Thanks both! We will try it!

**Comment by abdonrd** [comment]
@Nitwel I was trying and only works if the folder name starts with `directus-extension-`. Like:

```
/extensions
  /interfaces
  /displays
  /directus-extension-my-extension
    /dist
      index.js
    package.json
    README.md
  /operations
  ...and so on
```

This is expected?

**Comment by Nitwel** [comment]
Yes, this is to be expected.

**Pull request merged**
