### PR TITLE
Added more detailed oAuth configuration docs.

### PR DESCRIPTION
**Pull request by theonlynexus**
I wasn't exactly sure if the documentation for  `OAUTH_PROVIDERS` was the correct spot. Please feel free to move those paragraphs to a more appropriate location.

### CODE REVIEW

**Comment by benhaynes** [comment]
Thank you! We'll review this week!

**Review by rijkvanzanten — APPROVED** [review]

**Comment by emregency** [comment]
@theonlynexus thanks so much for the info! It allowed me configuring Azure AD as OAuth provider. Just a question, I needed to use the tenant ID in the endpoints as stated in the docs below.
https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app?tabs=dotnet#azure-ad-authority

and the `Application client ID` as the `OAUTH_MICROSOFT_KEY`. 

How did you manage to use the `application_id` in both places?

**Comment by theonlynexus** [comment]
@emregency Hi, I actually used the *Application (client) ID* as shown in the commit.
```
OAUTH_MICROSOFT_AUTHORIZE_URL = "https://login.microsoftonline.com/<microsoft_application_id>/oauth2/v2.0/authorize"
OAUTH_MICROSOFT_ACCESS_URL = "https://login.microsoftonline.com/<microsoft_application_id>/oauth2/v2.0/token
```

Yet it should be pretty easy to replace it with the *Directory (tenant) ID* if that's what you need. Just get the value from the Azure App Registration Overview page (see image below).

image

You can also easily copy the endpoints from the *Endpoints* section.

**Comment by emregency** [comment]
Thanks @theonlynexus ! It just didn’t work with the application_id 🤔, I had to use the tenant.

**Pull request merged**
