### PR TITLE
Port remaining tests into E2E blackbox

### LINKED ISSUE #14435: Port remaining E2E tests to blackbox
Once https://github.com/directus/directus/pull/13200 is merged, we should port over the remaining e2e tests, and remove the `/tests` folder in favor of only having the superior blackbox tests.

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Fixes #14435, fixes ENG-226

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [x] Other, please describe: Migration of tests

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]
LGTM!

**Review by br41nslug — APPROVED** [review]
Looking good and tests passing locally

**Comment by paescuj** [comment]
Awesome @licitdev! I was very much looking forward to this 😄

**Comment by Unified231** [comment]
Looking good and tests progress passing locally

**Pull request merged**
