### PR TITLE
Added `DB_INCLUDE_TABLES` env variable

### PR DESCRIPTION
**Pull request by AaronBeaudoin**
To address #11001.

I'll be the first to admit this code is a bit rough, so hopefully after taking a look it should only take a few minutes to tweak it to the best standard.

Also the table entry in the doc config table could probably be a bit more clear that when the setting is not specified it just includes all tables not specified in `DB_EXCLUDE_TABLES`, but I'm having trouble finding a clear and concise way to communicate that.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I'd rather not have both exclude _and_ include, and have the value of one conflict with the value of the other 🤔 Is there a way we can combine the functionality into a single env var?

We might be able to support regexes in the exclude env var, which in turn might allow for using a "match everything, except (X, Y, Z)" type settings (`^((?!articles).)*$`) (paging resident regex expert @nickrum)

**Comment by nickrum** [comment]
Supporting regexes in the exclude env var should be relatively easy to implement. Though, (negative) lookaround operations in regexes are sometimes tricky to wrap your head around and might be a bit overkill for something as simple as defining an include-list of tables.

The regex `^((?!articles).)*$` would actually match any table name that doesn't _contain_ "articles". The regex to match any table name that doesn't _equal_ "articles" would be something like `^(?!articles$).*`.

Most Javascript tools working on files support both include and exclude glob file path options. The include option is processed first. If it has been set, all files matching the option are included, else all files are included. The exclude option is then processed on top of what has been matched before in a similar fashion. Maybe we can take some inspiration from that in addition to adding regex support to `DB_EXCLUDE_TABLES`.

**Comment by molszanski** [comment]
I think it would be best to use something like `.gitignore`. Maybe there is a well-known-but-not-to-me pattern for that? 
If could serialize `.tableignore` into ENV that would be good enough IMO. 
On simpler not, we could ask users to serialize JSON into ENV. It is a pretty common practice.

**Comment by AaronBeaudoin** [comment]
Here are my thoughts.

> I think it would be best to use something like `.gitignore`. Maybe there is a well-known-but-not-to-me pattern for that?
If could serialize `.tableignore` into ENV that would be good enough IMO.
On simpler not, we could ask users to serialize JSON into ENV. It is a pretty common practice.

While I agree that `.gitignore` is a common pattern, in all cases I've seen it used it is being used to filter/exclude **files/folders**, hence the usage of glob. A similar concept, but I don't think a `.<whatever>ignore` file is the best approach personally since we're not working with files/folders here.

> Most Javascript tools working on files support both include and exclude glob file path options. The include option is processed first. If it has been set, all files matching the option are included, else all files are included. The exclude option is then processed on top of what has been matched before in a similar fashion. Maybe we can take some inspiration from that in addition to adding regex support to `DB_EXCLUDE_TABLES`.

I agree that having both "include" and "exclude" variables is a pretty common pattern. The way I implemented it here the exclude tables are filtered out before the include tables are processed (since the exclude tables are an existing option I wanted to ensure the current behavior is preserved), but as far as I can think of, flipping it would result in the same behavior. It is missing regex support, but there's no reason that couldn't be added later, right? 

_Also, I just realized that the current behavior allows you to put `directus_<whatever>` tables in the exclude list, which probably shouldn't be possible because it breaks things. Just a thought._

> We might be able to support regexes in the exclude env var, which in turn might allow for using a "match everything, except (X, Y, Z)" type settings (`^((?!articles).)*$`)

I like the idea of using regexes for this. To be honest, I just put together the minimum necessary implementation to support my use case so I can get up and running successfully with Directus. Perhaps regexes can be implemented later if necessary?

In any case, what would you guys like me to do right now to make this pull request mergable?

**Comment by rijkvanzanten** [comment]
> Here are my thoughts.
> 
> > I think it would be best to use something like `.gitignore`. Maybe there is a well-known-but-not-to-me pattern for that?
> > If could serialize `.tableignore` into ENV that would be good enough IMO.
> > On simpler not, we could ask users to serialize JSON into ENV. It is a pretty common practice.
> 
> While I agree that `.gitignore` is a common pattern, in all cases I've seen it used it is being used to filter/exclude **files/folders**, hence the usage of glob. A similar concept, but I don't think a `.<whatever>ignore` file is the best approach personally since we're not working with files/folders here.

Fully agreed on this. We shouldn't start relying on additional configuration files. This should be configured in the environment variables.

> > Most Javascript tools working on files support both include and exclude glob file path options. The include option is processed first. If it has been set, all files matching the option are included, else all files are included. The exclude option is then processed on top of what has been matched before in a similar fashion. Maybe we can take some inspiration from that in addition to adding regex support to `DB_EXCLUDE_TABLES`.
> 
> I agree that having both "include" and "exclude" variables is a pretty common pattern, even outside of working with files/folders (think IP address whitelist/blacklists, for example). The way I implemented it here the exclude tables are filtered out before the include tables are processed (the exclude tables are an existing option and it was easier to ensure the current behavior is not interfered with), but as far as I can think of, flipping it would result in the same behavior. It is missing regex support, but there's no reason that couldn't be added later, right?

Fair enough! If you both feel like it's an appropriate direction, I can be convinced 👍🏻 I just want to make sure that it is "obvious" in how it works, either through proper documentation, or by working in a standardized fashion.

> _Also, I just realized that the current behavior allows you to put `directus_<whatever>` tables in the exclude list, which probably shouldn't be possible because it breaks things. Just a thought._

Yeah good one, that feels like a foot-gun.

> > We might be able to support regexes in the exclude env var, which in turn might allow for using a "match everything, except (X, Y, Z)" type settings (`^((?!articles).)*$`)
> 
> I like the idea of using regexes for this. To be honest, I just put together the minimum necessary implementation to support my use case so I can get up and running successfully with Directus. Perhaps regexes can be implemented later if necessary?

Haha fair enough. I just wanna make sure that we implement it in a way now that can easily be extended in the future without having to have breaking changes. If we add both allow and deny lists now, and realize it needs to be different in a month, we have problem. That being said, it seems like the common opinion seems to be that having both exclude and include simultaneously is acceptable.

> In any case, what would you guys like me to do right now to make this pull request mergable?

Nothing right now! Implementation looks simple, and if we're all in favor of having both include and exclude, this should be good to go 👍🏻

**Comment by molszanski** [comment]
> Fully agreed on this. We shouldn't start relying on additional configuration files. This should be configured in the environment variables.

Just to be clear, in my original message I was referring to a format, not a physical file on disk/.git

**Comment by bamboowonder** [comment]
Did this pull request die on the vine?

**Pull request closed without merging**
