### PR TITLE
Add unit options for "Related Values" display

### LINKED ISSUE #3227: Add unit options to "Related Values" display
Add `Singular Unit` and `Plural Units` (both half width) to the Display options. This will allow showing more meaningful units instead of just `Item`:

`One Member` or `Three Members`

### PR DESCRIPTION
**Pull request by Nitwel**
closes #3227

### CODE REVIEW

**Comment by benhaynes** [comment]
Thanks Nils! This is exactly what I had asked for, but I'm wondering if this is worth extending to solve this too: https://github.com/directus/directus/discussions/3069

This PR adds the units to the Display (which is useful in that context). But maybe having these singular/plural units on the _Collection_ lets us do this in more places with less setup? @rijkvanzanten thoughts?

**Comment by rijkvanzanten** [comment]
Yeah I agree. Seems like we'd use the same setup across multiple places (this display, but also page titles etc)

Keep in mind that we'd have to make this an update to the existing translations repeater to add an additional field for "singular", as it will have to be ~~internationalized (is that even a verb?)~~ translated

**Comment by benhaynes** [comment]
Coolio. @Nitwel you comfortable with Directus schema changes?? 😐

**Comment by Nitwel** [comment]
I first have to understand what the plan now here is because I'm not really getting it right now. 😅 

So, how'd having these settings in the collection work? What if you'd wan't to call one field book/s and the other field cart/s?

**Comment by rijkvanzanten** [comment]
Right now, we allow you to set a translated name for the collection for use in Directus:

CleanShot 2021-02-19 at 11 43 21@2x

We'll update this to be `singular` / `plural` instead of just `translation`. That way, we can dynamically show `{count} {collection-translations.current-language.singular/plural}`

**Comment by Nitwel** [comment]
So for example, we have Articles and Authors (m2o). We would set in the translation of the Atricle collection single to Article and plural to Articles. Now we'd add the relatedValues display to the o2m field in the Authors collection. The display now has to get these translations from the other collection and display it?

**Comment by benhaynes** [comment]
That sounds about right. This also allows us to reference things more cleanly in the App. Instead of `New Articles Item Added"`we can say `New Article Added` (eg: in Activity). And repeaters can natively say: `Add New Article` (singular)

**Comment by Nitwel** [comment]
Hmm, I think we run into a serious problem with this new plan when using a m2a because for one, we don't directly know that it's an m2a and second, if we'd know it we still wouldn't know from which collection to select the translation.

**Comment by rijkvanzanten** [comment]
The related-values display for m2a is an exception to this rule unfortunately. The m2a-builder interface would still be able to use this though, as it's dropdown now says `Create new "Headings" item`, which would become `Create new Heading`

**Comment by Nitwel** [comment]
I updated the display to use the options from the collection now.

**Comment by rijkvanzanten** [comment]
Superseded by https://github.com/directus/directus/pull/5302

**Pull request closed without merging**
