### PR TITLE
Feat/interface presentation external images

### PR DESCRIPTION
**Pull request by JonathanSchndr**
## Description

With this extension it is possible to add dynamic images to a record. This can be useful when an external image provides dynamic info or it needs a visual explanation. Example Shield.io Badges. An entry can have X images. Each image needs a URL and optionally the width. If you like the feature, it would also make sense to create a new panel for the dashboard.

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I'm slightly worried about the privacy / security implications of this. This would also require the CSP headers to be reconfigured to allow the third party from showing images, and it means that the third party can track the Directus instance through the traffic to download the image 🤔

**Comment by JonathanSchndr** [comment]
> I'm slightly worried about the privacy / security implications of this. This would also require the CSP headers to be reconfigured to allow the third party from showing images, and it means that the third party can track the Directus instance through the traffic to download the image 🤔

You mean, if now someone has a strange source, the images are loaded and thus an automatic request to the other server happens by retrieving the file. Sure, this would be possible, but isn't that rather the task of the user to validate his sources cleanly?

**Comment by rijkvanzanten** [comment]
> Sure, this would be possible, but isn't that rather the task of the user to validate his sources cleanly?

I personally agree, but in practice it doesn't work like that unfortunately. The input data must be considered untrusted and therefore insecure, so this would be considered a problem, as we don't verify the third party source before requesting it for displaying in app. I'm just aggressively trying to prevent another https://github.com/directus/directus/security/advisories/GHSA-xmjj-3c76-5w84 or similar problem 🙂

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
