### PR TITLE
Use date (epoch) compare workflow instead of timer to refresh token in SDK

### LINKED ISSUE #10456: Auto Refresh in JS SDK not working
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Setting the option to use authRefresh does nothing. Auto refresh is not happening when I have an expired token

### To Reproduce

1) Set up a clear project with directus JS SDK
2) Init a new DirectusSDK object and set the following configuration
```js
auth: {
  mode: "json",
  autoRefresh: true,
},
storage: {
  mode: "LocalStorage",
},
```
3) Auth using SDK
4) Wait until the auth_token will expire
5) Try to make read request to any model without public access permissions

### Errors Shown

Error: Token expired.
    at Transport.request (interopRequireDefault.js:8)
    at async Transport.get (interopRequireDefault.js:8)
    at async ItemsHandler.readMany (interopRequireDefault.js:8)

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

14.18.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

docker-compose

### LINKED ISSUE #12275: Why am I getting a Token Expired error?
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I am using the following versions of Directus:

client: "@directus/sdk": "^9.5.1",
server: "directus": "^9.6.0"

I have a website that check the JS SDK's /me method on the first page-load. If it returns "invalid user credentials" I don't log in, but I create a public "anonymous" user. There is also a sign-up/login button on my website. When clicked it will go through the login flow UI, and call /users/invite etc. and eventually create a user. When the user logs in with his credentials, the login works. BUT after the expiration time of the access_token, (when closing and reopening the website). The /me method returns a "token expired" error, and consequetly all the public methods of the SDK are not working anymore (as it is trying to refresh the expired token, or something?).

my access_token_TTL is 2 mins and refresh_token_TTL is 7 days in my .env config.

### To Reproduce

- login with JS SDK auth login method. 
- reload page
- /me method called in beginning correctly returns the logged in user object.
- wait till access_token_TTL has expired.
- reload page
- /me method greeted with a 'Token expired' error

expectation: 
- after access_token_TTL reached the refresh_token should refresh the access_token behind the scenes and the /me method should return the logged in user (after refreshing the token behind the scenes)
- when not logging in for a time-period longer than the refresh_token_TTL, the /me method should return a simple "invalid user credentials" and an anonymous user would be created (my personal implementation).

### Errors Shown

a4618ee.js:2 GET https://subneu.live/api/users/me 403 (Forbidden)
bc75317.js:1 Error: Token expired.

### What version of Directus are you using?

client: "@directus/sdk": "^9.5.1", server: "directus": "^9.6.0"

### What version of Node.js are you using?

v15.5.1

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

nginx on ubuntu

### PR DESCRIPTION
**Pull request by krazyjakee**
Resolves: https://github.com/directus/directus/issues/10456, fixes #12275

By using an in-memory timer strategy to refresh the token, whenever the user reloads the page or does a hard navigate within the site, the timer is restarted. Whenever the user navigates to another tab in their browser, [the timer becomes unreliable](https://codereview.chromium.org/6577021).  This guarantees the access token will expire before it is refreshed.

This PR:
- Uses the epoch to test if the token has expired
- Removes the `msRefreshBeforeExpires` option as no longer needed
- Performs the expired test before every request

### CODE REVIEW

**Comment by azrikahar** [comment]
Hi @krazyjakee, thanks again for this PR. I've tested it and it does work like a charm!

Just to confirm, have you enabled the "Allow edits from maintainers" setting in your PR? [Here's a link to GitHub docs about it](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests).

**Comment by azrikahar** [comment]
Hi @krazyjakee, thanks again for this PR. I've tested it and it does work like a charm!

Just to confirm, have you enabled the "Allow edits from maintainers" setting in your PR? [Here's a link to GitHub docs about it](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests).

**Comment by krazyjakee** [comment]
@azrikahar That box looks to be checked by default. Let me know if I need to do something else for you.

**Comment by azrikahar** [comment]
> That box looks to be checked by default. Let me know if I need to do something else for you.

Thank you! Seems to be an intermittent issue on my end so all good 😄

**Review by rijkvanzanten — APPROVED** [review]

**Comment by dataexcess** [comment]
👏👏👏👏👏👏👏👏👏👏

**Pull request merged**
