### PR TITLE
Add util to send notifications to admins

### PR DESCRIPTION
**Pull request by Nitwel**
For example to send out warnings about deprecation / breaking changes

### CODE REVIEW

**Comment by paescuj** [comment]
> This warning method is still open for discussion and may not be the final solution.
> A problem to note is that currently, each time a notification gets created, we try to send out an email too but we likely want to prevent that from happening in this case.

Not sure if this is a good or bad thing 😄 A notification by email would draw more attention to it. But if this is not desired, I think we could easily add an option to the notification service which makes it possible to define if an email should be sent too (might be of interest anyway 🤔).

**Comment by phazonoverload** [comment]
There are two distinct things in this PR that I think should be decoupled: 

1. A way to push a notification to admin users on upgrade. 
2. A notice about basic extensions. 

I'm 100% in for 1 and I think I was part of a discussion that spurred this on. 

For number 2, I would remove from this PR and push this with the release that makes changes as an additional surface for making sure admins see breaking changes or to draw attention to large new features. I wouldn't do an announcement early - it's the responsibility of those self-hosting to read and understand changelogs / breaking changes before acting.

Number 2 is also probably copy for support/marketing to write.

**Comment by phazonoverload** [comment]
I also wonder if we want to have hardcoded alerts around the codebase. Maybe we just show these to everyone once, regardless of state. 'Breaking change in Directus 10.7: XYZ' for example. Even if no remedial action is required.

**Comment by paescuj** [comment]
> I also wonder if we want to have hardcoded alerts around the codebase. Maybe we just show these to everyone once, regardless of state. 'Breaking change in Directus 10.7: XYZ' for example. Even if no remedial action is required.

Definitively worth a thought!

**Review by paescuj — APPROVED** [review]

**Comment by paescuj** [comment]
Merging for now, the continuation of this is tracked internally under https://linear.app/directus/issue/MARK-1655.

**Pull request merged**
