### PR TITLE
Update of all vitest snapshots

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Description

Due to a breaking change in [vitest 0.29.0](https://github.com/vitest-dev/vitest/releases/tag/v0.29.0) it now [inserts a link to their docs](https://github.com/vitest-dev/vitest/pull/2867) when *running* the testsuite into snapshot files. This has definitely caused me to add those updated snapshots to a commit by accident before.

Since the pinned vitest version is 0.29.3 I think it is reasonable to update those snapshots. (Done by simply running the test suite).

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [x] Other, please describe:
Update of test snapshots 

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by paescuj — APPROVED** [review]
Thanks!

**Comment by rijkvanzanten** [comment]
This is also part of https://github.com/directus/directus/pull/18014

**Comment by hanneskuettner** [comment]
So should I close this and wait for the eventual merge of the Big One?

**Comment by rijkvanzanten** [comment]
> So should I close this and wait for the eventual merge of the Big One?

Lets give it a minute to see if the other PR is easy enough to merge (the QA might take a while!)

**Comment by paescuj** [comment]
Thanks again for your contribution! We're going to address this via https://github.com/directus/directus/pull/18014.

**Pull request closed without merging**
