### PR TITLE
Only pass needed values when sorting

### LINKED ISSUE #16000: Sorting on o2m and m2m is also updating the fields of the display template
### Describe the Bug

Whenever you rearrange the sorting of a o2m or m2m relation it is not only updating the sort property but also everything that is in the display template of the relation field.

Below the raw value after I only did a rearrange on the sort. It also updates the `b_title`, although I haven't touched that one.
```
{
	"create": [],
	"update": [
		{
			"b_title": "test 2",
			"id": "1edcbf51-259d-4dac-b9b8-9ed5d7429705",
			"sort": 1
		},
		{
			"b_title": "test 1",
			"id": "06a0c3c1-f129-451c-86e0-665787630b60",
			"sort": 2
		}
	],
	"delete": []
}
```

It hard to explain, but if you follow the steps below everything becomes clear.

### To Reproduce

1.  Create 2 collections, A and B.
2.  Give B a simple text field, let's say b_title.
3.  On collection A you create a O2M or M2M relation to collection B, including a sort property, let's say collection_b_relation.
image
5.  Set the Display Template of the relation field to show the b_title.
image
6.  Create a few B collection relations  (with a b_title) via collection A. And save them.
7.  Rearrage the relations.
8.  Look at the raw value, it not only contains an update on the sort property, also on the b_title.
```
{
	"create": [],
	"update": [
		{
			"b_title": "test 2",
			"id": "1edcbf51-259d-4dac-b9b8-9ed5d7429705",
			"sort": 1
		},
		{
			"b_title": "test 1",
			"id": "06a0c3c1-f129-451c-86e0-665787630b60",
			"sort": 2
		}
	],
	"delete": []
}
```

### Errors Shown

In most of the cases it will not cause any errors. 

But let's say you create a relation in collection_b to a collection you have only read access to. In the display template of the relation field in collection_a you add a field of this relation. After sorting it will try to update this field and it will cause a permission denied error.
This is how I found out about this bug eventually.

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

v16.6.1

### What database are you using?

Postgres 13.3

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by Nitwel**
The problem before was that we would pass all the info to the changes when updating, even those that where only for the display template. We now only pass the minimum changes to `useRelationMultiple`

Fixes #16000

### CODE REVIEW

**Review by azrikahar — COMMENTED** [review]
Works great! I believe we'll need to update sortItems in `files` interface as well 👍

Out of curiosity, would it be somehow feasible to abstract this in useRelationMultiple? Not sure would it add unnecessary complexity as well (or maybe it isn't really logical), so this is only a curious question rather than a requested change 😄

**Review by br41nslug — CHANGES_REQUESTED** [review]
Works great in my tests too 😄 But as Azri mentioned this same fix will need to be done for the Files interface too. Currently the files interface does still send the `fielname_download`,`title` and `type` with the payload on a re-order.

image

**Comment by Nitwel** [comment]
Yep, forgot the files interface, thanks!

**Review by br41nslug — APPROVED** [review]

**Comment by abdonrd** [comment]
This PR also fix https://github.com/directus/directus/discussions/16056, right?

**Comment by br41nslug** [comment]
Yes thats the same issue 😄

**Pull request merged**
