### PR TITLE
Update TypeScript in SDK

### PR DESCRIPTION
**Pull request by paescuj**
## Scope

Update TypeScript version to 5.4 for the SDK

<s>Had to hold back the TypeScript update to 5.4 for the SDK (and therefore also in docs) in #22063 because the newer version introduced a compilation error:
```
src/types/fields.ts:33:13 - error TS2322: Type 'Relations & RelationalFields<Schema, Item>' is not assignable to type 'string | number | symbol'.

33     [Key in RelationalFields<Schema, Item>]?: Extract<Item[Key], ItemType<Schema>> extends infer RelatedCollection
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

@br41nslug Would you mind taking a look at this issue? 🙏 Seems like it cannot be used as a key, maybe we can narrow down, assert or introduce a check for the type 🤔</s>

## Potential Risks / Drawbacks

Potential type issues

## Review Notes / Questions

None

### CODE REVIEW

**Comment by br41nslug** [comment]
Oh fun 😅

**Comment by br41nslug** [comment]
It looks like this breaking change was the cause https://devblogs.microsoft.com/typescript/announcing-typescript-5-4-beta/#breaking-changes#more-aggressive-reduction-of-intersections-between-type-variables-and-primitive-types

**Comment by paescuj** [comment]
> It looks like this breaking change was the cause https://devblogs.microsoft.com/typescript/announcing-typescript-5-4-beta/#breaking-changes#more-aggressive-reduction-of-intersections-between-type-variables-and-primitive-types

Wow, thanks for the fast fix 🚀❤️ Sounds like that's exactly it 👍

**Review by paescuj — COMMENTED** [review]
Checked & the fix looks good to me 👍

**Comment by paescuj** [comment]
Superseded by #22211

**Pull request closed without merging**
