### PR TITLE
Add request to service and hook context

### PR DESCRIPTION
**Pull request by tan-tan-kanarek**
## Description

Add request to service and hook context.
Related to issue https://github.com/directus/directus/discussions/11596

## Type of Change

- [ ] Bugfix
- [X ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [X ] Performed a self-review of the submitted code

If adding a new feature:

- [X ] Documentation was added/updated. PR: https://github.com/directus/docs/pull/263

### CODE REVIEW

**Comment by tan-tan-kanarek** [comment]
@rijkvanzanten, this PR is related to https://github.com/directus/directus/discussions/11596 as documented.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten, this PR is related to #11596 as documented.

Yeah I saw in your original description. #11596 is an open feature request (still in discussion), and not an issue though 🙂 See "Triaging Process" in https://github.com/directus/directus/blob/main/contributing.md#pull-requests for more info 👍🏻

**Comment by rijkvanzanten** [comment]
Heya! Thank you for your contribution. Unfortunately, we can't accept PRs for improvements/features that don't have a prior accepted Discussion and associated Issue (as per the [Contributing Guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests)). This is to ensure that PRs that are opened will actually get the chance to be reviewed, merged, and maintained by the core maintainers. We can reopen and continue this PR review once the requirements have been met. Thank you for your understanding!

**Comment by tan-tan-kanarek** [comment]
I just wanted to help.
Since you're guidelines are stiff and annoying, I stopped contributing to your code and I make all my many fixes locally only without sharing them with your great community that loses a lot, I'm sure I'm not the only contributor you lose.

**Pull request closed without merging**
