### PR TITLE
Fix 21563 include files in package json

### LINKED ISSUE #21563: Extensions CLI doesn't include `files` property in `package.json`
### Describe the Bug

When bootstrapping a new extension with the extensions CLI, the generated `package.json` doesn't include a `files` section. This combined with `.gitignore` often excluding `dist` means that that the bundled `dist` files aren't published to npm when using the default setup.

### To Reproduce

Bootstrap a new extension and publish it to `npm`. Note how the `dist` files are missing.

### Directus Version

10.10

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by DanielBiegler**
## Scope

What's changed:

- The package manifest now features the "files" key

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- TBH: Have not tried running it :gun::cowboy_hat_face: 

---

Fixes #21563

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by br41nslug** [comment]
Should `dist/` not also have been removed from the `.gitignore` templates 🙈

**Comment by rijkvanzanten** [comment]
No! We want to keep ignoring the `dist` folder on the repo, but if you do so you have to explicitly include it in the package.json so it's still published to npm 🙂

**Comment by br41nslug** [comment]
Agree to disagree then, I dont think you should be publishing anything that is not versioned in your repo.

**Comment by br41nslug** [comment]
> Many don't version dist folders in git at all, yet publish the dist to npm. 🤷🏻

Sure thats part of a common pattern but if we want to push that approach for extension devs then our templates should also include a `.npmignore` so you're only deploying `dist/` to npm and only committing `src/` to cvs.

**Comment by rijkvanzanten** [comment]
>  so you're only deploying dist/ to npm and only committing src/ to cvs.

That's what the `files` key does in `package.json` 👍🏻 It's an allow-list. Only the `dist` folder will be publishes with the current addition 🙂

**Pull request merged**
