### PR TITLE
Fix default values for interfaces & display

### LINKED ISSUE #18570: Input field type changed to password when adding conditions
### Describe the Bug

When attempting to add conditions to an input field, the input field type is automatically changed to "password".
This happen in Directus v10.1.0, on v10.0.0 it works normally.

### To Reproduce

Screenshot 2023-05-12 115758
Screenshot 2023-05-12 115731
Screenshot 2023-05-12 115701
Screenshot 2023-05-12 120145

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Custom)

### LINKED ISSUE #18572: Issue with Many-to-One Field Interface
### Describe the Bug

The M2O field interface is not working correctly. Specifically, when attempting to disable (create items) within the interface. As a workaround, u must click on the right arrow and clear the value.

This happen in Directus v10.1.0, on v10.0.0 it works normally.

### To Reproduce

Screenshot 2023-05-12 121511

To make it works:

Screenshot 2023-05-12 122857

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by paescuj**
Fixes #18572, fixes #18570

Reverting some of the TS error fixes included in #18507, #18491 and #18490.
The default values should be passed to the corresponding interfaces &  displays with the correct type, so instead of using strings I've update the type of `default_value` to accept `boolean` and `number`.
This works fine for now. Hopefully in the future we will be able to clean up the types so that the default type automatically adapts to the field type.

Furthermore, I've removed some unnecessary default values.

(Also intends to make @hanneskuettner happy 😉 - thanks for your report in https://github.com/directus/directus/pull/18507#issuecomment-1545482046)

### CODE REVIEW

**Comment by hanneskuettner** [comment]
Wouldn't the more correct fix be the one I pointed out in https://github.com/directus/directus/pull/18507#issuecomment-1545482046? By adding a `type: 'boolean'` or `type: 'number'` to the `Field` definitions of the interfaces/display the default_value correctly types as `boolean` and `number` instead of `string`.

**Comment by paescuj** [comment]
> ~Wouldn't the more correct fix be the one I pointed out in [#18507 (comment)](https://github.com/directus/directus/pull/18507#issuecomment-1545482046)? By adding a `type: 'boolean'` or `type: 'number'` to the `Field` definitions of the interfaces/display the default_value correctly types as `boolean` and `number` instead of `string`. Cause as you pointed out it seems to me like the default value does already adapt to the field type, the type is not set in all of the option definitions however. ~
> 
> I don't know what my IDE dreamed up. It definitely showed me the correct typings when adding the `type` key, but looking at the actual typings that doesn't make sense at all.

Yeah we should definitly do some type inference here in teh future. For now I think that's the easiest and most applicable fix.

**Review by br41nslug — APPROVED** [review]
LGTM it solves #18572 but i was not able to reproduce #18570 on my end

**Comment by paescuj** [comment]
> LGTM it solves #18572 but i was not able to reproduce #18570 on my end

Hmm, I was able to reproduce both issues on my end

**Comment by br41nslug** [comment]
My bad had created a bad condition for testing, I am able to reproduce https://github.com/directus/directus/issues/18570 now but the issue seems to only be solved for newly created conditions after this fix while existing conditions already experiencing this issue keep showing the behavior 🤔

**Review by azrikahar — APPROVED** [review]

**Pull request merged**
