### PR TITLE
Add hash display

### LINKED ISSUE #19889: Add redacted Display for the Hash interface
### Describe the Improvement

The Hash field currently comes with an interface but is missing the matching display resulting in the raw hashed value being rendered in overview pages. For the end user this should behave like the directus_user password field avoiding to directly render this value in the web app.

271256912-6d23976d-6284-4fb0-9434-35bfeb69a538
271257254-c0e79cd0-634b-408f-b59c-97beda2e4bdf

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- Added a hash display.

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- `redacted` might be more appropriate although it might limit options we can use for the display down the road
- Alternative path for this is to allow the `formatted-value` interface with only the `masked` available for selection

---

Fixes #19889

### CODE REVIEW

**Review by paescuj — COMMENTED** [review]
In my opinion, we can keep the display very simple and omit the option to reveal the value. The practical thing about this new display is that we now have a matching <s>default</s> for the hash interface. If you want to show the value, you can switch to other displays (for example, <s>Formatted Value</s> Raw Value).

WDYT?

**Comment by br41nslug** [comment]
> If you want to show the value, you can switch to other displays (for example, Formatted Value).

I tend to agree, either the Raw or formatted value displays can already be used to show the raw value.

**Comment by ComfortablyCoding** [comment]
Fair point, my main reasoning was to keep it somewhat inline with the hash interface options.

**Review by paescuj — APPROVED** [review]
🚀

**Pull request merged**
