### PR TITLE
adds the possibility to use default template in email operation

### PR DESCRIPTION
**Pull request by massimans**
## Description

adds the possibility to use default template in email operation
### remarks

- the new field doesn't show in operations overview for cleaner interface
- i provided the label for the english and french languages

Fixes #14091

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by massimans** [comment]
Hi,
Any updates on this?

**Comment by benhaynes** [comment]
Sorry, busy times. We're focused on fixes before features at the moment, but will review ASAP.

**Comment by genu** [comment]
@massimans Should this be extended to specify a template name?

I imagine in a more practical sense, I'd want to specify an email template to use, and just default to the base one.

**Comment by massimans** [comment]
I thought of it as just an extension to basic functionality but it would be easy to make it string

**Comment by azrikahar** [comment]
Coincidentally seems like #15829 added a similar enhancement here. 

> Should this be extended to specify a template name?
> 
> I imagine in a more practical sense, I'd want to specify an email template to use, and just default to the base one.

That being said, #15829 does also allow specifying which template to use, and this addressed @genu's suggestion, so maybe we can hone in on that PR instead 🤔

**Comment by massimans** [comment]
Hi,
indeed #15829 looks more advanced,i would be happy with it in Directus so I'm going ahead and close this PR.

**Pull request closed without merging**
