### PR TITLE
Undefined index: junction_key_left when using advance search both in api and ui

### PR DESCRIPTION
**Pull request by pinkahd**
On tables that have  a manny to one relation and an advance filter is applied the RelationTabelGatewayWithConditions file will throw an error on junction_key_left. I've applied a fix on it and it seems to work. I've tested this issue even with the example gallery table on the 'user' column and it gives me the same error.

Error message:

```
ErrorException
Undefined index: junction_key_left
 /var/www/html/directus/api/core/Directus/Db/TableGateway/RelationalTableGatewayWithConditions.php
on line 235
```

Api request url:
http://192.168.33.6/api/1/tables/tabel/rows?access_token=<<Removed>>&adv_search[0][id]=pin_number&adv_search[0][type]=like&adv_search[0][value]=123456

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Hi @pinkahd is there is any reason why you closed the PR?

**Comment by pinkahd** [comment]
Hey @WellingGuzman I didn't know if I should create a PR or an issues and when I created the PR I've created it from my master branch instead from a different branch. How do you want me to proceed to reopen the PR or to create an issues. Since you've never specified how to create a PR only how to open an issue.

Thanks.

**Comment by WellingGuzman** [comment]
Hi @pinkahd, you need to create a new branch, and do all the fixes/changes in there and open a PR. and do what you did, explaining what the PR do, in these case what problem solved.

Please feel free to open a new PR, you could also open a ticket and make yourself a PR about it, just incase the PR don't get through at first.

Thanks for submitting and take your time to try Directus.

**Comment by pinkahd** [comment]
Hey @WellingGuzman I've created a new PR #1149 

Thanks for your help.

**Pull request closed without merging**
