### PR TITLE
Add support for custom resolvers in GraphQL

### PR DESCRIPTION
**Pull request by 8byr0**
Following #4448 discussion, here's a WIP PR that addresses custom GraphQL schema.

The simple idea behind this feature is to allow to define GraphQL queries and mutation directly from your custom endpoint definition like so:
```javascript
// These fake functions are intended to be called by both REST and GQL entrypoints
const findUser = (id) => {
	return {
		id: id,
		firstName: 'John',
		lastName: 'Doe',
	};
};
const updateUser = (payload) => {
	const { id, firstName, lastName } = payload;
	return {
		id,
		firstName,
		lastName,
	};
};

module.exports = {
	handler: (router) => {
		router.get('/', (req, res) => res.send('Hello, World!'));
		router.get('/find_user', (req, res) => res.send(findUser(req.query.id)));
		router.post('/update_user', (req, res) => res.send(updateUser(req.query)));
	},
	mutations: [
		{
			operationName: 'update_user',
			fields: {
				id: 'Int!',
				firstName: 'String',
				lastName: 'String',
			},
			variables: { id: 'Int!', firstName: 'String', lastName: 'String' },

			// eslint-disable-next-line no-unused-vars
			async resolver(_, input) {
				// Do your mutation operations here

				return updateUser(input);
			},
		},
	],
	queries: [
		{
			operationName: 'find_user',
			fields: {
				id: 'Int!',
				firstName: 'String',
				lastName: 'String',
			},
			variables: { id: 'Int!' },
			async resolver(_, input) {
				return findUser(input.id);
			},
		},
	],
};
```

Building the schema is managed on GraphQL service's end to make it more simple for developers (they only need to know graphql, not the tools used to build the schema) but another approach could be to declare a query builder(and mutation builder) directly in custom endpoint definition:
```javascript
// These fake functions are intended to be called by both REST and GQL entrypoints
const findUser = (id) => {
	return {
		id: id,
		firstName: 'John',
		lastName: 'Doe',
	};
};
const updateUser = (payload) => {
	const { id, firstName, lastName } = payload;
	return {
		id,
		firstName,
		lastName,
	};
};

module.exports = {
	handler: (router) => {
		router.get('/', (req, res) => res.send('Hello, World!'));
		router.get('/find_user', (req, res) => res.send(findUser(req.query.id)));
		router.post('/update_user', (req, res) => res.send(updateUser(req.query)));
	},
	queryBuilder: (schemaComposer) => {
		schemaComposer.Query.addFields({
			find_user: {
				type: schemaComposer.createObjectTC({
					name: `endpoint_find_user`,
					fields: {
						id: 'Int!',
						firstName: 'String',
						lastName: 'String',
					},
				}),
				variables: { id: 'Int!' },
				resolve: (_, input) => {
					return findUser(input.id);
				},
			},
		});
	},
       // mutation builder would look similar
};

```

I preferred not to use this approach but I'm here for an open discussion about this so feel free to share your opinions!

~~One point that's not managed yet is the ability to pass directus context to the resolver.~~ (**edited**)

Tasks:
- [x] Update endpoint type definition to allow queries and mutation
- [x] Handle scheme generation
- [x] Forward directus && GraphQL context to resolver
- [ ] Update documentation
- [ ] Unit testing if applicable

### CODE REVIEW

**Comment by 8byr0** [comment]
Finally found the time to finish this!

I just pushed an update to pass context features to resolvers (`{ services, exceptions, env, database: getDatabase(), logger, getSchema }`) just like hooks callbacks.


What are your thoughts?

**Comment by 8byr0** [comment]
Updated code reflecting last changes:
```typescript
// These fake functions are intended to be called by both REST and GQL entrypoints
const findUser = (id) => {
	return {
		id: id,
		firstName: 'John',
		lastName: 'Doe',
	};
};
const updateUser = (payload) => {
	const { id, firstName, lastName } = payload;
	return {
		id,
		firstName,
		lastName,
	};
};

module.exports = {
	handler: (router) => {
		router.get('/', (req, res) => res.send('Hello, World!'));
		router.get('/find_user', (req, res) => res.send(findUser(req.query.id)));
		router.post('/update_user', (req, res) => res.send(updateUser(req.query)));
	},
	mutations: [
		{
			operationName: 'update_user',
			fields: {
				id: 'Int!',
				firstName: 'String',
				lastName: 'String',
			},
			variables: { id: 'Int!', firstName: 'String', lastName: 'String' },

			async resolver(_, input, { services, exceptions, env, database: getDatabase(), logger, getSchema }) {
				// Do your mutation operations here

				return updateUser(input);
			},
		},
	],
	queries: [
		{
			operationName: 'find_user',
			fields: {
				id: 'Int!',
				firstName: 'String',
				lastName: 'String',
			},
			variables: { id: 'Int!' },
			async resolver(_, input,{ services, exceptions, env, database: getDatabase(), logger, getSchema }) {
				return findUser(input.id);
			},
		},
	],
};
```

**Comment by 8byr0** [comment]
Disclaimer: I only tested primitive types (Int, Float, String...), it would be good to test deeper than that with a more real life use case

**Comment by 8byr0** [comment]
Any update on this @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
No new updates @8byr0. We're currently focussed on overall stability and other priority items (esp around the big v9 release from recently), so haven't gotten around to looking into this yet..

**Comment by jaycammarano** [comment]
> What's the status on this front? I'd really really use a way to have custom graphql schemas. Anything I can help with?

[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

**Comment by benhaynes** [comment]
@marcemira 

>Anything I can help with? 

We'll be reviewing ASAP, but it always helps if you want to review and provide your feedback here! Thank you! ❤️

**Comment by jaycammarano** [comment]
> 512d91f

It's going to take a bit of reworking just because of the merge conflicts. Just merging the GraphQL and extensions bit is going to take some work.

**Comment by marcemira** [comment]
Thanks for the quick response @jaycammarano @benhaynes. I can definitely help testing this branch and adding a review 👍🏻

**Comment by productdevbook** [comment]
when support ?

**Comment by azrikahar** [comment]
> when support ?

[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support/#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support/#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS! [^1]

[^1]: This is an automated response.

**Comment by asynchor** [comment]
Consider integrating [graphql-yoga](https://www.graphql-yoga.com/ in Directus. It will bring a lot of power along with it.)

**Comment by abdonrd** [comment]
Has this been abandoned? Or is there an intention to resume it soon? Thanks!

**Comment by rijkvanzanten** [comment]
> Has this been abandoned? Or is there an intention to resume it soon? Thanks!

Not abandoned 👍🏻 That being said, there's no current active dev-work done from the core team either. [We prioritize community PRs/issues based on community interest/engagement](https://github.com/directus/directus/pulls?q=is%3Apr+is%3Aopen+sort%3Areactions-heart-desc), so this one should hopefully be addressed soon 🙂

**Comment by maartenvn** [comment]
Hi,

Is there anything that can be done on this issue? I would love to continue on this, as I really need this feature for a project I am working on.

I know you guys don't provide estimates on features but I would love to soften the workload if it would help getting this feature ready 🙂

**Comment by rijkvanzanten** [comment]
> Hi,
> 
> Is there anything that can be done on this issue? I would love to continue on this, as I really need this feature for a project I am working on.
> 
> I know you guys don't provide estimates on features but I would love to soften the workload if it would help getting this feature ready 🙂

There's a couple things that would help this out! 

First of all is a written document that outlines exactly how this is supposed to work (RFC). That allows everybody to make sure that the way this is implemented will scale and work across various use cases (and as a bonus it makes sure that we have docs).

After that discussion has settled, it's time to (re)implement / resolve what needs resolving in the code so far to align with the completed spec, and add tests.

Once that's resolved, we can review and merge 🙂

**Comment by azrikahar** [comment]
Note: it seems like this PR is showing that it has 0 line changes, but I believe it's an unintentional mistake in this commit: https://github.com/directus/directus/pull/9395/commits/c7ca6b7e333ae9dd081020e46b1b3fbbb108f57a, which deleted all the actual/original code in this PR.

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
