### PR TITLE
add additional reload path

### PR DESCRIPTION
**Pull request by YannickArmspach**
## Description

[discussions #14922](https://github.com/directus/directus/discussions/14922)

A new .env variable for additional watch paths to improve local development of extensions (e.g. watch extension in monorepo workspaces ).

Single path exemple:
```env
EXTENSIONS_AUTO_RELOAD_PATH="../../packages/*/build/index.js"
```

Multiple paths exemple:
```env
EXTENSIONS_AUTO_RELOAD_PATH="../../packages/*/build/index.js,../../packages/*/build/app.js"
```

Fixes #

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by YannickArmspach** [comment]
#14922

**Comment by arpadgabor** [comment]
A merge on this pull request would be amazing! Especially for setups using turborepo/nx, etc.

**Review by nickrum — CHANGES_REQUESTED** [review]
Local extensions (the ones you put inside the extension folder) should always be single files without any dependencies. Your use-case should be supported out of the box by using [package extensions](https://docs.directus.io/extensions/creating-extensions.html#package-extension).

**Comment by arpadgabor** [comment]
Indeed, however from my understanding this PR adds support for hot-reloading of extensions that are loaded from a workspace. Or maybe I'm understanding something wrong?

**Comment by YannickArmspach** [comment]
@arpadgabor Yes you understand correctly. When we create a monorepo with workspaces for applications (Directus in this example) and other one for developing packages (Directus extensions in this example), hot reloading does not work because there are not located in the "extensions" folder. 

@nickrum My PR simply allows adding specific paths to listen for file changes in other folders.

**Comment by richardwardza** [comment]
I have the same situation and it would be a great help if this PR could be merged in. 

I have my layout as follows:
```
app  => directus installation
packages/directus-extension-operation-1
packages/directus-extension-operation-2
packages/directus-extension-operation-3
```
The `packages/directus-extension-operation-1` `2` and `3` packages are installed into the `app` (`npm install packages/directus-extension-operation-1 -w app`) but when I'm working on the code in `packages/directus-extension-operation-1` and I rebuild it then I currently need to restart the directus service to get the code change to reflect in `app`.

**Comment by nickrum** [comment]
> My PR simply allows adding specific paths to listen for file changes in other folders.

Admittedly it's a very simple addition that probably doesn't do much harm, but I would still prefer to encourage users to use the options that are already implemented and that do not need any configuration. I have briefly explained how this works over at https://github.com/directus/directus/discussions/14922#discussioncomment-3571164.

Also, to be able to properly reload additional extension paths when the file source changes, you would need to delete those files from node's require cache.

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
