### PR TITLE
Started with the translation to german

### PR DESCRIPTION
**Pull request by katywings**
The translation is obviously not finished so you can ignore & close this pull request - however it's meant as a litte preview ;)

### CODE REVIEW

**Comment by benhaynes** [comment]
Excellent! Thank you @katywings for the great start!

**Comment by WellingGuzman** [comment]
This is great, Thanks @katywings.

Another option can be let's keep it here until it's done. :)

**Comment by benhaynes** [comment]
We could also merge it (incomplete) so that other's can contribute from the bottom up... which was mentioned yesterday.

**Comment by WellingGuzman** [comment]
Even Better. Let's merge it.

**Comment by WellingGuzman** [comment]
We cannot merge this directly to development via GitHub, let's wait until we merge all into master.

**Comment by katywings** [comment]
Oh, is this a special problem with my pull request? Did I setup something wrong? I never hear that merges to branches other than master aren't possible D:

**Comment by WellingGuzman** [comment]
@katywings there's nothing wrong. We can merge to any branch locally, but through GitHub, is not possible. If it's possible I really would like to know how to. :)

Keep the good work, nothing wrong with your PR.

**Comment by WellingGuzman** [comment]
@katywings You did it right, I was the one wrong, danke schön. 👍

**Pull request merged**
