### PR TITLE
Don't throw error if entry is null or undefined

### LINKED ISSUE #15275: Setting of invalid permission crashes admin app for role involved
### Describe the Bug

Setting permission logic on any collection seems to crash (ie. Admin app just shows blank) when the permission contains a reference or a field via a m2m that either no longer exists, or doesn't contain any valid elements.

### To Reproduce

On the create permission of any collection on any role, set the Field Validation to check something that might be unreachable.

in my case this is what triggered it:
```
{
	"_and": [
		{
			"person": {
				"_eq": "$CURRENT_USER.organizations.org.members.person"
			}
		}
	]
}
```

$CURRENT_USER has many `organizations`, which each has one `org`, in turn has many `members` each connected to a `person`

 

### Errors Shown

[devStart] 13:14:04 🚨 Cannot read properties of undefined (reading 'members') 
TypeError: Cannot read properties of undefined (reading 'members')
    at ~/cms/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:85:71
    at Array.map (<anonymous>)

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chromium

### How are you deploying Directus?

Locally & GCP

### PR DESCRIPTION
**Pull request by u12206050**
## Description

Fix the error from being thrown crashing the entire admin app. However, could discuss how we could use the throwing of such an error to actually validate filters? @rijkvanzanten 

Fixes #15275 

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [ ] Performed a self-review of the submitted code

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
> However, could discuss how we could use the throwing of such an error to actually validate filters?

In this particular case, the idea is:

- If object, return `object[key]` or default value
- If array, return `object[key]` for each item in array

In case `object[key]` doesn't exist in array, I think it should return the same default value used as for the regular object, thoughts? 🤔

**Comment by rijkvanzanten** [comment]
In any case, it shouldn't default to `null`, as `null` could be the actual value of a field, and doesn't necessarily indicate that the path couldn't be read. We could discuss using `undefined` instead, as that would be a better representation

**Comment by u12206050** [comment]
> 

The issue here however is that object itself could be `null` and `null[key]` throws the error.

I agree null as default might not be correct, but this PR is first choosing the lesser of two evils. 

We can put up an issue/task to implement testing the validation/permission in the context of the specified role during edit, and rather show an error message if we catch any thrown error.

Could `undefined` be a default value?

**Comment by rijkvanzanten** [comment]
> The issue here however is that object itself could be null and null[key] throws the error.

Yeah! So using optional chaining here would get around that, as `null?.[key]` will resolve to `undefined`, which then combined with the nullish coalescing operator makes it resolve to the defaultValue (which itself defaults to `undefined`). 

Another thing I'd like to look into is when context is even an array 🤔 As far as I can tell, this `get` is only used in the context of the `parseDynamicVariable` function, and the context that's passed is always of type `ParseFilterContext`, which is never an array.

**Comment by rijkvanzanten** [comment]
> I agree null as default might not be correct, but this PR is first choosing the lesser of two evils.

I would prefer to—and I'm sure that we can—find the real solution, rather than a quick lesser of two evils bandaid 🩹. Trying to avoid as much technical debt as I can 😁

**Comment by u12206050** [comment]
I do agree, and I was searching around for a better solution, but in the end, this getter function is broken if you were to unit test it. It shouldn't throw an error unless that is what you want from it.

As a single function its definition is either to get the value or undefined, or should be made clear that it might throw and error and calling methods should probably wrap it in try catch (which from usage I could tell was going to result in a much larger PR)

**Comment by rijkvanzanten** [comment]
I think a good solution here is to drop the use of that custom `get` altogether. It feels very copy/pasted to me, and based on the types and flow of data it's not needed at all. The only difference of this get function is that it supports Arrays as the input context, but the input context is never an array in the context of the filter parsing 🤔

**Review by rijkvanzanten — APPROVED** [review]

**Comment by u12206050** [comment]
> of the filter parsing

Lets hope so 🤣  Isn't the value of a `_between` filter an array of values that could be fetched from $CURRENT_USER.
eg. $CURRENT_USER.orgs.location could result in `['NYC', 'OSL', DUB', 'HKN']`

**Comment by rijkvanzanten** [comment]
@u12206050 Hmm yeah that's true. Lemme do some more research. Still odd how that `get()` function was included in that function. I think it was copy pasted in from app/utils without being replaced in `app`? Very messy

**Pull request merged**
