### PR TITLE
Add Many to Any Builder Interface

### PR DESCRIPTION
**Pull request by rijkvanzanten**
CleanShot 2020-11-27 at 13 56 51

### CODE REVIEW

**Comment by danieljwestman** [comment]
@rijkvanzanten Do you guys have any approximative ETA on this one? Saw something about "in a couple of weeks", and that was a couple of weeks ago 😃  I'm pre-launching a product soon and this feature would put some sugar on the top... 👍🏻

**Comment by benhaynes** [comment]
Should be merged in either later this week, or early next week.

**Comment by rijkvanzanten** [comment]
For those reading along, the settings pane to configure this is coming right up 😉

**Comment by caiguofeng0209** [comment]
👅👅👅

**Pull request merged**
