### PR TITLE
Fix m2a/m2a/o2m sorting

### LINKED ISSUE #18096: Sorting M2A items does not work anymore in Directus 9.24.0
### Describe the Bug

Just updated Directus from 9.23.1 to 9.24.0 and I noticed that I can not re-order M2A items anymore. They are still draggable, but jump back to their previous positions after dropping. When saving, the sort order isn't changed in the database as well. 
This happens with both existing collections and new collections. 

Reverted back to 9.23.1 and sorting works again.

### To Reproduce

Create a collection with a M2A field that contains a couple of different items and a sort field. Then try to re-order the items.

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by hanneskuettner**
Fixes #18096 

This bug was introduced in #17746. `toArray` turned our sortField string into eg. `['s', 'o', 'r', 't'][0] => 's'` which doesn't do well in being a field.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@hanneskuettner Are you [on Discord](https://directus.chat) by chance? Might help out for some other PRs 🙂

**Comment by hanneskuettner** [comment]
@rijkvanzanten sure thing! Also called Hannes there. The cookie monster avatar.

**Comment by Nitwel** [comment]
Ahh, I imported the wrong `toArray`! I wanted to use the one from `@directus/utils`not from `lodash`

**Comment by julbd** [comment]
> which doesn't do well in being a field.
I love this bug description

**Comment by hanneskuettner** [comment]
> Ahh, I imported the wrong `toArray`! I wanted to use the one from `@directus/utils`not from `lodash`.

I've updated it to use that one.

Just for my own understanding, is it just your preferred style (instead of optional chaining) or is it because sortField could possibly be something like `'sort,name,age'` which would result in `['sort', 'name', 'age']`?

**Review by paescuj — COMMENTED** [review]
Thanks @hanneskuettner & @Nitwel!
I can confirm this fixes the sorting for existing items 👍
However when it comes to sorting newly added items in a M2A field, a consequential issue has arisen (or at least I've noticed it now 😇):
As soon as items are dragged around, the interface would show "Unexpected Error" with the following error in the console:
 > TypeError: item[relation.value.junctionPrimaryKeyField.field] is undefined

I've applied a fix in https://github.com/directus/directus/pull/18196/commits/a0d7a1fd9f785294ed05028b28a4c469dd59524c which seems to work fine, but I'd like to have this fix confirmed by @Nitwel beause I might be missing the exact context of this.

**Comment by hanneskuettner** [comment]
Good catch! Makes me wonder if it actually worked before #17746 or what changed in the meantime.

Is there any way this could be caught in a test or is that probably more involved as it requires a full blackbox e2e test?

**Comment by rijkvanzanten** [comment]
> Is there any way this could be caught in a test or is that probably more involved as it requires a full blackbox e2e test?

The current blackbox e2e tests are hitting the APIs, not the app. As for testing this in the app, to test this properly, we'd need to have a testing setup that would mimic that users drag-and-drop action with another e2e suite I think 🤔 Tricky!

**Review by Nitwel — APPROVED** [review]
Looks good to me! Added some more tests to cover this case.

**Comment by Nitwel** [comment]
> TypeError: item[relation.value.junctionPrimaryKeyField.field] is undefined

Seems to be an oversight of me, should definitely be junctionField!

**Review by paescuj — APPROVED** [review]
🚀

**Pull request merged**
