### PR TITLE
Add a new interface for creating custom transformations from images

### PR DESCRIPTION
**Pull request by qborisb**
# Sections
## Feature Description
This PR proposes a feature that allows to transform the images that reside in `directus_files` **without modifying them** ([here is where](https://github.com/directus/directus/discussions/14578) the discussion about this feature started). This allows items from any collections to reference the image while having their own points of interest and keeping support for rotations and image flipping along X and Y axes (thanks to the `/assets` endpoint and the exposed sharp API).

Untitled

## Overview of the proposed changes

This PR creates a new interface called "Image Transformation"

Screenshot 2022-10-18 at 14 42 35

The options that this new interface has are very similar to the "Image" interface, with the difference being the **Image Transformation Collection**.

Screenshot 2022-10-18 at 14 43 04

This interface sets up the following relationship:

Screenshot 2022-10-18 at 14 41 13

How does it even work?

- Essentially, it is an M2A relationship `directus_files -- image_transformations_collection -- m2a_collections`, **with additional M2O relations from `m2a_collections` back to the image_transformations_collection**
- The new image_transformations collection (that is being called junction collection on the image) contains the following required fields (apart from the M2A fields and an ID):
  - **width** - width of the crop
  - **height** - height of the crop
  - **x** - x offset of the crop
  - **y** - y offset of the crop
  - **filename_download** - download name of the image transformation
  - **image_transformations** - JSON object containing remaining transformations - a boolean **flipY** for indicating whether the original image was flipped by Y axis, a boolean **flipX** for indicating whether the original image was flipped by X axis, and an integer field **rotate** keeping negative/positive degrees of image rotation, so that all supported features by the current image interface get covered
- M2A relation allows to get all transformations for each file, as well as the exact item that has the transformations and its collection. On the other hand, M2O relations back to the junction **image_transformations** allow the collections to keep a single image_transformation_id (instead of file_id comparing to the "Image" interface). This allows to easily load the image for each item that uses the new **Image Transformation** interface.

Here is the example of how the relationship looks like in the database (excluding additions to `directus_relations` and `directus_fields`:

Screenshot 2022-09-18 at 17 09 52

Screenshot 2022-10-18 at 14 53 44

Screenshot 2022-09-18 at 17 10 50

## TODOs
1. Show an error message for anyone trying to edit the file that has image transformations referencing it

2. Write tests and update documentation

3. Add custom image preview for the interface

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by br41nslug — CHANGES_REQUESTED** [review]
I've run into a small bug in the cropping/editing modal where it doesnt scale correctly on first load (in both Firefox and Chrome which is not happening with the regular image interface) this resolves itself once the page is resized.
image

**Comment by qborisb** [comment]
@br41nslug hello! Thanks a lot for the feedback & sorry for the late response, I've been a bit busy lately :)

Seems like it's not a bug because of my changes: I can reproduce it on the latest `main` with the regular image interface. Steps I took to reproduce it (perhaps the first two can be omitted):
1. Create a new collection with a field using Image Interface
2. Upload new image from the `admin/content/:collection/:item_id` page
3. Click "edit image"
4. Close the edit modal
5. Resize the browser window
6. Click "edit image" again (may require closing the modal and clicking again a few times)

So, it looks like a weird browser-resize conflict with the canvas to me. Perhaps if you are able to reproduce this on main, we could open a new issue :)

Otherwise, what would be the next steps for this PR? Seems like there is a pending approval from @azrikahar as well?

**Comment by br41nslug** [comment]
I thought i couldn't reproduce this on main at the time but will test again and if so then its a separate issue for sure 😄

**Review by br41nslug — APPROVED** [review]
This scaling issue i found does indeed not seem to be directly related to this PR

**Comment by qborisb** [comment]
Hello, @rijkvanzanten! Any there any feedback points that I can already address?

Also, I still need to implement the error messages in case you edit a file that has image transformations referencing it, perhaps we could discuss it in a later call / in discord? :)

**Comment by qborisb** [comment]
@azrikahar Hello! Rijk mentioned that you were going to make the feature in this PR into extension, what's the status of it? Would be nice to get it done! :)

**Comment by azrikahar** [comment]
@qborisb Heya! I've ported over this PR to a bundle type extension for the most part, but I'd love your help with figuring out the relationship aspect since we'll need to shift it into an extension option 🙏 I'll follow up with you on Discord so that we can discuss the details 👍

**Comment by rijkvanzanten** [comment]
Closing this in favor of distributing it as an extension! 🙂 

https://github.com/directus-community/image-transformation

**Pull request closed without merging**
