### PR TITLE
Use Twig for Installation #1235

### PR DESCRIPTION
**Pull request by Alxmerino**
#1235 

This makes use of Twig for the installation templates. 
- Fully converts php templates into twig
- Adds Twig helper to for functions used in templates
- Uses `__t` translation function as a filter.

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Nice! @Alxmerino I just want one thing before merge, can you send a PR to the development branch?

**Comment by Alxmerino** [comment]
I sent my `master` to `directus:develoment` you mean to sent it from my `development` to `directus:development`?

**Comment by WellingGuzman** [comment]
Great. Sorry I'm on my phone, it wasn't clear to me it was to development branch. I will merge it.

Thanks.

**Comment by benhaynes** [comment]
This is awesome @Alxmerino!!!

Thank you so much for this huge PR... we really appreciate it! 😄

**Pull request merged**
