### PR TITLE
Ignore email field in oauth and store email in external_identifier

### PR DESCRIPTION
**Pull request by aidenfoxx**
Should solve #9139 by ignoring the default email field in oauth providers, and storing the user email in `external_identifier` instead.

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by wc-matteo** [comment]
this is a breaking change. If you don't (manually) put the email in `external_identifier` for existing users, they cannot login starting from v100

**Comment by pratikbalar** [comment]
> @wc-matteo this is a breaking change. If you don't (manually) put the email in `external_identifier` for existing users, they cannot login starting from v100

I've migrated from 9.2.x to 9.4.3 still getting `304 /admin/login?reason=INVALID_USER` any way to migrate existing data with `external_identifier` ?

**Comment by aidenfoxx** [comment]
> I've migrated from 9.2.x to 9.4.3 still getting `304 /admin/login?reason=INVALID_USER` any way to migrate existing data with `external_identifier` ?

No changes have been made regarding this after the v9 release, so migrating from v9.2.x should not break anything.

**Comment by pratikbalar** [comment]
It was not working in 9.2 so i though latest could fix it but in vain.

**Pull request merged**
