### PR TITLE
Fixed the type definition of the `service` property in the ApiExtensionContext

### PR DESCRIPTION
**Pull request by Zehir**
Hello, 

I am not sure at 100% on that one and was not able to build on my local copy but the error seems unrelated :
`error TS2307: Cannot find module '@directus/data-sql' or its corresponding type declarations.`

Fix (maybe) #19806

Thank for your time to review this PR

### CODE REVIEW

**Comment by paescuj** [comment]
Hey @Zehir 
Thanks for your pull request! However, this is not something we can/want to support right now.
We'll eventually type the services and expose it via `@directus/types` but this requires some additional effort.
I'm closing this pull request for now. Thank you for your understanding!

**Comment by paescuj** [comment]
Also please ensure to follow our [Contributing Guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests)). This is to ensure that PRs that are opened will actually get the chance to be reviewed, merged, and maintained by the core maintainers.

**Comment by Zehir** [comment]
> Hey @Zehir Thanks for your pull request! However, this is not something we can/want to support right now. We'll eventually type the services and expose it via `@directus/types` but this requires some additional effort. I'm closing this pull request for now. Thank you for your understanding!

I don't really undestand why but ok I will wait for the correct way to type it and will keep using my [workaround](https://discord.com/channels/725371605378924594/1121094628037361768/1155920541673332786) until then.
Even if that was not perfect it's was better than `any`

Thanks

**Comment by rijkvanzanten** [comment]
@Zehir The problem with the proposed solution is that it creates a circular dependency between API and `@directus/types` 😬 My preferred solution would be to split off the services into a `@directus/services` and then have that imported in both `/types` and `/api`

**Comment by Zehir** [comment]
Ah ok I see, I did not notice that thanks for clarification

**Pull request closed without merging**
