### PR TITLE
Hooks logout

### PR DESCRIPTION
**Pull request by workatease**
added logout api hooks for before and after

### CODE REVIEW

**Comment by licitdev** [comment]
@rijkvanzanten Can there be activity tracking added using a `logout` action?

**Comment by workatease** [comment]
> @rijkvanzanten Can there be activity tracking added using a `logout` action?
yes we can do it... great idea

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten Can there be activity tracking added using a logout action?
> > yes we can do it... great idea

This is a difficult one. Most of the time, the user won't explicitly logout, but simply have their auth session expire. This auth hook won't be called in those cases, and the activity record won't be created

**Comment by workatease** [comment]
> > @rijkvanzanten Can there be activity tracking added using a logout action?
> > > yes we can do it... great idea
> 
> This is a difficult one. Most of the time, the user won't explicitly logout, but simply have their auth session expire. This auth hook won't be called in those cases, and the activity record won't be created

you are right.. activity means all users actions so if the users did not logout explicitly then do we need to add it.

**Comment by workatease** [comment]
do you think if we insert an activity if the refresh token has expired will help
https://github.com/directus/directus/blob/bd791bcb952e60c9cb6c511d70e3bbcce1f3c499/api/src/services/authentication.ts#L253

**Comment by licitdev** [comment]
I suppose having the manual logout activity tracked allow admins who monitor for security / audits.
As for expired tokens, I feel that it can be ignored, as the action isn't triggered by the user.

That gotten me thinking about a new feature to view users' sessions where admins can revoke... 🤔

**Comment by workatease** [comment]
We are deleting all expired token on next user login
So there will not be any expired token for admins to delete https://github.com/directus/directus/blob/bd791bcb952e60c9cb6c511d70e3bbcce1f3c499/api/src/services/authentication.ts#197

**Comment by rijkvanzanten** [comment]
> So there will not be any expired token for admins to delete https://github.com/directus/directus/blob/bd791bcb952e60c9cb6c511d70e3bbcce1f3c499/api/src/services/authentication.ts#197

I think Ian meant that the admin would be able to cancel _active_ sessions, to effectively force the user to logout 👍🏻

**Comment by workatease** [comment]
> > So there will not be any expired token for admins to delete https://github.com/directus/directus/blob/bd791bcb952e60c9cb6c511d70e3bbcce1f3c499/api/src/services/authentication.ts#197
> 
> I think Ian meant that the admin would be able to cancel _active_ sessions, to effectively force the user to logout 👍🏻 

So that will be a new features ... For now we can view it in the system collection and remove it manually

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
