### PR TITLE
Remove Content-Type header check in Files POST requests

### LINKED ISSUE #16140: useless conditional statement
### Describe the Bug

**About**
So we where reading these pieces of code at our office and noticed a useless conditional statement. We wanted to make a pull request but at this point in time its not possible sinds we don't have the knowladge of which piece of code to keep.

**Statement 1**
Like shown below from line 124 to 126 a check on the request content type is performed, if this request content type isn't the same as the specified one the async handler callback stops executing.
https://github.com/directus/directus/blob/228a5ca15f981f01c7072b641d53e1edf562629a/api/src/controllers/files.ts#L124-L126

**Statement 2**
So after the first statement the code will move on and from line 134 to 138 we meet the second statement, this statement checks if request content type is the same as the specified one.
https://github.com/directus/directus/blob/228a5ca15f981f01c7072b641d53e1edf562629a/api/src/controllers/files.ts#L134-L138

**The Issue**
So the is we have is that the else statement that corresponds with the second statement will never be executed sind we allready stopped executing the function within the first statement.

### To Reproduce

-

### Errors Shown

-

### What version of Directus are you using?

-

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

-

### How are you deploying Directus?

-

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Fixes #16140

#11347 moved the content type header check from `multipartHandler` to the files POST request controller, however it was wrongly assumed that POST request must always include multipart file(s). This prevented the creation of file entry _without_ actual file which was supported prior to that PR. Hence this PR removes the check altogether.

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by br41nslug — COMMENTED** [review]
Do we want to document the option of sending JSON to the `/files` endpoint? The current docs explicitly say you need to use `multipart/form-data` (https://docs.directus.io/reference/files.html#upload-a-file).
I think we should make `type` a required property when creating an empty file. The current test payload `{ title: 'Test File', storage: 'local', filename_download: 'test_file' }` gets a success response and is saved to the database but is not rendered in the App.

https://user-images.githubusercontent.com/9389634/198552551-e138e92c-5a3f-4ae4-adac-c688d5e0f851.mp4

**Comment by azrikahar** [comment]
> Do we want to document the option of sending JSON to the `/files` endpoint? The current docs explicitly say you need to use `multipart/form-data` (https://docs.directus.io/reference/files.html#upload-a-file). 

Agreed 👍

> I think we should make `type` a required property when creating an empty file. The current test payload `{ title: 'Test File', storage: 'local', filename_download: 'test_file' }` gets a success response and is saved to the database but is not rendered in the App.

That's a great point. Though I do wonder if it's intentional (and there's an existing assumption) that file type may be null? 🤔 It seems to be filtered here:

https://github.com/directus/directus/blob/a664623761500565313fcbcd49a3297e7790aeb0/app/src/modules/files/routes/collection.vue#L259-L263

FWIW I do personally still wonder what is/was the utility of being able to make the POST request without a file.

@rijkvanzanten thoughts on these points/questions? Here's a quick summary:

- Should `type` be a required property? 

- Currently the app filters out files without type when fetching them, is there a specific reasoning?

- The files POST endpoint allows creation of files with only JSON payload, is there a specific use case? As Tim pointed out, the docs does note that it must be `multipart/data` instead of JSON, so there might be so disparity between how the API should/actually work. 🤔

**Comment by rijkvanzanten** [comment]
The only real use case is so you can associate metadata with a file that already exists on disk

**Comment by azrikahar** [comment]
> The only real use case is so you can associate metadata with a file that already exists on disk

That does makes sense! In that case, I assume `type` and `filesize` should also be included by the user themselves when making such association? Not sure should this use case be documented somehow 🤔

> I think we should make type a required property when creating an empty file. The current test payload `{ title: 'Test File', storage: 'local', filename_download: 'test_file' }` gets a success response and is saved to the database but is not rendered in the App.

@br41nslug upon further inspection, I've noticed this block of code setting the default type for uploaded files in case there's no type:

https://github.com/directus/directus/blob/2adbb3bfd27639b3af4453d4ffcdd3be59736dea/api/src/services/files.ts#L68-L70

Perhaps we can do the same for JSON payload? It does at least show up in the App after I tested to put such default in place.

**Comment by br41nslug** [comment]
> Perhaps we can do the same for JSON payload? It does at least show up in the App after I tested to put such default in place.

We definitely could but as Rijk said the usecase for this is to associate meta with already existing files i think requiring people to assign the correct type for that may be the better way to go.

**Comment by azrikahar** [comment]
> We definitely could but as Rijk said the usecase for this is to associate meta with already existing files i think requiring people to assign the correct type for that may be the better way to go.

Makes sense! Was partially wondering would it be too strict in the case where the user themselves aren't sure about the type, but it does feel like that should fall under the responsibility of users going with such use case to be begin with. Added a check for "type" in FileService's `createOne` so now it is required in this scenario 👍

**Review by br41nslug — APPROVED** [review]
Looking good 😄

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
