### PR TITLE
Throw rejected error for filter event in Flows

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Throw the error upstream to break the event execution if the last operation of a filter event rejects. 

Example condition that rejects.

```json
{
    "$trigger": {
        "_null": true
    }
}
```

image

https://user-images.githubusercontent.com/26413686/186953973-da8089ec-aa3d-40a9-9faa-25eb69a4fa98.mov

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by nickrum** [comment]
I'm wondering if we should make this configurable using `flow.options.return` instead of hardcoding the operation that is responsible for determining if the flow should throw to the last operation 🤔

**Comment by rijkvanzanten** [comment]
> I'm wondering if we should make this configurable using `flow.options.return` instead of hardcoding the operation that is responsible for determining if the flow should throw to the last operation 🤔

So the user can control what operation's data is thrown if the last operation throws a reject?

**Comment by nickrum** [comment]
Yes, that's what I was thinking!

**Comment by rijkvanzanten** [comment]
That'd be a pretty interesting enhancement. As of right now, I think defaulting to $last makes sense, as it also makes it pretty obvious which handler caused the error in case of an error you didn't manually create/expect 🤔

**Comment by nickrum** [comment]
Isn't that shown in the flows log? I'm fine with keeping it the way it is. It just felt weird to make the data that is returned configurable but not the data that is thrown because those two are conceptually very similar.

**Comment by rijkvanzanten** [comment]
That's fair!

**Pull request merged**
