### PR TITLE
Add stacked drawers effect 

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Makes it a little clearer when you're in a nested drawer

https://user-images.githubusercontent.com/9141017/122998097-a1442280-d37a-11eb-8cd2-177ca39cee92.mp4

### CODE REVIEW

**Comment by benhaynes** [comment]
Adding this here for reference...

Item Drawers

**Comment by danieljwestman** [comment]
May this be included soon? Seen it been removed from a few RC's in the past...

Referencing discussion in this topic:

https://github.com/directus/directus/discussions/8635#discussioncomment-1447670

**Comment by rijkvanzanten** [comment]
@danieljwestman I'd love to have it, but the interaction right now is a little too rough for my taste. The animation on close is janky, as it has to wait for the top most layer to animate out before it animates the one below it. Once that's smoothened out we'll merge it straight away. Wanna try fixing that in a follow-up PR?

**Comment by rijkvanzanten** [comment]
https://user-images.githubusercontent.com/9141017/147313636-3476bded-5b55-4316-91a6-be0d6a825aba.mp4

Newest revision ✨ (The stutter/jank must be from doing a screen recording, don't see that in normal use)

@benhaynes I'm pretty happy with this. Shall we merge this and tweak it from there?

**Comment by benhaynes** [comment]
This is looking great! If that _jank_ is only in the screen-recording then this is good to merge on my side! 🧙

**Pull request merged**
