### PR TITLE
fix for filtering nested M2M relations

### PR DESCRIPTION
**Pull request by zimmersi**
hello,
first of all, thanks for this master piece of software

I ran into the same issue as described https://github.com/directus/directus/issues/5747

I solved it for me by adding the same special case to the followRelation path, that is used to add the join clause for o2m relations.

I hope it is not breaking anything else. at least the admin app it still working fine.

### CODE REVIEW

**Comment by joselcvarela** [comment]
Hey @Oreilles 
Can you take a look since you were assigned to that issue? 👍

**Comment by rijkvanzanten** [comment]
This seems like a more appropriate solution than https://github.com/directus/directus/pull/10626 🙂

**Comment by zimmersi** [comment]
Hi everyone,
do you have already any plans when this fix will be released?

**Comment by jaycammarano** [comment]
> Hi everyone, do you have already any plans when this fix will be released?

[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete.

---

_This is an automated response._

---

That said I will try to review it ASAP.

**Review by jamescammarano — COMMENTED** [review]
This looks good to me.

**Comment by rijkvanzanten** [comment]
@jaycammarano could you add a test case to the E2E tests that covers this?

**Comment by jaycammarano** [comment]
> @jaycammarano could you add a test case to the E2E tests that covers this?

I was going to but I couldn't push to the repo.

**Comment by zimmersi** [comment]
thank you so much!
keep up the awesome work.
There is a good chance that we will become a monthly sponsor soon.
But since we are just a non-profit company, our resources are very limited!

**Pull request merged**
