### PR TITLE
Add extension auto reloading to the API

### PR DESCRIPTION
**Pull request by nickrum**
This can be enabled by using the `EXTENSIONS_AUTO_RELOAD` env var.

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rashidpathiyil** [comment]
Now we can watch changes of extensions without restarting directus app?

**Comment by nickrum** [comment]
@rashidpathiyil yes, you can set the `EXTENSIONS_AUTO_RELOAD` environment variable to `true` to instruct Directus to reload any changed, added or removed extension. When working on App extensions, you still have to manually reload the browser, though.

**Comment by Mukhammadali** [comment]
Hi @nickrum. Thanks for the great work! But  is there any reason why app extensions do not auto reload?

**Comment by nickrum** [comment]
@Mukhammadali App extensions should also auto reload when `EXTENSIONS_AUTO_RELOAD` has been set. Currently you have to reload your browser manually to see the changes, though.

To do this automatically, we'd have to either add websockets support to Directus or we'd have to add a dev server like Vite to the extensions-sdk to have proper HMR.

**Pull request merged**
