### PR TITLE
Add DX Module

### PR DESCRIPTION
**Pull request by Nitwel**
## Description

This PR will add a new module to Directus to improve the developer experience when writing a new Extensions for the app.

grafik

Note that this module will only be loaded when in development mode.

### CODE REVIEW

**Comment by awesome-developer-20** [comment]
Any reason behind this inovative/thought provoking/creative branch name 😅

**Comment by rijkvanzanten** [comment]
@awesome-developer-20 I asked about that on Discord earlier and the answer was _"Just calculate the integral and put the numbers into a ascii/utf8 converter."_ ..... 🤷🏻 

According to _the internet_, you could also write it as 

$$
x (x (x (x (x (x (68 x + 105) + 114) + 101) + 99) + 116) + 117) + 115
$$

which makes it way more obvious[^1].

[^1]: I have absolutely no clue what's going on

**Comment by Nitwel** [comment]
The reason why I decided for this name was because the `DX` from Developer Experience reminded me of `dx` as in ∫f(x)dx and then I decided to also throw in some ascii numbers that spell `Directus` in order to spice tings up a bit.

**Comment by Nitwel** [comment]
Also, since when can you write Latex in here? 👀❤️

**Comment by awesome-developer-20** [comment]
> The reason why I decided for this name was because the `DX` from Developer Experience reminded me of `dx` as in ∫f(x)dx and then I decided to also throw in some ascii numbers that spell `Directus` in order to spice tings up a bit.

Really creative 😅. I solved the equation but didn't thought of using it's coefficients as ASCII values.



> Also, since when can you write Latex in here? 👀❤️

Ohh yeah, just noticed it. It actually renders latex in branch name 😅

**Comment by Nitwel** [comment]
Oh that's not latex in the branch name, that's just a bit of trickeronie done by me. 😄

**Comment by awesome-developer-20** [comment]
> Oh that's not latex in the branch name, that's just a bit of trickeronie done by me. 😄

Then, how have you written integration sign, x to the power 3, etc in branch name 🤷

**Comment by Nitwel** [comment]
That are just casual UTF8 Symbols:
grafik

**Review by connorwinston — CHANGES_REQUESTED** [review]
I can not get this to build, I believe it has to do with the large amount of changes to the code base over the last week. I would merge in main myself and see if I can get it going, however, there are merge conflicts...and with not being as familiar with this code I wanted to leave it to you @Nitwel so I don't mess anything up!

**Comment by paescuj** [comment]
We're closing this pull request for now, as we'll work on other changes to extensions before and would therefore like to prevent conflicts with the work in this PR. Such a functionality might be reconsidered later on.

**Pull request closed without merging**
