### PR TITLE
Add query support for filter and search on main collection view.

### PR DESCRIPTION
**Pull request by u12206050**
## Description

Updates filter and search options in the url so that you can copy it and share it with a colleague of client.
Doesn't affect bookmarks, so is only active on the main collection view. 

AppContentQueryOptions

Fixes #

## Type of Change

- [ ] Bugfix
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by benhaynes** [comment]
Love it! Of course we still need to work around the URL max length limit, so I wonder if there's any minification we can do on the query string. I defer to Rijk on if this is something we can do, as we've discussed it before and didn't implement for the above reason.

**Comment by u12206050** [comment]
I could definitely compress the json string, although then the question becomes how readable to you want it?

**Comment by u12206050** [comment]
I just realised any filter&search query in directus, is anyways requested via query params from the Directus API. So if in general it hasn't been an issue, then this won't cause an issue either.

It seems the typical limit is 2048 characters which allows for quite a lot, so I would think for most cases it won't be a problem. Here is an example of 2048 characters just for reference :)

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae dui lectus. Curabitur tellus massa, maximus non ullamcorper a, rutrum a purus. Vestibulum eget orci quis tellus aliquet blandit nec scelerisque elit. Sed at ultricies lectus. Suspendisse potenti. Pellentesque non dui eu urna placerat sollicitudin eu et mi. Nunc sollicitudin neque elementum lectus ornare, a convallis neque feugiat. Sed vel tortor ornare, pretium enim nec, sollicitudin ante. Aenean aliquet dolor et lacus mollis, sit amet efficitur eros fermentum. Phasellus facilisis ex vel aliquam accumsan. Vivamus turpis nunc, ultricies congue eleifend in, accumsan eget leo.
Pellentesque finibus scelerisque lectus non pharetra. Duis ligula lorem, luctus ut tristique ac, scelerisque in nunc. Curabitur ut ultricies massa. Vestibulum risus turpis, elementum vel quam nec, rhoncus congue augue. Curabitur sit amet dictum dui. Nulla eros metus, suscipit suscipit ipsum mollis, bibendum egestas arcu. Donec felis diam, congue id suscipit sed, mattis vel tortor. Vivamus aliquam lorem eros, eu euismod erat pulvinar tempus. Etiam convallis condimentum gravida. Praesent suscipit a nisl ac pellentesque. Aliquam convallis a ex eget lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi mi felis, porttitor quis pretium quis, venenatis id eros. Integer aliquam luctus augue, quis posuere ipsum scelerisque eu. Donec vel neque posuere, varius ante et, bibendum quam. Suspendisse sit amet viverra augue.
In hac habitasse platea dictumst. Proin maximus id dui vitae ultricies. Pellentesque eget nibh a orci sagittis condimentum. Phasellus consectetur dapibus nisi vitae dictum. Praesent non dui fringilla, convallis elit vitae, cursus nisi. Nullam ornare sollicitudin bibendum. Phasellus eu dignissim diam. In eleifend orci diam, et ornare augue aliquam a. Nam rutrum nec turpis sed consequat. Sed in molestie risus, et scelerisque sapien. Vivamus nec turpis vehicula, lacinia velit sit amet, vulputate justo. Duis feugiat, erat vel.
```

**Comment by u12206050** [comment]
Could really use this feature asap :) Often helping users setting up presets and needing to get in a meeting with them just to help them with filters. Using this I can just do it on my end and send them a link :)

**Review by br41nslug — APPROVED** [review]

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
This currently only runs in the first `setup` call of the component, which means that it will only work on hard refreshes / direct navigation. If you link from another collection route, this logic doesn't trigger. I think we should rely on the vue-router lifecycle hooks to make sure we keep these in sync.

Also a tad worried about infinite update loops between query changes and the local filter/search if any of the two does any parsing beyond stringifying the underlying object

**Comment by u12206050** [comment]
> This currently only runs in the first `setup` call of the component, which means that it will only work on hard refreshes / direct navigation. If you link from another collection route, this logic doesn't trigger. I think we should rely on the vue-router lifecycle hooks to make sure we keep these in sync.
> 
> Also a tad worried about infinite update loops between query changes and the local filter/search if any of the two does any parsing beyond stringifying the underlying object

That is correct, but also intentional. Since the idea is that the use of this is for opening a link sent by someone else and having the collection open with the filters and queries applied as contained in that link.

I don't see a use case for the query string to be "watched", thus in the current state no chance for infinite loops.

Do you have a use case, please let me know :)

**Comment by u12206050** [comment]
My number one use case is from support emails, users stating they don't understand how to filter, or get a specific set of results.

Per today I have to setup a meeting with them and show them how to do it, versus being able to just generate the view on my end, copy the url and send it over to them.

Note also, that the query only contains the filters and search, not the layout or columns, since the other user might have different permissions.

**Comment by u12206050** [comment]
Found a very nice use case, for supporting using the vue-router hooks. 
When you have selected a bookmark, and then slightly changed it, and then select and item: Currently when then navigating BACK, the collection view is reset to what the original bookmark state, however with this PR (after I fix it) you can keep the state you were in, and therefor have the option to both update the bookmark or reset it.

**Comment by u12206050** [comment]
@rijkvanzanten  Thanks for the tip and getting me to do this. It is so much better and useful now. It actually fixes a long time ux issue I had, where I would alter a bookmark slightly to find items but as soon as I navigate to and back from those items then the bookmark state would reset. Now with this PR it is stored in the query string.

LatestVersionParams

Ready for release?

**Review by andreasgangso — APPROVED** [review]

**Review by andreasgangso — APPROVED** [review]

**Comment by u12206050** [comment]
@rijkvanzanten quick merge? :) Would really help us in delivering support to "not-so-technical" users

**Review by u12206050 — COMMENTED** [review]
It now works not only on setup.

**Comment by u12206050** [comment]
@rijkvanzanten  Don't know why I can't close your requested change, but it in any case is fixed as mentioned above.

Shall I book a 15min meeting with you to go through it and get it merged? Would help a lot with or less-technical users.

**Comment by rijkvanzanten** [comment]
> Shall I book a 15min meeting with you to go through it and get it merged? Would help a lot with or less-technical users.

No, I can't prioritize this new feature over the current in-progress items at this time. We have limited engineering cycles to spend, so have to stick to our prioritization of work. 
Generally speaking, a PR for a new feature should really have a Discussion labeled "Accepted", and a corresponding issue which outlines the exact to-be-implemented points before the implementation PR is started. PRs that don't have any previous discussion cost a lot of time to reverse engineer[^1], think through, and review, so can't be slotted in at the top of the list. I'll update the contribution.md file shortly to make our workflow more explicit.

[^1]: As an example for this particular feature. You've made technical decisions on the query params, like using `search` and `filter`, but not `sort`/`fields`/etc which we have to cycle back on. Similarly I noticed that this only seems to be implemented for Content, but not for users/files/dashboards/presets/etc. We also haven't thought through or discussed what this means for presets in general, whether or not presets / bookmarks are even useful if the full structure is in the URL, etc etc. Hence the discussion point above!

**Comment by u12206050** [comment]
Thanks for explaining that is fair. I'll setup a discussion then. :)

**Comment by u12206050** [comment]
> 

Just some quick remarks:

This is a PR for the content module explicitly, other modules such as users, dashboard and files do not have a need for this at the moment, but could be implemented in different PRs.

As for sort and fields, both are more dependent on the permissions the user has. Eg. if you sort on a field that the other user doesn't have access to it fails. Same for including fields that the other user doesn't have access to.

Adding fields in the table view and sorting is not as hard as filtering on very specific things, so explaining that is a bit easier.

**Comment by Saissaken** [comment]
Well done! Exactly what I need.
Hopefully we get more participation on the discussion #16228 so we can help design this and get merged!
Anyone interested please leave your 2c on the discussion, explain your use-case.

**Comment by koksikus** [comment]
It would be very useful to me today.  Firstly, to make a copy of the filter so I can go back to it.  As well as to share the results of the search with a colleague.

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
