### PR TITLE
Fix: keep folder while replacing files

### PR DESCRIPTION
**Pull request by dr-wahrheit**
## Description

Fixes #17427

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by WoLfulus** [comment]
@rijkvanzanten I see that you've approved this, but I don't think this fixes the issue at all nor does it has any effect since when replacing a file a PATCH request is made to `/files/:id`, with only the file buffer in the payload, so the folder itself when replacing a file is not driven by the app.

If for some reason this actually worked, having the app opened in a outdated file (for example someone else moved it to another folder), the actual folder would be overwritten by the replace action since there's a mismatch between client and server state.

@dr-wahrheit 

The actual fix should would be moving this block of code:

https://github.com/directus/directus/blob/37faf3bd5d0978812362d1803b4e2d6c2ce2d9f6/api/src/services/files.ts#L43-L49

Inside this else block and before the `createOne` statement.

https://github.com/directus/directus/blob/37faf3bd5d0978812362d1803b4e2d6c2ce2d9f6/api/src/services/files.ts#L62

And BTW, there's another bug with the replace operation that I think could be fixed in this PR (I'm not sure how the team is tracking progress and if it needs to be done in another issue/PR, buuuut): 

At this check

https://github.com/directus/directus/blob/37faf3bd5d0978812362d1803b4e2d6c2ce2d9f6/api/src/controllers/files.ts#L73

I believe this should also have a `&& !existingPrimaryKey` in the conditional. Because it will overwrite the file title whenever the file contents are updated.

**Comment by dr-wahrheit** [comment]
As far as I could see (I just started to see the Directus code ^_^) when a file is replaced via app (PATCH in /files/:id) all parameters are sent together with the stream as form-data . On the API side, the call is managed by a "multipartHandler" 

https://github.com/directus/directus/blob/37faf3bd5d0978812362d1803b4e2d6c2ce2d9f6/api/src/controllers/files.ts#L283-L286

which extracts them and then sends them to the "uploadOne".

https://github.com/directus/directus/blob/37faf3bd5d0978812362d1803b4e2d6c2ce2d9f6/api/src/controllers/files.ts#L92

It is therefore not entirely correct to say that they are not driven by the app.

Having said that I don't know exactly how the competition is and should be managed. You could actually edit a file that someone edited/deleted...that's good food for thought...

As for the second point, you are probably right, but it all depends on how you want to manage the "default folder" on the API side. I opened an issue about it https://github.com/directus/directus/issues/17518

For the third point I leave it to @rijkvanzanten

**Comment by WoLfulus** [comment]
The API supports patching any field, yes. But if you look at network inspector when replacing a file within the app, you'll see that it will only send the "file" field once you hit replace. Adding the folder field in the app will just mask the problem and it will still happen to someone using the API instead (in case of patching only the file contents)

**Comment by dr-wahrheit** [comment]
Yes, the change solves the problem on the app side.

On the API side, as you pointed out, if the "folder" parameter is not passed, the default folder is set, so if you need to modify the file you must necessarily also send the reference to the folder that contains it.

It might be a good idea to do as you suggested and move the check only to creation (Between us I would 😄). The problem could be linked to the issue I opened (#17518). 

@rijkvanzanten, what do you think?

**Comment by WoLfulus** [comment]
I did read #17518 but as @rijkvanzanten said, it sounds more like an issue on how you expect it to work inside the app. 

For example, I do expect the upload to land on the folder I'm currently at in the app (that includes the root folder too), as I currently do upload a lot of files to the root folder in a project I'm working on right now and I still have the default folder set in that project to another "Uploads" folder, just to avoid mixing things up if it's sent through the API without having folder set in the payload. 

For me the "default folder" works more like a "fallback folder" rather than a "default" one, as I always expect the folder to be set to the current one when I'm uploading a new file through the app.

Maybe it's just the wording in this case that causes confusion.

**Comment by Nitwel** [comment]
This will be closed in favour of #17744 as it is a api side bug.
Still thank you alot for your contribution @dr-wahrheit ! ❤️

**Pull request closed without merging**
