### PR TITLE
Actions presentation interface

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
A kind of port of v8's preview interface. 

UI:
image

image

### CODE REVIEW

**Comment by benhaynes** [comment]
Thank you @dimitrov-adrian!! Would love to add this back in to v9... really appreciate this one!

Some questions:

* Do the template strings allow for dot-notation and relational fields? eg: `{{author.id}}`
* Can we have the interface height match the global sizing? I think it's 52px tall in height, with 4px border radius (there should be global vars for these)
* Curious about the "pill-box" combined style, vs the just having separate buttons
* Wondering if we want to use the predefined style strings, or exact colors. I think I see why you used the strings here, but maybe that's not an issue if we use standard buttons?
* Maybe we could add a "Open in New Window" toggle option? That would also resolve that empty area in the half option. 😉

**Comment by dimitrov-adrian** [comment]
> * Do the template strings allow for dot-notation and relational fields? eg: `{{author.id}}`

Yes

> * Can we have the interface height match the global sizing? I think it's 52px tall in height, with 4px border radius (there should be global vars for these)
> * Curious about the "pill-box" combined style, vs the just having separate buttons

Actually I got with v-button-group component they just looks like pile, and using the default round from the component, may be separated button will looks bit more formal. I will try it.

> * Wondering if we want to use the predefined style strings, or exact colors. I think I see why you used the strings here, but maybe that's not an issue if we use standard buttons?

Standard buttons are two types only, normal (which seems to be an primary) and secondary.

I had think of more meanful names, instead of green, orange and etc. The colors are not exact, but using the names so ensure will looks good on light theme too.

> * Maybe we could add a "Open in New Window" toggle option? That would also resolve that empty area in the half option. 😉

😁

**Review by rijkvanzanten — APPROVED** [review]

**Comment by t7tran** [comment]
@rijkvanzanten It seems that `Open in New Window` option never get implemented. Can we add support for specifying `to` property instead of `href`?

**Comment by rijkvanzanten** [comment]
Do you mean add support for `target="_blank"`? Changing from `href` to `to` would just allow for client side routing in the app, which isn't what you're looking for if i"m understanding correctly

**Comment by t7tran** [comment]
Ah, I see the risk with `to` support. `target="_blank"` is implemented as the default behaviour. I was looking for the option to turn it off. But that would just break the user experience. Sorry, please ignore.

**Pull request merged**
