### PR TITLE
Update quickstart.md

### PR DESCRIPTION
**Pull request by mcmadafly**
## Description

Fixes #

## Type of Change

- [x] Bugfix
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
These two aren't the same! `npx directus init` will download the `directus` package, and call the CLI's `init` command, while `npm init directus-project` will use the `create-directus-project` package, which includes some other scaffolding 👍🏻

**Comment by vanling** [comment]
@rijkvanzanten Maybe an issue needed then? the quickstart code resulted in error here too

Schermafbeelding 2022-06-03 om 21 45 43

**Comment by rijkvanzanten** [comment]
@vanling What version of npm are y'all using? Looks like there might be a difference in how it's pulling in the optionalDependencies of the API 🤔 

This is on 8.5.5:

CleanShot 2022-06-03 at 15 48 04@2x

**Comment by rijkvanzanten** [comment]
(and yes, `ioredis` should be moved into the regular dependencies, lemme push up a commit for that regardless, still confused as to why it would work differently on different versions of npm tho)

**Comment by vanling** [comment]
```
npm --v. 8.10.0
```

**Comment by vanling** [comment]
Just switched to npm 8.5.5 and same error

node; v16.13.0

**Comment by rijkvanzanten** [comment]
Odd! I must have something in my globals then or something 🤔 It works for me as expected under 8.12 as well

**Comment by vanling** [comment]
NPM could do some nasty caching of packages (or globals yes)

**Comment by rijkvanzanten** [comment]
Yep... and they've had their fair share of unintended breaking changes during the 7.x and 8.x lifecycles as well, so I can't exclude anything there either.. 😭 

In any case, i'll move that optionalDep into regular deps, as the API does load it in at all times now for the messenger setup 👍🏻

**Comment by vanling** [comment]
Cool! now you made me curious into the difference between the two methods 🤓 _Down the rabbithole we go_

**Comment by rijkvanzanten** [comment]
TL:DR:

`npx directus init`

expects directus to be installed and expects you to be in a project folder you want to use, and sets up the database + generates a .env file

`npx create-directus-project` or `npm init directus-project` (same thing!) will generate this project folder first, then install `directus` and _then_ actually run `directus init` on your behalf 🙂

**Comment by vanling** [comment]
Cool thanks for the explanation. And i have directus globally installed i guess so my guess is that `npx directus init` always works

**Comment by rijkvanzanten** [comment]
Yeah! And in later versions of `npm`, `npx` will offer to install the package if you don't have it installed globally yet, so you end up in a similar position (except you miss out on the project folder scaffolding)

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/directus/pull/13719

**Pull request closed without merging**
