### PR TITLE
Fix relative link routing in button links

### LINKED ISSUE #8347: Button Links with relative URL opens a new window/tab
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

If you add Button Links with a relative URL (like` /collection`) as a "Presentation & Alias" field to a collection, a click shouldn't open a new window/tab.

Screenshot of Associations

### To Reproduce

See above.

### What version of Directus are you using?

v9.0.0-rc.94

### What version of Node.js are you using?

v15.14.0

### What database are you using?

PG 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally / NPM

### PR DESCRIPTION
**Pull request by licitdev**
Fixes #8347.

### CODE REVIEW

**Review by azrikahar — CHANGES_REQUESTED** [review]
Perhaps it would be better if we follow the same code style/logic Rijk implemented like in your recent module bar relative link PR, specifically here: https://github.com/directus/directus/pull/8130/commits/c8bde307372f52955e8ceee320fdc6ece89bb54a#diff-9a48f84c69616cffc686c1215f45b4e04775136c5eeb149c2d752e2807e48fd6L60-R69

just for uniformity sake 😄

**Comment by licitdev** [comment]
@azrikahar May I ask what do you mean by the same code style/logic?
Do you mean change `:href="link.url"` to `:href="link.href"`?

**Comment by azrikahar** [comment]
> @azrikahar May I ask what do you mean by the same code style/logic?
> Do you mean change `:href="link.url"` to `:href="link.href"`?

Ah sorry for that.. I meant how yours is `if is relative (starts with "/"), else not relative`, but Rijk opted for the reverse, which is `if not relative (starts with "http"), else is relative`.

**Comment by licitdev** [comment]
> Ah sorry for that.. I meant how yours is `if is relative (starts with "/"), else not relative`, but Rijk opted for the reverse, which is `if not relative (starts with "http"), else is relative`.
@azrikahar It has been changed in #8225 

The new PR uses omit like in the other PR, skipping the need to add `to` and `href` into the typings.

**Comment by azrikahar** [comment]
> @azrikahar It has been changed in #8225
> 
> The new PR uses omit like in the other PR, skipping the need to add `to` and `href` into the typings.

didn't notice #8225🤦‍♂️ really sorry for the confusion.

Thanks for the new update! LGTM

**Review by azrikahar — APPROVED** [review]

**Comment by licitdev** [comment]
@azrikahar No worries~ Thank you! ☺️

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
