### PR TITLE
Feature: don't expose admin url (optional)

### PR DESCRIPTION
**Pull request by GinMitch**
While building a project I found out that Directus 9 is exposing `/admin` path so here's a quick fix I tried locally. Would be happy to discuss & contribute.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@mullinsmikey I'd rather just make that the default behavior instead of adding another flag 🤔 

That being said, I do think it's important to have a more "friendly" `/` route. It'll most likely be the first thing people see when opening a new installation, so having it immediately shout "ACCESS DENIED" might be a little harsh.. (That's the primary reason we redirect to `/admin` now, as there's nothing under `/`) (Also considering non-technical users that might forget about the `/admin` part and get "stuck" on a technical (read: JSON) error message)

**Comment by benhaynes** [comment]
I'd like to hear more about why this is useful. Thinking of 80/20, it seems that most users would want to have the convenience of being redirected to the admin app when going to the root. Is this really a security concern?

Also, do we allow configuring the `/admin` path name, or is that static?

**Comment by WoLfulus** [comment]
> Also, do we allow configuring the `/admin` path name, or is that static?

That would be lovely!

I'm +1 to being able to configure `/admin` or at least setting prefixes for all Directus routes (like put everything under `/api`). This would make it a lot easier to integrate to other products/frameworks and run Directus together with them.

**Comment by mullinsmikey** [comment]
@rijkvanzanten you're totally right. This PR is mostly to be considered as an option. The default behavior could be just as you said - a kind of "soft error".

Speaking of this usability, we at Akoola host Directus on the subdomain while the service itself is public, and we don't want anyone to access the backend login page unintentionally. Even though our accounts are protected with 2FA, this additional security measure would be really nice.

**Comment by mullinsmikey** [comment]
Alright then, as I see this suggestion is not a "quick and dirty fix with TODO" but a more complex feature I could possibly work on.
You might want to discuss this idea (configurable login route, root page, etc) and I'd be happy to contribute to the project I use and appreciate. 🙂

**Comment by rijkvanzanten** [comment]
Original repo/branch doesn't exist anymore. This'll be continued in https://github.com/directus/directus/pull/4937

**Pull request closed without merging**
