### PR TITLE
Add a submit button to free up the enter key for line breaks (WIP)

### PR DESCRIPTION
**Pull request by wittwerch**
This PR addresses #1621. It allows a user to add line breaks to comments using the enter key. To submit a comment you have to explicitly click on the submit button.

To do:
- [ ] Style the button (I'm super bad at that :))
- [ ] Disable the automatic expansion of the comment field back and forth when you want to submit the comment

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Awesome @wittwerch, ping one of us when this is ready to test.

**Comment by wittwerch** [comment]
@WellingGuzman Actually beside the two tasks the implementation is complete. I struggled a bit with both tasks (that's why I created them in that PR). Could you have a look at it?

**Comment by WellingGuzman** [comment]
Hey @wittwerch thanks, it looks nice, i will give it a shot in a moment.

About the two task, @benhaynes or @rijkvanzanten can help you with that, unless they want to take it from there after merge.

**Comment by WellingGuzman** [comment]
Thanks @wittwerch, it's working perfectly @benhaynes or @rijkvanzanten will work on the styling.

**Pull request merged**
