### PR TITLE
Add Tree-View Interface

### PR DESCRIPTION
**Pull request by rijkvanzanten**
CleanShot 2021-03-19 at 18 26 06@2x

### CODE REVIEW

**Comment by LasseRosenow** [comment]
@rijkvanzanten do i get it right, that if this only works for one to many relationships, that you would have to always look for the root "menu" item first, to setup the menu structure correctly in the tree view?

**Comment by rijkvanzanten** [comment]
I'm not sure what you mean by the "you would have to always look for the root "menu" item first", but yes, it's a nested o2m structure where each parent item of the same type has one or more children

**Comment by LasseRosenow** [comment]
> I'm not sure what you mean by the "you would have to always look for the root "menu" item first", but yes, it's a nested o2m structure where each parent item of the same type has one or more children

What I mean is, that if I have a menu structure, I would have multiple entries, like in your screenshot: "about us", "products", "computers" etc. in the collection overview. But to find the treeview like it is in your screenshot, I would have to open the correct menu item, that is the root of all items first. I guess its some sort of "root" item in your case, that is the parent of "about us", "products" etc. But if i would open any of the other items from the collection overview, I would only see a part of the tree.


What I would like to have is the ability, to have some sort of view, like some sort of single instance object, which i just have to open and than would be able to see the whole tree right away. 

A simple solution for that would be the ability for collections to just specify a default item that just opens instead of the list of all items. In that case I could always show the root menu item straight away and would not have to find it in the list first to get the full tree-view. Or is this already possible?

Or are there any other ways to achieve what I would like to have?

**Comment by rijkvanzanten** [comment]
Ahh I see what you're saying. One quick way to achieve that is to add a filter that checks for `parent = null`, which would make your collection view only show the root items 🙂

**Comment by LasseRosenow** [comment]
@rijkvanzanten So now my current approach in Handling menus is creating a single instance collection called for example `main menu`, which has a O2M relation to a recursive collection called `menu-items`. 

This is working quite well, but it has the huge drawback, that you only have the tree view within the childs of `main menu`.

It would be amazing, to have one huge tree-view with in the `main menu` instance, so my proposal would be to maybe enable the tree-view on O2M relations, if those have a recursive collection as their target.

I think this should work without any problems like having to many relations and not being able to tell which relation to pick from, as it would be limited to O2M on recursive collections (the recursive collection would be the M here).

What do you think about this Idea, did I miss something important, or do you think this would be doable? :)

**Comment by LasseRosenow** [comment]
Actually after putting a little more thought into it, I think tree-views should be enabled for O-M relations in general.

I guess the reason why this is not done right now is, because not every item in a nested tree-view are necessarily from the same collection, so you cannot just move everything around and make each item a child of each other item.

But that could be fixed by for example checking the whole tree, when starting to drag an item, if it can have the currently being dragged item as a child. So one way would be to give all the items that cannot have the currently dragged item as a child, a dark background or make them more transparent or something like that just so you can see, where its possible to release the item and where not.

So I actually created a discussion for this: directus/directus/discussions/7447

**Pull request merged**
