### PR TITLE
Docs: Better configs structure to support multilingual docs, initial version of ru-RU docs

### PR DESCRIPTION
**Pull request by TemaSM**
- Removed obsolete `package-lock.json` file in `/docs`
- Updated dependencies in `/docs`
- Refactored Vitepress config to fit with multilingual docs ideology
- Added `vite-plugin-mkcert` to make docs to work via https on localhost (this prevents occuring browser's errors when loading https content from http page)
- **WIP**: Translated several pages into Russian language
<details>
<summary>Translated home page of Docs into Russian: screenshot</summary>
  
home_ruRU

</details>

🚧 **Work in progress**: will continue translating docs to Russian
<details>
<summary>⁉️ My observations on multilingual documentation and Vitepress vs Docusaurus</summary>
At the moment I see a drawback of Vitepress - poor i18n support.

If we start translating Vitepress-based documentation, the documentation will essentially have two versions of each file (.md), or `n * languages` and a lot of repetition in translation strings.

I think this is a very bad practice, as the responsibility for keeping the documentation up to date in a particular language will lie with the translators, not with the core Directus team, who a priori have more complete information about the product.

For example, the [pnpm project uses Docusaurus (React)](https://github.com/pnpm/pnpm.io), which has only single .md files as documentation in different languages.

The strings from these files are automatically uploaded to Crowdin, and then taken from there automatically to generate static documentation in different languages.

This approach allows you to use the source lines from the .md documentation as a single source of true information. And even if a part of some lines, sentences or paragraphs is not translated into the required language, the documentation in place of these lines (for example, in Russian-language documentation) will have lines in English. And this is much better than having outdated documentation in Russian or any other language.

Saying all this brings me to the point of bringing up the idea of trying to switch documentation from Vitepress to Docusaurus, but with support for Vue components that are already implemented in Directus documentation and its packages.

We will be able to build a competent and tight integration with Crowdin. This will allow translators to help with string translation not only in the Directus application interface itself, but also with translating the entire documentation into different languages, taking into account all the features of its design, custom components and other elements of the identity.

As a result, everyone wins - translators will get a simple and clear way to translate everything related to Directus, and Directus in turn will get more competently localized resources, which will inevitably lead to the popularization of the product in different countries.
At the same time, neither the Directus team nor the translators will have to service any technical debt to maintain the correct structure of translations, localized documentation, and getting rid of repetition in translation strings.

</details>

### CODE REVIEW

**Comment by paescuj** [comment]
Heya! Thank you for your contribution. Unfortunately, we can't accept PRs for improvements/features that don't have a prior accepted Discussion and associated Issue (as per the [Contributing Guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests)). This is to ensure that PRs that are opened will actually get the chance to be reviewed, merged, and maintained by the core maintainers. We can reopen and continue this PR review once the requirements have been met. Thank you for your understanding!

**Comment by rijkvanzanten** [comment]
We also (unfortunately) don't have the resources on the team to properly maintain all the docs in multiple languages 😬 I appreciate the idea and effort put in, but that's just not something we can take on at the moment

**Comment by TemaSM** [comment]
Thank you for your responses!
@rijkvanzanten I could put forward my position as a maintainer of the Russian version of Directus documentation.
Ready to take on this load of work, with the responsibility to keep the documentation up to date (synchronously pulling changes from the English version of the documentation).
Open to discussions on this part. We can chat in Discord on the Directus server (username: `temasm`), or in GitHub Discussions.

*Also, I'm looking forward to when we can move the documentation to a fully multi-lingual version, e.g. with seamless integration of Docusaurus and Crowdin (see "my observations on multi-lingual documentation and Vitepress vs Docusaurus" in the PRs description) - I've already contacted Ben about this, but it certainly requires general discussion. And I'm willing to do my best to improve the Directus documentation in a variety of ways.

**Comment by TemaSM** [comment]
Ok, thanks got it 👍 
So I'll focus my attention on the Russian translation in Crowdin.

**Pull request closed without merging**
