### PR TITLE
Fix padding v-field-template

### PR DESCRIPTION
**Pull request by YannickMol**
Fixes Rijk's comment on #4020

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
That same problem in my comment will surface every time a `<template #input>` is used though, so I think we'll have to add that padding on the `v-input` still, but do it based on whether or not the slot is dynamically filled, or using the default `<input>` 🤔

**Comment by rijkvanzanten** [comment]
We _might_ be able to "just" hack it in with a `.input > *` selector so it targets whatever's the first child in that input slot 🤔

**Comment by YannickMol** [comment]
At the moment it is only used in `field-select.vue`. Are you saying that if it is used in a custom component, the styling might not be applied as we have no influence on class names?

**Comment by rijkvanzanten** [comment]
> Are you saying that if it is used in a custom component, the styling might not be applied

That's exactly what I'm worried about 🤔 If the padding is purely based on the existence of the `<input>` in it, overriding that input with the slot will remove the padding as well, breaking the consistency of the styling.

That being said.. We could make the decision that the responsibility of that consistency of the styling within the input is based on whatever's is used as the replacement for the default `<input>`, in which case this PR would be sufficient for our purposes

**Comment by YannickMol** [comment]
It would be difficult to target the correct child element of the v-input element. We could go with `.input:first-child`, but there is no guarantee that the `<input>` is the first child element. I'll leave it up to you 🤞

**Comment by rijkvanzanten** [comment]
Yeah.. I think you're right. We also don't necessarily want to force this padding on whatever the first child is.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
