### PR TITLE
Only load defined fields in m2a

### LINKED ISSUE #14434: M2A showing not requested fields
### Describe the Bug

When requesting a specific field within M2A collection, it properly returns that field for that collection but also return all fields for other collections, although they were not asked.

### To Reproduce

Make the following request on the attached SQLite database:
http://localhost:8055/items/article_content?access_token=lwXx2LL7uZp03MwvA4QsmhnqmnWFTm64&fields[]=content.item:articles.content

You should see something like this:
image

Database:
[m2a-issue.sqlite.zip](https://github.com/directus/directus/files/9113743/m2a-issue.sqlite.zip)

### Errors Shown

_No response_

### What version of Directus are you using?

directus/directus:9.14.1

### What version of Node.js are you using?

directus/directus:9.14.1

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker => directus/directus:9.14.1

### PR DESCRIPTION
**Pull request by Nitwel**
This PR changes the fallback for loading m2a items from `['*']` to an empty array as it is not very intuitive to show all fields of other collections when you have specified a fields param for a certain collection.

Fixes #14434, Fixes ENG-227

### CODE REVIEW

**Review by azrikahar — APPROVED** [review]
The M2A collection(s) that is not requested does indeed not show all their fields now, only the ID 👍 so LGTM! (unless the intention was to return `{}` instead of ID, similar to when we don't specify any collection at all, e.g. `fields=m2a.item.name`)

## Test Setup

Example result of `/items/blocks?fields=m2a.item.*`:

```json
{
	"data": [
		{
			"m2a": [
				{
					"item": {
						"id": 1,
						"title": "A1"
					}
				},
				{
					"item": {
						"id": 2,
						"title": "A2"
					}
				},
				{
					"item": {
						"id": 1,
						"name": "B1"
					}
				},
				{
					"item": {
						"id": 2,
						"name": "B2"
					}
				}
			]
		}
	]
}

```

## Result of specifying `item:<m2a_collection_name>`

`/blocks?fields=m2a.item:b.name`

### Before

```json
{
	"data": [
		{
			"m2a": [
				{
					"item": {
						"id": 1,
						"title": "A1"
					}
				},
				{
					"item": {
						"id": 2,
						"title": "A2"
					}
				},
				{
					"item": {
						"name": "B1"
					}
				},
				{
					"item": {
						"name": "B2"
					}
				}
			]
		}
	]
}
```

### After

```json
{
	"data": [
		{
			"m2a": [
				{
					"item": 1
				},
				{
					"item": 2
				},
				{
					"item": {
						"name": "B1"
					}
				},
				{
					"item": {
						"name": "B2"
					}
				}
			]
		}
	]
}

```

**Review by licitdev — APPROVED** [review]
LGTM, added some tests.

Adding on to @azrikahar's comment, the GraphQL response for nested items returns `{}` when it does not have any field selected.

**Comment by paescuj** [comment]
> (unless the intention was to return `{}` instead of ID, similar to when we don't specify any collection at all, e.g. `fields=m2a.item.name`)

Wondering a bit the same... 🤔

**Comment by Nitwel** [comment]
The problem of returning the id instead of an empty object is that currently, a empty objects gets returned in the `parseFields` function only when you specify a field, but that field doesn't exist. If you specify an empty array, the parseFields function will instead add a fallback to the id of the item. For simplicity reasons and possibly breaking something else somewhere I went with that solution now.

**Review by paescuj — APPROVED** [review]

**Comment by paescuj** [comment]
> The problem of returning the id instead of an empty object is that currently, a empty objects gets returned in the `parseFields` function only when you specify a field, but that field doesn't exist. If you specify an empty array, the parseFields function will instead add a fallback to the id of the item. For simplicity reasons and possibly breaking something else somewhere I went with that solution now.

Thanks for the explanation! Makes sense for me 👍 Tested and works perfectly ✅

**Pull request merged**
