### PR TITLE
Remove dots when disabled

### LINKED ISSUE #4038: Remove dots when disabled
dots

### PR DESCRIPTION
**Pull request by YannickMol**
Fixes #4038

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Is this correctly marked as a draft @YannickMol ?

**Comment by YannickMol** [comment]
Yes, it blocks more than the dots only. Looking at a different approach.

**Comment by rijkvanzanten** [comment]
You might wanna handle it in here:

https://github.com/directus/directus/blob/308ae3075c0cc35677985191df994d67cc620202/app/src/modules/collections/routes/item.vue#L133-L141

or potentially in here:

https://github.com/directus/directus/blob/main/app/src/views/private/components/save-options/save-options.vue

🙂

**Comment by YannickMol** [comment]
Closing as need to review further.

**Pull request closed without merging**
