### PR TITLE
reload npm extensions when watch is enabled

### LINKED ISSUE #22948: Reloading extensions in workspaces
### Describe the Bug

I found a similar issue and discussion:
#14922
#14939

In my case, I am working in a workspace with pnpm.
Until now, what I did was install my extensions as dependencies, e.g.:
```json
"dependencies": {
  "directus": "^10.11.2",
  "@enovam/ge-extensions": "workspace:"
 }
```

The load extensions works correctly, but the changes are not updated.

Pulling the thread, then I saw that only the local extensions are added to the watch:

```ts
if (this.options.watch && !wasWatcherInitialized) {
  this.updateWatchedExtensions(Array.from(this.localExtensions.values()));
}
```

Once this was confirmed, what I did was remove the extension as a dependency and "installed" it with a symbolic link within the directus extensions folder.

In this way I was already detecting the changes.

My question is: Should the installed extensions method also work within the workspace?

### Directus Version

v10.11.2

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by bernatvadell**
## Scope

What's changed:

The watch for custom extensions has been modified to include those that have been installed in the package.json (moduleExtensions).

## Potential Risks / Drawbacks

You can increase the number of files to watch. Although this only affects development, when the "watch" option (EXTENSIONS_AUTO_RELOAD) is activated.

## Review Notes / Questions

I considered that it was not necessary to include the registry extensions. I currently can't think of any use cases that involve hot reloading these types of extensions.

---

Fixes #22948

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]
Code changes LGTM but I'll hold for @nickrum seeing he has the most experience in this topic 🙂

**Review by nickrum — CHANGES_REQUESTED** [review]
I think we should also add the `package.json` of newly added extensions to the list of watched files.

**Comment by bernatvadell** [comment]
Hi @nickrum can you review the latest changes? ty!

**Comment by bernatvadell** [comment]
@nickrum @rijkvanzanten follow up?

**Review by rijkvanzanten — APPROVED** [review]
LGTM! Thanks 🙂

**Pull request merged**
