### PR TITLE
Remove cache flushing on startup

### LINKED ISSUE #18245: Cache is flushed on every app start
### Describe the Bug

In a scaling environment where containers are added and started as load increases the cache is cleared on every container start. This has some serious side affects such as all containers having to request the schema from the database again, which is a heavy load especially running every time a new container starts. 

eg. 66 containers request schema, 2s later container 67th is started clearing the cache so now 67 containers all request schema again.

Solution:

Initial solution is to remove `await flushCaches();` [here](https://github.com/directus/directus/blob/84cb5028c76e320345fc8f7ce7d678dc2656974e/api/src/app.ts#L94) 
and optionally move it after migrations take place.

### To Reproduce

Deploy on any container service and do some load tests. Notice that as new containers are added there is an increase in database requests.

### Directus Version

9.24.0

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by rijkvanzanten**
This was added way back when to make sure that projects that upgrade don't run into bugs due to changes in the structure of the cache. However, this comes with the (huge) side-effect that all caches are flushed whenever a horizontal scaling event happens (eg when the project is scaling up, the caches are flushed, putting needless strain on the database while all containers try to regenerate the schema cache simultaneously).

Fixes #18245

### CODE REVIEW

**Review by jaads — APPROVED** [review]

**Review by paescuj — CHANGES_REQUESTED** [review]
Should we instead flush the caches in [api/src/database/migrations/run.ts](https://github.com/directus/directus/blob/main/api/src/database/migrations/run.ts) in case a migration has actually been performed? Theoretically a migration can lead to any changes in the database.

**Comment by licitdev** [comment]
> Should we instead flush the caches in [api/src/database/migrations/run.ts](https://github.com/directus/directus/blob/main/api/src/database/migrations/run.ts) in case a migration has actually been performed? Theoretically a migration can lead to any changes in the database.

Yes we should. 👍 However, when a new migration is added or when the schema is changed, the same issue occurs.

I wonder if we should add a `MAX_CONCURRENT_SCHEMA_FETCH` using the messenger Redis connection where a `schema_fetch_count` key increments before the fetching takes place. 🤔

**Comment by paescuj** [comment]
> Yes we should. 👍 However, when a new migration is added or when the schema is changed, the same issue occurs.
> 
> I wonder if we should add a `MAX_CONCURRENT_SCHEMA_FETCH` using the messenger Redis connection where a `schema_fetch_count` key increments before the fetching takes place. 🤔

Right, this sounds like a good plan 👍

**Comment by rijkvanzanten** [comment]
> Should we instead flush the caches in api/src/database/migrations/run.ts in case a migration has actually been performed? 

I don't think that'll solve it either. On migrate, you'll still have active containers on the old version, while the new one is upgrading. I think the only real fix is to make sure we add the current api version as part of the redis key

**Comment by paescuj** [comment]
> > Should we instead flush the caches in api/src/database/migrations/run.ts in case a migration has actually been performed?
> 
> I don't think that'll solve it either. On migrate, you'll still have active containers on the old version, while the new one is upgrading. I think the only real fix is to make sure we add the current api version as part of the redis key

Wouldn't the other instances get notified by the messenger about the schema change? Together with @licitdev's idea of locking the schema fetch I think that should work 🤔

**Comment by paescuj** [comment]
For now I think we could simply move the `flushCaches` call to the migrations (of course only execute it if migrations are performed) and track the ideas discussed above in a separate issue. This way we could already solve the issue when it comes to scaling without upgrading instances.

**Comment by rijkvanzanten** [comment]
> For now I think we could simply move the flushCaches call to the migrations (of course only execute it if migrations are actually performed)

@paescuj I don't think that'll work. Lets say you have 4 instances on v1. When updating, you'd move one instance to v2, wait for it to be done, and then move 2/4 to v2, 3/4 to v2, 4/4 to v2. When the first v2 comes online, migrations run and caches are flushed, however, because those other 3/4 are still on v1, the caches are recreated as fast as they're flushed. If there's a breaking change in that migration, it'll start crashing on both sides

**Review by paescuj — APPROVED** [review]
LGTM!

**Review by licitdev — APPROVED** [review]

**Pull request merged**
