### PR TITLE
Don't cache root index.html

### LINKED ISSUE #9627: Don't cache root index.html
We should prevent browsers/cdns from caching the main admin app index.html file. On new deployments, the references to the static files will change to invalidate the cache, but if the main index.html file is cached, the new version won't be opened in the browser on those deploys.

We should be able to do this by forcing the `Cache-Control` header to `no-cache` in here:

https://github.com/directus/directus/blob/67b51b7d44f3cca9bad3be4e90b6db8a8205c4f6/api/src/app.ts#L139-L143

### PR DESCRIPTION
**Pull request by azrikahar**
resolves #9627

### CODE REVIEW

**Comment by joselcvarela** [comment]
Hey @azrikahar 
I am thinking if `no-cache` will be enough.
There's this package: https://www.npmjs.com/package/nocache which sets a few other headers.
I think it will not harm if we have those additional headers, what do you think?

**Review by rijkvanzanten — APPROVED** [review]

**Comment by azrikahar** [comment]
Actually I did look into it, but you're right I should've at least put it up for discussion haha. From what I understand:

- `Pragma: no-cache` this should be no harm, and provides backward compatibility.
- `Expires: 0` not sure will this be useful, but also "no harm" category.
- `Surrogate-Control: no-store` I believe this can be somewhat related to above expires 0, but also not super sure do we need it.

**Comment by joselcvarela** [comment]
Well it is already merged so let's move on 😅

**Comment by rijkvanzanten** [comment]
Cache-Control is all we need 🙂 It's the same as `max-age=0, must-revalidate` where the `must-revalidate` is the important bit. That requires proxy caches to revalidate the content before serving it to the client, ensuring you're always seeing the latest version

**Pull request merged**
