### PR TITLE
Fix  http range request when transformation in use

### LINKED ISSUE #20055: Issue with Range Request HTTP 206 when using azure storage
### Describe the Bug

In the context of CDN Caching failure (Azure Front Door), we tested directus against range requests on assets:

Bypassing any proxy and CDN, here are the results:

Using `local` storage: works OK
```
curl -v -o nul --range "0-80000000" localhost:8055/assets/4ab8988c-fe10-4dea-b1df-2871043c2421
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:8055...
* Connected to localhost (127.0.0.1) port 8055 (#0)
> GET /assets/4ab8988c-fe10-4dea-b1df-2871043c2421 HTTP/1.1
> Host: localhost:8055
> Range: bytes=0-80000000
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< Content-Security-Policy: default-src none;style-src 'unsafe-inline'
< X-Powered-By: Directus
< Content-Type: image/jpeg
< Content-Disposition: inline; filename="my-file-on-local-storage.jpg"
< Accept-Ranges: bytes
< Cache-Control: public, max-age=2592000
< Vary: Origin, Cache-Control
< Last-Modified: Tue, 17 Oct 2023 15:17:10 GMT
< Content-Range: bytes 0-112518/112519
< Content-Length: 112519
< Date: Tue, 17 Oct 2023 16:47:18 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{ [32244 bytes data]
100  109k  100  109k    0     0   532k      0 --:--:-- --:--:-- --:--:--  546k
* Connection #0 to host localhost left intact
* 
```

Using `azure` storage: KO
```
▶ curl -v -o nul --range "0-80000000" localhost:8055/assets/38e68a3f-79d4-441e-b059-1d17cc3bf457.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:8055...
* Connected to localhost (127.0.0.1) port 8055 (#0)
> GET /assets/38e68a3f-79d4-441e-b059-1d17cc3bf457.jpg HTTP/1.1
> Host: localhost:8055
> Range: bytes=0-80000000
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< Content-Security-Policy: default-src none;style-src 'unsafe-inline'
< X-Powered-By: Directus
< Content-Type: image/jpeg
< Content-Disposition: inline; filename="my-file-on-azure-storage.jpg"
< Accept-Ranges: bytes
< Cache-Control: public, max-age=2592000
< Vary: Origin, Cache-Control
< Last-Modified: Mon, 16 Oct 2023 15:38:57 GMT
< Content-Range: bytes 0-93268/93269
< Content-Length: 93269
< Date: Tue, 17 Oct 2023 17:15:21 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{ [32247 bytes data]
100 93269  100 93268    0     0  14965      0  0:00:06  0:00:06 --:--:--     0* transfer closed with 1 bytes remaining to read
100 93269  100 93268    0     0  14964      0  0:00:06  0:00:06 --:--:--     0
* Closing connection 0
curl: (18) transfer closed with 1 bytes remaining to read
```

Notice the 

```
curl: (18) transfer closed with 1 bytes remaining to read
```

Same range request directly on azure blob: OK

```
▶ curl -v -o test_blob.jpg --range "0-80000000" https://myblob.blob.core.windows.net/directus-common/uploads/38e68a3f-79d4-441e-b059-1d17cc3bf457.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.239.141.196:443...
* Connected to myblob.blob.core.windows.net (52.239.141.196) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [347 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [81 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4923 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [365 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [102 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=*.blob.core.windows.net
*  start date: Sep 28 06:12:25 2023 GMT
*  expire date: Sep 28 06:12:25 2024 GMT
*  subjectAltName: host "myblob.blob.core.windows.net" matched cert's "*.blob.core.windows.net"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft RSA TLS CA 01
*  SSL certificate verify ok.
* using HTTP/1.x
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> GET /directus-common/uploads/38e68a3f-79d4-441e-b059-1d17cc3bf457.jpg HTTP/1.1
> Host: myblob.blob.core.windows.net
> Range: bytes=0-80000000
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< Content-Length: 93269
< Content-Type: image/jpeg
< Content-Range: bytes 0-93268/93269
< Last-Modified: Mon, 16 Oct 2023 15:38:57 GMT
< ETag: 0x8DBCE5E031CD8B7
< Vary: Origin
< Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: f5f40ba1-d01e-007e-291d-01463a000000
< x-ms-version: 2009-09-19
< x-ms-lease-status: unlocked
< x-ms-blob-type: BlockBlob
< Date: Tue, 17 Oct 2023 17:16:37 GMT
<
{ [15954 bytes data]
100 93269  100 93269    0     0   485k      0 --:--:-- --:--:-- --:--:--  497k
* Connection #0 to host myblob.blob.core.windows.net left intact
```

Consequence in real life:
CDN caching will fail using `azure` storage since the CDN will do HTTP `range` requests.

Source:
https://learn.microsoft.com/en-us/answers/questions/1366420/err-http2-protocol-error-when-using-azure-frontdoo
https://learn.microsoft.com/en-us/answers/questions/1338000/http2-protocol-error-with-azure-cdn

### To Reproduce

Use `azure` Storage
Upload an asset there
Make a range request to this asset through Directus and directly to blob (`curl --range`).
Diagnose HTTP 206 response and client behavior.

Use `local` storage
Upload an asset there
Make a range request to this asset through Directus (`curl --range`).
Diagnose HTTP 206 response and client behavior.

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

### LINKED ISSUE #20059: Issue with HTTP Range Requests and Transformation
### Describe the Bug

In the context of CDN Caching failure (Azure Front Door), we tested directus against range requests on assets:

Bypassing any proxy and CDN, here are the results:

Using Transformation: KO. `Content-Range` and `Content-Length` are inconsistent with actual size of the transformed asset.

```
curl -v localhost:8055/assets/38e68a3f-79d4-441e-b059-1d17cc3bf457\?format\=webp\&quality\=92 -o test.jpg --range "0-80000000"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:8055...
* Connected to localhost (127.0.0.1) port 8055 (#0)
> GET /assets/38e68a3f-79d4-441e-b059-1d17cc3bf457?format=webp&quality=92 HTTP/1.1
> Host: localhost:8055
> Range: bytes=0-80000000
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< Content-Security-Policy: default-src none;style-src 'unsafe-inline'
< X-Powered-By: Directus
< Content-Type: image/webp
< Content-Disposition: inline; filename="my-file.jpg"
< Accept-Ranges: bytes
< Cache-Control: public, max-age=2592000
< Vary: Origin, Cache-Control
< Last-Modified: Mon, 16 Oct 2023 15:38:57 GMT
< Content-Range: bytes 0-93268/70928
< Content-Length: 93269
< Date: Tue, 17 Oct 2023 22:01:24 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{ [32143 bytes data]
 76 93269   76 70928    0     0  11409      0  0:00:08  0:00:06  0:00:02     0* transfer closed with 22341 bytes remaining to read
 76 93269   76 70928    0     0  11409      0  0:00:08  0:00:06  0:00:02     0
* Closing connection 0
curl: (18) transfer closed with 22341 bytes remaining to read
```

Notice the 

```
curl: (18) transfer closed with 22341 bytes remaining to read
```

and inconsistency in Headers:

```
< Content-Range: bytes 0-93268/70928
< Content-Length: 93269
```

Consequence in real life:
CDN caching and delivering (when cache enabled) may fail when using Transformation since the CDN will do HTTP `range` requests.

Source:
https://learn.microsoft.com/en-us/answers/questions/1366420/err-http2-protocol-error-when-using-azure-frontdoo
https://learn.microsoft.com/en-us/answers/questions/1338000/http2-protocol-error-with-azure-cdn

>Cause:
>
>Problem is not with CDN but rather with the customer origin. **_If CDN sends a range request to the origin and the origin compresses the response (e.g., with gzip), the origin returns an incorrect Content-Range header_**.
>
>Resolution:
>
>**_The customer must fix their origin to send a correct Content-Range header._**
>
>The customer can do one of the following as a work-around:
>
>Disable caching in their CDN profile. This will cause CDN to not send range requests to the origin.
>**_Change the origin to ignore range requests (treating them as regular non-range requests and returning 200s instead of 206s)_**.
>Disable compression at the origin.

Suggestion:
Ignore range and respond as HTTP/200 instead of HTTP/206 when TransformationParams are set.

The idea is to use directus to render compressed assets, while caching the transformed results in CDN to save directus ressources, so compression is welcome on directus (Origin) and caching is desired (thus disabling it as a workaround does not apply).

### To Reproduce

Upload an asset and try a HTTP Range Request (`curl --range`) while giving query string for transformations (e.g. `?format=webp&quality=92`).
Inspect Content-Range and Content-Length headers of HTTP/206 response.

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by mscbpi**
## Scope

What's changed:

Only consider HTTP Range Requests when no Transformation parameters are set.
In current situation HTTP/206 Content-Length and Content-Range Headers are wrong when using tranformation.
See #20059 for details.

The patch returns HTTP/200 as soon as TransformParams are set and ignore range / Partial Content delivery, 

no transformation still produces the HTTP/206 response:
```
[01:02:41] GET /assets/38e68a3f-79d4-441e-b059-1d17cc3bf457?format=webp&quality=98 200 401ms
[01:02:48] GET /assets/38e68a3f-79d4-441e-b059-1d17cc3bf457?format=webp&quality=95 200 52ms
[01:04:40] GET /assets/38e68a3f-79d4-441e-b059-1d17cc3bf457 206 59ms
[01:04:56] GET /assets/38e68a3f-79d4-441e-b059-1d17cc3bf457?format=webp 200 88ms
```

Alternative would be to set headers to correct values after transformation.

## Potential Risks / Drawbacks

To be evaluated

## Review Notes / Questions

https://learn.microsoft.com/en-us/answers/questions/1338000/http2-protocol-error-with-azure-cdn
https://learn.microsoft.com/en-us/azure/frontdoor/front-door-caching?pivots=front-door-standard-premium#delivery-of-large-files

> Return a ranged response. The response must use HTTP status code 206. Also, the Content-Range response header must be present, and must match the actual length of the content that your origin returns. If your origin doesn't send the correct response headers with valid values, Azure Front Door doesn't cache the response, and you might see inconsistent behavior.
> 
>  Tip
> 
> **If your origin compresses the response, ensure that the Content-Range header value matches the actual length of the compressed response.**

Directus does not adapt Content-Range and Content-Length accordingly.
```
< Content-Range: bytes 0-93268/70928
< Content-Length: 93269
```
---

Fixes #20059

### CODE REVIEW

**Comment by mscbpi** [comment]
I have tried to think of a way to set the correct headers after transformation to keep partial content / 206 being honored when transformations are in use.

File size may decrease or increase (jpg => webp, quality=100 might increase), 

- if range.end was set to lastByte from the beginning, set the Content-Range and Content-Length to whatever length you get after transform -to avoid waiting for "missing" bytes of a smaller rendered file, or to avoid download  only a part of newly generated bigger file while we were expecting the entire one.
- if range.end was set to something smaller than lastByte -it was expected just to get a chunk-, compare the actual value, and if initial range.end is greater than actual size after transformation,  set the Content-Range and Content-Length to whatever length you get after transform to avoid waiting for "missing" bytes you were expected. If it is smaller, in that case we should only get the chunk where request.end was initially set, still adapting the Content-Range with actual values.

IMHO way too cumbersome and I many not have reviewed every case. Range requests have to be considered as normal request, ignoring range header, responded with HTTP/200 and not 206 when transformation is implied, and be downloaded all at once.

**Comment by mscbpi** [comment]
@paescuj from my understanding, what is common is that compression on app side makes HTTP Range Request wobbly:

CDNs asks for "range" request to cache and deliver big assets per chunk (8MB in the case of azure front door), expecting HTTP/206 as an answer with `Content-Range` header set to the actual bytes that are sent per chunk. 

Even if there is only one chunk, if file < 8MB, it has to be the right value matching actual size.

Having compression on app side (directus in our case) changes the actual content length and `Content-Range` should match. 

It looks common that compression on app side triggers this issue with `HTTP Range Request` because apps or even frameworks do not align `Content-Range` headers with actual side after compression, making de-facto compression on app side incompatible with `http range` request.

As illustrated in #20059 it is unfortunately the case with Directus, since `Content-Range` headers are wrongly set when transformation occurs and we ask for HTTP/206 Partial Content (Range Request).

These are cases that illustrates the same situations it in the context of Azure Front Door, other CDNs works the same way AFAIK:
https://learn.microsoft.com/en-us/answers/questions/1366420/err-http2-protocol-error-when-using-azure-frontdoo
https://learn.microsoft.com/en-us/answers/questions/1338000/http2-protocol-error-with-azure-cdn
https://techcommunity.microsoft.com/t5/fasttrack-for-azure/how-to-test-azure-front-door-origins-for-valid-http-range/ba-p/3745208

The official documentation there is a highlight on this issue which looks very common indeed:

https://learn.microsoft.com/en-us/azure/frontdoor/front-door-caching?pivots=front-door-standard-premium#request-methods

As a solution:
- find a way to always send the correct headers, along with correct chunks based on actual data size after transformation. It looks tricky, I am happy to discuss it if there is a way. There are a lot of cases when result is smaller or bigger than initial size after transformation, them comparing to initial range asked by client (that is overriden at the very beginning of the procedure with initial file data), etc. etc. 

As workarounds, it is told in the several documentation:
- Disable caching, thus the CDN will not try Range Request and no problem anymore (we lose most of CDN advantages)
- Disable compression on app side so `Content-Range` header matches the actual size, and use CDN compression instead (that's a pity because on-the-fly transformation is a must in Directus, and combined with CDN caching the result  is ideal)
And the third, selected workaround in this PR:
 - Ignore `Range: ` header if not handled correctly and responds with HTTP/200 and the complete file rather than HTTP/206 Partial Content with wrong information about size/range.

Directus is very good at handling `Range: ` header when transformation is not in place, and it is very useful to be able to stream chunks of video files with HTTP/206 Partial Content. This feature is kept.

My fix ignores header `Range: ` **only when we have transformation parameters set in the query string**, that will triggers transformation, change of actual size, and wrong  Content-Range headers in case of HTTP/206 response.

Ignoring the header just makes directus answer an HTTP/200 with the whole file, and CDNs will be happy with it.
The side-effect is that if transformation occurs on huge files, which is not something you want in any case (CPU/RAM on files that are > 10MB to apply transformation ?), you lose the benefits of "streaming" it per chunk. But anyway, it does not work right now because the generated headers are wrong, so you lose nothing.

**Comment by mscbpi** [comment]
Just as an illustration of the trickyness of setting Headers correctly

Say you ask for 0-8000000 range an asset that is 6MB before transformation. Code will set range.end to LastByte of the initial file because it is smaller than file size.

Now transforms occurs, and it appears this transformation makes the file bigger. It is now 10MB.

Not only range.end is wrong, but you'll have to rethink the whole process with the newer asset, since 10MB > 8MB and you should rethink completely the process of delivering, since now it has to be 2 chunks.

If transformation would result in smaller files for sure, which is not the case, it could be handled easily. Just take the min of `range.end` and `stat.file`. I had a fix for this, until I saw it did not work with `?format=webp&quality=100` which are making my jpg bigger.

**Comment by mscbpi** [comment]
One more interesting resource. Compression on node.js/express results in the same conclusion https://github.com/DanielLarsenNZ/nodejs-express-range-headers#advice--recommendations

> Accepting range requests is optional. Origin servers should be configured to either accept range requests (and respond correctly) or ignore range request headers and respond with a full (200 Ok) response.

> [Nodejs/express](https://github.com/DanielLarsenNZ/nodejs-express-range-headers#nodejsexpress)
> It looks like compression and range requests are incompatible in the nodejs/express/compression module. 
> ...
> The solution for Nodejs/express servers is to either support range requests, or compression (not both at the same time).

**Comment by paescuj** [comment]
Thank you so much for the detailed research! ❤️ 
That makes a lot of sense & I agree that a full response (200) seems the most appropriate solution for cases when transformation is requested 👍

**Review by paescuj — APPROVED** [review]

**Comment by mscbpi** [comment]
Thank you @paescuj for considering my solutions, your feedback and merging the code ! 🙏

**Pull request merged**
