### PR TITLE
Fix format of stored field conditions value

### LINKED ISSUE #19757: Conditions in v10.6.2
### Describe the Bug

After upgrading to v10.6.2 from 10.6.1 all conditions on fields no longer show in the UI and any new ones don't function.

### To Reproduce

Upgrade to v10.6.2 and create a new condition that hides a field. the rule will not apply when triggered.

Also go to a field that does have a condition and edit it. Under conditions, none will be shown.

Downgrade to 10.6.1 and all existing conditions show again but any created under version 10.6.2 now show with this error:
image

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by paescuj**
Fixes #19757

Regression introduced with #19639:

`v-form` requires the conditions value to be passed in form of `{ conditions }`.
But instead of retrieving it that way in the getter, it was incorrectly stored in this form. 
The form of the stored value shouldn't be changed as otherwise the conditions have no effect.

## Review Guide

1. Verify the interface in the "Conditions" tab of Field configuration works as expected, i.e. values can be saved and displayed again
2. Verify the conditions take effect when editing a corresponding item

### CODE REVIEW

**Review by DanielBiegler — COMMENTED** [review]
**Maybe my findings are out of scope for this PR but wanted to still share for a future issue maybe:**

My fields had conditions before this PR, so this happened for me on first opening:

image

But after you open the new dialog and close it, it disappears. (reappears when closing+reopening the side drawer)

and it also bugs out the first time you add a new condition but subsequent conditions work it's a lil' finicky, see the following video :smile: 

[Screencast from 25.09.2023 18:09:04.webm](https://github.com/directus/directus/assets/14810858/ee7b2978-0687-4dcd-b20b-e6b5a938007c)

**Comment by paescuj** [comment]
> **Maybe my findings are out of scope for this PR but wanted to still share for a future issue maybe:**
> 
> My fields had conditions before this PR, so this happened for me on first opening:
> 
> image
> 
> But after you open the new dialog and close it, it disappears. (reappears when closing+reopening the side drawer)
> 
> and it also bugs out the first time you add a new condition but subsequent conditions work it's a lil' finicky, see the following video 😄
> Screencast.from.25.09.2023.18.09.04.webm

Yeah, this is to be expected, unfortunately, if you added conditions under v10.6.2. You could manually "fix" the format in such a case via "Raw Editor".

**Review by br41nslug — APPROVED** [review]
I can confirm this fixes basic conditions

https://github.com/directus/directus/assets/9389634/ddf60485-e75f-4cfb-b4b2-efe28725337f

We will need to mention somewhere, i suppose in the release notes, that any conditions created or edited since the 10.6.2 release last week will need to be adjusted/fixed/recreated.

I was thinking if we could catch/fix these incorrectly saved conditions with a migration or similar but i suspect that would cause more issues than it'd solve.

**Review by DanielBiegler — APPROVED** [review]
Tested multiple scenarios and all the basic ones and nested fields inside groups worked for me also. Sadly the expansion of groups still doesnt work see #19571 but thats a different issue - Awesome fix nice one! :heart:

**Comment by paescuj** [comment]
> We will need to mention somewhere, i suppose in the release notes, that any conditions created or edited since the 10.6.2 release last week will need to be adjusted/fixed/recreated.
> 
> I was thinking if we could catch/fix these incorrectly saved conditions with a migration or similar but i suspect that would cause more issues than it'd solve.

Exactly, I would rather avoid that in favor of a simple note in the release notes.

**Comment by br41nslug** [comment]
> Exactly, I would rather avoid that in favor of a simple note in the release notes.

A note on the breaking changes page in the docs then perhaps?

**Pull request merged**
