### PR TITLE
Switch to new faker

### PR DESCRIPTION
**Pull request by Shinigami92**
Related to https://github.com/faker-js/faker/issues/542

### CODE REVIEW

**Comment by Shinigami92** [comment]
Please run the CI tests so we can see if everything works
I will come back and update to released version when it's out

**Comment by rijkvanzanten** [comment]
@Shinigami92 Is `beta.0` considered a gm release?

**Comment by Shinigami92** [comment]
> @Shinigami92 Is `beta.0` considered a gm release? Are there going to be any other expected breaking changes?

I assume yes, it is a gm release.
We do not expect any other "breaking changes" right now.
We would like to bring such modularization as your repo used back in v7,8,9 or later, but no promises yet.

**Comment by Shinigami92** [comment]
Oh and just FYI: I used `/locale/en` so it just loads faster / only uses the en locales.
Otherwise we could use `import { faker } from '@faker-js/faker'`
But this would load all current 56 availabled languages

**Comment by rijkvanzanten** [comment]
Good one @Shinigami92 👍🏻 

Also (not to negate the great work y'all are doing over there), we might not even need faker for these very limited uses in these two tests. @jaycammarano could you confirm/deny the reliance on faker in those test factories? Not relying on the dependency is even easier than keeping it up to date 🙂

**Comment by jaycammarano** [comment]
We definitely don't. We could just use static data.

**Comment by Shinigami92** [comment]
@rijkvanzanten yeah, I understand this decision.
Sad to hear that we "loose" a very big dependent customer, but 🤷 😅 

But could you run the CI anyway once, so we can confirm that we didn't break anything else (so we know for other customers)

**Comment by rijkvanzanten** [comment]
Superseded by https://github.com/directus/directus/pull/12934

**Pull request closed without merging**
