### PR TITLE
mssql - flattened IN clause to avoid double parenthesis. 

### PR DESCRIPTION
**Pull request by martijnboland**
This PR was taken from PR #3498 but disconnected from the original (large) PR.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
What was the problem with the original implementation here? Was `value` an array of arrays instead of an array of strings??

**Comment by martijnboland** [comment]
Yes, from the history, it looked like value was an array of arrays. 

However: this does not seem to happen anymore! Has something changed in this area *very* recently?

**Comment by rijkvanzanten** [comment]
Last change of that bit seems to be 3 months ago: https://github.com/directus/directus/commit/7891920209e34e8dad62d83c58cbc5d9918d78fd, is that recently enough to count? 😁

**Comment by martijnboland** [comment]
Kind of figured it out. PR #4140 has a nice side effect that it fixes the double parenthesis as well! Originally, a call to the /me endpoint resulted in 'role' appearing twice in the select list. This translated to a nested array with the same id's for the select ... in() query. After applying PR #4140 the nested array has disappeared. 

I think we can close this PR.

**Comment by rijkvanzanten** [comment]
Ahhh that makes sense! Good catch

**Pull request closed without merging**
