### PR TITLE
Add more options to extension.config.js

### LINKED ISSUE #22402: Add option to not clear screen when building extensions
### Describe the Improvement

It would be nice when building extensions in a docker environment for the CLI not to clear the screen on every change. Maybe just an option in the command like `directus-extension build --no-clear`.

As for as I can see, the relevant sections would be:
https://github.com/directus/directus/blob/main/packages/extensions-sdk/src/cli/run.ts#L27
https://github.com/directus/directus/blob/main/packages/extensions-sdk/src/cli/commands/build.ts#L490

Just not sure how you would like to pass the option down into the watchExtension function.

### LINKED ISSUE #22939: Allow more options for rollup config when building extensions
### Describe the Improvement

It would be nice to have a bit more control over how rollup builds and bundles extensions. Currently we can specify a plugins array, but there is a lot of other functionality that rollup offers that could be helpful to be able to add to the extensions.config.js file

### PR DESCRIPTION
**Pull request by GuyShane**
## Scope

What's changed:

- It is now possible to specify `onwarn` and `watch.clearScreen` options in extension.config.js
- It will also be easier to add more Rollup config options to the extension config file, since this change allows us to pass the user config object when making Rollup config

## Potential Risks / Drawbacks

- With more options potentially comes more maintenance. But this should be minimal since the defaults stay the same and we will just be passing options through to Rollup

## Review Notes / Questions

- I specifically added the options I did because they are relevant to my use cases, but I hope this PR serves as a base to add further options should other users want them

---

Fixes #22939 
Fixes #22402

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Instead of unlocking more options one by one, I'm wondering if we could "just" expose the whole config option and let the user inject whatever rollup options. That would solve for all future expansions here as well. @nickrum thoughts?

**Comment by nickrum** [comment]
I'm a little torn on this one. While it would definitely be simpler to just let the user inject whatever rollup options, there are quite a few options that have to be set in a certain way for extensions built by the Extensions SDK to work when loaded by Directus. I feel like as a user I would expect the SDK to either build extensions that Directus can load or show an error message, even if I messed with some option.

**Comment by rijkvanzanten** [comment]
@nickrum So you'd prefer to add individual options when the need arises? In that case this PR should be ready for review 🙂

**Review by nickrum — COMMENTED** [review]
Making the clearing of the screen in watch mode configurable makes a lot of sense to me 👍

Silencing warnings on circular dependencies was specifically done because our own `@directus/extensions-sdk` was throwing them a lot, which wasn't very meaningful and only confused users. Were you having issues with this? Maybe we can find a solution without having to add a dedicated option to the config file.

**Comment by GuyShane** [comment]
I was having issues with adding Sentry to an extension built as a module, and it would throw a bunch of `'this' keyword is equivalent to 'undefined'` warnings. I wanted to add something like this to onwarn:
```js
if (warning.code === 'THIS_IS_UNDEFINED') {
	return;
}
```

But I've since removed Sentry from the extension so it's not as big an issue for me now. I can remove it from this pull request if we're not sure we want to include the option yet.

Not clearing the screen in dev would still be nice though.

**Comment by rijkvanzanten** [comment]
I'll close this for now as per the discussions above. Lets keep discussing a final solution on the individual issues 🙂 Happy to take a new PR with just the screen clearing setting

**Pull request closed without merging**
