### PR TITLE
Enable global-agent package which allows user to use GLOBAL_AGNET_HTTP_PROXY

### PR DESCRIPTION
**Pull request by younky-yang**
Enable global-agent package which allows user to setup GLOBAL_AGENT_PROXY variables, that solves the problems that app needs to connect to outside the network

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
I don't know how I feel about adding in a package that overrides some internal Node http handling without knowing exactly what we're trying to achieve, knowing what parts it'll touch, and knowing what else it might affect..

Seeing that the problem was simply an outgoing http call, we should just update the `axios` instance that we use for making that call instead, and expose axios' proxy settings through environment variables defined in Directus itself, instead of injected by a third party

**Comment by rijkvanzanten** [comment]
As for global agent itself, it seems like it supports injecting through Node's `-r` flag as well, so there shouldn't be anything stopping you from running Directus with it as is, using `node -r 'global-agent/bootstrap' node_modules/directus/dist/start.js`

**Comment by younky-yang** [comment]
> I don't know how I feel about adding in a package that overrides some internal Node http handling without knowing exactly what we're trying to achieve, knowing what parts it'll touch, and knowing what else it might affect..
> 
> Seeing that the problem was simply an outgoing http call, we should just update the `axios` instance that we use for making that call instead, and expose axios' proxy settings through environment variables defined in Directus itself, instead of injected by a third party

I do think we may export an environment variable for proxy makes sense, but the challenge here is there are different dependencies of directus rely on the network packages, for example, the issue I encountered is about SSO, it uses grant which depends on request compose, so not axios for the network request, and for request compose used in grant, I didn't see a place can have the proxy take effect until we inject it through global agent. 

I will try node -r option for this, but at some scenario, and see if this option fit with our enterprise customized base image.

**Comment by joselcvarela** [comment]
You should be good to go with the `node -r` option.
Since 'global-agent' alters the definitions of 'http' and 'https', every request made on Nodejs will pass through 'global-agent', independently if is axios, request-compose, etc. because Node only have those two interfaces to make network requests.

About including 'global-agent', we really appreciate your contribution, but in my opinion we shouldn't do it, because it has no benefits (since you can use -r option) and it is one more package we need to maintain (when there's an update we need to check if breaks something on our side). Plus, 'global-agent' "catches" all the requests made to the network, including emails, passwords, etc. which makes me thinking if this should be considered a security vulnerability.

**Comment by rijkvanzanten** [comment]
@joselcvarela thanks for clarifying some more, you expressed my concerns perfectly:

> Since 'global-agent' alters the definitions of 'http' and 'https', every request made on Nodejs will pass through 'global-agent', independently if is axios, request-compose, etc. because Node only have those two interfaces to make network requests.

> Plus, 'global-agent' "catches" all the requests made to the network, including emails, passwords, etc. which makes me thinking if this should be considered a security vulnerability.

I simply don't know what else this affects that we don't know about. Seeing that you should be able to already use this setup by starting Directus with this package included through Node directly, I don't think it's something we need to include out of the box at this point.

Thank you for your understanding, and happy to keep the discussion going on how we can implement this in a more transparent way

**Comment by NilsBaumgartner1994** [comment]
Encountering the same problem with an directus instance behind a proxy wall, where I need to configure directus.
I partially solved this by injecting: 
`export http_proxy=.....`
before starting directus instance. But for SSO logins, this problem still exists...

Anyone who figured it out?

**Comment by NilsBaumgartner1994** [comment]
Ok got it.

Explanation:
- We need to set the proxy in order to install global agent, after that we configure global-agent, after that we start directus with global-agent

```
In docker-compose.yaml:
    command: >
      sh -c "
        export HTTPS_PROXY=<YOUR_PROXY> && 
        export HTTP_PROXY=<YOUR_PROXY> && 
        npm i global-agent &&
        export GLOBAL_AGENT_HTTP_PROXY=<YOUR_PROXY> && 
        npx directus bootstrap && 
        node -r 'global-agent/bootstrap' node_modules/directus/dist/start.js
```

**Pull request closed without merging**
