### PR TITLE
Patch Tuesday 🐸

### PR DESCRIPTION
**Pull request by rijkvanzanten**
npm is amazing, but keeping libraries up to date is a nightmare. Bots just spam the repo, so we're trying something new: Patch Tuesday (on wednesdays in the middle of each month).

# Updates

## `monorepo-root`

<details><summary>Patch / minor updates</summary>

```
@types/lodash                     ^4.14.182  →   4.14.186
@typescript-eslint/eslint-plugin    ^5.30.5  →     5.40.1
@typescript-eslint/parser           ^5.30.5  →     5.40.1
eslint                              ^8.19.0  →     8.25.0
eslint-plugin-vue                    ^9.2.0  →      9.6.0
globby                              ^11.0.4  →     11.1.0
prettier                              2.4.1  →      2.7.1
simple-git-hooks                     ^2.8.0  →      2.8.1
supertest                            ^6.2.3  →      6.3.0
typescript                           ^4.7.4  →      4.8.4
```

</details>

- `@types/jest                          27.5.2  →     29.2.0`
- `axios                               ^0.27.2  →      1.1.3`
- `jest                                 28.1.2  →     29.2.1`
- `jest-environment-node               ^28.1.2  →     29.2.1`
- `ts-jest                              28.0.5  →     29.0.3`
- `uuid                                 ^8.3.2  →      9.0.0`

### :x: Can't be updated at this time

- `globby                        ^11.0.4  →  13.1.2`
  ESM only, requires v10 branch

---

## `directus`

<details><summary>Patch / minor updates</summary>

```
@aws-sdk/client-ses               ^3.107.0  →   3.190.0
@directus/extensions-sdk           ^9.14.1  →    9.18.1
@godaddy/terminus                  ^4.10.2  →    4.11.2
@keyv/redis                         ^2.3.6  →     2.5.2
@types/async                        3.2.13  →    3.2.15
@types/express                     4.17.13  →   4.17.14
@types/express-serve-static-core  ^4.17.29  →   4.17.31
@types/express-session              1.17.4  →    1.17.5
@types/fast-redact                  ^3.0.1  →    ^3.0.2
@types/jsonwebtoken                  8.5.8  →     8.5.9
@types/ldapjs                        2.2.2  →     2.2.4
@types/lodash                     4.14.182  →  4.14.186
@types/marked                        4.0.3  →     4.0.7
@types/nodemailer                    6.4.4  →     6.4.6
date-fns                           ^2.28.0  →    2.29.3
eventemitter2                       ^6.4.5  →     6.4.9
express                            ^4.18.1  →    4.18.2
fast-redact                         ^3.1.1  →     3.1.2
graphql-compose                     ^9.0.8  →     9.0.9
joi                                ^17.6.0  →    17.6.3
keyv                                ^4.3.0  →     4.5.0
knex                                 2.2.0  →     2.3.0
liquidjs                           ^9.37.0  →    9.42.0
marked                             ^4.0.16  →     4.1.1
nodemailer                          ^6.7.5  →     6.8.0
nodemailer-mailgun-transport        ^2.1.4  →     2.1.5
openid-client                      ^5.1.10  →     5.2.0
pg                                  ^8.7.3  →     8.8.0
qs                                 ^6.10.5  →    6.11.0
rate-limiter-flexible               ^2.3.7  →    2.3.12
sanitize-html                       ^2.7.0  →     2.7.2
snappy                              ^7.1.1  →     7.2.0
sqlite3                             ^5.0.8  →     5.1.2
supertest                           ^6.2.3  →     6.3.0
ts-node                            ^10.8.2  →    10.9.1
typescript                           4.7.3  →     4.8.4
vm2                                ^3.9.10  →    3.9.11
```

</details>

- `@rollup/plugin-alias                ^3.1.9  →    4.0.0`
- `@rollup/plugin-virtual              ^2.1.0  →    3.0.0`
- `argon2                             ^0.29.1  →   0.30.1`
- `async-mutex                         ^0.3.2  →    0.4.0`
- `axios                              ^0.27.2  →    1.1.3`
- `commander                           ^8.0.0  →    9.4.1`
- `dotenv                             ^10.0.0  →   16.0.3`
- `graphql                            ^15.5.0  →   16.6.0`
- `helmet                              ^4.6.0  →    6.0.0`
  Changes defaults. Should check App usage and tweak our defaults accordingly. See https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md#500---2022-01-02
- `jest                                28.1.2  →    29.2.1`
- `js2xmlparser                        ^4.0.2  →    5.0.0`
- `object-hash                         ^2.2.0  →    3.0.0`
- `openapi3-ts                         ^2.0.2  →    3.1.1`
- `pino                                6.13.3  →     8.6.1`
  `prettyPrint` option was removed, needs a refactor to use the new transport system
- `pino-http                            5.8.0  →     8.2.1`
- `rollup                             ^2.75.6  →    3.2.3`
- `sharp                              ^0.30.6  →   0.31.1`
- `tedious                            ^13.0.0  →   15.1.0`
- `ts-jest                             28.0.5  →    29.0.3`
- `ts-node-dev                          1.1.8  →     2.0.0`
- `uuid                                ^8.3.2  →    9.0.0`

### Type updates

- `@types/jest                         27.5.2  →    29.2.0`
- `@types/node                        16.11.9  →   18.11.2`
- `@types/node-cron                     2.0.5  →     3.0.4`
- `@types/pino                         6.3.12  →     7.0.4`
- `@types/sharp                        0.30.4  →    0.31.0`

### :x: Can't be updated at this time

-  `@directus/format-title             ^9.15.0  →   10.0.0`
  ESM only, requires v10 branch
- `camelcase                           ^6.2.0  →    7.0.0`
  ESM only, requires v10 branch
- `chalk                               ^4.1.1  →    5.1.2`
  ESM only, requires v10 branch
- `execa                               ^5.1.1  →    6.1.0`
  ESM only, requires v10 branch
- `globby                             ^11.0.4  →   13.1.2`
  ESM only, requires v10 branch
- `inquirer                            ^8.2.4  →    9.1.4`
  ESM only, requires v10 branch
- `@types/inquirer                      8.2.1  →     9.0.2`
  Needs inquirer@9
- `nanoid                             ^3.1.23  →    4.0.0`
  ESM only, requires v10 branch
- `ora                                 ^5.4.0  →    6.1.2`
  ESM only, requires v10 branch
- `strip-bom-stream                    ^4.0.0  →    5.0.0`
  ESM only, requires v10 branch

---

## `@directus/app`

<details><summary>Patch / minor updates</summary>

```
@babel/core                         ^7.18.13  →     7.19.3
@babel/preset-env                   ^7.18.10  →     7.19.4
@directus/extensions-sdk             ^9.14.1  →     9.18.1
@fullcalendar/core                    5.11.0  →     5.11.3
@fullcalendar/daygrid                 5.11.0  →     5.11.3
@fullcalendar/interaction             5.11.0  →     5.11.3
@fullcalendar/list                    5.11.0  →     5.11.3
@fullcalendar/timegrid                5.11.0  →     5.11.3
@popperjs/core                        2.10.2  →     2.11.6
@sindresorhus/slugify                  2.1.0  →      2.1.1
@storybook/addon-actions              6.5.10  →     6.5.12
@storybook/addon-backgrounds          6.5.10  →     6.5.12
@storybook/addon-docs                 6.5.10  →     6.5.12
@storybook/addon-essentials           6.5.10  →     6.5.12
@storybook/addon-links                6.5.10  →     6.5.12
@storybook/addon-measure              6.5.10  →     6.5.12
@storybook/addon-outline              6.5.10  →     6.5.12
@storybook/client-api                 6.5.10  →     6.5.12
@storybook/client-logger              6.5.10  →     6.5.12
@storybook/core-common                6.5.10  →     6.5.12
@storybook/node-logger               ^6.5.10  →     6.5.12
@storybook/vue3                       6.5.10  →     6.5.12
@types/color                           3.0.2  →      3.0.3
@types/diff                            5.0.1  →      5.0.2
@types/dompurify                       2.3.1  →      2.3.4
@types/geojson                      7946.0.8  →  7946.0.10
@types/lodash                       4.14.177  →   4.14.186
@types/mapbox__mapbox-gl-draw          1.2.3  →      1.3.1
@types/mapbox__mapbox-gl-geocoder      4.7.1  →      4.7.3
@types/marked                          4.0.1  →      4.0.7
@types/qrcode                          1.4.1  →      1.5.0
@vue/compiler-sfc                     3.2.36  →     3.2.41
@vue/test-utils                       ^2.0.2  →      2.1.0
apexcharts                            3.30.0  →     3.36.0
date-fns                              2.24.0  →     2.29.3
dompurify                              2.3.3  →      2.4.0
flatpickr                              4.6.9  →     4.6.13
highlight.js                         ^11.5.1  →     11.6.0
html-entities                          2.3.2  →      2.3.3
joi                                  ^17.6.0  →     17.6.3
mapbox-gl                             ^2.9.1  →     2.10.0
markdown-it-anchor                    ^8.6.4  →      8.6.5
marked                                4.0.10  →      4.1.1
p-queue                                7.1.0  →      7.3.0
pinia                                 2.0.14  →     2.0.23
prettier                               2.4.1  →      2.7.1
qrcode                                 1.4.4  →      1.5.1
sass                                  1.43.4  →     1.55.0
typescript                             4.7.3  →      4.8.4
vite                                  ^3.1.7  →      3.1.8
vue                                   3.2.36  →     3.2.41
vue-i18n                              9.1.10  →      9.2.2
vue-router                            4.0.15  →      4.1.5
```

</details>

- `@directus/format-title               ^9.15.0  →     10.0.0`
- `@fortawesome/fontawesome-svg-core     1.2.36  →      6.2.0`
- `@fortawesome/free-brands-svg-icons    5.15.4  →      6.2.0`
- `@mapbox/mapbox-gl-geocoder             4.7.4  →      5.0.1`
  Adds an attribution footer. Should check map layout/interface for style glitches
- `@pinia/testing                       ^0.0.12  →     0.0.14`
- `@rollup/plugin-yaml                    3.1.0  →      4.0.0`
- `@storybook/builder-vite              ^0.1.41  →      0.2.4`
- `axios                                 0.24.0  →      1.1.3`
- `happy-dom                             ^6.0.4  →      7.6.0`
- `maplibre-gl                           1.15.2  →      2.4.0`
  There's one changelog entry regarding the removal of anything to do with `accessToken` and `mapbox://` links. Test layout/interface to confirm
- `nanoid                                3.1.30  →      4.0.0`
- `pretty-ms                              7.0.1  →      8.0.0`
- `react                                     17  →         18`
- `react-dom                                 17  →         18`
- `rollup                               ^2.75.6  →      3.2.3`
- `vitest                               ^0.18.1  →     0.24.3`

### Type Updates

- `@types/mime                            2.0.3  →      3.0.1`
- `@types/wellknown                       0.5.1  →      0.5.3`

### :x: Can't be updated at this time

- `codemirror                            5.64.0  →      6.0.1`
  Looks like codemirror 6 is a total rewrite and restructure of codemirror, meaning that the migration path is effectively the same as replacing codemirror completely. This should be done as a separate effort.
- `tinymce                               5.10.2  →      6.2.0`
  Similar to codemirror, this is a bigger rewrite that affects our use of tinymce. We should do this in a separate sprint
- `@tinymce/tinymce-vue                   4.0.5  →      5.0.0`
  Wraps tinymce 5, so see above

---

### :x: Can't be updated at this time

- `inquirer  ^8.1.2  →  ^9.1.4`
  ESM only, requires v10 branch

## `@directus/drive`

<details><summary>Patch / minor updates</summary>

```
fs-extra     ^10.0.0  →   10.1.0
typescript     4.5.2  →    4.8.4
```

</details>

- `dotenv        10.0.0  →   16.0.3`
- `jest          27.3.1  →   29.2.1`
- `ts-jest       27.0.7  →   29.0.3`

### Type Updates

- `@types/jest   27.0.3  →   29.2.0`
- `@types/node  16.11.9  →  18.11.2`

---

## `@directus/drive-azure`

<details><summary>Patch / minor updates</summary>

```
@azure/storage-blob  ^12.6.0  →  12.12.0
fs-extra              10.0.0  →   10.1.0
typescript             4.5.2  →    4.8.4
```

</details>

- `dotenv                10.0.0  →   16.0.3`
- `jest                  27.3.1  →   29.2.1`
- `ts-jest               27.0.7  →   29.0.3`

### Type Updates

- `@types/jest           27.0.3  →   29.2.0`
- `@types/node          16.11.9  →  18.11.2`

---

## `@directus/drive-gcs`

<details><summary>Patch / minor updates</summary>

```
@types/lodash          ^4.14.182  →  4.14.186
typescript                 4.5.2  →     4.8.4
```

</details>

- `@google-cloud/storage     ^5.8.5  →     6.5.3`
- `dotenv                    10.0.0  →    16.0.3`
- `jest                      27.3.1  →    29.2.1`
- `ts-jest                   27.0.7  →    29.0.3`

### Type Updates

- `@types/jest               27.0.3  →    29.2.0`
- `@types/node              16.11.9  →   18.11.2`

---

## `@directus/drive-s3`

<details><summary>Patch / minor updates</summary>

```
aws-sdk      ^2.928.0  →  2.1236.0
fs-extra       10.0.0  →    10.1.0
typescript      4.5.2  →     4.8.4
```

</details>

- `dotenv         10.0.0  →    16.0.3`
- `jest           27.3.1  →    29.2.1`
- `ts-jest        27.0.7  →    29.0.3`

### Type Updates

- `@types/jest    27.0.3  →    29.2.0`
- `@types/node   16.11.9  →   18.11.2`

### :x: Can't be updated at this time

`aws-sdk` is technically up to date, but has been superseded by `@aws-sdk/client-s3`. We should move to that other package, but that's a substantial re-write of the lib, so I'm not going to attempt that in this upgrade round.

---

## `extensions-sdk`

<details><summary>Patch / minor updates</summary>

```
@vue/compiler-sfc             ^3.1.1  →  3.2.41
fs-extra                     ^10.0.0  →  10.1.0
rollup-plugin-typescript2    ^0.31.2  →  0.34.1
typescript                     4.5.2  →   4.8.4
```

</details>

- `@rollup/plugin-commonjs      ^21.0.1  →  23.0.0`
- `@rollup/plugin-json           ^4.1.0  →   5.0.0`
- `@rollup/plugin-node-resolve  ^13.1.3  →  15.0.0`
- `@rollup/plugin-replace        ^3.1.0  →   5.0.0`
- `commander                     ^8.0.0  →   9.4.1`
- `rollup                       ^2.67.3  →   3.2.3`

### :x: Can't be updated at this time

- `chalk                         ^4.1.1  →   5.1.2`
  ESM only, requires v10 branch
- `execa                         ^5.1.1  →   6.1.0`
  ESM only, requires v10 branch
- `ora                           ^5.4.0  →   6.1.2`
  ESM only, requires v10 branch

---

## `@directus/schema`

<details><summary>Patch / minor updates</summary>

```
knex                   2.2.0  →  2.3.0
typescript             4.5.2  →  4.8.4
```

</details>

- `knex-schema-inspector  2.0.4  →  3.0.0`

---

## `@directus/shared`

<details><summary>Patch / minor updates</summary>

```
@types/express    4.17.13  →    4.17.14
@types/geojson   7946.0.8  →  7946.0.10
@types/lodash   ^4.14.182  →   4.14.186
date-fns           2.24.0  →     2.29.3
express           ^4.18.1  →     4.18.2
fs-extra           10.0.0  →     10.1.0
joi                17.4.2  →     17.6.3
knex                2.2.0  →      2.3.0
typescript          4.5.2  →      4.8.4
vue                3.2.36  →     3.2.41
vue-i18n           9.1.10  →      9.2.2
vue-router         4.0.15  →      4.1.5
```

</details>

- `axios             ^0.27.2  →      1.1.3`
- `pino               6.13.3  →      8.6.1`
- `vitest            ^0.18.1  →    ^0.24.3`

### Type Updates

- `@types/pino        6.3.12  →      7.0.4`

---

## `@directus/specs`

<details><summary>Patch / minor updates</summary>

```
openapi-types  ^12.0.0  →  12.0.2
```

</details>

- `openapi3-ts     ^2.0.1  →   3.1.1`

---

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@licitdev Looks like the blackbox tests aren't too happy with my Jest upgrades. Could you take a look? 🙏🏻

**Comment by licitdev** [comment]
`globby` is updated to its latest minor at `11.1.0` as versions `12.0.0` and above are ESM only. 
Ref: https://github.com/sindresorhus/globby/releases/tag/v12.0.0

**Comment by licitdev** [comment]
Noticed the request logging to be excessive, containing full information similar to the `LOG_STYLE=raw` but with nicer formatting from `pino-pretty`.

image

I've updated the transport to use `pino-http-print` from an example provided in `pino-http`. It utilises `pino-pretty` and outputs a similar log format with minor changes only. 
Ref: https://github.com/pinojs/pino-http#custom-formatters.

A new environment variable `LOGGER_TRANSPORT_OPTIONS` is added to allow the transport to be configurable. 
Ref: https://github.com/pinojs/pino-http-print#cli-arguments

### Pre Patch Tuesday

image

### Post Patch Tuesday

image

### Post Patch Tuesday with Configuration
`LOGGER_TRANSPORT_OPTIONS_TRANSLATE_TIME="SYS:standard"`

image

**Review by licitdev — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
> I've updated the transport to use pino-http-print from an example provided in pino-http. It utilises pino-pretty and outputs a similar log format with minor changes only.

Much better, thanks! 🙏🏻

**Pull request merged**
