### PR TITLE
Resolve ticket #1818

### PR DESCRIPTION
**Pull request by idelb**

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Sorry to make this painfully unnecessary, but can you patch the `develop` instead of `master` branch?

**Comment by idelb** [comment]
Sure. My fault, didn't know which branch to patch.
I have to make another pull request?

**Comment by WellingGuzman** [comment]
I think so, and thanks for this contribution.

**Comment by idelb** [comment]
I moved the patch to the right branch, you can close this pull request.

**Comment by WellingGuzman** [comment]
Ref: https://github.com/directus/directus/pull/1821

**Pull request closed without merging**
