### PR TITLE
Fix radio buttons with integer values

### PR DESCRIPTION
**Pull request by u12206050**
Fixes issue: #10111 

Possible discussion could be to add `Integer` as possible type to Radio Groups, but that would require more changes in display components as well.

### CODE REVIEW

**Comment by Oreilles** [comment]
It should not be possible to select the radio buttons interface with another type that string, as it is the only one supported.
The fact that you were able to do it (https://github.com/directus/directus/issues/10111) is a bug in itself, which will be fixed by https://github.com/directus/directus/pull/10096.
I will close this as the underlying issue has a much broader scope: which types do we add support for in the radio interface ? If we start adding int, we might want to also add others - and we'll also want to do this properly (add supported types to the interface declaration, cast the emitted value depending on that type, etc)

**Comment by benhaynes** [comment]
Any reason not to support `INT` (and other types) for the dropdown interface? I can see the value of having text options for an int value... and would rather not have separate dropdown interfaces for all the types. @rijkvanzanten thoughts?

**Comment by u12206050** [comment]
This should be fixed very quickly though, since there is currently 0 interfaces that support `INT` as value and string as their label for the choice. 
This leaves a gap in directus when using a predefined database schema that has used `INT` for a multiple choice field.
eg.
```
No = 0
Yes = 1
Maybe = 2
Unknown = 3
```

This fix at the very least allows the interface to work as expected if it was already defined so in the database.

**Comment by Oreilles** [comment]
I very much agree that it would very nice if support for other types than `string` was added, but this should be done properly and not just as a bug fix for a situation that wasn't supposed to be allowed 🙂 I'll gladly review another pull request that takes this into account. In the meantime you'll have to changing your database type to `varchar` for your use case to be officially supported.

**Pull request closed without merging**
