### PR TITLE
fix(docs): fix keycloak issuer url

### PR DESCRIPTION
**Pull request by andrewmiladd**
## Scope

What's changed:

- fixed the keycloak url issuer in sso examples

### CODE REVIEW

**Comment by paescuj** [comment]
Hey @andrewmiladd, thanks for the PR!

According to the official docs [^1], the previous URL seemed to be correct.
Is your suggested change based on another source?

[^1]: https://www.keycloak.org/docs/latest/securing_apps/#endpoints

**Comment by andrewmiladd** [comment]
Hey @paescuj,

While working on a project for my company, I attempted to enable Single Sign-On (SSO) for Directus with Keycloak as an Identity Provider (IP). I tried the provided link, even from Keycloak's documentation, but this URL consistently returns a 404 error.

Also, please check out this link where I found the correct endpoint that worked for my project: https://stackoverflow.com/questions/28658735/what-are-keycloaks-oauth2-openid-connect-endpoints

**Comment by paescuj** [comment]
> Hey @paescuj,
> 
> While working on a project for my company, I attempted to enable Single Sign-On (SSO) for Directus with Keycloak as an Identity Provider (IP). I tried the provided link, even from Keycloak's documentation, but this URL consistently returns a 404 error.
> 
> Also, please check out this link where I found the correct endpoint that worked for my project: https://stackoverflow.com/questions/28658735/what-are-keycloaks-oauth2-openid-connect-endpoints

I see, do you use Keycloak < 18? As mentioned in https://stackoverflow.com/a/71617578/20504834 it seems like `auth/` has been removed in newer version. If that's indeed the case we could mention both variants like:
```
# For Keycloak < 18.0.0
AUTH_KEYCLOAK_ISSUER_URL="http://<your_keycloak_domain>/auth/realms/<your_keycloak_realm>/.well-known/openid-configuration"
# For Keycloak >= 18.0.0
AUTH_KEYCLOAK_ISSUER_URL="http://<your_keycloak_domain>/realms/<your_keycloak_realm>/.well-known/openid-configuration"
```

**Comment by andrewmiladd** [comment]
> > Hey @paescuj,
> > While working on a project for my company, I attempted to enable Single Sign-On (SSO) for Directus with Keycloak as an Identity Provider (IP). I tried the provided link, even from Keycloak's documentation, but this URL consistently returns a 404 error.
> > Also, please check out this link where I found the correct endpoint that worked for my project: https://stackoverflow.com/questions/28658735/what-are-keycloaks-oauth2-openid-connect-endpoints
> 
> I see, do you use Keycloak < 18? As mentioned in https://stackoverflow.com/a/71617578/20504834 it seems like `auth/` has been removed in newer version. If that's indeed the case we could mention both variants like:
> 
> ```
> # For Keycloak < 18.0.0
> AUTH_KEYCLOAK_ISSUER_URL="http://<your_keycloak_domain>/auth/realms/<your_keycloak_realm>/.well-known/openid-configuration"
> # For Keycloak >= 18.0.0
> AUTH_KEYCLOAK_ISSUER_URL="http://<your_keycloak_domain>/realms/<your_keycloak_realm>/.well-known/openid-configuration"
> ```

Yes , actually I am using Keycloak 16
That would be accurate and correct ( determening the url based on version)

**Comment by paescuj** [comment]
> > > Hey @paescuj,
> > > While working on a project for my company, I attempted to enable Single Sign-On (SSO) for Directus with Keycloak as an Identity Provider (IP). I tried the provided link, even from Keycloak's documentation, but this URL consistently returns a 404 error.
> > > Also, please check out this link where I found the correct endpoint that worked for my project: https://stackoverflow.com/questions/28658735/what-are-keycloaks-oauth2-openid-connect-endpoints
> > 
> > 
> > I see, do you use Keycloak < 18? As mentioned in https://stackoverflow.com/a/71617578/20504834 it seems like `auth/` has been removed in newer version. If that's indeed the case we could mention both variants like:
> > ```
> > # For Keycloak < 18.0.0
> > AUTH_KEYCLOAK_ISSUER_URL="http://<your_keycloak_domain>/auth/realms/<your_keycloak_realm>/.well-known/openid-configuration"
> > # For Keycloak >= 18.0.0
> > AUTH_KEYCLOAK_ISSUER_URL="http://<your_keycloak_domain>/realms/<your_keycloak_realm>/.well-known/openid-configuration"
> > ```
> 
> Yes , actually I am using Keycloak 16 That would be accurate and correct ( determening the url based on version)

Cool, thanks for the quick confirmation & update ❤️

**Review by paescuj — APPROVED** [review]

**Comment by andrewmiladd** [comment]
Hey @paescuj 

the build has failed after merging

**Comment by paescuj** [comment]
> Hey @paescuj
> 
> the build has failed after merging

No worries, the checks were only canceled because in the meantime more PRs landed in main branch 👍

**Comment by andrewmiladd** [comment]
> > Hey @paescuj
> 
> > 
> 
> > the build has failed after merging
> 
> 
> 
> No worries, the checks were only canceled because in the meantime more PRs landed in main branch 👍 

So I don't need to rebuild ? 😊

**Comment by andrewmiladd** [comment]
So I need to rebuild? Or it will rebuild by its own?

**Comment by paescuj** [comment]
No need for manual intervention 👍 
The tests were superseded by the latest commit:
Screenshot 2023-10-11 at 00 15 53

**Comment by andrewmiladd** [comment]
Ahhh okay got it!
Thank you so much 🙏❤️

**Pull request merged**
