### PR TITLE
Display inline relationships in collection list

### PR DESCRIPTION
**Pull request by danilopolani**
This PR introduces a new features to display inline the relationships of a model. It's still work in progress (todo below) but I think it could be a nice addition.

A new `Display inline` along with a `Max. inline results` are now present when displaying `Related values`:

Transforming the output (at least for `m2m`, tbd for other relationships) from this:

To this (when `display inline` is checked):

It will use the `Display template` variable to build the output and the dropdown with the details will still be there.

-----

## Todo

- [x] [Interface] (Nice to have) Disable/Hide "Max results" if "Display inline" is not checked (any idea?)
- [x] [Style] Test with compact spacing
- [x] [Style] Test with comfortable spacing
- [x] [Style] Test with other display fields (no image etc.)
- [x] ~~[Core] Test with m2o~~ *not needed*
- [x] [Core] Test with o2m
- [x] ~~[Core] Test with translations o2m~~ *not needed / covered by https://github.com/directus/directus/pull/9776*
- [x] [Core] Test with m2a

### CODE REVIEW

**Comment by azrikahar** [comment]
Thanks for the PR! Just to answer the following question:

>  [Interface] (Nice to have) Disable/Hide "Max results" if "Display inline" is not checked (any idea?)

There's a good reference for this in group-accordion, where the choices are different depending on whether accordion mode is not checked:

https://github.com/directus/directus/blob/785c4306d63981360dad65b79e00a2ada844c636/app/src/interfaces/group-accordion/index.ts#L31-L79

In the same vein, adding a condition in the meta of `inlineMaxResults` such as (simplified):

```js
{
	field: 'inlineMaxResults',
	meta: {
		conditions: [{
			rule: {
				displayInline: {
					_eq: false,
				},
			},
			hidden: true,
		}],
	}
}
```

should do the trick here. Or you can also reverse it and make it hidden by default & if it's true, then make hidden false, for example.

**Comment by danilopolani** [comment]
Thank you @azrikahar , it works like a charm! The PR is pretty done, I just realised I should replace the custom chip component with `<v-chip>`, but I have to wait for https://github.com/directus/directus/issues/9864 to be solved to check that every display works fine 😢 
I'll remove the draft status on this PR as soon as possible after that

**Comment by LevinGermann** [comment]
> Thank you @azrikahar , it works like a charm! The PR is pretty done, I just realised I should replace the custom chip component with `<v-chip>`, but I have to wait for #9864 to be solved to check that every display works fine 😢
> I'll remove the draft status on this PR as soon as possible after that

Hey @danilopolani, I think the Draft status can be removed because #9864 is solved? :)

**Comment by danilopolani** [comment]
> > Thank you @azrikahar , it works like a charm! The PR is pretty done, I just realised I should replace the custom chip component with `<v-chip>`, but I have to wait for #9864 to be solved to check that every display works fine 😢
> > I'll remove the draft status on this PR as soon as possible after that
> 
> Hey @danilopolani, I think the Draft status can be removed because #9864 is solved? :)

Hey, 
I had another issue that was blocking this task but I noticed that they were not able to reproduce it, so probably it's just fixed with the latest releases. I'll come back on this asap, sorry!

**Comment by danilopolani** [comment]
Finally we got it! Thank you @rijkvanzanten for the [fix](https://github.com/directus/directus/issues/10105) 😄

**Comment by abdonrd** [comment]
Wow, that's really amazing! 👏🏻

**Comment by gloriarodrife** [comment]
It would be great to have this!

**Comment by errnesto** [comment]
This looks like great feature!

**Comment by julbd** [comment]
This feature would be very useful.
@rijkvanzanten no pressure but i don't understand why it is pending.

**Comment by julbd** [comment]
Ahah I understand, thanks for the reply :)

**Comment by rijkvanzanten** [comment]
> Yeah things and contributing processes changed a lot since I first opened this MR two years ago 😅

Yeah absolutely! Mostly to make sure we don't end up with PRs getting stale because we can't get to 'em on time 😬 Tricky balancing act to give new feature PRs the love and attention they need to make it in if we don't know / plan on them coming in (hence the new requirement for a prior issue now! That way we can make sure we schedule accordingly 🙂). Even though I think it's a very useful interface option to have, I'll close this PR out for now while we work on scoping out the requirements and updated PRs 👍🏻

**Pull request closed without merging**
