### PR TITLE
Support custom aspect ratios in image editor

### PR DESCRIPTION
**Pull request by qborisb**
## Description

Implements the improvement of the image editor mentioned in [this discussion](https://github.com/directus/directus/discussions/14395#discussioncomment-3130857)

Adds a new project setting called `Custom Aspect Ratios`, that, if specified, overwrites the default aspect ratios (16:9, square, etc.) in an image editor.

image

Each custom aspect ratio can be specified as an object with text (what the user sees) and the value (the actual ratio to be used in crop calculations)

Screenshot 2022-07-19 at 15 21 33

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Should we add an additional setting in project settings that sets the global defaults for the editor regardless of context? Then the interface option could be a more specific override for that global setting 🤔

**Comment by LasseRosenow** [comment]
> We should also make sure that people don't accidentally think it's binding, as you could still update the same image file through other places (like the file library). With that in mind, maybe it's actually better to only have it under project settings? Less flexible surely, but at least you wouldn't have the confusion about what sizes are allowed where 🤔

Hey everyone I just want to through my 2 cents in aswell :)
So I agree with @rijkvanzanten on this one. Because there are also discussions going on about having a requirement for images to have some certain ratio (#3286) So this feature would be in conflict. Because it would also be implemented in a similar way I suppose. Like defining the requested ratio inside the image interface, but this time it would be binding ^^

**Comment by LasseRosenow** [comment]
> Should we add an additional setting in project settings that sets the global defaults for the editor regardless of context? Then the interface option could be a more specific override for that global setting 🤔

Actually I really like this Idea, but also I feel like the `Project Settings` would get overcrowded. Something I would love to see is some new settings page that is more general being called "Interface Defaults" or something like this, enabling us to set all defaults for all interfaces in a more generic way (meaning its for everything and not some particular selected fields) :) What do you think?

**Comment by qborisb** [comment]
@rijkvanzanten I agree with you, now the custom aspect ratios can be configured in the global project settings:

Screenshot 2022-07-20 at 14 30 06

Then, these custom aspect ratios get used in all places where image-editor gets used (in file editing and item editing of any collection). Nevertheless, we would also appreciate the ability to specify aspect ratio per field (as was implemented in this PR earlier). Do you think there is any way with which people don't accidentally think the custom aspect ratios are a binding?

**Comment by qborisb** [comment]
@LasseRosenow good point about the `Project Settings` and "Interface Defaults"! I would be happy to integrate this PR with the discussion in [#3286](https://github.com/directus/directus/discussions/3286), though I am not sure at the moment what would be the best way to approach that :)

**Comment by qborisb** [comment]
@rijkvanzanten hello, it would be nice to get this PR merged :) I already made custom aspect ratios globally configurable, although initially our use case involved individual configurations in the interface settings. Do you think there is any way to implement this so that people don't confuse it with bindings?

**Comment by rijkvanzanten** [comment]
@azrikahar Might helping out with setting up a migration for the system field so we don't have to alter the seeds? Thanks!

**Comment by azrikahar** [comment]
> @azrikahar Might helping out with setting up a migration for the system field so we don't have to alter the seeds? Thanks!

Seems like there's no push access to this PR. I've added the migration (and resolve merge conflicts + minor code style tweaks) in #14786 for now.

**Review by azrikahar — COMMENTED** [review]
I'm not sure do we want to follow up this in #14786 or continue it here, but couple of additional questions/points:

- Should we simplify `image_editor_custom_aspect_ratios` to `custom_aspect_ratios` as the new column?

- Granted I'm not by any means very experienced in this, but is it usual to enter value for aspect ratios using floats (which is the current value input)?

- Let's make sure to update the docs as well, which should be in this page: https://github.com/directus/docs/blob/main/configuration/project-settings.md#

**Comment by rijkvanzanten** [comment]
> Seems like there's no push access to this PR. I've added the migration (and resolve merge conflicts + minor code style tweaks) in https://github.com/directus/directus/pull/14786 for now.

Ah yeah we've ran into that issue before. Lets close this in favor of #14786 then 👍🏻 

> Should we simplify image_editor_custom_aspect_ratios to custom_aspect_ratios as the new column?

Lets do it 👍🏻 

> Granted I'm not by any means very experienced in this, but is it usual to enter value for aspect ratios using floats (which is the current value input)?

Yes floats are important. For example: `16/9` = `1.77777778`, `16/10` = `1.6` etc.

**Comment by rijkvanzanten** [comment]
This'll is being continued in https://github.com/directus/directus/pull/14786

**Comment by azrikahar** [comment]
> Yes floats are important. For example: `16/9` = `1.77777778`, `16/10` = `1.6` etc.

I was actually wondering about it in terms of "ergonomics", such as having two input to enter `16`/`9` vs a float input to enter `1.77777778` 😄 but current approach should suffice 👍

**Pull request closed without merging**
