### PR TITLE
Load extensions in parallel

### LINKED ISSUE #4834: App keeps getting slower as more frontend extensions are used
When having many frontend extensions, it takes a real toll on the app's initial load time. And the more extensions you have, the longer it will take to load the app - at a much faster pace than if you were just developing the same vue app 'natively'.

I have about ~12 extensions (interfaces, layouts, and modules), and because the app frontend has to make `/extensions/[type]/[name]/index.js` requests for each of my extensions, it takes over 5s for the app to load, with caching on (time from seeing the white loading screen to seeing the app - about 12s without cache - and 1s without extensions).

Some workarounds I can think of:

- Reduce overhead of multiple requests by making it so all the extensions can be returned all at once with just 1 request from the API (eg. squeeze them into a single json, should be okay since you do always need them all anyway.)
- Look into making rollup build multiple extensions into 1 file
- Harder to do: load the extensions as they are needed (eg. hot-load module extension when user navigates there, or specific interfaces depending on viewed form) - not sure if possible wiht your current setup tbh
- Show some loading screen in the very initial phases of loading the app to make it less frustrating (currently it is just a white blank screen, with the window title "Loading...")
- More aggressive cache (eg. set a max age?)

With the advent of the marketplace I can easily see people having dozens of extensions loaded, so I think this is worth investigating :)

### PR DESCRIPTION
**Pull request by Nitwel**
closes #4834

### CODE REVIEW

**Comment by Jonesus** [comment]
Maybe this could be a PR to fix this issue while changing the same lines? :grin: 
https://github.com/directus/directus/issues/4733

**Comment by rijkvanzanten** [comment]
Gotta make sure you don't end up hitting the rate limiter this way. You're effectively burst loading all extensions, which might be problematic if you have 15 or more? 🤔  (obv based on rate limiter configuration)

**Comment by Nitwel** [comment]
Hmm, we could also group them in a batch of five or something?

**Review by rijkvanzanten — APPROVED** [review]

**Comment by sabinehoi** [comment]
Hey guys, for some reason this breaks extensions for me. `rc.56` works perfectly, then upgrading to `rc.57` breaks all extensions (none are loaded and warnings are printed to console `unable to load extension...` for each one). Let me know if you need more details or separate issue!

**Comment by benhaynes** [comment]
> Let me know if you need more details or separate issue!

Always good to open a new issue instead since this PR has already been merged and comments here can easily be overlooked.

**Pull request merged**
