### PR TITLE
Extend OpenAPI schemas for JSON-backed fields

### LINKED ISSUE #14208: Repeater field with two input fields is incorrectly typed in openapi spec
### Describe the Bug

A repeater with two input fields generates an OpenAPI spec that indicates the return value is a list of strings:

    list:
      nullable: true
      type: array
      items:
        type: string

When actually it returns a list of objects:

```js
[
  { title: 'a title', text: 'a text' },
  { title: 'another title', text: 'another text'}
]
```

The repeater: 
image

### To Reproduce

Create a repeater with two fields and generate the OpenAPI spec.

### Errors Shown

_No response_

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

v16.14.2

### What database are you using?

PostgreSQL 13.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by pmwheatley**
## Description

Fixes #14208

* Extended the OpenAPI spec generator to more robustly handle JSON-backed fields which specify nested fields.
* If the field type is JSON _and_ the field has nested field metadata available, then the extended type definitionm is now added to the schema.
* While the original issue referred only to manually created `repeater` fields, this fix will enhance other system `repeater` fields, such as `directus_collections.translations` which also include more explicit field metadata.

## Type of Change

- [x] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I'm wondering if we should/could safely rely on this. The configured fields in a repeater are just an app thing (not enforced by the API), so the type of the field contents is technically any JSON blob. Likewise, interfaces might not use the name `fields` for the option, as that's just an arbitrary name 🤔

**Comment by pmwheatley** [comment]
> I'm wondering if we should/could safely rely on this. The configured fields in a repeater are just an app thing (not enforced by the API), so the type of the field contents is technically any JSON blob. Likewise, interfaces might not use the name `fields` for the option, as that's just an arbitrary name 🤔

Thanks for the quick review! 😄 

I've done a bit of further digging, and I'm not sure there are _any_ cases in which a `json` field is returned as a `string` by the API (even a plain JSON field is returned as an object), so this could in theory be as simple as changing the schema for _all_ JSON fields from `{ type: "string" }` to `{ type: "object" }`.

What would (in general) be the effect of a client pushing a JSON blob which doesn't match the app's schema expectations (e.g. a `repeater` field with no/broken `fields` in the options)? My thinking was that if this could somehow break the app, then it should probably be enforced by the API (or at the least made visible in the spec to avoid unintentional error).

Still getting to grips with where different responsibilities sit here though, so very happy to go with the route of least friction for now (i.e. json fields return `object` type rather than `string`), and defer any discussion around more explicit typing until I understand the impact a bit better.

Would that be acceptable as a very light-touch fix for the issue?

**Comment by rijkvanzanten** [comment]
> I've done a bit of further digging, and I'm not sure there are any cases in which a json field is returned as a string by the API

This is correct, JSON fields are always cast and returned as JSON.

> so this could in theory be as simple as changing the schema for all JSON fields from { type: "string" } to { type: "object" }.

I agree!

> What would (in general) be the effect of a client pushing a JSON blob which doesn't match the app's schema expectations (e.g. a repeater field with no/broken fields in the options)? 

Technically speaking, the app would just ignore the fields that are included but aren't configured. Though there's a chance you'll cause issues in the interface by altering the data model too drastically (eg changing it from an array of items to a single object).

> My thinking was that if this could somehow break the app, then it should probably be enforced by the API

True, though doing deep object validation on JSON values that can be altered directly in the database is tricky. With a regular schema, we rely on the database as the last safety net when it comes to typing, but for JSON values it would only be checked when the Directus api is used.

> (or at the least made visible in the spec to avoid unintentional error).

I do think that the spec should follow what the API is doing though, not what the app then does on top of that data. So if the API doesn't enforce a certain structure, I don't think we should "enforce" that structure through the specs either 🤔 

> Still getting to grips with where different responsibilities sit here though, so very happy to go with the route of least friction for now (i.e. json fields return object type rather than string), and defer any discussion around more explicit typing until I understand the impact a bit better.
> Would that be acceptable as a very light-touch fix for the issue?

I think that the best approach (for now) is to have the spec "just" return `type: object` for all JSON fields, and not get into the deep JSON blob validation part yet.

**Comment by pmwheatley** [comment]
Turns out using `type: object` would not satisfy the original issue either, as the spec would still be returning an incorrect schema in the case of repeater fields (which return an array of objects).

In this case, I would lean towards returning an untyped schema for json, as that would allow anything which can be parsed as JSON to be considered valid (i.e. JSON object, array, primitive booleans, integers etc. can all be considered valid JSON). See the [discussion here](https://github.com/OAI/OpenAPI-Specification/issues/1388#issuecomment-339061316) on the differences with the `type` field between OpenAPI 2 and 3.

While this would satisfy the issue in terms of the _correctness_ of the spec, I don't think it adds anything in terms of _helpfulness_ of the spec.

An alternative approach would be to introduce a `oneOf` and enumerate the known cases:
```
{ type: 'object' },
{ type: 'array',
  items: { type: object }
}
...
```
but I'm not convinced yet that helps, and would exclude other valid JSON fields which are not explicitly mapped.

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
I think that _for now_ having JSON fields be returned as "any array or object of any structure" makes the most sense, as that's technically what the API will return (as there's no hard rules on the structure of json blobs. It's certainly better than "string", as that's just wrong. We can keep iterating on this moving forwards, but I think this is a decent starting point 🙂

**Pull request merged**
