### PR TITLE
Fix interface and display setup options with default values

### PR DESCRIPTION
**Pull request by nickrum**
The default values of the fields used to configure the interface and display options are properly set, but those values are not send to the API.

Unfortunately, I can't think of a way to fix this more cleanly.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
We should move this into the `store.ts` file that contains all other field watchers and logic 👍

**Comment by nickrum** [comment]
I wanted to stay away from that file if possible 😅

I'm not extactly sure what should be done if `options` is a `Component`.

**Comment by nickrum** [comment]
This is now in a much better state.

Depends on #3690

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
This isn't quite there yet 🤔 

I like the solution from a technical perspective, but there's a couple things that are going a little funny:

I noticed that it doesn't recognize the interface/display anymore which I think is due to the watcher that sets the `selectedDisplay` not firing soon enough.

CleanShot 2021-04-09 at 20 10 15@2x

The other thing I noticed is that it now only shows the default values, without any values that are saved to the DB 🤔

**Comment by rijkvanzanten** [comment]
On second thought (better late than never lol), is this even a problem?:

> The default values of the fields used to configure the interface and display options are properly set, but those values are not send to the API.

The interfaces themselves have default values for the props, wouldn't that already prevent any issues popping up from the default values not being saved to the interface options in the DB?

**Comment by rijkvanzanten** [comment]
As per https://github.com/directus/directus/pull/3525#issuecomment-819671225, this hasn't caused any issues later on. I'll close this for now. 

@nickrum Could you confirm if this is something we (still) need?

**Pull request closed without merging**
