### PR TITLE
Fix OpenAPI specs

### LINKED ISSUE #5504: Incorrect OAS definition
1) The issue is produced when you process the OAS definition. The OAS file that exports directus has some definitions missing: This is the error that show when I try to import it by swagger by example:

image

There are 2 different problems:
- operationId conflicts (both GET /user/me and PATCH /user/me have the same operationId),
- more importantly, undefined path parameters in some cases (e.g. {id} or {collection} is present in path name, but not declared as path parameters in the route definition)

2) Exact steps to reproduce this issue:
    2.1) Export the oas definition generated by the URL: /server/specs/oas
    2.2) Try the import the definition with some client like Swagger: https://editor.swagger.io/
3) Your environment:
    Directus v9.0.0-rc.62
    DBMS MySQL 8
    Deployment Docker
   
4) Solution:
I can fix it manually my definition but when I create a new category I have to do again in the new one, is a bit tedious. 
It should not be very conplitate fix it in the directus code.

### PR DESCRIPTION
**Pull request by paescuj**
Closes #5504

Btw. have you already considered / looked into generating OpenAPI specs with code annotations / comments? This would maybe help to keep the specs up-to-date... Just asking, no experience with this, though...
* https://apisyouwonthate.com/blog/theres-no-reason-to-write-openapi-by-hand
* This also looks quite interesting: https://github.com/lukeautry/tsoa

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
> Btw. have you already considered / looked into generating OpenAPI specs with code annotations / comments? This would maybe help to keep the specs up-to-date... Just asking, no experience with this, though...

Hmm yeah, I do like the idea of keeping it close to the source, as that makes sure it stays as up to date as it can. That being said though... OpenAPI isn't the only spec around, so I'm a little concerned we'll end up doing the same thing multiple times (OpenAPI, API Blueprint, RAML, JSON Schema) in comments all over the place 🤔 

I think it makes more sense to find a single tool that allows us to describe the API in detail, that then lets us export it to these different formats. We just need to find the one standard that can be converted to all the others.

**Comment by paescuj** [comment]
> Hmm yeah, I do like the idea of keeping it close to the source, as that makes sure it stays as up to date as it can. That being said though... OpenAPI isn't the only spec around, so I'm a little concerned we'll end up doing the same thing multiple times (OpenAPI, API Blueprint, RAML, JSON Schema) in comments all over the place

True that!

> I think it makes more sense to find a single tool that allows us to describe the API in detail, that then lets us export it to these different formats. We just need to find the one standard that can be converted to all the others.

This would be great! I'm not aware of such a tool, I only know that there are some converter tools (e.g. https://github.com/LucyBot-Inc/api-spec-converter).
Let's keep it like this for the moment and maybe change it once we've found a proper solution.

Besides this, I think this pull request is ready to get merged.

(This is actually one of my favorite xkcd 😅)

**Comment by rijkvanzanten** [comment]
I'm using Paw (https://paw.cloud) locally to debug the API endpoints (it's more or less Postman but as a native app). I've never really played around with it's documentation features, but it can export into multiple different formats. Might be worth looking into 🙂

**Comment by paescuj** [comment]
Sounds interesting! 👍 I think it's important that we can automate as much as possible (writing specification, converting, etc.).

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
