### PR TITLE
Small `Release` workflow clean-up

### PR DESCRIPTION
**Pull request by paescuj**
## Description

* Change `if` statements to be consistent across all workflows.
* Use `prepare` action in `publish-npm` job to set-up PNPM as used in all other workflows / jobs.

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
@paescuj Could this release automation failure be related to this change? https://github.com/directus/directus/actions/runs/3303957657/jobs/5452556415

I'm not seeing anything that catches my eye immediately, but it's the only change in the release flow so 🤷🏻

**Comment by paescuj** [comment]
I don't see the problem right now. If it is related, I'm very sorry! I can look at it in a few hours!

**Comment by rijkvanzanten** [comment]
> I don't see the problem right now. If it is related, I'm very sorry! I can look at it in a few hours!

I think it must've been an unrelated change in GH actions itself. I've reverted this PR and tried again, but the same issue persists 😭 I guess we'll have to recreate and update everything in that build process. Noticed there's a bunch of deprecation warnings too :(

**Comment by SanthoshMR** [comment]
I don’t think it’s related to GH actions. I was getting this error on bitbucket pipelines as well a few days back. It complained of corrupted packages. Will try digging deeper.

**Comment by paescuj** [comment]
I think I've found the cause... I'll provide a fix as soon as possible!

**Pull request merged**
