### PR TITLE
Add support for npm extensions

### PR DESCRIPTION
**Pull request by nickrum**
Missing features:

- [ ] Validate the host field against the Directus version using semver.
- [ ] Check for duplicate extensions.

### CODE REVIEW

**Comment by benhaynes** [comment]
This is so huge... thank you @nickrum!! I'm working on an updated in-app marketplace as we speak! ❤️

**Comment by rijkvanzanten** [comment]
Note to self: extend this to work with email templates

**Comment by nickrum** [comment]
This has already been implemented as part of #6377.

@rijkvanzanten Should we track the extension of this to work with email templates separately?

**Comment by rijkvanzanten** [comment]
What do you mean by 

> Should we track the extension of this to work with email templates separately?

?

**Comment by nickrum** [comment]
You left this note up there:

> Note to self: extend this to work with email templates

I was just wondering if we should track that in a new issue so we do not forget about it.

**Comment by rijkvanzanten** [comment]
Ah yeah, we'll have to make sure that every extension type is supported through the npm flow, not just a specific subset of them 🙂

**Pull request closed without merging**
