### PR TITLE
add meta object to createCollection SDK example.

### PR DESCRIPTION
**Pull request by alexvdvalk**
## Scope

What's changed:

- small bug in createCollection docs. The API requires a ```meta``` object in the createCollection payload otherwise it fails.

## Potential Risks / Drawbacks

- none

## Review Notes / Questions

---

Fixes #\<num\>

### CODE REVIEW

**Review by br41nslug — COMMENTED** [review]
It looks like this is the top example, if so it should not have an object at all but rather same as http/graphql:
```
const result = await client.request(
	createCollection(collection_object)
);
```

**Review by paescuj — DISMISSED** [review]
Thanks @alexvdvalk ❤️

**Comment by alexvdvalk** [comment]
its quite nice to be able to copy-paste the example and have it work

**Comment by br41nslug** [comment]
> its quite nice to be able to copy-paste the example and have it work

Correct, thats why one of the examples is copy-pastable, not exactly sure what the idea was behind duplicating these examples but each endpoint ended up with 2, one with a bunch of placeholders and one with a proper example

**Review by paescuj — APPROVED** [review]

**Pull request merged**
