### PR TITLE
Use SEARCH instead of GET to fetch filtered data in frontend

### LINKED ISSUE #5540: Use SEARCH instead of GET for o2m relational interfaces
Currently, the o2m interface will fetch and render the first 100 items inline. If you are relating to a collection that uses UUIDs for IDs, there's a change that the full URL starts to grow too big for certain browsers/webservers to handle, resulting in a `414 request-URI too large` error (see https://github.com/directus/directus/discussions/5419).

To resolve this, we should replace this call:

https://github.com/directus/directus/blob/bdbe28508934d97900c24cf2dd7f66c600893250/app/src/interfaces/list-o2m/list-o2m.vue#L307-L312

with [a SEARCH request](https://docs.directus.io/reference/api/introduction/#search-http-method) where the query is in the body

### PR DESCRIPTION
**Pull request by paescuj**
Closes #5540

Tested on Firefox, works like a charm.

Note: There is an open pull request from @rijkvanzanten for axios to accept method 'search' (string to be exact), however it is already working (just a TS warning) - see https://github.com/axios/axios/pull/3802

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@paescuj Should we just update every get in the app with search? I can already imagine 3 other places where this same issue might show up in the future, like list-m2m, list-m2a, but also things like batch edit for files, etc 🤔

**Comment by paescuj** [comment]
Sure, I can update all the list interfaces 👍
Not sure about the other stuff, we just need replace GET request where the query could grow big.
If you'd provide a list of other places, I'm going to update those as well.

**Comment by paescuj** [comment]
I've converted all `api.get` requests with a filter which could potentially become big.

Do you think we should update other requests too?
E.g.:
https://github.com/directus/directus/blob/31fbb5f06fed2460efd2bec31b8994e7d47f51f8/app/src/modules/files/components/navigation-folder.vue#L230-L238

**Comment by rijkvanzanten** [comment]
This is superseded by #12082

**Pull request closed without merging**
