### PR TITLE
Durus: a2o

### PR DESCRIPTION
**Pull request by jaads**
## Scope

Here the query logic is done for a2o.

What's changed:

- Added new type which defined how the a2o relation is stored in the datastores: as agreed, we have use a JSON column to store the dynamic relationship. here's an example:
```ts
{
    "foreignKey": [2],
    "foreignCollection": "images"
}
```
- The converter got enhances to convert an a2o field to an SQL query using JOINs based on JSON path values.

here is an example of a generated SQL query (two foreign collections, one of which has a composite key)
```sql
SELECT "t0"."id" AS "c0", "t0"."relation" -> $1 AS "c1", "t1"."heading" AS "c2", "t2"."image_url" AS "c3"
FROM "pages" AS "t0"
         LEFT JOIN "headings" AS "t1"
                   ON "t0"."relation" ->> $2 = $3 AND CAST("t0"."relation" -> $4 ->> 0 AS numeric) = "t1"."id" AND
                      "t0"."relation" -> $5 ->> 1 = "t1"."heading"
         LEFT JOIN "images" AS "t2"
                   ON "t0"."relation" ->> $6 = $7 AND CAST("t0"."relation" -> $8 ->> 0 AS numeric) = "t2"."id";
```   
with the paramters:
```js
[
  'foreignCollection',
  'foreignCollection',
  'headings',
  'foreignKey',
  'foreignKey',
  'foreignCollection',
  'images',
  'foreignKey'
]
```

an example result where a `related-result` is either from headers images collection.
```js
{ id: 1, 'related-data': { url: 'link29' } }
{ id: 2, 'related-data': { heading: 'news' } }
```
---

Fixes https://github.com/directus/durus/issues/16

### CODE REVIEW

**Comment by jaads** [comment]
the implementation is done 🎉 

however, one final test needs to be completed, for which a deterministic generation of the alias would be very helpful (https://github.com/directus/directus/issues/20717). A PR for this issue is almost done. After the issue is resolved, the test can be completed and this PR can be merged.

**Comment by jaads** [comment]
on hold until https://github.com/directus/directus/issues/20717 is done

**Comment by jaads** [comment]
we decided to add proper JSON support first and use that to tackle a2o. so this PR is on hold until https://github.com/directus/directus/issues/21156 is done

**Comment by rijkvanzanten** [comment]
Migrated to directus/durus

**Pull request closed without merging**
