### PR TITLE
Allow for selecting language in live preview

### LINKED ISSUE #19637: Live Preview with translations not working
### Describe the Bug

The live preview feature does not work when we use the translation feature. 
The preview window should propose a dropdown for selecting the language to see. 

As I want use slugs for article routing, and these slugs get translated and different for each languages, in the Preview URL I choose `BLOG_URL/(Translation->Slug)` but this got converted to the list of translated slugs instead of one (like `["slug-in-english", "slug-in-french"]`), so the page does not exist. 

### To Reproduce

Follow this translation guide
https://docs.directus.io/guides/headless-cms/content-translations.html

Then follow the Live preview guide
https://docs.directus.io/guides/headless-cms/live-preview/nextjs.html

Setup the preview URL to `BLOG_URL/(Translation->Slug)`

Open the preview, see that `Slug` is a string of an array of all the translated slugs.
The URL tried is `BLOG_URL/["slug-in-english", "slug-in-french"]`

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by Nitwel**
Should be a really nice enhancement for translations in live preview.

closes #19637 

Example url: `https://nitwel.de/{{translations.title}}/{{topic.translations.topic}}`
grafik

### CODE REVIEW

**Review by paescuj — CHANGES_REQUESTED** [review]
On the one hand I kinda like this solution, on the other hand it doesn't seem very intuitive to me:
- The language dropdown in Live Preview only appears after saving translations and only shows languages with translations, which doesn't seem very obvious to me (at least at first glance)
- With split view activated for translations, the user can now select three different languages in three different places which might be confusing
  
- Not sure if it's a good idea to add another element to the already somewhat crowded live preview bar:
  

If we really go with this we would have to update the min size for Live Preview to prevent it from being hidden behind the sidebar:
https://github.com/directus/directus/blob/ab64b3db289358d3476e1454e4dd7b3f8e80657f/app/src/modules/content/routes/item.vue#L6


A simpler solution could be to use the currently selected language from the translations field (left if split view is activated) for Live Preview.

**Comment by Nitwel** [comment]
> The language dropdown in Live Preview only appears after saving translations and only shows languages with translations, which doesn't seem very obvious to me (at least at first glance)

If there are no translated items, there is no need to show the option. Though I agree that that might be confusing.

> If we really go with this we would have to update the min size for Live Preview to prevent it from being hidden behind the sidebar

Very good point!

> A simpler solution could be to use the currently selected language from the translations field (left if split view is activated) for Live Preview.

That's not possible due to the following edge cases:
- There could be multiple translation interfaces in the same collection.
- There is no visual connection between the language selected in the interface and the language used for the live preview url.
- The live preview feature can't access state from within the extension.
- There could be no translations in the root collection but in a related one. E.g. an articles collection with tags and only the tags collection is being translated for some reason.

That's why there has to be a separate selector.

**Comment by rijkvanzanten** [comment]
This shouldn't be hardcoded to languages and translations. There's an infinite amount of permutations that you might want to use as URL templates, and this is too opinionated of a solution IMO. We could consider making some configuration options for this in the live preview settings of collections to allow you to render any dropdown, but lets not rush into things here with a new feature that's specific to languages 👍🏻

**Comment by Nitwel** [comment]
> but lets not rush into things here with a new feature that's specific to languages 

I agree, but I see this as a big blocker for anybody that uses translations in their schema in combination with live previews. The main problem being that the live preview feature is unusable on translated fields as you get an array of all possible options like `https://my.com/article/['art-1','enu-1']` so there is no way of knowing what item corresponds to what language.

That's why I see this as a bug that should be fixed sooner than later.

> We could consider making some configuration options for this in the live preview settings of collections to allow you to render any dropdown

I don't think I follow what you mean by that, but let me know what you think a proper solution could look like!

**Comment by DanielBiegler** [comment]
I think something more akin to the following where you could select/make any field you'd like:

image

Where you can then create generic or reference items that you would like to show up under a dropdown

(note: for the example I just copied raw html, I didnt look into implementation)

**Comment by paescuj** [comment]
> I think something more akin to the following where you could select/make any field you'd like:
> 
> image
> 
> Where you can then create generic or reference items that you would like to show up under a dropdown
> 
> (note: for the example I just copied raw html, I didnt look into implementation)

Interesting!

IMO, we should completely overhaul the Preview URL interface respectively create a new dedicated interface for URL composition, as it reaches its limits. I'll submit a Feature Request for this so we can discuss over there.

**Pull request closed without merging**
