### PR TITLE
Fix duplicate local extension name collision

### LINKED ISSUE #20213: Duplicate extensions name collision
### Describe the Bug

We have a lot of extensions, divided into the different folders `hooks`, `endpoints` etc.

Many of them do have the same name, which is now causing an issue in Directus 10.7.0

```
"Duplicate entry 'activities' for key 'directus_extensions.PRIMARY'",
```

Worst though is this is just shrugged off with a warning: ` Couldn't load extensions`
But the app still goes online, even though half of the hooks might not be active.

### To Reproduce

Add a folder called `activities` to both `extensions/hooks` and `extensions/endpoints` 

Add a simple index.js for each with some boiler code.

Notice when you try starting the server that it will though these warnings about unable to insert into the `directus_extensions` directory.

### Directus Version

10.7.0

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by nickrum**
Fixes #20213

### CODE REVIEW

**Review by paescuj — APPROVED** [review]
Works great 🚀

**Comment by u12206050** [comment]
This breaks custom endpoints by suffixing them with `:endpoint` #20223 20223

**Comment by u12206050** [comment]
I didn't have an issue with this PR: #20214 since we don't actually change the extension name.

**Comment by nickrum** [comment]
#20214 adds a prefix to all extensions which is not something we should do.

**Comment by XanManZA** [comment]
@rijkvanzanten shouldn't this changeset also cover bundle extensions?
I have a bundle extension receiving this error. Looking at the code it seems to only cover `operation` extension types.

**Comment by paescuj** [comment]
> @rijkvanzanten shouldn't this changeset also cover bundle extensions? I have a bundle extension receiving this error. Looking at the code it seems to only cover `operation` extension types.

The fix provided in this pull request covers all local extension types, which should be sufficient as bundle extensions names should be unique across an instance anyway. Please open a new issue if you feel like you stumbled upon a bug.

**Comment by XanManZA** [comment]
> > @rijkvanzanten shouldn't this changeset also cover bundle extensions? I have a bundle extension receiving this error. Looking at the code it seems to only cover `operation` extension types.
> 
> The fix provided in this pull request covers all local extension types, which should be sufficient as bundle extensions names should be unique across an instance anyway. Please open a new issue if you feel like you stumbled upon a bug.

Lodged issue https://github.com/directus/directus/issues/20412 with steps to reproduce.

**Pull request merged**
