### PR TITLE
Update glossary docs: Fix item description

### PR DESCRIPTION
**Pull request by SharmaPawan11**
## Scope

Fixes a typo in glossary.md where "collection" is written but "item" should be the correct word there.

## Potential Risks / Drawbacks

N/A

## Review Notes / Questions

N/A

### CODE REVIEW

**Comment by hanneskuettner** [comment]
Heya @SharmaPawan11, thank you for the doc fix!
Can you sign our CLA and then merge this?

**Comment by SharmaPawan11** [comment]
Sure @hanneskuettner . Let me do it

**Comment by SharmaPawan11** [comment]
Hey @hanneskuettner ! Can you please help me with the merge? It says merging is blocked - 

Merging can be performed automatically with 1 approving review. 

Also, the "Check / Format (pull_request)" is failing.

**Review by paescuj — APPROVED** [review]
Thanks for your contribution, @SharmaPawan11!

> Can you please help me with the merge?

Merging has to be performed by the core team 👍 

> Also, the "Check / Format (pull_request)" is failing.

We do code format checks via [Prettier](https://prettier.io/). If the check fails, you can, for example, fix the format by running the following command:
```shell
pnpm format --write
```
I did so for now 👌

**Pull request merged**
