### PR TITLE
Fix loading of Sandbox Operation Extensions

### PR DESCRIPTION
**Pull request by paescuj**
## Scope

What's changed:

- The expected definition format for Sandbox Operation Extensions was a function while it should be an object instead
- See https://docs.directus.io/extensions/sandbox/register.html#operations and also aligns with https://docs.directus.io/extensions/operations.html#api-entrypoint

## Potential Risks / Drawbacks

None

## Review Notes / Questions

None

---

Thanks to @phazonoverload for reporting!

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by phazonoverload** [comment]
Yes thank you! Look forward to this landing in an upcoming release

**Comment by binaryben** [comment]
Should sandboxed endpoints also be set to allow a configuration options with the `id` and `handler` items?

**Comment by paescuj** [comment]
> Should sandboxed endpoints also be set to allow a configuration options with the `id` and `handler` items?

Can you elaborate? Not sure I understand

**Comment by binaryben** [comment]
> Can you elaborate? Not sure I understand

Of course! The non-sandboxed endpoint extensions also allow for [definition as a config object](https://docs.directus.io/extensions/endpoints.html), i.e.:

```ts
export default {
	id: 'greet',
	handler: (router) => {
		router.get('/', (req, res) => res.send('Hello, World!'));
		router.get('/intro', (req, res) => res.send('Nice to meet you.'));
		router.get('/goodbye', (req, res) => res.send('Goodbye!'));
	},
};
```

For sake of alignment, should sandbox endpoints have the same fix applied? Not sure if it's considered a bug or feature request, so I wanted to check here first before reporting.

**Comment by paescuj** [comment]
> > Can you elaborate? Not sure I understand
> 
> Of course! The non-sandboxed endpoint extensions also allow for [definition as a config object](https://docs.directus.io/extensions/endpoints.html), i.e.:
> 
> ```ts
> export default {
> 	id: 'greet',
> 	handler: (router) => {
> 		router.get('/', (req, res) => res.send('Hello, World!'));
> 		router.get('/intro', (req, res) => res.send('Nice to meet you.'));
> 		router.get('/goodbye', (req, res) => res.send('Goodbye!'));
> 	},
> };
> ```
> 
> For sake of alignment, should sandbox endpoints have the same fix applied? Not sure if it's considered a bug or feature request, so I wanted to check here first before reporting.

Gotcha, nice catch! Thanks for clarifying and reporting ❤️ Indeed, this should behave the same as non-sandboxed endpoint extensions. I'll submit a fix 👍

**Comment by binaryben** [comment]
> For security reasons, we would probably come up with a way which requires routes under root to be explicitly allowed.

When we say allowing routes under root, wouldn't the behaviour of the ID serving as a namespace be no different from using the extension name? From a security perspective, I think ensuring the ID is not nullish and at most, having an exclusion list should cover most (if not all) security concerns. Keen to hear your thoughts of course

**Pull request merged**
