### PR TITLE
Add support for adding a collection accent color

### PR DESCRIPTION
**Pull request by oreilles**
Capture d’écran 2021-05-21 à 23 07 01

Because what's better than icons ? 
( This also contains a fix for the `select-icon` interface placeholder not having been updated after rename )

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Oooohhhhh i actually don't know how i feel about this 👀 When setup correctly, it could be a cool way to differentiate certain collections, but for non-graphic-design-inclined users, it's an easy way to make things look horrendous 😨

**Comment by Oreilles** [comment]
Aha. It's just something I wanted for the very start. All collection icons being the same color makes them less recognizable, and (imo) also makes the UI a bit sad. Ultimately the app design is the admin's decision - the logo, primary color, and pretty much the whole interface can already be themed in the app settings 🙂

**Comment by benhaynes** [comment]
Love it! I think this can be an optional, and powerful organizational tool for admins. Here are my thoughts:

* Off by default. This is interesting because when "off" the nav icons are dark and the page icons are light gray.
* Have a set of pre-defined "safe" colors to easily choose from, this will ensure things look decent
* We might also want to have the Collection/Item detail pages use this color in the header icon (left of page title)
* Maybe: Somehow allow for _any_ color to be used (without resorting to CSS overrides)

**Comment by benhaynes** [comment]
Can I see a screenshot of the configuration options you are using for setup?

**Comment by rijkvanzanten** [comment]
> Have a set of pre-defined "safe" colors to easily choose from, this will ensure things look decent
> Maybe: Somehow allow for any color to be used (without resorting to CSS overrides)

sounds like we'll just copy the color interface configuration for Project Color:

CleanShot 2021-05-21 at 21 36 15@2x

**Comment by benhaynes** [comment]
> sounds like we'll just copy the color interface configuration for Project Color:

Exactly! Just wondering if we should allow "other"... I guess so. 🤔

**Comment by Oreilles** [comment]
This is what the setup looks like:
Capture d’écran 2021-05-22 à 10 25 19

**Comment by rijkvanzanten** [comment]
> (Could be nice to have an input that does both... )

Agreed! Though the question "how can we have one interface (/field) save to two+ columns is a totally different can of worms 🪱

**Comment by Oreilles** [comment]
> > (Could be nice to have an input that does both... )
> 
> Agreed! Though the question "how can we have one interface (/field) save to two+ columns is a totally different can of worms 🪱

A workaround could be to change the `icon` field from text to json, and store it as `{ "name": ..., "color": ... }` ( that way we could also add the `filled` prop too... )

**Comment by benhaynes** [comment]
Let's keep the setup as you have it (no single field for two columns), but let's make name and description both half width:

```
[Name    ] [Note   ]
[Icon    ] [Color  ]
```

**Comment by rijkvanzanten** [comment]
Good point, it doesn't necessarily have to remain the _icon color_, but could be configured as a generic "collection color" that we can surface elsewhere in the future as well

**Comment by Oreilles** [comment]
> Let's keep the setup as you have it (no single field for two columns), but let's make name and description both half width:
> 
> ```
> [Name    ] [Note   ]
> [Icon    ] [Color  ]
> ```

- [x] Done

> Good point, it doesn't necessarily have to remain the icon color, but could be configured as a generic "collection color" that we can surface elsewhere in the future as well

Totally 👍

**Pull request merged**
