### PR TITLE
Add default folder upload to WYSIWYG editors

### PR DESCRIPTION
**Pull request by letoast**
Add the recently added feature of picking the default upload folder for items to WYSIWYG editors

### CODE REVIEW

**Comment by letoast** [comment]
As per https://github.com/directus/directus/pull/3209#issuecomment-892657472

**Comment by JonL1** [comment]
Is the review pending due to backlog or is anything else missing? May I help?

**Comment by letoast** [comment]
Wondering the same thing 😃

**Comment by benhaynes** [comment]
External reviews are always helpful in making sure everything's ready for final review/merge. That said, the main limitation now is our backlog of tasks before getting through all our PRs — and new features take a back-seat to stability and fixes.

**Comment by JonL1** [comment]
> External reviews are always helpful in making sure everything's ready for final review/merge. That said, the main limitation now is our backlog of tasks before getting through all our PRs — and new features take a back-seat to stability and fixes.

I totally understand that. I was just wondering if I could help in any way! Thanks for taking the time to reply and give context.

**Comment by rijkvanzanten** [comment]
Everything looks good to me on first look 🙂 I should have some time to review / merge before the next release 👍🏻

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
