### PR TITLE
[WYSIWYG] Custom element wrappers

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Adds the ability to add custom element wrappers w/ buttons into the editor. 

For example: the following setting
```json
{
  "highlight": {
    "name": "Add Highlight",
    "template": "<div class='highlight'>{{text}}</div>",
    "selector": "div.highlight",
    "preview_style": "border: 2px dashed grey;"
  }
}
```
results in the editor adding a `AH` button which will wrap the selected text with the provided template.  

screen shot 2017-06-09 at 22 22 33

The optional `selector` and `preview_style` properties allow the user to provide custom preview-styling inside the editor:

screen shot 2017-06-09 at 22 26 42

Next to that, this PR fixes some small bugs:
- Rename 'Inline Code' toolbar option to 'View Source'
- Fix 'inline' / 'alignment' toolbar option not being honored when it's the only one selected

_Update 1:_
The optional `label` property allows the user to override the default initial-based label of the button with a custom string

### CODE REVIEW

**Review by wellingguzman — APPROVED** [review]
Looks good, curious why changed `delete this.editor` to `this.editor = null`

**Comment by rijkvanzanten** [comment]
Ha! I knew you would notice.

I came across this little info snippet this week so it seamed like a low-hanging fruit optimization 😉 

https://mythbusters.js.org/#/v8-tips/freeing-memory

**Comment by WellingGuzman** [comment]
Awesome, makes sense! 👍

**Comment by benhaynes** [comment]
Yeehaw!

**Comment by RudolfFussek** [comment]
When I add a image and click on the Hightlight Button, doesn't work..

**Pull request merged**
