### PR TITLE
fix advanced filter fields order with field groups

### LINKED ISSUE #8932: Advanced filter show fields out of sequence when using field groups
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When not using field groups, the fields appear in the order specified in the collection settings. This is based on the **sort** column of the **directus_fields** table, and it works as expected. 

When using field groups, the sequential value stored in the **sort** column resets to "1" for each field group. Imagine a scenario with 3 fields groups, each containing 3 fields.  So the edit form has this sequence: 

**Group 1 Field 1** _(sort value = 1)_
**Group 1 Field 2** _(sort value = 2)_
**Group 1 Field 3** _(sort value = 3)_

**Group 2 Field 1** _(sort value = 1)_
**Group 2 Field 2** _(sort value = 2)_
**Group 2 Field 3** _(sort value = 3)_

**Group 3 Field 1** _(sort value = 1)_
**Group 3 Field 2** _(sort value = 2)_
**Group 3 Field 3** _(sort value = 3)_

When using filters, fields are displayed as follows, based on the sort value:

**Group 1 Field 1** _(sort value = 1)_
**Group 2 Field 1** _(sort value = 1)_
**Group 3 Field 1** _(sort value = 1)_
**Group 1 Field 2** _(sort value = 2)_
**Group 2 Field 2** _(sort value = 2)_
**Group 3 Field 2** _(sort value = 2)_
**Group 1 Field 3** _(sort value = 3)_
**Group 2 Field 3** _(sort value = 3)_
**Group 3 Field 3** _(sort value = 3)_

This makes them seem "shuffled". It's difficult to find fields in the list. The filter dropdown should  take groups into consideration when determining the order in which they're displayed. 

Ideally, it would be great if the dropdown list would display field groups as expandable folders. 

### To Reproduce

1. Organize fields for a collection using more than one field group. 
2. Use the filter at the top of the collection's layout and click _add filter_
3. Notice the fields are not in the same order as the collection configuration

### Errors Shown

None

### What version of Directus are you using?

v9.0.0-rc.98

### What version of Node.js are you using?

14.18

### What database are you using?

MySQL

### What browser are you using?

Chrome 94.0.4606.81

### What operating system are you using?

MacOS 11.6

### How are you deploying Directus?

Docker via Rancher

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #8932

## Before

Fields in groups are sorted wrongly in advanced filter (`g1` meant `group 1` etc):

chrome_aVMvE0lPjg

## After

The ordering are now correct. ~~with groups acting as dividers based on the suggestion here: https://github.com/directus/directus/issues/8932#issuecomment-969531943~~

Update: reverted divider changes for now, refer below comments for more detail.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I'm wondering if there's a slightly different way to highlight the hierarchy, without having to resort to fully nested sub-groups (like for relational fields). If you have any nested groups, the current solution quickly loses it usefulness:

CleanShot 2021-12-01 at 16 50 55@2x

Maybe indenting groups slightly could be enough to add the organization I'm looking for:

CleanShot 2021-12-01 at 16 52 48@2x

Thoughts @benhaynes?

**Comment by bcartier** [comment]
Would it be possible to reuse the nesting user interface that is use when creating/managing the field groups themselves? A combination of vertical border, darkening background? (the drag handle would be left out, of course)
 
Screen Shot 2021-12-08 at 2 32 46 PM

**Comment by rijkvanzanten** [comment]
@bcartier Yeah! I was aiming at something similar. It becomes a little tricky once you deal with nested groups, as it's a very small space to work with. We might start with just doing the proper ordering, as that's already a tremendous improvement, and then do another cycle on seeing how we can improve that UX to hint at the nested nature of the fields.

**Comment by bcartier** [comment]
> We might start with just doing the proper ordering

That would be great! I agree, it's really two separate issues. Would love to see the order implemented as a first step.

**Comment by azrikahar** [comment]
Reverted the divider changes 👍

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
