### PR TITLE
Port the app to Vue 3

### PR DESCRIPTION
**Pull request by nickrum**
⚠️  Depending on the complexity of your custom (app) extensions, this change might introduce some breaking changes. Please check https://v3.vuejs.org/guide/migration/introduction.html#breaking-changes to confirm any and all changes that might apply to your custom extension. 

---

Missing:

- [x] Fix `v-model`
- [x] `emits` option
- [x] Migrate Vue Router
- [x] Migrate Vue Draggable
- [x] Replace vue-i18n `i18n.global` with [`useI18n`](https://vue-i18n.intlify.dev/guide/advanced/composition.html)
- [x] Refactor layouts to get rid of teleport/portal
- [x] Refactor modules to register routes as children
- [x] Fix router-link exact prop
- [x] Fix `package.json`
  - [x] gitHead (lerna)
  - [x] scripts
- [x] Re-add readme/license/etc

### CODE REVIEW

**Comment by benhaynes** [comment]
Amazing!! ⚡ 😍 ⚡

**Comment by ernst86913** [comment]
@rijkvanzanten Hi Rijk, is there any reason why Vuetify is not used as component library? E.g. License,.... ?  Thanks, Roman

**Comment by Nitwel** [comment]
We decided not to go with Vuetify because there where some things that vuetify didn't provide which we needed.
Which doesn't mean that we didn't take a lot of inspiration from them and their components.

**Comment by rijkvanzanten** [comment]
In input-rich-text-md, the watcher is messing with the cursor position in code mirror somehow

**Pull request merged**
