### PR TITLE
fix syntax in oas

### LINKED ISSUE #14869: OAS does not validate against the OpenAPI v3.0 schema
### Describe the Bug

The downloaded OAS from `/server/specs/oas` does not validate against the OpenAPI v3.0 schema

### To Reproduce

```
mkdir /tmp/php-openapi; cd $_
curl -XGET -H 'Authorization: Bearer MyToken' https://directus.example.com/server/specs/oas > schema.json
docker run --rm -v $(pwd):/srv -w /srv --name directus-val thecodingmachine/php:8.1-v4-cli composer req cebe/php-openapi
docker run --rm -v $(pwd):/srv -w /srv --name directus-val thecodingmachine/php:8.1-v4-cli vendor/bin/php-openapi validate schema.json
```
or with any other schema validator

### Errors Shown

```
Errors found while reading the API description from schema.json:
- [/paths/~1utils~1hash~1generate/post/requestBody/content/application~1json/schema/properties/string] property 'required' must be array, but boolean given.
- [/paths/~1utils~1hash~1verify/post/requestBody/content/application~1json/schema/properties/string] property 'required' must be array, but boolean given.
- [/paths/~1utils~1hash~1verify/post/requestBody/content/application~1json/schema/properties/hash] property 'required' must be array, but boolean given.
- [/paths/~1utils~1export~1{collection}/post/requestBody/content/application~1json/schema/properties/format] property 'required' must be array, but boolean given.
- [/paths/~1utils~1export~1{collection}/post/requestBody/content/application~1json/schema/properties/query] Reference: additional properties are given. Only $ref should be set in a Reference Object.
- [/paths/~1utils~1export~1{collection}/post/requestBody/content/application~1json/schema/properties/file] Reference: additional properties are given. Only $ref should be set in a Reference Object.
- [/paths/~1items~1app/get/responses/200/content/application~1json/schema/properties/data/items] Reference: additional properties are given. Only $ref should be set in a Reference Object.
- [/paths/~1items~1app~1{id}/get/responses/200/content/application~1json/schema/properties/data] Reference: additional properties are given. Only $ref should be set in a Reference Object.
- [/paths/~1items~1app~1{id}/patch/requestBody/content/application~1json/schema] Reference: additional properties are given. Only $ref should be set in a Reference Object.
- [/paths/~1items~1app~1{id}/patch/responses/200/content/application~1json/schema/properties/data] Reference: additional properties are given. Only $ref should be set in a Reference Object.
OpenAPI v3.0 schema violations:
- [paths./utils/hash/generate.post.requestBody.content.application/json.schema.properties.string.required] Boolean value found, but an array is required
- [paths./utils/hash/verify.post.requestBody.content.application/json.schema.properties.string.required] Boolean value found, but an array is required
- [paths./utils/hash/verify.post.requestBody.content.application/json.schema.properties.hash.required] Boolean value found, but an array is required
- [paths./utils/export/{collection}.post.requestBody.content.application/json.schema.properties.format.required] Boolean value found, but an array is required
- [components] The property definitions is not defined and the definition does not allow additional properties
```

Applying some fixes results in the following diff:
```diff
--- schema-unfixed.json	2022-08-05 10:29:08.031631929 +0200
+++ schema.json	2022-08-05 10:31:20.729868189 +0200
@@ -740,10 +740,12 @@
                 "properties": {
                   "string": {
                     "description": "String to hash.",
-                    "type": "string",
-                    "required": true
+                    "type": "string"
                   }
-                }
+                },
+                "required": [
+                  "string"
+                ]
               }
             }
           }
@@ -783,15 +785,17 @@
                 "properties": {
                   "string": {
                     "description": "String to hash.",
-                    "type": "string",
-                    "required": true
+                    "type": "string"
                   },
                   "hash": {
                     "description": "Hash you want to verify against.",
-                    "type": "string",
-                    "required": true
+                    "type": "string"
                   }
-                }
+                },
+                "required": [
+                  "string",
+                  "hash"
+                ]
               }
             }
           }
@@ -932,21 +936,20 @@
                       "csv",
                       "xml",
                       "json"
-                    ],
-                    "required": true
+                    ]
                   },
                   "query": {
-                    "description": "The query object to use for the export",
-                    "required": true,
-                    "$ref": "#/components/definitions/Query"
+                    "$ref": "#/components/schema/Query"
                   },
                   "file": {
-                    "description": "Partial file object to tweak where / how the export file is saved",
-                    "type": "object",
-                    "required": true,
                     "$ref": "#/components/schemas/Files"
                   }
-                }
+                },
+                "required": [
+                  "format",
+                  "query",
+                  "file"
+                ]
               }
             }
           }
@@ -1119,7 +1122,6 @@
                     "data": {
                       "type": "array",
                       "items": {
-                        "type": "object",
                         "$ref": "#/components/schemas/ItemsApp"
                       }
                     },
@@ -1183,7 +1185,6 @@
                   "type": "object",
                   "properties": {
                     "data": {
-                      "type": "object",
                       "$ref": "#/components/schemas/ItemsApp"
                     }
                   }
@@ -1239,7 +1240,6 @@
           "content": {
             "application/json": {
               "schema": {
-                "type": "object",
                 "$ref": "#/components/schemas/ItemsApp"
               }
             }
@@ -1254,7 +1254,6 @@
                   "type": "object",
                   "properties": {
                     "data": {
-                      "type": "object",
                       "$ref": "#/components/schemas/ItemsApp"
                     }
                   }
@@ -1271,7 +1270,7 @@
         }
       }
     },
-   "/activity": {
+    "/activity": {
       "get": {
         "operationId": "getActivities",
         "summary": "List Activity Actions",
@@ -3340,6 +3339,65 @@
   },
   "components": {
     "schemas": {
+      "Query": {
+        "type": "object",
+        "properties": {
+          "fields": {
+            "type": "array",
+            "items": {
+              "type": "string"
+            },
+            "description": "Control what fields are being returned in the object.",
+            "example": [
+              "*",
+              "*.*"
+            ]
+          },
+          "filter": {
+            "type": "object",
+            "example": {
+              "<field>": {
+                "<operator>": "<value>"
+              }
+            }
+          },
+          "search": {
+            "description": "Filter by items that contain the given search query in one of their fields.",
+            "type": "string"
+          },
+          "sort": {
+            "type": "array",
+            "items": {
+              "type": "string"
+            },
+            "description": "How to sort the returned items.",
+            "example": [
+              "-date_created"
+            ]
+          },
+          "limit": {
+            "type": "number",
+            "description": "Set the maximum number of items that will be returned"
+          },
+          "offset": {
+            "type": "number",
+            "description": "How many items to skip when fetching data."
+          },
+          "page": {
+            "type": "number",
+            "description": "Cursor for use in pagination. Often used in combination with limit."
+          },
+          "deep": {
+            "type": "object",
+            "description": "Deep allows you to set any of the other query parameters on a nested relational dataset.",
+            "example": {
+              "related_articles": {
+                "_limit": 3
+              }
+            }
+          }
+        }
+      },
       "ItemsApp": {
         "type": "object",
         "properties": {
@@ -4764,67 +4822,6 @@
         }
       }
     },
-    "definitions": {
-      "Query": {
-        "type": "object",
-        "properties": {
-          "fields": {
-            "type": "array",
-            "items": {
-              "type": "string"
-            },
-            "description": "Control what fields are being returned in the object.",
-            "example": [
-              "*",
-              "*.*"
-            ]
-          },
-          "filter": {
-            "type": "object",
-            "example": {
-              "<field>": {
-                "<operator>": "<value>"
-              }
-            }
-          },
-          "search": {
-            "description": "Filter by items that contain the given search query in one of their fields.",
-            "type": "string"
-          },
-          "sort": {
-            "type": "array",
-            "items": {
-              "type": "string"
-            },
-            "description": "How to sort the returned items.",
-            "example": [
-              "-date_created"
-            ]
-          },
-          "limit": {
-            "type": "number",
-            "description": "Set the maximum number of items that will be returned"
-          },
-          "offset": {
-            "type": "number",
-            "description": "How many items to skip when fetching data."
-          },
-          "page": {
-            "type": "number",
-            "description": "Cursor for use in pagination. Often used in combination with limit."
-          },
-          "deep": {
-            "type": "object",
-            "description": "Deep allows you to set any of the other query parameters on a nested relational dataset.",
-            "example": {
-              "related_articles": {
-                "_limit": 3
-              }
-            }
-          }
-        }
-      }
-    },
     "responses": {
       "NotFoundError": {
         "description": "Error: Not found.",
```

### What version of Directus are you using?

9.15.0

### What version of Node.js are you using?

N/A

### What database are you using?

MySQL

### What browser are you using?

N/A

### How are you deploying Directus?

docker

### LINKED ISSUE #16183: OAS endpoint generates invalid spec
### Describe the Bug

It is impossible to generate valid api clients with the spec which is generated, because it is invalid. 

image

I don't know where this is coming from or who didn't read the spec, but this has to be moved to schemas. https://swagger.io/specification/#components-object No generator can do anything with that without 100 workarounds and disabling of validity checks.

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 14, Warning count: 0
Errors: 
	-attribute paths.'/utils/export/{collection}'(post).requestBody.content.'application/json'.schema.required is not of type `array`
	-attribute paths.'/users'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/files'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/flows'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/utils/export/{collection}'(post).requestBody.content.'application/json'.schema.#/components/definitions/Query is missing
	-attribute paths.'/presets'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/utils/hash/generate'(post).requestBody.content.'application/json'.schema.required is not of type `array`
	-attribute paths.'/folders'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/utils/hash/verify'(post).requestBody.content.'application/json'.schema.required is not of type `array`
	-attribute paths.'/items/blogs'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/activity'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute components.definitions is unexpected
	-attribute paths.'/permissions'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/roles'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

I'm sorry to be passive aggressive here but it is just tiresome. Excuse me, I now have to go to the next project, the actual OAS generator, to file at least 3 issues there too or fix them myself directly.

### To Reproduce

Just call /server/specs/oas with any user who has access to this endpoint

### Errors Shown

_No response_

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

irrelevant

### What database are you using?

irrelevant

### What browser are you using?

irrelevant

### How are you deploying Directus?

irrelevant

### LINKED ISSUE #16474: Open Api Spec can't be validated -> client code gen ends in broken client
### Describe the Bug

If you take the open api spec from a fresh directus install and put it into https://editor.swagger.io, you see that there are some structural errors... Most have to do with wrong syntax for required properties, which (only) leads to missing required info on that fields. But a wrong syntax in the components section, leads to a complete broken client when generated out of this spec, because references are missing.

### To Reproduce

- Install directus
- get open api file
- validate the file (i.e. on https://editor.swagger.io)
=> see errors

### Errors Shown

Most significant error:

Structural error at components
should NOT have additional properties additionalProperty: definitions
Jump to line 5735

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.18.0

### What database are you using?

mysql

### What browser are you using?

irrelevant

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by cf-ts**
## Description

I made some minor changes in the OAS files to make them syntactically correct, they now validate against the swagger online editor and a api client (I tested angular-typescript) can be created out of the spec, which ended in a broken client before these changes...

This PR should fix all errors mentioned in these related tickets:

Fixes https://github.com/directus/directus/issues/16474
Fixes https://github.com/directus/directus/issues/14869
Fixes https://github.com/directus/directus/issues/16183

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

(I did not change any code, just the yaml spec files...)

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by NickUfer** [comment]
This still doesn't seem to be correct.
image

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 12, Warning count: 0
Errors: 
        -attribute paths.'/revisions'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/permissions'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/users'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/folders'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/activity'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/files'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/operations'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/presets'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/flows'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/items/blogs'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/roles'(get).responses.200.content.'application/json'.schema.#/components/schemas/x-metadata is missing
        -attribute paths.'/utils/export/{collection}'(post).requestBody.content.'application/json'.schema.#/components/schemas/Query is missing

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

Query and x-metadata are now completely gone. Any advice? Caches were already cleared. This happened already once with `Files`, was just not generated. After removing and adding the same group it worked again, but this time not even this helps

**Comment by NickUfer** [comment]
How was this tested exactly? To me this seems impossible work correctly.

During generation `/components/schemas` is set to `{}` 
https://github.com/directus/directus/blob/2d104e933b5e582caa5b72371231bab3e1d05357/api/src/services/specifications.ts#L314-L325

And only schemas which have the exact same name as a collection are added back.

https://github.com/directus/directus/blob/2d104e933b5e582caa5b72371231bab3e1d05357/api/src/services/specifications.ts#L328-L363
`Query` and `x-metadata` belong to no collection.

I think we need something like

```typescript
components.schemas = {};
components.schemas.Query = cloneDeep(openapi.components.Query);
components.schemas.x-metadata = cloneDeep(openapi.components.x-metadata);
```

**Comment by cf-ts** [comment]
@NickUfer  I did not change Code of the extension, but the yaml files of the base api description... I moved "x-metadata" to the schema section, same with "query" and changed the references, but then it seems that the generator is changing the file again in a way I did not suppose... I tested my changes in the file but was not able to run the project as a whole when making the pr... I will look into getting the project to run and try to fix it correctly!

**Comment by cf-ts** [comment]
Problem ist that I can't buid the project, I get an error in this stage:
`app build$ vite build
│ vite v3.1.8 building for production...
│ transforming...
└─ Running...`

A JS out of mem error happens there and I don't know what to do... I'm running on Mac Air M1, maybe I should try my Mac Book Pro Intel with more RAM...

`│ <--- Last few GCs --->
│ [5463:0x140008000]    30074 ms: Mark-sweep 2010.3 (2082.4) -> 1994.5 (2081.9) MB, 907.8 / 0.0 ms  (average mu = 0.200, current mu = 0.041) allocation failure scavenge might not succeed
│ [5463:0x140008000]    31044 ms: Mark-sweep 2010.4 (2081.9) -> 1994.7 (2082.2) MB, 887.4 / 0.0 ms  (average mu = 0.146, current mu = 0.085) allocation failure scavenge might not succeed
│ <--- JS stacktrace --->
│ FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
│  1: 0x10496dc84 node::Abort() [/usr/local/bin/node]...`

**Comment by cf-ts** [comment]
@NickUfer But after looking into the generator more closely it seems that you are right, I did not see that schema section of the static file is dropped completely... Im sorry! So we would habe to add these two hard coded and every new schema not belonging to a collection... maybe there is a more generic way! @rijkvanzanten  I'm new to directus and therefore don't have such a good overview... But to me it seems that maybe we should add all models which do not have a "x-collection" record because they get thrown away!?

**Comment by cf-ts** [comment]
Ok, I managed to get directus running in local dev environment with simply more memory for the node process (NODE_OPTIONS=--max-old-space-size=7168)...

I don't know if my solution is better and won't open a new PR, but add it as a topic for discussion to @NickUfer PR and new Issue...

**Pull request merged**
