### PR TITLE
Added extra environment setting for sharp processing of invalid images

### LINKED ISSUE #16794: Sharp causing trouble with JPGs created on certain mobile devices
### Describe the Bug

Hi, I hate to trouble you with this but I've been trying to find the source of this bug for a while and I think I have it nailed down. I just don't know what to do about it.

I have a project that people upload photos of a weekly art challenge, and the users are very non-technical people. Some don't even have computers, just phones. I have been fighting about 1-2% of my users not getting past my upload form's error checking process. For the longest time I thought it was me or my users, but it looks like it's Sharp and Samsung's JPG creation not getting a long.

I know this is is Directus' issue board, but that's where I am having the problem and I don't know if there is anything I can do to help.

I found this bug report: https://github.com/lovell/sharp/issues/1578 talking about the issue.

The real issue comes when I try to convert the image to webp. The API errors and sends back a blank image.

### To Reproduce

This is a bit tricky, but you need to upload a JPG created on a samsung phone, here is one that caused the error: 
amy

I have confirmed that the above image was generated with Samsung Galaxy S21 Ultra.

Then you need to try and convert the image to webp via the API's image transformations.

This will cause an error in the API and deliver a blank image to the user.

### Errors Shown

image

image

```
Error: VipsJpeg: Invalid SOS parameters for sequential JPEG  

"message": "E_UNKNOWN: An unknown error happened with the file f6fdcdce-b7bc-48f8-a3d5-9cced867da75__165facd2baf7377772b0045e3f5b9a6644f04806.webp.\n\nError code: Error\nOriginal stack:
```

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.17.0

### What database are you using?

postgres 12

### What browser are you using?

chrome, firefox

### How are you deploying Directus?

self install, Ubuntu 22.04.1 LTS, manged by pm2

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

Some (invalid) images were not being rendered by Sharp because it fails on invalid images by default (which makes sense).
Instead of parsing invalid images by default i've introduced a new environment variable used to configure the fail level of Sharp directly. The `failOn` option of Sharp (https://sharp.pixelplumbing.com/api-constructor#parameters) can take the following values `none`, `truncated`,`error`,`warning` (default). Keeping the default value as it is now but allowing for people to set:
```
ASSETS_INVALID_IMAGE_SENSITIVITY_LEVEL="none"
```
allowing for invalid image processing if they so choose

Fixes #16794 
Fixes ENG-110

## Type of Change

- [ ] Bugfix
- [X] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [X] Documentation was added/updated. PR: https://github.com/directus/docs/pull/234

### CODE REVIEW

**Comment by paescuj** [comment]
Nice!

Just to be sure: Could this have any undesirable side effects? E.g. if set to `none` and image still fails to be transformed -> error is thrown and server crashes in the worst case. If so, would a `try...catch` help (if not already there)?

**Comment by StephenGunn** [comment]
Thank you, this is a great solution to a stupid problem.

**Comment by br41nslug** [comment]
> Just to be sure: Could this have any undesirable side effects?

Yeah dealing with invalid images could come with a risk of crashing or unexpected errors i suppose but it is not explicitly mentioned on the Sharp docs. This is also why i didnt want to change the default behavior for this but still allow it at your own risk.

**Comment by paescuj** [comment]
> Yeah dealing with invalid images could come with a risk of crashing or unexpected errors i suppose but it is not explicitly mentioned on the Sharp docs. This is also why i didnt want to change the default behavior for this but still allow it at your own risk.

Just saw that this would probably be caught on these lines 👍 

https://github.com/directus/directus/blob/877971ed4cde13b031559a9775db7f0cf1055608/api/src/services/assets.ts#L161-L164

**Comment by rijkvanzanten** [comment]
Looks great! <3 Lets workshop the name a bit though, `ASSETS_FAIL_ON_INVALID_IMAGE` is not _quite_ what the value is. The value controls the "strictness" of dealing with invalid images. Maybe we should call it something like `ASSETS_INVALID_IMAGES_SENSITIVITY`? So it matches the description from sharp a bit better too: _sensitivity to invalid images_

**Comment by paescuj** [comment]
> Looks great! <3 Lets workshop the name a bit though, `ASSETS_FAIL_ON_INVALID_IMAGE` is not _quite_ what the value is. The value controls the "strictness" of dealing with invalid images. Maybe we should call it something like `ASSETS_INVALID_IMAGES_SENSITIVITY`? So it matches the description from sharp a bit better too: _sensitivity to invalid images_

Good point 👍 I like the one you just proposed!

**Comment by paescuj** [comment]
> Naming things is hard XD [...]

 "There are only two hard things in Computer Science: cache invalidation and naming things." -- Phil Karlton
😆

> [...] tbh neither feels super fitting with the available values
> ```
> ASSETS_INVALID_IMAGES_SENSITIVITY="warning"
> ASSETS_INVALID_IMAGES_SENSITIVITY="none"
> ASSETS_FAIL_ON_INVALID_IMAGE="warning"
> ASSETS_FAIL_ON_INVALID_IMAGE="none"
> ```
> 
> But i'll happily change to `ASSETS_INVALID_IMAGES_SENSITIVITY` if that makes more sense to others 😄

I get your point! Would something with `LEVEL` be a better fit, e.g. `ASSETS_INVALID_IMAGES_SENSITIVITY`?
`ASSETS_INVALID_IMAGES_SENSITIVITY` would be okay for me, though. (We could refer to `sharp` in the docs)

**Comment by rijkvanzanten** [comment]
Sharp is calling it `failOn`, which definitely doesn't feel right 👀 

> options.failOn [string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String) level of sensitivity to invalid images, one of (in order of sensitivity): 'none' (least), 'truncated', 'error' or 'warning' (most), highers level imply lower levels. (optional, default 'warning')

It's effectively the "level of sensitivity" of dealing with invalid images, so maybe `ASSETS_INVALID_IMAGE_SENSITIVITY_LEVEL`? Bit on the long side, but it's a power user / edge case type of thing, so not the end of the world

**Comment by paescuj** [comment]
> Sharp is calling it `failOn`, which definitely doesn't feel right 👀

True 👀 

> It's effectively the "level of sensitivity" of dealing with invalid images, so maybe `ASSETS_INVALID_IMAGE_SENSITIVITY_LEVEL`? Bit on the long side, but it's a power user / edge case type of thing, so not the end of the world

I'd be happy with this one 👍🎉

**Review by licitdev — APPROVED** [review]
Tested this fix to work as intended. 💯

**Pull request merged**
