### PR TITLE
explicit CSV separator for Excel - fixes #21374

### LINKED ISSUE #21374: Add export options to CSV
### Describe the Improvement

When exporting CSVs, it's currently not possible to certain options like delimiter or "wrap in quotes". This hinders the usability, as certain copies of spreadsheet software require some of these options to be set in specific ways.

### PR DESCRIPTION
**Pull request by vwasteels**
## Scope

What's changed:

- add ```sep=,``` in CSV exports to make it automatically detected by Excel

## Potential Risks / Drawbacks

- verify with other CSV reader (Number, Google sheet) that it still opens correctly

## Review Notes / Questions

- 

---

Fixes #21374

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Thanks for the PR @vwasteels! It looks like the commits themselves were created anonymously, which causes some havoc in our CI pipeline. Mind resolving that? Usually it's because `git` on your computer isn't configured with an email address. Please see https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address for more information 🙂 

Once that's resolved I'm happy to merge this as the changes LGTM 🚀

**Comment by hanneskuettner** [comment]
I don't think this is a change we should put in to Directus, at least not in this current form of unconditionally adding the a `sep=,` line. 

This seems to be a highly Excel specific feature and not everyone uses Excel to view and process these files. The de-facto CSV standard does not mention this convention [^1].

There are CSV parsers out there that are used with this file, which will choke on this custom syntax, for example the Python standard library CSV parser:

```python
import csv
from io import StringIO
r = csv.reader(StringIO("""sep=,
foo,bar
1,2
2,3
"""))

print([l for l in r])
>> [['sep=', ''], ['foo', 'bar'], ['1', '2'], ['2', '3']]
```

So simply adding this line to all CSV output is an unwanted, breaking change.

[^1]: https://www.rfc-editor.org/rfc/rfc4180

**Comment by hanneskuettner** [comment]
I will close this issue, as this is a too opinionated breaking change that in addition does not really fix the linked issue https://github.com/directus/directus/issues/21374.

**Comment by vwasteels** [comment]
sorry last comment were mine I was connected with my bot account

**Pull request closed without merging**
