### PR TITLE
Notifications fix & update

### LINKED ISSUE #13727: Notifications go to page not found null/null
### Describe the Bug

I have created a "Flow" (admin/settings/flows).  As the result of a the flow a user notification is created.

The notification generates and I see it in the side panel.  However, when I click the title of the notification is takes me to a page not found with an address of http://localhost:8055/admin/content/null/null.

This is a clean project.  The only thing I have done is create it, and add this flow.

### To Reproduce

1. Create a flow.
2. trigger with server start
3. Set operation to Send Notification
4. Add a user id etc.
5. Add a title and message.
6. Save flow.
7. In this case restart server.

The notice bell has a red indicator.  When clicked the side panel opens and shows the notification.  When the notification is clicked I get the error page.

### Errors Shown

none

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

16.15.1

### What database are you using?

SQLite

### What browser are you using?

Safari/Chrome/Fire Fox

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by JasonAGross**
## Update the notification system to provide new functionality and fix a bug.

This update addresses the issue outlined here: https://github.com/directus/directus/issues/13727 but also provides some improvements around the notification system as a whole. It should also address this comment from another open PR: https://github.com/directus/directus/pull/15806#issuecomment-1266833670

- Notifications now have a 'read' property to indicate whether a notification has been viewed or not
- The notification badge in the navigation bar will now reflect the number of unread messages, as opposed to all messages in the inbox
- If a notification comes from a collection comment, the user will still be redirected to that collection. Otherwise, they can click a notification to see the detail message associated with it. This is the scenario when notifications are sent as a result of a flow/operation. 

Fixes #13727
Closes #15806

## Type of Change

- [x] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by JasonAGross** [comment]
I tried opening a discussion on this here: https://github.com/directus/directus/discussions/16184 but didn't get any feedback. I'm trying to get this bug fixed so we can implement a notification flow for a project I'm working on.

**Comment by Rifqi-Irfansyah** [comment]
i am confused, how to aplly to my project

**Comment by danieljwestman** [comment]
Any progress in this great improvement? This will make the notifications system a lot more useful and intuitive.

**Comment by Rifqi-Irfansyah** [comment]
how to upgrade directus version?

**Comment by JasonAGross** [comment]
> @JasonAGross Any progress in this great improvement? This will make the notifications system a lot more useful and intuitive.

@danieljwestman There is nothing more for me to do here right now. Waiting for feedback or approval from the core team.

**Comment by danieljwestman** [comment]
> @danieljwestman There is nothing more for me to do here right now. Waiting for feedback or approval from the core team.

Okay, 2bad it doesn't get the attention it deserves/needs...

**Comment by danieljwestman** [comment]
@rijkvanzanten Sorry for pinging you, but do you think this PR will get some light soon? The notification system is an important part of the platform but it needs more love and some functionality was left out in the first implementation. This PR seems to help a lot!

**Comment by rijkvanzanten** [comment]
https://github.com/directus/directus/pull/15806 implemented a (small yet big qol) initial fix. Lets move the suggested updates around a read-status (and any other improvements!) to [a feature request discussion](https://github.com/directus/directus/discussions/new?category=feature-requests) first so we can discuss the goals and design details before switching to implementation/review/qa 💪🏻

**Pull request closed without merging**
