### PR TITLE
Prioritize policies attached to users

### PR DESCRIPTION
**Pull request by paescuj**
## Scope

Ensure policies that are directly attached to a user are prioritized over attachments via role.

For that, we need to be able to define the order of `NULL` values, because those always need to come last across DB vendors. Support for defining that order is kept internal for now - we may want to expose later on.

## Potential Risks / Drawbacks

None

## Review Notes / Questions

None

---

Related to https://github.com/directus/directus/pull/22773#issuecomment-2177785391 & internal discussion

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Why does the order matter?

**Comment by hanneskuettner** [comment]
Because the order of policies influences the order that presets are applied, and we want to be consistent there. And the whole `nulls` thing is needed, because, sadly, different DB vendors order nulls differently by default.

**Comment by rijkvanzanten** [comment]
Ahh forgot about presets. Ty!

**Comment by paescuj** [comment]
@hanneskuettner realized that we additionally need to consider the order of parent and child roles, which is why we finally opted for a solution in JS. Closing this pull request in favor of #22967.

**Pull request closed without merging**
