### PR TITLE
Add Archive sidebar component

### LINKED ISSUE #9523: No way to "undo" show archived items
On 9.0.0, when you right-click the content collection in the nav, you can choose "Show Archived Items". There are a few problems here, such as clicking it again doesn't change anything (so it's unclear how to go back), and you can't see archived + normal items at the same time.

I recommend moving this to a dedicated "Archive" sidebar component (`archive` icon, below _Layout Options_), with either a radio list or dropdown with:

* Show Items
* Show Archive
* Show Items + Archive

This is easier to find, easier to understand, and offers more control.

### PR DESCRIPTION
**Pull request by azrikahar**
Resolves #9523.

Changes made:

- Removed "Show Archived Items" from collection context menu
- Added "Archive" sidebar component
  - Doesn't show for collection without app filter configured.
  - Uses router query like how it was, just with different values.
- Fixed minor UX issue where the archive dialog changed before the change is made, and the notification is still showing "deleted" when we are unarchiving instead of archiving:

    https://user-images.githubusercontent.com/42867097/146167288-44294171-9149-4035-b4f1-6016a8d2be1f.mp4
- Minor update to docs to reflect this change.

## Result

https://user-images.githubusercontent.com/42867097/146167559-7ae70820-23d2-4927-b229-a181f7154a8a.mp4

## Uncertainties

- Not super sure is the title `Filter` for selecting show items and/or archived items is ok, or if there's a better existing/new translated text for it.
- Maybe the route query can be `include_archived` instead of `archived`? sticked with the latter for now as the existing one was `archive`.

### CODE REVIEW

**Comment by benhaynes** [comment]
Love it!! Thank you, @azrikahar. A few thoughts/questions:

* Let's just remove the "Filter" field header and just show the dropdown
* When there are archived items, should we see a count on the sidebar title? (eg: `Archive (27)`) It can be paginated so it shows `100+` above the page count. Probably too much to add these numbers into the dropdown options?
* I like the badge for highlighting when this feature is on... nice work!
* Let's change the dropdown options to:
    * `Show Active Items` (no query string)
    * `Show Archived Items` (`?archived`)
    * `Show All Items` (`?all`)

@rijkvanzanten — thoughts?

**Comment by rijkvanzanten** [comment]
Like it!

Do we wanna try radio buttons in here instead of the dropdown? 🤔 Seeing that's the only option we have

**Comment by benhaynes** [comment]
That could work, as long as all the options stack nicely and don't take up too much vertical room. 👍

**Comment by azrikahar** [comment]
Here's the updated version with changes mentioned above:

https://user-images.githubusercontent.com/42867097/146326363-273dc509-e4ee-4619-9c29-5042b9b69543.mp4

> When there are archived items, should we see a count on the sidebar title? (eg: `Archive (27)`) It can be paginated so it shows `100+` above the page count. Probably too much to add these numbers into the dropdown options?

Does this mean showing total archived items per page when we change to another page? I assumed it meant the running total of archived items (not paginated), but I'm not sure am I understanding `It can be paginated so it shows 100+ above the page count` correctly 🤔

**Comment by benhaynes** [comment]
I was thinking it shows the total number of archived items, but it could make sense to base that on any active filters too. As for pagination, I just didn't know if it was easier to max out that count instead of showing a huge number. Also, thinking of about that in terms of performance overhead.

**Comment by azrikahar** [comment]
Just showing total number of archived items makes sense as well! Also not sure how much impact that is in terms of performance.

I did check back the revisions change and it does show total count (though it uses filter_count, maybe we can use aggregate count instead since we don't need the actual records). I believe this is what we're going for right?

video in this link: https://github.com/directus/directus/pull/6303#issuecomment-921954941

**Comment by benhaynes** [comment]
Good point! I actually like that you can see the Revision Count on the icon... do we want to try going that route? I know @rijkvanzanten might not think it's a good idea, but let's quickly discuss before merging.

**Comment by rijkvanzanten** [comment]
All I'm worried about is that it might be a bit sensory overload if every sidebar detail in there is grabbing attention with one of those badges 🤔 

We can go ahead with it for now though, and then adjust later if/when it's too much

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
