### PR TITLE
Change token and auth handling behavior.

### LINKED ISSUE #4883: LocalStorage auth_token, auth_refresh_token, and auth_expires are not removed on expiration
1) The issue and what you expected to happen
- In old SDK, those 3 tokens are removed when we leave the browser for the period time of ACCESS_TOKEN_TTL set in the Directus API. But in this new SDK, those tokens still persist in localstorage even with refresh. I always get `Token expired` error because my app still trying sending the old token to the API url. I need to manually remove them to fix it. Only, manual `await directus.auth.logout()` clears the tokens.

My current workaround is to always run the `directus.auth.refresh` along with the first time set in the login option.

2) Exact steps to reproduce this issue
- Update Directus to the latest v9.0.0-rc.54
- Replace @directus/sdk-js to @directus/sdk
- Rewrite the auth method as described here: https://docs.directus.io/reference/sdk/#auth
- I am using mode: 'json' and LocalStorage
- Set the API ACCESS_TOKEN_TTL to 1 minute so I can see the issue faster

3) Your environment:
    What version of Directus you are using: v9.0.0-rc.54
    Which DBMS are you using: MariaDB
    Which deployment are you using: npx
    What browser are you using: Chrome 89

### PR DESCRIPTION
**Pull request by WoLfulus**
This changes how SDK behaves a little:

- Requests will try to refresh the token first
- Concurrent/parallel requests are going to hold until the first refresh request ends and use it's resolve/rejection instead of dispatching a request
- Default auto refresh time set to 30sec when not specified
- Adds flags to the transport requests to enable/disable auto refresh and if the authorization headers should be sent or not

Closes #4883
Closes #4979

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by joselcvarela** [comment]
@rijkvanzanten milestone shouldn't be rc.61 ?

**Comment by rijkvanzanten** [comment]
@joselcvarela This PR made it into the rc60 milestone yesterday, so no i don't think so

**Comment by joselcvarela** [comment]
Sorry, my bad. 😢

**Comment by rijkvanzanten** [comment]
Np!

**Comment by WoLfulus** [comment]
@joselcvarela wait for .61 to use the SDK though, it landed with a small typo that makes it impossible to use authenticated routes.

**Comment by roggan87** [comment]
@WoLfulus is this PR also closing #3940? I'm specifically thinking of the proposed solution "We should come up with a way where it tries re-authenticating on first user interaction after an idle time."

**Comment by WoLfulus** [comment]
If you have an application that uses Directus, that will be solved, yes, but the app itself doesn't use the SDK, so unfortunately this won't be closed for now.

**Pull request merged**
