### PR TITLE
:sparkles: Postgres support for views

### PR DESCRIPTION
**Pull request by arnaud**
## Description

Directus extra postgres support for:

- Views
- Materialized Views
- Foreign Tables

RFC Proposal @ #17265
Fixes #3097

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

## Tests

Given the following data structure:

<details><summary>SQL</summary>

```sql
CREATE TABLE authors (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  first_name VARCHAR,
  last_name VARCHAR,
  vip BOOLEAN,
  user_created uuid REFERENCES directus_users(id),
  date_created timestamp with time zone,
  user_updated uuid REFERENCES directus_users(id),
  date_updated timestamp with time zone
);
CREATE INDEX authors_vip ON authors (vip);
CREATE INDEX authors_user_created ON authors (user_created);
CREATE INDEX authors_user_updated ON authors (user_updated);
  
CREATE TABLE articles (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES authors(id),
  title VARCHAR,
  body TEXT,
  user_created uuid REFERENCES directus_users(id),
  date_created timestamp with time zone,
  user_updated uuid REFERENCES directus_users(id),
  date_updated timestamp with time zone
);
CREATE INDEX articles_vip_idx ON articles (author_id);

INSERT INTO authors (first_name, last_name, vip) VALUES
('James', 'Bond', TRUE),
('Jason', 'Bourne', FALSE),
('John', 'Wick', FALSE);

INSERT INTO articles (author_id, title, body) VALUES
(1, 'Tomorrow never dies', DEFAULT),
(3, 'Follow the white rabbit', DEFAULT),
(3, 'Come get some', 'Here comes a new challenger');

CREATE VIEW authors_vip AS SELECT * FROM authors WHERE vip;

CREATE VIEW articles_draft AS SELECT * FROM articles WHERE body IS NULL;
```

</details>

It produces the following:

| Create collections from pre-existing views | Create custom collections from Directus | Live preview the view definition |
|-|-|-|
| directus-20230116-support-for-views | directus-20230117-create-views | directus-20230118-preview-views |

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hi @arnaud! Thanks for your Draft PR! I do want to quickly point out the process for having features merged into the codebase outlined in our [contributing guideline](https://github.com/directus/directus/blob/main/contributing.md). In order for the core team to be able to maintain this change over time, we have to ensure that the feature is fully specced out, reviewed, and agreed upon by the core team, before doing the actual implementation. Otherwise, it becomes incredibly hard for the maintainers to review and merge the PR in a timely fashion, which means there's a big chance the PR will go stale and never ends up being merged into the core codebase 😬

**Comment by phayes** [comment]
When trying to compile this branch I'm getting the following errors:

```
> directus@9.22.4 build /opt/directus/api
> tsc --build && copyfiles "src/**/*.{yaml,liquid}" -u 1 dist

src/controllers/collections.ts:23:18 - error TS2339: Property 'fields' does not exist on type 'void'.

23    headers: data.fields.map((v) => {
                    ~~~~~~

src/controllers/collections.ts:23:30 - error TS7006: Parameter 'v' implicitly has an 'any' type.

23    headers: data.fields.map((v) => {
                                ~
```

**Comment by arnaud** [comment]
> When trying to compile this branch I'm getting the following errors:
> 
> ```
> > directus@9.22.4 build /opt/directus/api
> > tsc --build && copyfiles "src/**/*.{yaml,liquid}" -u 1 dist
> 
> src/controllers/collections.ts:23:18 - error TS2339: Property 'fields' does not exist on type 'void'.
> 
> 23    headers: data.fields.map((v) => {
>                     ~~~~~~
> 
> src/controllers/collections.ts:23:30 - error TS7006: Parameter 'v' implicitly has an 'any' type.
> 
> 23    headers: data.fields.map((v) => {
>                                 ~
> ```
> 
> This error does not exist on the upstream [3bd2c1c](https://github.com/directus/directus/commit/3bd2c1cfd35985416f26cd940f2eb23e37b43e2f), so it's definitely a commit in this PR that's causing this build issue.

Thanks @phayes, I just landed the missing typings.

**Comment by rijkvanzanten** [comment]
> I initially thought that the currently open discussion going on over at https://github.com/directus/directus/discussions/3097 was enough;
Would you prefer I initiate a new and dedicated discussion instead?

The goal of the discussion is to reach a full clear RFC consensus of exactly how something is supposed to be implemented, at which point we convert it into an Issue. Issues are the actionable items we actually want to implement (and thus accept PRs for). At this point, there's still a lot unclear about SQL Views, like how they should operate cross vendor, how one is going to configure them from the admin app, how they're interacted with in the APIs, etc.

**Comment by bamboowonder** [comment]
@rijkvanzanten  For what it is worth, from a user perspective.  I do respect that you have a (sane) process you need followed for PR's to be safely integrated into core.   Also that being cross db supported is really important to the spirit of the core Directus.
And, for us, not having View (and arbitrary sql query) support has been a show stopper for me rolling this platform out to multiple clients and committing more deeply to the Directus ecosystem.    I did enquire about paying for this feature to be built, unfortunately when I ran the numbers our small team just could not justify the cost.  And so we were left with wanting to implement Directus with more clients, but being hamstrung by having to also use other tools for working with views and adhoc sql queries.  Which is janky and so we haven't.
For now, we are going to fork it, test it, and if it is reasonably stable run with it.  I know it is a risk, and something I'm not doing lightly.  But this feature is that important for us.
And to put my money where my mouth is, I just became a $100 per month github sponsor, which coincidentally put you past the $1000 / mth goal line!!    
I know we are small fry, but as I roll out Directus to other clients, I'll commit to more per month.   
And having View support is what is enabling this to happen, finally.  :)  Thank you @arnaud  and @phayes as always.
referencing #3097

**Comment by rijkvanzanten** [comment]
Thanks @bamboowonder! ❤️

**Comment by arnaud** [comment]
Just landed a RFC proposal @ #17265.
@rijkvanzanten What do you think?

**Comment by rijkvanzanten** [comment]
> Just landed a RFC proposal @ #17265. @rijkvanzanten What do you think?

Left my thoughts on there! Lets keep discussing the proposal on that discussion. Once we reach consensus on the last remaining questions, we can convert it to an issue and go over to implementation 🚀

**Comment by rijkvanzanten** [comment]
Closing this in regards to https://github.com/directus/directus/pull/17174#issuecomment-1400661010. Lets focus on finalizing the intended goals first 👍🏻

**Pull request closed without merging**
