### PR TITLE
Improve keyboard navigation between elements

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
Add keyboard navigation and highlight visual feedback when tabbing between elements
1. v-checkbox
2. v-radio
3. input-rich-text-md interface

Allow close the popup  selector with Esc key for:
1. select-color interface
2. select-icon

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@benhaynes Could you review / come up with a standardized focus style we could use everywhere?

**Comment by benhaynes** [comment]
I have ideas for a `focus` style, but first, can't we re-use the hover style as the focus style?

**Comment by rijkvanzanten** [comment]
@dimitrov-adrian Could you post a screenshot/video or two of how this looks on your PR? 🙂

**Comment by dimitrov-adrian** [comment]
Yes, sure, I tried to reuse the hover style, just not every component has such

https://user-images.githubusercontent.com/1009639/140054568-25261f3c-a0b5-4240-a82e-8b1a07b46b24.mov


https://user-images.githubusercontent.com/1009639/140054576-c203628f-e054-4fe6-9cb5-a1f272d86275.mov


https://user-images.githubusercontent.com/1009639/140054579-b9c2f6a8-684e-4bc3-bd2f-c0678185eff6.mov

Also thinks that dropdowns could have list navigation between elements but it's not part of this scope as this mostly focus on functional behaviour.

**Comment by benhaynes** [comment]
This looks good to me! We could add an additional focus style which would also help with the things that don't have a good focus state. This is the style I'm thinking, but in `var(--primary)` with an opacity to make it lighter:

https://codepen.io/larimaza/pen/qBByEzX

**Comment by dimitrov-adrian** [comment]
> This looks good to me! We could add an additional focus style which would also help with the things that don't have a good focus state. This is the style I'm thinking, but in `var(--primary)` with an opacity to make it lighter:

Well this will be good, as the checked checkbox is hard to mark with color only, also the links are laking any hint that they are links, nor they are focused. Also the navigation (that changes the current route) elements like buttons, menu items... etc. have no such styles too, so it's bit harder to define if you for example are selected a link then the simple space or enter key could potentially do something unwanted.

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
