### PR TITLE
Allow authentication using MSSQL azure-active-directory-service-principal-secret

### PR DESCRIPTION
**Pull request by erickjth**
This PR allows connecting with a database in an Azure Cloud using the azure-active-directory-service-principal-secret type via tedious.

The clientId and clientSecret keys that are ignored from `DB_` in the settings passed to the Knex's MSSQL Dialect.

https://github.com/knex/knex/blob/master/lib/dialects/mssql/index.js#L36

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Seeing that that full config is passed to that knexConfig object, can't you already achieve this by simply doing

```
DB_CLIENT_ID="abc"
DB_CLIENT_SECRET="def"
```

?

**Comment by erickjth** [comment]
> Seeing that that full config is passed to that knexConfig object, can't you already achieve this by simply doing
> 
> ```
> DB_CLIENT_ID="abc"
> DB_CLIENT_SECRET="def"
> ```
> 
> ?

Looks like they  get ignored by this:

```
	const connectionConfig: Record<string, any> = getConfigFromEnv('DB_', [
		'DB_CLIENT',  <--------- because of the prefix
		'DB_SEARCH_PATH',
		'DB_CONNECTION_STRING',
		'DB_POOL',
		'DB_EXCLUDE_TABLES',
		'DB_VERSION',
	]);
```

**Comment by rijkvanzanten** [comment]
Ahh gotcha. In that case, we should either enhance that util function to accept a deny-list of keys (rather than a deny-list of prefixes), or use an `omit` to strip out those keys before passing it to the knex connection config 👍🏻

**Comment by erickjth** [comment]
Hi @rijkvanzanten, 

I am wondering why is the CI failing; unfortunately,  I can't see details of the error.  

Is that something related to the code itself or something in the infra?

Did it break something that I have not noticed 😅  ?

Thanks.

**Comment by rijkvanzanten** [comment]
@erickjth We've made a ton of changes in the E2E and unit test setups, so I think a quick merge from main to make sure this branch is up to date will resolve that 👍🏻

**Comment by erickjth** [comment]
hello @rijkvanzanten, is there something pending you consider needs to be fixed with this PR? 
Thanks!

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Comment by alexsonphoenix** [comment]
Hi team, how would I set up connection to MSSQL using service principle?

Is it done through an environment variable?

**Pull request merged**
