### PR TITLE
Update base theme of the App

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Updates the default primary colors to the new primary/secondary combination used across the Directus ecosystem. Also adds a new default login page background image

### CODE REVIEW

**Comment by abdonrd** [comment]
@rijkvanzanten the purple icons is something expected?

Screenshot 2022-03-06 at 00 15 19

**Comment by benhaynes** [comment]
@abdonrd — Yes, it only uses that color. If no custom color has been set. You can still make it gray, or any other color, within the collection settings.

**Comment by abdonrd** [comment]
> @abdonrd — Yes, it only uses that color. If no custom color has been set. You can still make it gray, or any other color, within the collection settings.

Thanks!

This works for me in the `Custom CSS`:

```css
#navigation > .module-nav .nav .v-list-item-icon {
    --v-icon-color: inherit !important;
}
```

**Comment by t7tran** [comment]
Is there a generator for all of those variants based on the primary color?

**Comment by rijkvanzanten** [comment]
> Is there a generator for all of those variants based on the primary color?

No, the css overrides are the only way. That being said, there will be a dedicated theme settings section in settings for more granular and configuration control over the themes coming soon 👍🏻

**Comment by t7tran** [comment]
Thanks @rijkvanzanten. I meant whether the team used a tool to generate these colour codes from `--primary` to `--primary-10`, etc.; or computed them by hand. I'm referring to `custom_css`'s template.

**Comment by rijkvanzanten** [comment]
Ahh gotcha. Yes we use a Sass mixin to generate those:

https://github.com/directus/directus/blob/7c91aa4278f450cb2ed1eb0547b85a6309c68bd3/app/src/styles/themes/_light.scss#L31-L32

https://github.com/directus/directus/blob/7c91aa4278f450cb2ed1eb0547b85a6309c68bd3/app/src/styles/themes/mixins/generate-colors.scss#L1-L22

It's effectively a mix blend between the page background color and the primary color at various levels of strength:

https://github.com/directus/directus/blob/7c91aa4278f450cb2ed1eb0547b85a6309c68bd3/app/src/styles/_colors.scss#L34-L50

**Comment by aiaibabagit** [comment]
Look like the Apple-Touch-Icon is removed. Not sure why?

**Comment by sksar** [comment]
> > Look like the Apple-Touch-Icon is removed. Not sure why?
> 
> Cause it was branded and not user-editable 👍🏻

@rijkvanzanten 
Shouldn't the `safari-pinned-tab.svg` and `mstile-150x150.png` files be removed as well;

This is with reference to #4184 
Screenshot 2022-09-30 at 15 24 51

The favicon does not work for safari and in some versions of Microsoft edge.
I believe we should remove them in favor of the normal favicon.ico.

And as a side note maybe a feature request to be allowed to upload a custom favicon, in the Directus settings.

**Comment by rijkvanzanten** [comment]
> Been a year since that comment. Is this still coming?

It's the long-term goal, but there's nothing actively in works. In the grand scheme of things, we're prioritizing based on community engagement and feature requests, and theming doesn't come up that often 👍🏻

**Comment by M-GRV** [comment]
> > Been a year since that comment. Is this still coming?
> 
> It's the long-term goal, but there's nothing actively in works. In the grand scheme of things, we're prioritizing based on community engagement and feature requests, and theming doesn't come up that often 👍🏻

thanks. just saw it was intended for 9.6 but I agree its nothing that some css cant handle for the time being. I did make a new theme myself and restarted but its not catching. Is there a way to register a custom theme atm?

**Comment by rijkvanzanten** [comment]
> Is there a way to register a custom theme atm?

There's currently no such thing as a "theme". Custom CSS is how you can apply theming beyond the available options for logos and login-page images 👍🏻

**Comment by M-GRV** [comment]
> > Is there a way to register a custom theme atm?
> 
> There's currently no such thing as a "theme". Custom CSS is how you can apply theming beyond the available options for logos and login-page images 👍🏻

Documentation is lying to me than. 

image

**Comment by rijkvanzanten** [comment]
Ah yeah! That's inaccurate.. (cc @phazonoverload)

**Comment by ayatweb** [comment]
im in my var courses

**Pull request merged**
