### PR TITLE
Remove rollup from SDK

### PR DESCRIPTION
**Pull request by joselcvarela**
Transpiles to:
 - CommonJS (CJS) : necessary for Node using Javascript
 - ES2015 (ES6) : necessary for Browsers and Node using typescript
 
 ⚠Note:
 For Browsers, developers should use their own tools for minification.
 
 Changes:
 Mainly removes rollup and its plugins, and follow a similar structure declared on `package.json in @directus/extensions`
 
 Tested with `yarn link` in Node, React and Angular.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
> CommonJS (CJS) : necessary for Node using Javascript

Lets drop CommonJS completely in favor of ESM 👍🏻

**Comment by nickrum** [comment]
I'm not sure if we can actually fully drop rollup. When using the SDK directly inside a browser, it should ideally be bundled to a single minified entrypoint to prevent cascading network requests. Also, as bare-module-imports aren't supported by browsers yet, we would have to bundle axios into the SDK.

**Comment by rijkvanzanten** [comment]
> I'm not sure if we can actually fully drop rollup. When using the SDK directly inside a browser, it should ideally be bundled to a single minified entrypoint to prevent cascading network requests. Also, as bare-module-imports aren't supported by browsers yet, we would have to bundle axios into the SDK.

I'm wondering how common it is nowadays for somebody to use a package like this without having any buildchain whatsoever involved 🤔 I love the idea of just being able to plop in a dist file and have it work in the browser, but I'm not sure how realistic of a use case that is anymore (the amount of overhead required to support that might outweigh the benefits?)

**Comment by joselcvarela** [comment]
But. f the developer is already using axios in his project, it would be added twice?

**Comment by nickrum** [comment]
That is very true. Instead of bundling axios into the SDK, we could alias the import to an unpkg URL.

**Comment by joselcvarela** [comment]
But then, SDK couldn't work inside internal networks without Internet access 😋
Couldn't we provide an ESM module, ready to use both with bundlers and in vanilla JS? Knowing that in vanilla it would not be minified.

**Comment by nickrum** [comment]
True, but then you also won't be able to import the actual SDK in the first place by using `import DirectusSdk from 'http://unpkg.com/@directus/sdk';`.

I don't think this is possible because bundlers/node support `import axios from 'axios';` and browsers don't.

**Pull request closed without merging**
