### PR TITLE
Add table, iframe components

### PR DESCRIPTION
**Pull request by ztob**

### CODE REVIEW

**Comment by ztob** [comment]
sorry, my mistake

**Comment by licitdev** [comment]
Saw the commit in your main branch 😊 [https://github.com/ztob/directus/commit/14b6528b39a186368e7f61e24fef218f1f90e52b](https://github.com/ztob/directus/commit/14b6528b39a186368e7f61e24fef218f1f90e52b)

**Comment by ztob** [comment]
@licitdev  😄 , yeah, it would be great if directus would have all vue components as interface components

**Comment by rijkvanzanten** [comment]
> @licitdev  😄 , yeah, it would be great if directus would have all vue components as interface components

FWIW every v-* component is registered globally, so you should be able to use things like v-button currently 🙂

**Pull request closed without merging**
