### PR TITLE
Improvement/revision pagination

### LINKED ISSUE #3764: Revisions limit
### Issue
Admin app shows only first 100 revisions, while it should show all the revisions.

### Steps to reproduce
1. Make over 100 changes in the item.
2. The revisions list will contain only first 100 revisions and the counter will show 100.

### My environment
MySQL 8.0.22
Chrome 87.0.4280.141
Directus v9.0.0-rc.30

### LINKED ISSUE #7927: Getting duplicate "create" revisions
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I'm getting duplicate "Creation" events under revisions.

Screen Shot 2021-09-08 at 12 56 34 PM

### To Reproduce

1. Create an item
2. Look at revisions

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

### PR DESCRIPTION
**Pull request by wendevlin**
Closes #3764 
closes #7927

- Use pagination component for item revisions
- Add ability to collapse revision date groups

### CODE REVIEW

**Comment by Nitwel** [comment]
This is looking really good now. Thanks @masterwendu !

**Comment by benhaynes** [comment]
Screenshot or it didn't happen! 😉

**Comment by Nitwel** [comment]
GIF 17 09 2021 19-13-00

**Comment by benhaynes** [comment]
This is a thing of beauty!! Great job, @Nitwel!

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
