### PR TITLE
Update interface previews

### PR DESCRIPTION
**Pull request by azrikahar**
Updates interfaces that does not have preview SVGs at the moment, provided by @benhaynes.

- Tags
- Toggle
- Map
- Color
- Icon
- Checkboxes (Tree)
- File
- Image
- Tree View
- Translations
- Divider
- Button Links
- Accordion
- Detail Group
- Raw Group
- Hash
- Slider

## Preview

|Light|Dark|
|---|---|
|lbvo0yK3L7|S2eNKC0kih|

### CODE REVIEW

**Comment by benhaynes** [comment]
Looks amazing! Did I leave out Tree View? 

Any illustrations seem unclear or inaccurate?

**Comment by benhaynes** [comment]
I'll check in the morning...

**Comment by azrikahar** [comment]
> Looks amazing! Did I leave out Tree View?

No worries. I wasn't able to find it in the SVGs shared earlier, at least from what I can see.

> Any illustrations seem unclear or inaccurate?

At first the button links stood out a little bit on Dark theme, but got used to it now 👍

There's also 2 variations of checkbox tree and I went with the first one here. Just pointing that out in case the 2nd one is preferred.

**Comment by benhaynes** [comment]
Ahh, one of those `checkbox-tree` SVGs was meant to be treeview... it just wasn't renamed properly. Here it is:
[tree-view.svg.zip](https://github.com/directus/directus/files/7745945/tree-view.svg.zip)

**Comment by azrikahar** [comment]
Thanks for confirming! Updated 👍

image

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
