### PR TITLE
Add default-folder option

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
Continue work from https://github.com/directus/directus/pull/2896 on https://github.com/directus/directus/discussions/3022

1. Adding folder system interface
2. Add project setting for default folder for added files
3. Added setting for file, files and image interfaces to set folder for added files

UI
Screenshot 2020-11-26 at 13 34 54
Screenshot 2020-11-26 at 13 36 13
Screenshot 2020-11-26 at 13 48 34

### CODE REVIEW

**Comment by benhaynes** [comment]
Thank you so much @dimitrov-adrian !! I'll let Rijk formally review, but my initial feedback is to have the `Storage Default Folder` be **half width** so it sits to the right of the `Storage Asset Transform`. 👍

**Review by naif51191 — APPROVED** [review]

**Comment by massimans** [comment]
Hi,
any updates on this ?

**Comment by benhaynes** [comment]
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

**Comment by eXaminator** [comment]
> Or contribute a pull-request... after all, this is OSS!

This **is** a pull request... so no reason to be condescending here. I'm also waiting for this. Opening PRs is great and all, but doesn't help if they don't get reviewed / merged. So the question becomes, besides sponsoring, what **could** we do to help with PRs like these?

**Comment by benhaynes** [comment]
@eXaminator — I thought it was obvious, but maybe not... that is an auto-response for all "pings" about timing. No condescension here.

As for what can be done to speed things up, since this is already a PR, a comprehensive review (as a different contributor from the OP) would be the best action. Keep in mind that any full review needs to be tested on ALL SQL database vendors.

If this is a high-priority feature for your company, then (as the auto-response stated) consider sponsoring it so it gets an actual timeline.

Other than those options, all I can say is be patient. Reviewing PRs is a time-consuming process — we're an extremely small team, and stability/bugs take priority over new features like this.

**Comment by wc-matteo** [comment]
it'd be also nice to be able to set a default folder per-user

**Review by rijkvanzanten — APPROVED** [review]

**Comment by letoast** [comment]
@rijkvanzanten & @dimitrov-adrian 
This feature should be added to the WYSIWYG field option as well, since it's possible to upload images from there as well.

**Comment by rijkvanzanten** [comment]
@letoast Feel free to open a PR 🙂

**Comment by letoast** [comment]
@rijkvanzanten hehehe I don't know if my coding skills are up to par, but I can try :)

**Comment by rijkvanzanten** [comment]
You can do it! You got this 💪🏻 

This is how the option for `file` is configured:

https://github.com/directus/directus/blob/e6bd669c54e68a65b97fe148ce9596bacbc62877/app/src/interfaces/file/index.ts#L13-L27

We'll have to add that to the rich-text-html one as well:

https://github.com/directus/directus/blob/main/app/src/interfaces/input-rich-text-html/index.ts

Then we'll have to pass the value of that option on to the v-upload component usage here:

https://github.com/directus/directus/blob/e6bd669c54e68a65b97fe148ce9596bacbc62877/app/src/interfaces/input-rich-text-html/input-rich-text-html.vue#L82

👍🏻

**Pull request merged**
