### PR TITLE
add `Last-Modified` header to `/assets/*` responses

### PR DESCRIPTION
**Pull request by molszanski**
Related to this PR:  https://github.com/directus/directus/pull/11818

Related to a discussion:
https://github.com/directus/directus/discussions/6723

`Last-Modified` header basically enables caching in the browser. 
Without `Last-Modified`, `Cache-Control` is semi-useless in the browser. 

This enables asset caching for ~95% of use cases

### CODE REVIEW

**Comment by molszanski** [comment]
@rijkvanzanten  follow up to a prev PR: 
https://github.com/directus/directus/pull/11818

**Comment by molszanski** [comment]
Is there anything else I need to do?

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Nope! I just had to find the time to review/check/merge 🙂

**Comment by molszanski** [comment]
@rijkvanzanten thanks <3

**Pull request merged**
