### PR TITLE
Returns the nodemailer promise

### PR DESCRIPTION
**Pull request by keesvanbemmel**
We want to store the generated ID from our mail transporter (MailGun) so we can handle webhooks from MailGun with the status of sent mail items

Not sure who to tag for reviews etc @rijkvanzanten :)

## Description

Fixes #

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by azrikahar** [comment]
Hi! Would you mind updating the PR template with what we're currently using for this repo? Just for triaging and consistency sake 😊 You can also find the raw markdown here: https://raw.githubusercontent.com/directus/directus/main/.github/pull_request_template.md

With that said, in regards to this PR, can you share an example code for the scenario you have mentioned? Curious to see how it pans out as I'm not super familiar with the returned value personally.

On a slightly related tangent, I'm wondering should this also be returned in the Flows Mail operation:

https://github.com/directus/directus/blob/228a5ca15f981f01c7072b641d53e1edf562629a/api/src/operations/mail/index.ts#L18-L22

so that Flows can then also be used to support similar use cases 🧐

**Comment by rijkvanzanten** [comment]
> the generated ID from our mail transporter

Is this consistent behavior in `nodemailer`? Does it always return the ID from the provider? What if there's no ID (like sendmail etc). The only thing I'm worried about with this change is that the return type and value of this is going to be different depending on what configuration you're using for the mailer, which can cause some pretty inconsistent behavior.

**Comment by keesvanbemmel** [comment]
This is what the [documentation of node mailer](https://nodemailer.com/usage/) says:
`If callback argument is not set then the method returns a Promise object. Nodemailer itself does not use Promises internally but it wraps the return into a Promise for convenience`

So this PR will just return exactly what nodemailer returns.

**Comment by keesvanbemmel** [comment]
> With that said, in regards to this PR, can you share an example code for the scenario you have mentioned? Curious to see how it pans out as I'm not super familiar with the returned value personally.
> 

The returned value might/will change per mail transporter. But for example (using MailGun) imagine the following flow:
- We send out an email notification
- Nodemailer will return the ID of the email generated by MailGun somewhere in the callback function/promise
- We store this ID in a collection for that email
- MailGun posts webhooks to Directus with the status of that email (openend, clicked, bounced etc etc) with that ID
- We update the status in the collection using this info

> On a slightly related tangent, I'm wondering should this also be returned in the Flows Mail operation:
> 
> https://github.com/directus/directus/blob/228a5ca15f981f01c7072b641d53e1edf562629a/api/src/operations/mail/index.ts#L18-L22
> 
> so that Flows can then also be used to support similar use cases 🧐

Should work exactly the same indeed!

**Comment by azrikahar** [comment]
@keesvanbemmel thanks for the detailed walkthrough! It does make sense for such scenario. Slightly wished there's a more concise "example returned values for each transport" table/matrix that we can directly link to in the docs (technically more of a concern if we do return the value in Flows Mail operation for example). 🤔

Gave it a quick test of SMTP with Maildev and got the following response which does seems to align with their documented usage:

```js
{
    accepted: [ 'me@example.com' ],
    rejected: [],
    envelopeTime: 188,
    messageTime: 165,
    messageSize: 302,
    response: '250 Message queued as I44hqwfk',
    envelope: { from: 'no-reply@directus.io', to: [ 'me@example.com' ] },
    messageId: '<1fe7ae02-353c-8720-7d2a-986d52332cc4@directus.io>'
}
```

**Comment by keesvanbemmel** [comment]
@azrikahar I think we should/could just refer to the documentation of the specific driver. There is no point in creating (and more so updating) such a matrix ourselves right?

**Comment by azrikahar** [comment]
> @azrikahar I think we should/could just refer to the documentation of the specific driver. There is no point in creating (and more so updating) such a matrix ourselves right?

Agreed! Hence the wish of linking to it, not creating it ourselves 😁

**Comment by keesvanbemmel** [comment]
Ah! I misread @azrikahar! Where should we create such a table?

**Comment by keesvanbemmel** [comment]
> Ah! I misread @azrikahar! Where should we create such a table?

Any thoughts @azrikahar ? :) Really would like to close this!

**Comment by azrikahar** [comment]
> > Ah! I misread @azrikahar! Where should we create such a table?
> 
> Any thoughts @azrikahar ? :) Really would like to close this!

I was thinking that it should be present in Nodemailer's docs sort of like how we can link Helmet.js docs for CSP related configs so that it wouldn't be "outdated" if Nodemailer ever change things over there, but we can probably defer creating such a table for now. 👍

Another immediate thoughts, albeit very minor, would be perhaps we can change:

```js
return this.mailer.sendMail({ ...emailOptions, from, html });
```

to something such as:

```js
const info = await this.mailer.sendMail({ ...emailOptions, from, html });
return info;
```

just to be more inline similar logic throughout the codebase for consistency sake, in terms of code style at least.

Apart from that I do still agree with @rijkvanzanten's concern of potential inconsistent behavior, but perhaps it's something to note in the eventual extension services docs? My understanding is it should not be a change that affects existing `MailService` `send()` usage such as in custom extensions since the existing usage should already treat it as a void promise so they've never attempted to access the returned result 🤔

**Comment by keesvanbemmel** [comment]
@azrikahar I think that's a great way of returning it! The only thing I can't oversee is if that needs code changes anywhere else?

**Comment by azrikahar** [comment]
> The only thing I can't oversee is if that needs code changes anywhere else?

I believe there's none, from what I can tell 👍

This looks good to me with the notion of the returned value was never accessed in the past so it shouldn't break any existing setups AFAICT, but I'll defer to @rijkvanzanten on the current implementation (as well as the generic we added to "help out" with the returned type) and whether there's any unaccounted concern here.

**Review by azrikahar — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Not a fan of how it directly couples our usage of nodemailer under the hood, but i don't expect us to swap that out for another lib anytime soon, and I do certainly get the usability in extensions, so lets do it!

**Pull request merged**
