### PR TITLE
Fix entry file resolution when running with Phusion Passenger

### PR DESCRIPTION
**Pull request by lukas-schaetzle**
## Description

Attempt to fix the current issue with deployment on Passenger (used by Plesk/cPanel).

Fixes #15091

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by Tummerhore** [comment]
**Warning:** I could not yet test whether this really fixes the problem because I currently can't build the project. As soon as I have solved this I will test it.

**Comment by Tummerhore** [comment]
Alright, I've tested it now with Passenger and it fixed the problem. However, I had some trouble with Typescript since it's not really my strong suit...

- Exporting/Importing the declared const did not work (see my first commit)
- Declaring it globally works but leads to failing tests (see second commit)
- That's why I've declared it now locally in the same file. Certainly not the nicest solution but it works. If you know, how to outsource the delcaration feel free to adjust it :)

**Review by lessborders — APPROVED** [review]
This works.

**Comment by Rar9** [comment]
How to get this,  so directus can actually run on a plesk environment

**Comment by lessborders** [comment]
> How to get this, so directus can actually run on a plesk environment

I'd recommend waiting until the PR is merged - I replaced the specific files and rebuilt the package.

**Comment by rijkvanzanten** [comment]
While the solution seems to work for those who tested it, I'm not really a big fan of having such a passenger/phusion specific implementation. So far, the API doesn't care what the environment is we're running in. I'm wondering if there's a more agnostic way we can can resolve the underlying problem. I believe the problem stems from the fact that the passenger configuration is relying on a custom javascript file outside of the directus project that then imports and starts the server, rather than relying on on the run.js file, which in turn then causes the wrong `require.main.filename` to be used 🤔

**Comment by Tummerhore** [comment]
> While the solution seems to work for those who tested it, I'm not really a big fan of having such a passenger/phusion specific implementation. So far, the API doesn't care what the environment is we're running in. I'm wondering if there's a more agnostic way we can can resolve the underlying problem. I believe the problem stems from the fact that the passenger configuration is relying on a custom javascript file outside of the directus project that then imports and starts the server, rather than relying on on the run.js file, which in turn then causes the wrong `require.main.filename` to be used 🤔

Exactly, that's the problem here. I agree that it's not so nice to have a special treatment for Passenger in the code but I don't see any other possibility if you want to identify the entrypoint filename. So I guess the only two agnostic options would be
- to have an optional environment variable which can be used for the location of the entry file or node_modules folder
- or to do completly without the entry file resolution but I don't know if that's viable. I guess it's necessary for #14728?

**Review by sapientorius — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Seems like @nickrum found the underlying problem and fixed that instead of relying on custom overrides 🙂 

Superseded by https://github.com/directus/directus/pull/15574

**Pull request closed without merging**
