### PR TITLE
Fix/issue 16917

### LINKED ISSUE #16917: Avatar / logo flashes on page changes
I believe it might have something to do with the fact that it tries to load from the API and inject as a data string, and the navigation causes an `update` cycle in Vue, which causes it to reinstantiate the image. 

### Discussed in https://github.com/directus/directus/discussions/16908

<div type='discussions-op-text'>

<sup>Originally posted by **ernst86913** December 24, 2022</sup>
Hi - 
currently the logo and the avatar are reloaded on every route change... which creates a bit of a "messy" experience for the user as those components are "flickering". Would it be possible to keep those 2 components stay on the screen like all other navigation bar components (e.g. the Directus Standard logo works nicely).

Thanks,
Roman </div>

### PR DESCRIPTION
**Pull request by jay-p-b-7span**
## Description

Fixes #16917 

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by vanling** [comment]
Why portals? and how will this fix the "flickering image" issue from https://github.com/directus/directus/issues/16917 ?

**Comment by azrikahar** [comment]
Very much agree with @vanling questions here. I can only assume the choice was made due to some form of limitation with the built-in `<teleport>` perhaps? However without any elaboration as to _why_ we had to resort to `<portal>`, it can be very difficult to understand what is the actual reasoning for the approach taken in this PR, at least at a glance. Would really appreciate it if you can help clarify this! 🙂

**Comment by jay-p-b-7span** [comment]
Thanks for the feedback @azrikahar and @vanling. I have updated the code with vue teleport and removed portal vue as I experienced it was not needed and used vuejs native feature. Thank you.

**Comment by rijkvanzanten** [comment]
This feels like a very complicated change for such a small bug 🤔 What's the reason we have to resort on teleports? What's the cause of the flicker that can only be solved through the use of a teleport?

**Pull request closed without merging**
