### PR TITLE
Filter O2M collections with a subquery instead of joins to prevent cartesian products

### LINKED ISSUE #4078: getDBQuery generates invalid group by clause on some RDBMS types
The fix for issue #3798 introduces a group by clause in Select queries that is invalid for MS SQL Server, Oracle and I also think MySQL could be affected, depending on the ONLY_FULL_GROUP_BY SQL setting.

The problem is that on these databases, with a group by query, all select columns MUST be either an aggregate or in the group by expression. This is not the case. Only the id column is in the group by expression to prevent duplicate results.

It might be possible that this issue can be fixed with a select distinct query instead of the group by, but to be honest, I'm not sure whether this would cause any unwanted side-effects.

### PR DESCRIPTION
**Pull request by martijnboland**
This PR fixes #4078. A group by clause is not required anymore because filtering on O2M relations now generates a WHERE item.id IN (SELECT o2m_item.fk_id FROM o2m_collection WHERE...) subquery.

Tested locally with mssql, so testing with other RDMBSes still needs to be done.

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
It seems to break once I go 2 levels deep on the filter, eg

```
filter[categories][category_id][_eq]=2
```

works great, but

```
filter[categories][categories_id][gallery][directus_files_id][_eq]
```

fails with 

```
select `articles`.`id` from `articles` where `articles`.`id` in (select `articles_id` from `articles_categories` left join `categories` as `gn1vg4GG` on `articles_categories`.`categories_id` = `gn1vg4GG`.`id` where `categories_directus_files`.`directus_files_id` = '99c709b7-48c8-4e0d-89fc-55702bb7f5fe') limit 100 - SQLITE_ERROR: no such column: categories_directus_files.directus_files_id
```

(It's `/items/articles` -> `categories` (m2m) -> `categories_id` (m2o) -> `gallery` (m2m) -> `directus_files_id` (m2o) )

**Comment by rijkvanzanten** [comment]
I think it's due to the fact that we still need to do the joins on the nested o2m fields, but only if it's part of the subquery :thikn

**Comment by rijkvanzanten** [comment]
Updated the logic to combine the best of both worlds 🙂 

When it's the top-level request, it'll use the subquery, but if it's a nested subquery, it'll still do the O2M joins. The output query looks good to me too:

```sql
SELECT
	`articles`.`id`
FROM
	`articles`
WHERE
	`articles`.`id` in(
		SELECT
			`articles_id` FROM `articles_categories`
		LEFT JOIN `categories` AS `TATkm5bM` ON `articles_categories`.`categories_id` = `TATkm5bM`.`id`
		LEFT JOIN `categories_directus_files` AS `ZdjI1PFG` ON `TATkm5bM`.`id` = `ZdjI1PFG`.`categories_id`
		LEFT JOIN `directus_files` AS `38PYM4ir` ON `ZdjI1PFG`.`directus_files_id` = `38PYM4ir`.`id`
		WHERE
			`38PYM4ir`.`filename_disk` = '35ddcf5d-f791-43b2-a582-2ea5aff33599.jpeg'
	)
LIMIT 100;
```

**Review by rijkvanzanten — APPROVED** [review]

**Comment by martijnboland** [comment]
This looks perfectly fine to me. With 'select in()' it doesn't matter if the subquery returns duplicate results.

**Pull request merged**
