### PR TITLE
Modular CLI for Directus

### LINKED ISSUE #1025: Lost password first install
Hello,

well i can't connect on my directus, how reset the password please ?

when i cliqu on the ?  from the login password forms i have the error : Server error occurred!

so how connect without my password please, or how reset password thanks

### PR DESCRIPTION
**Pull request by Wedjaa**
This is a first stab at making the CLI modular, making it easier to extend the capabilities of the command line and implementing a very simple user password reset. 

  Fixes #1025

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Hey @Wedjaa Thanks for this PR.

I like this, and where this is going.

I don't know if this is done yet, but it doesn't work well, every time I tried to use the installer module (_it should be called Command will fit best, I believe_), the user always end up being `admin@directus.com` with password `directus` and the database, user and password in the config file there are always `directus`

If you can add some tests it will be great.

BUT. We actually don't have any Code Style Standard set yet, but we are working on variation of PSR2, so until this is done here are my thoughts.

The major issue is that style changes:
- Sometimes method have the curly braces at the same line, sometimes don't.
- Indentation change from 2 to 4 spaces.
- Method and Variable naming convention change from underscore to camel cases.

I really do like this and I'm giving you my feedback and as we are having more Contributions, we are going to have a time for creating a CONTRIBUTIONS GUIDELINES.

Let me know how this is going and what are the next step.

I had some ideas on how this could be done, and one that I think is missing in a way to Register command instead of being auto-loaded directly.

Something like this: 

```php
$commands = get_commands();
foreach($commands as $command) {
    register_command($command);
}
```

This is great, keep them coming.

**Comment by Wedjaa** [comment]
Will do sone code cleanup - right now I'know passing the parameters to the InstallerUtils - will have to look at what's happening in there and see if I'may passing the parameters wrong. 

  This firstime couple of commits were mainly to see if Tehran direction was the right one. Will add some tests before asking for a merge.

**Comment by Wedjaa** [comment]
* Teheran  -> 'the' --- spellchecker odd failure! :)

**Comment by WellingGuzman** [comment]
Amazing @Wedjaa, no pressure. We value this contributions.

You saved a google search there :)

**Comment by Wedjaa** [comment]
Soooo - this was a bit more than a simple code review. Modules now extend the same base module, making it easier to create new ones and maintain the way modules behave.

 Code has been cleaned up and made more compliant with the coding guidelines.

 The install command now tried to be more clever - before it would use directly the InstallUtils module, but that would fail if doing changes on an  existing configuration. Tried to make it more intelligent in that respect.

  The admin user e-mail is now changed on the schema inserted admin user; this should provide a way of changing the admin e-mail more often.

  Still need to add tests -- but give it a spin and let me know if there is anything else that seems broken. as it is now is still a WIP.

**Comment by benhaynes** [comment]
@Wedjaa – Sorry for the late response, but this is amazing. @WellingGuzman what do you think? Anything else this needs before we look at merging?

**Comment by Wedjaa** [comment]
@benhaynes Wanted to get a bit more ideas on what commands could be implemented before merging and looking at prompting the user for the parameters if missing - but I got stuck trying to find a proper way to handle multi-platform password prompting for PHP.

**Comment by WellingGuzman** [comment]
Hey @Wedjaa,

As long as you feel that this PR is working, we can add more commands on the go when you got the ideas what else could be a command.

As questions are a new feature, if you feel like it you can do it into another PR, but if you want some ideas or inspiration or how someone else did this, you can check [Symfony Console Compoenent QuestionHelper](https://github.com/symfony/symfony/blob/dbee09298ca68c27679b17fb1b1765020269d6ce/src/Symfony/Component/Console/Helper/QuestionHelper.php#L342-L388)

I will test what's done so far, sorry for the delay but I didn't thought it was ready to test, my bad.

**Comment by Wedjaa** [comment]
@WellingGuzman It's not you, it's me :) 

Still titled [WIP] while I finish implementing the tests, but "It Works" (tm)

**Comment by Wedjaa** [comment]
Having troubles mocking the DB for the tests - will mark this PR as ready while I figure out a proper way to test without having to run a SQL DB. 

   It kind of sucks that there is no way to get the password without calling a native executable - as Symfony does; but I guess it's the only way. Will create a new PR for that.

**Comment by WellingGuzman** [comment]
That sounds perfect @Wedjaa, I will merge this then. any thoughts @benhaynes ?

**Comment by benhaynes** [comment]
Yeah, this is great – and I agree that we can open a new PR for the password fetch.

Thanks @Wedjaa!

**Pull request merged**
