### PR TITLE
Updated Public Page Artwork

### LINKED ISSUE #20322: Replace public page default art
### Describe the Improvement

Get with the times!

### PR DESCRIPTION
**Pull request by benhaynes**
## Scope

What's changed:

- Changed the CSS/design of the art on the public page

## Potential Risks / Drawbacks

- Inefficient use of browser/GPU
- Subjective design

## Review Notes / Questions

- Efficient enough?
- Looking good?

---

Fixes #20322

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Love the design, _but_.... it runs very inefficiently 😬 

https://github.com/directus/directus/assets/9141017/5b73a6ed-0e68-4970-acca-723ac9cb044e

**Comment by benhaynes** [comment]
@rijkvanzanten — ok, back to you! It's nice and speedy now (afaict)

**Comment by ched-dev** [comment]
@benhaynes If I have my Chrome without hardware acceleration, I get a very choppy page which has a 1-2 second delay while I'm typing my login info. Is there a way to only enable this if hardware acceleration is turned on? It looks fine when I have it on.

Specs:
I'm on an M1 Mac in Chrome Version 120.0.6099.234 (Official Build) (arm64), issue was with hardware acceleration turned off.

**Comment by benhaynes** [comment]
@ched-dev — not sure about the conditional (does that check exist?) but if the animation isn't running smoothly then I guess the next best thing would be to override it with a public page background image instead. You could even use a screenshot of the animation if you wanted the same vibe.

We tried to keep the animation super performant, but it's hard to plan for all hardware/configs.

**Pull request merged**
