### PR TITLE
Fix issue with selecting a grouped field as a display value

### PR DESCRIPTION
**Pull request by u12206050**

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I think I might've beaten you to it in https://github.com/directus/directus/pull/12284, or did that not fix it for you? 😅

**Comment by u12206050** [comment]
No that didn't work. The problem is that when the field is in a group then
the key won't match since it is different from the path of the field which
includes the group, unlike the key.

**Comment by rijkvanzanten** [comment]
Yeah, so in #12284 it passes up the whole field object in the addField function, rather than just the key, which in turn means we don't have to do the key-based lookup in the field tree  so it basically replaces this: https://github.com/directus/directus/pull/12285/files#diff-aeeabdcffba5a966372b2df39ebd2ca4fcd93cf9219ab30a42ef1fe25514d699R203-R212 completely. It did seem to do the trick on my end:

https://user-images.githubusercontent.com/9141017/159356137-961bc1a6-7e09-4e5e-a9de-ca32110ae9ef.mp4

**Comment by u12206050** [comment]
Ah sorry forgot to reset my changes. I can confirm it is working. Thanks

**Pull request closed without merging**
