### PR TITLE
Change mail body type to wysiwyg editor #14473

### LINKED ISSUE #14473: No HTML support in Send Mail Operation under Flows
### Describe the Bug

As seen on:
https://github.com/directus/directus/blob/857eae54defc166bef6198d482bdaba2a0b876cf/api/src/operations/mail/index.ts#L17-L21

md() function is actually sanitize html so every time I tried to send and html, the attributes on the html tag would always stripped out

---

So for this bug, I'd like to propose to add one selection input under the subject input to choose whether the content must be send as html or md, or you could provide either markdown or wysiwyg editor for the body section.

I think this "bug" should be done as soon as possible since it can be a game changer for the send email function

### To Reproduce

I tried putting these into the body under the send mail operation
```html
<section style="color: #8d8c87; display: block; font-family: Arial, sans-serif; font-size: 12px; line-height: 120%; text-align:center;">
  
  <center>
   <img src="https://somedomain.com/assets/assetId.png" alt="logo" height="50">
  </center>
  
  # Hi! Welcome to Our Newsletter!
  
  Hi {{ $trigger.payload.email }}! Thank you for your enthusiasm for joining our newsletter list :D
  
</section>
```

Now, if you see on the preview tab, it's all looking fine, until you send them and you check them on the email

And the result received on the email was 

```html
<section>
<h1>Hi! Welcome to Our Newsletter!</h1>
</section>
```

### Errors Shown

No error shown

### What version of Directus are you using?

v9.13.0

### What version of Node.js are you using?

17.0.4

### What database are you using?

10.7.4-MariaDB-1:10.7.4+maria~bionic - mariadb.org binary distribution

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by raflymln**
## Description

Fixes #14473

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

This update made it possible to send an email like this:
image

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I don't think we can just replace the markdown setup with a html setup without breaking current installations that are already relying on markdown. A better solution here would be to add a toggle to explicitly allow HTML to be used inside the markdown editor (eg disable the sanitation), or add a toggle that allows the admin to switch between markdown and HTML "mode" 👍🏻

**Comment by raflymln** [comment]
What if we made a dual version of send mail, one with WYSIWYG and one with markdown? @rijkvanzanten , since i think this feature is kind of useful and important, we should make a solution for this, what do you think?

**Comment by rijkvanzanten** [comment]
> What if we made a dual version of send mail, one with WYSIWYG and one with markdown?

I think I'd prefer finding a solution within the options of the single operation, as beyond the message everything else about the operation is identical. A "Sanitize HTML" toggle that's enabled by default (current behavior) could already be sufficient, as that would allow HTML to be entered/rendered from the MD interface 🤔 

> since i think this feature is kind of useful and important, we should make a solution for this, what do you think?

I think it's a useful addition, but based on [community](https://github.com/directus/directus/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) [engagement](https://github.com/directus/directus/discussions/categories/ideas?discussions_q=sort%3Atop+category%3AIdeas) I can't say it's super high prio 🙂

**Comment by izoukhai** [comment]
@rijkvanzanten it's an important feature, because right now Flows are useless if you want to send emails for customers.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten it's an important feature, because right now Flows are useless if you want to send emails for customers.

I wasn't saying it isn't useful. We just gotta make sure we're not causing a big breaking change with a seemingly small update 🙂

**Comment by izoukhai** [comment]
> 

Sure I totally agree, I will play around with the "Sanitize HTML" toggle you mentioned earlier it looks like the best option right now ;)

**Pull request closed without merging**
