### PR TITLE
Allow for discarding of changes without leaving

### LINKED ISSUE #9642: Allow discarding of changes without leaving page
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The only way to reset the form to original state is to exit discarding changes and re-entering.

### To Reproduce

-

### Errors Shown

-

### What version of Directus are you using?

main branch

### What version of Node.js are you using?

v16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by licitdev**
Closes #9642.

discard-changes

It is implemented alongside `save-options` so that there is no need to prompt for confirmation, same as save as copy etc.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I'm wondering about the 80/20 of this. Is navigating away to cancel out of editing the item too cumbersome? Also a little curious if there's a UX problem with two very opposite actions so close together ("save" vs "undo everything"). Thoughts @benhaynes?

**Comment by benhaynes** [comment]
I don't mind having the explicit option to leave without saving... so there's a very clear option for that. Still, it's the same number of clicks for this versus hitting "back" and "confirm". :)

**Comment by licitdev** [comment]
> I'm wondering about the 80/20 of this. Is navigating away to cancel out of editing the item too cumbersome?

I added it as I've been debugging the form side of things. Often, making changes to a field and the only way to get the original value back was to click back, confirm, then re-enter.

> Also a little curious if there's a UX problem with two very opposite actions so close together ("save" vs "undo everything"). 

Indeed, they are opposite. Will it be better if a divider is added before the discard changes option?

**Review by rijkvanzanten — APPROVED** [review]

**Comment by benhaynes** [comment]
Happy with or without a divider. It's already clear, bt we could also say: `Discard All Changes`

**Pull request merged**
