### PR TITLE
Log localhost url on startup so it's clickable in terminals

### PR DESCRIPTION
**Pull request by zebapy**
This is a little DX enhancement so folks don't have to go to through browser, make a new tab, type out the URL. Instead they can ctrl+click the url in their terminal. Maybe there's a reason this isn't originally this way, but I want to suggest it.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@zebapy It's because there's a very good chance that you're not actually running Directus on localhost. This change would mean it also prints that message when running directus on your production server environment for example 🤔

**Comment by zebapy** [comment]
It's local to that server right? Are folks opening it from their production
server?

**Comment by rijkvanzanten** [comment]
I'm just worried about the confusion when somebody runs it on a production server where the public domain/ip is different, which would mean that opening localhost:8055 wouldn't actually do anything 🤔

**Comment by zebapy** [comment]
I could wrap it with a check for `NODE_ENV==='production'`?

**Comment by rijkvanzanten** [comment]
That'd work, but then we'd only show the message when you use `npm run dev`, and not when running the prod build of directus locally 🤔 

FWIW, I'm not sure if what I mentioned earlier is an actual problem tho! Just my gut feeling. Do you agree this is a problem we should worry about, or do you think most devs will understand what we mean?

> I'm just worried about the confusion when somebody runs it on a production server where the public domain/ip is different, which would mean that opening localhost:8055 wouldn't actually do anything 🤔

**Comment by zebapy** [comment]
My thought was log the original message on prod but then localhost version in dev mode. 

I do agree I don't think it's a problem in prod builds though. Someone knowing enough to set up the prod server and view the logs should understand. To me, it seems like the value from the dev clickable link outweighs that situation.

**Comment by nickrum** [comment]
In dev, `vite.js` should already log the localhost URL of the App to the console.

**Comment by rijkvanzanten** [comment]
Okay! Good point, lets do it 👍🏻

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
