### PR TITLE
Support custom aspect ratios in image editor

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Continuation of #14510 as there's no write permission to said PR. 

Implements #14395.

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [x] Documentation was added/updated -> directus/docs#66

### CODE REVIEW

**Review by br41nslug — COMMENTED** [review]
Works like a charm. But i do think we should append the custom ratios after the default set of ratios as that already provides you with the most common ratios but those disappear when you add a single custom ratio.
**default list**
image
**after adding a custom ratio**
image

**Comment by azrikahar** [comment]
> Works like a charm. But i do think we should append the custom ratios after the default set of ratios as that already provides you with the most common ratios but those disappear when you add a single custom ratio.

Frankly I had the same expectation initially! I sort of assumed it was purposely overridden in case they ended up being the same text (when there's both default `16:9` vs custom `16:9`, but it's a pretty edge case)

Perhaps we can use a divider to separate customs on top and still include the defaults? cc @rijkvanzanten

chrome_5JGdYhURvg

---

On a related note, thought's on using `aspect_ratio` as the icon vs the current `crop_square`? Feels like it's more appropriate as "custom aspect ratios".

|`crop_square`|`aspect_ratio`|
|---|---|
|chrome_kOq6WAffRN|chrome_SMT5WFmQD5|

**Comment by qborisb** [comment]
Hello guys! Let me jump into the discussion as well!

Firstly, thanks @azrikahar for creating a separate PR. The thing is, the initial PR was pushed from the fork that was created from the organisation that I work in. If you create a fork on the organisation, not a personal account, then you cannot allow edits from maintainers - that's the restriction of Github it seems. Hence, I will be creating any future PRs only from my personal account!

Secondly, I definitely agree with the choice of the icon, it does seem like a better fit for the "custom aspect ratios". Wasn't sure which icon to pick, honestly 🤔 Regarding the appending custom ratios part instead of replacing them: initially the PR started as an effort to add local custom aspect ratios - i.e., per image field. In that case, overwriting custom aspect ratios made much more sense. However, it turned out to be trickier to implement, and hopefully, we figure out how to support that nicely in the future. All in all, I agree that appending custom aspect ratios which were configured in a global settings make much more sense than overwriting them.

Lastly, regarding the ergonomics of entering a float instead of having a new component with two inputs that dynamically calculates the float: I indeed agree that it would be a better user experience to enter the float like that! So I am happy to start working on that!

Sorry for quite a lengthy comment, but seems like I covered all the points I've missed so far ;)

**Review by br41nslug — APPROVED** [review]

**Comment by azrikahar** [comment]
> that's the restriction of Github it seems. Hence, I will be creating any future PRs only from the fork in my personal account!

No worries! Also went and look for the relevant GH discussion and found it: https://github.com/community/community/discussions/5634. Hopefully it'll be made possible in the future!

> Secondly, I definitely agree with the choice of the icon, it does seem like a better fit for the "custom aspect ratios". Wasn't sure which icon to pick, honestly 

> All in all, I agree that appending custom aspect ratios which were configured in a global settings make much more sense than overwriting them.

Glad we landed on a great balance here 😊

> Lastly, regarding the ergonomics of entering a float instead of having a new component with two inputs that dynamically calculates the float: I indeed agree that it would be a better user experience to enter the float like that! So I am happy to start working on that!

Thanks!

**Pull request merged**
