### PR TITLE
Improve cache performance by compressing records

### PR DESCRIPTION
**Pull request by joselcvarela**
## Description
In some network conditions, writing or reading from cache could make some time. This scenario is even worst if the payload is somehow big.
In order to prevent huge payload to be written/read on Redis, we can compress/decompress this payloads so network can handle it easily. This makes requests to be faster.

In order to compress payload, we decided to use Gzip.
In our tests Brotli had higher compression rate, though Gzip was faster and the difference in compression was very small (95% vs 93%)

Fixes https://github.com/directus/cloud/issues/88
Fixes https://github.com/directus/cloud/issues/451

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by Attacler** [comment]
@joselcvarela maybe its better to also provide an .env variable to disable caching for files?

**Comment by rijkvanzanten** [comment]
> @joselcvarela maybe its better to also provide an .env variable to disable caching for files?

Files aren't cached in the cache store (redis etc) in the first place 👍🏻

**Comment by eikaramba** [comment]
back in the day i used snappy to compress/decompress from/to redis. in comparison gzip is even slower than that. just wanted to leave this here. also LZO/LZ4 can be a good candidate (i haven't tried it out but some benchmarks are even better so gzip<snappy<LZ4)

some links as reference:
https://stackoverflow.com/questions/35789412/spark-sql-difference-between-gzip-vs-snappy-vs-lzo-compression-formats
https://stackoverflow.com/questions/67537111/how-do-i-decide-between-lz4-and-snappy-compression

**Comment by rijkvanzanten** [comment]
Thanks for the insights @eikaramba! Looks like `lz4` for node doesn't really have a good existing lib available (https://www.npmjs.com/package/lz4 hasn't really been maintained in a minute), but `snappy` looks very promising!

**Review by rijkvanzanten — APPROVED** [review]

**Comment by eikaramba** [comment]
FYI: For the future a look into https://github.com/facebook/zstd seems to be worth it. AWS is switching to it, mongodb offers it (also snappy, might switch from that default) and all the benchmarks i found actually seemed to be overall stating that it is better than snappy. Which is suprising, as often times there are pros/cons, but it actually seems to achieve a better compression ratio with the same speed.
Not really high priority because snappy already performance good. just wanted to leave this here for future references...

**Comment by rijkvanzanten** [comment]
@eikaramba Sweet! Though just as with lz4, I'm having some trouble finding a good maintained node version 🤔

**Comment by eikaramba** [comment]
you can find it here: https://facebook.github.io/zstd/#other-languages
for nodejs this seems good https://www.npmjs.com/package/simple-zstd (using native bindings, no compilation needed and you can always use the latest version. however that means zstd dependency will be needed in all environments. there are also libs however which compile it via emscripten)

**Pull request merged**
