### PR TITLE
ESM only on 'format-title'

### PR DESCRIPTION
**Pull request by joselcvarela**
https://user-images.githubusercontent.com/14039341/135132669-9a5f5452-16f0-4805-a470-379c837beca0.mp4

### CODE REVIEW

**Comment by joselcvarela** [comment]
Should I change this to some `debug` tag ?
https://github.com/directus/directus/blob/a14b5b434cf7aa55a3c9d8d1205e4ea14bed3f1d/packages/format-title/package.json#L3

**Comment by joselcvarela** [comment]
@nickrum @rijkvanzanten 

It seems like `exports` is only used for named imports like `import "package"`
Since we are returning a function I think it is not necessary to use `exports` since it makes no sense to use imported names with this package.
Also, I have tried to run inside a `create-react-app` and `@angular/cli ng new` apps and worked as expected. Just needed the `module` defined.

**Comment by joselcvarela** [comment]
I think the cause for tests failing is this:
https://jestjs.io/docs/ecmascript-modules

What are your thoughts, should we follow this "hack"?

**Comment by rijkvanzanten** [comment]
@joselcvarela Those tests were already fixed by @jaycammarano in https://github.com/directus/directus/pull/8276 🙂

**Comment by joselcvarela** [comment]
I wish it was that, but unfortunately it keeps failing 😞

**Comment by rijkvanzanten** [comment]
Oh hold up, you're right. It's Jest that's not able to find the module now 🤔 Maybe it has some trouble with ESM itself?

**Comment by rijkvanzanten** [comment]
(sorry bout that, accidentally tagged the wrong number on that unrelated PR)

**Comment by nickrum** [comment]
`exports` is just an alternative to `main` that allows for fine-grained control over which files from the package are actually exported. So, using `"exports": "./dist/index.js"` just means you can only import this specific file by using `import formatTitle from '@directus/format-title';` and nothing else.

`module` is a non-standard field that is not supported by node, so any package running under node won't be able to use the title formatter. The field is used by most bundlers as an alternative entrypoint to `main`.

Thinking more about it, I don't think we can go full ESM on format-title just yet, as it is used my the Directus api package which is CommonJS-only for now.

**Comment by rijkvanzanten** [comment]
> as it is used my the Directus api package which is CommonJS-only for now.

FML

**Comment by joselcvarela** [comment]
I am closing this for now since this will not be possible while API is CommonJS.

**Pull request closed without merging**
