### PR TITLE
Add Flydrive license back

### PR DESCRIPTION
**Pull request by RomainLanz**
Hey there! 👋 

It seems that you are using [Flydrive](https://github.com/Slynova-Org/flydrive) code-base but you removed the license file.

As state in the Flydrive License (MIT):
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Here is a PR that add the license in the needed package.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Ty! Must've fallen through the cracks while moving / restructuring things over.

Sidenote: Is Flydrive being supported again? We ended up moving things over because PRs went stale / issues weren't answered reliably 😬

**Comment by RomainLanz** [comment]
Yes, plan to get back to it, it was sleeping for to long. 😄

**Comment by rijkvanzanten** [comment]
Nice! I'll probably end up backporting some of the newly added features over there then 🙂 

Do you have any overview of how coupled Flydrive is / will be to Adonis? I noticed your involvement in Adonis, and that combined with the `@adonisjs/drive` layer I kinda had to assume that `flydrive` was left on the sidelines

**Comment by RomainLanz** [comment]
The goal is to keep Flydrive standalone.
We created `@adonisjs/drive` to have a wrapper that fits well in AdonisJS.

**Pull request merged**
