### PR TITLE
Fix server error on root m2a query

### LINKED ISSUE #23179: M2A querying in rest filter returns error
Querying using the `:` syntax in the rest API throws a permissions error:

```
{"errors":[{"message":"You don't have permission to access field \"item:basic_collection\" in collection \"example_m2a\" or it does not exist. Queried in \"m2a\".","extensions":{"code":"FORBIDDEN","reason":"You don't have permission to access field \"item:basic_collection\" in collection \"example_m2a\" or it does not exist. Queried in \"m2a\".","stack":"DirectusError: You don't have permission to access field \"item:basic_collection\" in collection \"example_m2a\" or it does not exist. Queried in \"m2a\".\n    at createFieldsForbiddenError (/directus/api/src/permissions/modules/process-ast/utils/validate-path/create-error.ts:16:9)\n    at validatePathExistence (/directus/api/src/permissions/modules/process-ast/utils/validate-path/validate-path-existence.ts:16:9)\n    at processAst (/directus/api/src/permissions/modules/process-ast/process-ast.ts:28:4)\n    at ItemsService.readByQuery (/directus/api/src/services/items.ts:500:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ItemsService.readOne (/directus/api/src/services/items.ts:564:19)\n    at <anonymous> (/directus/api/src/controllers/items.ts:109:18)"}}]}
```

### PR DESCRIPTION
**Pull request by rijkvanzanten**
## Scope

What's changed:

- Fixed an issue that would cause the API to return a 500 error when a builder m2a field was queried without specifying nested fields.

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- Simple fix, simple review 🤞🏻 

---

Fixes #23179

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Test failure is unrelated to this PR

**Comment by rijkvanzanten** [comment]
Test failure was resolved in https://github.com/directus/directus/pull/23184

**Review by hanneskuettner — APPROVED** [review]
🎸

**Comment by arladmin** [comment]
Another active issue/bug (https://github.com/directus/directus/issues/23338), possibly related to/extension of this issue.

**Comment by hanneskuettner** [comment]
> Another active issue/bug (https://github.com/directus/directus/issues/23338), possibly related to/extension of this issue.

Unrelated, but similar

**Pull request merged**
