### PR TITLE
revisions for CRUD operations with $full

### LINKED ISSUE #15346: Flows: No revisions tracked when doing CRUD operations with full permission
### Describe the Bug

I created some flow to update items, but when the item is updated by the flow, I can't find the change log in Revisions panel:

image

(Only records modified directly by the user can be found, not those modified by the system.)

### To Reproduce

- Create a flow that updates any value of a item (Both the event-hook jobs and CRON tasks seem to have problems).
- Trigger the flow.
- Open the changed item's revisions.

### Errors Shown

_No response_

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

MySQL 8.0

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker Compose

### PR DESCRIPTION
**Pull request by freekrai**
## Description

This PR addresses the fact that when no user is set in flows aka system or `$full` permissions operations, then the app didn't store revisions to track the changes.

Originally, it set the `customAccountability` to null, now it will set it as follows:

```jsx
customAccountability = {
  user: null,
  role: null,
  admin: true,
  app: true,
  ip: '',
  userAgent: '',
  origin: '',
  share: undefined,
  share_scope: undefined,
  permissions: [],
};
```
This leads to revisions being created by the flow so we can track the changes.

Addresses #15345, fixes #15346

## Type of Change

- [X] Bugfix
- [X] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Review by licitdev — CHANGES_REQUESTED** [review]
Thank you for the PR. It works well for the item update operation. 👍 

This change should be propagated to all operations that has `permissions === '$full'`. Let's also extract the `customAccountability` conditional code-block into a util such as `getOperationCustomAccountability`. 🙂

**Comment by freekrai** [comment]
Right will push an update shortly

**Comment by freekrai** [comment]
@licitdev I've moved the codeblock into `getAccountabilityForRole` as a `system` role,  and updated create, update read, and delete to use it. 

So that calling:

```
customAccountability = await getAccountabilityForRole('system', { database, schema, accountability });
```

returns the block I had above, this lets it work the same as public, trigger or anything else.

**Review by licitdev — APPROVED** [review]
LGTM! 👍

**Pull request merged**
