### PR TITLE
Implement query hook

### PR DESCRIPTION
**Pull request by sebj54**
Hi there!

Here's my PR about the new query hook (see https://github.com/directus/directus/discussions/10486).

Usage:

```js
module.exports = function registerHook({ query }, { services, exceptions }) {
    query('items.read', async (query, { collection }, { schema, accountability }) => {
        if (collection === 'my_test_collection') {
            const newQuery = { ...query }
            newQuery.filter = {
                id: {
                    _eq: 1,
                }
            }
            query = newQuery
        }

        return query
    })
}

```

I'd like to know your thoughts before merging, because I'm not 100% sure about some points.

1️⃣ When I register a hook, I have to add an event name (I use `items.read`), but I'm not sure it is needed or relevant. Maybe we should keep it for some unknown future usage?

2️⃣ There are two variables named `query`  in my example. I'm afraid it won't be clear for everyone.

3️⃣ I have to create a `newQuery` object in my hook. If I try to add a `filter` to the `query` object, and try to log `query.filter` then, it is `undefined`. Are query objects immutable?

I also plan to add some docs before merging.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Ahhhh I was thinking we'd add a new _event_ `items.query` that fires as an existing `filter`, instead of adding a new hook _type_ (one of actions/filters/init).. 😬

**Comment by rijkvanzanten** [comment]
Yeah! That's exactly what I was thinking. The payload in filter hooks is mutable, so you'd be able to do something like 

```js
module.exports = function registerHook({ filter }, { services, exceptions }) {
    filter('items.query', async (payload, { collection }, { schema, accountability }) => {
        payload.limit = 1;
        return payload
    })
}
```

> I also noticed the hook I created is not triggered for system collections but I don't know if it is expected or if I missed something.

That's correct, they're firing under the different system scopes (so `users.read` instead of `items.read`)

**Comment by sebj54** [comment]
Ok, I've done the canges (the commit is way lighter now). But `payload` is still immutable on my side 😐 

```js
module.exports = function registerHook({ filter }, { services, exceptions }) {
    filter('items.query', async (payload, { collection }, { schema, accountability }) => {
        payload.limit = 1;
        console.log(payload.limit) // undefined
        return payload
    })
}
```

**Comment by sebj54** [comment]
Hi @rijkvanzanten, just passing by and wanted to know if there is anything blocking for this PR.

I rebased my branch to include latest changes (version 9.4.3). 

I don't know if the "immutable" payload is really a problem finally. I noticed that `payload.filter` is mutable, but you can't add a `filter` property to the payload if it is not already present. The same behavior occurs on other properties like `limit`.

So this is the actual behavior when you hit `/items/foo` (without query parameter):

```js
module.exports = function registerHook({ filter }, { services, exceptions }) {
    filter('items.query', async (payload, { collection }, { schema, accountability }) => {
        console.log(payload.limit) // undefined
        payload.limit = 1;
        console.log(payload.limit) // undefined
        return payload
    })
}
```

I have to do this to make it work:

```js
module.exports = function registerHook({ filter }, { services, exceptions }) {
    filter('items.query', async (payload, { collection }, { schema, accountability }) => {
        payload = { ...payload }
        console.log(payload.limit) // undefined
        payload.limit = 1;
        console.log(payload.limit) // 1
        return payload
    })
}
```

I don't know if it is because I use "vanilla" JS and not TypeScript.

Let me know if I can try anything out.

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Docs commit https://github.com/directus/docs/commit/57c11792cc0ee10f21e93ab6a6f0d917ab39e91d

**Comment by tinchoz49** [comment]
that was fast, thank you @rijkvanzanten!

**Comment by sebj54** [comment]
Thank you for the merge! :) Glad to have contributed to this awesome tool!

**Pull request merged**
