### PR TITLE
Added user existence check when migrating legacy comments

### PR DESCRIPTION
**Pull request by licitdev**
## Scope

What's changed:

- Added user existence check when migrating legacy comments to prevent invalid foreign key errors on `user_created`
- Added a simple array-based caching to reduce need to check user existence

### CODE REVIEW

**Review by ComfortablyCoding — APPROVED** [review]
Code LGTM!

**Review by br41nslug — APPROVED** [review]
lgtm, non-existing users get set to null

**Comment by MCl57** [comment]
Unfortunately, this error occurs now? Nothing has changed regarding the authorization of the database.

before:
git clone 11.13.2
pnpm install
pnpm build
```
PS C:\work\Directus\directus> pnpm --filter api cli bootstrap

> @directus/api@23.2.2 cli C:\work\Directus\directus\api
> NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"

C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packets\packet.js:738
    const err = new Error(message);
                ^

Error: Access denied for user 'directus'@'%' to database 'directusdb'
    at Packet.asError (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packets\packet.js:738:17)
    at ClientHandshake.execute (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_DBACCESS_DENIED_ERROR',
  errno: 1044,
  sqlState: '42000',
  sqlMessage: "Access denied for user 'directus'@'%' to database 'directusdb'",
  sql: undefined
}

Node.js v18.19.1
```

**Comment by licitdev** [comment]
@MCl57 I could not reproduce your issue, kindly double-check the database credentials.

**Comment by MCl57** [comment]
sorry network error. but the error still occour:
install
```
PS C:\work\Directus\directus> pnpm install
Scope: all 39 workspace projects
 WARN  There are cyclic workspace dependencies: C:\work\Directus\directus\api, C:\work\Directus\directus\directus
Lockfile is up to date, resolution step is skipped
Packages: +2330
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2330, reused 2300, downloaded 0, added 2330, done

devDependencies:
+ @changesets/cli 2.27.9
+ @directus/release-notes-generator 1.0.1 <- packages\release-notes-generator
+ @eslint/js 9.12.0
+ @types/eslint__js 8.42.3
+ @types/node 18.19.55
+ eslint 9.12.0
+ eslint-config-prettier 9.1.0
+ eslint-plugin-vue 9.28.0
+ globals 15.11.0
+ prettier 3.1.0
+ typescript 5.6.3
+ typescript-eslint 8.8.1

Done in 1m 5.2s
```

build
```
PS C:\work\Directus\directus> pnpm build

> directus-monorepo@ build C:\work\Directus\directus
> pnpm --recursive --filter '!docs' run build

Scope: 37 of 39 workspace projects
packages/specs build$ swagger-cli bundle src/openapi.yaml -o dist/openapi.json
│ Created dist\openapi.json from src/openapi.yaml
└─ Done in 4.5s
packages/constants build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 2.48 KB
│ ESM ⚡️ Build success in 1646ms
│ DTS ⚡️ Build success in 3958ms
│ DTS dist\index.d.ts 2.44 KB
└─ Done in 13s
packages/format-title build$ pnpm run '/^bundle|typecheck$/'
[4 lines collapsed]
│ . bundle: CLI tsup v8.3.0
│ . bundle: CLI Target: es2022
│ . bundle: ESM Build start
│ . bundle: DTS Build start
│ . typecheck: Done
│ . bundle: ESM dist\index.js 3.77 KB
│ . bundle: ESM ⚡️ Build success in 1391ms
│ . bundle: DTS ⚡️ Build success in 4125ms
│ . bundle: DTS dist\index.d.ts 122.00 B
│ . bundle: Done
└─ Done in 13.1s
packages/components build$ vite build
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387ms
│ vite v5.2.11 building for production...
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387ms
│ transforming...
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387mss in 779ms
│ ✓ 1 modules transformed.
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387mss in 779ms
│ Generated an empty chunk: "index".
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387mss in 779ms
│ rendering chunks...
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387mss in 779ms
│ [vite:dts] Start generate declaration files...
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387mss in 779ms
│ computing gzip size...
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387mss in 779ms
│ dist/index.js  0.00 kB │ gzip: 0.02 kB
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387mss in 779ms
│ [vite:dts] Declaration files built in 3978ms.
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387mss in 779ms
│ ✓ built in 4.08s
└─ Running...
packages/random build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.jsondex.ts --format=esm --dts
│ CLI tsup v8.3.0
│ CLI Target: es2022: tsconfig.json
│ ESM Build start
│ DTS Build start
│ ESM dist\index.js 915.00 B
│ ESM ⚡️ Build success in 1461ms
│ DTS ⚡️ Build success in 4057ms
│ DTS dist\index.d.ts 1.13 KB
└─ Done in 13s
packages/release-notes-generator build$ tsc --project tsconfig.prod.json
└─ Done in 5s
packages/schema build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 73.99 KB
│ ESM ⚡️ Build success in 387mss in 779ms
└─ Done in 39.1st
│ DTS ⚡️ Build success in 6282ms
│ DTS dist\index.d.ts 2.68 KBccess in 7377ms
└─ Done in 8.6s
packages/storage build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022 49.86 KB
│ ESM Build start
│ ESM dist\index.js 762.00 B
│ ESM ⚡️ Build success in 138ms
│ DTS Build start
│ DTS ⚡️ Build success in 3277ms
│ DTS dist\index.d.ts 1.87 KBB
└─ Done in 5.5s
packages/stores build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022et: es2022
│ ESM Build start
│ ESM dist\index.js 857.00 B
│ ESM ⚡️ Build success in 171mss in 779ms
│ DTS Build start
│ DTS ⚡️ Build success in 5394ms
│ DTS dist\index.d.ts 1.75 KBccess in 7377ms
└─ Done in 8.1s
packages/system-data build$ NODE_ENV=production tsup
[6 lines collapsed]
│ CJS Build start
│ ESM Build start
│ CJS dist\index.cjs 49.86 KB
│ CJS ⚡️ Build success in 1008ms
│ DTS Build start
│ ESM dist\index.js 49.26 KB
│ ESM ⚡️ Build success in 1111ms
│ DTS ⚡️ Build success in 1566ms
│ DTS dist\index.d.cts 4.92 KB
│ DTS dist\index.d.ts  4.92 KB
└─ Done in 4.5s
packages/update-check build$ pnpm run '/^bundle|typecheck$/'
[4 lines collapsed]
│ . bundle: CLI tsup v8.3.0
│ . bundle: CLI Target: es2022
│ . bundle: ESM Build start
│ . bundle: ESM dist\index.js 3.13 KB
│ . bundle: ESM ⚡️ Build success in 779ms
│ . bundle: DTS Build start
│ . typecheck: Done
│ . bundle: DTS ⚡️ Build success in 7377ms
│ . bundle: DTS dist\index.d.ts 94.00 B
│ . bundle: Done
└─ Done in 12.8s
packages/errors build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 10.51 KB
│ ESM ⚡️ Build success in 759ms
│ DTS Build start
│ DTS ⚡️ Build success in 6991ms
│ DTS dist\index.d.ts 8.30 KB
└─ Done in 9.9s
packages/storage-driver-local build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 3.91 KB
│ ESM ⚡️ Build success in 479ms
│ DTS Build start
│ DTS ⚡️ Build success in 6264ms
│ DTS dist\index.d.ts 1.44 KB
└─ Done in 9s
packages/types build$ tsc
└─ Done in 6.4s
sdk build$ NODE_ENV=production tsup
[8 lines collapsed]
│ DTS Build start
│ CJS dist\index.cjs     45.64 KB
│ CJS dist\index.cjs.map 66.41 KB
│ CJS ⚡️ Build success in 4302ms
│ ESM dist\index.js     41.33 KBms
│ ESM dist\index.js.map 59.28 KBms
│ ESM ⚡️ Build success in 4408ms
│ DTS ⚡️ Build success in 11107ms
│ DTS dist\index.d.cts 156.83 KB
│ DTS dist\index.d.ts  156.83 KB
└─ Done in 14.4s
packages/utils build$ pnpm run '/^build:.*/'
[26 lines collapsed]
│ . build:shared: DTS Build start
│ . build:node: DTS ⚡️ Build success in 3689ms
│ . build:node: DTS dist\node\index.d.ts 1.66 KB
│ . build:node: Done
│ . build:browser: DTS ⚡️ Build success in 6676ms
│ . build:browser: DTS dist\browser\index.d.ts 149.00 B
│ . build:browser: Done
│ . build:shared: DTS ⚡️ Build success in 9241ms
│ . build:shared: DTS dist\shared\index.d.ts 8.05 KB
│ . build:shared: Done
└─ Done in 12.3s
packages/env build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 16.96 KB
│ ESM ⚡️ Build success in 755ms
│ DTS Build start
│ DTS ⚡️ Build success in 6077ms
│ DTS dist\index.d.ts 90.00 B
└─ Done in 8.2s
packages/memory build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 13.57 KB
│ ESM ⚡️ Build success in 683ms
│ DTS Build start
│ DTS ⚡️ Build success in 7695ms
│ DTS dist\index.d.ts 13.45 KB
└─ Done in 9.8s
packages/pressure build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 2.25 KB
│ ESM ⚡️ Build success in 273ms
│ DTS Build start
│ DTS ⚡️ Build success in 5465ms
│ DTS dist\index.d.ts 885.00 B
└─ Done in 7.6s
packages/storage-driver-azure build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 3.74 KB
│ ESM ⚡️ Build success in 234ms
│ DTS Build start
│ DTS ⚡️ Build success in 8519ms
│ DTS dist\index.d.ts 1.52 KB
└─ Done in 10.5s
packages/storage-driver-cloudinary build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 13.81 KB
│ ESM ⚡️ Build success in 315ms
│ DTS Build start
│ DTS ⚡️ Build success in 5346ms
│ DTS dist\index.d.ts 2.85 KB
└─ Done in 8s
packages/storage-driver-gcs build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 3.54 KB
│ ESM ⚡️ Build success in 255ms
│ DTS Build start
│ DTS ⚡️ Build success in 6442ms
│ DTS dist\index.d.ts 1.46 KB
└─ Done in 9.2s
packages/storage-driver-s3 build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 12.18 KB
│ ESM ⚡️ Build success in 258ms
│ DTS Build start
│ DTS ⚡️ Build success in 18784ms
│ DTS dist\index.d.ts 2.08 KB
└─ Done in 21.6s
packages/storage-driver-supabase build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 6.46 KB
│ ESM ⚡️ Build success in 346ms
│ DTS Build start
│ DTS ⚡️ Build success in 4827ms
│ DTS dist\index.d.ts 1.76 KB
└─ Done in 7.3s
packages/themes build$ vite build
│ vite v5.2.11 building for production...
│ transforming...
│ ✓ 21 modules transformed.
│ rendering chunks...
│ [vite:dts] Start generate declaration files...
│ computing gzip size...
│ dist/index.js  40.88 kB │ gzip: 5.42 kB
│ [vite:dts] Declaration files built in 11931ms.
│ ✓ built in 12.52s
└─ Done in 16.9s
packages/validation build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 5.39 KB
│ ESM ⚡️ Build success in 117ms
│ DTS Build start
│ DTS ⚡️ Build success in 3965ms
│ DTS dist\index.d.ts 726.00 B
└─ Done in 5.7s
packages/extensions build$ pnpm run '/^build:.*/'
[14 lines collapsed]
│ . build:node: ESM dist\node.js 11.64 KB
│ . build:node: ESM ⚡️ Build success in 406ms
│ . build:node: DTS Build start
│ . build:shared: DTS Build start
│ . build:shared: DTS ⚡️ Build success in 12835ms
│ . build:shared: DTS dist\index.d.ts 54.57 KB
│ . build:shared: Done
│ . build:node: DTS ⚡️ Build success in 13434ms
│ . build:node: DTS dist\node.d.ts 55.17 KB
│ . build:node: Done
└─ Done in 16.7s
packages/composables build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 20.58 KB
│ ESM ⚡️ Build success in 307ms
│ DTS Build start
│ DTS ⚡️ Build success in 5631ms
│ DTS dist\index.d.ts 6.33 KB
└─ Done in 7.6s
packages/extensions-registry build$ tsup src/index.ts --format=esm --dts
│ CLI Building entry: src/index.ts
│ CLI Using tsconfig: tsconfig.json
│ CLI tsup v8.3.0
│ CLI Target: es2022
│ ESM Build start
│ ESM dist\index.js 7.08 KB
│ ESM ⚡️ Build success in 307ms
│ DTS Build start
│ DTS ⚡️ Build success in 5771ms
│ DTS dist\index.d.ts 21.72 KB
└─ Done in 7.7s
packages/extensions-sdk build$ tsc --project tsconfig.prod.json
└─ Done in 9.8s
app build$ vite build
[1014 lines collapsed]
│ dist/assets/ru-RU-DDfYu0LB.js                             143.99 kB │ gzip:    50.96 kB
│ dist/assets/sq-AL-Dkr8fhVv.js                             144.33 kB │ gzip:    46.07 kB
│ dist/assets/it-IT-B4TsjQHQ.js                             145.28 kB │ gzip:    44.42 kB
│ dist/assets/es-ES-DVlnu9-4.js                             145.41 kB │ gzip:    45.47 kB
│ dist/assets/fr-CA-dLv9K1y8.js                             148.65 kB │ gzip:    45.97 kB
│ dist/assets/fr-FR-B057QF8S.js                             148.73 kB │ gzip:    45.95 kB
│ dist/assets/index-B9l9rlci.js                             442.66 kB │ gzip:   123.49 kB
│ dist/assets/input-rich-text-html-J4Lgn5nk.js            1,268.10 kB │ gzip:   439.74 kB
│ dist/assets/index.fQyoBOfK.entry.js                     5,790.89 kB │ gzip: 1,725.47 kB
│ ✓ built in 1m 11s
└─ Done in 1m 25.9s
api build$ tsc --project tsconfig.prod.json && copyfiles "src/**/*.{yaml,liquid}" -u 1 dist
└─ Done in 32.3s
```


start
```

PS C:\work\Directus\directus> pnpm --filter api cli bootstrap

> @directus/api@23.2.2 cli C:\work\Directus\directus\api
> NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"

[10:19:58.498] INFO: Initializing bootstrap...
[10:19:58.509] INFO: Installing Directus system tables...
[10:20:00.394] INFO: Running migrations...
[10:20:00.431] INFO: Applying Remove Collection Foreign Keys...
[10:20:00.674] INFO: Applying Remove System Relations...
[10:20:00.706] INFO: Applying Remove System Collections...
[10:20:00.744] INFO: Applying Remove System Fields...
[10:20:00.776] INFO: Applying Add Cascade System Relations...
[10:20:02.215] INFO: Applying Change Webhook URL Type...
[10:20:02.298] INFO: Applying Add Relations Sort Field...
[10:20:02.360] INFO: Applying Remove Locked Fields...
[10:20:02.444] INFO: Applying Webhooks Collections Text...
[10:20:02.531] INFO: Applying Add Refresh Interval...
[10:20:02.601] INFO: Applying Make Filesize Nullable...
[10:20:02.690] INFO: Applying Add Collections Accountability...
[10:20:02.748] INFO: Applying Remove Files Interface...
[10:20:02.785] INFO: Applying Rename Interfaces...
[10:20:02.874] INFO: Applying Restructure Relations...
[10:20:03.073] INFO: Applying Add Foreign Key Constraints...
[10:20:03.194] INFO: Applying Add System Fk Triggers...
[10:20:04.111] INFO: Applying Add Collections Icon Color...
[10:20:04.167] INFO: Applying Add Insights...
[10:20:04.420] INFO: Applying Add Deep Clone Config...
[10:20:04.482] INFO: Applying Change Filesize Bigint...
[10:20:04.578] INFO: Applying Add Conditions to Fields...
[10:20:04.641] INFO: Applying Add Default Folder...
[10:20:04.764] INFO: Applying Replace Groups...
[10:20:04.795] INFO: Applying Add Required to Fields...
[10:20:04.858] INFO: Applying Update Groups...
[10:20:04.907] INFO: Applying Change Image Metadata Structure...
[10:20:04.948] INFO: Applying Add Geometry Config...
[10:20:05.017] INFO: Applying Remove Limit Column...
[10:20:05.087] INFO: Applying Add Auth Provider...
[10:20:05.330] INFO: Applying Webhooks Collections Not Null...
[10:20:05.405] INFO: Applying Move Module Setup...
[10:20:05.496] INFO: Applying Webhooks URL Not Null...
[10:20:05.572] INFO: Applying Add Collection Organization...
[10:20:05.689] INFO: Applying Replace Fields Group...
[10:20:05.807] INFO: Applying Replace M2M Interface...
[10:20:05.839] INFO: Applying Rename Login Action...
[10:20:05.869] INFO: Applying Update Presets...
[10:20:05.963] INFO: Applying Add Auth Data...
[10:20:06.022] INFO: Applying Add Webhook Headers...
[10:20:06.074] INFO: Applying Set Unique to User Token...
[10:20:06.135] INFO: Applying Update Special Geometry...
[10:20:06.163] INFO: Applying Remove Collections Listing...
[10:20:06.221] INFO: Applying Add Notifications...
[10:20:06.423] INFO: Applying Add Shares...
Error: alter table `directus_sessions` modify  `user` char(36) null  - Got error 42 "No message of desired type" from storage engine InnoDB
    at Packet.asError (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packets\packet.js:738:17)
    at Query.execute (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\work\Directus\directus\node_modules\.pnpm\mysql2@3.11.3\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_GET_ERRNO',
  errno: 1030,
  sqlState: 'HY000',
  sqlMessage: 'Got error 42 "No message of desired type" from storage engine InnoDB',
  sql: 'alter table `directus_sessions` modify  `user` char(36) null '
}
C:\work\Directus\directus\api:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @directus/api@23.2.2 cli: `NODE_ENV=development SERVE_APP=false tsx src/cli/run.ts "bootstrap"`
Exit status 1
```

**Pull request merged**
