### PR TITLE
Docs: getting-started > architecture

### PR DESCRIPTION
**Pull request by erondpowell**
TODO:

- [x] Write copy
- [x] Edit with Grammarly
- [x] Add in media
- [x] Tag management to review

[closes 105](https://github.com/directus/organization/issues/105)

### CODE REVIEW

**Comment by erondpowell** [comment]
@benhaynes 
https://deploy-preview-13258--directus-docs.netlify.app/getting-started/architecture/

**Review by rijkvanzanten — APPROVED** [review]
LGTM!

The only thing I'm not super sure about is the order of this in the navigation 🤔 

@benhaynes thoughts? We might want to move this a little further down the bottom, as it is a little more in-depth kinda info 
CleanShot 2022-06-06 at 21 26 45@2x

**Comment by benhaynes** [comment]
> We might want to move this a little further down the bottom, as it is a little more in-depth kinda info

Yeah, I think below installation might be better now that I'm seeing it. Or we could roll it into `Introduction` too 🤔

**Comment by rijkvanzanten** [comment]
Sounds good to me!

**Pull request merged**
