### PR TITLE
Enable cors (start)

### PR DESCRIPTION
**Pull request by Malusovium**
For now only the hack:
Handling the pre-flight request.
And setting the custom headers in through Apache

discussion/implementation in: 
#1291

### CODE REVIEW

**Comment by benhaynes** [comment]
Looking forward to the cleaned up version – but this is a great idea/start! Thanks @michieltjuh11!

**Comment by michieltjuh11** [comment]
This should work.
I wonder if setting the CORS values through settings(ui) is a good idea,
as it may introduce security concerns.

**Comment by WellingGuzman** [comment]
Thanks @michieltjuh11, I will test this later today and see how it goes. Although it will probably be best to be in the `configuration.php` but either way I will merge it an take it from there if it's working as expected.

**Comment by WellingGuzman** [comment]
Hey @michieltjuh11 did you test this? it doesn't work for me. Am I missing something?

**Comment by WellingGuzman** [comment]
It seems there's a type in [here](https://github.com/directus/directus/pull/1292/files#diff-8b70e60a0ec4a114cd218f61f7857d05R19) and [here](https://github.com/directus/directus/pull/1292/files#diff-8b70e60a0ec4a114cd218f61f7857d05R20)

As well the options don't return any headers cors headers.

Let me know if I'm missing or doing something wrong.

**Comment by WellingGuzman** [comment]
@michieltjuh11 can you please change it to merge with `development` branch instead of `master`?

**Comment by michieltjuh11** [comment]
When working with CORS,
An ajax request is made with the OPTIONS (handling preflight),
if it returns 200 it will send the next request(the actual request) with (GET, POST).
where allow headers must be the same as the request headers.

**Comment by WellingGuzman** [comment]
Thanks for changing back to development, but still has a typo and it doesn't work correctly to me. does it work for you? if you wish I can merge it and take it from here. sounds good?

Thanks for this solutions.

**Comment by michieltjuh11** [comment]
Okay, it works for me when the request headers match the allow-headers.
GL, if I may still be of some help git me up:)

**Comment by WellingGuzman** [comment]
As it is, I tried it but didn't work, then I fixed the typo, and add the header on options requests and worked.

Trying to understand if there's more than a way to work. As I expected should work as I'm doing it, but I'm more interesting in know why is work for you and it doesn't to me.

@michieltjuh11 are you on our Slack? we can talk more about it over there.

**Comment by michieltjuh11** [comment]
Not at the moment I would like to join ^^

**Comment by WellingGuzman** [comment]
Great, Send me an email to: `welling [at] rngr.org` and I will send you and invitation.

**Comment by michieltjuh11** [comment]
@WellingGuzman  I found out what went wrong...
Was working with docker-compose and the volume didn't connect properly(typo in the docker-compose.yml). Long story short I should ask the null-hypothesis more often ;)

**Comment by WellingGuzman** [comment]
Perfect @michieltjuh11, I didn't forget this PR. I will be merging it soon 👍

**Pull request merged**
