### PR TITLE
GraphQL 2.0

### LINKED ISSUE #4283: Support fragments in GraphQL for non-union types
The graphql fragments seem to be buggy at the moment.
I created one collection called "pages" with a standard string field "title" in the latest docker rc-release of directus v9.0.0-rc.43.

I made the collection public accessible and now I played with graphql:

```graphql

{
  items {
    pages {
      id
      title
    }
  }
}
```
and get (as expected)
```json
{
  "data": {
    "items": {
      "pages": [
        {
          "id": "1",
          "title": "My page"
        }
      ]
    }
  }
}
```
Now i want to use a fragment to get the same:
```graphql
fragment foo on pages {
  id
  title
}

{
  items {
    pages {
      ...foo
    }
  }
}
```
and things get weird:
```json
{
  "data": {
    "items": {
      "pages": [
        {
          "id": "1",
          "title": null
        }
      ]
    }
  }
}
```
I don't understand why `id` is set but `title` is `null` in that case. I think this is a bug.
Thanks for your help and your ongoing work for 9.0!

### LINKED ISSUE #4561: Add GraphQL Mutations support
Ref https://github.com/directus/directus/discussions/3052

### LINKED ISSUE #4627: Add "by key" fields in GraphQL
Right now, the full CRUD operations can only be done on list-sets in GraphQL. We should have a way where you can operate on just a single item by key.

Adding a suffix to the query/mutation field name seems to be most convenient: `articles {...}` -> `articles_by_key(id: "abc") {...}`

(We _could_ alternatively use some way to guess the singular/plural name of a collection, by using something like https://graphql-compose.github.io/docs/api/misc-api-methods.html#getpluralname, but that feels super tricky cross-language)

### LINKED ISSUE #4663: Graphql vs Singleton - Expected Iterable, but did not find one for field...
Not sure if still relevant as graphql is being revamped #4625
I'm using rc.51

### Describe the bug

Query expects an Iterable while trying to get a singular collection 'global'.

graphql Query.items (collections)

```
metadata(
sort: [String]
limit: Int
offset: Int
page: Int
search: String
filter: metadata_filter): [metadata]

global(
sort: [String]
limit: Int
offset: Int
page: Int
search: String
filter: global_filter): [global] <-this one should be singular!
```

### Steps to reproduce the behavior

1. Create a singular collection
2. Grant read permissions to it (also directus_collections.collection and directus_fields.field, see #4433)
3. Go go /graphql and try this query

```
{
  items {
    <your_collection> {
      id
    }
  }
}
```
Result

```
{
  "errors": [
    {
      "message": "Expected Iterable, but did not find one for field \"items.test\".",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "items",
        "test"
      ]
    }
  ],
  "data": {
    "items": {
      "test": null
    }
  }
}
```

### Expected behavior

Either an array (as described by schema) or a single object (as expected) in data.items.test

### Screenshots

grq

_test is singular, metadata is a regular collection_

### System

- Strapi version: 9.0.0 rc.51
- Database: SQLite
- Operating system: macos

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Closes https://github.com/directus/directus/discussions/4265, closes #4561, closes #4627

This also splits up the system _stuff_ from the non-system _stuff_ in two different endpoints: `/graphql/` and `/graphql/system/`.

Note: this does not yet include _non-crud_ system operations, like auth-login or create-comment.

Fixes #4625, fixes #4663, closes https://github.com/directus/directus/issues/4283

---

### To-do:

- [x] Update Gatsby source to match changes in this PR 
- [x] Add https://github.com/directus/directus/issues/4627

### CODE REVIEW

**Comment by emregency** [comment]
Hey @rijkvanzanten, 
don’t you think the ‘items’ is now redundant as we split the endpoints?

**Comment by rijkvanzanten** [comment]
> Hey @rijkvanzanten, 
> 
> don’t you think the ‘items’ is now redundant as we split the endpoints?

I split it up just for this reason 😉 This PR gets rid of that items scoping

**Comment by rdsubhas** [comment]
Hi @rijkvanzanten this is amazing, thanks a lot!!

A small query please. directus _(v8 and v9)_ allows relationships to system collections. Example: we can create a collection which relates to the directus_user.

image

In v8, we were able to retrieve both items and their related users.

In v9, if the graphQL system and items endpoints are split separately, would can these relationships still be retrieved? Thanks!

**Comment by rdsubhas** [comment]
Awesome, thanks a bunch!

**Pull request merged**
