### PR TITLE
skip interface options for variable panel

### LINKED ISSUE #15592: Dashboard global variable value is undefined within autocomplete interface
### Describe the Bug

The `{{value}}` part in the autocomplete is undefined when used within the Global Variable Panel in Dashboards.
Screenshot 2022-09-15 at 13 35 32

### To Reproduce
Screenshot 2022-09-15 at 13 35 11

In dashboards, create a new Global variable and select the `Autocomplete Input` as interface.

For testing, just put in the url `/items/COLLECTION?search={{value}}` replace collection with the name of one of your existing collections.

Now save and try to search in the autocomplete. Via inspect tools in network, notice the search term is undefined. 

### Errors Shown

_No response_

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chromium

### How are you deploying Directus?

Locally & GCP

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

This excludes all interface options for the variable panel from being parsed before they're passed to the panel.
For auto-complete the URL template was being parsed into `/items/test?search=undefined` before the interface gets it.
Not sure if this is too broad of a solution but i couldnt find any usecases yet for having variables used directly in interface options.

Fixes #15592

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
... although that being said, I think there's a case to be made for that. For example, it would be pretty cool if you could use a collections-dropdown relational select as one variable, and then use that selected collection in the configuration for the relational select variable panel 🤔

**Comment by u12206050** [comment]
This does fix the issue I have with the autocomplete field. So as a PR it good.

Btw, the fix itself doesn't mean you can't use other dashboard variables in the options, it just means that if it is undefined, then it leaves it as is.

**Review by u12206050 — APPROVED** [review]
Works, without any noticeable side affects.

**Comment by rijkvanzanten** [comment]
> Btw, the fix itself doesn't mean you can't use other dashboard variables in the options, it just means that if it is undefined, then it leaves it as is.

Ohhh right right, cool! All good then 🙂

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
