### PR TITLE
Add calendar layout

### PR DESCRIPTION
**Pull request by rijkvanzanten**
From @Nitwel: 

---

grafik

Adds the calendar layout to the next gen version of directus. 🚀 

<details>
  <summary>More Images</summary>
Week view

grafik

Agenda view

grafik

</details>

**Features**
- Normal calendar view.
- Time relative weekly view and single day view.
- Agenda view (Timeline)
- Support for Datetime, Date, Date&Time,
- Color support

**Todo**
- [x] Add year dropdown
- [x] Add time axis to day view (if  wanted)
- [x] Clean up code
- [x] Scrolling interactions
- [x] Click interactions (Click on day...)
- [x] Year view (maybe?)
- [ ] Proper way to display all events in the month view
- [x] ~~Support status colors (Dont know how to do that yet properly)~~
- [x] ~~Get the collection header smaller?~~
- [x] Fix layout height
- [x] Add on specific date button
- [x] Add select functionality

### CODE REVIEW

**Comment by hakki264ulku** [comment]
This is a perfect feature that I really do love! I hope this will be added soon :)

**Comment by benhaynes** [comment]
We're working on it! Any third party reviews from contributors would speed things up!

**Comment by danieljwestman** [comment]
Looking forward to this PR 🚀 hope it's not forgotten 😬

**Comment by rijkvanzanten** [comment]
No definitely not. As a matter of fact, it's on the v9.0.0 blockers list 👍🏻

**Pull request merged**
