### PR TITLE
Add new project setting for custom error message that will be displayed to user when they try to set a password that doesn't meet the Auth Password Policy requirements.

### LINKED ISSUE #8661: Improve error messages when password doesn't meet policy requirements.
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Right now, when a user offers a password that doesn't meet the password complexity requirements, there error messages returned to the user could be more helpful.

For example, when accepting an invite, the user sees an `Unexpected Error`:
Unexpected error

And when resetting a password, they receive the much better but still not super clear `Value doesn't have the correct format`:
Value doesn't have the correct format

### To Reproduce

Scenario 1: Accept invite
1. Choose an `Auth Password Policy` other than `None` on the `/admin/settings/project` page;
2. Send an email invite to a new user;
3. Click the invite link and enter a password that doesn't meet the requirements;

Scenario 2: Reset password
1. Choose an `Auth Password Policy` other than `None` on the `/admin/settings/project` page;
2. Log in as an existing user and attempt to reset their password to a new one that doesn't meet the policy requirements.

Expected: User receives an error message stating that their password does not meet the password policy.
Actual: User receives `Unexpected Error` in scenario 1, and `Value doesn't have the correct format` in scenario 2.

In both cases, the directus logs contain messages showing `Provided password doesn't match password policy` -- can we return that to the user in both cases instead of the cryptic messages?

### What version of Directus are you using?

v9.0.0-rc.96

### What version of Node.js are you using?

v16.10.0 (from directus/directus:9.0.0-rc.96 docker image)

### What database are you using?

MariaDB 10.3.23

### What browser are you using?

Chrome 94.0.4606.71

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by TonyLovesDevOps**
Does what it says on the tin.

Resolves #8661.

### CODE REVIEW

**Comment by aidenfoxx** [comment]
@TonyLovesDevOps Why not just `invalid_password_message`? We only have the one check on passwords, so I think it would be fine.

I'm just wondering if localization will be a problem. I can already see the issue ticket. 😅

**Comment by juancarlosjr97** [comment]
Any update on this PR? I would like this feature to our instance :)

**Comment by benhaynes** [comment]
No update, we're trying to work through issues in PRs as efficiently as possible.

**Comment by juancarlosjr97** [comment]
Thank you for the reply @benhaynes :)

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Comment by abernh** [comment]
For everybody stuck with the ambiguous error message (e.g. on Directus Cloud without options to fix it) I posted a CSS-only hack here 

https://github.com/directus/directus/discussions/13896#discussioncomment-6275872

**Pull request closed without merging**
