### PR TITLE
Add the ability to format $NOW dates with adjustment.

### PR DESCRIPTION
**Pull request by ijpatricio**
## The issue

This addresses #11314 

Long story short: if we want to define in no_code validation, that a date field should be `greater or equal than tomorrow`, it's currently impossible. 

This is because the nearest option on the current API of the dynamic `$NOW`, is `$NOW(+1 day)`. In turn, this will add 24H to the current time of processing, which is correct. But "tomorrow" starts at 00h00, which makes it impossible to build such validation only with no_code.

Think not only "tomorrow", but also "following month".`$NOW(+1 month)` will add 30days, X hours, X minutes, and so on.
"Following month" starts on the next day 1, at 00h00.

I think it's clear now, but feel free to visit the discussion mentioned above.

## The solution

While the most beautiful solution would be to add an "expressive parser" that would understand things like:
- `$NOW(tomorrow)`
- `$NOW(tomorrow at 15h00)`
- `$NOW(next month, on the 20th at 12h00)`

... I believe we can solve this gracefully with a native solution of the library underneath, which is `date-fns`.

Having said so, we could leverage the native API, which exposes the [format](https://date-fns.org/v2.28.0/docs/format) function.

With the addition of such feature, we can now achieve such validations:

```
// "tomorrow"
$NOW(+1 day | format: yyyy-MM-dd 00:00)

// "next month"
$NOW(+1 month | format: yyyy-MM-01 00:00) 

//"on the 15th of following month"
$NOW(+1 month | format: yyyy-MM-15 00:00) 
```

All we have to do is to perform an adjustment, just like before, but then "pipe" (`|`) to another function, `format: xxxx`.
The value of `xxxx` will be used by `date-fns`, so every format and specification we can use, it's documented [here](https://date-fns.org/v2.28.0/docs/format#description).
I think it will not suffice to delegate users to go there and read, hence Directus docs make brief documentation of such, with the basic examples, and then reference to the extensive, hard documentation.

## My thinking process on the code implementation

First of all, disclaimer: I don't have much experience with TS 😅 

So, for now, we're only adding `format` task to the API, which makes `$NOW(+1 month | format: yyyy-MM-01 00:00)` possible and working.

What I did was:

- Current `adjustment` is the mainTask.
- More tasks can be added, sequentially, by piping.

This would make also possible:

```
$NOW(+1 month | format: yyyy-MM-01 00:00 | anotherTask: payloadForTask ) 
```

So, I split the whole adjustment by `|`, trim them, execute the first one exactly like before, and then process the rest.
Only if the task is `format`, then I delegate the processing to the native `data-fns/format`.
This is to allow possibility of the next topic.

Tests were added. They speak for themselves 😄 

All signatures, types remained intact.

## Considerations

As we can easily add more `piped tasks`, that would perform more actions on the `Date`object, I think we could also achieve to add a `hook` that could, of course, be customized by the default extension system!

Picture this:

```
$NOW( +1 day | _check: availability, rooms )
```

This could represent a call to the hook `now:_check`, providing as arguments:
- The `Date` object
- Payload: `availability, rooms`.

This hook `now:_check` must be a custom extension, so its developer is responsible to interpret payload, and return a `Date` object, or `undefined`.

This is a rough idea, but I hope the message goes through!

## Breaking changes

No breaking changes. This change is purely additive.

Thank you for your time!

### CODE REVIEW

**Comment by jakedowns** [comment]
is there any progress on this? i'd love to be able to query records created today ($NOW without timestamp)

**Comment by rijkvanzanten** [comment]
> i tried day(now) and day($NOW) but that doesn't work as expected

Hey that's a good idea. I like this syntax much better than trying to add additional scoping information into the $NOW(x) handler :o Doing `year($NOW(-30 days))` feels clean

**Comment by jakedowns** [comment]
> > i tried day(now) and day($NOW) but that doesn't work as expected
> 
> Hey that's a good idea. I like this syntax much better than trying to add additional scoping information into the $NOW(x) handler :o Doing `year($NOW(-30 days))` feels clean

yeah, tho, once i got day(date_created) working, i realized, it's only extracting `2` from `2022-11-02 11:59:00` for example. 
so, yeah, unless the behavior would be different, perhaps a more generic custom formatting parameter is still the best bet

or if a new extractor full_day_no_time($NOW) could be added, that could work

**Comment by ijpatricio** [comment]
OH NO!!

@rijkvanzanten I deleted the fork while cleaning up and wasn't aware this would happen.

So I think it's still very recoverable, given if such a feature is desired.

What do you think?

**Comment by rijkvanzanten** [comment]
The changes are still available in the patches under files, so we didn't lose anything 🙂 

As for reopening the PR, lets hold off on that for a moment. We've tweaked our contributing guidelines to tighten up the process a bit to ensure we actually have resources available to review, merge, and maintain 🙂

**Comment by ijpatricio** [comment]
Sure think @rijkvanzanten, no problem! 😄 Thanks for the heads up!

**Comment by Akanixon** [comment]
So how is the progress on this one? I was thinking of  using year($NOW) and month($NOW) in insights

**Pull request closed without merging**
