### PR TITLE
[WIP] Make adapters optional dependencies and adapter selection in UI

### PR DESCRIPTION
**Pull request by angelhodar**
Hey everyone! As discussed with @rijkvanzanten [here](https://github.com/directus/directus/discussions/5951), I have moved the adapters dependencies to optionalDependencies, because there is no need to install whole AWS sdk if not using S3. The new sdk v3 allows to import only what is needed btw.

I am also trying to give the user the possiblity to upload to a custom adapter in a per file basis with the UI. I am not an expert with Vue but I think I have added the code to allow it BUT the problem is that it only sends the storage parameter to the API when the route in the front already has the ?storage=s3 attribute before clicking upload. I just have to do it twice to get the form data with the storage preset set, I dont know why that happens.

### CODE REVIEW

**Comment by benhaynes** [comment]
Wow, this is great!! I've wanted this one for a while... thank you so much! We'll review asap. 💯

**Review by nickrum — COMMENTED** [review]
The dependency change looks good to me.

From looking at the code, I don't think the adapter selection will work this way, as the file is uploaded directly inside the `v-upload` component.

**Comment by angelhodar** [comment]
@nickrum Thats what I wanted to talk about. I know its not completed, but the thing is that I dont understand why the code in collection.vue has functionality to upload files apart from the v-upload component. It doesnt seems clear to me the flow of the code from the add-vue is closed to the upload-file function.

**Comment by rijkvanzanten** [comment]
Two thoughts:

* The storage adapter selection should be part of the v-upload, as that's used all over the place (instead of a separate field in the upload dialog)
* The storage adapters should be fetched from the API, instead of being hardcoded to the driver _types_. In the API, you can configure multiple storage locations using the same driver, which wouldn't work with this approach. Similarly, it's not a given that you use AWS when using the S3 driver, as there are many different S3 compatible services out there.

> why the code in collection.vue has functionality to upload files apart from the v-upload component

I'm assuming you're talking about the files module collection.vue file here. The file library page supports drag and drop to upload anywhere on the page, so that's a special one-off case that's separate from the v-upload component.

**Comment by rijkvanzanten** [comment]
This has been superseded by https://github.com/directus/directus/pull/16825

**Pull request closed without merging**
