### PR TITLE
Fix Condition operator can not work on flows

### PR DESCRIPTION
**Pull request by imiskolee**
## Description

Fixes #

1. multi Joi.object wrapper if nested
2. context.data will overwrite the keyedData, so can not access any keyedData on some operator.

related 
1. https://github.com/directus/directus/issues/13855
2. https://github.com/directus/directus/issues/14307

## Type of Change

- [ Y ] Bugfix
- [ Y ] Improvement

## Requirements Checklist

- [ Y ] New / updated tests are included
- [ Y ] All tests are passing locally
- [ Y ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by andy1li** [comment]
It seems #13855 was fixed by #13596.

**Comment by rijkvanzanten** [comment]
@andy1li You're correct. That being said, I believe the change in this PR might be a solution for (unconfirmed) bug #14571, so I don't wanna close it yet 👍🏻

**Comment by webforte** [comment]
> It seems #13855 was fixed by #13596.

Confirmed, after the upgrade the "not allowed" error is not showing up anymore. However the condition operation still seems broken.

**Review by brunoribei-ro — APPROVED** [review]

**Comment by imiskolee** [comment]
resolved all conflicts.

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
