### PR TITLE
save wysiwyg image size in url params instead of html tags

### PR DESCRIPTION
**Pull request by maltejur**
When adding or editing an image in the wysiwyg-editor, this
Screenshot_20211125_164635

Will be turned into
`211030 P125 58`

Instead of
`211030 P125 58`

This way the Directus API will resize the images server-side and the client just has to load the required size.

In the future, some more advanced UI would be nice where you can control the fitting behavior, lock the aspect ratio, have some options for higher DPI devices, etc. and I would also like to work on that, but for now I hope this is a good first step.

Closes #2796

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]
Awesome improvement. Thanks @maltejur!

**Comment by maltejur** [comment]
Hmm weird, I'll take a look.

**Comment by daveharrisonbcc** [comment]
> Hmm weird, I'll take a look if I can reproduce those errors.

Thank you. To clarify as I didn't word that comment very well, it's when you type into the editor that the text is inserted in reverse, e.g

detresni si egami retfA Before image is inserted

**Comment by maltejur** [comment]
I fixed and opened a pull request for the first error, thanks for noticing that.

I think the second error doesn't originate from this pull-request, it seems like the access token that is added to the image url temporarily doesn't become valid only until a few seconds after the picture has failed to load in the editor (You can inspect the broken image in the browser inspector, open it in a new tab, refresh with Ctrl+F5 and see that the image actually works). You should probably open a issue about that.

**Comment by daveharrisonbcc** [comment]
Thanks for looking into this and sorting the first reverse text issue, much appreciated! I'll open an issue for the image problem.

**Pull request merged**
