### PR TITLE
Fix start script

### PR DESCRIPTION
**Pull request by nickrum**

### CODE REVIEW

**Comment by nickrum** [comment]
@rijkvanzanten any idea what's going on with tests? I don't see how the test failing could be related to the changes in this PR.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten any idea what's going on with tests? 

No idea! Looks like Dockerhub had a moment (500)?

CleanShot 2021-09-14 at 09 10 34@2x

**Comment by nickrum** [comment]
Could be 🤔 The error message is strange, though.

And the test failed again!

**Comment by rijkvanzanten** [comment]
> And the test failed again!

Yeh seems to fail across the board :C We should look into it

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
