### PR TITLE
Fix thumbnails not displaying in Files interface

### LINKED ISSUE #15735: Files thumbnails are not showing in files interface
### Describe the Bug

Files thumbnails are not showing in files interface.

image

### To Reproduce

1. Create a collection A.
2. Create field B that is Multiple Files (m2m).
3. Select the Files interface.
4. Go to Content module and try to add some files into B field. Click Save.
5. You can see that thumbnails are not rendering.

### Errors Shown

_No response_

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

v17.9.0

### What database are you using?

SQLite 3

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

### PR DESCRIPTION
**Pull request by d1rOn**
## Description

**Fixes #15735**

Before:
image

After:
image

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by scorpion-orion — APPROVED** [review]
No new code. Just reordering some lines and it's fixed.

**Review by br41nslug — APPROVED** [review]
Solves issue https://github.com/directus/directus/issues/15735 (but not https://github.com/directus/directus/issues/15763 i've removed that linked issue from the description).

**Review by azrikahar — APPROVED** [review]
LGTM!

@Nitwel this PR does seems to "revert" and move the `get()` and undefined check under the thumbnail logic that was altered in #15243, which should explain why it does fix the thumbnail issue. With that said, would you mind taking an additional look here just in case?

**Review by Nitwel — APPROVED** [review]
Looks good to me too!

**Pull request merged**
