### PR TITLE
Fix strict relative dates showing "incorrect"

### LINKED ISSUE #14389: Date display when using `strict` is strictly incorrect
### Describe the Bug

When displaying a datetime field as relative, it usually display the date for 28 August 1991 as "Almost 31 years", however when selecting the `strict` option as well it changes to "31 years".

I think what should happen when `strict` is selected is that it rounds down, at least that makes more sense when using it as displaying someones age.

Already have a fix for this.

### To Reproduce

Create datetime field, select display option as relative with `strict` enabled.

Create an item and set the date to a day within next month, and a year older than 2 years ago.

Observe the date in the collection view display to be "off" by one year.

### Errors Shown

_No response_

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

Edge

### How are you deploying Directus?

Locally & GCP

### PR DESCRIPTION
**Pull request by u12206050**
## Description

Set rounding method of relative formatted date to floor when strict option is selected

After this fix:
RelativeDateTimeFix

Fixes #14389 

## Type of Change

- [x] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by benhaynes** [comment]
Wouldn't this mean that if a date was 12.9 years ago it would print `12 years ago`? I understand _strict_ n the sense of a person's age... but is this more broadly applicable? 🤔

**Comment by benhaynes** [comment]
I actually think the clearest way to handle this would be to have a dropdown for rounding (floor, ceiling, round). I'm not entirely sure what `strict` does as of now, but if it just toggles the word `about`, then I think we could just keep that as a toggle and clarify the field label.

There might be a way to combine all of this into one dropdown option too... but I need to better understand what `strict` does before making that call.

**Comment by u12206050** [comment]
@rijkvanzanten I guess it is a matter of how precise you need to be. A date 12.6.14 would be "12 years ago" vs 12.6.16 being "13 years ago". All I need to solve today is being able to show ages correctly. So if that means I need to add the additional option in the display to allow people to select the rounding method then I can do so, just let me know :)

**Comment by u12206050** [comment]
@benhaynes Correct, the strict option on date-fns only removes the words "almost", "over", "less than", however I thought of using it to both remove the word and be strict in not rounding up. 
But I agree, I will add a new option for rounding.

**Comment by u12206050** [comment]
I use `down, up and nearest` Do you agree?
The value being stored is `floor`, `ceil` and `round`

Screenshot 2022-07-12 at 15 29 49

Screenshot 2022-07-12 at 15 29 53

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
> Yes, I agree those are the clearest words. Can we think of any clearer label for `strict`?

Good question. The only thing I can up with is a more descriptive thing, like `Show "about"`

**Comment by rijkvanzanten** [comment]
Lets at least merge through the new option first, as that all looks good to me, and we can keep discussing the naming on here 👍🏻

**Comment by benhaynes** [comment]
Sounds good. I wonder if we could convert `strict` into a dropdown for "length", "verbose", or "precision"... something like:

* Compact `12y`
* Short `12 years`
* Normal `12 years ago`
* Long `about 12 years ago`

**Comment by rijkvanzanten** [comment]
We're a little limited in what we can show through the date-fns library. That `compact` example for example would be non-trivial to implement, as `date-fns` doesn't return the relative dates in a format we can easily "translate" to the compact one 🤔

**Comment by benhaynes** [comment]
Ugh, right. Bummer. Maybe two toggles then?

* `Include "Fuzzy" Prefix`, (About, Over, Almost, etc)
* `Include "Ago" Suffix`

**Comment by rijkvanzanten** [comment]
We're currently relying on [`formatDistance`](https://date-fns.org/v2.28.0/docs/formatDistance) and [`formatDistanceStrict`](https://date-fns.org/v2.28.0/docs/formatDistanceStrict). I believe both of those support the `addSuffix` flag, so we can indeed make the "Ago" suffix an additional toggle 🙂 

That being said, we'd still wanna keep the new option from this PR to add the rounding function for the non-fuzzy rendering right?

**Comment by u12206050** [comment]
The "ago" suffix is already an option

**Comment by benhaynes** [comment]
> That being said, we'd still wanna keep the new option from this PR to add the rounding function for the non-fuzzy rendering right?

Yeah, we want to add the ability to control rounding, and then want to ensure we have toggles for the prefix/suffix for formatting. Then this should be good.

**Comment by rijkvanzanten** [comment]
> > That being said, we'd still wanna keep the new option from this PR to add the rounding function for the non-fuzzy rendering right?
> 
> Yeah, we want to add the ability to control rounding, and then want to ensure we have toggles for the prefix/suffix for formatting. Then this should be good.

And then also make sure the rounding toggle is disabled when the `prefix` option is used, as the rounding stuff doesn't apply when not using strict right? 🤔

**Comment by benhaynes** [comment]
> And then also make sure the rounding toggle is disabled when the prefix option is used, as the rounding stuff doesn't apply when not using strict right? 🤔

Hmm, not sure about that. What logic does this use by default when you have `about`? Pure rounding?

**Comment by u12206050** [comment]
I would assume the date-fns library knows how to deal with that set of
options.

**Comment by rijkvanzanten** [comment]
@u12206050 Only `formatDistanceStrict` has the rounding option though, so I think it's a no-op when passed to `formatDistance`

**Pull request merged**
