### PR TITLE
Allow base Email override for standard emails

### PR DESCRIPTION
**Pull request by Kinzi**
Ternary needs to be flipped so base templates can be overridden.

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by Kinzi** [comment]
❤️

**Comment by christianrr** [comment]
@Kinzi Thanks for making overriding templates work! I deeply needed this, great work :)

```
const resolvedPath = system
	? path.resolve(env.EXTENSIONS_PATH, 'templates', template + '.liquid')
	: path.join(__dirname, 'templates', template + '.liquid');
```

With this change, however, custom templates (e.g. an order confirmation e-mail) that have no system pendant would require to pass { system: true } as argument in the mailService.send(...) function, so that the renderTemplate function looks in the right spot, namely the extensions directory instead of the system directory; That is a bit hard to understand in my opinion.

Maybe it would be a better solution to always check the extension directory first, and only if no template is found there, then fall back to the system directory, something like:

```
private async renderTemplate(template: string, variables: Record<string, any>, system = false) {
	const resolvedPath = path.resolve(env.EXTENSIONS_PATH, 'templates', template + '.liquid');
	if (system && !fse.fileExists(resolvedPath)) resolvedPath = path.join(__dirname, 'templates', template + '.liquid');

	const templateString = await fse.readFile(resolvedPath, 'utf8');
	const html = await liquidEngine.parseAndRender(templateString, variables);

	return html;
}
```

What do you think?

**Comment by rijkvanzanten** [comment]
@christianrr In favor 🙋🏻‍♂️ (That would also fix https://github.com/directus/directus/issues/5555)

**Comment by Kinzi** [comment]
@christianrr Love this!

**Pull request merged**
