### PR TITLE
Improve Permissions in relational Interfaces

### LINKED ISSUE #15962: A regular user should not be allowed to edit an M2M item when the collection has no editing access for his role
### Describe the Bug

When clicking on the name of any of the M2M field, the related collection is opened despite the related collection has no editing access.
The opening throws the error "You don't have permission to access this."
But editing and saving the related item is still possible.
After coming back to the main item, it throws "You don't have permission to access this." and cannot be saved.

So saving is prevented, but not editing as it should be.
**I would like even then M2M collection item not to be shown.**

_May I add that unckecking the fields the user can read has no effect: he still sees the all, including `users in role` and even the custom fields_

### To Reproduce

1. Create an M2M field (in my case, it was `roles `in `directus_users `M2M to `directus_roles`)
2. For the role of this regular user disable editing on `directus_roles`
3. Allow editing on the M2M field in `directus_users `(to be able to add a `role `to `roles`) and check the field `roles `in editing permissions of the role.
4. In the form (in my case, the user form), add some `roles`.
5. After saving, back in the form, click on any of the `roles`.
=> `You don't have permission to access this.`
6. Edit the role, click on Save
7. Click on Save of the user
=>`You don't have permission to access this.`

### Errors Shown

Being able to edit a not allowed to edit collection
Then getting `You don't have permission to access this.`

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgresql 14

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

### LINKED ISSUE #16344: Custom edit permission are not replicated in Translations Interface
### Describe the Bug

Using the app,
given custom edit permissions on a translation collection,
when viewing the translation fields through the Translations Interface,
then the custom permissions are not replicated (all fields appear editable), which consequently also prevents saving (FORBIDDEN)

Similar issues come up when disabling create/delete on a pivot/junction table or the target table of a relation, which does _not_ cause the add/delete buttons in the app to disappear in interfaces that use this pivot/junction or target table, thus a user can create items which they then cannot save.

### To Reproduce

- Make a collection `foo`
- Add a translations field to the collection `foo`
- Add an input field `bar` and `baz` to the translations collection `foo_translations`
- Create a role which has custom/partial edit permissions on `foo_translations` (can only edit `foo_translations.bar`, and the relevant relation fields id, fk, lang)
- Using the role with custom permissions, edit field `foo_translations.baz` through the Translations Interface on `foo` --> permission denied

### Errors Shown

{
  "message": "You don't have permission to access this.",
  "extensions": {
    "code": "FORBIDDEN"
  }
}

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.18.0

### What database are you using?

postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

docker

### LINKED ISSUE #16823: A user who has no right to delete an O2M or M2O foreignkey should not see the X
### Describe the Bug

A user who hos no right to delete an O2M field sees the X at the end of the line

### To Reproduce

Create a collection with an O2M field.
No Access to delete for the O2M collection
Show O2M items in the parent collection

### Errors Shown

You see the X to delete the item at the bottom of every line.
Click on it
Save the main item
=> 
```
{
  "message": "You don't have permission to access this.",
  "extensions": {
    "code": "FORBIDDEN"
  }
}
```
The X should not be seen at first.

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

19.0.1

### What database are you using?

Postgresql 15

### What browser are you using?

Firefox & Edge

### How are you deploying Directus?

VPS

### PR DESCRIPTION
**Pull request by Nitwel**
This PR introduces a composable for permission checking on relations as something like this didn't exist before and it was cumbersome to check permissions for each interface by itself.

Fixes #15962
Fixes #16344
Fixes #16823
Fixes #17753
Fixes ENG-166
Fixes ENG-142

### CODE REVIEW

**Review by rijkvanzanten — DISMISSED** [review]
👏🏻 tests 👏🏻 tests 👏🏻 tests 👏🏻  😄

**Comment by Nitwel** [comment]
Added tests! 😄

**Review by br41nslug — COMMENTED** [review]
I like this more structured approach 😄 Looks like it fixes https://github.com/directus/directus/issues/15962 but im running into issues when testing for https://github.com/directus/directus/issues/16344

On `main` the translation interface doesnt disable the fields without permission but when testing on this PR branch i am unable to edit any field even when setting the translation collection to all edit permissions.

image
image

**Comment by Nitwel** [comment]
Good catch, I was checking for create and update permissions on the languages collection which in the case of the translation interface isn't needed. Is fixed now. 👍

**Comment by paescuj** [comment]
Would this pull request be ready for another round of reviews?

**Review by connorwinston — APPROVED** [review]
Works as expected to me, tested each issue this resolves.

**Review by br41nslug — APPROVED** [review]
Tested the 4 mentioned issues again and they have been resolved now 😄

**Pull request merged**
