### PR TITLE
Fixed undefined __t function in TableNotFoundException constructor

### PR DESCRIPTION
**Pull request by jimjam88**
```
Fatal error: Uncaught Error: Call to undefined function Directus\Database\Exception\__t() in /.../vendor/directus/database/Exception/TableNotFoundException.php on line 25

Error: Call to undefined function Directus\Database\Exception\__t() in /.../vendor/directus/database/Exception/TableNotFoundException.php on line 25

Call Stack:
    0.0002     357088   1. {main}()
    0.0139    1266792   2. ...
    0.0139    1267024   3. ...
    0.0139    1268592   4. ...
    0.1044    4227536   5. ...
    0.1044    4227536   6. Directus\SDK\ClientLocal->getTable() ...
    0.1044    4227536   7. Directus\Database\TableSchema::getSchemaArray() /.../vendor/directus/sdk/src/ClientLocal.php:71
    0.1044    4227536   8. Directus\Database\TableSchema::getTableColumnsSchema() /.../vendor/directus/database/TableSchema.php:238
    0.1044    4227536   9. Directus\Database\TableSchema::getTableSchema() /.../vendor/directus/database/TableSchema.php:199
    0.1044    4227536  10. Directus\Database\SchemaManager->getTableSchema() /.../vendor/directus/database/TableSchema.php:185
    0.1355    4365552  11. Directus\Database\Exception\TableNotFoundException->__construct() /.../vendor/directus/database/SchemaManager.php:178

```

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Hey @jimjam88, when did this issue happen, the function should've been loaded by then.

**Comment by WellingGuzman** [comment]
Oh you are using the SDK, which version are you using?

**Comment by jimjam88** [comment]
Yep, I'm using the SDK. dev-version/6.4 d4afab1

I see the `__t` function is defined in the API core. Obviously this isn't accessible by the SDK so I figured adding a `function_exists` call would be the best solution for this.


```
directus/collection       0.9.x-dev 8e53f6c       Directus Collection Library
directus/config           0.9.x-dev f60f427       Directus Config Library
directus/database         dev-master 738bd1d      Directus Database Component
directus/filesystem       dev-version/6.4 686fc3c Directus Filesystem Library
directus/hash             0.9.x-dev 28d0981       Directus Hash Library
directus/hook             dev-version/6.4 f01e4dd Directus Hook Library
directus/permissions      dev-version/6.4 da562f2 Directus Permissions (ACL) Library
directus/sdk              dev-version/6.4 d4afab1 Directus SDK for PHP
directus/utils            dev-version/6.4 2596577 Directus Utils
```

**Comment by WellingGuzman** [comment]
True, but this is a different problem, we should move that function somehow to the SDK instead. This would result in a hiding the problem effect which will include no message at all.

**Comment by WellingGuzman** [comment]
Thanks for the contribution, but unfortunately it won't be merged, we will try to solve this in the php sdk, and we will update the exceptions to not use translations directly.

**Pull request closed without merging**
