### PR TITLE
Add search in data-model collections overview

### LINKED ISSUE #19396: Add a search bar to the data model page
### Describe the Improvement

If you have a large data model, it would be very helpful to have a search bar like we do for interfaces so you can find the collection you're aiming to edit faster:

CleanShot 2023-08-10 at 11 03 45@2x

CleanShot 2023-08-10 at 11 02 25@2x

### PR DESCRIPTION
**Pull request by Nitwel**
fix #19396
Before Searching:
grafik
After:
grafik

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
This is perfect! One little tiny addition we should do is to add a `v-highlight` on those collection names to highlight the matched search 🙂

**Comment by Nitwel** [comment]
Awesome suggestion, looks even better now!

**Review by paescuj — CHANGES_REQUESTED** [review]
- Not sure whether we should put the focus to the search field by default when opening the page, feels a bit distracting to me
  
- Search input placeholder should be changed to something like "Search collections..."
- Seems like it does global matching, while it should only match the first occurrence IMO:

**Comment by Nitwel** [comment]
Added your suggestions except for `Seems like it does global matching, while it should only match the first occurrence IMO:`. I'm not really sure if we want to do that.

**Review by paescuj — APPROVED** [review]

**Review by br41nslug — APPROVED** [review]

**Pull request merged**
