### PR TITLE
Add support for a package extension bundle type

### PR DESCRIPTION
**Pull request by nickrum**
## Description

This adds a new `bundle` type to the extensions system which is package-only and which will allow you to create a single package extension that includes multiple other extensions. Those extensions are bundled into an App and an API entrypoint. This allows you to share dependencies and custom code between those extensions.

This also refactors how App extensions are loaded. They are now loaded from a single endpoint instead of using separate endpoints for each extension type.

### TODO

- [x] Add support to the Extensions SDK
- [x] Update tests in `@directus/shared`

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by freekrai** [comment]
> @freekrai @br41nslug mind kicking the tires by making some custom extensions that utilizes this? @Nitwel @ConnorSimply and myself can do the code review

Yeah I was thinking of making a new extension around the vercel satori stuff so perfect timing

**Comment by rijkvanzanten** [comment]
In todays "lets make things even more complicated": It would be really nice if the bundle type `entries` could be automatically introspected from a given glob, like:

```
"entries": [
  { "type": "panel", "source": "panels/**/index.js" }
]
```

or even automagically extract the type through

```
"entries": [
  "./panels",
  "./layouts"
]
```

**Review by rijkvanzanten — APPROVED** [review]
Works a beaut!

**Comment by rijkvanzanten** [comment]
Lets get these merge conflicts resolved, but i think it's good to merge otherwise 🙌🏻 @nickrum

**Comment by nickrum** [comment]
> Any big points I'm missing here @nickrum? 🙂

That sums it up pretty nicely 👍🏻

**Comment by azrikahar** [comment]
In relation to the Vite upgrade from v2 to v3 in #15943, the glob imported array is now sorted with a basic `.sort()` (https://github.com/vitejs/vite/blob/9f268dad2e82c0f1276b1098c0a28f1cf245aa50/packages/vite/src/node/plugins/importMetaGlob.ts#L364).

However in order to make the field creation drawer experience the same as before (especially `input` should be the first field), I've added sorting to "revert" to the original in Vite v2. Here is the comparison:

|Before adding our own sort|After adding our own sort|
|---|---|
|||

Note: We can also refer to the screenshots in #10611 to confirm that the resulting sort is same as how it used to be.

**Review by connorwinston — APPROVED** [review]
Nothing stands out to me, besides needing it to be documented well since it is a fairly technical use case.

**Review by freekrai — APPROVED** [review]
Looks good, will be a nice new structure for extensions to use.

**Comment by MichaelFBA** [comment]
If anyone has a small demo they can post a github repo it would be appreciated! Thanks and looking forward to it

**Comment by erondpowell** [comment]
> This PR adds:
> 
> * A new extension type "bundle"
> * A bundle is effectively a monorepo of multiple "regular" extensions
> * This allows all extensions to be bundled into a single `.js` file for production...

@nickrum @rijkvanzanten 
I haven't worked with Extensions yet at all.
If I'm doing the docs for this one, let's hop on a call to go over key details for this new feature.

**Comment by nickrum** [comment]
@azrikahar I simplified the app extension import logic a little bit. I hope you don't mind 😁

 @erondpowell We could either hop on a call or I could take care of the docs for this for the time being. The extension docs are in dire need of a little bit of love but that's a much bigger sprint.

**Comment by azrikahar** [comment]
> @azrikahar I simplified the app extension import logic a little bit. I hope you don't mind 😁

It's superrr clean and works really well. "a little bit" would be an understatement! Thank you ❤

**Comment by erondpowell** [comment]
> @erondpowell We could either hop on a call or I could take care of the docs for this for the time being. The extension docs are in dire need of a little bit of love but that's a much bigger sprint.

Happy for you to write them 😄  I was tagged... so I answered the call!
but tbh, I'm pretty *swamped* with configuration, cookbooks, and API docs.
In about 2-4 months, I should be freed up to really help with the Extensions docs.
Let's hop on a call then!

**Review by azrikahar — APPROVED** [review]

**Comment by br41nslug** [comment]
I finally got around to creating one of these bundled extensions over the weekend but got stuck trying to load it :( How does one load a bundle extension locally?

**Comment by rijkvanzanten** [comment]
> How does one load a bundle extension locally?

Bundle / pack type extensions are only loaded in through package.json, so you need to add a `directus-extension-xx` package to package.json. You can use `file://` path in package.json for easier local dev (or use `npm link` if that's more your jam)

**Comment by rijkvanzanten** [comment]
@azrikahar i'll merge it as is, and check that out in my dependency checking today 👍🏻

**Comment by paescuj** [comment]
> @azrikahar i'll merge it as is, and check that out in my dependency checking today 👍🏻

Yay, it's Patch Tuesday 🐸😄

**Comment by rijkvanzanten** [comment]
@paescuj wish me luck and god give me strength

**Comment by paescuj** [comment]
> @paescuj wish me luck and god give me strength

I do 💪🍀

**Comment by lluishi93** [comment]
Do we have any example on how to use this?

**Comment by MichaelFBA** [comment]
> Do we have any example on how to use this?

I managed to get it working like this
https://discord.com/channels/725371605378924594/1044590504907653152

**Comment by abdonrd** [comment]
There is no official docs for this? Thanks!

**Comment by azrikahar** [comment]
> There is no official documentation about this? Thanks!

It is in the works! ☺

**Comment by josh-hemphill** [comment]
Any news on adding the `bundle` type to the docs?

**Comment by paescuj** [comment]
> Any news on adding the `bundle` type to the docs?

[Unfortunately, we can not provide estimates on features or fixes](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍

**Comment by alexey-yarmosh** [comment]
If anyone else need to find a way of how to use `bundle` type in the similar to other extensions manner, here it is:
- assuming you are using docker and passing volume as `./extensions:/directus/extensions`
- from the `./extensions` folder call `npm init directus-extension` and choose `bundle` type
- make sure to name your extension as `directus-extension-*`, e.g. `directus-extension-my-super-extension`
- cd into `directus-extension-my-super-extension`
- add sub-extensions that need to communicate using `npm run add`
- run `npm run build`
- now your extension should be accepted by the directus and able to work

**Pull request merged**
