### PR TITLE
Add configuration for activity/revisions retention

### PR DESCRIPTION
**Pull request by rijkvanzanten**
This should've been there from the start honestly. Hindsight 20/20! 

Partially touches https://github.com/directus/directus/issues/17894 by ensuring that those tables don't grow beyond control.

Note: this is could be construed as a breaking change, as it is enabled by default.

### CODE REVIEW

**Review by licitdev — COMMENTED** [review]
Interesting approach! 👍 Some initial findings and thoughts.

- Records from `directus_revisions` for schema changes in SQLite are not deleted when the corresponding `directus_activity` record is deleted as `PRAGMA foreign_keys` has to be temporarily disabled.
- Should the truncation should take place after the record creation so that it will not truncate should the record creation fail?
- This truncation by date surely prevents the activity & revisions tables from growing out of control, however:
  -  Should it be more concise, specific to the collection / items for truncation?
  -  Or to keep it simpler, should there be configuration to bypass certain collections from the truncation.
  Eg: `BYPASS_RETENTION_TRUNCATE="coll_a,coll_b"`
- Could this truncation be run in a cron job instead if it is solely by the date? However, this may run into an issue due to #15052.
Eg: Truncate at 3am daily `RETENTION_TRUNCATE_SCHEDULE="0 3 * * *"`

**Comment by rijkvanzanten** [comment]
Thanks @licitdev!

> Records from directus_revisions for schema changes in SQLite are not deleted when the corresponding directus_activity record is deleted as PRAGMA foreign_keys has to be temporarily disabled.

Ayyyyy booooooo! 

> Should the truncation should take place after the record creation so that it will not truncate should the record creation fail?

I think it's fine to do upfront. As to your other point in doing it as a CRON job, it's something that should run regardless

> This truncation by date surely prevents the activity & revisions tables from growing out of control, however:
> - Should it be more concise, specific to the collection / items for truncation?

Yes! One other feature I'm working on to add after this is a per-collection setting for "max revisions per item". That way, you can control to only save the last 10 revisions per article, and have a longer max-retention time to cleanup unused outdated revisions 🙂 

> Or to keep it simpler, should there be configuration to bypass certain collections from the truncation.
> Eg: BYPASS_RETENTION_TRUNCATE="coll_a,coll_b"

Nah, to me this env var is meant as a last safety-guard. That type of option should be handled in settings rather than env vars 🙂

**Comment by ConnorSimply** [comment]
Some thoughts...

How does this impact performance? If you hit your instance with 1,000 requests all at once and each of those creates activity/revisions its going to call truncate a thousand times if I am interpreting this correctly. 

Right now the truncation is based on "time" so I think it should be a "time" based trigger as well. If the truncation is based on revision length it should be based on each time you create revisions/activity.

Idea...you could only call "truncate" on the unit of time that it is set. If it is set to "100 days" it could truncate once a day, if it is truncate to "12 hours" it could truncate once an hour. 

If you are planning on adding per collection truncation...would it make sense just to have that available in the collection settings instead of both the collection and environment variables? Or would the ENV variable be considered the "default" and you can override per collection?

**Comment by rijkvanzanten** [comment]
> How does this impact performance? If you hit your instance with 1,000 requests all at once and each of those creates activity/revisions its going to call truncate a thousand times if I am interpreting this correctly.

Should be very lightweight. The individual sql is very simple, and seeing it's ran so often, the amount of data that's being deleted is minimal, hence it being fairly quick.

> Right now the truncation is based on "time" so I think it should be a "time" based trigger as well. If the truncation is based on revision length it should be based on each time you create revisions/activity.

I don't really see how the two are related 👀 

> Idea...you could only call "truncate" on the unit of time that it is set. If it is set to "100 days" it could truncate once a day, if it is truncate to "12 hours" it could truncate once an hour.

Could work!

> If you are planning on adding per collection truncation...would it make sense just to have that available in the collection settings instead of both the collection and environment variables? Or would the ENV variable be considered the "default" and you can override per collection?

They'd both do something different 🙂 The env var would control the maximum time (anything) is retained, and acts as a sort of final failsafe to make sure the table doesn't grow beyond usable sizes. The per-collection setting would be a way to control how many revisions are saved per item

**Comment by Tummerhore** [comment]
Awesome and a much needed addition. I would also add archived notifications to the cleanup procedure. (However "archive" is then a not so fitting term and I would rename it to "recycle bin".)

**Comment by Tummerhore** [comment]
> Right now the truncation is based on "time" so I think it should be a "time" based trigger as well. If the truncation is based on revision length it should be based on each time you create revisions/activity.

I can second this. Doing the truncation on every edit could lead to a big difference between the set maximum time and the oldest actually stored items. For example: We have a retention time of 30 days and one collection item was edited quite heavily in the beginning so we have a lot of revisions. But then the item is left untouched so after 1 year these revisions are still stored. Of course, this is rather unlikely and it could also happen when a time based trigger is very long but I like @ConnorSimply's suggestion of using the specified unit for that.

**Comment by Tummerhore** [comment]
Also I'm wondering if this implementation doesn't have a problem with this [foreign key constraint](https://github.com/directus/directus/discussions/13481) when we delete an activity while keeping the associated revision? Maybe it's also worth considering to always keep the associated activity for stored revisions even when the activity is older than the retention limit.

**Comment by joselcvarela** [comment]
Let me be that guy: Any updates? 😅

**Comment by rijkvanzanten** [comment]
> Let me be that guy: Any updates? 😅

Soon! 😬

**Comment by u12206050** [comment]
Don't like the idea that things get truncated by time. We use the revision log as an audit log to see who did what changes. Some items hardly get changed over a couple of years, whilst others might be changed once per month or even week. However we still have to keep record of it for accountability sake.
I have added via migration cascading rules between activity and revision and do have a job that cleans old revisions of items that we don't need to keep history for.

So to conclude, any change to this should either be disabled by default, and when enabled have configuration options for deciding the rules per collection :)

PS: What about dumping old records to storage in batches, then the data could still be retrieved if need be for auditing reasons, or even be piped to BigQuery or similar data warehouse.

**Comment by slyk** [comment]
> Don't like the idea that things get truncated by time. We use the revision log as an audit log to see who did what changes. Some items hardly get changed over a couple of years, whilst others might be changed once per month or even week. However we still have to keep record of it for accountability sake. I have added via migration cascading rules between activity and revision and do have a job that cleans old revisions of items that we don't need to keep history for.
> 
> So to conclude, any change to this should either be disabled by default, and when enabled have configuration options for deciding the rules per collection :)

For me it became unusable, because of automatic processing of 7000 records couple of times.

As for defaults I guess:
1) for new installations - enabled, so people don't have rising DB and long loading (or not loading in my case) activity log. The advanced users can go to settings and turn it off.
2) for upgrades - disabled, because that is not how the system was working, so some (like you) can rely on this data.

**Comment by u12206050** [comment]
Ah, I just added indexes on collection and item and that reduced the rows scanned quite a lot currently have about 2mil rows in revisions

**Comment by joselcvarela** [comment]
Just to add another option: we can also export as CSV to File Library and remove from `directus_revisions` 🤔

**Comment by rijkvanzanten** [comment]
FWIW this is all controlled through env vars, this is not the type of thing that's just hardcoded in without any way to control it 🙂 You could always setup your own flow or mechanism to back it up to cold storage and still have Directus purge it over time, or not use this at all 👍🏻

**Comment by joselcvarela** [comment]
Want to add this valuable find:
I am using Postgres and when I did:
 ```sql
 delete from directus_revisions where collection = 'XXXX'
  ```
  It took more than 2mins
  
  But when I did
  ```sql
  begin;
ALTER TABLE "directus_revisions" DISABLE TRIGGER ALL; 
delete from "directus_revisions" where collection='XXXX';
ALTER TABLE "directus_revisions" ENABLE TRIGGER ALL;
  ```
It did't took a second, only 800ms

If Postgres was the blocker for existing databases, this may be the way.
Although we should do
  ```sql
  begin;
ALTER TABLE "directus_revisions" DISABLE TRIGGER ALL; 
delete from "directus_revisions" where collection='XXXX';
delete from "directus_activity" where collection='XXXX';
ALTER TABLE "directus_revisions" ENABLE TRIGGER ALL;
  ```
  instead so we don't end with any loose ends aka broken relationships.

**Comment by u12206050** [comment]
> Want to add this valuable find:
> 
> I am using Postgres and when I did:
> 
>  ```sql
> 
>  delete from directus_revisions where collection = 'XXXX'
> 
>   ```
> 
>   It took more than 2mins
> 
>   
> 
>   But when I did
> 
>   ```sql
> 
>   begin;
> 
> ALTER TABLE "directus_revisions" DISABLE TRIGGER ALL; 
> 
> delete from "directus_revisions" where collection='XXXX';
> 
> ALTER TABLE "directus_revisions" ENABLE TRIGGER ALL;
> 
>   ```
> 
> It did't took a second, only 800ms
> 
> 
> 
> If Postgres was the blocker for existing databases, this may be the way.
> 
> Although we should do
> 
>   ```sql
> 
>   begin;
> 
> ALTER TABLE "directus_revisions" DISABLE TRIGGER ALL; 
> 
> delete from "directus_revisions" where collection='XXXX';
> 
> delete from "directus_activity" where collection='XXXX';
> 
> ALTER TABLE "directus_revisions" ENABLE TRIGGER ALL;
> 
>   ```
> 
>   instead so we don't end with any loose ends aka broken relationships.
> 
> 

We can't simply disable triggers, since others might be dependent on them.
I'm also curious as too how many rows you were deleting in both tests?

**Comment by JesperWe** [comment]
> We can't simply disable triggers, since others might be dependent on them. I'm also curious as too how many rows you were deleting in both tests?

Adding an index to `directus_revisions.collection` will speed this up I guess?

**Comment by badrange** [comment]
> > We can't simply disable triggers, since others might be dependent on them. I'm also curious as too how many rows you were deleting in both tests?
> 
> Adding an index to `directus_revisions.collection` will speed this up I guess?

That helped me on my dev computer at least; without the indexes nothing happened even if I let a delete query run for hours. With indexes it took some 10 seconds.

**Comment by BlackDahlia313** [comment]
I like this idea as long as there is an option to preserve all comments. I don't mind pruning other activity logging, but I would want all comments to remain and I know that falls under activity. 

I am using it as the comment system on the frontend of my project.

**Comment by Natetronn** [comment]
This would be nice!

**Comment by appy-one** [comment]
> > Want to add this valuable find:
> > I am using Postgres and when I did:
> > ```sql
> > delete from directus_revisions where collection = 'XXXX'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It took more than 2mins
> > But when I did
> > ```sql
> > begin;
> > 
> > ALTER TABLE "directus_revisions" DISABLE TRIGGER ALL; 
> > 
> > delete from "directus_revisions" where collection='XXXX';
> > 
> > ALTER TABLE "directus_revisions" ENABLE TRIGGER ALL;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It did't took a second, only 800ms
> > If Postgres was the blocker for existing databases, this may be the way.
> > Although we should do
> > ```sql
> > begin;
> > 
> > ALTER TABLE "directus_revisions" DISABLE TRIGGER ALL; 
> > 
> > delete from "directus_revisions" where collection='XXXX';
> > 
> > delete from "directus_activity" where collection='XXXX';
> > 
> > ALTER TABLE "directus_revisions" ENABLE TRIGGER ALL;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > instead so we don't end with any loose ends aka broken relationships.
> 
> We can't simply disable triggers, since others might be dependent on them. I'm also curious as too how many rows you were deleting in both tests?

I had to delete 25 million records from the `directus_revisions` table for a collection that really didn't need revision/version tracking at all. A single (1 !) record delete from this table took minutes (Postgres 15.7 running in Google Cloud with 8GB mem and 2 dedicated vCPUs) until I removed the `directus_revisions_parent_foreign` foreign key constraint - I was able to delete the 25 million records in 100K batches in about an hour. I recreated the foreign key afterwards. Obviously I also changed the Directus tracking settings for this collection so it won't create any new records.

For anyone interested, here's how to remove the foreign key to delete records (Postgres):
```sql
ALTER TABLE directus_revisions DROP CONSTRAINT directus_revisions_parent_foreign;
```

To delete records in batches of 100K on a live system (not blocking anything for too long), execute this until done:
```sql
delete from directus_revisions where id in (
	select id from directus_revisions where collection='your_collection_name' limit 100000
);
```

And then recreate the foreign key:
```sql
ALTER TABLE directus_revisions
ADD CONSTRAINT directus_revisions_parent_foreign
FOREIGN KEY (parent) REFERENCES directus_revisions(id);
```

**Comment by rijkvanzanten** [comment]
Closed in favor of #23149 and updating this to use indices and grouped queries instead

**Pull request closed without merging**
