### PR TITLE
New OpenID and OAuth2 drivers

### PR DESCRIPTION
**Pull request by aidenfoxx**
⚠️  **Potential Breaking Change**: If you're relying on oAuth, make sure to update your configuration flags to match the new setup as per the docs.

---

New auth drivers with support for public registration through SSO.

- [x] Updated frontend to new design
- [x] Document configuration
- [x] Verify I didn't break anything

### CODE REVIEW

**Review by aidenfoxx — COMMENTED** [review]
Updated docs

**Comment by aidenfoxx** [comment]
@rijkvanzanten I think I'm done with this for now. As mentioned, there are no hooks for these new providers. I think you'll know better how to deal with those.

I also re-enabled the ability to set a provider and identifier when creating a user. I really think it makes sense in a situation where a user doesn't want to allow public registrations, but still be able to add users to the system who can log in with SSO.

**Review by joselcvarela — COMMENTED** [review]
Nice job @aidenfoxx ❤
Great improvements

I didn't test it yet, but will try later today.

One thing I noticed is the removal of `express-session`. I know since `grant` is not needed anymore it seems legit to remove `express-session`. But, didn't we use it anywhere else? I have checked and it seems not, but not sure.

**Review by azrikahar — COMMENTED** [review]
Minor review 👍

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
