### PR TITLE
Add default translation language option

### PR DESCRIPTION
**Pull request by Nitwel**

### CODE REVIEW

**Comment by benhaynes** [comment]
Yaaassss... thanks @Nitwel!! ❤️

**Comment by rijkvanzanten** [comment]
That's a great idea @kosssi 🙂

**Comment by zbjdonald** [comment]
Any updates?

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
