### PR TITLE
End-to-end tests setup refactor

### PR DESCRIPTION
**Pull request by oreilles**
This will remove all dependencies on Dockerode in the e2e tests.
They used to require building the Directus image and spinning a Directus container for each test database.
With those changes, the local Directus code is used instead, making it much faster.

TODO:
- [ ] Documentation 
- [ ] Github Actions configuration

In order to run the tests, you now have to run those commands from the repository root:
* `npm run build`
* `docker compose down` (clean up in case you ran the tests before)
* `docker compose up -d`
* Wait for all containers to launch
* `npm run test:e2e`

### CODE REVIEW

**Comment by paescuj** [comment]
Nice, @Oreilles! Let me know if you need any help for the GitHub workflow setup...

**Comment by Oreilles** [comment]
I do, I just can't for the life of me get it to work inside GitHub actions,.

**Comment by paescuj** [comment]
> I do, I just can't for the life of me get it to work inside GitHub actions,.

Okay, I'm looking into it 👍

**Comment by paescuj** [comment]
@Oreilles You can configure it like this to trigger the workflow: https://github.com/paescuj/directus/commit/ad2eedf5b723785135297a6a0ff5b102f5a5dba5
However, it looks like the tests are running endlessly... (https://github.com/paescuj/directus/runs/4740936001?check_suite_focus=true - running since ~15min)

**Comment by rijkvanzanten** [comment]
```
👮‍♀️ Tests complete!

Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

Error: The operation was canceled.
```

**Comment by Oreilles** [comment]
Closing in favour of https://github.com/directus/directus/pull/10968, cause unsolvable issue, and branch name preventing us from referencing it in the `ci.yaml` file.

**Pull request closed without merging**
