### PR TITLE
Fix reactivity of `useFormatItemsCountPaginated`

### LINKED ISSUE #24037: Item count broken in table view of O2M lists since 11.2.1
### Describe the Bug

Since upgrading to Directus 11.2.1, a O2M list in "Table" view always incorrectly shows "No items" despite there being many items in the list.

### To Reproduce

Create a O2M relationship within a collection and set the view to Table view.
Add several items to the list. 
Observe that the item count incorrectly says "No items"

Screenshot 2024-11-13 at 10 20 10

(related minor issue... the "open in new window" icon at the end of each row also now sometimes overlaps the content of the row)

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

Reactivity can be hard sometimes. Make sure that the arguments passed to the composable are actually reactive and correctly unreffed when used.

---

Fixes #24037

### CODE REVIEW

**Review by formfcw — CHANGES_REQUESTED** [review]
I've been reviewing the code for this PR, and I wanted to share some suggestions for improving the `useFormatItemsCountPaginated` composable. I think we could reduce complexity and improve maintainability.

I have two variants in mind:

Variant 1
- Remove the `useFormatItemsCountPaginated` composable and use the `formatItemsCountPaginated` utility function again, but pass the i18n object to it (`useI18n()` is already called in most cases, where this utility is called)
- Go through all occurrences of `useFormatItemsCountPaginated` and update
- Update `formatItemsCountPaginated` and  force it to pass the `i18n` object instead of calling `useI18n()` as a fallback within this function, so that each time the utility function is used, the i18n object must be passed

Variant 2
- Keep the composable, but undo the latest commits and update the computed to `computed(() => formatItemsCountPaginated(options, i18n));` … this shouldn’t break the reactivity.
- Update the `formatItemsCountPaginated` utility and pass `i18n` as a separate, second parameter, instead of calling `useI18n()` within this function, so that each time the utility function is used, the i18n object must be passed
- Go through all occurrences of `useFormatItemsCountPaginated` and `formatItemsCountPaginated` and update the code accordingly
- Optional: Following Vue’s composable conventions, return the computed as an object property, like `return { showingCount: computed(() => formatItemsCountPaginated({ ...options, i18n })) };` and update the code wherever it is called

**Comment by hanneskuettner** [comment]
The composable has been introduced in the first place in order to improve the usage of the format utility.

Regarding Variant 1:

I like that the current solution encapsulates the requirement of having to pass `i18n` to the format utility. This way the user of the composable does not need to care about what additional dependencies are required for the utility, this is an argument for mauntabbility of the current approach.

Regarding Variant 2:

Reverting the change of this PR (that is what you're suggesting, right?) will break reactivity, since options is just a plain object and not reactive at all.

> Following Vue’s composable conventions, return the computed as an object property

Where is that documented that this is convention for a composable just returns a single (computed) ref? :thinking:

**Comment by formfcw** [comment]
OK, I think it’s a good idea to use the wrapper composable as is. However, I’d like to suggest that we also prevent the problem the composable is supposed to solve from occurring in other areas. Could you please update `formatItemsCountPaginated` to require the `i18n` object to be passed directly, instead of calling `useI18n()` as a fallback within this function? This way, we ensure that an `i18n` instance is provided every time the utility function is used. Also, please remember to update `formatItemsCountPaginated` wherever it is used.

> Where is that documented that this is convention for a composable just returns a single (computed) ref? 🤔

Optional, but to answer your question: To be fair, it's not that clear. The convention in Vue is to return a plain object containing multiple refs. I would say even if you only have one ref, it is best practice. While you technically can return the ref itself, returning an object maintains consistency in your composables and allows for easier extensibility in the future. This approach also allows for better destructuring in components, as it keeps the pattern consistent regardless of the number of refs.

**Comment by hanneskuettner** [comment]
> Could you please update formatItemsCountPaginated to require the i18n object to be passed directly, instead of calling useI18n() as a fallback within this function? This way, we ensure that an i18n instance is provided every time the utility function is used. Also, please remember to update formatItemsCountPaginated wherever it is used.

Done 🤝

**Review by formfcw — APPROVED** [review]
LGTM 🚀 
Thank you @hanneskuettner !

**Pull request merged**
