### PR TITLE
Api: Do not suspend user if rate limiter store is unreachable

### LINKED ISSUE #19928: Login not possible when redis is not enabled but set as store
### Describe the Bug

When `RATE_LIMITER_STORE` is set to `redis`, but `RATE_LIMITER_ENABLED` is set to true, a `RateLimiterRedis` will be created when trying to log in. However, if the configuration is invalid or redis is currently unavailable, the rate limiter request will timeout and therefore will block the login attempt, resulting in the user being suspended.

From a user's view, I would expect the `createRateLimiter` function (from `rate-limiter.ts`) respects the `RATE_LIMITER_ENABLED` setting and will choose `memory` instead.

### To Reproduce

- Configure `RATE_LIMITER_REDIS_*` to a non-functional redis instance.
- Configure `RATE_LIMITER_STORE` to `redis`
- Configure `RATE_LIMITER_ENABLED` to `false`

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by joselcvarela**
## Scope

What's changed:

- Do not suspend user if rate limiter store is unreachable

## Potential Risks / Drawbacks

- N/A

## Review Notes / Questions

- In addition, I would like to ask why do we have a specific rate limiter for authentication? Shouldn't the global rate limiter be enough? 🤔

This was originally set on the following PR:
https://github.com/directus/directus/pull/5225
which fixed the following issue:
https://github.com/directus/directus/issues/2969

---

Fixes #19928

### CODE REVIEW

**Review by paescuj — COMMENTED** [review]
Will / should the login still be blocked for the time the store is unreachable? cc @br41nslug

**Comment by joselcvarela** [comment]
In my point of view, it does not make sense. If there's an issue on the connection with Redis, that shouldn't lock user forever 😬

**Comment by br41nslug** [comment]
tricky tricky, this will come down to a usability vs security argument. Locking a user if Redis is unavailable seems a bit harsh but without any rate limiter the door for brute forcing/password spraying is wide open 🤔 The global rate limiter depends on the same Redis too afterall.

So i guess the real question is... Should you be able to login at all if the configured rate limiters store is unreachable? 🤔

**Comment by paescuj** [comment]
> In my point of view, it does not make sense. If there's an issue on the connection with Redis, that shouldn't lock user forever 😬

> I do think the login should probably just error but not actually suspending the user.

Yeah, that's what I meant with blocking.

**Comment by paescuj** [comment]
> tricky tricky, this will come down to a usability vs security argument. Locking a user if Redis is unavailable seems a bit harsh but without any rate limiter the door for brute forcing/password spraying is wide open 🤔 The global rate limiter depends on the same Redis too afterall.

I agree. I think we can consider the situation Redis is unavailable a temporary and exceptional one, so it should be fine to simply block login (not suspending) until Redis comes up again.

**Comment by br41nslug** [comment]
Agreed that would be my preferred solution here 😄 Throwing something like a `ServiceUnavailable` error in that `catch`.

**Comment by joselcvarela** [comment]
I think you are right.
I have included the error when there's any other error with rate limiter.
Please give it a look 👍

**Review by paescuj — APPROVED** [review]

**Review by br41nslug — APPROVED** [review]

**Comment by br41nslug** [comment]
Ah github didnt update 😂

**Pull request merged**
