### PR TITLE
Correctly checking for mod_rewrite, instead of just pinging an URL.

### PR DESCRIPTION
**Pull request by parnas**

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Thanks @parnas for the PR, but this will only work on Apache using `mod_php`.

Would this solve an specific issue?

**Comment by parnas** [comment]
Yeah, that's correct. Perhaps it should fall back to ping if apache_get_modules is not available.

Alternatively, and probably more correctly, installation text for "'Mod_Rewrite Enabled'" should be altered from "Mod_Rewrite Enabled".

In my case, there was a problem with accessing pinged url, which wasn't related to mod_rewrite, so that message was misleading and I had to check the code, to see what code is actually checking.

**Comment by WellingGuzman** [comment]
I understand, but as this will only work in one case depending on the url, was the better option we remove that line of code you are suggesting long time ago, and because it only work on apache with mod php, what we can do is update the message AND fix whatever was the problem you were having.

**Comment by parnas** [comment]
Yup, I agree. Changing message (with mention of mod_rewrite in the faq link) is, probably, the best way to proceed.

I was also thinking of doing <ifModule !mod_rewrite.c> to set up environment variable, but that also will not reliably work with php cgi, and, also, itself depends on mod_env being enabled.

**Pull request closed without merging**
