### PR TITLE
Don't stringify nested item props

### LINKED ISSUE #7577: Collection display template doesn't show related field
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).

### Describe the Bug

When setting a display template with relational fields for a collection, for exemple `{{id}}, {{id_client.name}}`, the related values used to show correctly. It is no longer the case, and any relational field now shows as ``--``.

Maybe related to https://github.com/directus/directus/issues/7081 ?

### To Reproduce

* Create two collections, one containing a relational column to the other
* Set collection A display template to something referencing some field of collection B
* Create and navigate to an item individual page to see the rendered template.

### What version of Directus are you using?

9.0.0-rc.91

### What version of Node.js are you using?

Official docker image default

### What database are you using?

Postgres

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by oreilles**
Fixes https://github.com/directus/directus/issues/7577

I don't know what the purpose of this code was ? But removing those lines also made deep cloning the item (added with https://github.com/directus/directus/pull/7628) unnecessary, so I also removed it.

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by Oreilles** [comment]
@rijkvanzanten don't merge this yet. I figured that this was done because `micromustache` doesn't stringify object values when rendering them by default.

**Comment by rijkvanzanten** [comment]
I was gonna say, I believe the reasoning was to prevent `[object Object]` from showing up in the output.

**Comment by Oreilles** [comment]
This should do it 👍

**Comment by rijkvanzanten** [comment]
Merci, mon ami

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
