### PR TITLE
Many to many tagging and referencing - M2M interface

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
Continued and updated from #2899

In the nutshell, the interface allows M2M related items to be selected by referencing with autocomplete or to be added by defined single  field.

Solves #3065 and #3486

UI:

### CODE REVIEW

**Comment by benhaynes** [comment]
Ooh, a relational auto-complete has been on my wishlist for a while now! Is this an optional UI for the existing interface? Thanks @dimitrov-adrian — excited to check this one out!

**Comment by dimitrov-adrian** [comment]
> Is this an optional UI for the existing interface?

Is this an optional UI for the existing interface?

No, it's new interface. I though it could be a nice addin for tags interface, but then when take it closer look, both are very different, since the tags interface is just array manager, and this one actually do M2M referencing, just like tags on wordpress or the drupal's reference field.

--
It was on my wish list too, so to be bit more easy to ditch drupal ;)

**Comment by benhaynes** [comment]
Sorry, I meant this could be an option of the M2M interface... not of the tags interface. But maybe @rijkvanzanten has different ideas on how we split interfaces (by UI or core logic).

**Comment by rijkvanzanten** [comment]
By UI, as we discussed previously

**Comment by julbd** [comment]
This would be a really nice feature 🌟. Any update on this ?

**Comment by rijkvanzanten** [comment]
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

**Comment by gevera** [comment]
Awesome feature. Looking forward for it! Anyway I could help to make this happen?

**Comment by dimitrov-adrian** [comment]
@rijkvanzanten I had updated the code to be compatible with latest codebase.

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
This is great! 

Couple of tiny tweaks, and this is perfect. @azrikahar can you help finalize these last points so we can merge it asap?

- [x] Add hover states for menu list + tags (to deselect)
- [x] Make sort configurable (replace `alphabetize` with sort-field dropdown
- [x] remove closeOnSelect in favor of defaulting it to true (to be consistent with the rest of the system)
- [ ] Replace `referencingField` with using the `search` query param to search for everything, and add a "filter scope" optional field to allow searching through a single field

(Apologies for the _long_ delay in reviewing @dimitrov-adrian..)

**Comment by cdwmhcc** [comment]
Any update?

**Comment by rijkvanzanten** [comment]
> Any update?


[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

**Comment by SimonHausdorf** [comment]
@azrikahar what exactly is missing to get this merged? Also looking at your gif, I think it would be good if the input would clear once you selects a value.

**Comment by azrikahar** [comment]
> @azrikahar what exactly is missing to get this merged? 

Although the conflicting files only shows `v-chip.vue`, unfortunately there's a few other major parts that's not working anymore, such as the follow imports:

```
import useActions from '../list-m2m/use-actions';
import usePreview from '../list-m2m/use-preview';
```

As these files no longer exist since the overall relational interface rework in #12082. Hence it'll require fixing up before it can be usable and merged 🙂

> Also looking at your gif, I think it would be good if the input would clear once you selects a value.

Nice catch! Definitely agree 👍

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Comment by a-fazal** [comment]
@dimitrov-adrian @rijkvanzanten is this ever coming back?

**Comment by rijkvanzanten** [comment]
See my above comment as to why this PR was closed and how new features are requested, triaged, and implemented 👍🏻

**Pull request closed without merging**
