### PR TITLE
Change "register" for "handler" in the example

### PR DESCRIPTION
**Pull request by jjmiranda**
Change "register" for "handler" in the example custom endpoint route using id for access endpoints.

### CODE REVIEW

**Review by azrikahar — CHANGES_REQUESTED** [review]
Let's update line 44 as well 👍

```diff
- `register` — The endpoint's register function.
+ `handler` — The endpoint's handler function.
```

---

Relevant references for this PR's proposed change:

- https://github.com/directus/directus/blob/738dc605a3b6d273872a11eff056e14dbe45c19b/packages/shared/src/types/endpoints.ts#L5-L8

- https://github.com/directus/directus/blob/738dc605a3b6d273872a11eff056e14dbe45c19b/api/src/extensions.ts#L421

**Comment by nickrum** [comment]
When I reworked to extension the docs, my plan was to rename the property to `register` because both the hooks and endpoint docs refer to the default-exported functions as register functions and the hook docs also refer to the `filter`, `action`, etc. functions as register functions.
So, technically the implementation is wrong and not the docs. Not sure if we can make such a heavy breaking change now that v9 has been released.

**Comment by azrikahar** [comment]
@nickrum thanks for the clarification! That does make sense, but yea also personally not sure how should we fit that change in if possible. May be a point for discussion.

**Comment by jjmiranda** [comment]
As a developer, it took me 2 hours to find out why register was not a function and handler had to be used. As long as v9 doesn't have this change, the documentation has to be aligned to what is there, otherwise it's quite frustrating for new developers who start experimenting with Directus, like me ;)

**Review by jjmiranda — COMMENTED** [review]
As a developer, it took me 2 hours to find out why register was not a function and handler had to be used. As long as v9 doesn't have this change, the documentation has to be aligned to what is there, otherwise it's quite frustrating for new developers who start experimenting with Directus, like me ;)

**Comment by rijkvanzanten** [comment]
> As a developer, it took me 2 hours to find out why register was not a function and handler had to be used. As long as v9 doesn't have this change, the documentation has to be aligned to what is there, otherwise it's quite frustrating for new developers who start experimenting with Directus, like me ;)

Yeah absolutely 👍🏻

**Pull request merged**
