### PR TITLE
Add custom modules to WYSIWYG

### LINKED ISSUE #4354: Wysiwyg picture or video modal is hidden
Hello,

On a wysiwyg content, when you want to add a picture (or video), the modal to select the picture to add appears behind the Insert/Edit Image page.

Screenshot 2021-03-03 at 17 05 29

The modal to select the picture should be above the "insert/Edit Image".

The issue is present on directus-rc44. It is similar with this issue : https://github.com/directus/directus/issues/4173

### PR DESCRIPTION
**Pull request by Nitwel**
GIF 26 02 2021 15-32-51

closes #4354

### CODE REVIEW

**Comment by benhaynes** [comment]
Whoa, will this move the WYSIWYG modals (eg: add media) into drawers?? I've always hated the styling of those TinyMCE native modals...

**Comment by Nitwel** [comment]
Haha, yes. That's the plan. Let me quickly add some screenshots on how this looks right now!

**Comment by rijkvanzanten** [comment]
> Whoa, will this move the WYSIWYG modals (eg: add media) into drawers?? I've always hated the styling of those TinyMCE native modals...

@benhaynes turns out there's hardly any customization we can do into how TinyMCE renders those modals, so the next best thing is to reinvent those using our own components and structures.

**Comment by benhaynes** [comment]
Figures. Welp, at least then we'll have more control over how all that works!

**Comment by Nitwel** [comment]
I now added custom modals for adding/edding images, videos, links and source code.

Uploading Directus - Mozilla Firefox 2021-02-27 13-42-29.mp4…

**Comment by benhaynes** [comment]
I love this!! It looks great! 

It's it possible to use the same thing for the markdown editor?

Can we give embeds a min height so they roughly view at 16:9?

Also, can we ditch that thin weighted heading style? Let's match the new bolder header.

**Comment by jcuervas** [comment]
Would it be possible to link any file (selected from media, such as a pdf) from link modal?

**Comment by rijkvanzanten** [comment]
Yes

**Comment by iksent** [comment]
Will it work well together with translations modals?
[Having problems](https://github.com/directus/directus/issues/4354#issuecomment-795820263) now with it...

**Comment by Nitwel** [comment]
Yes, that was one of the reasons why we decided to do this.

**Comment by iksent** [comment]
Cool! Really waiting to get this merged 😌

**Comment by MaxSamnani** [comment]
how can i do this?

**Comment by danieljwestman** [comment]
@Nitwel Got any news about this awesome PR? Any known problems with it?

**Comment by benhaynes** [comment]
If @Nitwel says it's ready, then the main thing we need is reviewers. At the end of the day, @rijkvanzanten confirms what gets merged, but any other reviews would really help move things along! This also applies to all PRs, by the way. 🙂

**Comment by Nitwel** [comment]
Oh, this is already ready for review, otherwhise it would be a draft PR.

**Comment by benhaynes** [comment]
Awesome! @danieljwestman — would you want to do a first pass on reviewing this? If we can find/resolve any obvious issues, then we might be able to get Rijk on this sooner.

**Comment by danieljwestman** [comment]
@benhaynes For sure, I'll check it out

**Review by rijkvanzanten — APPROVED** [review]

**Comment by ProjGoodF** [comment]
It seems there is no way to insert an image from the media gallery now 🤷‍♂️

image

**Comment by Nitwel** [comment]
I had forgotten to make the new modals selectable in the interface settings.
#4961 and #4962 will resolve this, sorry for the inconvenience.

**Comment by ivoreis82** [comment]
The new module was very interesting! I miss being able to add in the images information to be used in the "title" attribute and in the "figcaption" element. Not only in the WYSIWYG module but anywhere where images are used in Directus. Do you intend to add this at some point?

**Comment by benhaynes** [comment]
We could always look into adding these inputs in a collapsed "Advanced Options" section at the bottom of the modal.

Also, a small UI note, but it'd be nice if the "lock ratio" button had a background color so it felt more like a button. :)

**Pull request merged**
