### PR TITLE
broken assets paths when serving Directus from a subfolder

### LINKED ISSUE #14565: 9.14.3 breaks assets paths when serving Directus from a subfolder (Apache)
### Describe the Bug

Up to version 9.14.1 serving Directus from a subfolder on Apache was working fine with the config from below.
On 9.14.3 the assets paths seems to be broken as the subfolder is now attached twice in the assets URL:
```
https://my.domain.com/cms/cms/assets/49857276-fb24-4db3-a808-6954becbb936
```

### To Reproduce

1. Create Directus instance and serve from subfolder in Apache

```
ProxyPreserveHost On
ProxyPass /cms http://127.0.0.1:8055
ProxyPassReverse /cms http://127.0.0.1:8055
```
.env
```
PORT=8055
HOST=localhost
PUBLIC_URL="https://my.domain.com/cms/"
```

2. Upload image and check path in network console 

### Errors Shown

_No response_

### What version of Directus are you using?

9.14.3

### What version of Node.js are you using?

16

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

Removed `getRootPath()` from all components where it gets passed to the `v-image` source in favor of letting the `v-image` deal with building the root path.

Fixes #14565 

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by spawnrider** [comment]
Hi @rijkvanzanten,

**This PR broke the loading of assets when the Directus instance is hosted in a subfolder.**

For example, if Directus is hosted in /cms subpatch : 
https://mycurrentdomain/cms/ 

Observed comportement : 
The background url is retrived from : 
https://mycurrentdomain/assets/xxx-xxx-xxxx 

Expected comportment : 
https://mycurrentdomain/cms/assets/xxx-xxx-xxxx 

I think the issue is also happening for foreground and others assets.

**Should we open an issue for that ?**

**Comment by rijkvanzanten** [comment]
> Should we open an issue for that ?

Yes please 👍🏻

**Comment by NDev8** [comment]
> **This PR broke the loading of assets when the Directus instance is hosted in a subfolder.**

Having the same problem with public background image.

If you are using Nginx as a reverse proxy then as a quick workaround, assets can be also served from the root path:

```nginx
# Pass only directus assets requested from root path also to directus
location ~* "^/assets/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}" {
	# Your proxy headers
	proxy_pass http://directus-upstream;
}
```

**Comment by NDev8** [comment]
> @NDev8 please open a new issue 👍🏻

I have opened an issue here: https://github.com/directus/directus/issues/16032

**Pull request merged**
