### PR TITLE
Fix fetching of all permissions

### LINKED ISSUE #18654: Missing Permissions since 10.1.1
### Describe the Bug

I have a mysterious bug since 10.1.1 where some user roles lost some of their permissions – but the permissions are set correctly.
I rolled back to 10.1.0 and everything is working again.

I think I found the bug: 
The permissions list is too long, and I guess due to this commit https://github.com/directus/directus/pull/17309 it is not being transferred entirely.
(Yes I have many collections)

- I used network inspector to see which permissions are being transferred, and turned out many of them were left out
- Then I used the API manually to get the permissions and same thing
- But as soon as I set limit:-1 to the request, all permissions get returned correctly.

### To Reproduce

Have many collections (I don't know how many, but the permissions API response was about 120 entries, around 4 per collection).

Create roles with varying CRUD-access to those collections

Log in as one of the roles and check if you can create/update items.

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by paescuj**
Fixes #18654 

~~Using the new `fetchAll` function introduced in #17309 to ensure all permissions are fetched~~

Temporary solution: forcing the permissions controller to return all items.

### CODE REVIEW

**Review by azrikahar — DISMISSED** [review]
Although this technically fixes the issue by making sure all permissions are fetched, but it seems like it "uncovered" a slight flaw with the `fetchAll` util, or in other words not accounting for unique behaviors such as permissions endpoint.

The `fetchAll` util currently starts with `hasMore = true`, and loops until the received data array is empty:

https://github.com/directus/directus/blob/268a1ee8fd093501278162c0d5611f87ee46fb14/app/src/utils/fetch-all.ts#L30-L36

However the permissions service unlike other typical services, has additional logic to always append to the result array (even if it's empty) with app access minimal permissions:

https://github.com/directus/directus/blob/268a1ee8fd093501278162c0d5611f87ee46fb14/api/src/services/permissions.ts#L46-L80

this in turn meant the returned array will _never_ be empty, thus causing the `fetchAll` util to loop indefinitely:

https://github.com/directus/directus/assets/42867097/d9d75c0d-e13d-41c5-9a74-eac6577da32d

(above setup has `QUERY_LIMIT_MAX=15` configured)

Perhaps a potential solution is for the permissions endpoint to have a flag so that we can make sure subsequent requests doesn't have the app access minimal permissions appended, but that feels slightly too hyper-specific at the moment, not sure if there's a better way to resolve this.

**Comment by paescuj** [comment]
> Although this technically fixes the issue by making sure all permissions are fetched, but it seems like it "uncovered" a slight flaw with the `fetchAll` util, or in other words not accounting for unique behaviors such as permissions endpoint.
> 
> The `fetchAll` util currently starts with `hasMore = true`, and loops until the received data array is empty:
> 
> https://github.com/directus/directus/blob/268a1ee8fd093501278162c0d5611f87ee46fb14/app/src/utils/fetch-all.ts#L30-L36
> 
> However the permissions service unlike other typical services, has additional logic to always append to the result array (even if it's empty) with app access minimal permissions:
> 
> https://github.com/directus/directus/blob/268a1ee8fd093501278162c0d5611f87ee46fb14/api/src/services/permissions.ts#L46-L80
> 
> this in turn meant the returned array will _never_ be empty, thus causing the `fetchAll` util to loop indefinitely:
> chrome_OzdFXyEaIj.mp4
> 
> (above setup has `QUERY_LIMIT_MAX=15` configured)
> 
> Perhaps a potential solution is for the permissions endpoint to have a flag so that we can make sure subsequent requests doesn't have the app access minimal permissions appended, but that feels slightly too hyper-specific at the moment, not sure if there's a better way to resolve this.

Hmm, good catch! Could we maybe get the minimal permissions in a single request and filter it out in the `fetchAll` call? Or isn't that possible via this `filterItems` function?

**Comment by paescuj** [comment]
> Hmm, good catch! Could we maybe get the minimal permissions in a single request and filter it out in the `fetchAll` call? Or isn't that possible via this `filterItems` function?

Feels also too hacky... 🕵️ Should we instead take this as an opportunity to implement https://github.com/directus/directus/pull/17309#issuecomment-1426218829? (cc @rijkvanzanten)

**Comment by rijkvanzanten** [comment]
We could have permissions api inject the static values first, and then force the offset to be static.length + query.offset? 🤔 That way it's only returned once, and the other logic stays the same

**Comment by u12206050** [comment]
Hmm, am I missing something? Why not just use `limit: -1`
```
const response = await api.get('/permissions', {
  params: { filter: { role: { _eq: userStore.currentUser!.role.id } }, limit: -1 },
});
```

Surely doesn't need to be that complicated?

**Comment by br41nslug** [comment]
> Hmm, am I missing something? Why not just use `limit: -1`
> 
> ```
> const response = await api.get('/permissions', {
>   params: { filter: { role: { _eq: userStore.currentUser!.role.id } }, limit: -1 },
> });
> ```
> 
> Surely doesn't need to be that complicated?

Because of this PR https://github.com/directus/directus/pull/17309 adding a configuration to add a MAX to `limit` (default is still `-1`)

**Review by licitdev — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
