### PR TITLE
Add the ability to provide custom liquid layouts and partials

### PR DESCRIPTION
**Pull request by danieljwestman**

### CODE REVIEW

**Comment by danieljwestman** [comment]
Or maybe in the reverse order for overwriting the defaults:

`[path.resolve(env.EXTENSIONS_PATH, 'templates'), path.resolve(__dirname, 'templates')]`

**Comment by rijkvanzanten** [comment]
> Or maybe in the reverse order for overwriting the defaults:

Great idea! Overwriting `base.liquid` would allow you to use a custom base template for the system transactional emails too

**Review by rijkvanzanten — APPROVED** [review]

**Comment by christianrr** [comment]
Wouldn't it make sense to always check the extensions template folder first for overrides - also for system templates? I'm thinking of translations into other languages, etc.

something like:
`private async renderTemplate(template: string, variables: Record<string, any>, system = false) {
	const resolvedPath = path.resolve(env.EXTENSIONS_PATH, 'templates', template + '.liquid');
	if (system && !fse.fileExists(resolvedPath)) resolvedPath = path.join(__dirname, 'templates', template + '.liquid');

	const templateString = await fse.readFile(resolvedPath, 'utf8');
	const html = await liquidEngine.parseAndRender(templateString, variables);

	return html;
}`

**Comment by rijkvanzanten** [comment]
@christianrr Yes it does, and that was done here: https://github.com/directus/directus/pull/5449 🙂

**Pull request merged**
