### PR TITLE
Fixed websocket authentication handling between websocket controllers

### LINKED ISSUE #23625: Streaming logs is breaking the regular REST websocket
### Describe the Bug

The introduction of the logs streaming endpoint (on path `/websocket/logs`) is interfering with the pre-existing REST websocket endpoint (on path `/websocket`). When connecting to the old websocket no authentication confirmation is ever received!

Current workarounds:
- Disable streaming logs (`WEBSOCKETS_LOGS_ENABLED=false`)
- ~Change the REST websocket path (`WEBSOCKETS_REST_PATH="/different"`)~

Example code:
```js
const socket = new WebSocket("ws://localhost:8055/websocket");
console.log("Socket initialized");

socket.addEventListener("open", () => {
  console.log("Socket open");

  socket.send(
    JSON.stringify({
      type: "auth",
      access_token: "<credentials>",
    })
  );
});

socket.addEventListener("message", (msg) => console.log("message received", msg.data));
socket.addEventListener("close", () => console.log("socket closed"));
socket.addEventListener("error", () => console.log("socket error!"));
```

Expected result (version 11.0.2):
image

Current result (version 11.1.0):
image

### To Reproduce

- Ensure that both websockets REST and logs streaming are enabled (they are by default)
- use the above script (or any other method) to connect to the rest websocket
- no authentication confirmation will ever be received

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgress

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #23625 

## Scope

*The cause:*

A new authentication function was introduced with log streaming `meetsAdminRequirement`. This function is used to enforce admin only for the logs streaming endpoint however instead of throwing an Error allowing the try catch to handle the closing of the connection it returns from the websocket upgrade process halfway leaving the connection open but in an error state.

This was the main culprit apparently missing a `not` in the `if`, causing the happy path to error:
https://github.com/directus/directus/blob/46611e67512279127216ddeec99a810cfb450dce/api/src/websocket/controllers/base.ts#L198

But others will return too in the case of failed authentication:
https://github.com/directus/directus/blob/46611e67512279127216ddeec99a810cfb450dce/api/src/websocket/controllers/base.ts#L310

*What's changed:*

- Renamed `meetsAdminRequirement` to a more generic `checkUserRequirements` in the abstract websocket controller
- Moved the logic from `meetsAdminRequirement` into the specific `LogsController`
- Removed the no-longer used `requireAdmin` property from the `WebsocketAuth` type/config
- Refactored `checkUserRequirements` to throw an error instead of returning

## Potential Risks / Drawbacks

- Potential authentication issues

## Review Notes / Questions

- I would like to lorem ipsum
- Make sure to test a regular websocket, graphql and log streaming to make sure authentication is performing as expected.

### CODE REVIEW

**Review by licitdev — DISMISSED** [review]
LGTM. It's cleaner with the method overriding! Thank you @br41nslug 🙏

**Review by licitdev — COMMENTED** [review]
@br41nslug The error thrown in `checkUserRequirements` will not close the connection. Should we close the connection like the previous error handling?

https://github.com/directus/directus/blob/62f57308f3ea6362866d9da06575c583d7739460/api/src/websocket/controllers/base.ts#L246-L254

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Code generally lgtm, once the above is resolved this can be merged

**Review by licitdev — APPROVED** [review]
> The "handleAuthRequest" function itself closes the connection here if checkUserRequirements fails and public connections are not allowed

Just confirmed this is the case, not sure why there was the unclosed connection previously 😓 

> I'm not sure this outer try-catch ignoring other errors is still required considering that entire function is one big try-catch already.

The outer try catch looks to be a failsafe to prevent the breaking of the connection. 🤔

**Pull request merged**
