### PR TITLE
Warn the user when a collapsed group field had an error

### PR DESCRIPTION
**Pull request by Nitwel**
GIF 01 09 2021 10-52-06

### CODE REVIEW

**Comment by benhaynes** [comment]
Can we make that `warning` icon small? I assume that's 24px, but perhaps we can try 18px?

**Comment by rijkvanzanten** [comment]
Also lets use `error_outline` instead of `warning`

**Review by rijkvanzanten — APPROVED** [review]

**Comment by benhaynes** [comment]
Can we get an updated screenshot or video here to see the end result? 🙏  @rijkvanzanten @Nitwel

**Comment by Nitwel** [comment]
GIF 03 09 2021 11-36-16

**Comment by benhaynes** [comment]
Thanks! Looks greeat!

**Pull request merged**
