### PR TITLE
Add file library integration for WYSIWYG interface

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
Adding file library integration for image and media plugins.

Issue https://github.com/directus/directus/issues/3160

UI
Screenshot 2020-12-02 at 2 24 52
Screenshot 2020-12-02 at 2 26 31

### CODE REVIEW

**Comment by seanmars** [comment]
Can add select image from uploaded in file library?

**Comment by dimitrov-adrian** [comment]
Yes, the tree dots on right, just like other file pickers.

**Comment by jooola** [comment]
This is nice, I am wondering if using tabs instead of the 3 dots is better. It is not obvious to me what the purpose of these 3 dots is.

TinyMCE seem to have something nice https://www.tiny.cloud/docs/demo/local-upload/

**Comment by dimitrov-adrian** [comment]
There is something that didn't take in mind. Returned URLs for images are without access token, which is logical since they shouldn't be stored, but then if the assets permission is not explicitly set to allow (which is logical for most use cases) the images are not loading because of forbidden.

@rijkvanzanten any advices?

**Comment by rijkvanzanten** [comment]
@dimitrov-adrian Good point.. that's not really something I have an answer for 🤔 We can't just plop in the access token of the current user, cause that might not be your "public" or "build" role. One way would be to have a "token" option for the interface that allows you to inject your own token to add to the images, but like you said, it isn't ideal if that's stored in the content in the DB

I think https://github.com/directus/directus/discussions/3144 could be a solution for the permissions situation too

**Comment by tboulogne** [comment]
hello,

Thanks for directus. Great works !
I'm balancing between directus and strapi. Directus get the bonus for now but the lack of this feature is a bad news for content production flow. This could help the switch if this review could be validate :-).

Thanks for help !

Regards

**Comment by benhaynes** [comment]
It's high on the list — we were working on other internal systems but will be back tot he core codebase starting tomorrow. 👍

**Comment by tboulogne** [comment]
thanks @benhaynes , if i'm lucky i could see this tomorrow on my screen :-) ?

**Comment by benhaynes** [comment]
Not likely to be tomorrow — we'll be _easing_ back into Core dev, so I'm sure there will be some smaller PRs and more critical issues that need attention first. But this week is a possibility!

**Comment by tboulogne** [comment]
@benhaynes i was kindling you a bit :-).

This week is ok for me. 

Thanks for all.

**Comment by tboulogne** [comment]
@benhaynes hello, a little up to know if we are in the way to see this this week.

Thanks for all

**Comment by rijkvanzanten** [comment]
@tboulogne We can't offer timelines for features/issues/PRs if it isn't a sponsored feature/PR. This is open-source software, work is prioritized internally, and all timelines are subject to change 👍🏻 See https://docs.directus.io/getting-started/support.html#sponsored-work for more information for more information on how to sponsor a feature.

**Comment by tboulogne** [comment]
Hello @rijkvanzanten Thanks for your reply. Sure it's open source with constraints. As you could read earlier, i was balancing between strapi and directus... On @benhaynes answer, i thought the boss's words was gold... and that i could choose directus...

**Comment by benhaynes** [comment]
@tboulogne — my words are gold, but you need to read them. We don't have any firm deadlines for new features unless they are sponsored, and this feature will be reviewed and added in when the Core team has time. Sometime soon, hopefully.

> We'll be easing back into Core dev, so I'm sure there will be some smaller PRs and more critical issues that need attention first. But this week is a **possibility**!

**Comment by tboulogne** [comment]
@benhaynes i read them :-), my question was : "a little up to know if we are in the way to see this this week.". So they was a gap between the question (to finalize a choice) and the answer of @rijkvanzanten directly on sponsoring... 

Note I will be ready to sponsor directus... but also remember i'm a french people and strapi is a frenchtech :-). So need some motivation to do so.

Thanks for all.

**Comment by tboulogne** [comment]
@benhaynes @rijkvanzanten : Could you let me know cost and delay for this feature on sponsored mode ? I send you a request on your dedicated form.

**Comment by benhaynes** [comment]
Sounds good — I replied via our messaging service. Regarding:

>...remember i'm a french people and strapi is a frenchtech :-). So need some motivation to do so.

We're not trying to convince anyone to use Directus over any another competitor — our platform speaks for itself. If being a French company is an important factor for you when choosing tech, that's fair, but no reason for us to try to motivate you. Browsing our ecosystem, you'll find that we're focused on the product, not sales.

**Comment by tboulogne** [comment]
get it thanks

**Comment by dimitrov-adrian** [comment]
I had just added imageToken setting to the interface like in the markdown

**Comment by Nitwel** [comment]
This is looking good. 👍 
@rijkvanzanten I'll need your help because file upload seems to be broken in general for me but when that is resolved and I fully tested this, it should be ready for merging.

**Review by rijkvanzanten — APPROVED** [review]

**Comment by lyonsbp** [comment]
When I try to use this feature the image upload box appears behind the insert/edit image modal, so I am unable to upload/select an image. This is on a fresh cli install.  If you look at the attached screenshot you can see a modal behind the current modal.
Anyone else have this issue?

Screen Shot 2021-02-25 at 12 07 15 AM

**Comment by SaizFerri** [comment]
I have the same issue. Seems to be a problem with the z-index of the second overlay.

**Comment by teokk1** [comment]
I have the same issue.

**Comment by beschneider** [comment]
Yes, same issue.

**Comment by iqraaaswad** [comment]
> When I try to use this feature the image upload box appears behind the insert/edit image modal, so I am unable to upload/select an image. This is on a fresh cli install. If you look at the attached screenshot you can see a modal behind the current modal.
> Anyone else have this issue?
> 
> Screen Shot 2021-02-25 at 12 07 15 AM

add this css to your custom css

`
.tox.tox-tinymce-aux {
    z-index: 499!important; 
}

.tox.tox-silver-sink.tox-tinymce-aux+.tox.tox-silver-sink.tox-tinymce-aux {
    z-index: 500!important;
}

span.vue-portal-target > .container.right+.container.center {
    z-index: 501!important;
}

span.vue-portal-target > .container.right+.container.center.container.center {
    z-index: 502!important;
}

.vue-portal-target > .v-menu-popper.active {
   z-index : 502!important;
}

.vue-portal-target > .container.right+.container.center+.container.right {
    z-index: 503!important;
}

.vue-portal-target > .container.right+.container.center+.container.center {
    z-index: 504!important;
}`

**Pull request merged**
