### PR TITLE
Add checkboxes-tree interface

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Allows for a multi-level list configuration

CleanShot 2021-06-22 at 16 58 42@2x

### CODE REVIEW

**Comment by supermx1** [comment]
Didn't see this interface... :(

**Comment by Kematia** [comment]
Is this coming for relational data? I had a similar one for recursive items. It's perfect to display the reverse of a o2m-tree!

**Comment by rijkvanzanten** [comment]
> Is this coming for relational data? I had a similar one for recursive items. It's perfect to display the reverse of a o2m-tree!

Good one! It isn't on the planning right now, but that should definitely be doable. The only thing we'll have to make sure is that we fetch the nested groups asynchronously as you could have a _ton_ of related o2m items 🤔

**Comment by Kematia** [comment]
> you could have a ton of related o2m items

 This is exactly what's going on with my clients 🤣 


https://user-images.githubusercontent.com/17851386/124384185-60c89b00-dcd0-11eb-904a-9c9bd07189d7.mp4



> fetch the nested groups asynchronously

Yup! In my own implementation I had a custom endpoint (I also needed a denormalized list), but here we could "traverse" the api with a depth of three? We need data of atleast the `child` item to display a togglable list-group

The API call would be done with `fields: ['*.*.*]`, could be a good middle ground...

**Comment by rijkvanzanten** [comment]
> The API call would be done with fields: ['*.*.*], could be a good middle ground...

Nah, this doesn't scale at all (burned myself big on this in v7/v8 😉 )

We'll have to check if an item has things in the "children" field on every level, and do the api request for the next nested level when the group is opened

**Comment by Kematia** [comment]
> > The API call would be done with fields: ['_._.*], could be a good middle ground...
> 
> Nah, this doesn't scale at all (burned myself big on this in v7/v8 😉 )
> 
> We'll have to check if an item has things in the "children" field on every level, and do the api request for the next nested level when the group is opened

@rijkvanzanten 


https://user-images.githubusercontent.com/17851386/124480721-dbb0b500-dda7-11eb-8265-c8179a9d4cf2.mp4

I'm stuck at the "fetching data at every level" stage for now.

I don't know how to approach it yet, I was thinking along those lines:

1. Make a relational only `v-checkbox-tree` duplicate
2. Hack the current `v-checkbox-tree` into recognizing relational data (or trigger the behaviour with a `dataType: relational` prop), and then dispatch a `get` request from inside the component
3. Have the current `v-checkbox-tree` emit a `hasOpened` event and handle the update from the parent component

2 and 3 are a bit hacky, and 1 is a bit verbose...

**Comment by Kematia** [comment]
I think I got it!

https://user-images.githubusercontent.com/17851386/124571941-8678b000-de48-11eb-92e4-06b5cfc8dec7.mp4



I added a `childrenParser` function as a prop of `v-checkbox` and `v-checkbox-tree`.
image

 Then I passed a function to fetch the children item (don't mind the hardcoded values, it's just for development). 
image


The saving doesn't work right now, but I think it's just a matter of emitting the right value (the uuid).

I can see a couple more roadblocks in the next steps but this might have been the biggest one.

**Comment by rijkvanzanten** [comment]
Ohh interesting approach! Yeah passing a "on group open" async event handler to the v-checkbox-tree group level makes a lot of sense. We should also have a loading prop to go with it, and/or have the checkbox group level render it's own spinner while waiting for the async loader. The other major question is how we're going to handle search. We might be able to search through the whole related collection, and then go back up the tree once we find it?

**Comment by Kematia** [comment]
> Yeah passing a "on group open" async event handler to the v-checkbox-tree group level makes a lot of sense.

It's actually just a computed value of the children field, so it's computed on the component's creation. It's incidentally triggered  when the group is toggled because that's when the children interfaces get spawned. But we can have it emit a `loading` event no problem inside the `childrenParser` function! 

> The other major question is how we're going to handle search. We might be able to search through the whole related collection, and then go back up the tree once we find it?

That's what I was thinking of as well! we will have a backend call to recursively find the _branch_ starting from the current _leaf_, working our way from the bottom to the top. It would return an array of ids to display in the interface. 

Such a call would guarantee the least amount of backend calls, and the same approach could be used for the search function as well I reckon, seeing that it's the same usage pattern of displaying the current value - only the origin of the input changes (value saved in the db/user input).

**Pull request merged**
