### PR TITLE
Rework api caching

### LINKED ISSUE #15177: Drop support for memcached
Memcached doesn't support pub/sub, which means it can't be used for various things we need to rely on a central store for, including cross instance messaging, effective queuing, and websockets support. 

Instead of trying to support memcached where it can be used, and use Redis for everything else, it makes more sense for the long term maintenance of the project to focus exclusively on Redis. Also ref #15176

### LINKED ISSUE #15178: Drop keyv in favor of direct Redis use
Once we drop support for memcached (as per https://github.com/directus/directus/issues/15177), we can drop the dependency on `keyv` in favor of using Redis directly. This allows us to rely on specific Redis functionality that doesn't exist in memcached, which in turn greatly improves the performance and maintainability of the project.

### LINKED ISSUE #15179: Upgrade schema information retrieval and caching
Currently, we introspect the whole schema on the first request, and store the result in the cache. This cached schema overview object is then passed around to all the services so they can rely on the schema information in operation.

This comes with a handful of downsides:

- Introspecting the database schema fresh can take quite a while
  Depending on the database vendor used, it can take anywhere from 30ms to 1.5 seconds to introspect the full database schema. Even though we heavily cache it, that's a non-trivial amount t of time to wait for the schema to be known
- The output schema object is pretty big. Depending on your schema, the overview object can easily be over half a million characters, which in turn causes:
- Caching is very fast for smaller chunks of data with large read/write ops. However, storing a single massive value can easily cause bottlenecks it the connection to/from the caches
- The full schema is read even when it's not needed / only partially used

To improve on this, we should:

- Introspect (and cache) parts of the schema when they're actually requested, rather than all ahead of time
- Store the schema information in smaller chunks (eg per collection / field) in the caches

### PR DESCRIPTION
**Pull request by Nitwel**
Throws keyv and memcache out of the window. (╯°□°）╯︵ ┻━┻
Makes the schema access scale O(1) instead of O(n).

closes #15177
closes #15178
closes #15179

### CODE REVIEW

**Comment by daawaan4U** [comment]
helloo, stumbled upon this from #13401, looks exciting btw 🤯, i know that this PR mostly focuses on schema access, but are there set plans on the roadmap to implement granular cache-invalidation for queries with the new cache service (e.g. creating/updating/deleting certain items only purge the cached queries that possibly contains it?

**Comment by rijkvanzanten** [comment]
@daawaan4U Yes absolutely, though that gets complicated really fast, so we'll have to take this one step at a time 🙂

**Comment by joselcvarela** [comment]
Just to be aware that, currently, if getting value from cache and retrieving that value takes longer than timeout, Directus crashes.
I believe that can be tested with a small `CACHE_REDIS_COMMAND_TIMEOUT` value like 200ms or using `ipfw` command within Redis container.

**Comment by rijkvanzanten** [comment]
Merging this into v10 so we can use that branch as a blue-print for prod implementation of the updated caching logic 💪🏻

**Pull request merged**
