### PR TITLE
Feat: Export only selected items

### PR DESCRIPTION
**Pull request by yarick2000**
Fixes #5898

Added optional functionality that allows to export only selected items from the view. User can disable this option (it's enabled by default) by unchecking new 'Use selected items' checkbox in the export sidebar.

### CODE REVIEW

**Comment by benhaynes** [comment]
Nice idea!! Thanks @yarick2000!

**Comment by doodlemania2** [comment]
Suggest always disable by default at this point if we're changing base functionality, but agreed - this is excellent idea!

**Comment by yarick2000** [comment]
> Suggest always disable by default at this point if we're changing base functionality, but agreed - this is excellent idea!

Ok, fixed that, now this option unchecked by default.

**Comment by rijkvanzanten** [comment]
With the totally overhauled exporting flow, this idea and toggle will have to be revisited. Lets keep discussing the above question, and the other ifs and hows of the implementation of this idea over on https://github.com/directus/directus/discussions/12967 🙂

**Comment by yarick2000** [comment]
Hi Rijk, that sounds nice, but unfortunately, right now Directus is not on
my plate. Maybe sometime later I'll be back on board...

**Pull request closed without merging**
