### PR TITLE
Fix field aliasing not returning null after merging documents

### PR DESCRIPTION
**Pull request by addisonElliott**
## Description

Bug introduced in #12759

Fix niche case with aliasing where `{}` was returned instead of `null` if **all** aliased fields were `null`. This stems from the fact that `_.merge(null, {})` will return `{}`. This is a problem because `{}` is truthy and has some unintended side-effects throughout the codebase.

This can be reproduced if you take a M2O relation and allow null values. In my instance, I discovered this from a user display. It'll show "Unknown User" instead of "--" to indicate it's null.

**Note:** I didn't touch the merging of multiple results for each field pivot because it's unclear to me if/how that needs to be changed. Advice welcome there.

Example:

image

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Review by br41nslug — COMMENTED** [review]
I am unable to recreate the error situation using the production steps on the `main` branch or v9.13. Am i missing steps to get to this exact situation?
image
Could this problem have been tackled by other pr's perhaps ( like #14241 addresses a similar issue)

**Comment by addisonElliott** [comment]
The problem's still there AFAICT. I'm testing on Directus Cloud which has v9.13.

If you have a demo version on Directus Cloud, you can reproduce by setting author field to nullable in articles collection. From there, set the author to null on an article and you'll see this.

In your screenshot, you're not using the user display like in my screenshot. You can sort-of see the issue in your screenshot where it's showing 6 dashes (`------`) because it's displaying null for each item in the display template. You should only see 2 dashes because the entire item is null.

In the demo version, the author field is using the User display somehow. Not sure how to reproduce that part without manually editing the database.

**Comment by br41nslug** [comment]
i'll re-test on a cloud demo instance 😄

**Comment by azrikahar** [comment]
One way I've used to reliably reproduce this is to create a collection with "Updated By" system field, then add a simple string field. Then create 2 items, but making sure to update 1st item afterwards, and we can see the 2nd item shows the Unknown User value:

image

Tested this PR and it works like a charm. Seeing that the API does return null for said nested user fields when there's no user, I do think it makes sense to prevent alias logic from "building" an empty object instead of null. 🤔

> In the demo version, the author field is using the User display somehow. Not sure how to reproduce that part without manually editing the database.

The demo does indeed "manually" use the user display even though it's selectable at the moment. Seeing that the field schema does check whether it's a M2O to `directus_user` before showing OnCreate/OnUpdate with "Save Current User ID", a similar enhancement to make user display selectable would no doubt be helpful! But let's move that as a feature request in discussions.

**Review by azrikahar — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
