### PR TITLE
Fix permissions using dynamic user or role fields

### LINKED ISSUE #18898: Update permissions is incorrect
### Describe the Bug

When you try to set Item update permissions to something nested, for example we have relation like A -> B, and we want to allow edit A, only when B.status  eq published. So I created filter A->B.status eq published, but I cannot edit A at all. It's new bug which was introduced in 10.3.0, previous versions works fine

### To Reproduce

Create two collections, like A and B, and try to set Update item permissions to something nested like A->B.status eq published

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

### LINKED ISSUE #19039: Permissions using $CURRENT_USER.X not working
### Describe the Bug

Since 10.3.0 Permissions on directus collections that have minimal default permissions such as on the `directus_users` collection, don't seem to work with custom permissions when using `$CURRENT_USER.SOME_FIELD`

This results in fields being read only it seems and can't be edited.

From #18898

### To Reproduce

Create a `user_roles` collection with 
`user` m2m to `directus_users` with `roles` as alias
`role` m2m to `directus_roles` with `users` as alias

On a custom role on the `directus_users` collection add a permission to UPDATE eg.
{
  "role": {
      _in: "$CURRENT_USER.roles.role"
   }
}

Add the roles of other people to the user you will be testing with that has the new permission.
And then switch to that user to test if they can edit other people with the role that exists in one of their roles.

### Directus Version

10.3.0-10.3.1

### Hosting Strategy

Self-Hosted (Custom)

# root cause: 92f2a9197e1c71e88a92eb498278571f4901b0de

### LINKED ISSUE #19043: Item permissions do not work when updating and deleting
### Describe the Bug

Since version 10.3.0 - 10.4.0, item permissions for updating and deleting have ceased to work in the rules of which there are nested collections.

This results in fields being read only it seems and can't be edited.

related bugs:
From #18898 
From #19039 

this works great in v10.2.1 and below

### To Reproduce

in my case i create collections
1. Organizations
2. Clinic
3. Appointments

organization has relation one to many with clinic and relation many to many system collection **directus_role**

Appointments has relation many to one with clinic

i am trying to filter access by $CURRENT_ROLE
important: in organization i added role for example manager

when user with role manager try to edit appointment, he can't do it, because fields being read only

but admin, has access ...

i also try to create another simple collection "discount" without relation and filtering access by $CURRENT_ROLE 

image_2023-06-30_13-50-46

and this doesn't work to ...

and so I thought, what if i use my role GUID and i try it

image_2023-06-30_13-52-16

and it doesn't work to, user can't edit and delete

image_2023-06-30_13-53-45

I confirm that it works in the v10.2.1 and below

### Directus Version

v10.3.0 - v10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by u12206050**
Dynamic variables were not fetched, so not being parsed and checked

Fixes #19039, fixes #18898, fixes #19043

### CODE REVIEW

**Comment by u12206050** [comment]
Have tried fixing the unit tests, but have been unable to mock the pinia store successfully.

**Comment by u12206050** [comment]
Should I just remove the unit tests so it will pass, even though I think it is best to include them?

**Comment by paescuj** [comment]
> Should I just remove the unit tests so it will pass, even though I think it is best to include them?

I'll look into this later that day 👍

**Review by paescuj — APPROVED** [review]

**Comment by u12206050** [comment]
Nice, well done @paescuj thanks! Hopefully we can get this released asap? Have been waiting on a fix for almost a month now.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
