### PR TITLE
Content

### PR DESCRIPTION
**Pull request by erondpowell**
@rijkvanzanten

I forgot to apply a few of our talking-points globally (not just on the area we commented).
In the process, I added a few more last-sec edits.

I'm really done this time 🙏

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@erondpowell mind resolving the conflicts?

**Comment by erondpowell** [comment]
> @erondpowell mind resolving the conflicts?

Should be good to go now 👍

**Comment by erondpowell** [comment]
Screen Shot 2022-04-21 at 4 42 43 PM

Also, is this supposed to be like this?

**Comment by benhaynes** [comment]
@rijkvanzanten is going to get you a special "placard" for `Cloud Exclusives` similar to our extensions one. Also, I DM'd you a folder of approved media to use (instead of our logo). Also, let's make sure to really showcase a rich experience... this Kanban should have more "tasks" in it so it feels a bit more robust.

Also, I don't think the column groups are limited to "status"... it can be any field to group on (I think).

But yes, this is what I was thinking!

**Comment by erondpowell** [comment]
> @rijkvanzanten is going to get you a special "placard" for `Cloud Exclusives` similar to our extensions one. Also, I DM'd you a folder of approved media to use (instead of our logo). Also, let's make sure to really showcase a rich experience... this Kanban should have more "tasks" in it so it feels a bit more robust.
> 
> Also, I don't think the column groups are limited to "status"... it can be any field to group on (I think).


Nice 👍 Yeah as soon as that kanban bug is worked out I plan on redoing these into videos.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
