### PR TITLE
check that collection exists and not a singleton on panels

### LINKED ISSUE #15212: GraphQL query fails when using query parameters on a singleton data model
### Describe the Bug

It is currently not possible to use data from a singleton data model as source for an insights dashboard (tested with the metric type).

image

### To Reproduce

- Create a new data model and mark it as singleton
- Create a new dashboard and use any value from this data model

### Errors Shown

```
{"errors":[{"message":"GraphQL validation error.","extensions":{"code":"GRAPHQL_VALIDATION_EXCEPTION","graphqlErrors":[{"message":"Unknown argument \"limit\" on field \"Query.build_status\".","locations":[{"line":1,"column":39}],"path":["query_6df036f1"]}]}}]}
```

Additionally, if a sort-column is set, it will complain about that as well.

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

### LINKED ISSUE #15334: Time series panel error when it is linked to a collection that not longer exists
### Describe the Bug

When viewing a time series panel that is getting data from a collection, and we intentionally delete said collection, the panel will show the spinner indefinitely since there's an error.

https://user-images.githubusercontent.com/42867097/187624993-880f32f3-7641-4722-bc8c-da2a393b151c.mp4

The error seems to stem from here:

https://github.com/directus/directus/blob/d7b8ef297e1389d648cd7b7ed7d9db3b8eca57b0/app/src/utils/query-to-gql-string.ts#L33

Where the non-null assertion causes the accessing of `.field` to error out.

Perhaps the fix would be to prevent fetching of data when the panel is relying on a collection/field  that does not exist anymore.

### To Reproduce

1. Create a new collection for time series panel later on
   - ensure to create a numeric field as the time series value
   - ensure to create a datetime/timestamp field as the time series date
2. Create dashboard, then create a time series panel with above collection
3. View the panel, everything should work fine
4. Go to data model and delete the new collection
5. Go back to view the panel, it will throw gql validation error (because the API side couldn't find the collection and field anymore)
6. Refresh browser so that the collections and fields store can rehydrate
7. Notice that the panel is infinitely spinning, and refer to "Errors Shown" section below for the error appeared in browser console

### Errors Shown

Browser console error:

```
query-to-gql-string.ts:33 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'field')
    at formatQuery (query-to-gql-string.ts:33:93)
    at queryToGqlString (query-to-gql-string.ts:17:32)
    at loadPanelData (insights.ts:205:21)
    at Proxy.refresh (insights.ts:170:9)
    at Proxy.<anonymous> (pinia.esm-browser.js:1305:30)
    at beforeEnter (index.ts:25:11)
    at vue-router.esm-bundler.js:1934:35
    at new Promise (<anonymous>)
    at vue-router.esm-bundler.js:1908:18
    at vue-router.esm-bundler.js:3423:65
```

### What version of Directus are you using?

latest main branch

### What version of Node.js are you using?

16.16.0

### What database are you using?

PostgreSQL 13.5

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally in dev build

### PR DESCRIPTION
**Pull request by freekrai**
## Description

This PR adds a check to metric, list and time-series panels to see if the collection is either:

1. no longer existing aka deleted, renamed, or just plain flew away somehow
2. singleton

If the collection does not exist or is a singleton then we just issue a return and don't execute.

Fixes #15212, fixes #15334

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Sweet! This is perfect. 

Last little tweak here is that we should prevent singletons from being selected in the first place. Right now, you can still select the singleton, and it would then just fail silently, which isn't the best UX.

**Comment by freekrai** [comment]
Yeah can work on that part shortly

**Comment by rijkvanzanten** [comment]
Also what was the original issue you were trying to link? #15221 seems to be an unrelated PR

**Comment by freekrai** [comment]
> Also what was the original issue you were trying to link? #15221 seems to be an unrelated PR

I edited that #15212 was the original link but somehow it typed it as 221 🤦🏻

**Comment by freekrai** [comment]
I've added a prop to system-collection interface: `includeSingleton` which is `true` by default, then in the panels, we set this to `false`, as that is what we call to fetch the collections.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
