### PR TITLE
Move repo to `pnpm` based workflow

### PR DESCRIPTION
**Pull request by rijkvanzanten**

### CODE REVIEW

**Comment by abdonrd** [comment]
Just curiosity, why pnpm instead of npm workspaces?

**Comment by rijkvanzanten** [comment]
> Just curiosity, why pnpm instead of npm workspaces?

We're currently relying on npm workspaces, but it isn't fully featured yet. To get around that, we're relying on `lerna` to augment it with features we need, but that comes with it's own quirks. Pnpm does all we need out of the box, and has the added benefit that it's global-symlinked based module resolution generally really comes in handy when maintaining multiple projects that all share the same dependencies (installs are way faster for example)

**Comment by loongmxbt** [comment]
Hi, we used to use old versions to develop extensions(before 9.11, npm). Today we pull the lastest update, we followed https://docs.directus.io/contributing/running-locally/ and cannot get it run, hope to update the `running locally` docs.

**Comment by rijkvanzanten** [comment]
We updated that particular doc to show all the `pnpm` commands. What issues are you seeing?

**Comment by seymoe** [comment]
@rijkvanzanten I got "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  not found: build" when I execute `pnpm build` and cannot find out reason.

Node v16.13.0 (npm v8.14.0)

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten I got "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  not found: build" when I execute `pnpm build` and cannot find out reason.
> 
> 
> 
> Node v16.13.0 (npm v8.14.0)

It's `pnpm -r build` (note the -r)

**Comment by loongmxbt** [comment]
> > @rijkvanzanten I got "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  not found: build" when I execute `pnpm build` and cannot find out reason.
> > Node v16.13.0 (npm v8.14.0)
> 
> It's `pnpm -r build` (note the -r)

Thanks a lot, `pnpm -r build` solves the problem.

**Comment by SeanDylanGoff** [comment]
A big <3 for this, actually wanted to propose it sometime, but never got to it. AWESOME!

**Comment by MajedMuhammad** [comment]
I see supporting pnpm will prevent us from using npm. 
npm i is showing:
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

**Comment by rijkvanzanten** [comment]
Yes, use `pnpm` to build the repo from source

**Comment by MajedMuhammad** [comment]
Yes, got it. But now, no way to use npm?

**Comment by rijkvanzanten** [comment]
No, `pnpm` is required to build the repo from source

**Pull request merged**
