### PR TITLE
Updated readme installation instructions to use docker

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

Updated installation instructions to use docker instead of npm

Refs [DOCS-135](https://linear.app/directus/issue/DOCS-135)
Follow up to [DOCS-61](https://linear.app/directus/issue/DOCS-61)

## Type of Change

- [ ] Bugfix
- [X] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by br41nslug** [comment]
@paescuj Thats definitely an option too i hadnt considered, i was mainly focussed on updating the undocumented `npm install` instructions that still lingered.

**Comment by paescuj** [comment]
> @paescuj Thats definitely an option too i hadnt considered [...]

I'm glad you're considering this as a possible option! I'm gladly available for further discussion on this.

> [...] i was mainly focussed on updating the undocumented `npm install` instructions that still lingered.

Perfectly understandable!

**Comment by erondpowell** [comment]
@br41nslug Are you by chance waiting for a review to merge?

**Comment by paescuj** [comment]
@erondpowell I was suggesting to dropping the installation second from the README and link to the documentation instead... I would also be very interested in your opinion about this!

**Comment by rijkvanzanten** [comment]
Lets drop it in favor of pointing people to the docs!

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
