### PR TITLE
Update to Vue 3.3

### PR DESCRIPTION
**Pull request by paescuj**
Update to [Vue 3.3](https://blog.vuejs.org/posts/vue-3-3) and update of related dependencies.
This will be of benefit for the further app code clean-ups / optimizations which are planned for the coming days.

**Note:** Removed [`@vue/compiler-sfc`](https://www.npmjs.com/package/@vue/compiler-sfc) since it's included as a dependency of the main vue package as of 3.2.13 and replaced `rollup-plugin-vue` with `@vitejs/plugin-vue` (see https://github.com/directus/directus/pull/18588#issuecomment-1546740015).

### CODE REVIEW

**Comment by hanneskuettner** [comment]
Have you verified that you can build extensions with the SDK with Vue 3.3? Cause when I tried it manually yesterday by bumping the compiler-sfc I realized that the rollup-plugin-vue doesn't support that and afaik that is used for bundling the extensions?

**Comment by paescuj** [comment]
> Have you verified that you can build extensions with the SDK with Vue 3.3? Cause when I tried it manually yesterday by bumping the compiler-sfc I realized that the rollup-plugin-vue doesn't support that and afaik that is used for bundling the extensions?

Yeah, worked for me 👍 Would you mind testing against this branch?

**Comment by paescuj** [comment]
> Have you verified that you can build extensions with the SDK with Vue 3.3? Cause when I tried it manually yesterday by bumping the compiler-sfc I realized that the rollup-plugin-vue doesn't support that and afaik that is used for bundling the extensions?

Good point though with `rollup-plugin-vue`. This plugin is no longer maintained already for some time (see https://github.com/vuejs/rollup-plugin-vue).
Therefore I replaced it with [`@vitejs/plugin-vue`](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue) in https://github.com/directus/directus/pull/18588/commits/ecb77b55787ea2d1279dd77e72cb89b087e7c9c6.
This is possible since Vite plugins are are also valid Rollup plugins. Tested and everything looks fine. 👍

**Review by br41nslug — COMMENTED** [review]
Encountered no issues when recompiling a module and bundle with frontend extensions on my end.

However I am seeing this warning pop up:
image

**Comment by paescuj** [comment]
> Encountered no issues when recompiling a module and bundle with frontend extensions on my end.

Great, thanks for your tests!

> However I am seeing this warning pop up: image

Yeah, unfortunately the warning has been appearing for some time (unrelated to this PR). This plugin is not actively maintained anymore. While it seems to work with Rollup v3 the it requires Rollup v2 in its peer dependencies.

**Review by azrikahar — APPROVED** [review]
LGTM. Although technically the frontend extensions (eg. interface) built file seems a tiny bit different, but seems to works the fine for me as well 👍

---

Vue 3.3 blog post: https://blog.vuejs.org/posts/vue-3-3

> The new `defineOptions` macro allows declaring component options directly in `<script setup>`, without requiring a separate `<script>` block

this did ever so slightly bothered me as well with our usages of `inheritAttrs: false` in a number of places, glad we can clean them up now!

**Comment by paescuj** [comment]
> LGTM. Although technically the frontend extensions (eg. interface) built file seems a tiny bit different, but seems to works the fine for me as well 👍

Yeah, it's compiled a slightly different (other names for the variables, ...), but ultimately the same result.

<details><summary>Diff</summary>

```diff
4c4
< var script = defineComponent({
---
> var _sfc_main = defineComponent({
20,28d19
< const _hoisted_1 = ["value"];
<
< function render(_ctx, _cache, $props, $setup, $data, $options) {
<   return (openBlock(), createElementBlock("input", {
<     value: _ctx.value,
<     onInput: _cache[0] || (_cache[0] = $event => (_ctx.handleChange($event.target.value)))
<   }, null, 40 /* PROPS, HYDRATE_EVENTS */, _hoisted_1))
< }
<
31c22
< var css = "\ninput[data-v-64969d30] {\n    width: 200px;\n}\n";
---
> var css = "\ninput[data-v-6e321582] {\n    width: 200px;\n}\n";
34,36c25,31
< script.render = render;
< script.__scopeId = "data-v-64969d30";
< script.__file = "src/interface.vue";
---
> var _export_sfc = (sfc, props) => {
>   const target = sfc.__vccOpts || sfc;
>   for (const [key, val] of props) {
>     target[key] = val;
>   }
>   return target;
> };
37a33,41
> const _hoisted_1 = ["value"];
> function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {
>   return openBlock(), createElementBlock("input", {
>     value: _ctx.value,
>     onInput: _cache[0] || (_cache[0] = ($event) => _ctx.handleChange($event.target.value))
>   }, null, 40, _hoisted_1);
> }
> var InterfaceComponent = /* @__PURE__ */ _export_sfc(_sfc_main, [["render", _sfc_render], ["__scopeId", "data-v-6e321582"], ["__file", "interface.vue"]]);
>
43c47
<   component: script,
---
>   component: InterfaceComponent,
```

</details>

> Vue 3.3 blog post: https://blog.vuejs.org/posts/vue-3-3
> 
> > The new `defineOptions` macro allows declaring component options directly in `<script setup>`, without requiring a separate `<script>` block
> 
> this did ever so slightly bothered me as well with our usages of `inheritAttrs: false` in a number of places, glad we can clean them up now!

Oh yes, so many cool updates in this release 🚀

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
