### PR TITLE
Add Subject to password request (SDK)

### PR DESCRIPTION
**Pull request by AndreyKindin**
Adding the possibility to add a custom subject to the password request email via JavaScript SDK

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I'm not sure if this meets [80/20](https://docs.directus.io/contributing/introduction/#feature-requests) 🤔 

On a more serious note though, I think this could be considered a bit of a security risk. If you can change the subject on the fly, you could fairly easily phish someone into thinking it's from another source. What's the use case you're trying to solve with this feature?

**Comment by AndreyKindin** [comment]
>  What's the use case you're trying to solve with this feature?

The use case is relatively simple, different customers want/need different subjects in different languages in their emails. The customers have users who don't speak English and for them "Password Reset Request" is a no go because it's the same as "blah blah blah" 😊.  And that is why it is very important to have the possibility to change the subject (80/20) if the system is not only designed for english speakers.

> On a more serious note though, I think this could be considered a bit of a security risk. If you can change the subject on the fly, you could fairly easily phish someone into thinking it's from another source.

The security relevant is the link to the password reset and this is in the env and indeed the sender of the mail which also can not be changed on the fly. If I want/can fake all this I don't use the password request mail.

**Comment by benhaynes** [comment]
We should be able to use our standard translation function so the system handles subjects in different languages... right, @rijkvanzanten ?

**Comment by AndreyKindin** [comment]
Translation is a good and necessary solution for default value, but not for dynamic customization.
How about 2 more variables in the .env once for requestPasswordReset and inviteUser
EMAIL_PASSWORD_RESET_SUBJECT
EMAIL_USER_INVITE_SUBJECT
i can make the pull request for this

**Comment by rijkvanzanten** [comment]
Having the subject be overridable in the env vars is a nice first step, but still leaves a couplet things to be desired. It won't account for user languages still, and won't allow for things like overriding the body copy either.

I think the better approach here would be to implement API translations first (so the emails are sent in the users preferred language), and add the ability to override these translations second (which would allow the server admin to tweak any aspect of the default emails at will.

**Comment by AndreyKindin** [comment]
have done the first step and set a new pull request 
https://github.com/directus/directus/pull/7412

**Comment by rijkvanzanten** [comment]
As per https://github.com/directus/directus/pull/7372#issuecomment-898463064, I think the real solution here is to implement proper translatable strings on the API side, which can then in turn be used to change the strings used for various things that come from the API, like the sent emails. Lets not busy up the env vars with configuration that we know will be deprecated soon after 👍🏻  Thanks for the suggestion tho! ❤️

**Comment by JonathanSchndr** [comment]
I would like to get more momentum here, because there is a big NEED that at least the subject is translatable. But now a global solution should be created to implement a translation before the API. So that one can cover this, a precise briefing would be important again and a clean list of requirements.

**Comment by rijkvanzanten** [comment]
> I would like to get more momentum here, because there is a big NEED that at least the subject is translatable. But now a global solution should be created to implement a translation before the API. So that one can cover this, a precise briefing would be important again and a clean list of requirements.

Translatable is not the same as fully custom though! The latter comes with big security implications. Mind opening a new feature request detailing how this should work ideally? That'd help getting this moving in the right direction 🙂

**Comment by JonathanSchndr** [comment]
> > I would like to get more momentum here, because there is a big NEED that at least the subject is translatable. But now a global solution should be created to implement a translation before the API. So that one can cover this, a precise briefing would be important again and a clean list of requirements.
> 
> Translatable is not the same as fully custom though! The latter comes with big security implications. Mind opening a new feature request detailing how this should work ideally? That'd help getting this moving in the right direction 🙂

#17485

**Pull request closed without merging**
