### PR TITLE
include default values in use-item

### LINKED ISSUE #5697: include default field values in initialValues
The 'values' provided by v-form do not include default values.

This might be intended (?) but it makes it difficult to work with custom interfaces/hooks that rely on a complete data set being passed through. Although it'd be possible to fetch default values from the db when working with custom extensions, it'd be safer to have them included in the emitted object right away.

Would it be possible to include default field values in initialValues or have v-form emit them just like user inputs?

### PR DESCRIPTION
**Pull request by ghost**
closes #5697

### CODE REVIEW

**Comment by maximilian-github** [comment]
I had a feeling this was too easy… and it was … kind of. 

We can't assume that we can just handle all field.schema?.default_value like this. It seems to work fine for all fields managed by directus except for "id", but when I set an auto increment int directly in the db, I run into the same problem of course.

Now, I first thought this was an error in my approach. But it turns out that form-field.vue does the same: 
```
const _value = computed(() => {
		if (props.value !== undefined) return props.value;
		if (props.initialValue !== undefined) return props.initialValue;
		return defaultValue.value;
// > [Vue warn]: Invalid prop: type check failed for prop "value". Expected Number with value NaN, got String with value "nextval('test_id_int'::regclass)".
});
```

So I guess we indeed can just leave it like this for now and solve the underlying problem at a different time. Or is this not a bug because we assume that everything is managed exclusively through directus? Even if that's the case, do we expect to implement new features (like auto increment ints) that would have us run into the same issue later? @rijkvanzanten: could you give me a rough idea how you feel about this? Am I missing something? :) Thank you!

**Comment by rijkvanzanten** [comment]
@maximilian-github I think this is the right track 👍🏻 

> but when I set an auto increment int directly in the db, I run into the same problem of course.

This is a different problem that we'll have to solve separately from this issue I think 🙂  (ref https://github.com/directus/directus/discussions/5472)

**Comment by Oreilles** [comment]
Directus should not try to insert the actual default value into a field that has a default value, because there is no way to know if it's a string or a function.
The whole point of having a default value for a field (from the database pov) is to be able to input null into them.
If anything, the `defaultValue` should be only presentational: show it to the user in the schema, but leave it empty everywhere else.

**Comment by rijkvanzanten** [comment]
That's true. I do think it's useful to have them passed to the other fields in the injected `values` though 🤔

**Comment by rijkvanzanten** [comment]
As per aurele's comment above, Directus itself shouldn't inject the default values in the item value that's staged to be saved to the API. We can keep discussing the functionality to provide the default values to extensions through a new `inject` call, or potentially by merging it with `values` in a new discussion 🙂

**Pull request closed without merging**
