### PR TITLE
Cleanup empty file on write errors

### PR DESCRIPTION
**Pull request by rijkvanzanten**
The local write file didn't take errors on the write stream into account, causing potential empty files to be created when the write would fail. This PR adds an error handler for the write stream that cleans up any erroneously created files by deleting the partial file and rejecting the promise.

### CODE REVIEW

**Review by freekrai — APPROVED** [review]
uploaded a couple dozen images and no empty images.

**Review by joselcvarela — CHANGES_REQUESTED** [review]
This seems to not solve the issue for the case when the outer timeout occurs on transformation 🤔
What I believe is happening is while the following function is running (because is taking too long):
https://github.com/directus/directus/blob/212e52b6b0018646db92c21ecedf3dd3d7f931f2/api/src/services/assets.ts#L184
Then the outer timeout guards kicks in and breaks the flow, leaving the file there without any data:
https://github.com/directus/directus/blob/212e52b6b0018646db92c21ecedf3dd3d7f931f2/api/src/services/assets.ts#L157

Probably we will need to pass a `reject` callback to `withTimeout` in order to remove the file.

**Comment by rijkvanzanten** [comment]
@joselcvarela The outer promise rejection should cancel the web request that's awaiting the result of the promise, but it shouldn't cause problems with the stream coming in as far as I'm aware 🤔

**Comment by rijkvanzanten** [comment]
@joselcvarela Those files you referenced have been (drastically) updated since. Could you confirm this issue still exists? 🙂

**Comment by rijkvanzanten** [comment]
I'll close this for now, as I believe the problem might've been fixed by https://github.com/directus/directus/commit/0154878f2746809896738a1cfb73edcaa3dceace

**Pull request closed without merging**
