### PR TITLE
Adding and removing collections from m2a

### LINKED ISSUE #3231: Allow adding/removing collections from M2A relationship config
I took a look into the M2A builder and it is pretty nice. Thank you for the great work. 

Never the less I already found some things which should be improved. 

1. The Builder should have a sorting possibility
2. You cannot add a new collection once you created a m2a field

### PR DESCRIPTION
**Pull request by Nitwel**
closes #3231 

grafik

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Lets clean this up a bit by using the same logic for both missing-collection and collection-is-no-longer-part-of-relation. It should only check if the item is in a collection that is part of the relation, and render the "m2a_item_not_existing" message regardless. 

(Also lets rename that `m2a_item_not_existing` to `m2a_builder.item_invalid`)

**Comment by Nitwel** [comment]
The thing is that right now I'm looking if we can at least render some information when the collection still exists and only render RIP when the whole collection is gone. So should I get rid of that and only show that the item is corrupted?

**Comment by rijkvanzanten** [comment]
> So should I get rid of that and only show that the item is corrupted?

Yes 👍🏻

**Comment by Nitwel** [comment]
It is now way more simple.

**Comment by tylerforesthauser** [comment]
Hey guys! Is it possible to say how close we are to seeing this implemented in a release?

**Comment by rijkvanzanten** [comment]
@tylerforesthauser 

~~**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!~~

Roughly 5 minutes out

**Review by rijkvanzanten — APPROVED** [review]

**Comment by tylerforesthauser** [comment]
> @tylerforesthauser
> 
> Roughly 5 minutes out

Haha well I didn't see that coming! I appreciate this so much!

**Pull request merged**
