### PR TITLE
Fix "Unrestricted file system access to" messages

### PR DESCRIPTION
**Pull request by paescuj**
Prevent Vite from throwing the following messages in dev mode:
```
@directus/app: Unrestricted file system access to "/admin/src/displays/boolean/index.ts"
@directus/app: For security concerns, accessing files outside of serving allow list will be restricted by default in the future version of Vite. Refer to https://vitejs.dev/config/#server-fs-allow for more details.
@directus/app: Unrestricted file system access to "/admin/src/displays/collection/index.ts"
[...]
```

### CODE REVIEW

**Comment by nickrum** [comment]
I'm wondering if this is something that should rather be solved on vite's end, given using `import.meta.globEager()` with `base: '/admin/'` feels like it should just work.

**Comment by paescuj** [comment]
> I'm wondering if this is something that should rather be solved on vite's end, given using `import.meta.globEager()` with `base: '/admin/'` feels like it should just work.

Actually, I was thinking the same 😄🙈

**Comment by paescuj** [comment]
@nickrum I can open an issue in Vite's repository as soon as I've enough time, okay?

**Comment by nickrum** [comment]
@paescuj that would be really nice, thanks!

Yes, sounds like a good idea.

**Review by nickrum — APPROVED** [review]

**Comment by paescuj** [comment]
> @paescuj that would be really nice, thanks!
> 
> Yes, sounds like a good idea.

Thanks! Will do 👍

**Pull request merged**
