### PR TITLE
Remove button in O2M fields works in readonly mode

### LINKED ISSUE #3930: Remove button in O2M fields works in readonly mode
Hi Team,
   if i set a O2M field as readonly the "Creat New" and "Add Existing" buttons disappears but it's still possible to remove items using the "Deselect" button.

I'm using Directus 9.0.0-rc.34, MySql 5.7, Npx

image

### PR DESCRIPTION
**Pull request by YannickMol**
Fixes #3930

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Weird! `v-show` toggles `display: block` and `display: none`, so I'm a little confused why switching that to `v-if` makes it work 🤔

**Comment by YannickMol** [comment]
It's probably because `v-show` is not allowed on the template element - see [Vue Docs](https://vuejs.org/v2/guide/conditional.html#v-show).

**Comment by rijkvanzanten** [comment]
Ha! Touché

**Review by rijkvanzanten — APPROVED** [review]

**Comment by benhaynes** [comment]
Thank you for the contribution, @YannickMol !! We really appreciate the help... ❤️

**Comment by YannickMol** [comment]
Happy to help out, learning by doing, as I have limited experience 😉

**Pull request merged**
