### PR TITLE
Close WYSIWYG fullscreen when opening drawer or dialog

### LINKED ISSUE #12012: WYSIWYG fullscreen overlaps link popup
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a WYSIWYG editor and when I put it into full screen with the button on the toolbar and try to turn a text into a link with the link button, the link popup is not visible. Going out of full screen shows the popup. So fullscreen overlaps the link popup.

### To Reproduce

1. Go to any WYSIWYG editor
2. Press fullscreen button in the toolbar
3. Select any text and try to turn it into a link

### Errors Shown

_No response_

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

-

### PR DESCRIPTION
**Pull request by licitdev**
Closes #12012.

## Before

https://user-images.githubusercontent.com/26413686/157276999-b8ed07cf-0538-45ec-a9ed-aaa50957c7ac.mov

## After

https://user-images.githubusercontent.com/26413686/157277054-064fc5f7-3d9b-42d8-9de5-3ccd280f42a6.mov

### CODE REVIEW

**Comment by benhaynes** [comment]
Nice! Is there any way to avoid that "pop" showing the editor again when the z-index (or whatever it is) changes?

**Review by rijkvanzanten — APPROVED** [review]

**Comment by licitdev** [comment]
@benhaynes It's a challenge to override this behaviour as TinyMCE's fullscreen works by scaling the editor to the max space available via script and adding a CSS class that sets the `z-index` at 1200 with position as `fixed`. The transition is something we could improve on in the future.

A transitions test on the editor... 😂

https://user-images.githubusercontent.com/26413686/157290631-5f22050c-1c89-4895-9efb-b19160b19f62.mov

**Comment by benhaynes** [comment]
Understandable. I think if we override transition timing to `0` that could help too, maybe it'll be so fast no one will see! :)

**Comment by programmarchy** [comment]
@licitdev
New Directus user here, and I recently came across this exact bug. This may not be the best place to hash out a discussion since this commit was already merged, so let me know if it makes sense to put somewhere else.

My use case is writing a simple blog post body in the WYSIWYG. Fullscreen mode is useful because it leaves the action bar pinned to the top of the screen. So when you need to insert images, you don't need to scroll up the page (losing your place) to hit the insert image button.

I think a better user experience would be for the editor to stay fullscreen, and when adding an image, have the drawer open over the editor. It's understandable that TinyMCE is fighting over z-index, but I'm coming at this from a UX point of view, not a technical one.

**Comment by programmarchy** [comment]
FWIW, setting `z-index` to 1201 on the container class in the v-dialog component seems to work.

**Comment by rijkvanzanten** [comment]
>  It's understandable that TinyMCE is fighting over z-index, but I'm coming at this from a UX point of view, not a technical one.

The main issue is that the editor itself can be _in_ a drawer or a dialog, which in turn means that the z-index will always be fighting, no matter what we set the index values to :C

**Comment by programmarchy** [comment]
@rijkvanzanten In that case, perhaps we could use a selector with more specificity to handle that case?

I've attempted a solution in #12045 although I could not find a way to get the UI into a state with a rich text input inside a dialog. If you can show me how to put the UI into a state like that, I might be able to improve it.

**Comment by rijkvanzanten** [comment]
> In that case, perhaps we could use a selector with more specificity to handle that case?

Good question. It's tinymce that controls the (i believe inline-) styles of that full screen mode, so we'll have to do some research in how much we can tweak that 🤔

**Pull request merged**
