### PR TITLE
Fix fetching from related collection in drawer item

### LINKED ISSUE #17108: 403 error when editing m2a item inside drawer
### Describe the Bug

When I click on item in m2a interface, the drawer is opening. In the same time the 403 error popup appears.

In DevTools I see that **app is trying to fetch the junction collection with and id of m2a item** (that is related to another collection).
This API call is performed by:
https://github.com/directus/directus/blob/abde5adacdfa8a377d941923059c97c72ef6e15a/app/src/views/private/components/drawer-item.vue#L319

The 403 error appears every time when junction collection item with an id of item collection is not exists (very often).

### To Reproduce

1. Create collection A with m2a relation.
2. Create an item of A, add at least one "any" item.
3. Open editing page of created A item.
4. Try to edit one of "any" item. The 403 error will appear.

I suggest to use PK type = UUID for all collections, because of auto-incremented ids can be the same in junction and "any" collections.

### Errors Shown

_No response_

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

v17.9.0

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

### PR DESCRIPTION
**Pull request by licitdev**
## Description

The related collection for base endpoint should be reading from the local `collection` variable and not from `props.collection`.

Fixes #17108, closes ENG-469. 

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by azrikahar — APPROVED** [review]
Great catch! This was an oversight on my part in #16700 🤦‍♂️

**Comment by vanling** [comment]
You magnificent beasts <3

**Comment by keithotto** [comment]
Is there any ETA on when this next release will be available? I just upgraded my client to 9.22.4 and they are getting these error dialogs constantly which is rather annoying for them. I'm trying to decide if it's worth downgrading back to a previous working version.

**Comment by dammafra** [comment]
Hi @azrikahar, there's any ETA on the next release?

**Pull request merged**
