### PR TITLE
Add display options for repeater

### LINKED ISSUE #19692: Repeater field could display Text on interface instead Value for select dropdown
### Describe the Improvement

Using the repeater field, when creating a select entry, where we enter Text and Value, when using the template to display the information to the user, we only have the option of entering the field name {{field}}, which works well for other types of data entry.

But I believe that for a better user experience, the Text entered for the select should be displayed, as the Value is generally a technical data.

Select Field Detail
image

Select Field Option Detail
image

Repeater Field Details
image

User interface with Teplate applyed
image

This could be a bug?

### PR DESCRIPTION
**Pull request by Nitwel**
closes #19692

Adds options for specifying a display on the repeater interface.

grafik

### CODE REVIEW

**Review by paescuj — DISMISSED** [review]
Nice work 🚀 

I think we should make the UI a bit clearer, otherwise the user might be overwhelmed:
- Rename "Options" to "Interface Options" for a clear separation between interface and display options
- Maybe add a horizontal rule
- Rename "Display Label" to "Display", just like we use "Interface" above

Screenshot 2023-09-18 at 09-26-25 Directus

**Comment by Nitwel** [comment]
Good points, instead of using a divider, I think using a group to hide the display options might help with the clutteredness.

**Review by jaads — DISMISSED** [review]
under "display options", I assume it should say "select an display" instead of "select an interface"
Screenshot 2023-09-19 at 10 44 12

**Comment by jaads** [comment]
it would be nice to also have the docs updated in this PR, right? 🤔

**Comment by jaads** [comment]
> I think using a group to hide the display options might help with the clutteredness.

would it be possible to group interface and interface options together as well? 🤔

**Comment by jaads** [comment]
is "raw value" missing under "display label"? I would have expect it there since it's also an option when changing the display type after the field got created

**Comment by Nitwel** [comment]
Updated it to use groups for interface options. Interface group is open by default while display group is cloded by default.

grafik

**Comment by Nitwel** [comment]
> is "raw value" missing under "display label"? I would have expect it there since it's also an option when changing the display type after the field got created

It is the default display anyways to just unselecting any display is the same as selecting the raw display.

**Comment by Nitwel** [comment]
> it would be nice to also have the docs updated in this PR, right? 🤔

Oh, didn't knew we had docs on this. Will update them!

**Review by jaads — COMMENTED** [review]
so I have created a repeater (field/column is called`something`) with two fields called `first` and `second`. the interface works fine. I can add data to those two fields. I created one item, this it how it looks in in the database: `[{"first":"one","second":"two"}]`.

I did not specify any display. I would expect the studio to show me the **raw** data like above but is doesn't. instead it shows me the value of the first field, which is `one` here.  
Screenshot 2023-09-20 at 14 19 12

**Review by paescuj — APPROVED** [review]
Awesome work, @Nitwel! Works & looks great! ❤️

**Pull request merged**
