### PR TITLE
Packages/Env: Allow casting when reading config value from a file

### PR DESCRIPTION
**Pull request by joselcvarela**
## Scope
It is possible to pass a file to env by using `<CONFIG>_FILE` and the value should be the location of the file.

Currently this file is sometimes being recognized as `array`, `json` or any other type as the value is always [casted](https://github.com/directus/directus/blob/main/packages/env/src/lib/create-env.ts#L35) and the [type is guessed](https://github.com/directus/directus/blob/main/packages/env/src/utils/guess-type.ts#L3) when there are no more information.

In this PR we:
- allow file to be casted to another type like `array` or `json`
- recognize file as string by default

What's changed:

- File is recognized as string by default
- File can be casted as any other type

## Potential Risks / Drawbacks

- If someone is relying on having their file being recognized as a random unexpected type, they can have issue

## Review Notes / Questions

- N/A

### CODE REVIEW

**Review by paescuj — COMMENTED** [review]
> recognize file as string by default

@joselcvarela Not sure about this point, since it would introduce different behavior for `_FILE` variables vs. "plain" variables, and in particular that [type mapping](https://github.com/directus/directus/blob/dfe6cca40b34926012797d4cc127b1579c1d57d4/packages/env/src/utils/get-type-from-map.ts) would no longer apply to files.

> allow file to be casted to another type like array or json

I understand the need for this, though 👍 Would it be sufficient to just implement this point? Then it would also not be a breaking change.

**Comment by paescuj** [comment]
IMO `_FILES` variables should just behave the same as their non-`_FILES` counterpart, so that we neither have to add nor remove any (auto)casting.

**Comment by br41nslug** [comment]
@paescuj So what exactly are you suggesting? Either they currently already do behave the same right (even tho there is no real defined behavior for something like `TEST_FILE=array:somefile.txt,otherfile.txt`) or Jose's change will make them behave the same in the expected parsed value.

**Comment by paescuj** [comment]
> @paescuj So what exactly are you suggesting? Either they currently already do behave the same right (even tho there is no real defined behavior for something like `TEST_FILE=array:somefile.txt,otherfile.txt`) or Jose's change will make them behave the same in the expected parsed value.

Yeah, applying the following change from this PR

> allow file to be casted to another type like array or json

while dropping this one

> recognize file as string by default

**Comment by br41nslug** [comment]
Ah so you want to keep the type guessing when not explicitly casting the type then?

As my first comment said my preference would definitely go out to relying less on the `guessType` utility and have more reliable/explainable types when dealing with env vars.

The long term goal for environment variables is reduce the reliance on casting and eventually have them all be treated as `string` and only explicitly casted/parsed by the end-user/logic where needed (which is what we've slowly been doing by using more and more `Boolean(env['SOME_VAR'])` in our codebase instead of casting the var at the top level). Perhaps @rijkvanzanten can chime in whether that is still the vision for the future?

**Comment by jaads** [comment]
I changed a few things:
- removed the default cast to string (`string:`)
- added some tests in the current test file
- added a new test file with fewer mocks

Now the only thing new in this PR is that a cast prefix is allowed, for configs which end with `_FILE`

**Review by jaads — APPROVED** [review]

**Pull request merged**
