### PR TITLE
Add support to insensitive case operators

### PR DESCRIPTION
**Pull request by bernatvadell**
Resolves #2981, #11552

For one of my projects I needed to implement the possibility of searching regardless of uppercase and/or lowercase.

The first thing has been to refactor the apply-query method to reduce the number of existing "if". To do this, I have separated each operator in a file independently, and by means of a factory pattern I resolve the operator that is to be applied. 

Finally I have implemented the operator in the app. 

image

It would be pending to implement other case-sensitive operators...

I hope the PR can help you and anything you need me to modify, let me know.

### CODE REVIEW

**Comment by benhaynes** [comment]
Whoa, this is huge!! Thank you so much for contributing this, @bernatvadell! I can't wait to hear what the Engineering team thinks of this. Again, we really appreciate this PR! ❤️

**Comment by joselcvarela** [comment]
Nice job 💪
This can also be a step into solve this https://github.com/directus/directus/issues/5996

**Comment by bernatvadell** [comment]
Hi @joselcvarela 

I have been able to convert the "in" into an "exists", the main challenge has been that when doing the negation "not exists" I have had to invert the adjacent filters. 

in this example we see how "author" has two records "demo" 
image

If we apply a filter to not include authors who do not have an article named "HELLO", now the author does not appear, despite having another article named "TEST". 

image

However, I put an article that does not really have the author, if it appears: 
image

I think that by implementing the "exists" instead of the "in" they should improve query performance. 

I hope you find it useful.

**Comment by bernatvadell** [comment]
> Whoa, this is huge!! Thank you so much for contributing this, @bernatvadell! I can't wait to hear what the Engineering team thinks of this. Again, we really appreciate this PR! ❤️

I'm still waiting for feedback from the team,

It already happened to me with another PR (that of the relationship of elements) that took a long time and when it began to be valued, there were so many conflicts that it had to start from scratch.

Every day that passes, it costs more to keep an active PR,

If you need something else, tell me and I'll try to implement it.

Thanks to the team for the hard work. Keep going! 💪

**Comment by benhaynes** [comment]
Absolutely. We just launched a new website, Cloud tier, and Cloud Dashboard... so we've been really busy for weeks. We should be back on track with PRs by early next week. Apologies for the delays with these reviews.

**Comment by nordcart** [comment]
Wow this is great! Thank you! Is it possible to add this to the next update? 🙏

**Comment by bernatvadell** [comment]
Fixed conflicts

**Comment by krazyjakee** [comment]
Would the exists condition be part of this PR? If so what would it look like in the interface? Currently you have to select a subfield for example `Demos -> name` and put the condition on that. Would you be able to put the condition directly against the collection (Demos)? For example `Demos Exists`.

My use case is that I want to filter all items that have no value for that field (m2o or m2m) and right now that is simply not possible.

**Comment by bernatvadell** [comment]
Hi @benhaynes, @rijkvanzanten , @nickrum , @jaycammarano , do you want me to close this PR? It doesn't look like it will finally be integrated into the main branch...

**Comment by rijkvanzanten** [comment]
> Hi @benhaynes, @rijkvanzanten , @nickrum , @jaycammarano , do you want me to close this PR? It doesn't look like it will finally be integrated into the main branch...

Nope, not at all. It will in fact make it into the main branch once our other higher priority obligations are out of the way 👍🏻 

As you've probably noticed by the huge volume of activity on this repo, it's quite difficult to prioritize new features that aren't part of a sponsored sprint and/or fix open issues, hence the longer times to review/merge 🙂

**Comment by krazyjakee** [comment]
To answer my own question above, this PR would not fix https://github.com/directus/directus/issues/5996 but would be a step towards a solution as @joselcvarela mentioned above.

It would not resolve the following use case: `able to filter all items that have no value for an m2m or m2o field`.

**Comment by azrikahar** [comment]
@krazyjakee #12488 should actually help you to achieve that! With something like `?filter[count(your_m2a_field)][_eq]=0`.

**Comment by krazyjakee** [comment]
> @krazyjakee #12488 should actually help you to achieve that! With something like `?filter[count(your_m2a_field)][_eq]=0`.

Where is that in the docs? Also what is the graphql syntax?

Thanks

**Comment by rijkvanzanten** [comment]
@krazyjakee it's here: https://docs.directus.io/reference/query/#array-functions

The syntax for GraphQL (to be merged in https://github.com/directus/directus/pull/12684) will follow the existing style for date/time functions:

```graphql
query {
  articles {
    tags_func {
      count
    }
  }
}
```

```graphql
query {
  articles(filter: { tags_func: { count: { _eq: 3 }}}) {
    id
    title
  }
}
```

**Comment by krazyjakee** [comment]
@rijkvanzanten @azrikahar thanks! Just a heads up, this functionality absolutely murders the database even with a few hundred records.

**Comment by bernatvadell** [comment]
Merged the last changes & fixed conflicts

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten @azrikahar thanks! Just a heads up, this functionality absolutely murders the database even with a few hundred records.

What functionality? The json array count or the case insensitive search? Murders how? What database vendor?

**Comment by krazyjakee** [comment]
I won't hijack this PR @rijkvanzanten @azrikahar https://github.com/directus/directus/discussions/12853

**Comment by bernatvadell** [comment]
> Absolutely. We just launched a new website, Cloud tier, and Cloud Dashboard... so we've been really busy for weeks. We should be back on track with PRs by early next week. Apologies for the delays with these reviews.

Hi @benhaynes 

Almost three months later, I still don't have a feedback. I just need to know if there is any interest in merging this PR. As I said, keeping a PR active and conflict-free takes work. There is a lot of work going on in the repository every day, and conflicts are a reality.

On the other hand, task #5996 has been closed, which is not yet resolved, and this PR offers a solution.

I know that you have many priorities ahead of you, but I understand that this is an Open Source project, in which you seek the participation of developers, and if you want us to really collaborate with even bigger improvements, you need to give value to the work that is done, He did not speak economically, because in my case, I am making it profitable in other ways, and I simply want to return the favor you are doing me by releasing this source. The only thing we ask for is a little attention to the work we are doing.

I would not like my words to be misunderstood, I greatly appreciate the work you do, and I am aware that your income does not come from gratitude. You have a cloud to maintain and enhance.

As always, thanks for your work.

**Comment by benhaynes** [comment]
My sincere apologies, @bernatvadell — your words are not misunderstood, we've dropped the ball on getting community PRs reviewed and merged. We've been trying to get ahead of this, but demand has been growing faster than our team, and we therefore have very little engineering time available. That means we've been prioritizing stability/issues/tests over new features. This isn't an excuse, more of my attempt at an explanation. Either way, these delays will discourage our community from contributing to Directus... which is the _last_ thing we want (as long as the PRs are quality, coordinated beforehand, and pass 80/20).

That said, this is a great improvement, and it deserves more timely attention. I am not only pinging our team here (@directus/team 🔔 ) but also posting this in our team chat to give it an extra nudge. I can't guarantee a merge (also, Rijk is out this week), but we'll at least get you a review... and if things look good we can get this into Core.

**Review by br41nslug — APPROVED** [review]
The change works great in my local tests. I can imagine this will be very useful to a lot of people.

**Comment by krazyjakee** [comment]
@benhaynes @br41nslug huge personal thanks from me.

**Comment by bernatvadell** [comment]
I have added tests for all operators except:
_intersects_bbox
_nintersects_bbox
_intersects
_nintersects
_empty
_nempty
_nnull
_null

I have found a bug in _nstarts_with that I have detected through the test. It is already corrected.

**Review by jamescammarano — APPROVED** [review]

**Comment by nordcart** [comment]
@bernatvadell I upgraded to 9.11.0. This does not however work for me. The filter below should at least show 60 items.

image

**Comment by bernatvadell** [comment]
> @bernatvadell I upgraded to 9.11.0. This does not however work for me. The filter below should at least show 60 items.
> 
> image

Hi @nordcart ,

In this PR, only the operator "Contains (Insensitive)" has been included in the app.

Below "Doesn't contains" uses the operator "_ncontains". This operator remains case sentitive on those engines that do.

I have yet to launch another PR with the rest of the operators in the APP, in your case, the operator you are looking for is "_nicontains".

Adding new operators is relatively easy, here are the two reference commits:

- Implementation: https://github.com/directus/directus/pull/11737/commits/ba255fdae4baccd5a0f9c71992efd6c46a3ac0e8
- Translation: https://github.com/directus/directus/pull/11737/commits/197f99061cca8d07783879542125625afb732474

**Comment by nordcart** [comment]
@bernatvadell Ok, that explains it! I´m following when the PR is launched. Great work by the way 😃 ! And thank you for your hard work!

**Comment by bernatvadell** [comment]
> @bernatvadell Ok, that explains it! I´m following when the PR is launched. Great work by the way 😃 ! And thank you for your hard work!

PR is in the air! #13431

**Comment by rijkvanzanten** [comment]
Another one: https://github.com/directus/directus/issues/13468

**Pull request merged**
