### PR TITLE
Missing logs with Pino asynchronous logging

### LINKED ISSUE #16284: Missing logs with Pino asynchronous logging
### Describe the Bug

After update to `^9.19` (same with latest `v9.20.3`), `npx directus bootstrap` has no logs:

Screenshot 2022-11-02 at 1 07 04 PM

Logs with `v9.18.1`:

Screenshot 2022-11-02 at 1 09 14 PM

### To Reproduce

Update to `^9.19` and run `npx directus bootstrap`.

### Errors Shown

_No response_

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

Force pino logger in `sync` mode when used for logging.

All logs should be visible again with this fix however for CLI commands it does output the "INFO: Loaded extensions: test" aswell which is good for the `start` command but can be a problem for automated scripts using the `count` command or similar.

Fixes #16284

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by azrikahar — COMMENTED** [review]
Works like a charm 👍 but would we need to use `cliLogger` for all commands? I tested `schema snapshot` and it seems like the `"Snapshot saved to <file-path>"` log doesn't show up without using `cliLogger`. 🤔

**Comment by rijkvanzanten** [comment]
> but would we need to use cliLogger for all commands

All CLI commands need to use the sync logger, yes. The process will quit before the log is rendered otherwise 👍🏻

**Comment by abdonrd** [comment]
Thanks for working with this!

We had a problem with the schema at staging and we were driving ourselves crazy trying to figure out what was going on (because we did not see any log). 😅

**Comment by tinchoz49** [comment]
this is great, thank you! @abdonrd as a workaround for now, setting the env `LOG_STYLE: raw` should print the log

**Comment by azrikahar** [comment]
It seems like it is not exclusively for CLI as we may need the same fix for `validateEnv`. 

Errors such as `"KEY" environment variable is missing` aren't being rendered when we run `npx directus start`. Tested and can confirm `cliLogger` will fix the error log from `validateEnv`.

https://github.com/directus/directus/blob/7899f6a2679ea5f0ffcdb29e1d722be41ca0e5c3/api/src/app.ts#L66

https://github.com/directus/directus/blob/7899f6a2679ea5f0ffcdb29e1d722be41ca0e5c3/api/src/utils/validate-env.ts#L7-L8

Thanks to @viters for bringing this up on Discord 👍

**Comment by azrikahar** [comment]
In relation to the comment above regarding other logs being affected aside from CLI commands, adding some further findings here:

- `pino` was bumped from `6.13.3` → `8.6.1` in #16052
- `pino` defaulted to asynchronous logging in [`8.0.0`](https://github.com/pinojs/pino/releases/tag/v8.0.0) via pinojs/pino#1448
- `logger` is also available in extensions, so usages such as:

    ```js
    try {
        // logic
    } catch(e) {
        logger.error(e);
        process.exit(1);
    }
    ```

    will also not log any error. However technically the `process.exit` here might be more specific to `cli.before`/`cli.after` hook extensions to add custom cli commands rather than other type of extensions.

So I do wonder what would be the implication of reverting back to synchronous logging 🤔 (as in it used to be synchronous as well, but understandably there should be performance gain with asynchronous logging)

**Comment by br41nslug** [comment]
Did some testing and i can't get the `pino-http-print` to properly switch to sync. The `pino-http-print` transport seems to have been updated for pino 7 but not yet for pino 8 and has not seen a release in about a year. I've attempted to drop the dependency for now in favor of using `pino-pretty` directly but unsuccessfully so far.

**Comment by azrikahar** [comment]
Can't seem to be able to make it synchronous either, as if `sync` (or nesting it under `prettyOptions` as `pino-http-print` documented) doesn't get recognized.

However oddly when I tried changing the following code locally:

https://github.com/directus/directus/blob/6e730956afbba37832b49587cc06049d99b68937/api/src/logger.ts#L19-L26

into this (also made sure to install the latest `pino-pretty@9.1.1`):

```js
	pinoOptions.transport = {
		target: 'pino-pretty',
	};
```

The validateEnv error logs does get printed even without configuring `sync`, at least in dev:

**Comment by abdonrd** [comment]
How about reverting the dependency update and publishing a new patch version?
Until a final solution to the problem is found.
Thanks!

**Review by licitdev — APPROVED** [review]
Logs from the dist build surfaces after this PR and nice addition of the `ignore` option. 👍 

One small note, I believe the `redact` in `pinoOptions` could be removed as it's covered under `httpLoggerOptions`.

**Comment by abdonrd** [comment]
When can we expect a release with this? Thank you! 🙏🏻

**Pull request merged**
