### PR TITLE
Add filter support for autocomplete fields.

### PR DESCRIPTION
**Pull request by u12206050**
## Description

Allows using the autocomplete interface to search for values, since the value actually stored might be a bit verbose (ie. an ID)

SupportAutocompleteInFilter

In the code you'll notice I use `autocomplete` in the `if` statement if or not to use the interface, since others could then implement their own autocomplete interfaces (which is what I am also working on)

Fixes #

## Type of Change

- [ ] Bugfix
- [ ] Improvement
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by u12206050** [comment]
@rijkvanzanten Does this need an issue first before merging?
In my case I use the autocomplete to fill values from another Directus instance, but when filtering I would like to filter by the company name for example, although since the company name isn't actually stored I need to first find the id in order to filter items. This just makes that much easier.

**Comment by u12206050** [comment]
@benhaynes I just realised that as soon as this is merged we could start on PR that would allow related items to be selected using the same type of interface, especially since it isn't as straight forward for all users how to filter or search by navigating what could be a very big field tree.

Scenario, Cars collection has M2O to Brand collection. 
On cars you could add a filter `cars.brand.name CONTAINS ford` but another option would be just selecting `cars.brand EQUALS 32` 32 being the `id` of Ford. But knowing that requires first searching in the Brand collection. If we used the autocomplete interface, you could search `ford` select it from the dropdown list, and have it insert `32` into the search field.

Could become the default way for filtering on relationships.

**Comment by benhaynes** [comment]
> Could become the default way for filtering on relationships.

Oooh, that is really exciting. You're right, this would be a far cleaner way to find/interact with relational items... and could also be a helper shortcut included on the other relational interfaces to attach existing items. 👍

**Comment by u12206050** [comment]
@benhaynes Still waiting :)

**Comment by benhaynes** [comment]
@rijkvanzanten — I know we have other priorities at the moment, but is there any insight we can provide into the LoE or timeline to review this? Days, weeks, months?

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
