### PR TITLE
Update rollup-plugin-styles to v4

### LINKED ISSUE #11688: Potential security vulnerability in one of your dependencies: nth-check
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Potential security vulnerability in one of your dependencies: nth-check

From the GitHub UI:

Screenshot 2022-02-17 at 16 01 56

Screenshot 2022-02-17 at 16 17 24

### To Reproduce

No steps.

### Errors Shown

_No response_

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by abdonrd**
Fix #11688

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@abdonrd Looks like there's some type mismatches between the rollup packages 🤔 

from the failed tests:

```
Error: src/cli/commands/build.ts(147,5): error TS2322: Type 'Plugin' is not assignable to type 'false | Plugin | null | undefined'.
```

we might have to upgrade the other rollup packages as well to make sure everything aligns

**Comment by abdonrd** [comment]
Ouch!

Reading [the v4.0.0 changelog](https://github.com/Anidetrix/rollup-plugin-styles/releases/tag/v4.0.0) I expect no breaking changes (as they just mention the minimum node version change).

I will check it!

**Comment by rijkvanzanten** [comment]
✅✅✅

**Review by rijkvanzanten — APPROVED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Oh my bad, that's just because I forgot to add it to the milestone 🤦🏻

**Pull request merged**
