### PR TITLE
Add sidebar shadow for kanban layout

### PR DESCRIPTION
**Pull request by br41nslug**
Follow up to https://github.com/directus/directus/pull/18516 adding a drop shadow to the sidebars.

Light:

firefox_Dv4ruY1PJD

Dark:

firefox_M27gNF8f3S

Fixes https://github.com/directus/directus/discussions/12789
Closes ENG-1010

### CODE REVIEW

**Comment by LasseRosenow** [comment]
IMHO the current version with the different color looks better.

Shadow feels a bit weird in directus. It is used nowhere else I think?

**Comment by rijkvanzanten** [comment]
> IMHO the current version with the different color looks better.
> 
> Shadow feels a bit weird in directus. It is used nowhere else I think?

The header bar currently uses a similar shadow when content scrolls underneath! This PR is aiming to make that consistent between the various surfaces that overlap

**Comment by licitdev** [comment]
In addition, prior to this PR, the `v-menu` seems to "blend" with the kanban board in dark mode.

image

**Comment by azrikahar** [comment]
I believe this also happens to implement #12789, if I'm interpreting it correctly 👍

**Review by jaads — APPROVED** [review]
Confirming that the shadow now appears for kanban and map layout and works for dark and light mode. code is also looking good!

**Review by paescuj — APPROVED** [review]
Works for now, hopefully we can find a better solution at some point

**Pull request merged**
