### PR TITLE
Fix debugging random portno

### PR DESCRIPTION
**Pull request by paulboudewijn**
fixes #9801

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by joselcvarela** [comment]
Since I had a specific entry to attach debugger to port 9229 in `launch.json` I believe this makes things a bit more time consuming since we need to copy/paste the new port.

So, do you have any solution to attach debugger avoiding copy/paste every time?

**Comment by rijkvanzanten** [comment]
@joselcvarela It's a curse and a blessing, when using the fixed port, there's a scenario where the port might already be in use by another process (I ran into that as well) 🤔 

What configuration are you using in VS Code? I remember mine asking me what process to attach too when starting the debugger, rather than defaulting to 9229

**Comment by joselcvarela** [comment]
My usual flow is to start a terminal window split into 3 panes and start `npm run dev -w directus` on one pane, `npm run dev -w @directus/app -- --host=0.0.0.0` on other pane and finally `npm run dev -w @directus/shared`.
With previous configuration I could attach into any process whenever I wanted to. Now I have other more complex options:
- Check the random port and attach to it. Then need to reattach with the new port;
- Attach to process, but I need to choose what process I want to attach on new "attach"
- Launch any npm script via debugger inside VSCode.

Probably it's just the fact I am not used to the other flows, but I my current solution is to change `package.json` for the older change x)

**Comment by rijkvanzanten** [comment]
Are you running those terminal windows from within VS Code?

**Comment by joselcvarela** [comment]
Nope, I am running inside iTerm.

**Comment by rijkvanzanten** [comment]
Makes me think: do we even have to include `--inspect=0` by default? Couldn't we remove that from the command in package.json, in favor of adding it on the fly when you're running npm run dev? `npm run dev -- --inspect` 🤔

**Comment by joselcvarela** [comment]
Makes sense to me. By default, no inspect mode attached. The ones who want debug, just pass it as argument. Most efficient way to resolve bugs 😅

**Comment by rijkvanzanten** [comment]
I think that's the only way we can make it unopinionated enough to work for all use cases

**Comment by rijkvanzanten** [comment]
Update: My idea won't work. The flag needs to come _before_ the file that's being ran by ts-node-dev, so we won't be able to tack it on to the end like that.

This:

```
... --exit-child src/start.ts --inspect=0
                              ^^^^^^^^^^^
```

Needs to go here:

```
... --exit-child --inspect=0 src/start.ts
                 ^^^^^^^^^^^
```

**Comment by joselcvarela** [comment]
Although we can do `NODE_OPTIONS="--inspect=0"`

**Pull request merged**
