### PR TITLE
Add search field in settings > presets

### LINKED ISSUE #2940: Settings > Presets: Missing "Search" query
There is no way to set this from within the Settings page. This can either be at the top of the Layout Preview, or in the Page Sidebar.

### PR DESCRIPTION
**Pull request by Nitwel**
closes #2940 
grafik

### CODE REVIEW

**Comment by benhaynes** [comment]
@rijkvanzanten — do you prefer this as-in, or in the sidebar like sorting and advanced filtering? I think the sidebar might be cleaner...

**Comment by rijkvanzanten** [comment]
Yeah lets move it to the sidebar so it's close to filter/layout options 👍🏻 

Also wondering if there's a way we can make it more obvious that those options exist and are applied to the layout in the top right 🤔

**Comment by benhaynes** [comment]
How about a matching yellow notice in the form that explains that all those sidebar options in yellow are for customizing the preset?

**Comment by Nitwel** [comment]
grafik
With that search icon now on the side, it is fairly obvious that there is more to configure. Before, I even was scared to click on it because what do these 3 scary lines do. 😉 😄

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
