### PR TITLE
Feature/markdown shortcuts

### PR DESCRIPTION
**Pull request by Dominic-Marcelino**
adds #4235 + h6 to the md-editor

NOTE:
At least in Europe `command+alt` is already in use for some of the shortcuts (e.g `command+alt+q` will ask to quit the browser). **BUT** for international support  (#4123)  I've used the `meta+alt` version over the `control+alt` - hoping this will support other countries / keyboards (unfortunately I don't have a Russian keyboard to test it 😆 )

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Where did you pull the inspiration for the keyboard shortcuts from?

I would personally expect headings to be ⌥⌘1, ⌥⌘2, ⌥⌘3 etc, instead of control. That's mostly because I'm super used to what Bear (https://bear.app) does:

CleanShot 2021-02-26 at 15 10 54@2x

> At least in Europe command+alt is already in use for some of the shortcuts (e.g command+alt+q will ask to quit the browser).

This is true, but that doesn't necessarily mean we can't use them within the context of an editable box. Similarly, we have "meta+s" on the page for saving the whole item, even though that technically means "save current page as html" in the browser.

(This is going to be a fun discussion 😄 )

**Comment by rijkvanzanten** [comment]
Ohh I misread part of that. The inline-preview is still coded to `control` instead of meta:

`translateShortcut(['control', 'alt'])`

The actual shortcuts seem way closer to what I mentally expected:

```
		useShortcut('meta+b', () => edit('bold'));
 		useShortcut('meta+i', () => edit('italic'));
 		useShortcut('meta+k', () => edit('link'));
 		useShortcut('meta+alt+d', () => edit('strikethrough'));
 		useShortcut('meta+alt+q', () => edit('blockquote'));
 		useShortcut('meta+alt+c', () => edit('code'));
 		useShortcut('meta+alt+1', () => edit('heading', { level: 1 }));
 		useShortcut('meta+alt+2', () => edit('heading', { level: 2 }));
 		useShortcut('meta+alt+3', () => edit('heading', { level: 3 }));
 		useShortcut('meta+alt+4', () => edit('heading', { level: 4 }));
 		useShortcut('meta+alt+5', () => edit('heading', { level: 5 }));
 		useShortcut('meta+alt+6', () => edit('heading', { level: 6 }));

**Comment by Dominic-Marcelino** [comment]
Should I we use meta for the tooltip, as it’s just an internal alias for command and control?

For the others I got inspired by WordPress, but totally up for it! 

Initially didn’t wanted to override to much shortcuts, but you’re right, in such a specific contexts it shouldn’t matter.

**Comment by rijkvanzanten** [comment]
> Should I we use meta for the tooltip, as it’s just an internal alias for command and control?

Yeah! `meta` will be translated to `⌘` or `Ctrl` based on mac vs other 🙂 

https://github.com/directus/directus/blob/main/app/src/utils/translate-shortcut/translate-shortcut.ts

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
