### PR TITLE
Flow operations return undefined instead of null

### PR DESCRIPTION
**Pull request by licitdev**
## Description

The `null` return value by a flow operation impacts filter event hooks by replacing the original payload.

image

In the above example, a `Log to Console` operator is added to a filter event hook with the `Response Body` is set as `$last`. 

Prior to this PR, the return value of `null` replaces the original payload, leading to the object created with default values only. After this PR, such operations with no return value will simply leave the payload as is.

Reference to the filter emitter reassigning payload when the return value isn't `undefined`. 

https://github.com/directus/directus/blob/8ec47e8da92d9be10247bcd08c319d2d8ce7e2b5/api/src/emitter.ts#L42-L44

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by nickrum** [comment]
I tried to use `null` instead of `undefined` inside the data processed by flows because this data might be stringified to json and also for consistency.
I think we should either encourage people to use a specific operation key instead of `$last` or solve this on the filter level instead of hardcoding it for each flow type.

**Comment by licitdev** [comment]
This issue was discovered by @erondpowell and I agree that it feels odd where an operation which doesn't output any data such as conditions / log to console, changes the payload to `null`.

@nickrum Here's an example of an edge case on the usage of `$last` on a `filter` event.
Please ignore the operation options as they are just placeholders for visualisation.

image

When the condition rule passes, the existing behaviour returns a `null` which leads to the payload being replaced with a `null`. On the other hand, `$last` works perfectly if condition rejects as there's data being returned.

The only way I could think of, is to add another operation in the resolve route, to return the original payload. Eg: via run script or transform payload operation

image

Is this be the recommended way? We should document this if this PR is deemed unnecessary.

Additionally, I believe there should not be an issue with `undefined` as the data is being keyed, therefore it'll remain as undefined when accessed thru `keyedData[key]`.

**Comment by rijkvanzanten** [comment]
I kinda like the idea of certain operations returning `undefined` to indicate that there's no data at all, in which case the flow handler can skip over setting `$last` entirely, as `$last` would be the last operation _with data_, rather than the _last operation_ 🙂

**Comment by erondpowell** [comment]
> I think we should either encourage people to use a specific operation key instead of $last or solve this on the filter level

BTW, I haven't mentioned this yet... but here's a quick tangent on `$last`: Its a handy utility, but the concept confuses newcomers. Alternatively, we could allow people to copy/paste an operation key directly from the operation panel and Logs... Or even dynamically display them as the user types. That said, I do currently find myself reaching for `$last` pretty frequently.

> I kinda like the idea of certain operations returning undefined to indicate that there's no data at all, in which case the flow handler can skip over setting $last entirely, as $last would be the last operation with data, rather than the last operation

I think that could be more confusing. I haven't done an actual survey, but my impression is that users find `$last` hard to use because they can't mentally track and map the ~~Flow Object~~ Data Chain... Making it skip over operations without data will add to this complexity of the required mental map. Now they have to track ***every*** preceding operation on the object ***and*** know whether it returns a value.

**Comment by ConnorSimply** [comment]
@erondpowell 

Adding on to what you have said, that is one of my biggest slowdowns with flows is `What is actually in $last at this point?` and changing it to the last data instead of last operation sounds like a bigger brain conundrum. It would be cool if access the whole flow run data object was a separate object than the $last data entirely.

**Comment by erondpowell** [comment]
> It would be cool if access the whole flow run data object was a separate object than the $last data entirely.

wait, wym? 

P.S. check out Brain slug's idea: https://github.com/directus/directus/discussions/15870#discussioncomment-3823606

**Comment by rijkvanzanten** [comment]
Closing this, as I fully agree with Connor's point:

> Adding on to what you have said, that is one of my biggest slowdowns with flows is What is actually in $last at this point? and changing it to the last data instead of last operation sounds like a bigger brain conundrum.

**Pull request closed without merging**
