### PR TITLE
Send correct payload to auth provider for oauth

### LINKED ISSUE #8378: oAuth - Invalid Credentials
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The last update broke the oAuth login.

On Version: 9.0.0-rc.94 everything works fine. On the latest version it throws an error: ```myappdirectus | 10:40:39 ⚠️  Invalid user credentials. ```

FAQ:
- Yes the user is created
- Yes the user is activated

I can reproduce the problem.

### To Reproduce

Just simply create an own SSO service.
Used docker.

### What version of Directus are you using?

directus/directus:9.0.0-rc.95

### What version of Node.js are you using?

v14.15.4

### What database are you using?

postges

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by aidenfoxx**
Should resolve #8378

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by dijs** [comment]
Has this been released?

**Comment by bamboowonder** [comment]
Is it possible this bug has come back?   I'm on 9.8, cli/npm and get the INVALID_USER error when trying to use google auth

**Comment by aidenfoxx** [comment]
@bamboowonder seems unlikely. It's almost certainly a different issue. Was Google working prior to 9.8, and is your configuration correct? If you're not using dynamic registration in your config, you must ensure you have an existing Directus user with the correct "Provider" and "External Identifier" for your auth provider.

**Comment by bamboowonder** [comment]
This is a fresh install of Directus 9.8.  And setup the google auth after creating the identical user manually in Directus (based on email address).

**Comment by aidenfoxx** [comment]
I would check your config Google side. Make sure your redirect URLs line up, and that your `PUBLIC_URL` is set to a full domain in your Directus config.

**Pull request merged**
