### PR TITLE
support for custom operation extension creation

### PR DESCRIPTION
**Pull request by nodeworks**
## Description

This adds support for creating custom operation extensions.

Fixes #

## Type of Change

- [ ] Bugfix
- [x] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by benhaynes** [comment]
So exciting... thank you!! Not sure if you coordinated with the core team, but always good to confirm the approach first to not duplicate work or head in the wrong direction. Either way, really appreciate you helping us speed up this extensibility! ♥️

**Comment by MoreBlood** [comment]
any updates on this?

**Comment by genu** [comment]
Is this different than #14410 ?

**Comment by rijkvanzanten** [comment]
> Is this different than #14410 ?

Yes. 14410 adds it to the extensions-sdk package, this adds support to directus itself

**Comment by genu** [comment]
hmm, it seems there is an overlap in the `extensions-sdk` effort though. Maybe I'm not following.

**Comment by genu** [comment]
As far as I can tell, all the updates in this PR, are also present in some form in #14410

**Comment by nickrum** [comment]
Support for operation extensions was already implemented as part of the original flows PR. There was a bug though, which prevented the App part of those extensions from being loaded. A fix for this is also included in #14410.

@nodeworks Thanks again for your contribution. I had to do a few refactorings to make this work nicely with command line flags, to clean up the console output, to make Typescript happy and to make this a little bit more maintainable once we add more hybrid extensions. Thus, I'm closing this PR in favor of #14410.

**Pull request closed without merging**
