### PR TITLE
Add min and max options to date picker interface

### PR DESCRIPTION
**Pull request by u12206050**
The idea is to be able to make use of flat-pickr's options for disabling dates before or after the min and max values given.
Here you can specify the name of another field in either the min or max.

Example: start and end date.

Screenshot 2021-12-27 at 21 00 23

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I think we'd want to be able to choose between a field, or a custom date value 🤔 We wouldn't want to require two extra fields just to configure this option. Likewise, we should use a dropdown of all available fields on the current collection rather than a text-input

**Comment by u12206050** [comment]
I actually did first try to make use of the v-field-select, but couldn't figure out how to configure it to use the current collection that is busy being configured??

**Comment by rijkvanzanten** [comment]
The options object of the interface index file can actually be a function, that gets the currently in-works field detail as it's context object, which can then be used to dynamically return different interfaces etc:

https://github.com/directus/directus/blob/5f8ed253d0313a513e4fc3435b034f4388c423f8/app/src/interfaces/input/index.ts#L14-L17

The following is available in the context object:

https://github.com/directus/directus/blob/5f8ed253d0313a513e4fc3435b034f4388c423f8/app/src/modules/settings/routes/data-model/field-detail/store/index.ts#L39-L82

**Comment by u12206050** [comment]
Turns out I couldn't use v-field-select, but found the system-field interface that seems to be the correct one, awesome that it also supports types then we know the correct field is selected.

In regards to specifying a static value, I don't think it should be part of the options though, if needed, I would create a different field with possibly a default value and maybe hidden as well, that can if need be updated when needed either via query or via the admin, if it isn't hidden.

**Comment by rijkvanzanten** [comment]
> In regards to specifying a static value, I don't think it should be part of the options though

Yeah, I think I agree. It's more a validation question than an interface option 👍🏻

**Comment by u12206050** [comment]
Don't think pull request is too complicated, and would be a nice addition for anyone having multiple dates that should be affected in real time by each other. eg. Booking flights, hotels, anything with a from and to.

Screenshot 2022-06-02 at 08 55 01
There are some new translation strings, not sure how to include them?

Screen Recording 2022-06-02 at 08 52 30


Or are we closing it in favour of using validation rules?

**Comment by benhaynes** [comment]
@u12206050 — I love this approach, it feels very clean. Not sure if validation can handle this atm. @rijkvanzanten thoughts?

**Review by br41nslug — COMMENTED** [review]
Very nice addition to the datetime interface. I am however wondering if we should release this without the capability to validate this behavior in the app or api. While this blocks picking of dates and gives a nice warning it does not stop manually entered dates from being saved I think this might be confusing since it's easy to assume this will also validates the value. I'm not saying that this validation should be part of this interface but currently it is not possible at all to create a validation rules like this depending on other fields manually.

I did find a niche little edge case where the date picker will clear the input with an invalid date on close when nothing has been selected it would be nice if it left the original value intact when no real interaction has happened.

**Comment by u12206050** [comment]
Yes I know about that niche, there is a simple setting that I can add to disable that affect.

In regards to validation, we could consider adding a validation rule automatically vs having to manually create it. Although since this rule is based on the value of another field it unfortunately isn't possible either.

Need this so bad:
```
{
  "from": {
     "_gte": "$CURRENT_ITEM.to"
  }
}
```

**Comment by u12206050** [comment]
@benhaynes @rijkvanzanten this has now been a long time coming :) But used it to add 1 more ability.
Now one can use `$NOW` together with any adjustments for also setting min and max. Checkout the gif.

Datetime interface


Together with the new $CURRENT_ITEM logic in a different PR they compliment each other very well as you can see here in this gif:

Datetime interface validation

**Comment by benhaynes** [comment]
Ohhh, yup!! I really like that! This is awesome, @u12206050 !! 🙌

**Comment by u12206050** [comment]
@rijkvanzanten This is the last conflict update I'm doing, can't keep spending so much time updating old PRs :) Would be very nice to have the feature though.

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
