### PR TITLE
M2O filtered dropdown

### PR DESCRIPTION
**Pull request by asteinarson**
I implemented an (optionally) filtered dropdown interface for many-to-one relationships.  I think it's quite useful, for more quickly and precisely editing values referring to other tables. 

Since I don't know how you do with pull requests (interfaces, displays,...) atm. I did not go through effort of adding items in translation files and so on. Maybe there is a better way to build the filter - but this achieves the basics. 

As feedback, I found it a bit difficult to get a nice layout, on the interface customization (I wanted two parts: _Display fields_, _Filter_).  Particularly getting some vertical space, after the divider was hard.

I developed against RC 0.44. When pulling/merging w RC 0.46 - I hit a new Api / Db error - it looks unrelated to my new interface. (I report on it separately).

### CODE REVIEW

**Comment by koziserek** [comment]
That would be extremely useful for my use-case.

**Comment by miguelurtado** [comment]
👍👍

**Comment by jrvidotti** [comment]
+1

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
