### PR TITLE
Do not queue any extension reloads if a reload job is pending

### LINKED ISSUE #20440: Multiple "Reloading extensions" get executed in sequence
### Describe the Bug

While directus server is running, whenever we do a batch `pnpm -r build` of our extensions, we notice in the console that Directus is "Reloading extensions" again and again and again * 22, which is one per extension is seems.

It does this in sequence and the server doesn't work correctly until it is finished.

Looking at the code in `api/src/extensions.ts` I notice in the `reload()` function that it is simply being enqueued onto a job stack.

## Solution

Debounce the reloading of extensions. The `chokidar.watch` being used seems to trigger the reload function multiple times per second as the files in `extensions` folder is being updated. So debounce and only execute a reload once every 1s, once in the start of the second and once in the end (if another reload has been called)

### To Reproduce

Build a lot of custom extensions in parallel whilst auto reload extensions is true.

### Directus Version

10.6

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- We will no longer queue any extension reloads if any reload extension jobs are pending.
   - The pending job once started should register any of the changes made 

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- This solution is preferred over a traditional debounce implementation as it requires no configuration (via ENV) or preferences on the users side. 

---

Addresses #20440

### CODE REVIEW

**Review by paescuj — DISMISSED** [review]
I don't see a big improvement with this solution, there are still multiple reloads happening one after the other. I actually think that debouncing would be more suitable here - actually, this is what I've set up in a draft branch a few months ago 😅 Now comparing it 👍

**Comment by ComfortablyCoding** [comment]
While jobs can happen one after another if a job is pending and a change happens this will prevent a new job from queueing up which reduces the number of jobs as well as any issues with overlapping reloads.

If we allow for debounce we will need to introduce a new ENV var(s) to enable configuration of the debounce. With the current implementation we get a sort of debounce (no jobs queued while a job is pending) and no need for any configuration.

**Comment by br41nslug** [comment]
> I actually think that debouncing would be more suitable here - actually, this is what I've set up in a draft branch a few months ago

Purely in theory i do not directly think a timeout based debounce approach would be better 🤔 but would love to get a glance at that draft to compare 😄

**Review by br41nslug — APPROVED** [review]
I think this is fine approach to solve the issue's edgecase of multiple simultaneous reloads when doing a lot of FS changes.

@paescuj did you have that link for the alternative approach suggestion? Holding off merging for a little bit longer but cant block this forever

**Review by paescuj — APPROVED** [review]

**Pull request merged**
