### PR TITLE
Add authenticate method to authentication service

### PR DESCRIPTION
**Pull request by smilledge**
Previously (~v96) it was possible to programatically create an access and refresh token for a user without providing a password. This made it possible for extensions to authenticate API requests using custom middleware (for example, using a  JWT provided by another system).

This patch adds an `authenticate()` method that can create tokens for a user without going through the full login flow.

### CODE REVIEW

**Comment by azrikahar** [comment]
@aidenfoxx would you mind to take a gander here? 😁

**Comment by aidenfoxx** [comment]
So the ability to log in without a password was a workaround to allow OAuth authentication within the limitations of the old auth flow.

If we want to allow generating tokens programmatically I would rather have a function dedicated to that, rather than breaking up the functions into 2 parts. Either that, or add a `skipVerification` parameter that skips the `provider.login` call.

**Comment by rijkvanzanten** [comment]
> If we want to allow generating tokens programmatically I would rather have a function dedicated to that, rather than breaking up the login functions into 2 parts

I would agree with that. It should be doable enough to move this bit to a separate "generateTokens" function:

https://github.com/directus/directus/blob/28b2dedd90ff25bed7dccd9aafe4f60527313265/api/src/services/authentication.ts#L200-L223

that's then being used in these alternative functionalities

**Comment by smilledge** [comment]
Agree with the feedback and after thinking about this some more I don't believe this is a good solution. 

It would be good to have the ability to easily implement custom authentication for requests, so I'll look into some other solutions and submit a new pull request. 

I'm thinking either;
1. Only authenticate a request if accountability hasn't already been set (eg, by extension middleware)
2. Add hooks to allow setting and/or overriding the request accountability in the authentication middleware
3. Webhook authentication ([similar to the way Hasura does it](https://hasura.io/docs/latest/graphql/core/auth/authentication/webhook.html))

**Pull request closed without merging**
