### PR TITLE
Check for valid filters.

### LINKED ISSUE #16189: [BUG] Leading underscore in primary key causes misbehavior on m2o and new row creation
### Describe the Bug

An error occurs whenever creating items or using a key for in a relationship where the primary key of the collection starts with an underscore 
e.g. '_id'

Screen Shot 2022-10-26 at 1 52 20 PM

### To Reproduce

Using a new install of Directus on a PostgreSQL db

Create two collections. 

In the first collection add the default primary key. No other fields are required.
In the second collection name the primary key `_id` and create an additional field (any field type is okay) with input data entry, so you can view some values in this collection.

Setup a m2o relationship from the first collection to the second collection and set both display and interface to show some data from the second collection (i.e. show the additional data field)

Add a row to collection 2 with some data in the data field. You will get an error, but the data will have saved to the DB

Add a row to collection 1 and link to the row in collection 2. You will receive an error whenever you try and view the data as a lookup against collection 1.

Youtube Video [attached](https://youtu.be/hENEdn9Z-Q4) with 3 collections to show the incorrect function (leading underscore in primary key name) and the correct function (shown while using an underscore in the middle of the primary key name)

### Errors Shown

Error on the UI
```{
  "errors": [
    {
      "message": "\"integer\" field type does not contain the \"_id\" filter operator",
      "extensions": {
        "code": "INVALID_QUERY"
      }
    }
  ]
}
```

No errors on the web console. 
400 response from the server, but no errors from the server either.

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 13

### What browser are you using?

Chome

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

When validating filters we were only checking for the existence of an underscore `_` as first character. I've added an extra check to look for valid filters instead.

Fixes #16189 
Fixes ENG-151

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [X] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by connorwinston — COMMENTED** [review]
Should `_some` and `_none` be included in the list of filter operators?

**Comment by br41nslug** [comment]
> Should _some and _none be included in the list of filter operators?
They definitely should, nice catch!

**Review by azrikahar — COMMENTED** [review]
API changes LGTM!

This issue made me curious about the App, then I realized the same "anything that starts with `_` is a filter operator" assumption is made there, which can break things particularly in the search/filter:

(the key for `Name` field here is `_name`)

https://user-images.githubusercontent.com/42867097/198555846-3752be52-be21-49a2-b5bd-6bfe9d254504.mp4

I tried to update these places similar to what you've updated in the API and it seems to work afterwards, but feel free to validate whether these are sufficient/correct 👍

https://github.com/directus/directus/blob/27383226b99ba4602b1ef9e1168a1f8908356a36/app/src/views/private/components/search-input.vue#L130-L132

https://github.com/directus/directus/blob/27383226b99ba4602b1ef9e1168a1f8908356a36/app/src/interfaces/_system/system-filter/nodes.vue#L165

https://github.com/directus/directus/blob/27383226b99ba4602b1ef9e1168a1f8908356a36/app/src/interfaces/_system/system-filter/utils.ts#L11

**Comment by licitdev** [comment]
@br41nslug Possible if we hold on this PR until https://github.com/directus/directus/pull/14798 is merged?

**Comment by br41nslug** [comment]
Keeping this draft until the breakage around `$FOLLOW()` can be explained and fixed.

**Comment by rijkvanzanten** [comment]
Closing this for now to revisit later 👍🏻

**Pull request closed without merging**
