### PR TITLE
Fix NPM Quickstart Guide

### LINKED ISSUE #21227: Wrong create project documentation
### Page

https://docs.directus.io/getting-started/quickstart.html

### Describe the Inaccuracy

I tried following create project from this doc by running `npm init directus-project@latest`

image

When I tried I got error:

image

I think the documentation is wrong. Or perhaps maybe this one is right answer `npm init directus-project@latest .` ?

My setup info:

```
node v20.11.0
npm 10.4.0
create-directus-project 10.0.1
```

### PR DESCRIPTION
**Pull request by estheragbaje**
This documentation updates the previous and gives the exact command users should run in order to start Directus locally via NPM.

Closes #21227

### CODE REVIEW

**Comment by paescuj** [comment]
A bit of a scope expansion, but I'd like to divide the three quickstart manuals into multiple steps and align things between the manuals. IMO, it's a bit too tightly packed right now and even more with this PR.
My suggestion (code attached below):





<pre>
::: tabs

== Directus Cloud

1. Create / Login to your [Directus Cloud Account](https://directus.cloud)

   The very first time you log in to your Cloud Account, you will be prompted to create a Team. Each Directus Cloud
   Project exists within the scope of one Team. They allow you to organize Team Members, Projects and Project Billing as
   desired.

2. Create a new project

   Once started, it should take around 90 seconds for the Cloud Project to created. During this time, a link will be
   sent to the email associated with your Cloud Account. The email will contain your Project URL as well as an email and
   password to login. If you used GitHub to create your account, this will be your GitHub email.

3. Access your new project

   Using the URL in your email inbox or on your Directus Cloud Dashboard.

<sub>Learn more about Directus Cloud Projects in our [User Guide](/user-guide/cloud/projects).</sub>

== Docker Installation

1. Initialize and start a new Directus project

   You will need [Docker](https://docs.docker.com/get-docker/) installed and running on your machine.

   Open up your terminal and run the following command:

   ```shell
   docker run \
   -p 8055:8055 \
   -e KEY=replace-with-random-value \
   -e SECRET=replace-with-random-value \
   directus/directus
   ```

2. Access your new project

   The initial admin email address and password will be shown in the terminal. Directus should now be available at
   http://localhost:8055 or http://127.0.0.1:8055.

<sub>Learn more about self-hosting Directus in our [Self-Hosted Quickstart](/self-hosted/quickstart).</sub>

== NPM Installation

1. Initialize a new Directus project using the CLI

   Replace `<project-name>` with the name you want to use for the project directory.

   ```shell
   npm init directus-project@latest <project-name>
   ```

   Follow the prompts to configure your database and to create your first admin user.

2. Start the new project

   Run the following commands to start the new project locally:

   ```shell
   cd <project-name>
   npx directus start
   ```

<sub>Learn more about self-hosting Directus in our [Self-Hosted CLI Guide](/self-hosted/cli.html).</sub>

::: danger Docker is Recommended

While this method works and is maintained, it is not recommended. Docker removes environment-specific quirks that can
lead to Directus not running properly in some contexts.

Running Directus without Docker may result in errors as a result of environment-specific characteristics. In such a
case, make sure you have the required system dependencies for `isolated-vm`, `sharp`, and `argon2` installed.

:::
</pre>

**Comment by estheragbaje** [comment]
@paescuj thanks for this suggestion. I like the way it is broken down, should be much easier for users to follow. Same content, better layout I don't have any objection to so I'd implement this :D

**Comment by phazonoverload** [comment]
I agree with your assessment, but this isn’t the PR for it - we are currently fresh multi-part getting starting guide which will allow us to give each of these steps more breathing room

**Comment by estheragbaje** [comment]
I don't see any downsides to implementing this in this PR. We're not including a different content, but making it more understandable to users. @phazonoverload

**Review by paescuj — APPROVED** [review]

**Pull request merged**
