### PR TITLE
changed #save_options event

### PR DESCRIPTION
**Pull request by peremp**
This change allows the users to "Save & stay" as many times as they want.

### CODE REVIEW

**Comment by benhaynes** [comment]
@WellingGuzman – I understand why this is good for "Save and Stay", but is there any reason this switch would cause any issues?

**Comment by WellingGuzman** [comment]
Hey, I thought I commented on here, sorry. I was testing this, but it didn't work, it just trigger the event for saving (main button, save and leave).

Do you test this @peremp?

@benhaynes I know why this should be helpful, though. maybe we should deselect after we "change" the dropdown OR do it as suggested which seems more obvious, but it giving me some issue, I could take a look but I've short time the next these few days.

**Comment by benhaynes** [comment]
Yeah, no rush. I like the method proposed here, or we could explicitly _de-select_ after (which seems like it would still honor "only save if there are changes". Let's decide which of these ways is better and merge/implement.

Any thoughts, @peremp?

**Comment by peremp** [comment]
@benhaynes The de-select option could work too. The other options of the select doesn't keep the view so I think that is not really important which fix is applied.

@WellingGuzman I don't understand your question at all. I tested it, and I could click on "save and stay" as many times as I wanted. The option was not de-selected but the event was triggered correctly.

**Comment by WellingGuzman** [comment]
I have test this many times and it just save and leave. I asked if you test it recently because still not doing what expected.

I think this should be de-select, to me it seems more obvious, right?

**Comment by benhaynes** [comment]
Not sure why there are differences in what you two are seeing – cache issues?

I am open to either solution... but I defer to Welling for which way we move forward with.

**Comment by peremp** [comment]
It's working for me. Anyway I reverted the event to "change" and de-selected the option.

**Comment by WellingGuzman** [comment]
I have install it clean so many times, maybe browser acting differently? which browser are you on @peremp?

I don't want to give up on this just want to make sure why is not working in my end.

**Comment by peremp** [comment]
I'm on Chrome.
Tested it on Firefox too.

**Pull request merged**
