### PR TITLE
Add sharable eslint, stylelint & prettier packages

### PR DESCRIPTION
**Pull request by azrikahar**
Addresses #8511

_Note: Heavily needs review 😅_

### Pending

   - [x] I assume we'll need to modify the current monorepo's eslint & stylelint to use these packages?
   - [ ] Not sure whether the current peerDependencies are correct.
   - [x] ~Currently I left out Prettier from both ESLint & Stylelint. Is that correct? or do we need to turn Prettier into a sharable package as well?~ Added Prettier package, and included prettier related configs to ESLint & Stylelint packages
   
### Dropped
 
   - [ ] For ESLint, do we need to split it up, such as `@directus/eslint-config/base`, `@directus/eslint-config/typescript` and `@directus/eslint-config/vue`? Reference: https://github.com/antfu/eslint-config/tree/master/packages. Might be useful as some users might only want base/typescript for hooks/endpoints, while others need the vue variant for interface/modules etc, but yea not really sure here.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
>  I assume we'll need to modify the current monorepo's eslint & stylelint to use these packages?

Yes!

>  Not sure whether the current peerDependencies are correct.

Not sure either! We should find another shared eslint config like this, and see how it's "normally" handled 👍🏻 

> Currently I left out Prettier from both ESLint & Stylelint. Is that correct? or do we need to turn Prettier into a sharable package as well?

Good question.. I suppose the use case is to be able to apply Directus' style rules on your own projects, so I would assume that includes prettier config as well. Thoughts @dimitrov-adrian?

>  For ESLint, do we need to split it up, such as @directus/eslint-config/base, @directus/eslint-config/typescript and @directus/eslint-config/vue? Reference: https://github.com/antfu/eslint-config/tree/master/packages. Might be useful as some users might only want base/typescript for hooks/endpoints, while others need the vue variant for interface/modules etc, but yea not really sure here.

I don't think that's required. That's where the "overrides" section of the rules comes in. That controls what specific rules/packages are used for what file types 👍🏻

**Comment by dimitrov-adrian** [comment]
> Not sure either! We should find another shared eslint config like this, and see how it's "normally" handled 👍🏻

> With the shared package we went with using a single package instead of splitting it up into multiple smaller ones. Given those config packages only include single files, maybe we should do this here as well 🤔

It seems that in most, others bundle it as separate packages. About the dependencies, what I'v saw is that base of the package goes as a `peerDependencies` and what the config require/include is going to `dependencies`, so what @azrikahar did is may be the correct

Ref:

- https://github.com/WordPress/gutenberg/tree/trunk/packages (prettier-config, eslint-plugin, stylelint-config)
- https://github.com/Shopify/web-configs/tree/main/packages (prettier-config, eslint-pllugin, stylelint-plugin)
- https://github.com/github/eslint-plugin-github https://github.com/github/prettier-config
- https://github.com/stackbit/prettier-config https://github.com/stackbit/eslint-config https://github.com/stackbit/stylelint-config
- https://github.com/zeplin/eslint-config
- https://github.com/sveltejs/eslint-config

I had played and test in my example extension and how I use them is https://github.com/dimitrov-adrian/directus-extension-linkmeta/blob/directus-sharable-config-test/package.json (npm link seems doesn't works fine in such cases so I needed to install manually from a tgz)

**Comment by nickrum** [comment]
> Just to be clear, this means there won't be any dependencies/devDependencies, just peerDependencies? This means the installation step should also include all of them right?

Yes, exactly! Npm 7+ installs peer dependencies by default.

> what I'v saw is that base of the package goes as a `peerDependencies` and what the config require/include is going to `dependencies`

Well, technically the config doesn't require anything. It just specifies additional configs and plugins as strings. But it doesn't really make too much of a difference. It should work either way.

> Oh do you mean all 3 eslint, stylelint and prettier inside a package? Can you share a high level directory structure and the potential installation step? Would it be something like `npm install --save-dev eslint @directus/shared-config`?

Yes, something like that. We could just put all configs into a single package and then use the package.json `exports` field to be able to import them using `@directus/shared-config/eslint` etc.

I'm not a huge fan of having a lot of very tiny packages, but that's just personal preference. I don't mind either way 👍

**Comment by dimitrov-adrian** [comment]
I had some time to play with this using @azrikahar's code and regarding @rijkvanzanten last comment about single package I ended with https://github.com/dimitrov-adrian/directus-codestyle which I already use in my extensions, and it seems to play nice.

I did an branch on directus to test if behave normally with the monorepo's code and it seems to works fine there as well.

https://github.com/dimitrov-adrian/directus/tree/sharable-codestyle-config

**Comment by azrikahar** [comment]
@dimitrov-adrian thank you for the continuation, looks good to me! I'll make the change accordingly over here, as well as previous recommended changes/structure discussed above.

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
