### PR TITLE
Add support to sort on a nested value

### LINKED ISSUE #8606: API - deep sort on M2M does not work properly
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hi guys, I can't found solution how to sort deep M2M items. 
I have two collections Posts and Categories with posts_categories M2M relation (id, post, category). 
I need to get last Category Posts (sort by -date_created). 

I'm trying with:
`&deep[posts][post][_sort]=-date_created`
and
`&deep[posts][post][_sort]=date_created`
but order of Posts don't change.

With LOG_LEVEL = trace the SQL queries seems to be correct: 
```select `posts`.`id` from `posts` where `posts`.`id` in (?, ?, ?) order by `posts`.`date_created` desc [3, 4, 5]```
and
```select `posts`.`id` from `posts` where `posts`.`id` in (?, ?, ?) order by `posts`.`date_created` asc [3, 4, 5]```
but order of posts in response is the same (id asc) even if i try to order by id and -id.

Initially i'm goin to open Q&A in Discussions but it seems like a bug.

### To Reproduce

https://user-images.githubusercontent.com/17914536/136378996-40dc5320-149b-48d1-aa65-62133c476b94.mp4

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

16.10.0

### What database are you using?

MySQL 8.0.26

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by nodeworks**
This is my first attempt at solving the nested sorting problem. It seems to work with my limited testing but I am SURE there use cases where it breaks. when you make a query you can do something like this:

```
query {
  stores(sort: ["owner.favorite_fruit.main_ingredient.ingredient"]) {
    name
    owner {
      email
      first_name
      last_name
      favorite_fruit {
        main_ingredient {
          ingredient
        }
      }
    }
  }
}
```

Or for descending:

```
query {
  stores(sort: ["-owner.favorite_fruit.main_ingredient.ingredient"]) {
    name
    owner {
      email
      first_name
      last_name
      favorite_fruit {
        main_ingredient {
          ingredient
        }
      }
    }
  }
}
```

Would love some feedback and contributions as I'm sure theres going to be changes!

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
This is really cool! Thanks @nodeworks 🙂

**Comment by nodeworks** [comment]
> This is really cool! Thanks @nodeworks 🙂

No problem! Let me know what else needs to be done so we can get this feature merged in!

**Comment by nodeworks** [comment]
Hey @rijkvanzanten is there anything I can do to speed up the merge process? Are there any changes you want me to make?

**Comment by rijkvanzanten** [comment]
> Hey @rijkvanzanten is there anything I can do to speed up the merge process? Are there any changes you want me to make?

The one thing I would love to look into is to see what we can do to reduce the amount of duplicated code. The same addJoin logic exists elsewhere, and it feels like we might run into some issues if we duplicate that out (where we'd end up fixing something in one, but not the other etc) 🤔 

Would you be able to see if we could pull that addJoin out, and reuse it in all places?

**Comment by nodeworks** [comment]
> 

No problem! Just pushed a commit for that.

**Comment by nodeworks** [comment]
@rijkvanzanten any chance we can target this for the next release? 🤞

**Comment by rijkvanzanten** [comment]
Yes!

**Comment by nodeworks** [comment]
Hey @rijkvanzanten just seeing what could be done to get this out ASAP, I see it didn't make the cut for the release. Is there something else I can do? Thanks!

**Comment by benhaynes** [comment]
Hey @nodeworks — my sincere apologies for this one slipping through the cracks. We had a crazy week getting the huge _relational overhaul_ PR reviewed and merged — which solved upward of 15 different issues. We appreciate you taking the time to submit this PR and will prioritize its review this week. ❤️

**Comment by wc-matteo** [comment]
this doesn't seem to work. I created a test collection (testa) with a o2m relation (testa -> testb).

With this query:
```graphql
{
	testa(sort: ["testb.foo"]) {
		testb {
			foo
		}
	}
}
```

I get:
```json
{
	"errors": [
		{
			"message": "select top (@p0) [testa].[id] from [testa] order by [rjnno].[foo] asc - The multi-part identifier \"rjnno.foo\" could not be bound.",
			"locations": [
				{
					"line": 2,
					"column": 2
				}
			],
			"path": [
				"testa"
			]
		}
	],
	"data": {
		"testa": null
	}
}
```

this is the result without the nested sort:

```json
{
	"data": {
		"testa": [
			{
				"testb": [
					{
						"foo": "aaa"
					},
					{
						"foo": "bbb"
					},
					{
						"foo": "ccc"
					}
				]
			}
		]
	}
}
```

am I missing something?

**Comment by rijkvanzanten** [comment]
> am I missing something?

Yeah! This feature sorts on nested M2Os, not O2Ms. An O2M is an array of things, so you can't really sort on a "value" as there's multiple of those values

**Comment by wc-matteo** [comment]
right! I was confusing this feature with the deep sort. But what about a collection which has a translations collection attached. You want to query the main collection, sorting the results by a field in the translations collection (e.g. updated_on) and filtering by language id so that the translations would only contain a single value (making it, logically speaking, a o2o relation)?

**Comment by rijkvanzanten** [comment]
That's currently not supported, as the translations are technically still an array of values (even if you've filtered it down to one)

**Comment by wc-matteo** [comment]
may I create a feature request for this?

**Pull request merged**
