### PR TITLE
Fix click event for unconfigured tables

### LINKED ISSUE #9052: Links to unconfigured table in data model is broken
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

In the data model setting page, clicking on an already configured table works (browser navigate to `settings/data-model/<collection>`), but nothing happens when clicking on a table that is not yet configured.

It is however possible to go to `settings/data-model/<collection>` by manually entering it in the url bar.

### To Reproduce

* Create a table in your database from outside Directus
* Go to `settings/data-model/`
* Click on the unconfigured table

### Errors Shown

```
Uncaught TypeError: _ctx.openCollection is not a function
    onClick collections.vue:73
    callWithErrorHandling runtime-core.esm-bundler.js:6685
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:6694
    invoker runtime-dom.esm-bundler.js:347
```

### What version of Directus are you using?

rc.99

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

local

### PR DESCRIPTION
**Pull request by azrikahar**
fixes #9052

## Context

Clicking a database-only or unconfigured table causes error of `openCollection is not a function`.

It is because it is used here inside `collections.vue`:

https://github.com/directus/directus/blob/8b7b94ac681e5d5575625313d682ed5790e4deed/app/src/modules/settings/routes/data-model/collections/collections.vue#L73

but it exists inside `collection-item.vue`:

https://github.com/directus/directus/blob/8b7b94ac681e5d5575625313d682ed5790e4deed/app/src/modules/settings/routes/data-model/collections/components/collection-item.vue#L151-L157

## Applied fix

- moved the function up to `collections.vue`, then change `collection-item` to emit openCollection event instead. Hope that's okay.

- fixed minor lint errors.

### CODE REVIEW

**Comment by joselcvarela** [comment]
Hey @azrikahar 
Check my latest commit, basically use a single block, to avoid maintaining two block 👍

**Comment by azrikahar** [comment]
> Hey @azrikahar Check my latest commit, basically uses a single block, to avoid maintaining two block 👍

Originally I did have thoughts on combining them, but I'm not sure whether we should mix click events to router links🤔

The `null` in @click will technically still add click event to all of them right? It was something that I was looking to avoid, but maybe it's not really important.

**Comment by joselcvarela** [comment]
> Originally I did have thoughts on combining them, but I'm not sure whether we should mix click events to router links🤔

Is there any problem to have anchors with onclick events?🤔 IMO, we definitely should try to use focusable elements for actions. This improves accessibility and keyboard navigation.

**Comment by azrikahar** [comment]
Oh ya <div> definitely should be changed. I was just being pedantic on the click event still being attached to collections now as well rather than just attaching to folders only 🙈

**Comment by joselcvarela** [comment]
Oops my bad then.
It makes totally sense split into two different things.
I've just pushed a revert and use button.

It would be cool to define a block(template?) to be reused on both conditions. But I think we will need a specific component for that, right? I think it's not possible to reuse block inside a component.

**Comment by azrikahar** [comment]
Yea I think we can keep it as it is for now. Technically even the "db-only" in collections.vue is copied & modified slightly from collection-item.vue haha, but yea it should be fine at the moment.

**Review by joselcvarela — APPROVED** [review]

**Review by Nitwel — APPROVED** [review]
Looks good to me!

**Comment by paulboudewijn** [comment]
Is the difference in layout (padding) between existing and db-only items intentionally?

image

If not, could you then add the `dense` attribute to the `v-list-item`?

image

**Comment by benhaynes** [comment]
Hey @paulboudewijn — yes, I updated the top items and forgot to update the system collections. It'd be great to get all these using the same padding.

Also, while talking about padding... there is a "dead zone" where clicking these rows doesn't trigger a click. It'd be great to resolve that so it doesn't confuse users (easy to click and nothing happens).

**Comment by azrikahar** [comment]
added "dense" to db-only and fixed the "dead zone".

**Review by joselcvarela — COMMENTED** [review]
image

Can you make that area clickable? 
I think people tend to click on plus icons 😛

Other than that, everything seems to work as expected 👍

**Comment by joselcvarela** [comment]
This might be out of scope and tell me if I should open a PR for it or if you can make it work in this PR, but on clicking on `folder` icon for toggle collapsing seems to not work as expected.

https://user-images.githubusercontent.com/14039341/143057726-e4c6e7f7-a8a5-47fb-9433-4654de891cb0.mov

**Comment by rijkvanzanten** [comment]
Good one @joselcvarela. There seems to be a conflict in the nested click events.

**Pull request merged**
