### PR TITLE
Add search to Roles in Access Control

### LINKED ISSUE #21601: Add the ability to search by 'Name' or 'Description' in 'Access Control'
### Describe the Improvement

Depending on the Directus setup, you could have a large number of user roles defined.  Instead of scrolling through them to look for the one you are looking for, it would be nice to have the ability to search either by 'Name' or 'Description' to find the ones you are looking for.

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

What's changed:

- Added a search bar to the role collection page
- Since all roles are loaded without pagination, an in-app search just works

## Review Notes / Questions

- I reused (read 'copied') the search bar from the data model collection with its styles, should we refactor this into one component?

---

Fixes #21601

### CODE REVIEW

**Review by paescuj — COMMENTED** [review]
> should we refactor this into one component?

Yeah, let's do that 🎉

**Comment by hanneskuettner** [comment]
Refactored to use the existing `SearchInput` component in both the data model collections view and the roles view. This needed a small rework of the `SearchInput` component.

Added `autofocus` and `placeholder` props to retain original functionality in settings views (search get autofocused if more than 25 items). `autofocus` influences the initial active state of the component if set to `true`.

I also improved two visual bugs in the original component:

---
Fixed margin of close icon for `showFilter: false`
|Before|After|
|-|-|
|Screenshot 2024-04-22 at 16 35 24|Screenshot 2024-04-22 at 16 43 25|

---
Fixed jumping of filter icon when opening and closing search input

**Before**

https://github.com/directus/directus/assets/4376726/347f90f9-4623-49e8-a151-0c2961ca660e


**After** 

https://github.com/directus/directus/assets/4376726/9e523883-19b7-4be8-9e2c-c1f0c2686b7e

---

The overall look in the collections listing in the data model section changed slightly as the search is contracted by default.

**Before**
Screenshot 2024-04-22 at 16 58 46

**After**
Screenshot 2024-04-22 at 16 33 15
Screenshot 2024-04-22 at 16 33 20

**Comment by hanneskuettner** [comment]
After a small discussion we decided to drop the auto activation in case of a non-null initial value. This was intended for its use in the collection interface, since it does not properly update on route changes it was broken after the first collection and inconsistent overall. 
We tested it with resetting on route change, this led to janky focus behavior / unwanted, unfinished animations when switching between different collections.

Since we were working on the search input anyways I added two improvements:
- Set `type="search" spellcheck="false" autocapitalize="off" autocorrect="off" autocomplete="off"` thats the way Google and Algolia roll, so let's also be cool 😎 
- Disable and unfocus the search if the user hits the Escape key

**Review by paescuj — APPROVED** [review]
Nice addition, harmonization and clean-up 😃 

Made sure the jumping effect is completely gone now:

https://github.com/directus/directus/assets/5363448/481687ed-3f33-47fd-9b90-44ab574397f8

https://github.com/directus/directus/assets/5363448/f6a522ca-8886-4925-820c-55862b78e0ed

**Pull request merged**
