### PR TITLE
serve rollup output chunks

### LINKED ISSUE #18083: Peer/optional dependencies of extensions discarded
### Describe the Bug

When designing an app extension with external dependencies (peer or optional), the extension manager bundles a single file without resolving node dependencies and discarding other rollup chunks.

### To Reproduce

Create a directus extension `directus-extension-example` with optional dependency on `example-plugin`, building makes `example-plugin` external.

Create a directus instance and add  `directus-extension-example`.

If enabled, `import("example-plugin")` tries to load the chunk located at `"/extensions/sources/index-xx.js"` and fails.

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by gbicou**
when generating extensions bundle with optional or peer dependencies, chunks of javascript sources are routed by the extensions controller

fix #18083

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Do you mind providing a little explanation of what this does / how it works / how it improves on #18083? 🙂 I'm a little confused by what I'm looking at here

**Comment by bicouy0** [comment]
when the extension manager calls rollup to bundle the javascript source, it stores all the chunks generated (dynamic entries, ...) and serves them under the `/extensions/sources/[chunk].js`

in a setup where `directus` depends on `directus-extension-example` which itself depends **dynamically** or **externally** on `example-plugin` (with a `await import('example-extension')` for example) : 

- `directus` is served from `/admin/assets/*`
- `directus-extension-example` is served from `/extensions/sources/index.js`
- `example-plugin` is served from `/extensions/sources/[chunk].js`

---

For example, my directus extension depends on optional package : 

```json
{
  "optionalDependencies": {
    "@tiptap/extension-underline": "^2.0.2"
  },
}
```

When building this extension, the generated app.js contains : 

```js
if (flag) { await import("@tiptap/extension-underline") }
```

And then in a project with this extension and if the `@tiptap/extension-underline` is added, the generated `/extensions/sources/index.js` contains : 

```js
if (flag) { await import('./index-84c2d5b3.js') }
```

Where `index-84c2d5b3.js` is the chunk generated by rollup.

This solves the loading of peer or optional dependencies of the extension itself.

**Review by rijkvanzanten — APPROVED** [review]
Code LGTM :)

**Review by paescuj — APPROVED** [review]
Nice 👍

**Comment by bicouy0** [comment]
thanks !

**Comment by paescuj** [comment]
> [...] because this way when building an App extension you can't be sure that the extension will even run in the browser leading to client side app errors which were previously caught when building the extension

Can you elaborate on this?

> So I was planning to add that to the build step of App extesions without having to rely on node module resolution.

Would still be something we can pursue and then replace the current approach, right?

**Comment by nickrum** [comment]
> Can you elaborate on this?

Sure! If the Extensions SDK doesn't touch a dependency because it is kept as an external import, then this dependency could be anything. It could be provided as cjs-only, it could import node-internals or it could import a native module. This would throw an error at runtime which could have been caught at buildtime.
Also, if the dependency that is kept as an import, is itself depending on a lot of modules (which might themselves also depend on a lot of modules), this might lead to way longer start up times of the API.

> Would still be something we can pursue and then replace the current approach, right?

Yes, absolutely. But if we would replace node resolution for App extensions with our own system, this would break extensions depending on node resolution.

**Pull request merged**
