### PR TITLE
Give config file higher priority than existing env

### LINKED ISSUE #12884: Directus default Dockerfile environment variables cause config file to be partially ignored
### Describe the Bug

The Directus `Dockerfile` has the following code to set some default environment variables:

```
ENV \
  DB_CLIENT="sqlite3" \
  DB_FILENAME="/directus/database/database.sqlite" \
  EXTENSIONS_PATH="/directus/extensions" \
  STORAGE_LOCAL_ROOT="/directus/uploads"
```

Defaults can definitely be nice, but what if I'd like to set a `CONFIG_PATH` and set everything in a custom config file? So in my case I add configuration to my `docker-compose.yaml` file like so:

```yaml
services:
  database:
    ...
  directus:
    ...
    volumes:
      - ./directus-config/:/directus/config/
    environment:
      - CONFIG_PATH=/directus/config/config.yaml
```

Now inside that file I set some variables like so:

```yaml
KEY: directus
SECRET: directus
ADMIN_EMAIL: directus@example.com
ADMIN_PASSWORD: directus
DB_CLIENT: postgres
DB_HOST: database
DB_PORT: 5432
DB_DATABASE: directus
DB_USER: directus
DB_PASSWORD: directus
```

With this configuration, the default `DB_CLIENT` environment file set in the `Dockerfile` will take priority over the `DB_CLIENT` value I set in my config file. That means I have to do the following in my `docker-compose.yaml` to "fight" the default environment variable configuration.

```yaml
services:
  directus:
    ...
    volumes:
      - ./directus-config/:/directus/config/
    environment:
      - CONFIG_PATH=/directus/config/config.yaml
      - DB_CLIENT=postgres
```

Now I'm either defining `DB_CLIENT` in multiple places or omitting it from my custom config file, both of which are confusing and/or prone to error. It also forces me to know the default set inside the `Dockerfile` if I want to use a custom config file and is a rather hard to catch issue.

From the Docker perspective this is intended behavior, but from the Directus perspective I'd say this is a "bug" because defaults should never override explicit values regardless of where they are defined.

### To Reproduce

I think the description above is pretty solid in this case to explain how the issue can be reproduced.

### Errors Shown

No errors. That's part of the reason this is rather hard to catch. I'm also not aware of a way to see the currently loaded configuration that Directus is using, which is something that would have really helped me find this issue.

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

Whatever version the Directus Docker image is using.

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Fixes #12884

### CODE REVIEW

**Comment by badrange** [comment]
In our project we have one .env file (default location) and use environment variable overrides for different environments (local development, master/staging, feature branch environment, production. 

Do I understand this change correctly, that this change will break our setup?

**Comment by rijkvanzanten** [comment]
Yes, that use case isn't supported. I would highly recommend relying on multiple .env files, and switching between them with the `CONFIG_PATH` environment variable, or using a JavaScript based config file and dynamically switching the config based on another flag 👍🏻

**Comment by martijnboland** [comment]
What do you recommend now for storing secrets etc? Obviously, we cannot store these in Github in multiple .env files. 
The override mechanism turned out to be very useful (and intuitive) where env variables set in our hosting platform have higher priority than anything set in a file.

**Comment by avatarbabe** [comment]
This change broke our setup as well. We have some default environment variables in a .env file, but we overwrite these through config in Azure. But that doesn't work anymore. I'm not sure I understand how this works, does it overwrite all the environment variables? Or just the ones defined in the .env file? 

If I have a default endpoint in .env for example, it won't be overwritten anymore. But if I remove that variable from the .env file, and keep it in the Azure config, will it be overwritten/removed?

**Comment by rijkvanzanten** [comment]
If an environment variable exists both in the environment _and_ the `.env` file, the `.env` has precedence over the environment one. You can change what file to use for the configuration through [the `CONFIG_PATH` environment variable](https://docs.directus.io/configuration/config-options/#configuration-files) which in turn also allows you to use json/yaml or even javascript files as the source of configuration. For more advanced setups where you want to dynamically assign certain variables based on other external factors, you might want to rely on the javascript config files 👍🏻

**Comment by FINDarkside** [comment]
I think it's a bad idea to make this kind of breaking change just to fix an issue that is actually in the Dockerfile. People are used to actual env variables taking precedence over `.env` files just like it works with dotenv, Next.js and Docker Compose just to name a few. In my opinion the real fix would be to stop setting env vars in the default Dockerfile and use some other way to set defaults that have the lowest priority if set elsewhere.

**Comment by paulboudewijn** [comment]
This change causes IISNode to crash. **At this moment Directus doesn't work on IIS anymore.**

Apparently IISNode uses named pipes (#5977) instead of a portnumber. The `PORT` environment variable is set at runtime by IISNode with a dynamically generated named-pipe. 
Since this change, the `PORT` environment gets overwritten with the default portnumber in the .env file, causing IISNode to use the non-existing named-pipe '8055'.

**Comment by badrange** [comment]
> Since this change, the `PORT` environment gets overwritten with the default portnumber in the .env file, causing IISNode to use the non-existing named-pipe '8055'.

Solution: Remove the PORT entry from your config file. That's what we had to do with all the settings that vary by deployment environment after this change was made. 

I do belong to the group that thinks it would have been better to let env variables take precedence over the settings in the config file, but it doesn't mean that this change makes it impossible to get directus working in IIS.

**Pull request merged**
