### PR TITLE
fix `@keyv/redis` use simple sets over redis sets

### LINKED ISSUE #20205: Upgrade `@keyv/redis` and configure to not use a set to track keys
### Describe the Improvement

Sometimes user sees content cached when it was already updated.
The project is configured with `CACHE_AUTO_PURGE` to true and `CACHE_TTL` to 30m.
So the user only sees content updated after the TTL.

We already have tried to use the clear cache endpoint without any effect.

This is difficult to reproduce but I have seen this once in a while 
I believe `@keyv/redis` is the culprit. It looks like somehow it loses track of some keys and those are only deleted after the TTL set on Redis.

It looks like we are still using version 2.5.8 of `@keyv/redis` but the latest version is 2.8.0: https://github.com/directus/directus/blob/main/api/package.json#L222C15-L222C15

In this version there's a new feature where keys can be stored as simple keys instead of being tracked on a set (`useRedisSets: false`): https://github.com/jaredwray/keyv/pull/855/files
In the past I have noticed that in other projects, Redis instances were growing with keys not being deleted. So I think this would be nice to have.

Also the deletion of keys in most recent version is asynchronous by using UNLINK instead of DEL command.
https://github.com/jaredwray/keyv/pull/921/files

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:
- Cache keys backed by redis now use simple sets over redis sets.

## Potential Risks / Drawbacks
- Enabling this feature "could lead to performance issues in production when using the clear function, as it will need to iterate over all keys to delete them." We use clear at https://github.com/ComfortablyCoding/directus/blob/main/api/src/cache.ts#L85 so it can potentially effect us. It does state that we should `useRedisSets:false` for high perf as otherwise it can lead to to memory leaks. Not sure which is the lesser of 2 evils.
    - Potentially this issue was already fixed for enabled case in the latest version via https://github.com/jaredwray/keyv/pull/881
- Should we make this option configurable?

## Review Notes / Questions
- I reviewed the changes made between the current and updated verions for `keyv` and `@keyv/redis` did not see any potential issues due to version bumps.
- Info regarding useRedisSets was taken from https://github.com/ryanrobertsname/keyv/tree/main/packages/redis#useredissets

---

Fixes #20205

### CODE REVIEW

**Comment by paescuj** [comment]
Hey @ComfortablyCoding! Thank you for your contribution! Is this PR ready for review in the meantime?

**Comment by ComfortablyCoding** [comment]
Hello @paescuj,

I marked this as draft since I am not able to confirm that my fix has indeed resolved the issue and did not want to waste anyones time on a review. The reported issue is not an easily reproducible (as stated in the report) and although Jose did provide me with some possible reproductions I have not had much luck setting those up.

The changes made were done based on the proposed fix provided in the report. To be honest I am not sure what to do with it at this point.

Happy to mark as non-draft for review or close it depending on what is preferred here given the info mentioned above.

**Comment by joselcvarela** [comment]
I will try to reproduce it today and check if it works.
To be honest I am not sure if this would be reproducible on local machine but I can tell that this may fix the issue where some keys were not in tracking list

**Comment by joselcvarela** [comment]
OK I finally had some time to test this.
In order to make my tests I have (scenario A):

0. Enable `CACHE_ENABLED`, `CACHE_PERMISSIONS=true`, `CACHE_AUTO_PURGE=true` and `CACHE_TTL=30m`
1. Created a collection A with some fields
2. Run postgres through docker compose
3. Run redis through docker compose
  3.1. Added `NET_ADMIN` to `cap_add` and then installed `apk add iproute2`. Finally ran `tc qdisc add dev eth0 root netem delay 500ms`. This makes things really slow 😬
4. Ran Directus v10.6.3 through docker compose.
5. Created a script to insert multiple items in A
6. Created a script to read multiple items from A and at same time was updating current user name (in order to clear cache).

Then I checkout this PR and (scenario B):
8. Did docker build on root
9. Ran new built image 
10. Did same step as 6.

On scenario A (current Directus) I witnessed that keys on `namespace` set were fewer than the cache keys present on Redis database 0.
This is not desirable but it's the current behaviour

On scenario B (this PR) I witnesses that all keys were removed from Redis database 0.
This is also not desirable because Rate Limiting, Messenger, Synchronization, Schema, Permissions keys should not be removed because some item has changed and triggered Cache Auto Purge.

**Comment by rijkvanzanten** [comment]
> On scenario B (this PR) I witnesses that all keys were removed from Redis database 0.
This is also not desirable because Rate Limiting, Messenger, Synchronization, Schema, Permissions keys should not be removed because some item has changed and triggered Cache Auto Purge.

Wait so `useRedisSets: false` doesn't support namespaces then? That'd be a bug in keyv as far as I can tell 🤔

**Comment by joselcvarela** [comment]
> > On scenario B (this PR) I witnesses that all keys were removed from Redis database 0.
> > This is also not desirable because Rate Limiting, Messenger, Synchronization, Schema, Permissions keys should not be removed because some item has changed and triggered Cache Auto Purge.
> 
> Wait so `useRedisSets: false` doesn't support namespaces then? That'd be a bug in keyv as far as I can tell 🤔

It doesn't look like unfortunately 🥲

https://github.com/jaredwray/keyv/blob/main/packages/redis/src/index.ts#L68-L76

https://github.com/jaredwray/keyv/blob/main/packages/redis/src/index.ts#L39-L45

**Comment by ComfortablyCoding** [comment]
Well that's unfortunate.

I'll close this in favour #15178.

**Comment by joselcvarela** [comment]
I think this still can be done 💪

We can make a PR suggesting changing 
```
		if (!this.opts.useRedisSets) {
			return `sets:${key}`;
		}
```
by
```
		if (!this.opts.useRedisSets) {
			return `this._getNamespace():${key}`;
		}

```
On this file https://github.com/jaredwray/keyv/blob/main/packages/redis/src/index.ts#L39-L45

**Comment by ComfortablyCoding** [comment]
I will create a PR for that in the keyv repo in that case.

If/when it gets merged I'll re-attempt this solution.

**Comment by paescuj** [comment]
FYI: https://github.com/jaredwray/keyv/pull/956 has been released last week via [`@keyv/redis@2.8.1`](https://github.com/jaredwray/keyv/releases/tag/2023-12-02) which in turn has been updated on our side via #20714.

**Pull request closed without merging**
