### PR TITLE
Added in JSONEditor

### PR DESCRIPTION
**Pull request by csprance**
Added in JSON Editor let me know if you need any changes made. 

3 different modes: 
Code, Tree, Text

Error Highlighting, code editing features from builtin ACE editor.

### CODE REVIEW

**Comment by mkleywegt** [comment]
This works for me, but the Ace editor complains about the empty state of the field upon initiating a record.

**Comment by WellingGuzman** [comment]
Hey @csprance, before merge can you please change `function (` to `function(` I love it with no spaces in between, I prefer it that way. don't ask 😄

**Comment by WellingGuzman** [comment]
Hey @csprance, the tree mode, seems to be working, but the style seems to be broken.

**Comment by WellingGuzman** [comment]
@csprance we are going to merge the interface and take it from here, thanks for the PR.

**Pull request merged**
