### PR TITLE
Prevent changing active status of the only active admin user

### PR DESCRIPTION
**Pull request by azrikahar**
Addresses #13291

Currently there is a check to prevent deletion or removal of the last admin role/user, but not the status _change_ of the last admin user, so it is technically possible to suspend yourself as the last admin (though arguably this is more of a user error).

Result:

https://user-images.githubusercontent.com/42867097/168524800-0c6db987-5a09-4efb-8333-4d43035a9a9b.mp4

### CODE REVIEW

**Comment by sxsws** [comment]
'last admin user' to 'only active admin user'?

**Comment by azrikahar** [comment]
> 'last admin user' to 'only active admin user'?

There's a `.andWhere({ 'directus_users.status': 'active' })` clause, so it _is_ "only active admin user"! Updated the title.

**Review by rijkvanzanten — APPROVED** [review]

**Comment by joselcvarela** [comment]
Should we also apply this when admin fails password multiple times and account becomes suspended?

**Comment by rijkvanzanten** [comment]
> Should we also apply this when admin fails password multiple times and account becomes suspended?

We can't just disable that for admin users, as that kinda defeats the purpose of the feature to auto-lock on repeated failed logins 🤔

**Comment by joselcvarela** [comment]
> I get your point, but there's some people trying multiple times to login into their projects where they are the only user present, so when Admin user is marked as suspended, the entire project will be unaccessible.
So instead of doing this we may do something like mark Admin as `active` again after a day of `suspended` 🤔

**Comment by rijkvanzanten** [comment]
That's also true. We could make it a "time" lock, just like what you'd find on most smartphones nowadays 🤔

**Comment by benhaynes** [comment]
A time lock makes sense, and/or including additional admin tools (EG in the cloud dashboard) for resetting passwords/status for users.

**Pull request merged**
