### PR TITLE
Register <drawer-collection> in Vue app for relational interface extensions

### PR DESCRIPTION
**Pull request by JoshTheDerf**
## Description

This PR registers the `<drawer-collection>` component in the Vue app to allow extensions to provide custom relational interfaces. `<drawer-item>`, the main other component needed for this purpose, is already registered.

From Discussion #17234
(Should I open an issue for this sort of change?)

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Closing this as the PR contains commits without associated GitHub users

**Comment by JoshTheDerf** [comment]
> Closing this as the PR contains commits without associated GitHub users

Do you need me to try and re-commit with my user associated properly? Seems to have been an issue with my work vs personal setup.

**Comment by JoshTheDerf** [comment]
Yep, makes sense. Likely because I changed my account email awhile back but didn't update `git config` on the system I authored the commit. Will rework it when I get a chance.

**Comment by rijkvanzanten** [comment]
> Yep, makes sense. Likely because I changed my account email awhile back but didn't update `git config` on the system I authored the commit. Will rework it when I get a chance.

Ahh yeah that would explain it indeed 👍🏻

**Comment by JoshTheDerf** [comment]
New PR opened with corrected commit: #18153

**Pull request closed without merging**
