### PR TITLE
updated gulp sass

### PR DESCRIPTION
**Pull request by Anthonyzou**
Makes `npm install` faster.

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Thanks for the contribution @Anthonyzou!

**Comment by WellingGuzman** [comment]
It seems you didn't include the `package-lock.json`

**Comment by Anthonyzou** [comment]
I'll just exclude it. I'll just let you guys decide what lock file you want to include.

**Comment by WellingGuzman** [comment]
Great!

**Pull request merged**
