### PR TITLE
Store schema in shared cache Fix logic regarding fetching one schema at a time

### LINKED ISSUE #22243: Containers getSchema throwing "hit infinite loop"
### Describe the Bug

When our containers are scaling we found many of them crashing, looking at the logs we found this error.

This started happening after updating from 10.9.3 to 10.10.7

Screenshot 2024-04-18 at 13 23 25

### To Reproduce

Scale up to multiple containers running directus 10.10.7

### Directus Version

v10.0.7

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by u12206050**
This adds the schema to the redis cache as well as fixes the lock logic surrounding fetching the schema.

Testing locally with redis server and pm2 to spawn multiple containers shows significant improvement.

Fixes: #22243

### CODE REVIEW

**Comment by u12206050** [comment]
Here is an historic view of our production environment of how the various changes within the PR made an impact:

Screenshot 2024-04-19 at 08 13 30

This shows a 92.86% reduction in the average time to get the schema.

**Comment by said-alex** [comment]
Any update on this fix? Apparently I'm facing this problem, which brought me here.

**Comment by niklasthunviktui** [comment]
Also interested in updates on this since we are experiencing this issue as well.

**Comment by rijkvanzanten** [comment]
We explicitly exclude the schema object from the Redis cache, as the large value size can cause major Redis slowdowns in lower powered infrastructure, which causes other issues. The infinite loop problem should be resolved in https://github.com/directus/directus/pull/23141

**Comment by u12206050** [comment]
> We explicitly exclude the schema object from the Redis cache, as the large value size can cause major Redis slowdowns in lower powered infrastructure, which causes other issues. The infinite loop problem should be resolved in #23141

That is exactly the reason for caching this. Rather than just not caching it at all in shared cache, we can make it optional for those in "lower powered infrastructure".

**Pull request closed without merging**
