### PR TITLE
Truncate User Agent to 255 Chars before going into DB

### LINKED ISSUE #19642: 'Value in collection "directus_activity" is too long' on Instagram and TikTok webviews
### Describe the Bug

On mobile user agent is longer than 255 characters making any POST/PATCH throwing `Value in collection "directus_activity" is too long`.

### No log investigation

**One important thing here is that I found no log referencing this in my server logs.**
We found it in our Hotjar recordings:
image

Based on this thread https://stackoverflow.com/questions/73401376/fix-value-is-too-long-in-directus-field, I investigated a bit and found that directus_activity.user_agent has a max length of 255 so I changed it to a TEXT column.

After a little while, on my production server, when I do a:
```sql
select user_agent, LENGTH(user_agent)  from directus_activity WHERE LENGTH(user_agent) > 255 ORDER BY id DESC;
```
I got those user_agents longer than 255 chars:
```bash
[ RECORD 1 ]------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (Linux; Android 10; MAR-LX1A Build/HUAWEIMAR-L21A; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 musical_ly_2023101040 JsSdk/1.0 NetType/WIFI Channel/huaweiadsglobal_int AppName/musical_ly app_version/31.1.4 ByteLocale/fr ByteFullLocale/fr Region/FR Spark/1.4.0.5-bugfix AppVersion/31.1.4 BytedanceWebview/d8a21c6
length     | 372
-[ RECORD 2 ]------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 BytedanceWebview/d8a21c6 musical_ly_31.0.2 JsSdk/2.0 NetType/WIFI Channel/App Store ByteLocale/fr Region/FR FalconTag/7324F287-6597-469B-B809-BDDAC27C9C9B
length     | 264
-[ RECORD 3 ]------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 BytedanceWebview/d8a21c6 musical_ly_31.0.2 JsSdk/2.0 NetType/WIFI Channel/App Store ByteLocale/fr Region/FR FalconTag/73BAEB5A-0616-474B-B7CC-1E3C29BFFD25
length     | 264
-[ RECORD 4 ]------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 BytedanceWebview/d8a21c6 musical_ly_31.0.2 JsSdk/2.0 NetType/WIFI Channel/App Store ByteLocale/fr Region/FR FalconTag/73BAEB5A-0616-474B-B7CC-1E3C29BFFD25
length     | 264
-[ RECORD 5 ]------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 BytedanceWebview/d8a21c6 musical_ly_31.0.2 JsSdk/2.0 NetType/WIFI Channel/App Store ByteLocale/fr Region/FR FalconTag/812659A8-CD93-418C-A849-EA0E9C09A2A7
length     | 266
-[ RECORD 6 ]------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 BytedanceWebview/d8a21c6 musical_ly_31.1.0 JsSdk/2.0 NetType/WIFI Channel/App Store ByteLocale/fr Region/FR FalconTag/7A8E7D6A-EB2C-4E8D-BCF1-E8237A5EF6DA
length     | 264
-[ RECORD 7 ]------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 BytedanceWebview/d8a21c6 musical_ly_31.0.2 JsSdk/2.0 NetType/WIFI Channel/App Store ByteLocale/fr Region/FR FalconTag/38F3EFEA-69FD-4AA2-87E4-DBEE2DB97EAD
length     | 264
-[ RECORD 8 ]------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 BytedanceWebview/d8a21c6 musical_ly_31.0.2 JsSdk/2.0 NetType/WIFI Channel/App Store ByteLocale/fr Region/FR FalconTag/38F3EFEA-69FD-4AA2-87E4-DBEE2DB97EAD
length     | 264
-[ RECORD 9 ]------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (Linux; Android 10; SM-G960F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 musical_ly_2023101040 JsSdk/1.0 NetType/WIFI Channel/googleplay AppName/musical_ly app_version/31.1.4 ByteLocale/fr ByteFullLocale/fr Region/FR Spark/1.4.0.5-bugfix AppVersion/31.1.4 BytedanceWebview/d8a21c6
length     | 364
-[ RECORD 10 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (Linux; Android 10; SM-G960F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 musical_ly_2023101040 JsSdk/1.0 NetType/WIFI Channel/googleplay AppName/musical_ly app_version/31.1.4 ByteLocale/fr ByteFullLocale/fr Region/FR Spark/1.4.0.5-bugfix AppVersion/31.1.4 BytedanceWebview/d8a21c6
length     | 364
-[ RECORD 11 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (Linux; Android 12; SM-A047F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 Instagram 298.0.0.31.110 Android (31/12; 300dpi; 720x1465; samsung; SM-A047F; a04s; exynos850; fr_FR; 510206667)
length     | 269
-[ RECORD 12 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user_agent | Mozilla/5.0 (Linux; Android 12; SM-G970F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36 musical_ly_2023101010 JsSdk/1.0 NetType/MOBILE Channel/googleplay AppName/musical_ly app_version/31.1.1 ByteLocale/fr ByteFullLocale/fr Region/FR Spark/1.4.0.5-bugfix AppVersion/31.1.1 BytedanceWebview/d8a21c6
length     | 371
```

Which seems to mean that no mutation works with Directus on `TikTok`  and `Instagram` webviews.

We are still using Directus 10.6.1 but, I understand your code, current version is still impacted: https://github.com/directus/directus/blob/main/api/src/database/seeds/05-activity.yaml#L20-L22

Here is the migration I used to fix it:
```js
export async function  up(knex) {
  await knex.schema.table(`directus_activity`, (table) => {
    table.renameColumn(`user_agent`, `user_agent_small`)
  })
  await knex.schema.table(`directus_activity`, (table) => {
    // must be done in a second schema call
    table.text(`user_agent`)
    // table.string(`user_agent_bak`)
  })
  await knex(`directus_activity`).update({
    user_agent: knex.ref(`user_agent_small`),
    // user_agent_bak: knex.ref(`user_agent_small`),
  })
}

export async function down(knex) {
  await knex(`directus_activity`).update({
    user_agent_small: knex.ref(`user_agent`), // May lose data
  })
  .where(`user_agent`, `!=`, ``)
  await knex.schema.table(`directus_activity`, (table) => {
    table.dropColumn(`user_agent`)
    table.renameColumn(`user_agent_small`, `user_agent`)
  })
}
```

### Digging with TikTok
Once we identified it we could try with TikTok, and we now got another error, which I found in the logs: `ERROR: insert into "directus_sessions" ("expires", "ip", "origin", "token", "user", "user_agent") values ($1, $2, $3, $4, $5, $6) - value too long for type character varying(255)`

So I duplicated my migration for `directus_sessions` and now it works.

### Odd migration effect
On local environment (`PostgreSQL 13.11 (Debian 13.11-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`), the result of my migration is:
```
directus=# \d+ directus_activity
                                                              Table "public.directus_activity"
      Column      |           Type           | Collation | Nullable |                    Default                    | Storage  | Stats target | Description 
------------------+--------------------------+-----------+----------+-----------------------------------------------+----------+--------------+-------------
 id               | integer                  |           | not null | nextval('directus_activity_id_seq'::regclass) | plain    |              | 
 action           | character varying(45)    |           | not null |                                               | extended |              | 
 user             | uuid                     |           |          |                                               | plain    |              | 
 timestamp        | timestamp with time zone |           | not null | CURRENT_TIMESTAMP                             | plain    |              | 
 ip               | character varying(50)    |           |          |                                               | extended |              | 
 user_agent_small | character varying(255)   |           |          |                                               | extended |              | 
 collection       | character varying(64)    |           | not null |                                               | extended |              | 
 item             | character varying(255)   |           | not null |                                               | extended |              | 
 comment          | text                     |           |          |                                               | extended |              | 
 origin           | character varying(255)   |           |          |                                               | extended |              | 
 user_agent_bak   | character varying(255)   |           |          |                                               | extended |              | 
 user_agent       | text                     |           |          |                                               | extended |              | 
```

But on my servers (railway.app Postgres services: `PostgreSQL 13.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit`) I get:

```
   Column   |           Type           | Collation | Nullable |                    Default                    | Storage  | Stats target | Description 
------------+--------------------------+-----------+----------+-----------------------------------------------+----------+--------------+-------------
 id         | integer                  |           | not null | nextval('directus_activity_id_seq'::regclass) | plain    |              | 
 action     | character varying(45)    |           | not null |                                               | extended |              | 
 user       | uuid                     |           |          |                                               | plain    |              | 
 timestamp  | timestamp with time zone |           | not null | CURRENT_TIMESTAMP                             | plain    |              | 
 ip         | character varying(50)    |           |          |                                               | extended |              | 
 collection | character varying(64)    |           | not null |                                               | extended |              | 
 item       | character varying(255)   |           | not null |                                               | extended |              | 
 comment    | text                     |           |          |                                               | extended |              | 
 origin     | character varying(255)   |           |          |                                               | extended |              | 
 user_agent | text                     |           |          |                                               | extended |              | 
```

I have no id where my backup column is (also the copied data is lost).

### Conclusion
- `directus_activity.user_agent` and `directus_sessions.user_agent` being VARCHAR 255 make all mutation on Directus impossible from TikTok and Instagram webviews 
- IMHO, the silent aspect of this bug and its impact on those platforms makes it quite critical for conversion funnels
- Please tell me if my fix is the right one (I'm all but a pro with Postgres)
- If you have any clue why my migration has different effect locally and online, please tell me!

### To Reproduce

Visit an app having Directus as backend and trigger a mutation from a TikTok webview

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Custom)

### PR DESCRIPTION
**Pull request by connorwinston**
## Scope

What's changed:

- Truncate the User-Agent everywhere that it is saved in the API.

## Potential Risks / Drawbacks

- User-Agents over 255 characters will not be complete.

## Review Notes / Questions

- None

---

Fixes #19642

### CODE REVIEW

**Comment by br41nslug** [comment]
User agents should never be used for actual logic anyway so i wouldnt call it a "risk" ;) they're just a reference value that can easily changed/mocked/spoofed

**Comment by paescuj** [comment]
> User agents should never be used for actual logic anyway so i wouldnt call it a "risk" ;) they're just a reference value that can easily changed/mocked/spoofed

Correct, it's more of a small drawback that some info might be incomplete. But we cannot guarantee to store the full header anyway, even if we use a bigger field size, as the header itself has no official limit 😅

**Review by paescuj — COMMENTED** [review]
Wouldn't it be sufficient to only truncate it inside the activity service, where the object is actually getting persisted?
https://github.com/directus/directus/blob/70de6168b880470c5aebc9cd7ff07b9816e4ef84/api/src/services/activity.ts#L30

**Comment by connorwinston** [comment]
> Wouldn't it be sufficient to only truncate it inside the activity service, where the object is actually getting persisted?
> 
> https://github.com/directus/directus/blob/70de6168b880470c5aebc9cd7ff07b9816e4ef84/api/src/services/activity.ts#L30

Not really, because insertion of user_agent into the database happens in `ActivityService.CreateOne`, `ItemService.CreateMany`, and then also `knex.insert`. There really isn't a consistent place to intercept the user_agent in one spot.

**Pull request closed without merging**
