### PR TITLE
Add caching of queries executed every api request

### PR DESCRIPTION
**Pull request by u12206050**
During load testing we found two queries that were being executed every request, and even though they are fast, under load bother were taking considerable time (> 8ms).

By caching the results for 10s we reduce load on the database as well as keep it fast.

Additionally I think actually the ip_access could just be fetched with the accountability actually since it seems they are always checked after each other, but can do that in another PR

ip_access
accountability

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I'm wondering if we can move the role IP check to the refresh/login event, and have the logged-in IP tracked inside the JWT token. That way, we can still check the IP on every request (which should also help a lot in preventing MITM style attacks), but only do the database check when the token is refreshed 🤔

**Comment by paescuj** [comment]
> I'm wondering if we can move the role IP check to the refresh/login event, and have the logged-in IP tracked inside the JWT token. That way, we can still check the IP on every request (which should also help a lot in preventing MITM style attacks), but only do the database check when the token is refreshed 🤔

Very interesting idea 👍

**Comment by u12206050** [comment]
> I'm wondering if we can move the role IP check to the refresh/login event, and have the logged-in IP tracked inside the JWT token. That way, we can still check the IP on every request (which should also help a lot in preventing MITM style attacks), but only do the database check when the token is refreshed 🤔

JWTs aren't used during token api requests, which is where most of the load (in our case) is coming from.

**Comment by rijkvanzanten** [comment]
> JWTs aren't used during token api requests

wdym? The access token that's returned from /auth/login and refresh is a JWT. By adding the ip address to that and checking it against the client IP during use ensures that you can only use the access token from the IP address it was created for. That in turn allows us to move the role ip allowlist check to the /login and /refresh operations, which reduces the per-request overhead a bit more.

**Comment by u12206050** [comment]
> > JWTs aren't used during token api requests
> 
> wdym? The access token that's returned from /auth/login and refresh is a JWT. By adding the ip address to that and checking it against the client IP during use ensures that you can only use the access token from the IP address it was created for. That in turn allows us to move the role ip allowlist check to the /login and /refresh operations, which reduces the per-request overhead a bit more.

I meant in out use case we use the token authentication which is the token you can generate and set on a user which can be used without having to call `/auth/login` first.
This token is just an ordinary string.
That being said, I also completely understand where you are coming from, especially if you are only storing the original ip address in the JWT that was used when logging in (be wary of mobile connections though, but guess that is out of scope for limiting by ip in the first place).

**Comment by rijkvanzanten** [comment]
Ahh yeah good point!

**Comment by jpizzle34** [comment]
Also wanted to highlight that the
```sql
select "ip_access" from "directus_roles" where "id" is null limit $1
```
query is also executed for requests that are returning a HTTP 304 response, which in certain cases negates some of the benefits of caching content responses, especially in the case where content doesn't frequently change, nor requires IP access control (i.e. public content or in systems where IP access control is implemented external to Directus).

Beyond caching the mentioned sql responses, can we also add the option to disable the IP access lookup (either through env vars or options in the admin panel)?

**Comment by u12206050** [comment]
Still a potential here to reduce request response times ;)

**Comment by rijkvanzanten** [comment]
Closing this in favor of a bigger cache-on-query project we're planning. Ty!

**Pull request closed without merging**
