### PR TITLE
Simplify presentation/aliases & accordion setup flow

### LINKED ISSUE #9528: Divider/Alias setup flow
The divider (and maybe all aliases or presentation types) should not have a "Default Value" or "Required" toggle. That's extra visual noise and might confuse users.

Screen Shot 2021-11-05 at 10 43 54 AM

### PR DESCRIPTION
**Pull request by azrikahar**
resolves #9528

Criteria of affected interfaces: they have `hideLabel` set as `true`, which includes

- Presentation - Divider
- Presentation - Links
- Presentation - Notice
- Group - Accordion

### Data Model page

image

### Setup flow

https://user-images.githubusercontent.com/42867097/141403165-cb8b4426-c179-4a0c-803a-9776ac15e0a7.mp4

### CODE REVIEW

**Comment by benhaynes** [comment]
Sooo much better than before.... turned out great!

Also, a side note for another issue, we should override the repeaters background color variable to use the inverse color (white). That will give those rows contrast again.

**Comment by azrikahar** [comment]
> Sooo much better than before.... turned out great!
> 
> Also, a side note for another issue, we should override the repeaters background color variable to use the inverse color (white). That will give those rows contrast again.

Just to confirm, you mean the one in Button Links right? 

The items themselves do have a good contrast:

chrome_Vg7MzAYH4O

But seems like the No Item notice is the one "sharing" the same color. Here's the current applied fix to it:

chrome_7WgHy5PN8I

chrome_mHbY95GLB9

**Comment by benhaynes** [comment]
Ahh, makes sense. Thank you!

**Review by rijkvanzanten — APPROVED** [review]

**Comment by stx-chris** [comment]
Directus 9.5.1: I wanted to try this cool feature but as soon as the read-permissions for a role is restricted (removing a single field permission is enough), all notices disappear for that user. The notices seem to be displayed only if the role has full read permissions on the collection. Also, notices don't appear in the field permission list. Intention or bug?

**Comment by azrikahar** [comment]
@stx-chris this PR doesn't add Notice as they are added long before this. Here we're just implementing auto-id-generation, so I believe this is an unrelated thing here. 

With that said, that does sound like a bug so it'll be helpful if you can submit an issue with minimal reproduction steps 👍

**Pull request merged**
