### PR TITLE
Docs: Add FAQs section

### PR DESCRIPTION
**Pull request by joselcvarela**
Don't know if this should be the way to go, but at least we could provide this for now and remove on future.

## Purpose
The intent for this PR is to had a place where we show users how to do things. For example, instead of
`Please provide the Raw Value of the field`
we will be able to
`Please provide the [Raw Value](https://docs.directus.io/getting-started/faqs/#:~:text=There%27s%20two%20approaches%20to%20debug%20Directus) of the field`

(The last link it looks weird because HTML does not support opening details via URL. But if we select the text inside details and choose `Copy Link to Highlight`, it will open the details, at least on Chrome. We can also handle this by ourselves.)

### CODE REVIEW

**Comment by erondpowell** [comment]
Yo @rijkvanzanten so [in reference to this comment](https://discord.com/channels/725371605378924594/915654933590720573/935184522163675138), my idea was to dynamically put FAQs and questions and team response (from github issues or whatever) as an `<iframe>` (or whatever) on the docs page that addresses the issue. This "FAQ" could be displayed at the very bottom or on the right as a widget with each question an accordian. The point would be to make FAQs exist in lock-step with their documentation.

My solution seems somewhat complicated to implement; requires some recoding of the actual docs app and needs to be p well thought out. It might include making a data table to track every question and the source of truth- idk exactly.

@josevarela#0949's solution is straight forward. And already implemented. And seems awesome!

My only thought is will Jose's approach be "like herding cats" with hundreds or thousands FAQs. I don't [grok](https://en.wikipedia.org/wiki/Grok#:~:text=%22to%20understand%20intuitively%20or%20by%20empathy%2C%20to%20establish%20rapport%20with%22%20and%20%22to%20empathize%20or%20communicate%20sympathetically%20(with)%3B%20also%2C%20to%20experience%20enjoyment%22%2C) it entirely and I can't really tell all the ramifications.

**Comment by rijkvanzanten** [comment]
Yeah! It would be great to have a FAQ section per docs page, but that means we need to have some sort of way to associate the discussion on GitHub with the subject in the docs, and make sure those references stay up to date (in case the pages change, or the features get tweaked). For example, an answer on GH that says "This doesn't exist _yet_", shouldn't show up on the page of the docs when the feature exists now 🤔

**Comment by rijkvanzanten** [comment]
For the time being, it's probably easier to have a manual list of need-to-knows, and extend in the future once the rest of the docs are a bit sturdier 👍🏻

**Comment by erondpowell** [comment]
> Yeah, I worry about the iFrame approach... but this is a good idea in general!

What's the worry on the iframe approach?

**Comment by rijkvanzanten** [comment]
> What's the worry on the iframe approach?

I'm sure it's mostly technical reasons. Iframe are a little difficult to inline without feeling totally out of place, also wouldn't allow us to do any filtering on context, etc etc. 

That being said, I'm assuming by "iframe" you simply meant to embed or show the discussions inline, regardless of technology used to do so 🙂

**Review by erondpowell — APPROVED** [review]
Nice! Thanks @joselcvarela

**Comment by erondpowell** [comment]
> > What's the worry on the iframe approach?
> 
> I'm sure it's mostly technical reasons. Iframe are a little difficult to inline without feeling totally out of place, also wouldn't allow us to do any filtering on context, etc etc.
> 
> That being said, I'm assuming by "iframe" you simply meant to embed or show the discussions inline, regardless of technology used to do so 🙂

Yeah, totally. This would be a component, which would have some logic behind it, then whatever made sense. Which might be an iframe, embed, taking the github comment's JSON and injecting it in the component it our own way, or whatever.

**Comment by joselcvarela** [comment]
As @azrikahar pointed out, we could also include https://github.com/directus/directus/blob/main/docs/configuration/faq.md

**Comment by erondpowell** [comment]
> As @azrikahar pointed out, we could also include https://github.com/directus/directus/blob/main/docs/configuration/faq.md

You want to rip that out entirely and add it into your new FAQ?

**Comment by erondpowell** [comment]
@rijkvanzanten I think we should close this, as we plan to link in Github discussions to the relevant docs page/section.

**Comment by rijkvanzanten** [comment]
Agreed, we're not going ahead with this

**Pull request closed without merging**
