### PR TITLE
Docs typo fix

### PR DESCRIPTION
**Pull request by bartoszpijet**
## Scope

What's changed:

- Typo in docs was fixed, there is no such thing as useCollectionStore (should be useCollectionsStore)

## Potential Risks / Drawbacks

- None, just docs typo fix

### CODE REVIEW

**Comment by hanneskuettner** [comment]
Heya! Thank for you this PR! It looks like you made this commit without using an email address (linked you your GitHub account). Would you mind configuring git to use the correct email and amending the commit to include your email, that way you can add your username to CLA and the commit can be correctly attributed back to you.

**Comment by bartoszpijet** [comment]
> Heya! Thank for you this PR! It looks like you made this commit without using an email address (linked you your GitHub account). Would you mind configuring git to use the correct email and amending the commit to include your email, that way you can add your username to CLA and the commit can be correctly attributed back to you.

Hi, must have left git config from company repos. I'll handle that first thing tommorow!

**Comment by bartoszpijet** [comment]
Now it should be fine, let me know if there are any further issues

**Review by hanneskuettner — APPROVED** [review]
Perfect @bartoszpijet! Thank you very much for your first contribution!

**Pull request merged**
