### PR TITLE
lockfile: regenerate to fix inconsistencies

### PR DESCRIPTION
**Pull request by happysalada**
There are some inconsistencies in the package-lock.json at the moment.
For example the "cpu-features" dependency has no entry at all even though it's reference.
This generates some errors in some environments.
Would you mind regenerating the lockfile from scratch ?
That's what I did in this PR.
let me know if you need more informations.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@happysalada How did you regenerate the lock file initially? Your first commit had like 40,000 additions, while a fresh generation on node 16.13 is way smaller 🤔

**Comment by happysalada** [comment]
There are a couple of gotchas when regenerating a lockfile.
You need to have the node_modules folder empty, otherwise npm will just use those as entry and it will not fill in the "integrity" and the "resolved".
You can see that on this PR, I didn't do this correctly, because some "integrity" are actually deleted.
If you are open to it, I can take a fresh copy of master and generate it "properly".

The idea behind having all the "resolved" and "integrity" attribute is that it makes it possible for other package managers to handle npm. This is done with the purpose of adding this package to nixos.

Let me know if you need anything.

**Comment by happysalada** [comment]
alright, I just regenerated it, and you are right, the diff is massive.
How about you regenerate it yourself, removing all the node_modules (from the top directory and sub directories) and removing the package-lock.json (that way there is no trust issue, since the diff is relatively hard to review).

**Comment by rijkvanzanten** [comment]
> You need to have the node_modules folder empty, otherwise npm will just use those as entry and it will not fill in the "integrity" and the "resolved".

I never knew this was the case :| what an interesting quirk.

I just regenerated the lock file "fresh" (by removing the node modules recursively with lerna clean), and the diff is even bigger than when you did it on your end. Oh the mysteries of the package-lock file 🕵🏻

**Comment by happysalada** [comment]
Thanks a lot for this!
(sooooooooo many quirks with npm :-) )

**Comment by rijkvanzanten** [comment]
> Looks like an issue with the CI?
> 
> https://github.com/directus/directus/actions/runs/1917733461

I'm not sure if that problem is related. The CI went through just fine on my commit here. I think it's a fluke

**Pull request merged**
