### PR TITLE
Bugfix: Visual inconsistency for tree-view

### LINKED ISSUE #15676: Visual inconsistency for tree-view
### Describe the Bug

The tree-view interface has some visual quirks as compared to the other relational interfaces, mainly:

- It uses shadows instead of the bordered row style
- Open/close arrows point the wrong way (closed should be 👉🏻, open should be 👇🏻)
- There's no notice when there aren't any items yet

### To Reproduce

Add a tree-view interface with some content,  note the visual inconsistencies:

CleanShot 2022-09-20 at 16 32 03@2x

### Errors Shown

n/a

### What version of Directus are you using?

v9.17.4

### What version of Node.js are you using?

18

### What database are you using?

PG13

### What browser are you using?

Safari

### How are you deploying Directus?

Locally

### PR DESCRIPTION
**Pull request by AlexGaillard**
## Description

Fix visual inconsistency on relational tree view interface where borders and shadows were different to other interfaces and the open/close arrows were facing the wrong direction.

Also added v-notice to show up when tree node has displayItems passed to it.

Node with some subnodes:
Screenshot_8

Node with no subnodes:
Screenshot_7

Fixes #15676, fixes ENG-184

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Lets use a down-chevron instead of an up-chevron for the "closed" state.

@Nitwel @azrikahar do you remember if there was a specific reason why we went with a `ul > li.row` instead of a `v-list > v-list-item` setup here before? I think this interface might've been skipped when we refactored the older ul/li setup to v-list/v-list-item, but I'm not sure 🤔

**Comment by azrikahar** [comment]
> @Nitwel @azrikahar do you remember if there was a specific reason why we went with a `ul > li.row` instead of a `v-list > v-list-item` setup here before? I think this interface might've been skipped when we refactored the older ul/li setup to v-list/v-list-item, but I'm not sure 🤔

I don't have a clear context either, but I believe it has always been ul/li when it was first created in #4602.

I was able to find the refactoring to v-list/v-list-item which was #4093. It could just be because the original issue #3647 prompting this refactoring didn't include treeview, though it's also odd how the PR #4602 adding treeview happened later than the refactoring (which might explain why it wasn't prompted to refactor), but I can see there's an existing treeview interface during said refactoring? 🤔

**Review by azrikahar — COMMENTED** [review]
First of all would like to welcome you as a first-time contributor here! 

I'm wondering do we want to add a "loading" state when expanding items (using the `loading` ref from useRelationMultiple), or maybe just not show the notice since the initial "no items" seems abit odd:

chrome_y6csInEPa6

Or perhaps it would be slightly better to not allow expanding it when there's no children in the first place, but fully understand that can be a separate discussion altogether, so just throwing this out there rather than a required change in this PR.

**Comment by rijkvanzanten** [comment]
> > @Nitwel @azrikahar do you remember if there was a specific reason why we went with a `ul > li.row` instead of a `v-list > v-list-item` setup here before? I think this interface might've been skipped when we refactored the older ul/li setup to v-list/v-list-item, but I'm not sure 🤔
> 
> I don't have a clear context either, but I believe it has always been ul/li when it was first created in #4602.
> 
> I was able to find the refactoring to v-list/v-list-item which was #4093. It could just be because the original issue #3647 prompting this refactoring didn't include treeview, though it's also odd how the PR #4602 adding treeview happened later than the refactoring (which might explain why it wasn't prompted to refactor), but I can see there's an existing treeview interface during said refactoring? 🤔

Lets see if we can clean this up by using v-list to be consistent with the other relational interfaces

**Comment by rijkvanzanten** [comment]
@AlexGaillard Wanna give that a shot? Ideally we replace [these inline `<li>` with styles](https://github.com/directus/directus/pull/15741/files#diff-8ee7c0b17f551923fd30f0466afb04315b5a36fc6cfadc2e3b9304afc46bfd95R23) with `<v-list-item>` etc just like in the other relational interfaces 🙂

**Comment by AlexGaillard** [comment]
Sure thing 👍

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
