### PR TITLE
Update Knex to version 0.95.0

### LINKED ISSUE #2904: SQLite Initialization/Migration Fails
Trying to upgrade a SQLite database fails with the error message "Method implemented in the dialect driver". It seems like `dropForeign()` is not implemented for the SQLite driver.
As the migrations are run when initializing a database this error shows up, even though the initialization works.

### LINKED ISSUE #2948: Sqlite does not support alter column
Changing interface of field trigger error

```
08:15:50 🚨 Sqlite does not support alter column. 
Error: Sqlite does not support alter column.
    at TableCompiler_SQLite3.addColumns (/directus/node_modules/knex/lib/dialects/sqlite3/schema/tablecompiler.js:35:11)
    at TableCompiler_SQLite3.TableCompiler.alterColumns (/directus/node_modules/knex/lib/schema/tablecompiler.js:184:10)
    at TableCompiler_SQLite3.TableCompiler.alter (/directus/node_modules/knex/lib/schema/tablecompiler.js:77:8)
    at TableCompiler_SQLite3.TableCompiler.toSQL (/directus/node_modules/knex/lib/schema/tablecompiler.js:34:20)
    at TableBuilder.toSQL (/directus/node_modules/knex/lib/schema/tablebuilder.js:45:42)
    at SchemaCompiler_SQLite3.alterTable (/directus/node_modules/knex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_SQLite3.toSQL (/directus/node_modules/knex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (/directus/node_modules/knex/lib/schema/builder.js:79:43)
    at /directus/node_modules/knex/lib/runner.js:31:36
    at /directus/node_modules/knex/lib/runner.js:277:24
08:15:50 ✨ request errored PATCH 500 /fields/table1/body 18ms
```

---

### Project details
Directus Version: 9.0.0-beta.13
Environment: production
OS: Linux 4.19.76-linuxkit
Node: 14.13.1

### PR DESCRIPTION
**Pull request by nickrum**
I tried to split this up into multiple commits to make reviewing at least a little bit easier.

Knex now uses two different exports for the constructor function and the type namespace. Also, Knex now uses tedious, the underlying database driver of mssql, directly.
I had to add `@types/node` as a dev dependency to the api to prevent it from importing an outdated version. Additionally, I had to up the typescript version of the schema package to be compatible with the new Knex version.

The mssql change is untested, so I am marking this as draft for now.

Fixes #2948, fixes #2904

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Code changes LGTM!

**Comment by rijkvanzanten** [comment]
@nickrum I'm seeing a bunch of TS errors when building the suite (just a regular `npm run build` from the root, after a `rm -rf node_modules && npm install`)

CleanShot 2021-03-03 at 18 51 30@2x

It seems to be the change in import of the types for Knex, and potentially this upgrade of Typescript:

https://github.com/directus/directus/pull/4374/files?file-filters%5B%5D=.json&file-filters%5B%5D=.ts#diff-ccb4b7623a0b0dfc801a63df0d5be8897e2a7fa73a9b4ada3e99661b079af7cfR45

**Comment by nickrum** [comment]
@rijkvanzanten Strange.. Those "Knex can only be imported by using ..." errors indicate that the api is trying to import the old 0.21.x Knex version.
Have you also tried to do a `lerna clean` to remove the nested `node_modules` folders?

**Comment by nickrum** [comment]
Of course you are 😂 Because you know that npm will handle this for you with all it's package.jsons and package-lock.jsons

**Review by rijkvanzanten — DISMISSED** [review]

**Review by rijkvanzanten — APPROVED** [review]

**Comment by martijnboland** [comment]
Exciting! I'll check mssql ASAP.

**Pull request merged**
