### PR TITLE
Add load tests

### PR DESCRIPTION
**Pull request by Nitwel**

### CODE REVIEW

**Comment by benhaynes** [comment]
Can we get this merged? Can we come up with some number of simple, medium, and complex queries (auth, public, not cached, etc), and then run these at least once to capture some benchmarks in number/chart form that we can use within Sales/Marketing?

**Comment by Nitwel** [comment]
@licitdev in which folder do these load tests belong?

**Comment by licitdev** [comment]
Great question! I'm wondering if the load test should be in a separate repo. 🤔
@rijkvanzanten How should we go about it?

**Comment by paescuj** [comment]
> Great question! I'm wondering if the load test should be in a separate repo. 🤔

IMO it depends a bit on how tightly we want it to be integrated. E.g. do we want to run it as a check on every commit / pull requests? Do we expect that the tests needs to be update / extend frequently (along with the code)?

**Comment by rijkvanzanten** [comment]
> > Great question! I'm wondering if the load test should be in a separate repo. 🤔
> 
> IMO it depends a bit on how tightly we want it to be integrated. E.g. do we want to run it as a check on every commit / pull requests? Do we expect that the tests needs to be update / extend frequently (along with the code)?

Great question! This also ties into the bigger question of "When do we run what tests". Right now, the blackbox tests take quite a while to run, so we don't wanna do that every PR (or even every commit). Maybe it's a good idea to make a scheduled GitHub Action that runs the full test suite (eg full blackbox + perf tests) every day at 00:00 or something?

**Comment by paescuj** [comment]
> Right now, the blackbox tests take quite a while to run, so we don't wanna do that every PR (or even every commit). Maybe it's a good idea to make a scheduled GitHub Action that runs the full test suite (eg full blackbox + perf tests) every day at 00:00 or something?

Exactly, I think a regularly scheduled run would be more meaningful as it could be performed undisturbed through to the end. However, we'd need to be notified somehow in case of problems and be able to find the cause as quickly as possible (maybe multiple blackbox test runs over the day).

**Comment by rijkvanzanten** [comment]
>  to find the cause as quickly as possible (maybe multiple blackbox test runs over the day).

I think this might be less of an emergency though; as long as we're notified before release it should be OK. Keep in mind that these run after we've already reviewed PRs and ran the lightweight e2e tests + unit tests

**Comment by paescuj** [comment]
> as long as we're notified before release it should be OK. Keep in mind that these run after we've already reviewed PRs and ran the lightweight e2e tests + unit tests

Right, very good points! 👍 

So the load tests definitively seem to be a good fit for a scheduled run!
Not sure if it's really worth to create a separate repository for this.
If we keep it in this repository, such a structure would be nice in my eyes 😃:
```
└── tests
    ├── blackbox
    ├── load
    └── maybe-others-tests-later-on
```

**Comment by paescuj** [comment]
Closing this for now to be revisited later.

**Pull request closed without merging**
