### PR TITLE
Sort schema snapshot

### LINKED ISSUE #11240: Schema snapshotting inconsistency
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I've made some changes on server. Snapshotted schema, put it in my local env (that lacks some collections), tried to apply, that failed (as usual, but t is another story). Ok, I've dumped the db from server, imported it in local db. Run schema apply — got bunch of useless updates (this will be next ticket), but it applied. And then I've snapshotted schema again. And file differes.

It is full of such blocks:

Снимок экрана 2022-01-24 в 19 50 30
 
Nothing changed here but order of fields.

Why is this a problem? Because schema file is supposed to be version controlled. And when one adds a collection for example, dumps the schema — and instead of having proper diff with change in collection one gets a huge mess on tens of. thousands changes when nothing can be understood or tracked. It is critical to force strict order in yaml render

### To Reproduce

Snapshot schema in different environments

I suppose that difference is OS-dependent, server runs in docker, locally — MacOS

### Errors Shown

_No response_

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v16.13.1

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

node base docker image, macos

### How are you deploying Directus?

Docker, kubernetes, locally

### PR DESCRIPTION
**Pull request by diegoleme**
Closes #11240 

Force known sort order in schema snapshot keys

### CODE REVIEW

**Comment by azrikahar** [comment]
Understandably this was brought up in #10904, but I'm also not entirely sure why it was closed either.

With that said, is there an example of the before/after of the schema snapshot? Curious on how the Array-first sorting as stated by `smart-deep-sort` would look like 🤔 Also seems like the CI is failing due to the package missing type declarations.

**Comment by diegoleme** [comment]
@azrikahar, I refactored the use of sortDeep, so it becomes clearer what is happening using only lodash and solves the typing problem.

image

**Comment by diegoleme** [comment]
Just so I can understand the flow better. Do I need to do something else, for that will it be in a next release?

**Review by azrikahar — APPROVED** [review]
Just to confirm, the `0` in `sortBy(pairs, 0)` shouldn't be necessary right? https://github.com/directus/directus/pull/12907/commits/487c015c7058e17840565d0dcc73d914e0bc346d#diff-c783b2074f310fd793d1653b823996330e13b500204316918a8676a873c51841R54. Do let me know if it actually has effect that I'm not aware of.

Otherwise LGTM! 👍

**Review by br41nslug — APPROVED** [review]
Works very well in my local tests creating consistent snapshots with well readable diffs for GIT!

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
