### PR TITLE
French i18n

### PR DESCRIPTION
**Pull request by jonhershon**
Translated all UI strings to French. Left alone most MySQL-specific and
programming terms.

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Thank you @jonhershon for your contribution.

**Comment by christophemarois** [comment]
@WellingGuzman The merged french locale does not appear in the users settings locale's dropdown yet. Specifying it manually in the `localesAvailable` array in `app/main.js` did not seem to do anything either  :

```javascript
var defaultOptions = {
  locale: 'en',
  localesAvailable: [{
      code: 'en',
      name: 'English'
    }, {
      code: 'fr',
      name: 'Français'
    }],
  ...
}
```

Any ideas?

**Comment by WellingGuzman** [comment]
Thanks for reporting this, we've moved the locales to the `api` directory so that's why it was missing. we have been changing how and where we put the locales lately.

Commit: https://github.com/directus/directus/commit/79403c39504065c0075f39c06ffd653e315a97e0

Let me know if that works for you too.

**Comment by WellingGuzman** [comment]
Hey @christophemarois, no a problem we have change it on the development branch, and I was trying to hot fixes but forgetting that the path was change it all over the place.

Thanks.

**Comment by benhaynes** [comment]
This is excellent! Getting some great language files in there already!

**Pull request merged**
