### PR TITLE
Split existing docs pages into Developer Docs and User Guide

### PR DESCRIPTION
**Pull request by estheragbaje**
The current docs contain a number of pages which are less relevant to developers, but more useful to end-users. This PR splits user guides into a dedicated area of docs with it's own sidebar.

### CODE REVIEW

**Comment by phazonoverload** [comment]
Looks good - we need to handle redirects. Can you sum up any patterns/explicit redirects and we can build them into our redirects file in this repo https://github.com/directus/directus/blob/main/docs/netlify.toml

**Comment by phazonoverload** [comment]
@estheragbaje I'm pretty sure the redirects are incomplete - every page and subpage needs a redirect rule that applies to it.

**Comment by estheragbaje** [comment]
> Looks good - we need to handle redirects. Can you sum up any patterns/explicit redirects and we can build them into our redirects file in this repo https://github.com/directus/directus/blob/main/docs/netlify.toml

Fixed this

**Review by rijkvanzanten — APPROVED** [review]
Split LGTM. Little worried about people not realizing there's a new top-level nav item in the top-right, but the new homepage should help with that

**Comment by estheragbaje** [comment]
> Split LGTM. Little worried about people not realizing there's a new top-level nav item in the top-right, but the new homepage should help with that

Yes, the new landing page should help with that.

**Comment by phazonoverload** [comment]
Echoing once again that the new landing page should help with that haha. Also, many of these pages are less developer-focused and we're on the chopping block anyway if we didn't make this change, so I anticipate they'll directly be linked to.

**Review by bryantgillespie — APPROVED** [review]

**Pull request merged**
