### PR TITLE
[WIP/RFC] APP extension HMR + API extension live reloading

### PR DESCRIPTION
**Pull request by SeanDylanGoff**
With this PR (once finished) we'll be able to develop all types of extensions much more comfortably.

Adresses:
https://github.com/directus/directus/discussions/5938
https://github.com/directus/directus/discussions/3674
https://github.com/directus/directus/discussions/5539
https://github.com/directus/directus/discussions/5386
https://github.com/directus/directus/discussions/3017
https://github.com/directus/directus/discussions/3044

So far working:

HMR for layouts, displays, interfaces and modules
Reloading of hooks & endpoints without restarting the whole server

Still missing:
- adding/removing of app extensions requires (manual) page reload
- adding/removing of api extensions requires full (manual) server restart.

I'm also planning on adding an additional CI Job to create a second image (either directus-dev:9.0.0-rc.xx or directus:dev-9.0.0-rc.xx) that - as the name implies - runs directus in dev mode.
However: dev directus app runs on port 8080, which could cause a lot of confusion/make it impossible to just swap images for extension dev. 
Can we change this? @rijkvanzanten (I think like 30 versions ago everything was reachable on 8055...)

Also there is one big question: the directory structure. With this approach extensions would not be bundled in dev (but they have to be in prod) - which will create a collision between the bundled and unbundled index.js
Maybe someone has a good idea?

### CODE REVIEW

**Comment by benhaynes** [comment]
Thank you @SeanDylanGoff!! Can't wait to get this reviewed... we really appreciate the help! ❤️

**Comment by nickrum** [comment]
Thanks, improving the extension development experience is definitely a top priority!

Unfortunately this completely breaks npm extensions. We can't support them by using `import.meta.globEager` as it only supports basic glob patterns. For npm extensions we need to dynamically load files based on module resolution. That's why extension loading in dev is currently implemented as a vite plugin.
IMO it is important to re-use as much as possible between local and npm extensions to minimize the maintenance burden of supporting two ways of loading extensions instead of introducing a new way of loading local extensions.
Also, Vite needs to know the path of `import.meta.globEager` at server start so it is not possible to configure the path using the `EXTENSIONS_PATH` env var and (at least to my knowledge) it currently does not support HMR if files are added to or removed from the matched path.

In addition to that, Directus' dev mode should only be used to actually work on the Directus code base. We should either support another _extension-dev_ mode that allows developing extensions by installing directus as a dependency or provide an additional extension development app/host that is specifically built for this purpose. Again, it is important to minimize the maintenance burden of supporting three different environments here. HMR should be implemented in the vite plugin using the unbundled extension source. That way it can be re-used in Directus' dev mode and when developing extensions.

Not exactly sure what you mean by "collision between the bundled and unbundled index.js", but not bundling in dev shouldn't be a problem as long as the extension source itself is equivalent. That's how it is done right now.

**Comment by SeanDylanGoff** [comment]
> Unfortunately this completely breaks npm extensions.

Are npm extensions documented somewhere? Surely there would be a way to support both

> IMO it is important to re-use as much as possible between local and npm extensions to minimize the maintenance burden of supporting two ways of loading extensions instead of introducing a new way of loading local extensions.

Agreed

> Also, Vite needs to know the path of `import.meta.globEager` at server start so it is not possible to configure the path using the `EXTENSIONS_PATH` env var and (at least to my knowledge) it currently does not support HMR if files are added to or removed from the matched path.

The env var is available at server start though?!

> In addition to that, Directus' dev mode should only be used to actually work on the Directus code base. We should either support another _extension-dev_ mode that allows developing extensions by installing directus as a dependency or provide an additional extension development app/host that is specifically built for this purpose. Again, it is important to minimize the maintenance burden of supporting three different environments here. HMR should be implemented in the vite plugin using the unbundled extension source. That way it can be re-used in Directus' dev mode and when developing extensions.

While I understand the intention (I wanted to implement it like this at first aswell), I'm not sure whether:
- it is possible to have "half" of an application in HMR mode
- in case it's possible devtools would work as expected? they won't be able to see "into" directus probably.
- we'd probably have to ship a ton of devDependencies - so we'd need a separate docker image anyways - or waste a lot of space

> Not exactly sure what you mean by "collision between the bundled and unbundled index.js", but not bundling in dev shouldn't be a problem as long as the extension source itself is equivalent. That's how it is done right now.

Directus expects extensions/modules/test/index.js to be a bundled entrypoint.
But where would the unbundled entry be? extensions/modules/test/src/index.js? Would make sense, but feels kinda weird to have the top level directory as a bundle target. extensions/modules/test/dist/index.js would make more sense.

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
