### PR TITLE
feat: gh-action managing pre-releases

### PR DESCRIPTION
**Pull request by sandros94**
No, there isn't an open issue, nor it would make sense for such a small change.

## What this does?

This single change automatically adds the `pre-release` tag inside the GH Releases, as well as adds the corresponding (`alpha`, `beta`, `rc`) tag to the published docker image (this last one is a bit hacky but its due to [this issue](https://github.com/docker/metadata-action/issues/305)). 

image

## Use cases

In the event you would go back to provide pre-releases this would not only make them more organized, but most importantly make them easily available for (external) pre-release CI/CD tests.
I could easily see this becoming particularly useful once #13041 gets drafted.

### CODE REVIEW

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Lets also make sure it's pushed to the correct tag on npm 👍🏻

**Comment by Sandros94** [comment]
> Lets also make sure it's pushed to the correct tag on npm 👍🏻

True.
Let me double check how npm tag work, tomorrow I'll make the changes

**Review by sandros94 — COMMENTED** [review]
https://github.com/directus/directus/pull/19094/commits/a5580fb902be3d3073f7e9fef2639d19e782bc4b#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L43-R66

@rijkvanzanten I don't much like the idea of having all this `if`s, but this was the fastest way to manage it and more in line with the container tagging.

P.S.: I don't have yet npm packages knowledge to double test if this works correctly, I've based the changes purely on the [npm docs](https://docs.npmjs.com/cli/v9/commands/npm-publish#tag) and [pnpm docs](https://pnpm.io/cli/publish#--tag-tag).

**Comment by paescuj** [comment]
> @rijkvanzanten I don't much like the idea of having all this `if`s, but this was the fastest way to manage it and more in line with the container tagging.

Hey @Sandros94, thanks for this! Yeah, I agree. I think it would be worth moving this into a separate action where we could parse the version with [`semver`](https://www.npmjs.com/package/semver) and reliably discover pre-releases.

**Comment by Sandros94** [comment]
> Yeah, I agree. I think it would be worth moving this into a separate action where we could parse the version with [`semver`](https://www.npmjs.com/package/semver) and reliably discover pre-releases.

Yeah, basically rewriting, at least partially, the [metadata-action](https://github.com/docker/metadata-action) as I suggested in [this comment](https://github.com/docker/metadata-action/issues/305#issuecomment-1625618407) in their related issue.

> `[...]`
> Even though I'm not confident enough in js/ts I wanted to open up a pull request anyway, but as soon as I looked at the code I've seen the problem: there is too much manual use of the `latest` tag check, making a refactor a must just to implement them _(`rc`, `beta` and `alpha`)_.
>
> Once I get some free time I'll hope to help with this, `[...]`

Personally, considering my current level in js/ts, it would be quite a time-consuming task atm. So I'm more knee to work on other, more impending, tasks and make this one _nicer_ on a later date (keeping an eye on it with an open issue).

More over, as much it would be nice to follow the full [`semver`](https://semver.org/) spec, IMHO this should be done by something like [`metadata-action`](https://github.com/docker/metadata-action) rather by Directus actions themselves, especially when we consider [the following](https://semver.org/#spec-item-9):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. `[...]` **Pre-release versions have a lower precedence than the associated normal version.** A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

Basically, IMHO, instead of accepting **any** pre-release tag Directus should use only the main ones (`rc`, `beta` and `alpha`), with the main goal of creating functional **order** within the pre-release distribution and testing.

So, some of the paths I currently see (the ones with asterisks at the end are the ones I see feasible right now):
1. Wait for an unofficial, generic, pre-release tag from `metadata-action` (maintainer has said he wont work on it, but neither did not accept PRs).
  a. In the meantime: use all these `if`s to just _make it work_. `(**)`
  b. In the meantime: move all the `if`s to a side action that would handle them (maybe via regex). `(*)`
2. Build our custom `metadata-action` with the `semver` package.

P.S.: I've noticed that I don't currently manage any other non-`rc || beta || alpha` pre-release tags, could this become an issue for you? How strict are you with the tag push?

**Comment by rijkvanzanten** [comment]
>  So I'm more knee to work on other, more impending, tasks and make this one nicer on a later date (keeping an eye on it with an open issue).

I'd usually agree to keep the MVP scope small, but release CI is one of those things that doesn't get touched / worked on for months on end, which in turn means that any tech-debt we introduce now becomes a large maintenance burden over time. Your example around using other tags than alpha/beta/rc is a great example. 6 months from now, we might suddenly decided to release a `next` tag, thinking the release CI will handle it, and things will suddenly fail.

> Basically, IMHO, instead of accepting any pre-release tag Directus should use only the main ones (rc, beta and alpha), with the main goal of creating functional order within the pre-release distribution and testing.

This makes sense for dev->GA release flows, but doesn't work for nightly releases 🤔

**Comment by Sandros94** [comment]
> 6 months from now, we might suddenly decided to release a `next` tag, thinking the release CI will handle it, and things will suddenly fail.

This becomes especially true for newcomers. Yeah I do see how the current approach would be fine for small to medium projects with decent SOP, but not so much here.

> This makes sense for dev->GA release flows, but doesn't work for nightly releases 🤔

While looking at your GA I didn't notice one for nightly releases. So I imagined this was on purpose, since each build is roughly 40-50 minutes and most probably it would substantially increase GA costs.

I've limited experience on this, when we talk about big projects. On the smaller scale I usually assign one of my free worker nodes just for that, again with the only aim to cut down on GA costs for potentially unsuccessful builds (I'm still rough with test scripts 😜).

## So far

So, just to confirm I'm getting things right, this should be the current state:
- **We should remove all the `if`s**:  the main objective of this would be to not preclude ourselves the ability to use any other tags (especially when using multiple ones at the same time, ex: `v12.0.0-alpha.evaluation`).
- **Moving the analysis of the `semver` to a separate GA**: this would not only reduce the tech-debt but potentially make it easier to include other `semver` features like metadata endling.

For the last point I yet don't fully understand if it would be better to implement this directly in the original `metadata-action` or it would be better off creating our own.

**Comment by rijkvanzanten** [comment]
> While looking at your GA I didn't notice one for nightly releases. So I imagined this was on purpose, since each build is roughly 40-50 minutes and most probably it would substantially increase GA costs.

It's mostly because we simply haven't had the time to configure the infrastructure for it yet 🙂 If we have the release automation configured in a way that can already handle pre-releases like you're implementing here, we can start doing nightly releases easier as well!

> So, just to confirm I'm getting things right, this should be the current state

That sounds correct to me!

> For the last point I yet don't fully understand if it would be better to implement this directly in the original metadata-action or it would be better off creating our own.

Ideally we have a custom step that can extract the right information first, and then pass that information to the existing `metadata-action` 👍🏻

**Comment by Sandros94** [comment]
> It's mostly because we simply haven't had the time to configure the infrastructure for it yet

Would you prefer keeping nightly releases as GA or setup it externally?

> If we have the release automation configured in a way that can already handle pre-releases like you're implementing here, we can start doing nightly releases easier as well!

In general shouldn't we consider nightly releases separate from pre-releases? Even just the triggering is different (daily instead of manually via tag push). In this regard `metadata-action` already has a [type=schedule](https://github.com/docker/metadata-action/#typeschedule). So IMO we should create a different GA, mainly to keep it separate since they have a different trigger and the nightly builds all should share the same nightly tag.

> Ideally we have a custom step that can extract the right information first, and then pass that information to the existing `metadata-action` 👍🏻

What about doing the other way around? In a custom step (that is executed in a separate GA) using `metadata-action` to extract the right information (considering it already does [90% of the job](https://github.com/docker/metadata-action/#typesemver)) and using that already filtered information to do the last part (managing custom tags and pre-releases).

I already have a few ideas rn and I need to test them on my end first, although I wont be able to do so this week. One problem I already see it coming is that while the `semver` standard already covers custom (and multiple) tags, that would be easily managed by both image and package registries, how should we handle the GH Releases? As far as I'm aware they only support `prerelease` and `latest`, regardless of other tags. 🤔

**Comment by Sandros94** [comment]
> That'd be on GA as well 👍🏻
> 
> They're released on a different schedule, but a "nightly" tag is still a "pre-release", as there's only "pre-release" and "release"

If I'm not mistaken GA should permit multiple triggers. In this case I should be able to mange both tag-push and cron-job triggers in the same `release.yml`, while doing a step inside something like `tags.yml` action. Once I make a working one I'll update this PR.

> GH releases should have the full version (including tag) number in the release title, and everything that isn't a regular "release" is a "pre-release", regardless of tag

Yeah, my brain just didn't work as it should... now that I've eaten something I'm noticing I was overcomplicating things.

**Comment by Sandros94** [comment]
This is probably going to take a bit. The main reason is that I've noticed a major flaw in my original approach, basically it doesn't take in consideration for which version we are adding the pre-release tag.

Eg.: we already have `v11.0.0-alpha` published, thus it would have the `alpha` tag assigned to it. In the event we start working on `v10.9.0-alpha` that contains a number of breaking changes in the current state as soon as the workflow is completed this later one would get the `alpha` tag, removing it from the other one. A correct approach would be to assign the most generic tag only to its latest revision of the latest pre-release version, but yet provide additional tags for those not-so-latest pre-releases.

The Idea I have in my head is:
| GA-Event          | Tags                                                       |
|-------------------|------------------------------------------------------------|
| `v11.0.0-alpha`   | `11.0.0-alpha`, `11.0-alpha`, `11-alpha`, `alpha`          |
| `v10.9.0-alpha.4` | `10.9.0-alpha.4`, `10.9.0-alpha`, `10.9-alpha`, `10-alpha` |
| `v10.9.0-alpha.3` | `10.9.0-alpha.3`                                           |
| `v10.8.4-alpha.9` | `10.8.4-alpha.9`, `10.8.4-alpha`, `10.8-alpha`             |

But to do so I'm forced to create a separate GA based on [semver](https://www.npmjs.com/package/semver) (as it was first suggested).

> Hey @Sandros94, thanks for this! Yeah, I agree. I think it would be worth moving this into a separate action where we could parse the version with [`semver`](https://www.npmjs.com/package/semver) and reliably discover pre-releases.

This would also mean that we could reliably check for pre-existing `pre-releases` and prevent adding the most generic tags to releases that aren't the most recent ones.

As I gain more and more js/ts knowledge I'm starting to think that I'm able to do such task, but I want to experiment a bit beforehand on my side. The semver package should already do 90% of the work, so I need to configure the last part about the top level generic pre-release tags.

One aspect I don't understand from the [semver specs](https://semver.org/#spec-item-11) is situations like `10.9.0-alpha.beta` where this should be the latest version for between migrating from `alpha` to `beta`, so in my head it is like a point of no return (to other `alpha.n`), but I don't much like this approach. Should we strictly follow the spec or manage it differently?

**Comment by rijkvanzanten** [comment]
> One aspect I don't understand from the [semver specs](https://semver.org/#spec-item-11) is situations like 10.9.0-alpha.beta where this should be the latest version for between migrating from alpha to beta, so in my head it is like a point of no return (to other alpha.n), but I don't much like this approach. Should we strictly follow the spec or manage it differently?

I'm down to say lets only focus on `major.minor.patch` (GA releases) and `major.minor.patch-tag.n` (prerelease) formats. Once you get into the `x-tag.tag.tag.tag.n` situation, things get weird / difficult quickly

**Comment by Sandros94** [comment]
> I'm down to say lets only focus on `major.minor.patch` (GA releases) and `major.minor.patch-tag.n` (prerelease) formats.

Yeah, I'm scratching my head around this for the last few hours, while my understanding of the spec define the whatever thing is after the dot of a tag as its version identifier, the current state of semver package does the opposite (`semver.prerelease(version)` outputs `["beta", "3-test"]` instead of `["beta.3", "test"]` for `10.9.0-beta.3-test` as input).

It could only be me that I'm doing something wrong, but will see.

> Once you get into the `x-tag.tag.tag.tag.n` situation, things get weird / difficult quickly

IMO that should output the following tags: `x-tag.tag.tag.tag.n`, `x-tag`, `tag` (only if x is the latest one).

**Comment by rijkvanzanten** [comment]
> Yeah, I'm scratching my head around this for the last few hours, while my understanding of the spec define the whatever thing is after the dot of a tag as its version identifier, the current state of semver package does the opposite (semver.prerelease(version) outputs ["beta", "3-test"] instead of ["beta.3", "test"] for 10.9.0-beta.3-test as input).

Lets for this change only focus on GA and single-tag releases (f.e. `10.4.3-beta.3`) 👍🏻 

Anything beyond that is very uncommon, and feels very complicated to solve (and will most likely not be used within the context of Directus 😁 )

**Comment by Sandros94** [comment]
> Anything beyond that is very uncommon, and feels very complicated to solve (and will most likely not be used within the context of Directus 😁 )

Funnily enough (yes yes, I know, I probably kept focusing on the wrong detail) it has been super simple to manage. But it made me realize another decent flaw in that approach: it wouldn't take in consideration any duplicates. If `v11.0.0-alpha.69-test.420` exists just pushing `v11.0.0-alpha.69` and/or `v11.0.0-test.420` could potentially create a number of issues.

So yeah, I'm starting to fully agree on managing only one pre-release tag at the time. Should I force it?

**Comment by rijkvanzanten** [comment]
> EDIT2: at that point I might just consider to fail the GA if the input contains more than one prerelease tag...

Yes! This 😄

**Comment by Sandros94** [comment]
> > EDIT2: at that point I might just consider to fail the GA if the input contains more than one prerelease tag...
> 
> Yes! This 😄

Perfect, then I got it already, mostly, working.

One last thing that I've noticed (that it is a problem for the current `docker/metadata-action` too) is that it has no way to fetch the list for current active tags. This would be somewhat of a dealbreaker for pre-releases because the generic tags would go to whichever version is being released last.

Example with `docker/metadata-action`:
image
(this happens for every generic tags, like `latest`, `alpha`, `beta`, `rc` and so on.)

I'll try to solve this last one, then update the PR either way.

**Comment by rijkvanzanten** [comment]
Thanks @Sandros94! We took the great research presented in this PR, continued on it, and merged it in through #19510 😄

**Comment by paescuj** [comment]
> I see, such a great work. I probably couldn't even match it. I'm glad to have helped even just on the research side of things!

Looking forward to your next contribution 😃❤️

**Pull request closed without merging**
