### PR TITLE
Revision of tsconfig files & introduction of type checking

### LINKED ISSUE #7953: Add `tsc` to linting step
As @Oreilles correctly pointed out, `vite` doesn't seem to type check the code at the moment. We should update the `lint` command (and therefore the lint CI step) to run `tsc` globally to make sure there's no type regressions introduced

### PR DESCRIPTION
**Pull request by paescuj**
As reqested and discussed in #7953, this introduces type checking of the code base.

Closes #7953.

See [below](https://github.com/directus/directus/pull/9375#issuecomment-962067237) for explanation.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Thanks @paescuj! @Oreilles will finally be able to sleep easy at night knowing that the TypeScript warnings in the app will be checked 😴

**Comment by Oreilles** [comment]
Lovin' it ❤️

**Comment by rijkvanzanten** [comment]
@paescuj Should we try resolving the type issues that are preventing the linter from passing in this PR?

**Comment by paescuj** [comment]
> @paescuj Should we try resolving the type issues that are preventing the linter from passing in this PR?

Yes, would prevent the linting check to fail all the time after merging this PR...

**Comment by nickrum** [comment]
How about moving the type checking to the build step of the app? When scaffolding a Vite/Vue3/Typescript project, Vite now adds a `"build": "vue-tsc --noEmit && vite build"`-script to package.json. IMO this makes a lot of sense given all the other packages are also type-checked at build time.

This tsconfig `references`-thing is quite interesting. Never seen that one before. I'm wondering how useful it is for us, though. Looking at the docs, it seems like `references` is a means to structure a Typescript-based package into even smaller pieces. In our case it creates a file-system based coupling between packages which should ideally be able to exist in isolation only being coupled through npm.

**Comment by paescuj** [comment]
Thank you very much @nickrum for your review & feedback!

I've not yet been able to provide a detailed description to the PR, so I'm now doing this here.

> How about moving the type checking to the build step of the app? When scaffolding a Vite/Vue3/Typescript project, Vite now adds a `"build": "vue-tsc --noEmit && vite build"`-script to package.json. IMO this makes a lot of sense given all the other packages are also type-checked at build time.

I decided to integrate the type checking into the linting steps (as opposed the build steps) for the following reasons:
* This allows us to quickly check the whole code base using one dedicated command (`npm run lint:typescript`) without having to build all the packages (type check **15s** vs build **1m5s**).
* It allows us to check parts of the repo which don't have a "build process" or don't to type checking (like `/tests`, `format-title`).
* And probably the main reason is "vue-tsc", while the package itself being great it comes with the following downsides for us:
  * Currently throws out more than 700 errors.
  * It takes 1min to complete, which would be added to the build process every time.
  * It increases `node_modules` by another 80MB and 89 packages...

For this reason I've created a separate job in the "Lint" workflow which does the checking of `app` with "vue-tsc".
I'd like to keep it separate until we have solved those issues in the app. Afterwards, I agree that it makes more sense (also from a technical point of view) to move the type checking to the build step. Having all `vue` files type checked would then obviously make up for the increased build time and size of `node_modules`.

> This tsconfig `references`-thing is quite interesting. Never seen that one before. I'm wondering how useful it is for us, though. Looking at the docs, it seems like `references` is a means to structure a Typescript-based package into even smaller pieces. In our case it creates a file-system based coupling between packages which should ideally be able to exist in isolation only being coupled through npm.

While looking for a way to type check all packages with just one command I stumbled upon [project references](https://www.typescriptlang.org/docs/handbook/project-references.html). Many other projects structured as monorepos seems to use it the way I've configured it in this pull request.
By using `references` we profit from these two points:
* Build mode will automatically build the referenced project if needed, so you don't need to build other packages before. Also a nice-to-have in watch mode.
* Having features like “Go to Definition” in supported editors (for example VS Code).

You made a valid point though concerning the isolation of the packages. What do you think @nickrum & @rijkvanzanten (and maybe others), should we better go on without "project references"?

**Comment by paescuj** [comment]
> You made a valid point though about the isolation of the packages. What do you think @nickrum & @rijkvanzanten (and maybe others), should we better go on without "project references"?

After thinking about this for a while my conclusion is that we should go on without "project references" in the build process (for @nickrum's reason).
However, we could still profit from them by having two configuration files in each package - one for the build process (`tsconfig.build.json`, without references) and one for "dev mode" (`tsconfig.json`, with references - picked up by IDEs like VS Code).

Let me know about your thoughts! I'll happily update this PR accordingly.

**Comment by nickrum** [comment]
> Currently throws out more than 700 errors.

Ah yeah, this is likely the same issue that is currently plaguing the Volar VS Code extension. As far as I know, both Volar and `vue-tsc` transpile Vue SFCs to JSX to do type checking. But, as we transitively import `@types/react` througth `fullcalendar`, Typescript will ignore the JSX types provided by Vue and use the React ones instead. I don't think there is a solution to this issue yet.

The other reasons for doing type checking as part of the lint step also make sense to me 👍

> Having features like “Go to Definition” in supported editors (for example VS Code).

Interesting! Doesn't that work out of the box in VS Code? When I hit "Go to Definition" on something imported from `@directus/shared`, VS Code directs me to the correct file.

**Comment by paescuj** [comment]
Sorry for my super late answer on this!

> Ah yeah, this is likely the same issue that is currently plaguing the Volar VS Code extension. As far as I know, both Volar and vue-tsc transpile Vue SFCs to JSX to do type checking. But, as we transitively import @types/react througth fullcalendar, Typescript will ignore the JSX types provided by Vue and use the React ones instead. I don't think there is a solution to this issue yet.

Interesting... Thanks for the explanation! Probably, this has been fixed in the meantime, at least the type errors now have dropped to ~400.

> Interesting! Doesn't that work out of the box in VS Code? When I hit "Go to Definition" on something imported from @directus/shared, VS Code directs me to the correct file.

The difference here is that you don't need to build the other packages beforehand.

---

So, I'd like to resume the work on this issue.
Personally, I'd propose to keep things simple and proceed as follows:

1.  Submit a pull request which addresses all the type errors in the app
2. Enable type check in the build process of the app (`vue-tsc --noEmit && vite build`)
3. Submit a separate pull request which contains the other cleanups I did in this pull request

What do you think?

**Comment by rijkvanzanten** [comment]
> Submit a pull request which addresses all the type errors in the app

Lets do this as multiple smaller PRs. A single PR that tries to fix all is going to be a hundreds-of-files-thousands-of-lines PR which is going to be impossible to review/merge quickly enough to prevent 1000 merge conflicts. I'd rather tackle in smaller chunks 🙂

**Comment by rijkvanzanten** [comment]
Approach makes total sense! Fixing the issues first, then enabling the automation to ensure no new errors sneak in feels like the right move. Doing it in reverse requires everything to be done in parallel, which isn't gonna work.

As for grouping, difficult! My gut feeling would say per "section" (maybe modules?) or "component type" (eg views vs components etc), but honestly it doesn't really matter, as long as the individual "chunks" don't get too large.

**Comment by paescuj** [comment]
Great! Thanks for sharing your thoughts! I'm going to look into this and will see how it is most practical.

**Comment by paescuj** [comment]
I'm closing this in favor of #16545 and other pull requests that will follow.

**Pull request closed without merging**
