### PR TITLE
Fix public assets

### LINKED ISSUE #21359: Public assets no longer accessible
### Describe the Bug

A small change in #20768 is causing  permissions errors on assets that should be publicly accessible. We had an exception for `public background`, `logo`, etc in the settings to be publicly accessible without having to edit the permissions.

image

### To Reproduce

1. update to 10.9
2. select a public image in the settings
3. log out or try to access the image directly without authentication

### Directus Version

10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #21359 

## Scope

What's changed:

- Added admin permissions to the FilesService used in the AssetsService.
- Removed an obsolete data check as `FilesService.readOne` will always return an Item or throw an error itself.

## Potential Risks / Drawbacks

- Depends on whether this change was required.

## Review Notes / Questions

- I would like to lorem ipsum

### CODE REVIEW

**Comment by paescuj** [comment]
> @DanielBiegler do we need the filesService for something focal point related here?

IIRC, this was changed to ensure the data is properly casted which isn't necessarily the case when using direct knex.
Can we remain on `FilesService` but with `accountability: null`?

**Comment by br41nslug** [comment]
Sure that works for me 😄

**Comment by paescuj** [comment]
> We're explicitly casting the returned value using `as` so that makes little difference i think 🤔 the original casting was incorrect tho missing the `undefined` option

Sorry, I wasn't talking about TS, but the actual values being processed via Files/ItemsServices.

**Review by paescuj — APPROVED** [review]
Works and looks good 🙏

**Pull request merged**
