### PR TITLE
update Marathi (mr-IN) translation to 94% completion

### PR DESCRIPTION
**Pull request by satputekuldip**
This pull request includes changes to add Marathi (India) language support and update the contributors list. The most important changes include adding Marathi to the list of translations, updating available languages, and defining number formats for Marathi.

Language support additions:

* [`.changeset/wild-frogs-carry.md`](diffhunk://#diff-e84b7587447c27a5623bd2612449477ea5d060ce3d4cb412e9c6be803a624355R1-R5): Added Marathi (mr-IN) to the list of translations with 94% completion.
* [`app/src/lang/available-languages.yaml`](diffhunk://#diff-6a934d874215dc23e22e41ffb9a67d059f311fd716890e7c5bcef9e5ac94c192R42): Added Marathi (India) to the list of available languages.
* [`app/src/lang/number-formats.yaml`](diffhunk://#diff-484c9c71601da4cfb89e0304437fc0971b414301df6245567445aef71197f9b4R534-R546): Defined currency, decimal, and percent number formats for Marathi (India).

Contributors update:

* [`contributors.yml`](diffhunk://#diff-4e549b88aa1ad2b3d1d7fe9eddeb285ecc6d471a242534282da55decd768e6d4R191): Added `satputekuldip` to the contributors list.

### CODE REVIEW

**Comment by satputekuldip** [comment]
Its 100% now... please merge this PR

**Comment by hanneskuettner** [comment]
Heya @satputekuldip thank you so much for your effort translating the Studio!

Seems like the unit tests might be failing because the translations actually live in the `translations` branch. @paescuj have you dealt with adding a new language before? Should this PR be based on the `translations` branch so that it can be merged into it?

**Comment by paescuj** [comment]
Latest Marathi translations are now in `main` 👍 

@satputekuldip Please update this branch to be on the latest state of `main`. For future PRs, it would be great if you first create a new branch instead of directly working on `main`, as this makes it easier for maintainers to work on or update the PR 🙏 Thank you!

**Comment by satputekuldip** [comment]
There were 3 variable problems in the translation... I've fixed them on crowdin... should I push the changes directly or wait for update from crowdin...
and sorry for `main` brach PR next time it won't happen...

**Comment by satputekuldip** [comment]
I'm closing this PR as translation branch just updated... I'll open new PR with the new changes...

**Pull request closed without merging**
