### PR TITLE
Add format query parameter to assets

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
Add support for reformat image output on assets. It adds support for `format` parameter.

Idea  https://github.com/directus/directus/discussions/3057

### CODE REVIEW

**Comment by benhaynes** [comment]
Thank you so much, @dimitrov-adrian — we'll review ASAP!

**Comment by rijkvanzanten** [comment]
LGTM!

We'll have to figure out if and how we want to expose this under settings too. We should add a dropdown to the directus settings assets for `format`

**Comment by dimitrov-adrian** [comment]
It might be useful for using in assets settings. I was more of thinking it for use in web apps usecases, where you need conditional use asset as a webp for example.

**Comment by rijkvanzanten** [comment]
Yeah definitely! I'm just thinking about the use case where you want to prevent people from being able to generate any size/format they want, but instead rely on a preconfigured set of sizes with those keys. By not surfacing this in settings, you'd only be able to use the `format` parameter if you allow "full" usage of the assets endpoint transform query params

**Comment by dimitrov-adrian** [comment]
Exposed setting in assets as

Screenshot 2020-11-24 at 0 51 32

**Comment by rijkvanzanten** [comment]
@dimitrov-adrian (better late than never update) Thanks! We'll be moving away from the fixed settings structure (width/height/quality/etc) in favor of dynamic JSON objects that let you combine any of sharps options. This also allows us to start exposing more of Sharps functionality through query params, like compositing/blending rotate, background-colors etc etc etc 😄 

I'll pick that up on this branch as a starting point 👍🏻

**Comment by cynova** [comment]
@rijkvanzanten can you tell us if there is anything we could contribute (code/documentation/whatever) to get this merged ASAP? Or is it just waiting on something else?

**Comment by rijkvanzanten** [comment]
@cynova I'd like to turn this into a bigger change that allows for any of sharp's methods, instead of allowlisting one at a time, and increasing the complexity of the project settings configuration. The main things are:

https://github.com/directus/directus/pull/3154/files#diff-5da24c390f8befd890a3c9e96c17862e386efabee8937b09120547bfcaa397d0R39-R46

Making sure that this list contains ~~all~~ most of sharp's options (some of them don't make sense in an endpoint context, like global sharp configuration)

You can also always ask somebody else (me/wolf/nils/martin/aiden/etc) to take a look :) 

Making sure that this is a "flexible" JSON object that allows for any of the options in the endpoint, instead of just the 5 or so we have now.

We don't necessarily have to implement every sharp feature as a query param immediately to suffice for this PR, but it would be nice to set the correct infrastructure in place to more easily extend that in the future, before we start adding more options as one-offs 👍🏻

**Comment by tim-smart** [comment]
Started playing around with an idea here: https://github.com/directus/directus/pull/6593

**Comment by rijkvanzanten** [comment]
Superseded by and added in #6593

**Pull request closed without merging**
