### PR TITLE
Adds user to rate limit key

### PR DESCRIPTION
**Pull request by keesvanbemmel**
This PR needs some discussion.

The goal of this PR is to keep a rate limit score per user, if a user is logged in / accountability is avaible.

At the moment rate limits are counted per IP address. But some larger companies have hundreds of employees working from behind the same external IP address. In these cases a rate limit per user on a specific IP is required.

I have solved this in the past by adding the user id to the IP address and let the combination of the two be the rate limit key. If no accountability is available, only the IP address is used.

**The reason this PR needs a discussion:**
To get access to accountability info in the request, the `authenticate` middleware should be called before the `rate-limit` middleware.

Now this opens directus up to this: if someone has a VALID directus JWT token that can not be verified through JWT means, the database will be queried to find a user that matches that token. This happens before the rate limiter kicks in and might be a potential opening for ddos like attacks? Not sure, but that's what I would like to discuss.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
This is an interesting catch-22 🤔 We can't authorize before the rate limiter, as that means the rate limiter no longer protects against brute forcing the auth, but we need the authorizer first in order to extract the user to track in the rate limiter

**Comment by keesvanbemmel** [comment]
Perhaps add a second limiter? One only for auth routes for example?

**Comment by rijkvanzanten** [comment]
Maybe! We could put a rate limit on how fast you can login to the same user for example, that would prevent the issue and doesn't have the same IP problem 🤔

**Comment by rijkvanzanten** [comment]
@licitdev This is an interesting chicken/egg puzzle. You need to scope the rate limit to a given user if provided in order to prevent users on a shared IP (like a corporate network) to be caught in the same rate limiter, but we can't use `authenticate` before the rate limiter, as that allows the outside world to brute-force the `authenticate` call. I think we need to look into adding a custom rate-limiter just for calls to the authenticate middleware, to prevent brute-forcing the auth, and then call the "regular" rate limiter (now with the updated user scope) after that

**Comment by licitdev** [comment]
>  I think we need to look into adding a custom rate-limiter just for calls to the authenticate middleware, to prevent brute-forcing the auth, and then call the "regular" rate limiter (now with the updated user scope) after that

Agreed, we should add a separate rate limiter before the `authenticate` middleware to prevent brute-forcing of authentication. This rate limiter should still be scoped to the IP address, with the rate-limit value reset upon successful authentication. 👍🏻

**Comment by rijkvanzanten** [comment]
This was superseded by https://github.com/directus/directus/pull/17296 🙂

**Pull request closed without merging**
