### PR TITLE
[WIP] add folder picker in file/files/image interface drawer

### LINKED ISSUE #15968: Add folder picker in image/file interface drawer
When using the image(s)/file(s) interfaces, the sidebar doesn't render the folder picker. We should render the file-library folder picker in the left sidebar of the drawer when the files are being selected.

---

### Discussed in https://github.com/directus/directus/discussions/4999

<div type='discussions-op-text'>

<sup>Originally posted by **Meldiron** April 12, 2021</sup>
If we add `Image interface` there are 3 options: from disk, from gallery, from URL

image

If we pick option `from mgallery`, we get list of all files uploaded to Directus that we can filter by name

image

My idea is, can we filter by folders? If I enter file library, there is the left panel to put files into folder in order to prevent mess

image

**Having a folder selection instead of list of all files would be awesome ♥**</div>

### PR DESCRIPTION
**Pull request by azrikahar**
## Description

Fixes #15968

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by LasseRosenow** [comment]
If I have configured a specific folder for my file picker, it would not show the whole folder tree, but only the configured one and its sub-folders correct?

**Comment by danieljwestman** [comment]
> If I have configured a specific folder for my file picker, it would not show the whole folder tree, but only the configured one and its sub-folders correct?

Thats an important aspect ☝🏼

**Comment by azrikahar** [comment]
Closing this for now in favor of narrowing review efforts on other PRs first.

**Comment by azrikahar** [comment]
For reference purpose, this is now superseded by #18320 👍

**Pull request closed without merging**
