### PR TITLE
Fix column sorting (issue #2033)

### PR DESCRIPTION
**Pull request by alexshevch**
Right now column sorting does not work, until the user manually refreshes the page. This is a simple sorting fix that forces the table to rerender when needed. The reload happens smoothly, using the default directus loading indicator. It does not reload the entire page, caching is still applied. Works in all major browsers.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hey @shevaroller! Thanks for the help 😄 

Closes #2033

**Comment by WellingGuzman** [comment]
Hey @shevaroller thanks for the contribution, I do have one question: I know this is a quick fix, but doesn't this come with a drawback? this runs the router again, rendering the whole module.

**Comment by rijkvanzanten** [comment]
@WellingGuzman True, but better this re-rendering drawback than the thing not working at all 😄

**Comment by shevaroller** [comment]
@WellingGuzman you are right. A proper fix is still much appreciated :)

**Pull request merged**
