### PR TITLE
Fix "Update files date fields" migration failed on MySQL (#23647)

### PR DESCRIPTION
**Pull request by miauyo**
* Fix "Update files date fields" migration failed on MySQL

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hey @miauyo! What issue # is this fixing?

**Comment by miauyo** [comment]
> Hey @miauyo! What issue # is this fixing?

#23647

**Comment by paescuj** [comment]
> > Hey @miauyo! What issue # is this fixing?
> 
> #23647

Thanks! And how is this supposed to fix the issue? The column `uploaded_on` would now be missing 👀

**Comment by miauyo** [comment]
> > > Hey @miauyo! What issue # is this fixing?
> > 
> > 
> > #23647
> 
> Thanks! And how is this supposed to fix the issue? The column `uploaded_on` would now be missing 👀

My understanding is that the two fields uploaded_on and created_on are repeated

**Comment by paescuj** [comment]
> My understanding is that the two fields uploaded_on and created_on are repeated

Ah not quite, the migration first renames the existing column `uploaded_on` to `created_on` (in order to keep the data) and then creates a new column again named `uploaded_on`. Now, as reported in #23647, the latter leads to an issue on MySQL under certain circumstances (SQL modes, ...).

I'll close this pull request as the suggested solution doesn't work, but you're very welcome to submit a new one if you got another solution. Thanks! ❤️

**Pull request closed without merging**
