### PR TITLE
Fix "Save as Copy" for relational fields

### LINKED ISSUE #9991: "Save as copy" does not copy relational fields
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

As mentioned https://github.com/directus/directus/issues/6963#issuecomment-975709592, and https://github.com/directus/directus/discussions/9910 I re-open this subject : 

When I duplicate (_save as copy_) an item which has O2M "related items" to one or several of its fields, these related items are not copied, they are just "moved": after *save as copy* is run, the initial item's o2m field will be empty.

The problem is worse for M2M relationships : When I copy an item with M2M fields, I'm not sure of what happens for its M2M fields, but it looks like the junction table rows AND related items are not copied.

### To Reproduce

- Create a collection A, with O2M fields, and a M2M field. 
- Create an item of A (let's call it `a.1`), with some related items in O2M and M2M fields.
- Select every duplication fields of A except `ID` (the result is same if you select every duplication fields except ID and recursively related collection ID's)
- Save the `a.1` item " as a copy ". Let's call this new item `a.2`.

Result : Some strange behavior happens. While I'm expecting than the `a.1` item is copied with all related items copied and linked to my new `a.2` item, it appears than some O2M items are just "moved" under `a.2` and so removed from `a.1`.

### Errors Shown

_No response_

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

latest

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #9991

## Before

Using "Save as copy" on relational fields will "re-assign" them to the new item, thus "removing" them from the original item. This is true even when Items Duplication Field has been setup (without the IDs).

https://user-images.githubusercontent.com/42867097/145423648-42ad442b-bc6a-44ac-9865-10125d4f421b.mp4

This is due to during saving, the relational fields still have their primary key attached to them.

## Investigation

Currently there's existing implementation to remove primary keys, but it doesn't check/delete nested ones:

https://github.com/directus/directus/blob/81262800cb271e033cc865dcd620f8061579579c/app/src/composables/use-item/use-item.ts#L178-L181

## Solution

- delete nested keys
  - at the same time, some nested items only has their ID when they are not actually edited. Hence during this process, we had to call the api again using the fields from item duplication fields, and replace the ID-only entries.
- Also changed `router.push` to `router.replace` since it felt more natural personally, but can be reverted if there's reasons for `router.push` that's not apparent for me at the moment.

## After

https://user-images.githubusercontent.com/42867097/145424113-8f3e58c8-7332-4f60-b5ed-d2afdd7f79ec.mp4

### CODE REVIEW

**Review by rijkvanzanten — COMMENTED** [review]
@azrikahar Should this check happen recursively? Right now it only checks on the first nested o2m level right? 🤔

**Comment by azrikahar** [comment]
@rijkvanzanten oh ya... I believe it is not recursive indeed. I'll check on it again and amend accordingly 👍

**Comment by rashidpathiyil** [comment]
This is a issue I have been experiencing for a long time, I thought it might have been reported by someone

Database: PostgreSQL

**Review by rijkvanzanten — APPROVED** [review]

**Comment by younky-yang** [comment]
I still got the infinity circle rolling when click Save as Copy if the collection item has an M2M relations.

**Comment by azrikahar** [comment]
> I still got the infinity circle rolling when click Save as Copy if the collection item has an M2M relations.

Would you mind opening a new issue with a schema snapshot so that we can investigate further and better attempt to reproduce it? Thanks 👍

**Comment by younky-yang** [comment]
https://github.com/directus/directus/issues/13426

**Comment by ricricucit** [comment]
JFYI:
I'm testing on the cloud version, and what you see in the screen + "_Save as copy_", give me infinite loading.

Screenshot 2022-12-30 at 19 04 58

**Comment by br41nslug** [comment]
@ricricucit This can unfortunately be due to this other still open issue for "save as copy" https://github.com/directus/directus/issues/15771

**Comment by ricricucit** [comment]
shouldn't, this same PR, have fixed it? 🤔 
FYI: Tried removing all IDs from duplication fields, didn't fix it for me.

**Comment by br41nslug** [comment]
@ricricucit I don't think this is related to the "save as copy" itself. It looks like you have an empty field `&fields[]=` in your url which is not allowed. Removing this should fix it or please create a new issue if this request was generated by the App.

**Pull request merged**
