### PR TITLE
Add extra type check in apply-diff

### LINKED ISSUE #18774: cannot delete schemas when applying them twice
### Describe the Bug

While testing stuff for #17117 I've noticed that if I try to apply a schema twice on the second time it prompts me to delete the collections. Which even for an edge case this could indeed be useful. But when I try to do it it throws this error:

```log
ERROR: Cannot read properties of null (reading 'meta')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'meta')",
      "stack":
          TypeError: Cannot read properties of null (reading 'meta')
              at file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/utils/apply-diff.js:124:128       
              at Array.filter (<anonymous>)
              at file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/utils/apply-diff.js:124:58        
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
```

### To Reproduce

As per the other issue, you can find the files in [this branch](https://github.com/Sandros94/test-nuxt3app/tree/directus).

<details>
  <summary>docker-compose-dev.yml</summary>
  
  ```yml
  version: '3.4'

  services:
    directus:
      image: directus/directus:10.2

      user: node
      command: sh -c "node /directus/cli.js bootstrap && node /directus/cli.js schema apply --yes /directus/schema.yml && node /directus/cli.js start"

      volumes:
        - ./schema.yml:/directus/schema.yml:ro
      #  - directus-uploads:/directus/uploads
      #  - directus-extensions:/directus/extensions
      ports:
        - 8055:8055

      tty: true
      stdin_open: true
      environment:
        KEY: 'second-key'
        SECRET: 'second-secret'
        DB_CLIENT: 'pg'
        DB_HOST: 'database'
        DB_PORT: '5432'
        DB_DATABASE: 'directus-db'
        DB_USER: 'directus'
        DB_PASSWORD: 'directus'
        DB_POOL__MIN: '0'
        CACHE_ENABLED: 'true'
        CACHE_STORE: 'redis'
        CACHE_REDIS: 'redis://cache:6379'
        # CACHE_AUTO_PURGE is for recreating the cache every time the db content is update/created/deleted - this will change in the future
        CACHE_AUTO_PURGE: 'true'
        ADMIN_EMAIL: 'user@example.com'
        ADMIN_PASSWORD: 'password'
        ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '8256'
        CORS_ENABLED: "true"
        CORS_ORIGIN: "true"
        CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "www.google.com google.com www.youtube.com youtube.com"

      depends_on:
        - database
        - cache


    database:
      image: postgis/postgis:13-master
      tty: true
      stdin_open: true
      #volumes:
      #  - directus-db:/var/lib/postgresql/data
      #  - directus-db_dumps:/db_dumps
      environment:
        POSTGRES_DB: 'directus-db'
        POSTGRES_USER: 'directus'
        POSTGRES_PASSWORD: 'directus'


    cache:
      image: redis:6
      depends_on:
        - database


  #volumes:
    #directus-uploads:
    #directus-extensions:
    #directus-db:
    #directus-db_dumps:
  ```
</details>

<details>
  <summary>schema.yml</summary>
  
  ```yml
  version: 1
  directus: 10.1.0
  vendor: postgres
  collections:
    - collection: links
      meta:
        accountability: all
        archive_app_filter: true
        archive_field: status
        archive_value: archived
        collapse: open
        collection: links
        color: null
        display_template: null
        group: null
        hidden: false
        icon: null
        item_duplication_fields: null
        note: null
        singleton: false
        sort: null
        sort_field: null
        translations: null
        unarchive_value: draft
      schema:
        name: links
  fields:
    - collection: links
      field: date
      type: date
      meta:
        collection: links
        conditions: null
        display: null
        display_options: null
        field: date
        group: null
        hidden: false
        interface: datetime
        note: null
        options: null
        readonly: false
        required: true
        sort: 4
        special: null
        translations: null
        validation: null
        validation_message: null
        width: half
      schema:
        name: date
        table: links
        data_type: date
        default_value: null
        max_length: null
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: links
      field: id
      type: uuid
      meta:
        collection: links
        conditions: null
        display: null
        display_options: null
        field: id
        group: null
        hidden: true
        interface: input
        note: null
        options: null
        readonly: true
        required: false
        sort: 1
        special:
          - uuid
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: id
        table: links
        data_type: uuid
        default_value: null
        max_length: null
        numeric_precision: null
        numeric_scale: null
        is_nullable: false
        is_unique: true
        is_primary_key: true
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: links
      field: link
      type: string
      meta:
        collection: links
        conditions: null
        display: null
        display_options: null
        field: link
        group: null
        hidden: false
        interface: input
        note: null
        options:
          iconLeft: link
          placeholder: link
        readonly: false
        required: true
        sort: 3
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: link
        table: links
        data_type: character varying
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: links
      field: name
      type: string
      meta:
        collection: links
        conditions: null
        display: null
        display_options: null
        field: name
        group: null
        hidden: false
        interface: input
        note: null
        options:
          placeholder: name
        readonly: false
        required: true
        sort: 2
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: name
        table: links
        data_type: character varying
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: links
      field: status
      type: string
      meta:
        collection: links
        conditions: null
        display: labels
        display_options:
          choices:
            - text: Hidden
              value: hidden
              background: '#292929'
            - text: Visible
              value: visible
              background: '#00FF00'
          showAsDot: true
        field: status
        group: null
        hidden: false
        interface: select-dropdown
        note: null
        options:
          choices:
            - text: Hidden
              value: hidden
            - text: Visible
              value: visible
        readonly: false
        required: false
        sort: 5
        special: null
        translations: null
        validation: null
        validation_message: null
        width: half
      schema:
        name: status
        table: links
        data_type: character varying
        default_value: hidden
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
  relations: []
  ```
</details>

Once deployed, attach to the running directus container and try to apply the schema again.

### Directus Version

v10.2

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by br41nslug**
Fixes #18774

Added extra `null`/`undefined` checks to applyDiff which are throwing errors when applying a snapshot twice.

> Wanted to get some extra tests in here for this specific issue but can't find a way to do so without refactoring apply-diff significantly

### CODE REVIEW

**Review by jaads — APPROVED** [review]

**Review by paescuj — APPROVED** [review]

**Comment by co2nunes** [comment]
It only failed on the last test apparently there is no longer more information about the issue.
I hope to have it makes it to the next release. 
Is there a release date or board I can have a look?

**Comment by rijkvanzanten** [comment]
This was added in 10.3.0. We use milestones to mark what releases a PR is in 👍🏻

**Comment by co2nunes** [comment]
@rijkvanzanten Please check the above "x" bc7e92e because it still failing on my Directus 10.3.0 Postgres Database from Development to Staging: 

```
ERROR: Cannot read properties of null (reading 'meta')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'meta')",
      "stack":
          TypeError: Cannot read properties of null (reading 'meta')
              at filterCollectionsForCreation (file:///home//.npm/_npx/ebcc468e2b0f2b61/node_modules/@directus/api/dist/utils/apply-diff.js:101:43)
              at Array.filter (<anonymous>)
              at file:///home//.npm/_npx/ebcc468e2b0f2b61/node_modules/@directus/api/dist/utils/apply-diff.js:122:58
              at /home//.npm/_npx/ebcc468e2b0f2b61/node_modules/knex/lib/execution/transaction.js:221:22
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
```

```
$ node -v
v20.2.0
Docker: 
$ docker version
Client:
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        7155243
 Built:             Mon May  1 21:07:11 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       6051f14
  Built:            Wed Apr 19 00:00:00 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.5
  GitCommit:        f19387a6bec4944c770f7668ab51c4348d9c2f38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Server EC2: uname -a
Linux eu-xxxx-.compute.internal amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jun  6 00:47:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten Sorry to add noise on the queue but please check the above "x" [bc7e92e](https://github.com/directus/directus/commit/bc7e92e4b0512735821aa43aa67280c963184bca) because it still failing on my Directus 10.3.0 Postgres Database from both Development and Staging:

The commit you referenced has seemingly nothing to do with this PR 🤔 Also the X came from the GH actions runner failing to start one of the matrixes in the blackbox tests, which happens from time to time. Every other DB variant reported green, as do newer commits on 10.3 and the current main branch 👍🏻 

Mind opening a new issue?

**Pull request merged**
