### PR TITLE
Write full item to revisions

### LINKED ISSUE #17677: Directus | Flows are not updating the Revision while creating a collection
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I'm using Directus lastest version

 1. I have created a Data Model "Article" with title and Random_order field. 
image

image

 2. I have created an flow which will update a random number into the field "Random_order".
image

image

image

image

 3. The feature is working fine but when i saw the revision history, that revision history is not showing any details about "Random_order" value. It should show the random number 535.
 
image

So the problem is, when we use Directus flow to alter the field value of any Data model, then its not getting recorded in Revision history. 

Currently i'm using the "Filter" type of Directus Flow

### To Reproduce

I'm using Directus lastest version, 9.22. 

 1. I have created a Data Model "Article" with title and Random_order field. 
image

image

 2. I have created an flow which will update a random number into the field "Random_order".
image

image

image

image

 3. The feature is working fine but when i saw the revision history, that revision history is not showing any details about "Random_order" value. It should show the random number 535.
 
image

So the problem is, when we use Directus flow to alter the field value of any Data model, then its not getting recorded in Revision history. 

Currently i'm using the "Filter" type of Directus Flow

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by Nitwel**
Problem: Changes after hooks don't get saved to revisions.

Right now I went with the changes after hooks but we could go even further and also include `payloadWithoutAliases` which is the data that get's inserted into the table. @rijkvanzanten you very likely know what's the right way here.

Fixes #17677

### CODE REVIEW

**Review by paescuj — APPROVED** [review]
Considering the data we had before with `payload` I think `payloadAfterHooks` is just fine 👍

**Review by rijkvanzanten — APPROVED** [review]

**Comment by ananth3087** [comment]
@Nitwel @rijkvanzanten could you please let me know the Directus version in which this fix will be available?

**Comment by ananth3087** [comment]
> > @Nitwel @rijkvanzanten could you please let me know the Directus version in which this fix will be available?
> 
> The next one 👍🏻

@rijkvanzanten  could you please create new Directus version (9.23.2) with all latest fixes? i'm waiting for this fix

**Comment by paescuj** [comment]
> > > @Nitwel @rijkvanzanten could you please let me know the Directus version in which this fix will be available?
> > 
> > 
> > The next one 👍🏻
> 
> @rijkvanzanten could you please create new Directus version (9.23.2) with all latest fixes? i'm waiting for this fix

We can not provide estimates on the timeline for upcoming releases. Thanks for the understanding!

**Pull request merged**
