### PR TITLE
Added getCustomUserClaims

### PR DESCRIPTION
**Pull request by vnmtvlv**
## Description

In directus_users table we have a relation to profiles table, like User{profile: uuid}, we store some information about user there, subscription and so on. It would be great if we can access to it in custom endpoints req.accountability.
Just like {user, role, profile} = req.req.accountability

We can add new env variable ACCESS_TOKEN_CUSTOM_CLAIMS - comma separated user_directus fields.
And then on login (just now only with default provider) add them to tokenPayload.

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by u12206050** [comment]
@j0hnfl0w You can very easily solve this with a hook on `auth.jwt` just use the exact same logic you have in this PR and you should be able to get it working. Within the hook, execute your logic, and return that complete tokenPayload.

If this is what you have been doing, and this PR is purely to support it without the use of hooks, then ok. Although, it can't be guaranteed that the claims you want to add to the payload are available on the `user` object. Some people might want to include claims like membership status or organization which might need to be fetched first.

**Comment by j0hnfl0w** [comment]
Looks like to use custom hook auth.jwt is what i wanted, thank you!

**Comment by j0hnfl0w** [comment]
@u12206050 So using hooks with filter cannot add custom fields to req.accountability :(
```
filter('auth.jwt', (input, ctx) => {
   input.customField = '123'
   return input
})
```

**Comment by u12206050** [comment]
Correct it doesn't add it to accountability but does add it to the tokenPayload in the same way as this PR is doing.

The claims will be available on the JWT access token in your frontend or admin if that is where you wanted to use it.
What else did you have in mind though?

**Comment by j0hnfl0w** [comment]
I need them these custom fields in req.accountability object.
So now I add these fields with filter - auth.jwt
And with filter - authenticate I parse jwt token and add custom fields to customClaims.

**Comment by rijkvanzanten** [comment]
> I need these custom fields in req.accountability object.

That's not what this PR does though 🤔 This PR adds it to the payload of the JWT that's being generated for use, but doesn't then re-add those custom JWT claims into the req.accountability object in use.

As of right, I wouldn't rely on adding custom things into the accountability object, as that accountability object can be created from multiple sources (and therefore may or may not have access to the fields you expect). Lets open a new feature request Discussion so we can discuss what the actual use case is, discuss what the ideal solution is, and then circle back to the actual implementation 👍🏻

**Pull request closed without merging**
