### PR TITLE
Add support for split rollup configuration for different modes

### PR DESCRIPTION
**Pull request by hanneskuettner**
## Scope

Add the option to split `extension.config.js` file for the two different rollup modes we use: `extension.config.node.js` and `extension.config.browser.js`.

I stumbled over this while developing a bundle extension that uses dependencies that have different [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) for different bundling environments and require the `node-resolve` plugin to be configured differently for API and app extensions.

For example I need to be able to use this configuration for node:

```js
import { nodeResolve } from "@rollup/plugin-node-resolve";

export default {
  plugins: [
    nodeResolve({exportConditions: ["node"]})
  ]
}
```

and this for the browser:

```js
import { nodeResolve } from "@rollup/plugin-node-resolve";

export default {
  plugins: [
    nodeResolve({exportConditions: ["browser"]})
  ]
}
```

which would import the correct dependencies for each environment that are exported with export conditions.

What's changed:

- Added the possibility for the extension developer to specify different `extension.config` files for the two different modes in which we currently use rollup `node` and `browser`. This is fully backwards compatible, as it defaults to no mode suffix, but prefers configuration files with the mode suffix.
- You can now have the configuration files `extension.config.node.js` and `extension.config.browser.js` and they will be considered for their applicable environment
- Improved the DX with this, yeah!

## Potential Risks / Drawbacks

- None, since fully backward compatible

## Review Notes / Questions

- N/A

---

Fixes a problem I currently have...

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Review by nickrum — COMMENTED** [review]
When I implemented support for extension config files, I had the idea to allow the default export inside the config to be a function that returns the config object and that receives the extension type and the other options as parameters, but I never got around implementing it. This would support the exact same use case and might be a little more flexible. Thoughts?

**Comment by hanneskuettner** [comment]
> When I implemented support for extension config files, I had the idea to allow the default export inside the config to be a function that returns the config object and that receives the extension type and the other options as parameters, but I never got around implementing it. This would support the exact same use case and might be a little more flexible. Thoughts?

I like that more, thank you for pointing that out! Let me quickly figure that our and open another PR for that so we can decide with which one to go.

Huh is this why we do issues first, so these thinks don't need to be pointed out in PRs?

**Comment by rijkvanzanten** [comment]
> Huh is this why we do issues first, so these thinks don't need to be pointed out in PRs?

˚₊‧꒰ა _yes_ ໒꒱ ‧₊˚

**Review by binaryben — COMMENTED** [review]
I'm happy to add my stamp of approval to this. Are we holding off on merging until the alternative PR is published for discussion though?

**Comment by rijkvanzanten** [comment]
> Are we holding off on merging until the alternative PR is published for discussion though?

Yup! I don't want to ship this and then immediately remove it again in favor of a different solution 👍🏻

**Comment by rijkvanzanten** [comment]
Closing this to be revisited later.

**Pull request closed without merging**
