### PR TITLE
Replace raw templates deeply when applying data to options

### PR DESCRIPTION
**Pull request by nickrum**
## Description

This should get rid of a lot of the friction and confusion around passing values between operations in a flow.
When using a raw template string (a mustache template with a single interpolation and nothing else e.g. `"{{ $last.data }}"`) inside a nested structure like an array or object, the value is now passed as is instead of being stringified to json.

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by erondpowell** [comment]
please ping me when this gets merged and I will give the new system a whirl to make sure docs are in sync. Thanks 🙏

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
@nickrum ready to merge?

**Comment by erondpowell** [comment]
FYI @azrikahar @nickrum the app has some imbedded examples of how to use the `{{ opKey }}` syntax . Should any of these get updated?

Screen Shot 2022-10-26 at 12 02 03 PM

**Comment by azrikahar** [comment]
> FYI @azrikahar @nickrum the app has some imbedded examples of how to use the `{{ opKey }}` syntax . Should any of these get updated? This is from "log to console"
> 
> Screen Shot 2022-10-26 at 12 02 03 PM

I believe they are still correct 👍 This change is more related to the output/result rather than the syntax (which is still the same) as described in https://github.com/directus/directus/discussions/15945#discussioncomment-3861135.

Though I do notice there's a stray single quote at the end after the period thanks to your screenshot, so that should probably be removed.

**Pull request merged**
