### PR TITLE
Flatten oauth user profile so we can use sub-values

### PR DESCRIPTION
**Pull request by aidenfoxx**
Fixes issues with providers that return user data in a sub-object like Twitter:

```
{
  data: {
    id: "123456",
    ...
    username: "SomeGuy"
  }
}
```

Now we can use `AUTH_TWITTER_IDENTIFIER_KEY="data.username"` to access the identifier correctly. Verified working with Twitter using the following config:

```
AUTH_TWITTER_DRIVER="oauth2"
AUTH_TWITTER_CLIENT_ID="..."
AUTH_TWITTER_CLIENT_SECRET="-..."
AUTH_TWITTER_AUTHORIZE_URL="https://twitter.com/i/oauth2/authorize"
AUTH_TWITTER_ACCESS_URL="https://api.twitter.com/2/oauth2/token"
AUTH_TWITTER_PROFILE_URL="https://api.twitter.com/2/users/me"
AUTH_TWITTER_IDENTIFIER_KEY="data.username"
AUTH_TWITTER_SCOPE="tweet.read users.read"
AUTH_TWITTER_ICON="twitter"
```

NOTE: Twitter doesn't return an email. Use "username" as an alternative.

(I also ninja'd in the ability to define a first/last name key in oauth 🤫)

### CODE REVIEW

**Review by StobyWan — APPROVED** [review]
Code looks great, I like how it was handled, will you add new oauth props to docs?

**Comment by aidenfoxx** [comment]
I tend to make my PRs on my lunch breaks so, documentation usually gets skipped. 😅 

I'll probably make a new PR to update the docs with all the new config variables I've ninja'd in over time.

**Comment by StobyWan** [comment]
can I help move this one into next build?

**Comment by aidenfoxx** [comment]
@rijkvanzanten I think the pipeline fail was unrelated to the code if you're able to re-trigger it. Other than that it's a fairly minor change.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
