### PR TITLE
Adding editor to image component

### PR DESCRIPTION
**Pull request by juancarlosjr97**
Adding a new button to edit images directly from collection 

Related to https://github.com/directus/directus/pull/6340

### CODE REVIEW

**Comment by juancarlosjr97** [comment]
Thank you @azrikahar I ran the locally but was not showing the same errors as the CI, I was going to look into it today, but thank you for doing it in advance :)

**Comment by azrikahar** [comment]
No worries! Thanks for all the PRs as always 👍

**Comment by qborisb** [comment]
Additionally, with this implementation, image preview is not being updated once the crop is made. 
For it to work, the computed `src` property needs to be changed, so that image URL gets updated when the image gets cropped.

**Comment by qborisb** [comment]
Hello!
Should've mentioned it before starting the review: made a review as requested in the [following discussion](https://github.com/directus/directus/discussions/14395) :)

**Comment by juancarlosjr97** [comment]
Hey @qborisb, happy to share access to the repository so you can continue the MR, I do not have enough time right now, but happy it can be merged, it would be great :)

**Review by rijkvanzanten — APPROVED** [review]

**Comment by juancarlosjr97** [comment]
Awesome it got merged, thank you for the additional work everyone :)

**Comment by qborisb** [comment]
@rijkvanzanten Thanks a lot, I am very happy that this PR got merged :)

There is still one bug left though - the image preview does not get updated after you edit the image. If you refresh the page, it gets updated. I know how to fix the issue, so I would be happy to create a PR for it :)

**Comment by rijkvanzanten** [comment]
Go for it! @qborisb

**Pull request merged**
