### PR TITLE
Add options to configure delimiter & unicode support on CSV export

### LINKED ISSUE #15874: Format of CSV Import (Configuration of Delimiter / Separator)
### Describe the Bug

Unfortunately, it is not possible to import the data in a slightly different format. For example, it is not possible to use the column separator semicolon (`;`), which is common in Germany.

I am very impressed with the software and would love to use it for our customers.

Found this discussion: #12456

Am I missing an configuration? Once this is planned, can I help develop it with an MR?

Many Thanks.

### To Reproduce

1. Create CSV file
2. Import Example
    ```
   "Col1";"Col2"
    "foo";"bar"
    ```

### Errors Shown

CSV Format Error.

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

Docker bundled version

### What database are you using?

MySQL v8

### What browser are you using?

Unimportant

### How are you deploying Directus?

Docker

### LINKED ISSUE #16818: No UTF-8 (special characters) on CSV export
### Describe the Bug

When exporting items from a collection (to a CSV file), special characters are replaced with weird characters - in my use case there are Norwegian specific characters.

I know CSV does not support UTF-8 characters by default but there is also a similar filetype called CSV UTF-8 (Comma delimited) which should support "special characters".

### To Reproduce

Export an item from a collection which contains special characters in the field value.

### Errors Shown

_No response_

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 14.4.1

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by paescuj**
## Description

Closes #16818, addresses #12456

Need to clarify / clean-up a few things before ready for merging.

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by cs1m0n** [comment]
Any update on this? 🙏

**Comment by paescuj** [comment]
@cs1m0n This needs more work. I might be able to look at it the next days.

**Comment by rijkvanzanten** [comment]
Closing this for now to be revisited later 👍🏻

**Comment by idmansourali** [comment]
Hi, is there any update on this please?

**Comment by LevelUpGit** [comment]
Hope it comes soon.

**Pull request closed without merging**
