### PR TITLE
Group groups in field select, add search when number of fields exceeds 20

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Groups grouped fields in the various field dropdowns for improved organization in field selection.

Partially implements https://github.com/directus/organization/issues/65

CleanShot 2022-03-15 at 12 59 33@2x

https://user-images.githubusercontent.com/9141017/158431531-77b490ab-1201-46d7-a635-ea7bcfad26bc.mov

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
One to-do before merging:

- [ ] Verify / fix that nested relational fields _in_ a group field can still be expanded

**Comment by u12206050** [comment]
Think this PR is breaking quite a few things. Maybe revert it until fixed?

**Comment by rijkvanzanten** [comment]
> Think this PR is breaking quite a few things. Maybe revert it until fixed?

Could you elaborate on what things? There was the key issue on the nested group path, but you already resolved that in the other PR.

**Comment by u12206050** [comment]
Trying to set the display value of a field that is within a group doesn't work anymore. Will open an issue.
Sorry no reason to revert it :) Just some new bugs that need squashing

**Comment by u12206050** [comment]
Here is the fix #12285

**Pull request merged**
