### PR TITLE
fix search errors 

### LINKED ISSUE #17946: Search error
### Describe the Bug

You have table (collection): id (int), params (string)
If you try to find big value in this table (collection) - you catch the error

```json
 {
  "errors": [
    {
      "message": "select \"collection_name\".\"params\", \"collection_name\".\"id\" from \"collection_name\" where ((\"collection_name\".\"id\" = $1) or LOWER(\"collection_name\".\"params\") LIKE $2  order by \"collection_name\".\"id\" asc limit $12 - value \"710406684325\" is out of range for type integer",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

create collection with id (int) and field test (string)
try to find big value in this table (collection) - you catch the error

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by Zack-Heisnberg**
## Description

Using raw instead of direct where to ignore out of range errors

https://github.com/directus/directus/issues/17946#issuecomment-1484351227

https://github.com/directus/directus/issues/17946#issuecomment-1484895566

to reproduce use postgressDB with a field int4 try any number out of range for a 4 byte field  > 2147483647 , 
the issue happens also on float with very big numbers ( out of range for type real )

Fixes https://github.com/directus/directus/issues/17946

https://github.com/directus/directus/issues/15809
https://github.com/directus/directus/issues/14638

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by Zack-Heisnberg** [comment]
> As per your comment on the original issue:
> 
> > in the other hand using where ( orWhere ) is the equivalent of the following code , the code will perform checks internally using the ( libpq library ) , and show the out of range error
> 
> If it's Postgres itself that throws that error, should we hack around it with a `raw` query? I'd assume there's a good reason for the database to deny an integer for search it knows is too big for the datatype thinking

the issue here is not on the Postgress server , trying to  run the Exact query the code is generating in the apply search  directly in psql or pgAdmin  will run without errors , and without any performance issues 

image

in fact the way the server side works When we compare the "sort" column to a value that is too large to fit into an int4 data type, the database will perform an implicit data type conversion. The value 2000000000000000000000000000 is too large to fit into an int4 data type, so the database will convert it to a bigint data type, which can accommodate larger values and act like CAST  in comparing , 
only if we try to insert a value that is too large for the data type, we will get an "out of range for type integer" error.


but it's the  pg driver  that  give the error , because even though the query is  syntactically correct and can be executed by the database. if we are simply trying the following

const failedQuery = "SELECT * FROM " + collection + " WHERE " + collection + "." + name + " = $1";
pool.query(failedQuery, [number], function(err, rows) {
  if(err) throw err
  console.log(rows)
  pool.end()
})

the pg driver knows that the sort is int4 and the value can't be parsed  , so the query will always return 0 results ,  so it's throws the error when trying to parse the number value to the data type 

but  in our case we have different fields , and since there is no sql injection risk and no performance issues we can simply use the raw here , this will make parsing number values pass directly on server side and doesn't throw errors as long as we already checking with isNaN

the mysql driver let the server handle it this is why it's not giving issues 

i tried this alternative way is to  check values on directus side
it's worked for integer using the Number.isSafeInteger(number) 

```
} else if (['bigInteger','decimal', 'float'].includes(field.type)) {
				const number = Number(searchQuery);
				if (!isNaN(number)) 
                                              this.orWhere({ [`${collection}.${name}`]: number });
} else if (['integer'].includes(field.type)) {
				const number = Number(searchQuery);
				if (!isNaN(number) && Number.isSafeInteger(number)) 
                                              this.orWhere({ [`${collection}.${name}`]: number });
```
however , i had a string and integer and other different field ( float with precision set to 25 ) on very big numbers i get 
out of range for type as well for the float field this time , so  it's will be harder to check each field and do all the integrated checks that the pg lib is doing , 

and since it's the same query with knex so either it's will fail because that single field or success only when all checks pass so we can't like set it to ignore errors 
i think it's the best way to use the raw

**Review by azrikahar — COMMENTED** [review]
Some thoughts/questions after revisiting this PR now:

- Should we do this using helpers, such that other vendors can remain with the original approach?
- With or without using helpers, we should probably have a blackbox test for this scenario to verify if it is indeed Postgres being the _sole_ outlier here.

**Comment by br41nslug** [comment]
Judging from the comments it sounds like we're going to take a different route for this fix :) Converting this to draft for now to prevent confusion

**Comment by paescuj** [comment]
Thanks for your pull request! However a potential fix for the issue should meet the criteria now outlined in https://github.com/directus/directus/issues/17946#issuecomment-1531734100. Therefore I'm going to close this pull request for now. Thank you for your understanding!

**Pull request closed without merging**
