### PR TITLE
Update Docker image to execute as a non-root user

### PR DESCRIPTION
**Pull request by t7tran**
Just a minor update to Docker image build to allow its container to run as a non-root user following container best practices.

### CODE REVIEW

**Comment by paescuj** [comment]
Thank you for your changes which I really endorse!
I think we could even do some further improvements here:
* Change the permission for the `entrypoint` and `print` scripts directly in Git and move the `WORKDIR /directus` instruction right after the `USER node` instruction so we could omit the `RUN chmod +x /usr/bin/entrypoint && chmod +x /usr/bin/print
&& chown node:node /directus` step in the Dockerfile.
  Note: Each 'RUN' step creates a new layer which should be kept as low as possible - see [Minimize the number of layers](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers)
* Remove the following step for the same reason as above: https://github.com/directus/directus/blob/b8eb64e12f46475d8f0a7ff80d4b2ead64e60ab0/.github/actions/build-images/rootfs/directus/images/main/Dockerfile#L22
* Locally installed binaries should actually be placed in `/usr/local/bin` instead of `/usr/bin`
* I'm not sure whether 'bash' is really required in the `builder` image. It was probably added for the loop which could be replaced by `for i in $(seq 60)`. At the same time I would reduce the loop to maybe 10 tries which would still mean 5min of waiting in the worst case...:
  https://github.com/directus/directus/blob/b8eb64e12f46475d8f0a7ff80d4b2ead64e60ab0/.github/actions/build-images/rootfs/directus/images/main/Dockerfile#L9-L12 https://github.com/directus/directus/blob/b8eb64e12f46475d8f0a7ff80d4b2ead64e60ab0/.github/actions/build-images/rootfs/directus/images/main/Dockerfile#L20

Please note that the "non-root user" change is potentially a breaking change for some Directus users since files in the Docker volumes are currently owned by root. Maybe we should add a note somewhere.

**Review by rijkvanzanten — APPROVED** [review]
Changes LGTM, but I'm not Docker expert 😁 

Shall we apply those changes immediately on this PR @paescuj?

**Comment by paescuj** [comment]
@rijkvanzanten Yes, I'm going to add the suggestions to this PR 😃 

Have done quite a lot "Docker stuff" and changes LGTM/should be safe, except as I mentioned it would mean some users must change the owner of files in their Docker volumes.

**Comment by rijkvanzanten** [comment]
> it would mean some users must change the owner of files in their Docker volumes.

Is that something we can do automatically? 🤔

**Comment by paescuj** [comment]
> > it would mean some users must change the owner of files in their Docker volumes.
> 
> Is that something we can do automatically? 🤔

Hmm, unfortunately not. When merging this PR the container will be started with user 'node' right-away so we won't have enough rights to change the owner from 'root' to 'node'.

**Comment by paescuj** [comment]
@rijkvanzanten Sorry, I don't have enough permissions to update this PR...

**Comment by rijkvanzanten** [comment]
Ohh right right.. Let me merge this into a new branch under `directus/directus`, and then you can PR on that 👍🏻

**Comment by rijkvanzanten** [comment]
@paescuj It's on `docker-updates` :

**Comment by paescuj** [comment]
@rijkvanzanten Thanks!

**Comment by t7tran** [comment]
@paescuj I've updated my PR branch with responses to your comments below:
- Permission in git: I don't see this as a huge issue as the size increase for those will be negligible; and can be done in a separate PR/task
- Cat step removal: I don't know what this does but it's harmless for the staging image as it won't end up in the final image
- local binary should be under `/usr/local/bin`: agreed but again harmless IMHO in this context
- bash in builder: again, harmless in the builder stage
- permission to existing volumes: yes it isn't ideal situation but the sooner this is done, the better. People can still run docker with `root` at their own risk, or update the volumes' permission once.

I have squashed all RUN statements down to two. Usually, I would only have one with the help of `gosu`. Please let me know if you'd like to go this far.

@rijkvanzanten I presume I don't have access to `docker-updates` branch so my latest commit will need to be reviewed and merged from the original branch.

**Comment by rijkvanzanten** [comment]
I can't give users access to specific branches I don't think. You should be able to open a new pr on that branch using your existing fork/branch though 👍🏻

**Comment by Attacler** [comment]
How to update docker containers that have the volumes marked as root?
right now directus does not have write access in /uploads on one of my instances

**Comment by paescuj** [comment]
@Attacler See https://github.com/directus/directus/discussions/6480#discussioncomment-917708

**Pull request merged**
