### PR TITLE
Cache GraphQL POST queries

### LINKED ISSUE #11418: GraphQL POST requests are not cached
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

GraphQL requests will not be cached nor returned from cache when using `directus/sdk` or Directus docs information. 

Directus implementation caches only GET requests:
`api/src/middleware/respond.ts:17`
image

Also, cache key for GraphQL post requests will be always the same irregardless of variables / query:
`api/src/utils/get-cache-key.ts:13`
image

Contrary to docs (where `POST /graphql` is suggested), implementation of `api/src/middleware/graphql.ts` requires (or suggests) GET requests to fetch data. 

### To Reproduce

1. Run Directus
2. Use SDK or use `POST /graphql` to get data
3. Cache is not used at all (for example monitor redis).

### Errors Shown

_No response_

### What version of Directus are you using?

9.4.3 (but code does not change for 9.5.0)

### What version of Node.js are you using?

N/A

### What database are you using?

N/A

### What browser are you using?

N/A

### What operating system are you using?

N/A

### How are you deploying Directus?

N/A

### PR DESCRIPTION
**Pull request by viters**
Resolves https://github.com/directus/directus/issues/11418

### CODE REVIEW

**Comment by CoenWarmer** [comment]
Would love to have this, anything we can do to get this merged @rijkvanzanten @viters?

**Comment by viters** [comment]
@CoenWarmer 
I can resolve conflicts if @rijkvanzanten is ready to merge this and will prompt me to fix it.

Although, as we've discussed in different topic, POST queries will not be cached by browser. So if your GQL queries are not that big, you can use GET instead of POST, you will have caching in current Directus version (it works flawlessly) and browser will cache your queries as well.

All you need to do is to extend Directus class from SDK and write your own GraphQLHandler, which uses GET requests instead of POST. Remember to properly stringify your query and variables.

**Comment by benhaynes** [comment]
Thank you, @viters!! We've been slammed the past few months (wrapping up the free cloud tier and sponsored work), but are finally back on Core... you may have noticed we closed ~100 issues and merged 20+ PRs in the past week or so. I'm sure @rijkvanzanten will be able to provide some feedback this upcoming week, and (hopefully) we can get this merged!

Again, we appreciate the contribution! ❤️

**Comment by viters** [comment]
@benhaynes 

Yeah, I just today reviewed recent releases change log and I am really impressed by the speed of introducing changes and new functions. Directus is really fast growing.
By any means I did not want to sound offensive in "_I can resolve conflicts if @rijkvanzanten is ready to merge this and will prompt me to fix it_" - that was just plain statement of me being ready to act when required ^^

**Comment by CoenWarmer** [comment]
@benhaynes you guys have been really nailing it over the past few months! Love to see the community interaction and the extremely fast turnaround on issues. Kudos!

**Comment by benhaynes** [comment]
Thank you both! We're really excited for some solid stability and big updates coming... good to be back on Core!

> By any means I did not want to sound offensive in "I can resolve conflicts if @rijkvanzanten is ready to merge this and will prompt me to fix it" - that was just plain statement of me being ready to act when required ^^

No worries at all, I understand. We felt horrible letting some PRs sit for so long without feedback. Growing pains. No offense taken... we owe you a review. 👍

**Comment by rijkvanzanten** [comment]
I think this can be simplified quite a bit by simply allowing `/graphql` to be parsed by the caches at all times, and then setting `res.locals.cache = false` in the graphql controller when a mutation is detected 🤔 

Created a draft PR with that implemented, curious to hear your thoughts @viters @CoenWarmer: https://github.com/directus/directus/pull/14371/files

**Pull request closed without merging**
