### PR TITLE
Support global installation and add update check

### PR DESCRIPTION
**Pull request by msaaddev**
In this PR, I have addressed #6794. The user will now be able to globally install the CLI and use it. Also, if there is an update available, they will get notified when they run the CLI.

P.S. I have not updated the version.

### CODE REVIEW

**Comment by msaaddev** [comment]
@rijkvanzanten @benhaynes kindly take a look!

**Comment by benhaynes** [comment]
Thanks, @msaaddev — we'll review asap... appreciate the PR!! 🙂

**Review by rijkvanzanten — APPROVED** [review]
Makes me think, should we do this in Directus itself on startup? Would be nice to show a little 

"⚠️ New version available (v9.4.1)"

message on startup 🙂

**Comment by benhaynes** [comment]
> Makes me think, should we do this in Directus itself on startup? Would be nice to show a little
> 
> "⚠️ New version available (v9.4.1)"
> 
> message on startup 🙂

Ooh, I like that!

**Comment by benhaynes** [comment]
> Makes me think, should we do this in Directus itself on startup? Would be nice to show a little
> 
> "⚠️ New version available (v9.4.1)"
> 
> message on startup 🙂

Ooh, I like that!

**Comment by msaaddev** [comment]
> Makes me think, should we do this in Directus itself on startup? Would be nice to show a little
> 
> "⚠️ New version available (v9.4.1)"
> 
> message on startup 🙂

Do you mean in Directus CLI? Also, It is quite possible. And if you want, I can go ahead and take care of it as well.

**Comment by rijkvanzanten** [comment]
The CLI under the `api` folder, yeah. So when you start Directus using `npx directus start`, it'll show the warning when applicable 🙂

**Comment by msaaddev** [comment]
Makes sense. Should I go ahead and open a PR for this.

> The CLI under the `api` folder, yeah. So when you start Directus using `npx directus start`, it'll show the warning when applicable 🙂

**Comment by rijkvanzanten** [comment]
Sure! Lets do it in here, so it's shown regardless of how you're starting up directus:

https://github.com/directus/directus/blob/aa71420ab1630905b440b3f2932749533ae4319c/api/src/start.ts#L21

**Comment by msaaddev** [comment]
> Sure! Lets do it in here, so it's shown regardless of how you're starting up directus:
> 
> https://github.com/directus/directus/blob/aa71420ab1630905b440b3f2932749533ae4319c/api/src/start.ts#L21

Alright. I will take care of it.

**Pull request merged**
