### PR TITLE
Clean-up docker image

### PR DESCRIPTION
**Pull request by paescuj**
⚠️ **Notice**:

This changes the user that owns the volumes from `root` to `node`. This change might affect your existing installation  depending on your usage of the Docker Image.

---

Thanks @t7tran!

Based on https://github.com/directus/directus/pull/5801 and https://github.com/directus/directus/pull/5833

* Contains the change from @t7tran to run the container with the user 'node' instead of 'root'.
  * As already mentioned before:
    > Please note that the "non-root user" change is potentially a breaking change for some Directus users since files in the Docker volumes are currently owned by root. Maybe we should add a note somewhere.
* Clean-ups as described in https://github.com/directus/directus/pull/5801#issuecomment-845964089
* Additional clean-ups (would be great if @WoLfulus could confirm those changes 😃):
  * Update versions in package.json which is used for the image, remove yargs as it is already installed globally (I think we don't need it here, right?): https://github.com/directus/directus/commit/fce2fb6180e741e8aefd219fbeb9cdd3938e088a
  * Remove first stage image (`builder`) as it is simply unnecessary and move installation of Directus to actual image: https://github.com/directus/directus/commit/1c8601ad749000874061e5045fc80c6138edad5b
  * Some other small changes: Don't cache apk packages, add a few comments and move EXPOSE and SHELL instructions to bottom (as suggested by @t7tran and seen in most Dockerfiles)

Also I asked myself:
* Would there be another / a better way to "automatically" keep the versions in the docker `package.json` file in sync with the one from `api/package.json`...
* Is [util-linux](https://github.com/directus/directus/pull/5877/files#diff-f868a0a80eb92541d2ad8435073c187d9c0c1fbac1e3ed83f256443e90b10f41R39) really required?

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
@WoLfulus Looks good to you?

**Comment by WoLfulus** [comment]
Yes, some of the question I'll be adding myself in a new PR

**Review by WoLfulus — APPROVED** [review]

**Comment by AKockWorth** [comment]
> This change might affect your existing installation depending on your usage of the Docker Image.

It does, and it did. And it's quite an annoying one to fix with k8s virtual disks used as mounted volumes. Please be more careful of these changes in the future and provide a scripted migration path. i.e.: Add an entrypoint script that can `sudo chown -R node:node` on the directories that might be mounted externally.

**Comment by t7tran** [comment]
Two comments from me:

- I don't think the team at Directus would ever make an inconsiderate change. It was a serious bad practice to run containers as root user and the change was made rather now than later.
- Since the container runs as non-root, it won't be able to do it on your behalf.

We're running Kubernetes everywhere on clouds and on-prem including air-gapped environments, so I feel your pain as we ran into similar situations before (with persistence volume permission). So if one thing could have been done better was a transitive version which runs as root but the process and includes the `chown` step. However, we will find that someone will just jump to the latest version and come back to complain.

Among lots of other great things that Directus team has brought together, I would let this slip through. By the way, this is nowhere near the frustration of upgrading our extensions to Vue 3.

**Comment by rijkvanzanten** [comment]
@AKockWorth hence the big warning notice at the top of the readme:

> ## 🚧 Release Candidate
> 
> This is pre-release software. While we're providing migrations between versions, changes may occur at any time, and certain features might be missing or broken. You can follow along with the issue tracker for an in-depth list of upcoming enhancements.

We're aware that there might be a couple changes that could be considered breaking changes in certain use cases while we're finishing up how things _should_ work exactly, which is why we've marked the current versions as pre-release 👍🏻

**Pull request merged**
