### PR TITLE
Add select all and delete buttons for notifications drawer

### LINKED ISSUE #23440: Delete notifications from App
### Describe the Improvement

And I'm back with another tiny issue regarding notifications: Currently there's no way of deleting notifications via the app.

I'd expect to have a third `delete` button at the top of the notification-actions. 

Related to [#22265(comment)](https://github.com/directus/directus/issues/22265#issuecomment-2298753869) there could be either a `delete all` or an `select all` button in combination with a second buttton to delete the selected ones

### PR DESCRIPTION
**Pull request by NickSettler**
## Scope

Notification drawer header action buttons changed. They allow to select / deselect notifications in inbox and archived notifications views. Delete and archive buttons executing their actions for the selected notifications.

What's changed:

- Removed archive all button
- Added select all / deselect all checkbox
- Added delete button

## Potential Risks / Drawbacks

- I don't see any

## Review Notes / Questions

- ...

---

Fixes #23440

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Thanks @NickSettler! Bit.. opinionated though 😁 I wouldn't want to lose the ability to archive notifications first. Maybe there's a world where we keep the "Archive" interaction on the inbox, and put the "Permanently Delete" button there when you're looking at the archive? 🤔

**Comment by NickSettler** [comment]
> Thanks @NickSettler! I wouldn't want to lose the ability to archive notifications first. Maybe there's a world where we keep the "Archive" interaction on the inbox, and put the "Permanently Delete" button there when you're looking at the archive? 🤔

Do you mean having the delete button only when the archived notifications view is displayed? I thought of the conversation in the issue that both buttons at the same time in the inbox view would be useful. That's how it looks now on this branch in the inbox view for example:

image

**Comment by rijkvanzanten** [comment]
Hm yeah that could work! I'd say lets move the select-all button to be an inline-link above the list itself as it's less of a "primary action", and then do it this way where both buttons exist at the same time 🙂 Archive could be the 'primary' (eg right-most) action, with delete being present next to it 👎🏻

**Comment by rijkvanzanten** [comment]
This is feeling really good now. Thanks @NickSettler! ❤️ The only small tweak I wanna make is to leave the tooltip identical and rely on the button disabled state for the not-allowed communication to be consistent with how that works in the rest of the app, but that's a small tweak I'll push over the finish line now 🙂

**Comment by rijkvanzanten** [comment]
Now seeing that the second half of my previous comment didn't happen in this PR, so lets not over-rotate and scope-creep in this PR 🙂 Changes LGTM!

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
