### PR TITLE
 Use same ordering of script props across all components

### PR DESCRIPTION
**Pull request by paescuj**
- Following official docs: https://vuejs.org/guide/typescript/composition-api.html#typing-component-props
- For the sake of consistency, e.g. so that it's easily "grep-able"

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
Next up: put script before template? 🥸👀

**Comment by paescuj** [comment]
> Next up: put script before template? 🥸👀

Hmmm 😄 No plans in this regard from my side. What do you think would speak for it? I personally prefer to have the template at the top because that is what ultimately defines a component.

**Review by jaads — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
> Hmmm 😄 No plans in this regard from my side. What do you think would speak for it? I personally prefer to have the template at the top because that is what ultimately defines a component.

I agree, which is why we've done it like that in the past. However, Vue's "standard" format nowadays seems to be script first! 👀

**Comment by paescuj** [comment]
> I agree, which is why we've done it like that in the past. However, Vue's "standard" format nowadays seems to be script first! 👀

Oh right, interesting! I wonder what their reasons for this are 👀

**Pull request merged**
