### PR TITLE
Improve translation string performance

### LINKED ISSUE #15501: Translation string performance
### Describe the Bug

In projects with many translation strings, there's a UI blocking delay every time the Directus app loads in the browser (logging in, opening a Collection Item in a new tab, etc. The delay is caused when parsing the strings, not the network API request to retrieve the translation string values. 

I think the translation strings should be aggressively cached, and not re-requested or parsed every time Directus is opened a tab/window. 

 

### To Reproduce

1. Create many translation strings (like localized values for a large checkbox tree, for example)
2. Observe the impact on performance waterfall in browser dev tools

### Errors Shown

None

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.17

### What database are you using?

MySQL

### What browser are you using?

Chrome, Safari on macOS

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

Translation string performance improvements using the JSON Query feature. In the current state with a lot of translation strings ~the app will slow down significantly~ ([mitigated in this PR](https://github.com/directus/directus/pull/16038)) and the translation strings management page will use an exorbitant amount of compute and memory or just break the tab if unable to do so.

This PR adds the following:
- A migration to update the current `translation_strings` content to a more queryable structure.
- Replaced the hydration of translation strings to only fetch the current language.
- Updated the translation strings setting page to use the new structure and added virtual pagination.

## Demo

**Before**

https://user-images.githubusercontent.com/9389634/212737360-aff4a1a9-6420-4675-8970-5a43a90dc812.mp4

**After**

https://user-images.githubusercontent.com/9389634/212735658-e47a78a8-5f99-4a41-8ab5-4dbc435d10f9.mp4

## Tested

I've attempted to test the following translations list [translation_strings.json.gz](https://github.com/directus/directus/files/10412226/translation_strings.json.gz) in the following vendors: mysql5, sqlite3, postgres 14, mssql 2019, oracle 18.
The following vendors seem to some limits lower than expected:
- mysql5 ran into a default max query size of 4mb (worked when sizing the list down a little)
- oracle seems to have a max of 4000 characters on the translation_strings field (that should be higher i think)
- also ran into the Directus `MAX_PAYLOAD_SIZE` and had to increase that to work with this dataset

Fixes https://github.com/directus/directus/issues/15501
Fixes ENG-193

## Type of Change

- [X] Bugfix
- [X] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [x] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

### CODE REVIEW

**Comment by br41nslug** [comment]
I'm not yet marking this as "ready for review" because if it would get merged into the json query branch that would make reviewing that PR more difficult.

**Comment by br41nslug** [comment]
Marking as "ready for review" but please dont prematurely merge as that only makes reviewing the blocking PR https://github.com/directus/directus/pull/15889 more difficult

**Comment by br41nslug** [comment]
The system translation interface was missed in this implementation. And an issue discovered when using SQLite

**Review by licitdev — APPROVED** [review]
Works as intended by only importing all translations strings when necessary.

**Comment by br41nslug** [comment]
closing this stale PR in favor of https://github.com/directus/directus/pull/18097

**Pull request closed without merging**
