### PR TITLE
Add System token interface

### PR DESCRIPTION
**Pull request by azrikahar**
Closes directus/organization#106

## Motivation

Enhance security for static access tokens by using `conceal` (it will be redacted, similar to how password field currently shows up in the App or when it's value is returned via API).

## Result

Initially logs in as a user with Regular role that has recommended defaults permissions, then logs in as an admin to showcase the token regeneration and interactions.

https://user-images.githubusercontent.com/42867097/170420292-fa2c7ce5-2d9f-44d0-8f13-70c9945c5a6b.mp4

### CODE REVIEW

**Comment by azrikahar** [comment]
> @azrikahar What's left to-do to get this out of draft? 🙂

Was a mix of wanting to do an additional pass from non-admin user perspective (fixed it's interaction and disabled state just now!) as well as awaiting for any feedback/changes required 👍 Marking this as ready to review now.

**Comment by jaycammarano** [comment]
Reviewing/testing now.

So in your video is "regular@example.com" granted admin privileges still?

**Review by jamescammarano — APPROVED** [review]
Tested through the app manually:
- admin setting a token for themselves. a regular user can not see the admin.
- admin setting a token for another user
- refreshing the token
- non-admin users can't set their own token
- Tested using the token on GQL+REST items(POST/GET) and `user/me`(GET/PATCH) endpoints

It also doesn't break any previously set tokens. Can't think of other scenarios.

Using `/utils/random/string` was a good idea.

**Comment by stx-chris** [comment]
Unfortunately this breaking change rendered our app unusable. For our use case, the user token represented a personal but anonymous path in our app. We statically render all paths to speed up performance whenever a user signs in. As the token for the users is generated by another app, we cannot use the user's id as a path instead.

Now during the static rendering procedure, all we get back from the users interface is a bunch of stars "*" for the tokens, which means we cannot generate any user paths at all. **Is there an option or query parameter we could provide to the SDK/Postman to reply the token in plain text instead?**

**Comment by rijkvanzanten** [comment]
@stx-chris There's currently no way to circumvent the obfuscation of password/token in the API. Feel free to open a new feature request and we can keep discussing 👍🏻

**Comment by stx-chris** [comment]
> @stx-chris There's currently no way to circumvent the obfuscation of password/token in the API. Feel free to open a new feature request and we can keep discussing 👍🏻

Thx @rijkvanzanten, in addition to the token field we decided to use the user's title field for our special use case. So no need for a feature request; thx anyway for your quick response!

**Comment by rijkvanzanten** [comment]
Glad to hear that @stx-chris! You can also add any custom fields into the users table if you prefer using a more dedicated interface/type for that value, but I'm glad to hear you're no longer relying on the access token for that 👍🏻

**Pull request merged**
