### PR TITLE
Replace template with p element

### LINKED ISSUE #18842: Export hangs UI
### Describe the Bug

When entering 6000 items into the items to export, the notice changes icon, but still states that the export will be downloaded to my device once completed.

However, once I start the export I soon get an email (with nothing in it, another issue) but then also nothing happens on the admin ui side of things, not file gets downloaded or anything. It just hangs and I can't even close the modal. Only way to escape is by refreshing.

### To Reproduce

Start and export of 6000 items, wait a bit at first, ideally until after you get notified by email that export is finished.

Try and navigate / close / or view any files being downloaded.

### Directus Version

10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### LINKED ISSUE #18957: Export changing limit breaks UI
### Describe the Bug

Changing the limit field on export sidebar breaks adding or removing fields

### To Reproduce

- On collection open export side bar
- Edit the limit field
- Try adding/removing field to export

It should now be added, and should be able to add and remove more fields.

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by u12206050**
Vue doesn't work well when doing `<template v-if="someCondition">This is just a string</template>` it is very hard to debug, but after 8 hours I found the source and reason.

- The PR closes #18842, closes #18957

Reference: https://stackoverflow.com/questions/72733707/why-am-i-getting-a-cannot-read-properties-of-null-reading-parentnode-error-fro

### CODE REVIEW

**Review by br41nslug — APPROVED** [review]
Nice find, resolves the 2 linked issues as expected in my tests.

**Review by rijkvanzanten — APPROVED** [review]
We've seen a similar bug fix before. I'm pretty sure this might be a new bug in Vue that was introduced somewhere around 3.2-3.3 🤔 This pattern didn't use to cause an issue before

**Comment by rijkvanzanten** [comment]
I don't think I entirely understand how the stackoverflow reference applies to the <template> with `v-if` usage @u12206050 🤔  Could explain like I'm five yo?

**Comment by u12206050** [comment]
> I don't think I entirely understand how the stackoverflow reference applies to the <template> with `v-if` usage @u12206050 🤔  Could explain like I'm five yo?

Sorry about that, yeh it was only actually the last comment on that thread that triggered me to look out for that which in deed was the issue.

I agree it might be a vue issue but makes sense in terms of a root element or router view that you can't pass in just a string but need an element

**Pull request merged**
