### PR TITLE
Fix `@keyv/redis` cache losing keys in high latency environments

### LINKED ISSUE #20205: Upgrade `@keyv/redis` and configure to not use a set to track keys
### Describe the Improvement

Sometimes user sees content cached when it was already updated.
The project is configured with `CACHE_AUTO_PURGE` to true and `CACHE_TTL` to 30m.
So the user only sees content updated after the TTL.

We already have tried to use the clear cache endpoint without any effect.

This is difficult to reproduce but I have seen this once in a while 
I believe `@keyv/redis` is the culprit. It looks like somehow it loses track of some keys and those are only deleted after the TTL set on Redis.

It looks like we are still using version 2.5.8 of `@keyv/redis` but the latest version is 2.8.0: https://github.com/directus/directus/blob/main/api/package.json#L222C15-L222C15

In this version there's a new feature where keys can be stored as simple keys instead of being tracked on a set (`useRedisSets: false`): https://github.com/jaredwray/keyv/pull/855/files
In the past I have noticed that in other projects, Redis instances were growing with keys not being deleted. So I think this would be nice to have.

Also the deletion of keys in most recent version is asynchronous by using UNLINK instead of DEL command.
https://github.com/jaredwray/keyv/pull/921/files

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
## Scope

What's changed:

- Cache keys backed by redis now use simple sets over redis sets.

## Potential Risks / Drawbacks

- None

## Review Notes / Questions

- I was not able to test if this resolves it specifically for high latency environments. Following the steps outlined #20238 did not work for my machine. Solution was done based on proposal in the original issue.
- https://github.com/jaredwray/keyv/pull/956 and https://github.com/jaredwray/keyv/pull/964 both of which were blockers for this task have been merged and released in the latest `@keyv/redis` version.

---

Fixes #20205

### CODE REVIEW

**Comment by joselcvarela** [comment]
Just to give an heads up:

I was looking into this PR, but saw that this implementation:
https://github.com/jaredwray/keyv/blob/main/packages/redis/src/index.ts#L123
Is not yet set:
https://unpkg.com/browse/@keyv/redis@2.8.3/dist/index.js
This can bring some issues since both cache and system cache are being removed when you only have updated your user name.
As it is currently, only cached items are removed, so not changes are made to system cache when you update your user name.
I think we should wait until we have that released.
Although I am not understanding how this version works. On npm it says
latest version is 2.8.3
https://www.npmjs.com/package/@keyv/redis?activeTab=versions
but on Github it says 2.8.1
https://github.com/jaredwray/keyv/blob/main/packages/redis/package.json

Although @ComfortablyCoding already asked more information about that:
https://github.com/jaredwray/keyv/pull/956#issuecomment-1906452416

**Comment by ComfortablyCoding** [comment]
Moving this to draft until the new version is released due to the issues stated above.

**Comment by ComfortablyCoding** [comment]
A new version (2.8.4) has been released with the missing changes

**Comment by ComfortablyCoding** [comment]
@joselcvarela The newest `@keyv/redis` release has the required changes from both PRs and seems to now work as expected.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
