### PR TITLE
Pass accountability to activity and revision services

### LINKED ISSUE #17266: Accountability object not available in activity hooks
### Describe the Bug

Custom Claims / custom accountability are a great feature of Directus. Unfortunately the (custom) accountability object is not passed through to activity hooks - where it would actually be needed for auditing purposes. Therefore it’s not possible to track activities based on custom claims / custom accountability.

### To Reproduce

Write a custom claim, use custom claim information to enhance accountability object… listen to activity hooks… accountability object is always empty.

### Errors Shown

_No response_

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

6.14

### What database are you using?

15

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

The accountability object was not getting passed down to the `ActivityService` and `RevisionService` user by the `ItemsService`.
This PR adds the `accountability` object to the constructors of these services falling back to `null` when not applicable.

Fixes #17266 

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by paescuj — CHANGES_REQUESTED** [review]
If I understand it correctly, the activity entries are currently created in "super" mode for all users (because no `accountability` object is passed). I'm afraid that the entries won't be created anymore for users with no access to `directus_activity` when passing the `accountability` object to this service!

**Comment by br41nslug** [comment]
@paescuj You are very right 🤦 hmmm thats going to be a bit tricky

**Comment by br41nslug** [comment]
Forcibly setting of the admin flag technically fixes it but i don't think this is the way to go. At least for the Activities service we could consider sending any custom properties on `accountability` with the payload 🤔

**Comment by rijkvanzanten** [comment]
Accountability and revisions are written by the system, never directly by the user, so the omission of the accountability here is on purpose

**Comment by br41nslug** [comment]
Definitely they are executed by the system however still triggered by user interaction (semantically still making the user accountable i.m.o).
Revisions cannot be created by users but activities can as comments are part of activity.

**Comment by paescuj** [comment]
> Perhaps this should be considered with the proposal of Viters to enhance the context of hooks/events (#16852) instead of trying to monkey patch it like this 🤔

Yes, something along these lines feels like a better approach!
As already discussed on Discord, direct changes to the `ActivityService` / `RevisionService` within the current structure are tricky and tend to end up as a hacky workaround.

**Pull request closed without merging**
