### PR TITLE
Support adding additional notices to release notes via changesets

### PR DESCRIPTION
**Pull request by paescuj**
Adding support to pass additional notices to the release notes via changesets (shown under "⚠️ Potential Breaking Changes") by using the following pattern in a changeset:

`.changeset/example-1.md`
```md
---
"directus": minor
---

::: notice
Some multiline notice from a changset.
Containing important stuff.
:::

Added something
```

`.changeset/example-1.md`
```md
---
"@directus/api": patch
---

::: notice
Other single line notice.
:::

Added another thing
```

Result into:

> ### ⚠️ Potential Breaking Changes
> 
> **Added something ([#1]())**
> Some multiline notice from a changset.
> Containing important stuff.
> 
> **Added another thing ([#2]())**
> Other single line notice.
>
> [...]

For example for notes like https://github.com/directus/directus/pull/18097#issuecomment-1562517232 to ensure we don't forget about such notes.
This will also help to fully automate the release workflow...
The format could then also be changed / improved later.

Pattern borrowed from https://vitepress.dev/guide/markdown#custom-containers.

### CODE REVIEW

**Review by azrikahar — APPROVED** [review]
code changes LGTM, but just some tiny thoughts/questions:

- > Adding support to pass additional info to the release notes via changesets by using the following pattern in a changeset

    Technically this isn't a high priority so should not block this PR, but we may need to have a documentation publicly for this given that this package is made public (eg. to guide others how to use this and the exact format to use).

- Should we add some form of comment based on the explanation from https://github.com/directus/directus/pull/18726#discussion_r1205445904 for the regex, just for future readers/maintainers?

**Comment by rijkvanzanten** [comment]
@paescuj Should we just use GitHub's existing format? For example:

> **Note**
> This also improves xyz

> **Warning**
> This will break when abc

**Comment by rijkvanzanten** [comment]
> You mean for the format inside the changeset or in the resulting release notes?

Yes

**Comment by paescuj** [comment]
> > You mean for the format inside the changeset or in the resulting release notes?
> 
> Yes
> 
> If we use it for both, we don't have to do any magic parsing or editing. In MD environments where that special syntax doesn't work, the output is still legible and "pretty" enough to work 🙂

The advantage of the current approach is that you can put whatever you want into the "info box" and it will get forwarded into the release notes exactly this way. For example if you want the additional info to be in a GitHub style info/warning box you can do so
```md
::: info
> Note
> An important note
:::
```
while at the same time if you want to use it to have some plain text added in the release notes you can simply do
```
::: info
A slightly less important note
:::
```

In any case we still need to do some parsing of the changeset summary because we need to split it up into "info content" and "normal content".

However I'm happy about suggestions here! For example we could also reduce the pattern to (omitting `info`)
```md
:::
Additional notes
:::
```

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Two little tweaks:

- Lets rename from `info` to `notice`
- Lets make sure we add the name or a link or something of the changeset that put the text at the top for context

**Review by rijkvanzanten — CHANGES_REQUESTED** [review]
Two little tweaks:

- Lets rename from `info` to `notice`
- Lets make sure we add the name or a link or something of the changeset that put the text at the top for context

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
