### PR TITLE
Add AdvancedFilter to drawer select

### PR DESCRIPTION
**Pull request by nickluger**
As discussed and designed, here: #6892.

* Extracted `AdvancedFilter` in a separate component that is used both, in the sidebar and in the `drawer-collection` now.
* Had to add back the `OperatorType` to [types](https://github.com/bluepick-app/directus/blob/96433f3107c4bab0fc01dd6c24497a15727d8fea/app/src/views/private/components/advanced-filter/types.ts#L9), as it was still being [imported](https://github.com/directus/directus/blob/32972f4c01b788b284266d1199fc161ee68c32ea/app/src/views/private/components/filter-sidebar-detail/get-available-operators-for-type.ts#L1).

### CODE REVIEW

**Comment by benhaynes** [comment]
Any screenshots? I'm curious how you implemented this... did you chat with @rijkvanzanten first? I know the plan (as of now) is to shift the advanced filter UI back into a dropdown of the search bar (which also solves filtering in the drawer).

**Comment by nickluger** [comment]
I did it exactly like the suggested [Option 3](https://github.com/directus/directus/discussions/6892#discussioncomment-1031061) in the discussion, that @rijkvanzanten, you and me considered the best, but used a default secondary button, as the search-bar-like button is custom designed.

 Here some screenshots:

No filters applied
Bildschirmfoto 2021-07-28 um 16 19 50

One filter applied
Bildschirmfoto 2021-07-28 um 16 20 08

Multiple filters applied, the menu can be scrolled
Bildschirmfoto 2021-07-28 um 16 20 22

**Comment by nickluger** [comment]
Multiple filters applied, closed, using search at the same time
Bildschirmfoto 2021-07-28 um 16 23 32

**Comment by nickluger** [comment]
Was not 100% sure what you meant by **in** the searchbar, as I never used v8, so I put it besides the search bar. In my opinion, as the search bar is expandable, i.e. per default hidden, the filter should not be in the bar. Filter and search **can** be used together, but it's not a requirement. Often enough, only the filter would be needed, so it should be accessible independently.

**Comment by benhaynes** [comment]
Sorry, crazy morning. This is great!! Thank you for explaining. I really like how you've structured this... the only question I'd have is should we combine the filter+search buttons (see rough mockup below). @rijkvanzanten thoughts on that?

Screen Shot 2021-07-28 at 2 59 53 PM

@nickluger — any thoughts on pro/cons for these options?

**Comment by rijkvanzanten** [comment]
We could even take it a step further, and make search move integrated with the filter, instead of treating the filter as an addition on the search bar 🤔

**Comment by benhaynes** [comment]
> We could even take it a step further, and make search move integrated with the filter, instead of treating the filter as an addition on the search bar 🤔

I'm down for this too — as long as searching is still only one click away.

**Comment by rijkvanzanten** [comment]
I was thinking we could open the filtering popover as soon as you focus in the search bar, almost like a dropdown 🤔

**Comment by benhaynes** [comment]
Perhaps, yeah! Could be solved with a new dropdown design and good auto-focus. 👍  The main thing we'd lose is the persistence of the search query (if one exists) which stays open/visible when it has a value.

Screen Shot 2021-07-28 at 3 35 58 PM

**Comment by rijkvanzanten** [comment]
We'll have to update the styling of that "collapsed" style to have an indicator that there's more filters active than just the search 🤔 Other than that, the dropdown option would still work with it!

**Comment by benhaynes** [comment]
Yeah, that was the "filter icon within the search bar" that I [pasted here](https://github.com/directus/directus/pull/7036#issuecomment-888546463). We used to have a number badge on top of the filter icon to indicate the difference.

**Comment by rijkvanzanten** [comment]
> Yeah, that was the "filter icon within the search bar" that I pasted here. We used to have a number badge on top of the filter icon to indicate the difference.

Ah gotcha, the arrow made me think it was the toggle button to make the popover show/hide

**Comment by nickluger** [comment]
Thanks for your input, guys!

1. I agree, that it would be great if filter and search could be edited at the same time without an additional click! As this is possible in the normal collections-view, when you keep the sidebar and filter-dropdown open, while typing in the searchbar.
   > I was thinking we could open the filtering popover as soon as you focus in the search bar, almost like a dropdown

   On the other hand, this always-in-approach might be overkill for simple and quick searches. It's still an _advanced_ filter, that might not be needed for every collection. I assume, that's why you decided to put it in the sidebar in the first place. Also, if you already applied a bigger filter-combination, and start searching within the filtered set, the always-open filter dropdown would overlay parts of the first results, while searching.

2. I think both, filter and search must be reachable independently with one click and also be **detectable** independently, i.e. neither should be hidden in the other.  

   > my thinking is that "search" is really just another filter...   but one that should be readily available (one-click away)

   That's kind of true, but filter is not just another search, and so filter should also be readily available and visible. As a new user, coming from the collection views, I'd assume the advanced filter is in some kind of sidebar. As soon as I realize, there's no sidebar, I'd start looking for a filter icon somewhere else. 

   In that regard, I'm not sure yet, how the design shown by @benhaynes achieves that, if there are no filters and no searchQuery, yet. Either the filter icon would be crammed into this search icon
Bildschirmfoto 2021-07-29 um 06 28 31
...which would look ugly. Or the search bar would have to stay always open.
Bildschirmfoto 2021-07-29 um 06 31 09
... although the expansion-feature of the bar is pretty cool and minimalistic.

Filter and search are conceptually different in my opinion - which is why they are separated in most apps (also in Directus, the filter is normally in the sidebar!) The typical process is to either directly run a quick search, or  - for certain cases -  build a subset of the collection by applying one or multiple filters. Then I might also search within that reduced subset.

**Comment by rijkvanzanten** [comment]
> The typical process is to either directly run a quick search, or - for certain cases - build a subset of the collection by applying one or multiple filters.

This poses the question: Is filtering a way to "search" using more specific properties, or a standalone tool to extract a subset of data. To me, both search and filtering achieve the same goal, though filtering does it more accurately. (I basically see filtering as an _advanced search_ / see search as a _simple filter_ if that makes sense 😄 )

**Comment by benhaynes** [comment]
I agree with that thinking — search is the easily available (but less precise) filter option. I would argue that the filter access button could be located within the search button/bar. The primary "magnifying glass" is how you find things... via search and/or filter. Once you click the search button, you can immediately start typing to filter by search, or click the "advanced filter" icon (within the expanded search bar) to open the filter dropdown.

The badge/count indicator can exist on the main search button/icon (when closed), or on the filter icon (when expanded). If you click on the main search icon **and there are already active filters then I think it should also auto-expand the filter dropdown.**

This direction will have a slight learning curve when filtering is removed from the sidebar, but I think it makes the most logical sense. Action Button real estate is very precious and I don't think the slight difference between search and filtering warrants two buttons.

One thing that might be worth looking into would be "pinning" the filter window open... but I'm not sure where this would live.

**Comment by nickluger** [comment]
> Once you click the search button, you can immediately start typing to filter by search, or click the "advanced filter" icon (within the expanded search bar) to open the filter dropdown. The badge/count indicator can exist on the main search button/icon (when closed), or on the filter icon (when expanded). If you click on the main search icon and there are already active filters then I think it should also auto-expand the filter dropdown.

Perfect combination 👍

> Action Button real estate is very precious and I don't think the slight difference between search and filtering warrants two buttons.

Agree 👍

**Comment by Oreilles** [comment]
This can be closed as the advanced filter options have been merged in the search bar in release `9.0.0`.

**Pull request closed without merging**
