### PR TITLE
Fix notification archive all

### PR DESCRIPTION
**Pull request by Dominic-Marcelino**
## Scope

The query used for the "Archive All" notifications request was invalid, not being passed as a `filter` thus not having any effect.

- For non-admin users the request would fail since users are usually only allowed to update their own notifications: https://github.com/directus/directus/blob/772b2901f196f425b0f91c5e189a64ed9c3bbfe0/packages/system-data/src/app-access-permissions/app-access-permissions.yaml#L73-L77
- Even more importantly, for admin users (or users having extended permission on `directus_notifications`), notifications for **any users** up to `QUERY_LIMIT_DEFAULT` would have been archived

## Potential Risks / Drawbacks

None

## Review Notes / Questions

- Additionally, limiting the patch request to only update items which are not yet archived as suggested in https://github.com/directus/directus/pull/23411#pullrequestreview-2245604875
- Includes a fix for the user filter which I (@paescuj) forgot to commit in #23414

---

Related to #22265 - not considering it as fully fixed yet, since the issue with `QUERY_LIMIT_DEFAULT` still exists (though the situation should be better now)

### CODE REVIEW

**Review by paescuj — CHANGES_REQUESTED** [review]
IMO we should either:
- Extend the current query filter to only patch notification items that have the status `inbox`. This might already be sufficient for most cases.
- Add a new service method and API endpoint which allows to actually archive all items, regardless of the query limit.
- Replace the current "Archive All" button with a "Select All" option as suggested in https://github.com/directus/directus/pull/19503#issuecomment-1692586807

**Comment by Dominic-Marcelino** [comment]
The more I think about it I think the archive-all button should only affect the currently visible notifications.
Imho this is especially important in relation to filter: once I filter notifications I'd expect the button to archive all related to this filter. This would be given with the key-approach and align with the batch-update from layouts.



> Extend the current query filter to only patch notification items that have the status `inbox`. This might already be sufficient for most cases.

The query-limit issue still exists when adding an inbox-status filter. Not sure why 😅 


> Add a new service method and API endpoint which allows to actually archive all items, regardless of the query limit.

Would be the cleanest option but also be pretty unsafe in case of thousands (or hundred-thounsands) of notifications.
For sure archiving notifications takes way less resources than other larger updates but IMHO it feels wrong to build around the limitations


> Replace the current "Archive All" button with a "Select All" option as suggested in [Improve notifications view #19503 (comment)](https://github.com/directus/directus/pull/19503#issuecomment-1692586807)

Would also feel right for me, but would be one click extra related to the current solution. Wdyt in relation to the first thoughts?

**Comment by Dominic-Marcelino** [comment]
> The query-limit issue still exists when adding an inbox-status filter. Not sure why 😅
> 
> >

Just noticed that the original implementation was missing the `filter` key... Updated in order to use the current app-filter in order to archive all filtered items.


If the number of items exceeds the limit, the archiving will start with the oldest. However, I'm not sure if we should start with the newest items instead, so the user can immediately see that something has happened. (The user could only notice the change based on the count once #23414 is merged.)

**Review by paescuj — APPROVED** [review]
It's more severe than it initially seemed, see updated description in https://github.com/directus/directus/pull/23411#issue-2473360355

**Pull request merged**
