### PR TITLE
Add missing class, so edit user will work again

### PR DESCRIPTION
**Pull request by WorksDev**

### CODE REVIEW

**Comment by WellingGuzman** [comment]
Hey @WorksDev, would you care to explain this commit? what would this fix?

**Comment by WorksDev** [comment]
Oh, sry :) On User Listing Page http://mydomain.xx/users, it is actually not possible to click on user to show up the edit modal because this class is missing

**Comment by WellingGuzman** [comment]
how can I reproduce the issue? I'm able to open the modal, and `js-choose-user` class, it's only used on the `directus_users` interface.

**Comment by WorksDev** [comment]
Umf i think this was my browser cache after update - sry for that.

**Pull request closed without merging**
