### PR TITLE
Fix S3 storage driver large file upload

### LINKED ISSUE #22722: Can't upload large files with S3 storage driver
### Describe the Bug

I am experiencing issues with uploading large video files (10GB to 100GB) using Directus with an S3 storage drive.
While the upload process works for smaller files up to 10GB, larger files (25GB to 50GB) fail to upload completely. 

The upload starts but stops randomly between 25% and 75%, displaying an error modal.

Directus Error

### To Reproduce

1. Set up Directus with an S3 storage driver.
2. Attempt to upload a video file between 25GB and 100GB.
3. Observe the upload process.

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by emilienbidet**
## Scope

What's changed:

- Change the S3 storage driver upload file method following [this guide] (https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_s3_Scenario_UsingLargeFiles_section.html) to handle very large file, 25GB and more

## Potential Risks / Drawbacks

- The implementation works for small file but not for large file again. The issue should come from somewhere else...

---

Fix #22722

### CODE REVIEW

**Comment by emilienbidet** [comment]
This branch is maybe a bad implementation of the next big feature of #22536

**Comment by emilienbidet** [comment]
Thank you very much for your answer @rijkvanzanten. So if you think it worth the job. I will then take some time to write tests for theses changes :)

**Comment by rijkvanzanten** [comment]
That'd be fantastic. Thanks @emilienbidet!

**Comment by rijkvanzanten** [comment]
Closing this as the original issue was resolved and we've since published the big TUS upgrade which also addresses this 🙂

**Pull request closed without merging**
