### PR TITLE
show error popup for composite unique indexes

### LINKED ISSUE #8028: Multicolumn unique index: violation not handled in app
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

This happens at least on Postgres 13.

If you have a `UNIQUE`-index/constraint on a single column and try to deliberately violate this constraint, the app UI handles the `400 - Bad Request` status code returned gracefully, by showing an error message alongside the affected field:

Bildschirmfoto 2021-09-14 um 15 00 16

If you have a **multicolumn** `UNIQUE` index/constraint on e.g. two fields like 

```sql
CREATE UNIQUE INDEX my_special_composite_index
    ON my_table (col_a, col_b);
```

Violating this index by creating a second row with already existing values for `col_a` and `col_b` will show no error message in the UI, although the API returns a `400 Bad Request`.
This is returned by the API and not catched and handled by the app:
```
{
  "errors": [
    {
      "message": "Field \"col_a, col_b\" has to be unique.",
      "extensions": {
        "code": "RECORD_NOT_UNIQUE",
        "collection": "my_table",
        "field": "col_a, col_b",
        "invalid": "item_1, cktjva3qy0002r8nghiig3pmp",
        "stack": "Error: Field \"col_a, col_b\" has to be unique.\n    at uniqueViolation (/Users/.../directus/dist/exceptions/database/dialects/postgres.js:44:12)\n    at extractError (/Users/.../node_modules/directus/dist/exceptions/database/dialects/postgres.js:21:20)\n    at translateDatabaseError (/Users/.../node_modules/directus/dist/exceptions/database/translate.js:28:48)\n    at /Users/.../node_modules/directus/dist/services/items.js:360:72\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
      }
    }
  ]
}
```

## What would be expected?

The error should be shown somehow to the user. Maybe in context of the affected columns, as the one-column-unique-index error, but not necessarily that precisely. 

At least a normal error message should be shown, similar to when an `Internal Server Error 500` or an `InvalidPayloadException` is thrown like this:

Bildschirmfoto 2021-09-14 um 15 22 55

### To Reproduce

1. Create a collection with a composite UNIQUE index.
2. Create an item in it.
3. Try to create another item with the same values.
4. No error shown, but item not created.
5. Take a look in the console and your network tab and see 400.

### What version of Directus are you using?

9.0.0-rc.92

### What version of Node.js are you using?

14

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #8028

## Reported bug

_Prior to this, I ran the query `CREATE UNIQUE INDEX my_special_composite_index ON posters (category, size);` to create the multi-column unique index in the PostgreSQL database._

When we enter a new record with the exact same composite unique index values, no error seems to be shown even though the request does fail with status 400:

https://user-images.githubusercontent.com/42867097/133542149-ac159deb-74d5-4492-a488-09f54c471c10.mp4

chrome_BbDRfAvV3P

## Investigation

When the request returns error, it does actually correctly be added to `validationErrors` over here because it falls under `RECORD_NOT_UNIQUE` (refer image above) in `VALIDATION_TYPES`:

https://github.com/directus/directus/blob/9ba43c19f8c7ae4add0394ace7f90cbc524177e7/app/src/composables/use-item/use-item.ts#L145-L149

However validation-error looks for `err.field === field.field`, so field.field (`"category"` or `"size"`) will never equal err.field which is a combined string of `"category, size"`:

https://github.com/directus/directus/blob/9ba43c19f8c7ae4add0394ace7f90cbc524177e7/app/src/components/v-form/v-form.vue#L54

Which it why it seems like nothing happened, despite the validationError is set properly. It's just that it's not applied to the fields visually.

## Current proposed changes

add a check whether field contains a comma, while still being inside the `VALIDATION_TYPES.includes(err?.extensions?.code)` filter/map, then trigger unexpectedError function to show the error modal.

But this current change still doesn't show error message(s) below the relevant inputs.

## After current changes applied

https://user-images.githubusercontent.com/42867097/133542674-7857bd8f-a6fe-433b-8938-f7d72c546fbd.mp4

## Tentative more thorough change

Here's a more elaborate experimental change (not included in this PR yet) which does show the error message under the inputs:

https://user-images.githubusercontent.com/42867097/133542408-62f98f97-8f9b-4721-8318-06f314160be5.mp4

However that involves adding an optional `fields?: string[]` here:

https://github.com/directus/directus/blob/9ba43c19f8c7ae4add0394ace7f90cbc524177e7/packages/shared/src/types/fields.ts#L57-L64

so that I can turn the `field` with comma into an array as `fields`, then change

https://github.com/directus/directus/blob/9ba43c19f8c7ae4add0394ace7f90cbc524177e7/app/src/components/v-form/v-form.vue#L54

into 

```js
validationErrors.find((err) => err.field === field.field || err.fields?.includes(field.field))
```

I'm not sure if that's a good approach so I'll leave this as a draft for now.

### CODE REVIEW

**Comment by joselcvarela** [comment]
Hey @azrikahar 
Any reason this is still in draft?

**Comment by azrikahar** [comment]
> Hey azrikahar Any reason this is still in draft?

It depends on whether we would like to have the slightly clearer input highlights (highlight inputs that has errors) in the video under `Tentative more thorough change`. It's clearer, but I'm not sure if the approach I used is correct or not.

If the current fix (video under `After current changes applied`) is good enough, I'll okay with moving this out of draft 👍

**Comment by rijkvanzanten** [comment]
@azrikahar I think the real fix here is to check if all validation errors in the form context are shown. If not, we should throw a dialog (like your current fix) for the unexpected errors. That would also fix #9006 and #9176

**Comment by azrikahar** [comment]
> check if all validation errors in the form context are shown.

Just to confirm, this means checking if there are errors where `validationErrors.find((err) => err.field === field.field)` fails to find them right?

**Comment by rijkvanzanten** [comment]
Yeah! Right now, the app doesn't throw an error as we're showing validation errors locally on the form. However, when the validation error applies to a field that's not shown in the current context, we should still throw the error dialog, otherwise it's hidden forever

**Comment by azrikahar** [comment]
Somehow I've just noticed, or rather recall after seeing this again, where this part of the code should be sort of doing what you meant right?

https://github.com/directus/directus/blob/5d3a041ca249ff6e5be5d3f93ed2149c985151b4/app/src/components/v-form/v-form.vue#L170-L188

I believe there's an error here, where we should do the following changes:

```diff
-    let included = fieldKeys.includes(error.field) === false && fieldsInGroupKeys.includes(error.field);
+    let included = fieldKeys.includes(error.field) === false && !fieldsInGroupKeys.includes(error.field);
```
~~it should be NOT includes right?~~ Not sure if this is correct now..

On a second thought, will `fieldKeys.includes(error.field) === false` actually be true for hidden fields? fieldKeys still has all keys regardless of hidden or not here from what I can see.

```diff
     if (props.group === null) {
-        included = included && fieldsInGroup.find((field) => field.field === error.field)?.meta?.group === null;
+        included = included && isNil(fieldsInGroup.find((field) => field.field === error.field)?.meta?.group);
    }
```
We need to use isNil because if it can't find the field, it returns `undefined`, not `null`.

After fixing it, it does show up here:

image

---

With that said, here's my line of thought on finalizing this fix:

- fix the `unknownValidationErrors`'s logic
- enhance it doing additional checks:
  - If it's hidden, pass it to unknownValidationErrors to appear on the notice above.
  - If it's "not hidden + does not have a matching field", trigger the error dialog box, but _do not_ pass it back to unknownValidationErrors.
  
So would the following logic be correct?

But seems like the dialog box doesn't accept `extensions` at the moment 🤔

**Comment by azrikahar** [comment]
> ~~it should be NOT includes right?~~ Not sure if this is correct now..

>On a second thought, will `fieldKeys.includes(error.field) === false` actually be true for hidden fields? fieldKeys still has all keys regardless of hidden or not here from what I can see.

Might've confused myself after staring at it for a period of time, but I've just tested it with only a required field and it is still not showing up as a notice:

https://user-images.githubusercontent.com/42867097/140264533-5383de02-4157-4262-85cc-0aa4539a7661.mp4

**Comment by Oreilles** [comment]
This would also fix https://github.com/directus/directus/issues/9119. 👍

> However that involves adding an optional fields?: string[] here:
> https://github.com/directus/directus/blob/9ba43c19f8c7ae4add0394ace7f90cbc524177e7/packages/shared/src/types/fields.ts#L57-L64

Or better yet, type both `valid` and `invalid` as `(number | string)[]` to avoid having to check if it's an array or not when you'll want to use it.

**Comment by sarthakgaur** [comment]
@azrikahar Any update on this?

**Comment by joselcvarela** [comment]
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

**Comment by azrikahar** [comment]
Superseded by #12001

**Pull request closed without merging**
