### PR TITLE
Add translatable label to themes and field translations

### LINKED ISSUE #20637: Add translations for theming strings
I noticed while looking into integrating theming into the onboarding that there are some untranslated strings related to theming for example:

- "Default Appearance"
- "Default Theme Light"
- "Default Theme Dark"
- "Directus Default"
- "Directus Minimal"
- "Directus Color Match"

Edit: Dont forget the User settings too, in my naive first try they dont wanna work for some reason at the moment.(?)

### PR DESCRIPTION
**Pull request by DanielBiegler**
## Scope

What's changed:

- Added i18n keys for some theming related strings
- Added a new field to themes package called `label` which is used as the display name instead of `name` which allows us to call `translate()` on it to internationalize theme names via `$t:`-strings
    - image

## Potential Risks / Drawbacks

- Too large labels but the label is rendered by `v-text-overflow` which deals with this correctly:
    - image

## Review Notes / Questions

- Dont forget to rebuild themes in case youre testing this: `pnpm --filter themes build`

---

Fixes #20637

### CODE REVIEW

**Review by rijkvanzanten — DISMISSED** [review]
Lets rename `name` to `id`, and use `name` for the pretty translated name 🙂

**Comment by br41nslug** [comment]
> Lets rename name to id, and use name for the pretty translated name 🙂

Not necessarily in scope for this PR but should we not make `name` translatable for all extensions? especially frontend ones like interfaces and displays

**Comment by rijkvanzanten** [comment]
@DanielBiegler Maybe we can use `ext.id ?? ext.name` in case `id` is missing? That way it'll just default to using the name as the id if it doesn't exist

**Comment by paescuj** [comment]
> Not necessarily in scope for this PR but should we not make `name` translatable for all extensions? especially frontend ones like interfaces and displays

Isn't that already the case? At least it's used that way internally:

https://github.com/directus/directus/blob/7492223d6a4655d9b02474816a6acac31eba2930/app/src/interfaces/boolean/index.ts#L6-L8
https://github.com/directus/directus/blob/7492223d6a4655d9b02474816a6acac31eba2930/app/src/displays/boolean/index.ts#L5-L7
https://github.com/directus/directus/blob/7492223d6a4655d9b02474816a6acac31eba2930/app/src/operations/condition/index.ts#L4-L7
https://github.com/directus/directus/blob/7492223d6a4655d9b02474816a6acac31eba2930/app/src/panels/bar-chart/index.ts#L8-L10
https://github.com/directus/directus/blob/7492223d6a4655d9b02474816a6acac31eba2930/app/src/layouts/calendar/index.ts#L30-L31

> @DanielBiegler Maybe we can use `ext.id ?? ext.name` in case `id` is missing? That way it'll just default to using the name as the id if it doesn't exist

I hope we can keep it as consistent as possible for all (app) extensions.

**Comment by rijkvanzanten** [comment]
@paescuj yeah but there's no way to include the actual translation strings, so it's a bit limited atm

**Comment by paescuj** [comment]
> > Isn't that already the case? At least it's used that way internally:
> 
> Yeah that only works for us internally not for extension builders unless your extension is conveniently named like something already in our translation files

Sure, I got that 👍 Yeah, would be nice to have a way to ship translations via extensions 😃

**Review by paescuj — APPROVED** [review]
LGTM 🚀 Tested in dev & prod

**Pull request merged**
