### PR TITLE
Fix "Export to CSV" for relational fields (n:1, file) 

### LINKED ISSUE #14344: CSV export of presentation values don't work since v9.12.0 - n:1 relation
### Describe the Bug

I am using the CSV export for presentation values...
bug_csv_0

with these relational values ( "veranstaltung" and "veranstaltung.titel") from a n:1 relation:
bug_csv_1

### Version 9.14.1:
bug_csv_2_9 14 1

### Version 9.13.0:
bug_csv_3_9 13 0

### Version 9.12.2:
bug_csv_3_9 12 2

 ### Version 9.11.1:
bug_csv_4_9 11 1

### To Reproduce

1. Create a n:1 relation with display of relational values
2. Use the "quick CSV export for presentation values"
3. take a look at the exported values and compare with the presentation values
4. try different versions of directus and repeat  step 2 and 3

In v9.11.1 it should work as expected. In all versions since 9.12.0 it doesn't work anymore.

### Errors Shown

_No response_

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Vivaldi (Chromium)

### How are you deploying Directus?

Local, PaaS (Render - Web Service)

### PR DESCRIPTION
**Pull request by abernh**
## Description

Fixes https://github.com/directus/directus/issues/14344

Currently the function `getAliasedValue()` is used in `tabular.vue` in order to get the values for aliased fields.

This fix moves this function from `tabular.vue` to `tabular/index.ts` and applies it now already on the `items` array.

## Fixes
Now the correctly looked up values are not only shown in the table layout in the UI but are also included in the presentational "EXport to CSV" files.

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by christianrr** [comment]
@azrikahar Could this potentially be merged into the next version? I face the same problem as described above. Many thanks!

**Review by Nitwel — APPROVED** [review]
Looks good to me, thanks for the contribution! 😄

**Review by jaads — APPROVED** [review]

**Comment by azrikahar** [comment]
@Nitwel I just noticed this thanks to Jan, but mind taking a peek here to see whether #17799 coincides/supersedes this change?

**Comment by paescuj** [comment]
> @Nitwel I just noticed this thanks to Jan, but mind taking a peek here to see whether #17799 coincides/supersedes this change?

Yes, thanks @azrikahar! Please check that 👍

**Comment by rijkvanzanten** [comment]
From what I can tell, this was superseded by #17799 🙂

**Comment by ConnorSimply** [comment]
@paescuj Does #17799 resolve ENG-232 / #14344 ?

**Pull request closed without merging**
