### PR TITLE
Propagate mutation options for schema apply

### LINKED ISSUE #16503: Failed to create relation because collection doesn't exist
### Describe the Bug

Maybe I'm having a really bad day but... while trying to debug #16493 I started attempting to recreate the whole database see if it works. But now I can't get an empty database to initialize with the database schema.

Unfortuately for me, the `attachments` collection does exist, as it is the first one in the whole snapshot. I tried this same thing with another snapshot and got the same error with another collection.

Not sure why it started happening, but it happens on both my local and on my VPS. I have a feeling Directus skips creating some collection? But why...

Initial tables in `bootstrap` were created successfully.

### To Reproduce

I created [a gist](https://gist.github.com/arpadgabor/d945f0121edf73976d32778d703d3311) with the two snapshots that are experiencing these issues.

### Errors Shown

```
{"level":50,"time":1668764884784,"pid":28534,"hostname":"flow","msg":"Failed to create relation \"attachments.file\""}
{"level":50,"time":1668764884789,"pid":28534,"hostname":"flow","err":{"type":"InvalidPayloadException","message":"Collection \"attachments\" doesn't exist","stack":"Error: Collection \"attachments\" doesn't exist\n    at RelationsService.createOne (/home/arpad/projects/ccoc/node_modules/.pnpm/directus@9.21.0/node_modules/directus/dist/services/relations.js:141:19)\n    at /home/arpad/projects/ccoc/node_modules/.pnpm/directus@9.21.0/node_modules/directus/dist/utils/apply-snapshot.js:190:44","status":400,"code":"INVALID_PAYLOAD","extensions":{}},"msg":"Collection \"attachments\" doesn't exist"}
```

### What version of Directus are you using?

9.21.0, 9.20.4, 9.19.2

### What version of Node.js are you using?

16.18.1

### What database are you using?

Postgres 13 (postgis/postgis:13-3.3-alpine)

### What browser are you using?

n/a

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by licitdev**
## Description

Fixes #16503. The schema `apply` cli command wraps DB changes within a transaction. The emitting of action events now runs outside of this transaction.

A `bypassCache` flag is added, ensuring that the fetched schema is up to date and removed the redundant flushing of caches.

The changes were tested in https://github.com/directus/directus/pull/14713/commits/390907d511a18b404140640313c4904d6feec977 where the schema apply tests passes.

### Tests passing for snapshot apply

image image

## Type of Change

- [x] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [x] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Comment by azrikahar** [comment]
For references, this PR propagates changes from #15576, and later on included the `bypassCache` flag addition to `getSchema` from #14713.

**Review by azrikahar — APPROVED** [review]
Works with several manual tests, especially after the addition of `bypassCache` flag in getSchema(). There are more comprehensive tests for this in #14713, so we should be able to rely on those.

Additionally noticed that currently getSchema() accepts `accountability` option:

https://github.com/directus/directus/blob/12786728ed3d2c1808863fca3fcdda588d0e2c0f/api/src/utils/get-schema.ts#L17-L18

but it's no longer in used over there, likely an old code that was not removed when the logic was extracted away from it. Opted to remove it in this same PR as well 👍

**Comment by licitdev** [comment]
Can confirm that `accountability` is no longer used within getSchema().
Thanks @azrikahar! 🙏

**Review by br41nslug — APPROVED** [review]
Not necessarily related to this PR but with the removal of `accountability` from `getSchema` we really should make the `schema` optional for all services and default to `getSchema` (like we do for the knex object)

**Pull request merged**
