### PR TITLE
Change default status color to specific var

### LINKED ISSUE #24009: Tweak default status colors
### Describe the Improvement

Because "status" field is "default" system optional field to chose i suggest to add new theme variable like 

- published
- draft
- archived

Because now is set by "primary color" from theme and this is very hard to tweak inside custom CSS - because no explicit class in status component.

In file is defined what color have to be set by default when the status filed is chosen. 

https://github.com/directus/directus/blob/main/app/src/modules/settings/routes/data-model/new-collection.vue

### PR DESCRIPTION
**Pull request by gavalierm**
Because Status field is optional by default it will be great to have custom css viariable to have option to twak this variable in custom CSS for all default status fileds.

## Scope

What's changed:

Color defaults for status field

## Potential Risks / Drawbacks

- this can broke actual color schema for default status, because there is no such color variables in default theme css files and have to be added.

## Review Notes / Questions

- i do not know how exactly is color variables computed in __styles so i do not change anyting in default __styles files in this pull request.

---

Fixes #24009

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hi @gavalierm! Thanks for your suggestion 🙂 I don't think that adding a new set of (very) specific theme properties for a default interface option is appropriate here. It adds a bit too much noise for my taste, especially seeing that those interface options can be changed to whatever you want them to be 👍🏻

**Comment by gavalierm** [comment]
I fully understand. But… ;) 

if you decide to have “different status colors” for something like “status” which is almost in all collections it is super heavy work to do so.

because you need to change status “display” and “interface” colors (so twice in same field) fore each collection iny directus.

Will be nice to consider this as “planned”. Maybe not today… but someday?


There is a option to tweak custom css but this is not the way also. Becase status html elementa have “no class” the color is just “—primary” so this is not possible to diif the status color from primary template color.


And if you change color directly in interface the change is represent by “style” attribute directly on element.. ao there is no chance to do it globally.

**Comment by rijkvanzanten** [comment]
While I agree it's still a bit more manual work than ideal; you can streamline that process a bit by setting it up once in a way that you want it to be, and then use the copy raw / paste raw field options to quickly paste that same config in the other interfaces/displays that you want it to match with 👍🏻

**Comment by gavalierm** [comment]
Yes it is a bit better then nothing.

But it is a bit strange to have primary color as status color. 

i do not will "fight" for it, but it just lost the directus "yey it just works :P" if i change the primary color of template and i lost my "status" colors.

I think status color have to be definet separately because "status" is (optional) system default field so it will be nice to have different default colors from "primary template".

We can stop discussion if there is no reason to tweak this :)

**Pull request closed without merging**
