### PR TITLE
Add option to toggle _some and _none on o2m

### PR DESCRIPTION
**Pull request by Nitwel**
## Scope

What's changed:

- Add option to toggle _some and _none on o2m

## Potential Risks / Drawbacks

- Only the filter could break

Fixes #19890 

## Overview
grafik
grafik
grafik

### CODE REVIEW

**Review by br41nslug — COMMENTED** [review]
So far it seems to work as intended in my testing however i find the UX implementation fairly unintuitive. Especially when dealing with multiple levels of nesting it is not directly clear to me which relation it applies to and how i would make it only apply to one specific relation in the chain. I would love for this to be more like the Tree structure of `_or` and `_and`

image

**Comment by benhaynes** [comment]
First question: Shouldn't there be an `All` as well? `Some` and `None` being the other two...

**Comment by br41nslug** [comment]
> First question: Shouldn't there be an `All` as well? `Some` and `None` being the other two...

Would love to have that as new feature :D Doing double negatives can get quite cumbersome in complex filters. That is however a new feature and out of scope for this PR.

**Comment by rijkvanzanten** [comment]
Closing this to be revisited later.

**Pull request closed without merging**
