### PR TITLE
Revert a change which broke interface-input with choices

### LINKED ISSUE #12530: filter not showing available options
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

In 9.6.0 it was possible to select a value from a dropdown list if the field had options eg:
options in filter

However after updating to 9.8.0 this is no longer possible eg:
options missing in filter

### To Reproduce

Create a dropdown field with some options.

Try and select those options via the filter.

### Errors Shown

None

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

Chrome

### What operating system are you using?

osx

### How are you deploying Directus?

GCP

### PR DESCRIPTION
**Pull request by u12206050**
Fixes #12530

### CODE REVIEW

**Comment by u12206050** [comment]
The bug was introduced in this commit: 175fb849c48dd0e888480f25fa1dfa3c2231f7c7

**Comment by benhaynes** [comment]
Thanks for the PR!! 👍

**Review by azrikahar — COMMENTED** [review]
After looking into #12363's change on `input-group` component, I'm inclined to believe this is actually intentional. 

The line changed in this PR falls under the `v-else-if`:

https://github.com/directus/directus/blob/33c379a912395575e8267339d398b86197b03b7a/app/src/interfaces/_system/system-filter/input-group.vue#L2-L26

where the original (assumed) intention is to make contains/starts/ends etc to _not_ show the choices as I do agree it can be a little odd.

and as we can see in line 2, this choices interaction still works for eq/neq/lt/lte/gt/gte which makes more sense, and I've tested it:

image

Perhaps @rijkvanzanten can confirm/clarify the context of said change when he can look into this 👍

**Comment by u12206050** [comment]
Ah that makes sense. Will look into then rather selected eq as the default option for a dropdown field then.

**Comment by rijkvanzanten** [comment]
Yup! That's correct. "Contains" is to search using a substring in a bigger value, so it uses a text-input

**Comment by benhaynes** [comment]
While I agree with this logic, I do like the accessibility of the dropdown. Since we have `contains` as the default operator, it's an additional step to get to that dropdown (switch to `eq`). I wonder if there's a way to get the best of both worlds. 🤔

**Comment by rijkvanzanten** [comment]
We could default the filter to equals, seeing that "contains" is very similar to the regular search bar that's already above it (though it searches through a single field rather than all) 🤔

**Comment by benhaynes** [comment]
Yeah. It was nice being able to immediately start typing and get a result, but the search is good for that. Conflicted!

**Comment by u12206050** [comment]
I figure we can use a test on `choices` if choices has length then we default to `eq` else `contains` what do you think? @benhaynes  @rijkvanzanten

**Comment by benhaynes** [comment]
That could work too... bummer we wouldn't be consistent with our operators, but that's just how it is. 🙂

**Comment by u12206050** [comment]
I tried locating a place to implement this logic, but `choices` isn't available in the `nodes` scope where the initial operator value is set simply using `[0]`(ie. the first operator in available operators)

Any suggestions? @rijkvanzanten

**Comment by azrikahar** [comment]
@u12206050 made an attempt over here #12598. Feel free to help confirm whether it resolves this 👍

**Comment by u12206050** [comment]
Awesome that works. Thanks.

**Pull request closed without merging**
