### PR TITLE
Fix json serialization

### LINKED ISSUE #16216: Copy Raw Value from JSON fields
### Describe the Bug

Copying the raw value from a repeat in the field set-up does not properly stringify the json.
image
```
// Copied Result: 
[object Object],[object Object],[object Object],[object Object],[object Object]
```
```js
// Expected Result:
[
	{
		"text": "Not-Started",
		"value": "not_started"
	},
	{
		"text": "On-Track",
		"value": "on_track"
	},
	{
		"text": "Stuck",
		"value": "stuck"
	},
	{
		"text": "Completed",
		"value": "completed"
	},
	{
		"text": "Archived",
		"value": "archived"
	}
]
```

### To Reproduce

Copy the raw value from a repeater interface when creating a field.

### Errors Shown

None

### What version of Directus are you using?

9.19.1

### What version of Node.js are you using?

{ node: 'v16.17.0', npm: '8.15.0' }

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Railway from Repository

### LINKED ISSUE #16557: From 9.21.0 Edit Raw Value from JSON fields also shows [object Object]
### Describe the Bug

Before 9.21.0 while Copy Raw showed `[object Object]` #16216 we still has the opportunity to Edit Raw Value and copy.
Now, from 9.21.0 even Edit Raw Value from JSON fields shows also ` [object Object]`

Hence we have no mean to get the JSON raw value.
Which makes it very difficult to handle and maintain complex filters.

### To Reproduce

Set a filter, for example in a Preset, and Edit ou Copy Raw Value.

### Errors Shown

`[object Object]`
instead of the JSON 

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgresql 15

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

### PR DESCRIPTION
**Pull request by br41nslug**
## Description

Specifically on the preset page the `filter` field had type `string` instead of `json` causing the `[object Object]` when rendered, updated the field definition and checked the rest of the app for the same mistake.
For copying i added a simple type check which json.stringifies the data if it is not a string.

Fixes #16557
Fixes #16216

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated. PR:

### CODE REVIEW

**Review by azrikahar — COMMENTED** [review]
Nice catch! Thoughts on moving the stringify logic into `copyToClipboard`? 🤔 Coincidentally reminded me of the copy button in the `<v-error>` dialog, and it it turns out it also does a similar stringify with additional formatting:

https://github.com/directus/directus/blob/12786728ed3d2c1808863fca3fcdda588d0e2c0f/app/src/components/v-error.vue#L50-L52

Perhaps combining the logic with your string check within `copyToClipboard` will make it "smarter" in case it's ever used elsewhere 😃

**Comment by br41nslug** [comment]
Makes a lot of sense to me to do this sort of fallback handling inside the `copyToClipboard` function. I am leaving that `v-error` example as is however as im falling back to no formatting for `stringify` while the `v-error` there uses fairly specific formatting options.

**Review by connorwinston — CHANGES_REQUESTED** [review]
These changes do not work as expected. They do not ensure the type of value that is copied follows through pasting it. Copying a raw number pastes it as a string.

The new changes do fix `[object object]`, but now i just pastes in the JSON as a string.
image

**Comment by br41nslug** [comment]
> They do not ensure the type of value that is copied follows through pasting it. Copying a raw number pastes it as a string.

Can you explain how you've gotten this result? The clipboard is always a string but these values should be parsed on paste in the Raw Value field. Seems to be working as expected on my end 🤔 

firefox_dO2jiiQGB2

**Comment by ConnorSimply** [comment]
> > They do not ensure the type of value that is copied follows through pasting it. Copying a raw number pastes it as a string.
> 
> Can you explain how you've gotten this result? The clipboard is always a string but these values should be parsed on paste in the Raw Value field. Seems to be working as expected on my end 🤔
> 
> firefox_dO2jiiQGB2 [ firefox_dO2jiiQGB2 ](https://user-images.githubusercontent.com/9389634/207000495-ae363909-8dff-4f22-a329-4a9f35687e01.gif) [ ](https://user-images.githubusercontent.com/9389634/207000495-ae363909-8dff-4f22-a329-4a9f35687e01.gif)

I just followed these steps...https://github.com/directus/directus/issues/16216 in the field settings, just go to a repeater, copy the raw value and then paste the raw value.

**Comment by br41nslug** [comment]
Interesting that button seems to be only present in chrome, it is not there in my firefox gif 🤔 TIL will debug the issue in chrome tomorrow

**Review by connorwinston — APPROVED** [review]
LGTM Now

**Pull request merged**
