### PR TITLE
Use technical collection/field names in settings

### LINKED ISSUE #19414: Use technical collection/field names in settings
### Describe the Improvement

There's various places in Settings where we show the collection/field name. For a lot of those places, we use the "pretty" version (either translated / or auto-capitalized version). We should use the technical keys there. For example in relationship configuration for m2a:

CleanShot 2023-08-11 at 14 04 02@2x

Or permissions: 

CleanShot 2023-08-11 at 14 04 23@2x

### PR DESCRIPTION
**Pull request by Nitwel**
fixes #19414

M2A:
grafik
Roles:
grafik
grafik
grafik

### CODE REVIEW

**Comment by Nitwel** [comment]
I used the raw keys for now but let me know if we want to throw a formatTitle at them.

**Comment by jaads** [comment]
it seems to work everywhere except for one component in the M2A builder for selecting the related collections.
Screenshot 2023-08-16 at 13 03 10

**Review by paescuj — CHANGES_REQUESTED** [review]
I guess we should use 𝚖𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎 font for the collection dropdown in M2A as well, like in the other places:
Screenshot 2023-08-16 at 17 29 09

**Review by paescuj — APPROVED** [review]

**Review by DanielBiegler — APPROVED** [review]
I like it! :)

**Pull request merged**
