### PR TITLE
Add items.read filter hook

### LINKED ISSUE #10164: Add items.read Hook Filter
### Discussed in https://github.com/directus/directus/discussions/7837, https://github.com/directus/directus/discussions/4847, https://github.com/directus/directus/discussions/3736, and https://github.com/directus/directus/discussions/4812

This issue is to track adding a hook for `ITEMS.READ` (both before and after) so that read responses can be altered or trigger logic. With this feature, we also need to update the docs and include a large warning about the potential for performance issues and breaking the Directus app itself.

### PR DESCRIPTION
**Pull request by oreilles**
Fixes #10164

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by Oreilles** [comment]
@rijkvanzanten did you remove the `query` from the filter hook meta input in the previous PR ? Cause it's there again as I hadn't pulled any changes from the upstream branch before posting this PR.

**Comment by rijkvanzanten** [comment]
@Oreilles I did not! The merge conflict said there was nothing there before, and that it was added in this branch, so I figured it was the intended thing to have?

**Comment by Oreilles** [comment]
Well that's strange, must have been swept away when merging with `main`..?
Anyway, I just had put it cause it was in the `action` filter below, not sure if it actually is useful.

**Comment by rijkvanzanten** [comment]
Doesn't hurt to have! Nice bit of extra metadata to adjust your hooks operation on (eg only fire your hook when the query doesn't include `aggregate` for example)

**Pull request merged**
