### PR TITLE
Add expand_more icons to sidebar detail

### LINKED ISSUE #3621: Add "expand_more" icon to right of sidebar detail component
Makes it a little more obvious that sidebar sections can be opened, when in expanded view (larger screens)

### LINKED ISSUE #4123: Saving item options not working in different language
1) Cannot use keyboard shortcut for "Save and Stay" or "Save and Create New"
    The shortscuts `Ctrl+S` and `Ctrl+Shift+S` doesn't save item in collection, when using keyboard language different from English or other where position of `KeyS` differs.

2) Exact steps to reproduce this issue
    1) Install app and login
    2) Create empty collection with at least one field
    3) Open create item page to create item in the collection
    4) Change keyboard language to another, where KeyS doesn't matches its position on the keyboard or not exists at all
    5) Try using shortcut for "Save and Stay" (`Ctrl+S`) or "Save and Create New" (`Ctrl+Shift+S`)

3) Environment:
    Directus version: `directus/directus:v9.0.0-rc.24`
    DBMS: `postgres:12`
    Cache: `redis:6`
    Deployment: Docker via `docker-compose.yml` file
    Browsers:
    - Chrome 88.0.4324.150
    - Chrome Mobile 88.0.4324.152

### PR DESCRIPTION
**Pull request by Nitwel**
closes #3621

This now looks like this.
GIF 18 02 2021 14-06-05

### CODE REVIEW

**Comment by benhaynes** [comment]
Thanks @Nitwel — two things...

1. We shouldn't push down all the menus to accommodate that _Close_ button. I think the top/info component should have the "X" instead of the arrow. I just don't think the whole menu can be pushed down when opening.
2. Can you give a bit more insight into why we can't open the first component on auto-open? If you click on an item, that one will always open. So the only time we have the auto-expand is when the App auto-opens the sidebar because the viewport is wide enough. Can't we just add the logic there to open a component if none are already open?

@rijkvanzanten thoughts on these?

**Comment by dimitrov-adrian** [comment]
I like the change. These section are behaving like accordion, but didn't look like it right now, nor links. Now it's clear visible they are sections and the X is for closing the sidebar.

Auto-open first section is good idea too.

**Comment by rijkvanzanten** [comment]
> We shouldn't push down all the menus to accommodate that Close button. I think the top/info component should have the "X" instead of the arrow. I just don't think the whole menu can be pushed down when opening.

Agreed

> Can you give a bit more insight into why we can't open the first component on auto-open? If you click on an item, that one will always open. So the only time we have the auto-expand is when the App auto-opens the sidebar because the viewport is wide enough. Can't we just add the logic there to open a component if none are already open?

@Nitwel The change there would be to extract what the first section is in here, and then set the default on open to the first one instead of `[]`: https://github.com/directus/directus/blob/main/app/src/views/private/components/sidebar-detail-group/sidebar-detail-group.vue#L25

**Comment by Nitwel** [comment]
Just found it a bit inconsistent to have the icon not on the first spot.

**Comment by Nitwel** [comment]
I managed to get this working nicely somehow. Should be ready for review.

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
