### PR TITLE
Fix: GraphQL query fails when using query parameters on a singleton data model

### LINKED ISSUE #15212: GraphQL query fails when using query parameters on a singleton data model
### Describe the Bug

It is currently not possible to use data from a singleton data model as source for an insights dashboard (tested with the metric type).

image

### To Reproduce

- Create a new data model and mark it as singleton
- Create a new dashboard and use any value from this data model

### Errors Shown

```
{"errors":[{"message":"GraphQL validation error.","extensions":{"code":"GRAPHQL_VALIDATION_EXCEPTION","graphqlErrors":[{"message":"Unknown argument \"limit\" on field \"Query.build_status\".","locations":[{"line":1,"column":39}],"path":["query_6df036f1"]}]}}]}
```

Additionally, if a sort-column is set, it will complain about that as well.

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

### PR DESCRIPTION
**Pull request by freekrai**
## Description

If you use query parameters such as filter, limit or sort on singletons in GraphQL, the query will fail since singletons have no arguments assigned to them and so will never pass the Known arguments rule.

There were two options open: 

1. give singletons arguments, which don't make any difference in the call or 
2. parse and remove the arguments before we execute the query.

This PR takes the raw document, checks if the query is on a singleton and parses out the arguments before execution. 

Fixes #15212

## Type of Change

- [X] Bugfix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [X] All tests are passing locally
- [X] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
This seems to crash on my end when using a schema introspection request, like:

```graphql
query IntrospectionQuery {
  __schema {
    queryType {
      name
    }
    mutationType {
      name
    }
    subscriptionType {
      name
    }
    types {
      ...FullType
    }
    directives {
      name
      description

      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description

  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type {
    ...TypeRef
  }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}
```

```
16:13:34 🚨 Cannot read properties of undefined (reading 'singleton')
TypeError: Cannot read properties of undefined (reading 'singleton')
    at GraphQLService.cleanSingletons (/Users/rijkvanzanten/Developer/directus/directus/api/src/services/graphql/index.ts:1463:57)
```

**Comment by rijkvanzanten** [comment]
That being said, I also think that the true solution here is to prevent the illegal GraphQL request to be made from the app, rather than stripping out illegal values from the GraphQL request, and silently return data that wasn't requested. The error shown on the app side is technically expected, as the request that was made to GraphQL is supposed to throw that error. It's the App that currently doesn't properly distinguish between Singletons and regular collections, and therefore allows people to use the regular collection.

We should either prevent singletons from being selected in the `Collection` field for these Insights Panels (easy solution), or (harder solution) update the options to not allow aggregate/sort when using singletons, and ensuring that all other arguments are properly stripped out when the graphql query is compiled app side

(1): CleanShot 2022-08-31 at 16 21 58@2x

(2): 

This is the call made from the app to start creating the GQL request, 

https://github.com/directus/directus/blob/a2425b6be8f28d84096ee845cec9d4bf148c41af/app/src/stores/insights.ts#L167-L184

the actual request is constructed and created here:

https://github.com/directus/directus/blob/a2425b6be8f28d84096ee845cec9d4bf148c41af/app/src/stores/insights.ts#L185-L230

Alternatively, we could also solve it on the Panel level, rather than the Dashboardd level, as that where the illegal queries originate from:

https://github.com/directus/directus/blob/99f38285fd58e7033a9fbb37f161e79f5d735b48/app/src/panels/metric/index.ts#L25-L32

**Comment by freekrai** [comment]
Sure, I'll revisit this from the app side as that makes sense. Will close this PR and open a new one shortly.

**Comment by rijkvanzanten** [comment]
Sweet, thanks! Happy to discuss here or on Discord if you have any questions or run into anything unexpected.

My gut feeling right now is that we want to tackle this in the individual `query()` methods of the panels themselves, as those are source of where the invalid arguments are generated. Doing it on the dashboard level would be a good failsafe, but doesn't necessarily solve the underlying issue 🤔

**Pull request closed without merging**
