### PR TITLE
fix divider not showing/ showing when not needed (drawer-item)

### PR DESCRIPTION
**Pull request by NigmaX**
when all fields of a junction collection are hidden but shown during conditions drawer-item will refer to it as hidden (drawer item is not reactive) and will hide the divider, although it might be shown in a later phase (depends on the condition) 

example: 
divider missing

moving the divider to the v-form and having a new prop (showDivider) will resolve the non-reactive problem and allow the context to be controlled from the outside.

Another thing:
when entering the "drawer-item" it makes more sense to see the collection (junction in this case) on top and the relation on the bottom (the opposite from what it is now), that way if you have extensions to the collection on the junction table it will be shown on top for more easy access. 

example: 
divider on top

SUMMARY

- moving the v-divider from the drawer-item to the v-form 
- adding a new "show-divider" prop to v-form
- changing the order of the forms shown so that the selected collection will be shown before the relation
 

let e know if you have any thoughts regarding this change.
Thanks!

## Type of Change

- [x] Bugfix
- [x] Improvement
- [x] Refactor / codestyle updates
- [ ] New Feature
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [ ] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hi @NigmaX! Thanks for the bug fix 🙂 

Lets undo the "changing the order of the forms shown so that the selected collection will be shown before the relation" part, or at least make it configurable on the interface options for the many to many. I think it's too opinionated to just change that for everybody, without offering a way to keep the current behavior 👍🏻

**Comment by NigmaX** [comment]
@rijkvanzanten changed the form order back for now,
I'll create a separate Pull Request sometime in the future for adding the options to the interface :) 
Thanks!

**Comment by NigmaX** [comment]
Sooo, had some spare time to add this modification, I think it has a great value (at least for our use-case :))
here's a video demonstrating the new option

https://user-images.githubusercontent.com/8597752/180935099-feb2a7b2-ea3d-4449-904a-992c1ed1cea0.mp4

**Comment by rijkvanzanten** [comment]
Awesome @NigmaX! Lets find a slightly more descriptive name/label for that field, and we're all set to merge 🎉 

@benhaynes thoughts on the naming there? TL;DR it's a toggle that controls whether or not the custom fields of the junction table in a m2m show up on the top or bottom of the drawer. The name `Relation First.` feels a tad too generic, as it's not incredibly obvious what the "Relation" is there. Maybe `Junction Fields Location` with a radio/dropdown for `Top` / `Bottom`? 🤔

**Comment by rijkvanzanten** [comment]
A dropdown there would also allow for "off" to flat out hide those fields, which could be a  nice addition in the future

**Comment by benhaynes** [comment]
`Junction Field Location` as a drop-down with those three options seems ideal to me!

**Comment by NigmaX** [comment]
Added, but instead of having "off" option, I added "_hide junction fields_" and "_hide related fields_"
that way we can control which collection to show.

example video. (let me know if you want me to add/remove anything else)

https://user-images.githubusercontent.com/8597752/181172393-18b4e283-ad0d-4b07-991c-eacac7b7446b.mp4

**Comment by rijkvanzanten** [comment]
> that way we can control which collection to show.

I don't think we'll need that actually! If you only want to show the junction items, you should just use a one-to-many interface instead of the many-to-many interface 🙂

**Comment by NigmaX** [comment]
@rijkvanzanten That's a good point!
removed the hide and put off instead (will hide the junction)
Thanks!

**Review by br41nslug — COMMENTED** [review]
Very useful fix and is working great in my tests 😄 But i am not sure if we should have the `Off` feature at all 😬 I don't think it's the relational interfaces responsibility to determine the visibility of it's nested fields. I think having the option to hide potentially required fields on the junction table independent of the field visibility settings can be confusing.

**Comment by NigmaX** [comment]
@br41nslug ill be happy to fix it.
let me know if you want me to remove the "off" option.

**Comment by br41nslug** [comment]
Let's remove it for now so i can merge it 😄 and perhaps open up the discussion for the "Off" setting as an optimization idea to the community/team to see if im wrong on whether it can be confusing.

**Comment by NigmaX** [comment]
@br41nslug Done! 👍 
I removed the "off" option from the dropdown

**Review by br41nslug — APPROVED** [review]

**Pull request merged**
