### PR TITLE
Initial interface of O2M & M2M Table View

### PR DESCRIPTION
**Pull request by u12206050**
O2M Table View

Supports

- [x] search
- [x] sorting
- [x] add new / existing

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Seeing that the setup and logic is so similar, would it be possible / make sense to make this an option of the existing one to many interface? 🤔 Like a toggle to go between a list and a table view

**Comment by u12206050** [comment]
> Seeing that the setup and logic is so similar, would it be possible / make sense to make this an option of the existing one to many interface? 🤔 Like a toggle to go between a list and a table view

Yes actually, although it is the difference between choosing a template vs set of fields.

Is it possible to toggle an option based on another option value?

**Comment by u12206050** [comment]
Done. Love the new approach, also allows for searching now even on list view when more than 1 page

**Comment by u12206050** [comment]
Let me know if you have any other ideas with this. I actually think a miniature tabluar layout view as interface could be the next logical step for really large relationships, or even just for better navigation.

Laravel Nova has this type of layout if you want inspiration.

**Comment by u12206050** [comment]
Might have over done it now but I like it :)
o2m-interface-v3

**Comment by u12206050** [comment]
@rijkvanzanten Done :)

**Comment by Nitwel** [comment]
Looks awesome!

Here my thoughts:
- it would make sense to add these options to all relational multiple interfaces so `files`, `list-m2a`, `list-m2m` and `list-02m` just to make it consistent.
- `limit` -> `items per page` just as the translation
- I'm not sure if we'd want to put the buttons on the top.
- We might wan't to disable search/filtering when only having 1 page to keep it clean.

Other than that I really like it and it is a good enhancement.

**Comment by u12206050** [comment]
> Looks awesome!
> 
> Here my thoughts:
> 
> * it would make sense to add these options to all relational multiple interfaces so `files`, `list-m2a`, `list-m2m` and `list-02m` just to make it consistent.
> * `limit` -> `items per page` just as the translation
> * I'm not sure if we'd want to put the buttons on the top.
> * We might wan't to disable search/filtering when only having 1 page to keep it clean.
> 
> Other than that I really like it and it is a good enhancement.

Good Suggestions:

Search/filtering doesn't show at all if there isn't more than 1 page
I had the buttons at the bottom, but it becomes quite cramped with pagination on slightly smaller screens
I see "Per page" exists, so am using that for now.

Agree with getting the same options on the other interfaces, just not sure how, since for example, 

- [ ] list-m2a isn't a fixed set of fields?
- [ ] list-m2m could work
- [x] this is currently list-o2m

**Comment by LasseRosenow** [comment]
Not sure if you already thought about this and might have some good reasons for why you went for the boolean checkbox, but for what its worth I think a dropdown might be more user friendly here:

image

Especially the "Table or List(default) title is a bit hacky and would not be necessary with a dropdown that just could be set to `List` by default

**Comment by sksar** [comment]
Can the option to hide/show the external link (open the related collection item) be configured to show or hidden?
From what it seems like that if you click on the row, the drawer opens, but if you click the external link icon, then it opens in full.
Can there be an option to basically hide the external link icons? 
Like a toggle: 
- [ ] Show external link

**Comment by u12206050** [comment]
Screenshot 2022-04-21 at 19 17 03

Options added.

O2M & M2M supported.

O2M with many items
Screenshot 2022-04-21 at 19 18 23

M2M with few items
Screenshot 2022-04-21 at 19 18 45

**Comment by sksar** [comment]
This looks good, this looks really good! Wish to have this feature soon @rijkvanzanten

**Comment by LasseRosenow** [comment]
I don't know if its ideal that the `Create New` and `Add Existing` buttons change their location depending on if there is a paginator.

Wouldn't it make more sense to just blend in the paginator within the already free space and keeping the rest as is?

**Comment by u12206050** [comment]
> I don't know if its ideal that the `Create New` and `Add Existing` buttons change their location depending on if there is a paginator.
> 
> Wouldn't it make more sense to just blend in the paginator within the already free space and keeping the rest as is?

Good catch, that was an unintentional side affect of the paginator not showing in that case. Fixing now.

**Comment by u12206050** [comment]
Screenshot 2022-04-21 at 21 37 04

Fixed

**Comment by benhaynes** [comment]
Really excited for this one, thank you for all this great work, @u12206050!! Not being a proper dev myself (to pull this PR and text locally), I'd love an updated MP4 of the latest UX/UI to review. ❤️

**Comment by u12206050** [comment]
RelationshipTableView
@benhaynes Here you go, let me know if you want to look at anything specific

**Comment by benhaynes** [comment]
Thank you!! This is looking great. Could you explain the "link" feature? That is not clear to me.

Also, we might want to get the search/filter bar background consistent with the background (white in this case)... but that's super minor. :)

**Comment by u12206050** [comment]
The link feature is for navigating directly to a related item, whilst keeping the history, ie, when going back you go back to the item.

My experience has been that users tend to navigate through the collection that is easiest to search, and in a heavy relationship based system, it isn't required to update related items within a transaction of initial item.

Another important use case is the fact that the field in a O2M relationship doesn't show up in the side panel when editing. Meaning if I want to change the actual relationship on a related item, I first need to find the ID, go to the collection view, search for the ID, select and then update. Being able to navigate directly greatly increases the UX

Arguably link feature should also be on on the `select-dropdown-m2o` interface, but will leave that for another PR.



In regards to search bar, if it is same as background, which is a bit greyish, wouldn't it seem a bit disabled?

**Comment by LasseRosenow** [comment]
Maybe the greyish background should be white instead. I think its a bit inconsistent with the rest of directus right now, because directus usually does not draw those kind of grey boxes around fields 🤔 Just my two thoughts on that :)

**Comment by u12206050** [comment]
I do agree that it is a bit different.
It is using the `v-sheet` component, and it is to visually group the table with the search. It could be a simple border can accomplish the same affect.

**Comment by benhaynes** [comment]
The background of the search should be white (page background)... I was commenting on the parts under the search icons looking gray, but maybe that's just the GIF compression. Also, I agree with @LasseRosenow that the gray background feels a bit different than the rest of the core app... this should probably just look like the table layout (white on white, see below). I think the search bar will still feel "connected"... though I wonder if there's anything else we can add to that header to make it even more useful. The ability to change/override the default fields?
Screen Shot 2022-04-24 at 9 31 03 AM

**Comment by u12206050** [comment]
What do you think about this @benhaynes ?
Screenshot 2022-04-24 at 15 41 16

**Comment by benhaynes** [comment]
@u12206050 — much better! I've always been cautious about adding borders around fields because when we started doing "groups" it got very complex looking with nested borders. But in this case I think it works really well. 

There's also the added benefit of (potentially) allowing a truncated list and/or scrolling. I also want to be careful about double-scrolling on the page, as I find that cumbersome, but if we do want to truncate we can do a "Show All" button that expands the list. Though, all this might not matter since we allow the user to set the page count.

 When Search is enabled, I'd love to find a way to minimize that header (absolute position the search icon?) or use the top-left space better. Needs some more thought, but I don't have any good ideas for that right now.

Going back to the "link" conversation, could you explain a bit more about why a drawer wouldn't work? Any time you navigate away from a parent item, you'll need to save/discard your edits. Also, the drawer just feels more seamless and expected. That said, I want to add a "Go To Item" action button on all drawers, so if you're looking at an item in a drawer you always have an option to navigate to the full item page. If you don't like the "extra click" to do that, I'm down to always have a right-click context menu on the interface rows (very implicit)... or a dedicated "..." (`more_vert`) icon that opens the same "more actions" context menu. In short, I like the idea of having one main row click action (open in drawer), one row icon (delete), and then grouping all other actions in a context menu. This keep the UI clean.

Also, I usually prefer the `launch` icon for navigating to things, it removes the confusion the `link` icon has with URLs.

In any event, this is all looking awesome! ❤️

**Comment by u12206050** [comment]
Screenshot 2022-04-24 at 16 49 30

What about this? Looks more similar than the tabular collection view, except for the extra select existing button
@benhaynes

**Comment by u12206050** [comment]
In regards to the link, in your reasoning a "Go to item" will also have the same issues with discarding changes in the parent item. Although in both cases either way a modal will pop up alerting you as such:

DiscardPrompt

As mentioned, the main reason is for ease of navigation. Since Directus doesn't have Item view, but only Item detail, then it is sort of the only way to navigate, especially on on "children" collections that might be hidden, except when navigated to via their parent collection.

**Comment by benhaynes** [comment]
> What about this? Looks more similar than the tabular collection view, except for the extra "Add Existing" button

Interesting! This is very similar to the listing page... but would be quite different from the other interfaces. I'd like to hear what @rijkvanzanten thinks, but if we _were_ to go with this direction, I would want to make the "select existing" as a circular secondary action button left of the primary "add" button. But I'm not 100% on this direction yet. 🤔 

> In regards to the link, in your reasoning a "Go to item" will also have the same issues with discarding changes in the parent item. 

Correct. I was just saying that I think using it as navigation is a secondary feature (for most users), but I could be wrong. I'm fine keeping the feature, but think it should be one level removed (under a context menu). We should get @rijkvanzanten's feedback on this too.

> Since Directus doesn't have Item view, but only Item detail

What do you mean by this?

Also, curious if these column widths are draggable (like the layout) or not.

**Comment by u12206050** [comment]
> > Since Directus doesn't have Item view, but only Item detail **Meant Item Edit**
> 
> What do you mean by this?

In other admin platforms (for example Laravel Nova) you have three views; Collection, Item Detail, Item Edit.

The item detail displays the values without any inputs, here is an example:

Item Detail

This is the Post Detail, which has many comments, displayed as a tabular layout.

**Comment by u12206050** [comment]
@benhaynes What do you think about changing the launch icon out for the edit icon, which opens in the drawer? Then using the launch icon to link to the item?

**Comment by benhaynes** [comment]
> What do you think about changing the launch icon out for the edit icon, which opens in the drawer? Then using the launch icon to link to the item?

I still question how often that would be used by the broader userbase (as a primary action), versus deprioritizing it as an option in the context menu. Also, I don't think the "open in drawer" action needs an icon, I feel like that is the default row click, right?

CC @rijkvanzanten

**Comment by u12206050** [comment]
> open in drawe

Yes, in this version the default click opens the drawer.
We have a case that updates can not be made on the parent collection, but can be made on child collection items, however with the drawer the update isn't made unless you save the parent collection, forcing us to give explicit access on the parent collection on that specific alias that contains the relation.

There is also this issue #12881 that is currently not allowing us to deploy 9.9.1 due to our clients not being able to update any child relationships through the parent, although when navigating directly to the child updates do work.

Besides these reasons, it is still an option that can be toggled though.

**Comment by koksikus** [comment]
I think this is a great solution - clean, simple and significantly improves the data display process.  I look forward to releasing this.

**Comment by sksar** [comment]
> Screenshot 2022-04-24 at 16 49 30
> 
> What about this? Looks more similar than the tabular collection view, except for the extra "Add Existing" button @benhaynes

@u12206050 
The add existing button looks a little out of place.

How about when the + button is clicked a dropdown appears, asking to "Create New" or "Add Existing"?
And if out of the two buttons is disabled then the + button would directly open the only available function.

**Comment by benhaynes** [comment]
> The add existing button looks a little out of place. How about when the + button is clicked a dropdown appears, asking to "Create New" or "Add Existing"? And if out of the two buttons is disabled then the + button would directly open the only available function.

If we were to go with this direction, then the "Select Existing" would be an action button (round, secondary button beside "Add New". However, this approach is very different form the other relational interface buttons. Currently, we don't use the round action buttons anywhere but in the header... so I'm conflicted.

**Comment by sksar** [comment]
> > The add existing button looks a little out of place. How about when the + button is clicked a dropdown appears, asking to "Create New" or "Add Existing"? And if out of the two buttons is disabled then the + button would directly open the only available function.
> 
> If we were to go with this direction, then the "Select Existing" would be an action button (round, secondary button beside "Add New". However, this approach is very different from the other relational interface buttons. Currently, we don't use the round action buttons anywhere but in the header... so I'm conflicted.

So can we go with like two round buttons? 
I believe "create new" and "add existing" should be closer together rather than far apart.

**Comment by benhaynes** [comment]
> So can we go with like two round buttons? I believe "create new" and "add existing" should be closer together rather than far apart.

As I said, that recommendation is based on this direction... but I don't think that is a consistent approach with the other relational interfaces. **The following works nicely:**
164979349-c878c02f-8343-4498-85b8-5a47f263c7e2

**However, we need a better way to include search/filter, as this feels awkward:**
164979389-d232cfd1-87bf-4c10-b9e7-776103bdd637

The solution from @u12206050 (use the header buttons) was great in isolation but doesn't match any other design patterns in the system. I propose we remove the border outline (the last row has a bottom line that gets doubled up, and I just don't think it's needed), and find a way to absolute position a search/filter button.

I'm open to other suggestions. This is a tough one... but it's _so_ close!

**Comment by sksar** [comment]
@benhaynes Yeah I am fine with this one. This looks very consistent, to what is currently the O2M interface.

**Comment by benhaynes** [comment]
> How about we remove the border altogether. And try to make the heading "Things" and the "Search" on the same line.

That's not how interfaces work right now. The field label area above is not within their access... @rijkvanzanten can correct my if I'm wrong.

**Comment by sksar** [comment]
> > How about we remove the border altogether. And try to make the heading "Things" and the "Search" on the same line.
> 
> That's not how interfaces work right now. The field label area above is not within their access... @rijkvanzanten can correct my if I'm wrong.

Yes, I am aware of that.

**Comment by u12206050** [comment]
So a few notes. Personally I like having the "Create new" and "Add existing" buttons at the top of a possible long list of items. The only thing I want to see when I scroll down is pagination by the time I am at the bottom.

I understand the concept of not wanting to break out of the design system, although it is new interface that shares a lot of similarities with the collection tabular view, why wouldn't we want also share the same layout and feeling then just because it is further down the page. It isn't as if there is any other round buttons on the detail page.

Will remove the border and seems like there are a few code conflicts that need to be fixed.

**Comment by u12206050** [comment]
### With vs without border (VIEW ONLY):

Screenshot 2022-05-05 at 11 04 50
With border, fits in nicely with surroundings


Screenshot 2022-05-05 at 11 06 31
Without border, seems loose and not tied together.


### LONG LIST WITH MANAGE


Screenshot 2022-05-05 at 11 09 37
With border

Screenshot 2022-05-05 at 11 09 05
Without border

**Comment by u12206050** [comment]
What do you think about this for add existing? @benhaynes 

Screenshot 2022-05-05 at 11 30 03

**Comment by u12206050** [comment]
Think this is a winner?

Screenshot 2022-05-05 at 11 33 49

**Comment by LasseRosenow** [comment]
What about putting the old `Creat New` and `Add Existing` buttons to the top left instead of the circles on the right? I think the space should be sufficient

**Comment by u12206050** [comment]
> 

On smaller devices once the search bar opens then there isn't enough space.

Think the icons are very self explanatory and neat. I know it is a bit of a break, but is that really a bad thing? We could use secondary color perhaps?

**Comment by benhaynes** [comment]
Great work @u12206050 — you've convinced me! Let me add some thoughts below, and we'll see if we can get this buttoned-up.

* For the "Select Existing" button, let's use the same _secondary_ style we do on the Layouts. It's more subdued, and we should be consistent with only one primary action.
* Is the header fixed, scrolling, or do we not have _internal_ scrolling within the interface? My preference is to avoid the nested scrolling whenever possible
* Is there a way (in the interface or options) to control the setup for this layout? I know you allowed adding and reordering fields, but we can't control column width, right?
* Also, any thoughts on enabling other Layouts here? I know this PR is all about the Table-mode, but we have so many layouts, and this new direction (border-contained table with round action buttons) just _feels_ like it should have all the power of the Layouts. Could be really interesting to have media (cards), maps, calendars, etc used for showing the relational data. Maybe there's a way to reuse the config from those too, for the above column width and other setup. Just thinking out loud, I know this is a much bigger/different scope.
* Another random idea, to fill that top-left gap in the header, can you (or anyone else) think of anything that would work there? It could be an option to control some heading, or we could pull in other dynamic info automatically. It could be the collection you're linking to, or the collection's icon, etc. 🤔 

Specific to this image...
166893099-a8e64474-0ad8-4d8b-a2ed-0afd7b7b04e3

* Since I agree that the border looks better, can we add some logic to avoid the bottom row border when there's no pagination (to avoid that double-border)? To me, it makes it look like the list continues and I should scroll... which is not the case.
* I don't think that whole large header is justifiable for the item count, can we collapse that when readonly or permissions remove those buttons? Does search/filter still exist there when there's pagination? This is the main issue I have with this direction... that big gap just feels so unconsidered.


Again, awesome work!! Sorry for all the back and forth. :)

**Comment by sksar** [comment]
> * Another random idea, to fill that top-left gap in the header, can you (or anyone else) think of anything that would work there? It could be an option to control some heading, or we could pull in other dynamic info automatically. It could be the collection you're linking to, or the collection's icon, etc.

@benhaynes @u12206050 
How about some stats like info. Instead of the "5 items" text, how about in the options it could be like a display template, and the user could put in anything the user would want. 

For example such as: 
`"{count} products under {product->category->name}. Click + to add more."`

Something like that. Count, Sum, Avg simple stuff like that.

**Comment by u12206050** [comment]
@benhaynes 

The header is not fixed, so there is no internal scolling.

I agree with the double border issue. It has been bothering me as well, although I can't remove it without some `!important` css override. I will investigate a bit more to see if I can solve that and the `items` count when only in display mode.

@sksar Both you and Ben are mention good ideas that I have also thought about and would love to implement, although I think this PR is a big enough already, so just want to get it in first.

**Comment by benhaynes** [comment]
> How about some stats like info. Instead of the "5 items" text, how about in the options it could be like a display template, and the user could put in anything the user would want.

An interesting idea, but I don't know if we have support for our aggregators (etc) in the template strings yet. Also, **width** is a big concern here, that example you gave would certainly be too long... so we would need to really think about how to limit characters (including dynamic ones).

> I agree with the double border issue. It has been bothering me as well, although I can't remove it without some !important css override. I will investigate a bit more to see if I can solve that and the items count when only in display mode.

Perfect... small change, but big UI improvement.

> @sksar Both you and Ben are mention good ideas that I have also thought about and would love to implement, although I think this PR is a big enough already, so just want to get it in first.

Absolutely! We're fast escaping MVP territory... and most things can be future improvements. The only reason I raised the question about "all layouts" is because that's a more fundamental question. But as long as it won't be a breaking change to enable other layouts later, let's put a pin in that.

**Comment by sksar** [comment]
@u12206050 
Suggestion: Normal color for the (Add New), and subdued / greyish color for the (Add existing). 
Then I guess it would be consistent with the rest of the UI.

PS: Drop a preview image here of how that looks.

**Comment by sksar** [comment]
@u12206050 @benhaynes 
I just noticed something, since this is a table view, shouldn't there be an option for choosing the row height,
between the options of "Compact", "Cozy", and "Comfortable" ?

I do not see those options.

@u12206050 maybe you can add that. 😄

Amazing work, by the way.

**Comment by u12206050** [comment]
@sksar 

Screenshot 2022-05-08 at 08 44 25

**Comment by u12206050** [comment]
@benhaynes @sksar  Random idea, total breaks from the normal view, but utilises the space a bit better?

I kinda like it, but am totally ready for it to be shot down 😆 

Screenshot 2022-05-08 at 08 46 11

**Comment by sksar** [comment]
> @benhaynes @sksar Random idea, total breaks from the normal view, but utilises the space a bit better?
> 
> I kinda like it, but am totally ready for it to be shot down 😆
> 
> Screenshot 2022-05-08 at 08 46 11

Feels weird. Especially when you can set the interface as fill width and it fills the entire width, it will look weird.
However the text "1-10 of 198 items" is perfect. And can stay on the left. Would look good. Just the search bar in the center is a bit weird.
Can you just make the text left.

**Comment by u12206050** [comment]
Looks good, also thinking of removing the "limit" option in the interface setup, and just have the per page option as it is in tabular view, bottom right.

Screenshot 2022-05-08 at 09 00 13

**Comment by sksar** [comment]
> Looks good, also thinking of removing the "limit" option in the interface setup, and just have the per page option as it is in tabular view, bottom right.
> 
> Screenshot 2022-05-08 at 09 00 13

Perfect. This is it! I'm sold!
This is the one!!
I hope @benhaynes will like it.

Now if we could just compact the rows, and choose between the three options as I mentioned earlier.

**Comment by sksar** [comment]
> also thinking of removing the "limit" option in the interface setup, and just have the per page option as it is in tabular view, bottom right.

You can remove the limit, but keep it as a default option. So it would default to what is set in the option.
If the user refreshes then it would go back to the default every time.

**Comment by u12206050** [comment]
There you go, replaced limit with table spacing option when table layout is selected.

Screenshot 2022-05-08 at 09 22 04

Screenshot 2022-05-08 at 09 22 27

**Comment by u12206050** [comment]
Screenshot 2022-05-08 at 09 28 37

Without double border.

**Comment by sksar** [comment]
@u12206050  Perfecto. Can you share a compact size screenshot too?

**Comment by sksar** [comment]
@u12206050 I believe you can keep the per page option. But do not treat that as a limit, rather treat that as default. So it would every time default to that one if set. But the user still can change it on the view itself, but that would be just temporary. If the user refreshes the page or navigates out it will revert back to the default.
What do you think of this approach?

<hr>

Another thing maybe you could do is, give an option to either have the border or remove the border. In my case, I can think of many instances where it would work better WITH a border, and also many cases where it would work better WITHOUT a border.

<hr>

Also in many cases, I would just make it read-only, so does it hide the add buttons?
Also, can we have an option to just hide the header bar completely?
Like in this image:


> Screenshot 2022-04-24 at 15 41 16

So that, it would hide everything, including the searching and filtering, Add buttons, and also the "1-10 of 15 items" text as well. Completely.

<hr>

I believe these changes would make it very very flexible.

What do you guys say? @u12206050 @benhaynes

**Comment by u12206050** [comment]
@sksar Testing out edge cases and realised there is a bug with the append cell not showing with more columns, it gets squished. Fixed the bug, but also playing around with setting it to sticky. What do you think?
Screenshot 2022-05-08 at 10 05 35

**Comment by sksar** [comment]
> What do you think?

Looks okay, however, there should be a clear separation between the content and the cross button, like maybe you can play with the left-border width on the sticky.

Also, what do you think about my above suggestions?
Maybe we can discuss further on those, here or on discord.

**Comment by u12206050** [comment]
Screenshot 2022-05-08 at 10 12 07

Compact is broken, seems bit broken on normal collection view as well:
Screenshot 2022-05-08 at 10 12 40

**Comment by u12206050** [comment]
**Recap**
Default list layout 

Screenshot 2022-05-08 at 14 39 00

Table view with search and links enabled.

Screenshot 2022-05-08 at 14 49 52

**Comment by benhaynes** [comment]
Great conversation! A few points:

* I see a bunch of screenshots with different things, but to be clear: when there is no pagination, there should be no bottom border on the last row. When there IS pagination, then we should include the last row border to separate them.
* I still think the counts should go where they are normally (besides search) and we should add the icon for the related collection in the top left.
* Since page count is ephemeral, I agree that the _default_ should be set in the options, but allow override in the normal dropdown in the bottom-right.
* I think there's a border beside the row action items on the right. All borders should use the global variable... so in this default case, they should be 2px.
* I think the "compact cropping" is a known issue that has a PR fix already.
* Question: does this interface allow for sorting by clicking on the headers?
* Question: Does this interface allow for reordering (drag and drop) until there are multiple pages? You should be able to increase the page count to get around this too.
* I think we need to revisit the repeater style (non-table), as that is looking odd without a border keeping it connected with the search and action buttons.

Other than the last point on the repeater, all of this should be simple tweaks. Hopefully we can get this aligned before this Thursday's release so we can get this out there! Thank you again, @u12206050!!! ❤️

**Comment by u12206050** [comment]
@benhaynes 

Some points in response

- I see a bunch of screenshots with different things, but to be clear: when there is no pagination, there should be no bottom border on the last row. When there IS pagination, then we should include the last row border to separate them.
  **Implemented, although this is really just a case for <10 items**
- I still think the counts should go where they are normally (besides search) and we should add the icon for the related collection in the top left.
  **Wouldn't it look weird having the label right above with the icon below?**
- Since page count is ephemeral, I agree that the default should be set in the options, but allow override in the normal dropdown in the bottom-right.
  **We actually removed setting a default (10) in the options, in favour of adding the table spacing option. Should I add it back?**
- I think there's a border beside the row action items on the right. All borders should use the global variable... so in this default case, they should be 2px.
  **I actually thought it looked better being the same width as the row borders? 2px suddenly makes it stand out a lot more than needed, but I concur to you the final decision.**
- I think the "compact cropping" is a known issue that has a PR fix already.
  **Ignoring then**
- Question: does this interface allow for sorting by clicking on the headers?
  **Yes sorting works**
- Question: Does this interface allow for reordering (drag and drop) until there are multiple pages? You should be able to increase the page count to get around this too.
  **No, table doesn't support drag and drop, so if you want sorting functionality you would need to use list layout.**
- I think we need to revisit the repeater style (non-table), as that is looking odd without a border keeping it connected with the search and action buttons.
  **As explained to sksar, in the list layout, each item technically has its own border, so it gives a different kind of feel as opposed to the table which has light top and bottom borders per row.**

**Comment by u12206050** [comment]
Updated to work as half-width

Screenshot 2022-05-09 at 21 35 47

Also added some logic to auto calculate column widths. Although only time will tell if the logic works. So far it seems to be fine.

Screenshot 2022-05-09 at 21 36 38

Other updates as mentioned above are are done.

**Comment by benhaynes** [comment]
> Implemented, although this is really just a case for <10 items

Well, wouldn't it be for any lists less than `page count`... which could be way more?

> We actually removed setting a default (10) in the options, in favour of adding the table spacing option. Should I add it back?

I think it's a nice feature to have, but is also pretty specific. We could add it as an Advanced Option too.

> Wouldn't it look weird having the label right above with the icon below?

I don't think so, but I see your point.

> No, table doesn't support drag and drop, so if you want sorting functionality you would need to use list layout.

Any reason for this? The `v-table` component and relationship setup both support this.

> As explained to sksar, in the list layout, each item technically has its own border, so it gives a different kind of feel as opposed to the table which has light top and bottom borders per row.

Hmm, let's see what @rijkvanzanten thinks... haven't had any feedback from him yet.

--

Would it be possible to only show the vertical border beside the row buttons if the other columns extend beyond and force scrolling? We don't have vertical lines anywhere else in the system, so I'd prefer to only show them if needed.

**Comment by u12206050** [comment]
> > Implemented, although this is really just a case for <10 items

> Well, wouldn't it be for any lists less than page count... which could be way more?

Right, however since this is an actual collection view, the page count dynamically adjusts according to the amount of filtered results. I could also not choose pages as the toggle, since if you choose a high limit of 100items then there might not be any pages and thus it would hide, but then so would the "per page" interface also, which is not wanted.

> > No, table doesn't support drag and drop, so if you want sorting functionality you would need to use list layout.

> Any reason for this? The v-table component and relationship setup both support this.

I can try to implement it before Thursday, but I am really not sure how well it will work, since I can't find another example for it.


In regards to the vertical border:

1.  There is always going to be a first time a design element is new, and can feel like it "breaks" with existing design system
2.  There are also other options, such as subdued background color instead of border.
3.  It is quite hard to detect consistently if there are overflowing columns in order to toggle the border.

**Comment by u12206050** [comment]
Just realised that drag and drop sorting would mean we can't sort by columns. 
For some it would mean more to sort by columns, whereas for others it should always be sorted by the sort key.

Also sorting doesn't work if the sorting field isn't included in the set of fields to fetch.

Conclusion, leaving this as is and open a new issue and PR to include support for drag and drop support to a sortable table layout. @benhaynes  you agree?

**Comment by benhaynes** [comment]
In regards to sorting, we can leave it out for an MVP, but it will need to be supported eventually. It should work the same as on the table Layout:

* If you have a sort column configured (and results fit on one page) then the drag handles show
* Sorting is disabled until you order by the sort column (just like on the Layout) so you get both order and sort

Again, we'll have to wait until @rijkvanzanten has time to review all this, since I'm not as deep on the technical side.

**Comment by sksar** [comment]
@u12206050 @benhaynes 
Any updates on this?
When is this expected to get merged ?
I hope very soon.

**Comment by koksikus** [comment]
Many people ask me about this solution, not knowing it already exists. The way to display the list in Directus is great, but when the list is expanding and you need to find something in it, this solution is perfect. 
Since we have been waiting for a new release for so long 😉, we should now get this solution as a reward for patience 🤪

**Comment by u12206050** [comment]
I'm waiting just as eagerly for this. Seems though that the Directus team is very busy as of late, I have about 3 PRs with more coming, but the rollout timeline is quite slow. @benhaynes Maybe there is someway to improve PRs being merged in, since it can really contribute greatly to an open source project.

**Comment by goggi** [comment]
I'm loving this new feature!! Played around a bit with it and have 2 comments.

1. Sort icon is available on columns with data type JSON. But the following error pops up when pressing it: 
image
Maybe remove the sorting icon when it's not available

2. Is there any way to resize the columns? 
image

**Comment by benhaynes** [comment]
> Seems though that the Directus team is very busy as of late

Quite busy, and some key members have been out sick (some with COVID). So it was a slow week... but we're ramping back up now and will give this more attention! ❤️

**Comment by u12206050** [comment]
> I'm loving this new feature!! Played around a bit with it and have 2 comments.
> 
> 1. Sort icon is available on columns with data type JSON. But the following error pops up when pressing it:
>    image
>    Maybe remove the sorting icon when it's not available
> 2. Is there any way to resize the columns?
>    image

Thanks for the test, hope to get some time soon.

**Comment by u12206050** [comment]
@rijkvanzanten Hows it looking with this PR?

**Comment by koksikus** [comment]
Good question! 😉

**Comment by u12206050** [comment]
@rijkvanzanten Let me know if you want to get on a call and go through it if you are wondering about some stuff.

Also, don't know if it helps, but I edited the interface files side by side so that most of the code is the as much the same as possible, so might help reviewing them side by side as well? Good luck :)

**Review by azrikahar — CHANGES_REQUESTED** [review]
Granted I'd still wish to do an additional pass and test it out even more just to err on the side of caution, but let's make sure to use translation keys for the new fields in `list-m2m` and `list-o2m` (name, choice text, label etc) 👍

Thanks again for the great PR!

**Comment by u12206050** [comment]
> Granted I'd still wish to do an additional pass and test it out even more just to err on the side of caution, but let's make sure to use translation keys for the new fields in `list-m2m` and `list-o2m` (name, choice text, label etc) 👍
> 
> Thanks again for the great PR!

Do I just replace the static strings with `$t:word` or do I also have to add the `word` + translation somewhere? How do I do that if yes?

**Comment by u12206050** [comment]
Ok, pushed now, let me know if I needed to do it differently.

**Comment by azrikahar** [comment]
@u12206050 Thanks for pushing the changes 👍 added a few minor tweaks as well. Just a few final questions in general:

- Just to confirm, the enableSearchFilter option also be hidden if it's not table layout?

- @benhaynes understandably the `link` and `close`/`remove` icons are pretty self-explanatory, but I assume we should still add tooltip to these? If yes, what should they be called (particularly the link)? 🤔 `View Item` might not be apt as we can "view" it in drawer when clicking on the row already, so maybe something like `Navigate to this item`?

   chrome_ZZ2bdNWRoU

**Comment by benhaynes** [comment]
@azrikahar 

* I think the "Navigate" icon/button should be optional, and off by default. I don't think this adds enough new functionality (beyond clicking to open in a drawer) to have on by default. I also feel that the `launch` icon is more appropriate here (instead of link), and agree that the tooltip should be `Navigate to Item`.
* The tooltip for remove should be `Remove Item`, but I also noticed a trash icon in earlier screenshots, and would like to understand if these are both used... and how. Essentially, if we are _disconnecting_ the item, then we say `Remove Item`, but if we are deleting the relational item we should use the tooltip `Delete Item`.

**Comment by u12206050** [comment]
How do I sponser this PR to get it merged? Or do I just start sponser the entire Directus Project? :)

**Comment by rijkvanzanten** [comment]
> How do I sponser this PR to get it merged? Or do I just start sponser the entire Directus Project? :)

https://directus.io/contact/ gets you in touch with the right team immediately 🙂

**Comment by mark-james** [comment]
Hi @u12206050, how easy would it be to turn this interface into an extension?

**Comment by u12206050** [comment]
@mark-james currently it isn't too easy. As I would have then created it quite a while back. So I am also eagerly awaiting it being merged.

**Review by licitdev — COMMENTED** [review]
The table view works well in M2M! 👍 
However there are some glitches for O2M, as shown in the video below. 🤔 Might be existing issues within the O2M interface.

https://user-images.githubusercontent.com/26413686/185446923-75d7aa28-aeb3-4143-91b0-a3f2c5b62983.mov

https://user-images.githubusercontent.com/26413686/185446970-47339251-94da-4d91-b17f-02299af70150.mov

**Comment by azrikahar** [comment]
> The table view works well in M2M! 👍 However there are some glitches for O2M, as shown in the video below. 🤔 Might be existing issues within the O2M interface.

I believe it's related to existing O2M issues such as #15120 and #13537, though now it seems to not be exactly the same with them in this PR, so I think we'll need to investigate said issues first. 👍

**Comment by u12206050** [comment]
@azrikahar Don't you think those issues would be fixed outside of this PR, and thus that this PR could be merged none the less?

**Review by azrikahar — APPROVED** [review]

**Pull request merged**
