### PR TITLE
Added bookmarks support for users admin module

### PR DESCRIPTION
**Pull request by vnmtvlv**
## Description
There was a feature request from my clients to add bookmarks for users module, to separate users by subscription type.

Inside UserNavigation component reused component:
import NavigationBookmark from '@/modules/content/components/navigation-bookmark.vue';
Added prop there to go to another route.

Copied all bookmark related code from here: app/src/modules/content/routes/collection.vue

## Type of Change

- [ ] Bugfix
- [x] Improvement
- [ ] New Feature
- [ ] Refactor / codestyle updates
- [ ] Other, please describe:

## Requirements Checklist

- [ ] New / updated tests are included
- [ ] All tests are passing locally
- [x] Performed a self-review of the submitted code

If adding a new feature:

- [ ] Documentation was added/updated

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I'm wondering if there's a good way to make the `useBookmarks()` composable and template part reusable between the three `collection.vue` pages 🤔 It looks like the underlying setup should be the same across all of them

**Comment by j0hnfl0w** [comment]
Yep, there is a lot of code copy pasted (

**Comment by rijkvanzanten** [comment]
> Yep, there is a lot of code copy pasted (

Lets try to clean that up a little bit before merging this through then 🙂

**Comment by rijkvanzanten** [comment]
Heya, thanks for your PR! Our small team has been attempting to work through a backlog of external contributions for the better part of a year, but in that time many have become too stale to merge or the change is no longer desired/relevant.. 
We've updated the [contributing guidelines](https://github.com/directus/directus/blob/main/contributing.md#pull-requests) and are working on [making more resources available](https://github.com/directus/directus/discussions/17977) to make sure that doesn’t happen again 😬 In the meantime, we'll have to close this PR for now..

**Pull request closed without merging**
