### PR TITLE
Remove misleading contents migration docs for now

### LINKED ISSUE #18067: Applying snapshot is a destructive behaviour when you have custom migrations
### Describe the Bug

If you have a custom migration that changes a field type from string (255) to text and it's applied after the snapshot, on container restart, data gets lost as the migration change is reverted.

This follows the guidelines outlined in the [docs](https://docs.directus.io/extensions/migrations.html#migrations-and-directus-schema):

> 
> 1 npx directus database install
> 2 npx directus database migrate:latest
> 3 npx directus schema apply ./path/to/snapshot.yaml
> 4 mv .custom-migrations/* migrations/
> 5 npx directus database migrate:latest

### To Reproduce

1. Create a collection called Images
2. Create a field called `description` as type string (255 length)
3. Save the schema and apply it in the order of the docs (above).
4. Create a custom migration to change `description` type from `string` to `text`
5. Create new data for description with > 255 length
6. Restart contianer

Expected:
Snapshot changes not be descrutive.

Actual: snapshot change is destructive and text gets truncated to 255.

### Hosting Strategy

Self-Hosted (Docker Image)

### PR DESCRIPTION
**Pull request by paescuj**
Closes #18067

### CODE REVIEW

**Comment by abdonrd** [comment]
And there is no recommended alternative? Thanks!

**Comment by paescuj** [comment]
> And there is no recommended alternative? Thanks!

I'm afraid there's no alternative we can officially recommend at the moment.

**Review by rijkvanzanten — APPROVED** [review]
Unfortunate as it is, this is definitely one of those cases where no information is better than the wrong information

**Comment by abdonrd** [comment]
Thanks both!

**Comment by rijkvanzanten** [comment]
@abdonrd I'd really like to hear your thoughts on https://github.com/directus/directus/discussions/17495 and https://github.com/directus/directus/discussions/13041 🙂 This is a topic of high-interest, but also one that's incredibly finicky in the number of edge cases and approaches.

**Pull request merged**
